/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.internal.rest.auth;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyInt;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.security.Principal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Optional;

import org.eclipse.kura.audit.AuditConstants;
import org.eclipse.kura.audit.AuditContext;
import org.eclipse.kura.internal.rest.auth.RestSessionHelper.XsrfTokenStatus;
import org.eclipse.kura.internal.rest.provider.RestServiceOptions;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpSession;
import jakarta.ws.rs.container.ContainerRequestContext;
import jakarta.ws.rs.core.PathSegment;
import jakarta.ws.rs.core.UriInfo;

public class SessionAuthProviderTest {

    private static final String IDENTITY_NAME = "foo";
    private static final String XSRF_TOKEN_PATH = "/session/v1/xsrfToken";
    private static final String CHANGE_PASSWORD_PATH = "/session/v1/changePassword";
    private static final String RESOURCE_PATH = "/requireAssets";

    private final RestSessionHelper sessionHelper = mock(RestSessionHelper.class);
    private final HttpServletRequest request = mock(HttpServletRequest.class);
    private final HttpSession session = mock(HttpSession.class);
    private final ContainerRequestContext requestContext = mock(ContainerRequestContext.class);
    private final UriInfo uriInfo = mock(UriInfo.class);

    private final Map<String, String> auditProperties = new HashMap<>();
    private AuditContext.Scope auditScope;

    private SessionAuthProvider provider;
    private Optional<Principal> result;

    @Before
    public void setup() {
        this.auditScope = AuditContext.openScope(new AuditContext(this.auditProperties));

        when(this.requestContext.getUriInfo()).thenReturn(this.uriInfo);
        when(this.session.getId()).thenReturn("sessionId");

        this.provider = new SessionAuthProvider(this.sessionHelper,
                new HashSet<>(Arrays.asList(CHANGE_PASSWORD_PATH, XSRF_TOKEN_PATH)),
                Collections.singleton(XSRF_TOKEN_PATH));
        this.provider.setOptions(new RestServiceOptions(Collections.emptyMap()));

        givenRequestPath(RESOURCE_PATH);
    }

    @After
    public void teardown() {
        this.auditScope.close();
    }

    @Test
    public void shouldNotAuthenticateIfSessionIsNotPresent() {
        givenNoSession();

        whenAuthenticateIsCalled();

        thenRequestIsNotAuthenticated();
        thenAuditContextDoesNotReportIdentity();
    }

    @Test
    public void shouldNotAuthenticateIfSessionDoesNotContainIdentity() {
        givenSessionWithoutIdentity();

        whenAuthenticateIsCalled();

        thenRequestIsNotAuthenticated();
        thenAuditContextDoesNotReportIdentity();
    }

    @Test
    public void shouldAuthenticateIfXsrfTokenIsValid() {
        givenAuthenticatedSession();
        givenXsrfTokenStatus(XsrfTokenStatus.VALID);

        whenAuthenticateIsCalled();

        thenRequestIsAuthenticatedAs(IDENTITY_NAME);
        thenSessionLastActivityIsUpdated();
    }

    @Test
    public void shouldSkipAuthenticationIfXsrfTokenIsMissing() {
        givenAuthenticatedSession();
        givenXsrfTokenStatus(XsrfTokenStatus.MISSING);

        whenAuthenticateIsCalled();

        thenRequestIsNotAuthenticated();
        thenAuditContextDoesNotReportIdentity();
        thenSessionValidityIsNotChecked();
    }

    @Test
    public void shouldNotAuthenticateIfXsrfTokenIsInvalid() {
        givenAuthenticatedSession();
        givenXsrfTokenStatus(XsrfTokenStatus.INVALID);

        whenAuthenticateIsCalled();

        thenRequestIsNotAuthenticated();
        thenAuditContextReportsIdentity(IDENTITY_NAME);
        thenSessionValidityIsNotChecked();
    }

    @Test
    public void shouldAuthenticateWithoutXsrfTokenOnAllowedPath() {
        givenAuthenticatedSession();
        givenRequestPath(XSRF_TOKEN_PATH);

        whenAuthenticateIsCalled();

        thenRequestIsAuthenticatedAs(IDENTITY_NAME);
        thenXsrfTokenIsNotChecked();
    }

    @Test
    public void shouldNotAuthenticateIfSessionIsExpired() {
        givenAuthenticatedSession();
        givenXsrfTokenStatus(XsrfTokenStatus.VALID);
        givenExpiredSession();

        whenAuthenticateIsCalled();

        thenRequestIsNotAuthenticated();
        thenAuditContextReportsIdentity(IDENTITY_NAME);
    }

    @Test
    public void shouldNotAuthenticateIfSessionIsLocked() {
        givenAuthenticatedSession();
        givenXsrfTokenStatus(XsrfTokenStatus.VALID);
        givenLockedSession();

        whenAuthenticateIsCalled();

        thenRequestIsNotAuthenticated();
        thenAuditContextReportsIdentity(IDENTITY_NAME);
    }

    @Test
    public void shouldAuthenticateIfSessionIsLockedAndPathIsAllowed() {
        givenAuthenticatedSession();
        givenXsrfTokenStatus(XsrfTokenStatus.VALID);
        givenLockedSession();
        givenRequestPath(CHANGE_PASSWORD_PATH);

        whenAuthenticateIsCalled();

        thenRequestIsAuthenticatedAs(IDENTITY_NAME);
    }

    @Test
    public void shouldNotAuthenticateIfCredentialsChanged() {
        givenAuthenticatedSession();
        givenXsrfTokenStatus(XsrfTokenStatus.VALID);
        givenChangedCredentials();

        whenAuthenticateIsCalled();

        thenRequestIsNotAuthenticated();
        thenAuditContextReportsIdentity(IDENTITY_NAME);
    }

    private void givenNoSession() {
        when(this.sessionHelper.getExistingSession(this.request)).thenReturn(Optional.empty());
    }

    private void givenSessionWithoutIdentity() {
        when(this.sessionHelper.getExistingSession(this.request)).thenReturn(Optional.of(this.session));
        when(this.sessionHelper.getPrincipalFromSession(this.session)).thenReturn(Optional.empty());
    }

    private void givenAuthenticatedSession() {
        when(this.sessionHelper.getExistingSession(this.request)).thenReturn(Optional.of(this.session));
        when(this.sessionHelper.getPrincipalFromSession(this.session))
                .thenReturn(Optional.of(() -> IDENTITY_NAME));
    }

    private void givenXsrfTokenStatus(final XsrfTokenStatus status) {
        when(this.sessionHelper.getXsrfTokenStatus(this.request)).thenReturn(status);
    }

    private void givenExpiredSession() {
        when(this.sessionHelper.isSessionExpired(any(HttpSession.class), anyInt())).thenReturn(true);
    }

    private void givenLockedSession() {
        when(this.sessionHelper.isSessionLocked(this.session)).thenReturn(true);
    }

    private void givenChangedCredentials() {
        when(this.sessionHelper.credentialsChanged(any(HttpSession.class), anyString())).thenReturn(true);
    }

    private void givenRequestPath(final String path) {
        final List<PathSegment> segments = new ArrayList<>();

        for (final String segment : path.substring(1).split("/")) {
            final PathSegment pathSegment = mock(PathSegment.class);
            when(pathSegment.getPath()).thenReturn(segment);
            segments.add(pathSegment);
        }

        when(this.uriInfo.getPathSegments()).thenReturn(segments);
    }

    private void whenAuthenticateIsCalled() {
        this.result = this.provider.authenticate(this.request, this.requestContext);
    }

    private void thenRequestIsAuthenticatedAs(final String identity) {
        assertTrue(this.result.isPresent());
        assertEquals(identity, this.result.get().getName());
    }

    private void thenRequestIsNotAuthenticated() {
        assertFalse(this.result.isPresent());
    }

    private void thenAuditContextReportsIdentity(final String identity) {
        assertEquals(identity, this.auditProperties.get(AuditConstants.KEY_IDENTITY.getValue()));
    }

    private void thenAuditContextDoesNotReportIdentity() {
        assertFalse(this.auditProperties.containsKey(AuditConstants.KEY_IDENTITY.getValue()));
    }

    private void thenSessionLastActivityIsUpdated() {
        verify(this.sessionHelper).updateLastActivity(this.session);
    }

    private void thenSessionValidityIsNotChecked() {
        verify(this.sessionHelper, never()).isSessionExpired(any(HttpSession.class), anyInt());
        verify(this.sessionHelper, never()).isSessionLocked(any(HttpSession.class));
        verify(this.sessionHelper, never()).updateLastActivity(any(HttpSession.class));
    }

    private void thenXsrfTokenIsNotChecked() {
        verify(this.sessionHelper, never()).getXsrfTokenStatus(any(HttpServletRequest.class));
    }

}
