/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 * Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.data.store;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.util.Optional;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

import org.eclipse.kura.core.data.DataServiceOptions;
import org.eclipse.kura.core.testutil.TestUtil;
import org.eclipse.kura.message.store.provider.MessageStore;
import org.eclipse.kura.message.store.provider.MessageStoreProvider;
import org.junit.Test;

public class MessageStoreStateShutdownTest {

    private final MessageStoreProvider messageStoreProvider = mock(MessageStoreProvider.class);
    private final MessageStore messageStore = mock(MessageStore.class);
    private MessageStoreState state;
    private ScheduledExecutorService houseKeeperExecutor;

    @Test
    public void shutdownStopsHouseKeeperAndClosesStore() throws Exception {
        givenMessageStoreState();
        givenOpenMessageStore();

        whenShutdown();

        thenHouseKeeperExecutorIsTerminated();
        thenMessageStoreIsClosed();
    }

    @Test
    public void shutdownCompletesWhenHouseKeeperDoesNotTerminate() throws Exception {
        givenMessageStoreState();
        givenOpenMessageStore();
        givenHouseKeeperExecutorThatDoesNotTerminate();

        whenShutdown();

        thenHouseKeeperExecutorWasShutDownAndAwaited();
        thenNoHouseKeeperExecutorIsKept();
        thenMessageStoreIsClosed();
    }

    /*
     * Steps
     */

    private void givenMessageStoreState() throws Exception {
        final DataServiceOptions options = mock(DataServiceOptions.class);
        when(options.getStorePurgeAge()).thenReturn(60);
        when(options.getStoreHousekeeperInterval()).thenReturn(900);
        when(options.getKuraServicePid()).thenReturn("test.data.service");
        when(this.messageStoreProvider.openMessageStore(anyString())).thenReturn(this.messageStore);

        this.state = new MessageStoreState(this.messageStoreProvider, options);
    }

    private void givenOpenMessageStore() throws Exception {
        this.state.getOrOpenMessageStore();
    }

    @SuppressWarnings("unchecked")
    private void givenHouseKeeperExecutorThatDoesNotTerminate() throws Exception {
        final Optional<ScheduledExecutorService> realExecutor = (Optional<ScheduledExecutorService>) TestUtil
                .getFieldValue(this.state, "houseKeeperExecutor");
        realExecutor.ifPresent(ScheduledExecutorService::shutdownNow);

        this.houseKeeperExecutor = mock(ScheduledExecutorService.class);
        when(this.houseKeeperExecutor.awaitTermination(30, TimeUnit.SECONDS)).thenReturn(false);
        TestUtil.setFieldValue(this.state, "houseKeeperExecutor", Optional.of(this.houseKeeperExecutor));
    }

    @SuppressWarnings("unchecked")
    private void whenShutdown() throws Exception {
        if (this.houseKeeperExecutor == null) {
            this.houseKeeperExecutor = ((Optional<ScheduledExecutorService>) TestUtil.getFieldValue(this.state,
                    "houseKeeperExecutor")).get();
        }
        this.state.shutdown();
    }

    private void thenHouseKeeperExecutorIsTerminated() {
        assertTrue(this.houseKeeperExecutor.isTerminated());
    }

    private void thenHouseKeeperExecutorWasShutDownAndAwaited() throws InterruptedException {
        verify(this.houseKeeperExecutor).shutdown();
        verify(this.houseKeeperExecutor).awaitTermination(30, TimeUnit.SECONDS);
    }

    @SuppressWarnings("unchecked")
    private void thenNoHouseKeeperExecutorIsKept() throws NoSuchFieldException {
        assertFalse(((Optional<ScheduledExecutorService>) TestUtil.getFieldValue(this.state, "houseKeeperExecutor"))
                .isPresent());
    }

    private void thenMessageStoreIsClosed() {
        verify(this.messageStore).close();
    }
}
