/*******************************************************************************
 * Copyright (c) 2025 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.crypto;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.fail;

import java.io.IOException;
import java.lang.reflect.Field;
import java.nio.file.Files;
import java.util.Optional;

import org.eclipse.kura.KuraException;
import org.eclipse.kura.system.SystemService;
import org.junit.After;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;
import org.mockito.Mockito;

public class CryptoServiceImplCustomKeyTest {

    @Rule
    public TemporaryFolder tempFolder = new TemporaryFolder();

    private CryptoServiceImpl cryptoService;
    private SystemService mockSystemService;
    private String testPlaintext;
    private char[] encryptedData;
    private char[] decryptedData;

    @Before
    public void setup() {
        this.mockSystemService = Mockito.mock(SystemService.class);
        try {
            Mockito.when(this.mockSystemService.getKuraDataDirectory())
                    .thenReturn(Files.createTempDirectory(null).toString());
        } catch (IOException e) {
            throw new IllegalStateException("cannot create temporary directory");
        }
        this.cryptoService = new CryptoServiceImpl();
        this.cryptoService.setSystemService(this.mockSystemService);
    }

    @After
    public void cleanup() {
        System.clearProperty("org.eclipse.kura.core.crypto.secretKey");
    }

    @Test
    public void loadKeyFromSystemProperty16Bytes() {
        given16ByteCustomKey();
        givenSystemPropertyKey();

        whenActivatingCryptoService();

        thenSecretKeyLengthIs(16);
    }

    @Test
    public void loadKeyFromSystemProperty24Bytes() {
        given24ByteCustomKey();
        givenSystemPropertyKey();

        whenActivatingCryptoService();

        thenSecretKeyLengthIs(24);
    }

    @Test
    public void loadKeyFromSystemProperty32Bytes() {
        given32ByteCustomKey();
        givenSystemPropertyKey();

        whenActivatingCryptoService();

        thenSecretKeyLengthIs(32);
    }

    @Test
    public void rejectDefaultKey() {
        givenDefaultKey();
        givenSystemPropertyKey();

        whenActivatingCryptoService();

        thenDefaultKeyIsUsed();
    }

    @Test
    public void rejectInvalidKeyLength15Bytes() {
        givenCustomKeyWithLength(15);
        givenSystemPropertyKey();

        whenActivatingCryptoService();

        thenDefaultKeyIsUsed();
    }

    @Test
    public void rejectInvalidKeyLength17Bytes() {
        givenCustomKeyWithLength(17);
        givenSystemPropertyKey();

        whenActivatingCryptoService();

        thenDefaultKeyIsUsed();
    }

    @Test
    public void rejectInvalidKeyLength20Bytes() {
        givenCustomKeyWithLength(20);
        givenSystemPropertyKey();

        whenActivatingCryptoService();

        thenDefaultKeyIsUsed();
    }

    @Test
    public void rejectInvalidKeyLength31Bytes() {
        givenCustomKeyWithLength(31);
        givenSystemPropertyKey();

        whenActivatingCryptoService();

        thenDefaultKeyIsUsed();
    }

    @Test
    public void useDefaultKeyWhenNoCustomKeyProvided() {
        whenActivatingCryptoService();

        thenDefaultKeyIsUsed();
    }



    @Test
    public void encryptAndDecryptWithCustomKey() {
        given32ByteCustomKey();
        givenSystemPropertyKey();
        givenPlaintext("test-data-to-encrypt");
        whenActivatingCryptoService();
        thenSecretKeyLengthIs(32);
        whenEncryptingData();
        whenDecryptingData();
        thenDecryptedDataMatchesPlaintext();
    }

    @Test
    public void encryptAndDecryptWithDefaultKey() {
        givenPlaintext("default-key-roundtrip");
        whenActivatingCryptoService();
        thenDefaultKeyIsUsed();
        whenEncryptingData();
        whenDecryptingData();
        thenDecryptedDataMatchesPlaintext();
    }

    @Test
    public void ciphertextFormatHasSeparator() {
        given16ByteCustomKey();
        givenSystemPropertyKey();
        whenActivatingCryptoService();
        thenSecretKeyLengthIs(16);
        whenEncryptingData();
        String c = new String(this.encryptedData);
        assertTrue(c.contains("-"));
        assertEquals(2, c.split("-").length);
    }

    @Test(expected = KuraException.class)
    public void decryptMalformedThrows() throws KuraException {
        whenActivatingCryptoService();
        this.cryptoService.decryptAes("malformed".toCharArray());
    }

    @Test
    public void base64RoundTrip() throws Exception {
        whenActivatingCryptoService();
        String v = "roundtrip";
        String enc = this.cryptoService.encodeBase64(v);
        String dec = this.cryptoService.decodeBase64(enc);
        assertEquals(v, dec);
    }

    @Test
    public void hashProducesDifferentValues() throws Exception {
        whenActivatingCryptoService();
        String a = this.cryptoService.hash("a", "SHA-256");
        String b = this.cryptoService.hash("b", "SHA-256");
        assertFalse(a.equals(b));
    }

    @Test
    public void keystorePasswordPersists() throws Exception {
        whenActivatingCryptoService();
        char[] pwd = "p@ssw0rd".toCharArray();
        this.cryptoService.setKeyStorePassword("/ks", pwd);
        char[] out = this.cryptoService.getKeyStorePassword("/ks");
        assertArrayEquals(pwd, out);
    }

    private void given16ByteCustomKey() {
        this.testPlaintext = "1234567890ABCDEF";
    }

    private void given24ByteCustomKey() {
        this.testPlaintext = "12345678901234567890ABCD";
    }

    private void given32ByteCustomKey() {
        this.testPlaintext = "12345678901234567890123456789012";
    }

    private void givenDefaultKey() {
        this.testPlaintext = "rv;ipse329183!@#";
    }

    private void givenCustomKeyWithLength(int length) {
        StringBuilder builder = new StringBuilder(length);
        for (int i = 0; i < length; i++) {
            builder.append((char) ('a' + (i % 26)));
        }
        this.testPlaintext = builder.toString();
    }

    private void givenPlaintext(String plaintext) {
        this.testPlaintext = plaintext;
    }

    private void givenSystemPropertyKey() {
        System.setProperty("org.eclipse.kura.core.crypto.secretKey", this.testPlaintext);
    }

    private void whenActivatingCryptoService() {
        this.cryptoService.activate();
    }

    private void whenEncryptingData() {
        try {
            this.encryptedData = this.cryptoService.encryptAes(this.testPlaintext.toCharArray());
        } catch (KuraException e) {
            fail("Encryption failed: " + e.getMessage());
        }
    }

    private void whenDecryptingData() {
        try {
            this.decryptedData = this.cryptoService.decryptAes(this.encryptedData);
        } catch (KuraException e) {
            fail("Decryption failed: " + e.getMessage());
        }
    }

    private Optional<byte[]> getSecretKey() {
        try {
            Field field = CryptoServiceImpl.class.getDeclaredField("secretKey");
            field.setAccessible(true);
            Object value = field.get(this.cryptoService);
            if (value == null) {
                return Optional.empty();
            }
            return (Optional<byte[]>) value;
        } catch (NoSuchFieldException | IllegalAccessException e) {
            fail("Unable to access secret key: " + e.getMessage());
            return Optional.empty();
        }
    }

    private void thenSecretKeyLengthIs(int expectedLength) {
        Optional<byte[]> secretKey = getSecretKey();
        assertTrue(secretKey.isPresent());
        assertEquals(expectedLength, secretKey.get().length);
    }

    private void thenDefaultKeyIsUsed() {
        Optional<byte[]> secretKey = getSecretKey();
        assertFalse(secretKey.isPresent());
    }

    private void thenDecryptedDataMatchesPlaintext() {
        assertNotNull(this.decryptedData);
        assertArrayEquals(this.testPlaintext.toCharArray(), this.decryptedData);
    }
}
