/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 * Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.ssl;

import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import org.eclipse.kura.ssl.SslServiceListener;
import org.junit.Test;
import org.osgi.util.tracker.ServiceTracker;

public class NotifySslServiceListenersTest {

    @SuppressWarnings("unchecked")
    private final ServiceTracker<SslServiceListener, SslServiceListener> tracker = mock(ServiceTracker.class);
    private final SslServiceListeners sslServiceListeners = new SslServiceListeners(this.tracker);
    private final SslServiceListener failingListener = mock(SslServiceListener.class);
    private final SslServiceListener healthyListener = mock(SslServiceListener.class);
    private Throwable propagatedThrowable;

    /*
     * Scenarios
     */

    @Test
    public void notifiesRemainingListenersWhenOneThrowsException() {
        givenListenerFailingWith(new IllegalStateException("listener failure"));
        givenTrackedListeners(this.failingListener, this.healthyListener);

        whenConfigurationIsUpdated();

        thenNothingPropagated();
        thenListenerNotified(this.healthyListener);
    }

    @Test
    public void notifiesRemainingListenersWhenOneFailsWithLinkageError() {
        givenListenerFailingWith(new NoClassDefFoundError("uninstalled bundle class"));
        givenTrackedListeners(this.failingListener, this.healthyListener);

        whenConfigurationIsUpdated();

        thenNothingPropagated();
        thenListenerNotified(this.healthyListener);
    }

    @Test
    public void propagatesVirtualMachineErrorFromListener() {
        givenListenerFailingWith(new OutOfMemoryError("simulated"));
        givenTrackedListeners(this.failingListener, this.healthyListener);

        whenConfigurationIsUpdated();

        thenPropagated(OutOfMemoryError.class);
    }

    /*
     * Steps
     */

    private void givenListenerFailingWith(Throwable failure) {
        doThrow(failure).when(this.failingListener).onConfigurationUpdated();
    }

    private void givenTrackedListeners(SslServiceListener... listeners) {
        when(this.tracker.getTrackingCount()).thenReturn(1);
        when(this.tracker.getServices()).thenReturn(listeners);
    }

    private void whenConfigurationIsUpdated() {
        try {
            this.sslServiceListeners.onConfigurationUpdated();
        } catch (Throwable e) {
            this.propagatedThrowable = e;
        }
    }

    private void thenNothingPropagated() {
        assertNull(this.propagatedThrowable);
    }

    private void thenPropagated(Class<? extends Throwable> expected) {
        assertTrue("unexpected: " + this.propagatedThrowable, expected.isInstance(this.propagatedThrowable));
    }

    private void thenListenerNotified(SslServiceListener listener) {
        verify(listener).onConfigurationUpdated();
    }
}
