/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 * Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.ssl;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import static org.junit.Assume.assumeTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.io.IOException;
import java.io.OutputStream;
import java.lang.management.ManagementFactory;
import java.lang.management.OperatingSystemMXBean;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.KeyStore;

import javax.net.ssl.TrustManager;

import org.eclipse.kura.core.testutil.TestUtil;
import org.junit.After;
import org.junit.Test;

public class TrustStoreLoadingTest {

    private static final char[] PASSWORD = "changeit".toCharArray();
    private static final char[] WRONG_PASSWORD = "wrong".toCharArray();
    private static final int ATTEMPTS = 50;

    private final SslManagerServiceImpl sslManagerService = new SslManagerServiceImpl();
    private Path trustStore;
    private TrustManager[] trustManagers;
    private int failedLoads;
    private long openDescriptorsBefore;
    private long openDescriptorsAfter;

    /*
     * Scenarios
     */

    @Test
    public void loadsTrustManagersWithTheRightPassword() throws Throwable {
        givenRevocationCheckDisabled();
        givenTrustStore();

        whenTrustManagersAreLoadedWith(PASSWORD);

        thenTrustManagersAreReturned();
    }

    @Test
    public void releasesTheTrustStoreFileWhenTheLoadFails() throws Exception {
        givenUnixFileDescriptorCount();
        givenTrustStore();

        whenTrustManagersAreLoadedRepeatedlyWith(WRONG_PASSWORD);

        thenEveryLoadFailed();
        thenNoFileDescriptorIsLeaked();
    }

    @After
    public void tearDown() throws IOException {
        if (this.trustStore != null) {
            Files.deleteIfExists(this.trustStore);
        }
    }

    /*
     * Steps
     */

    private void givenUnixFileDescriptorCount() {
        assumeTrue(ManagementFactory.getOperatingSystemMXBean() instanceof com.sun.management.UnixOperatingSystemMXBean);
    }

    private void givenRevocationCheckDisabled() throws NoSuchFieldException {
        final SslManagerServiceOptions options = mock(SslManagerServiceOptions.class);
        when(options.isSslRevocationCheckEnabled()).thenReturn(false);
        TestUtil.setFieldValue(this.sslManagerService, "options", options);
    }

    private void givenTrustStore() throws Exception {
        final KeyStore keyStore = KeyStore.getInstance(KeyStore.getDefaultType());
        keyStore.load(null, PASSWORD);
        this.trustStore = Files.createTempFile("truststore", ".ks");
        try (OutputStream out = Files.newOutputStream(this.trustStore)) {
            keyStore.store(out, PASSWORD);
        }
    }

    private void whenTrustManagersAreLoadedWith(char[] password) throws Throwable {
        this.trustManagers = loadTrustManagers(password);
    }

    private void whenTrustManagersAreLoadedRepeatedlyWith(char[] password) {
        this.openDescriptorsBefore = openFileDescriptors();
        for (int i = 0; i < ATTEMPTS; i++) {
            try {
                loadTrustManagers(password);
            } catch (Throwable e) {
                this.failedLoads++;
            }
        }
        this.openDescriptorsAfter = openFileDescriptors();
    }

    private void thenTrustManagersAreReturned() {
        assertTrue(this.trustManagers.length > 0);
    }

    private void thenEveryLoadFailed() {
        assertEquals(ATTEMPTS, this.failedLoads);
    }

    private void thenNoFileDescriptorIsLeaked() {
        assertTrue("open file descriptors grew from " + this.openDescriptorsBefore + " to " + this.openDescriptorsAfter,
                this.openDescriptorsAfter - this.openDescriptorsBefore < ATTEMPTS / 2);
    }

    /*
     * Utilities
     */

    private TrustManager[] loadTrustManagers(char[] password) throws Throwable {
        return (TrustManager[]) TestUtil.invokePrivate(this.sslManagerService, "getTrustManagers",
                new Class<?>[] { String.class, char[].class }, this.trustStore.toString(), password);
    }

    private static long openFileDescriptors() {
        final OperatingSystemMXBean bean = ManagementFactory.getOperatingSystemMXBean();
        return ((com.sun.management.UnixOperatingSystemMXBean) bean).getOpenFileDescriptorCount();
    }
}
