/*******************************************************************************
 * Copyright (c) 2025 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.linux.net.iptables;

import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;

import java.net.UnknownHostException;
import java.util.HashSet;
import java.util.Set;

import org.eclipse.kura.KuraException;
import org.eclipse.kura.net.IPAddress;
import org.junit.Before;
import org.junit.Test;

/**
 * Test class for AbstractLinuxFirewall ICMP rule detection functionality.
 * This feature verifies that ICMP rules in additional rules prevent allowIcmp from being set.
 */
public class AbstractLinuxFirewallTest {

    private TestableAbstractLinuxFirewall firewall;
    private IptablesConfig mockIptablesConfig;
    private Set<String> filterRules;
    private Set<String> natRules;
    private Set<String> mangleRules;

    @Before
    public void setUp() {
        this.mockIptablesConfig = mock(IptablesConfig.class);
        this.firewall = new TestableAbstractLinuxFirewall();
        this.firewall.iptables = this.mockIptablesConfig;
        this.filterRules = new HashSet<>();
        this.natRules = new HashSet<>();
        this.mangleRules = new HashSet<>();
    }

    @Test
    public void setAdditionalRulesWithIcmpRulesInFilter() throws KuraException {
        givenAdditionalRulesWithIcmpInFilter();

        whenSettingAdditionalRules();

        thenAllowIcmpIsFalse();
    }

    @Test
    public void setAdditionalRulesWithIcmpRulesInNat() throws KuraException {
        givenAdditionalRulesWithIcmpInNat();

        whenSettingAdditionalRules();

        thenAllowIcmpIsFalse();
    }

    @Test
    public void setAdditionalRulesWithIcmpRulesInMangle() throws KuraException {
        givenAdditionalRulesWithIcmpInMangle();

        whenSettingAdditionalRules();

        thenAllowIcmpIsFalse();
    }

    @Test
    public void setAdditionalRulesWithoutIcmpRules() throws KuraException {
        givenAdditionalRulesWithoutIcmp();

        whenSettingAdditionalRules();

        thenAllowIcmpIsTrue();
    }

    @Test
    public void setAdditionalRulesWithEmptyRules() throws KuraException {
        givenEmptyAdditionalRules();

        whenSettingAdditionalRules();

        thenAllowIcmpIsTrue();
    }


    // Given methods

    private void givenAdditionalRulesWithIcmpInFilter() {
        this.filterRules.add("-A input-kura -p icmp --icmp-type 8 -j DROP");
        this.filterRules.add("-A input-kura -p tcp --dport 80 -j ACCEPT");
    }

    private void givenAdditionalRulesWithIcmpInNat() {
        this.natRules.add("-A prerouting-kura --protocol ipv6-icmp --icmpv6-type 129 -j DROP");
        this.natRules.add("-A prerouting-kura -p tcp --dport 443 -j ACCEPT");
    }

    private void givenAdditionalRulesWithIcmpInMangle() {
        this.mangleRules.add("-A prerouting-kura -p icmp -m icmp --icmp-type 8 -m state --state NEW,RELATED,ESTABLISHED -j DROP");
        this.mangleRules.add("-A prerouting-kura -p tcp --tcp-flags SYN,RST SYN,RST -j DROP");
    }

    private void givenAdditionalRulesWithoutIcmp() {
        this.filterRules.add("-A input-kura -p tcp --dport 80 -j ACCEPT");
        this.natRules.add("-A prerouting-kura -p tcp --dport 443 -j ACCEPT");
        this.mangleRules.add("-A prerouting-kura -p tcp --tcp-flags SYN,RST SYN,RST -j DROP");
    }

    private void givenEmptyAdditionalRules() {
        // filterRules, natRules, and mangleRules are already empty
    }

    // When methods

    private void whenSettingAdditionalRules() throws KuraException {
        this.firewall.setAdditionalRules(this.filterRules, this.natRules, this.mangleRules);
    }

    // Then methods

    private void thenAllowIcmpIsFalse() {
        verify(this.mockIptablesConfig, times(1)).setAllowIcmp(false);
    }

    private void thenAllowIcmpIsTrue() {
        verify(this.mockIptablesConfig, times(1)).setAllowIcmp(true);
    }

    /**
     * Testable implementation of AbstractLinuxFirewall for testing purposes.
     */
    private static class TestableAbstractLinuxFirewall extends AbstractLinuxFirewall {

        public TestableAbstractLinuxFirewall() {
            super();
            this.allowIcmp = false;
        }

        @Override
        protected IPAddress getDefaultAddress() throws UnknownHostException {
            return IPAddress.parseHostAddress("0.0.0.0");
        }

        @Override
        protected String getIpForwardFileName() {
            return "/proc/sys/net/ipv4/ip_forward";
        }
    }
}
