/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt.common;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertThrows;
import static org.junit.Assert.assertTrue;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.atLeastOnce;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;

import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import org.eclipse.kura.KuraAuthenticationFailedException;
import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.KuraException;
import org.eclipse.kura.core.testutil.pki.TestCA.TestCAException;
import org.eclipse.kura.core.token.jwt.issuer.JwtIssuingService;
import org.eclipse.kura.core.token.jwt.verifier.JwtVerificationService;
import org.eclipse.kura.security.keystore.KeystoreService;
import org.eclipse.kura.security.token.TokenIssueRequest;
import org.eclipse.kura.security.token.TokenVerifyRequest;
import org.eclipse.kura.security.token.VerificationProof;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;

public abstract class AbstractJwtScenario {

    protected static final String TEST_IDENTITY = "test.user";
    protected static final String SIGNING_ALIAS = "jwt-signing-key";
    protected static final String DEFAULT_ISSUER = "kura";

    private KeystoreFixture keystore = new KeystoreFixture();

    private final JwtIssuingService issuingService = new JwtIssuingService();
    private final JwtVerificationService verificationService = new JwtVerificationService();

    private String issuedToken;
    private TokenInspector issuedTokenInspector;
    private Instant issuedNoEarlierThan;
    private Instant issuedNoLaterThan;
    private Exception issuingFailure;

    private VerificationProof proof;
    private Exception verificationFailure;

    protected KeystoreFixture keystore() {
        return this.keystore;
    }

    protected String issuedToken() {
        return this.issuedToken;
    }

    protected TokenInspector issuedTokenInspector() {
        return this.issuedTokenInspector;
    }

    protected Exception issuingFailure() {
        return this.issuingFailure;
    }

    protected VerificationProof proof() {
        return this.proof;
    }

    protected void givenKeystorePrivateKeyEntry(final String alias, final int keyIndex) throws TestCAException {
        this.keystore.withPrivateKeyEntry(alias, TestKeys.rsa(keyIndex));
    }

    protected void givenKeystorePrivateKeyEntryWithNonRsaKey(final String alias) throws TestCAException {
        this.keystore.withNonRsaPrivateKeyEntry(alias);
    }

    protected void givenKeystoreTrustedCertificate(final String alias, final int keyIndex) throws TestCAException {
        this.keystore.withTrustedCertificate(alias, TestKeys.rsa(keyIndex));
    }

    protected void givenKeystoreTrustedCertificate(final String alias, final int keyIndex, final Instant validFrom,
            final Instant validTo) throws TestCAException {

        this.keystore.withTrustedCertificate(alias, TestKeys.rsa(keyIndex), validFrom, validTo);
    }

    protected void givenKeystoreTrustedCertificateForNonRsaKey(final String alias) throws TestCAException {
        this.keystore.withTrustedCertificate(alias, TestKeys.certificate(alias, TestKeys.ecdsa()));
    }

    protected void givenKeystoreSecretKeyEntry(final String alias) {
        this.keystore.withSecretKeyEntry(alias);
    }

    protected void givenKeystoreWithoutEntry(final String alias) {
        this.keystore.withoutEntry(alias);
    }

    protected void givenAKeystoreThatAlwaysFails() {
        this.keystore = KeystoreFixture.alwaysFailing();
    }

    protected void givenTheIssuerIsBoundToTheKeystore() {
        this.issuingService.setKeystoreService(this.keystore.service(), this.keystore.serviceProperties());
    }

    protected void givenTheVerifierIsBoundToTheKeystore() {
        this.verificationService.setKeystoreService(this.keystore.service(), this.keystore.serviceProperties());
    }

    protected void givenTheIssuerIsActivatedWith(final IssuingConfig config) {
        this.issuingService.activate(config.toOcd());
    }

    protected void givenTheVerifierIsActivatedWith(final VerificationConfig config) {
        this.verificationService.activate(config.toOcd());
    }

    protected void givenIssuingIsNotAvailableYet() {
        whenATokenIsIssuedFor(TEST_IDENTITY);

        thenNoTokenIsIssued();
        thenIssuingFailedWith(KuraErrorCode.CONFIGURATION_ERROR);

        resetIssuingOutcome();
    }

    protected void givenVerificationIsNotAvailableYetFor(final String token) {
        whenATokenIsVerified(token);

        thenNoVerificationProofIsProduced();
        thenVerificationFailedWith(KuraErrorCode.CONFIGURATION_ERROR);

        resetVerificationOutcome();
    }

    protected void givenTheBoundKeystoreAnnouncedAChange() {
        whenTheBoundKeystoreAnnouncesAChange();
    }

    protected void givenAForeignKeystoreAnnouncedAChange() {
        whenAForeignKeystoreAnnouncesAChange();
    }

    protected void givenTheBoundKeystoreWasUnbound() {
        whenTheBoundKeystoreIsUnbound();
    }

    protected void givenADifferentKeystoreInstanceWasUnbound() {
        whenADifferentKeystoreInstanceIsUnbound();
    }

    protected void givenTheIssuerWasReconfiguredWith(final IssuingConfig config) {
        whenTheIssuerIsReconfiguredWith(config);
    }

    protected void givenTheVerifierWasReconfiguredWith(final VerificationConfig config) {
        whenTheVerifierIsReconfiguredWith(config);
    }

    protected void whenATokenIsIssuedFor(final String identityName) {
        whenATokenIsIssued(TokenIssueRequest.builder().identityName(identityName).build());
    }

    protected void whenATokenIsIssued(final TokenIssueRequest request) {
        resetIssuingOutcome();

        this.issuedNoEarlierThan = Instant.now();

        try {
            this.issuedToken = this.issuingService.issue(request);
            this.issuedTokenInspector = TokenInspector.of(this.issuedToken);
        } catch (final Exception e) {
            this.issuingFailure = e;
        }

        this.issuedNoLaterThan = Instant.now();
    }

    protected void whenATokenIsVerified(final String token) {
        whenTheRequestIsVerified(TokenVerifyRequest.builder().token(token).build());
    }

    protected void whenATokenIsVerifiedFor(final String token, final String intendedConsumer) {
        whenTheRequestIsVerified(TokenVerifyRequest.builder().token(token).intendedConsumer(intendedConsumer).build());
    }

    protected void whenTheIssuedTokenIsVerified() {
        assertNotNull("no token has been issued, nothing to verify", this.issuedToken);

        whenATokenIsVerified(this.issuedToken);
    }

    protected void whenTheIssuerIsReconfiguredWith(final IssuingConfig config) {
        this.issuingService.updated(config.toOcd());
    }

    protected void whenTheVerifierIsReconfiguredWith(final VerificationConfig config) {
        this.verificationService.updated(config.toOcd());
    }

    protected void whenTheBoundKeystoreAnnouncesAChange() {
        this.keystore.forgetRecordedInteractions();

        this.issuingService.handleEvent(this.keystore.changedEvent());
        this.verificationService.handleEvent(this.keystore.changedEvent());
    }

    protected void whenAForeignKeystoreAnnouncesAChange() {
        this.keystore.forgetRecordedInteractions();

        this.issuingService.handleEvent(KeystoreFixture.changedEventFrom(KeystoreFixture.FOREIGN_PID));
        this.verificationService.handleEvent(KeystoreFixture.changedEventFrom(KeystoreFixture.FOREIGN_PID));
    }

    protected void whenAKeystoreChangeWithoutSenderPidIsDelivered() {
        this.keystore.forgetRecordedInteractions();

        this.issuingService.handleEvent(KeystoreFixture.changedEventWithoutSenderPid());
        this.verificationService.handleEvent(KeystoreFixture.changedEventWithoutSenderPid());
    }

    protected void whenAnUnrelatedEventOnTheKeystoreTopicIsDelivered() {
        this.keystore.forgetRecordedInteractions();

        this.issuingService.handleEvent(KeystoreFixture.unrelatedEventOnTheKeystoreTopic());
        this.verificationService.handleEvent(KeystoreFixture.unrelatedEventOnTheKeystoreTopic());
    }

    protected void whenTheBoundKeystoreIsUnbound() {
        this.issuingService.unsetKeystoreService(this.keystore.service());
        this.verificationService.unsetKeystoreService(this.keystore.service());
    }

    protected void whenADifferentKeystoreInstanceIsUnbound() {
        final KeystoreService anotherKeystore = new KeystoreFixture(KeystoreFixture.FOREIGN_PID).service();

        this.issuingService.unsetKeystoreService(anotherKeystore);
        this.verificationService.unsetKeystoreService(anotherKeystore);
    }

    protected void thenATokenIsIssued() {
        assertNull("issuing failed unexpectedly", this.issuingFailure);
        assertNotNull("expected a token to be issued", this.issuedToken);
    }

    protected void thenNoTokenIsIssued() {
        assertNull("expected no token to be issued", this.issuedToken);
    }

    protected void thenIssuingFailedWith(final KuraErrorCode expectedErrorCode) {
        assertNotNull("expected issuing to fail", this.issuingFailure);
        assertTrue("expected a KuraException but got " + this.issuingFailure.getClass().getName(),
                this.issuingFailure instanceof KuraException);
        assertEquals(expectedErrorCode, ((KuraException) this.issuingFailure).getCode());
    }

    protected void thenIssuingFailedWithBadRequestMentioning(final String expectedFragment) {
        thenIssuingFailedWith(KuraErrorCode.BAD_REQUEST);
        assertTrue("failure message '" + this.issuingFailure.getMessage() + "' does not mention " + expectedFragment,
                this.issuingFailure.getMessage().contains(expectedFragment));
    }

    protected void thenIssuedTokenHeaderHas(final String name, final String expectedValue) {
        final JsonElement entry = requireHeaderEntry(name);

        assertEquals(expectedValue, entry.getAsString());
    }

    protected void thenIssuedTokenHasNoClaim(final String name) {
        thenATokenIsIssued();
        assertFalse("claim '" + name + "' should not be present in " + this.issuedTokenInspector.payload(),
                this.issuedTokenInspector.claim(name).isPresent());
    }

    protected void thenIssuedTokenHasStringClaim(final String name, final String expectedValue) {
        final JsonElement claim = requireClaim(name);

        assertTrue("claim '" + name + "' is not a JSON string but " + claim, isPrimitiveString(claim));
        assertEquals(expectedValue, claim.getAsString());
    }

    protected void thenIssuedTokenHasBooleanClaim(final String name, final boolean expectedValue) {
        final JsonElement claim = requireClaim(name);

        assertTrue("claim '" + name + "' is not a JSON boolean but " + claim,
                claim.isJsonPrimitive() && claim.getAsJsonPrimitive().isBoolean());
        assertEquals(expectedValue, claim.getAsBoolean());
    }

    protected void thenIssuedTokenHasIntegralClaim(final String name, final long expectedValue) {
        final JsonElement claim = requireClaim(name);

        assertTrue("claim '" + name + "' is not a JSON number but " + claim, isPrimitiveNumber(claim));
        assertEquals(expectedValue, claim.getAsLong());
    }

    protected void thenIssuedTokenHasDecimalClaim(final String name, final double expectedValue, final double delta) {
        final JsonElement claim = requireClaim(name);

        assertTrue("claim '" + name + "' is not a JSON number but " + claim, isPrimitiveNumber(claim));
        assertEquals(expectedValue, claim.getAsDouble(), delta);
    }

    protected void thenIssuedTokenHasNullClaim(final String name) {
        final JsonElement claim = requireClaim(name);

        assertTrue("claim '" + name + "' is not a JSON null but " + claim, claim.isJsonNull());
    }

    protected void thenIssuedTokenHasStringArrayClaim(final String name, final List<String> expectedValues) {
        final JsonElement claim = requireClaim(name);

        assertTrue("claim '" + name + "' is not a JSON array but " + claim, claim.isJsonArray());

        final List<String> actualValues = new ArrayList<>();
        claim.getAsJsonArray().forEach(element -> actualValues.add(element.getAsString()));

        assertEquals(expectedValues, actualValues);
    }

    protected void thenIssuedTokenHasObjectClaimWithEntry(final String name, final String key,
            final String expectedValue) {

        final JsonElement claim = requireClaim(name);

        assertTrue("claim '" + name + "' is not a JSON object but " + claim, claim.isJsonObject());

        final JsonObject object = claim.getAsJsonObject();

        assertTrue("claim '" + name + "' has no entry '" + key + "' in " + object, object.has(key));
        assertEquals(expectedValue, object.get(key).getAsString());
    }

    protected void thenIssuedTokenClaimIsAUniversallyUniqueIdentifier(final String name) {
        final JsonElement claim = requireClaim(name);

        assertTrue("claim '" + name + "' is not a JSON string but " + claim, isPrimitiveString(claim));
        assertEquals(claim.getAsString(), UUID.fromString(claim.getAsString()).toString());
    }

    protected void thenIssuedTokenExpiresAt(final Instant expectedExpiration) {
        final JsonElement claim = requireClaim("exp");

        assertEquals(expectedExpiration.getEpochSecond(), claim.getAsLong());
    }

    protected void thenIssuedTokenExpiresAtIssueTimePlus(final Duration expectedLifetime) {
        final JsonElement claim = requireClaim("exp");

        final long earliest = this.issuedNoEarlierThan.plus(expectedLifetime).getEpochSecond();
        final long latest = this.issuedNoLaterThan.plus(expectedLifetime).getEpochSecond();
        final long actual = claim.getAsLong();

        assertTrue("exp is " + actual + " but was expected between " + earliest + " and " + latest,
                actual >= earliest && actual <= latest);
    }

    protected void thenIssuedTokenIsNotBeforeAt(final Instant expectedNotBefore) {
        final JsonElement claim = requireClaim("nbf");

        assertEquals(expectedNotBefore.getEpochSecond(), claim.getAsLong());
    }

    protected void thenTheTokenIsVerifiedFor(final String expectedIdentityName) {
        assertNull("verification failed unexpectedly", this.verificationFailure);
        assertNotNull("expected a verification proof", this.proof);
        assertEquals(expectedIdentityName, this.proof.getIdentityName());
    }

    protected void thenNoVerificationProofIsProduced() {
        assertNull("expected no verification proof", this.proof);
    }

    protected void thenVerificationFailedAsAuthenticationFailure() {
        assertNotNull("expected verification to fail", this.verificationFailure);
        assertTrue("expected a KuraAuthenticationFailedException but got "
                + this.verificationFailure.getClass().getName(),
                this.verificationFailure instanceof KuraAuthenticationFailedException);
    }

    protected void thenVerificationFailedBecauseOf(final Class<? extends Throwable> expectedCauseClass) {
        thenVerificationFailedAsAuthenticationFailure();

        final Throwable cause = this.verificationFailure.getCause();

        assertNotNull("expected the failure to carry a cause", cause);
        assertTrue("expected a cause of type " + expectedCauseClass.getName() + " but got " + cause.getClass().getName(),
                expectedCauseClass.isInstance(cause));
    }

    protected void thenVerificationFailedWithoutAnUnderlyingCause() {
        thenVerificationFailedAsAuthenticationFailure();

        assertNull("expected the failure to carry no cause", this.verificationFailure.getCause());
    }

    protected void thenVerificationFailedWith(final KuraErrorCode expectedErrorCode) {
        assertNotNull("expected verification to fail", this.verificationFailure);
        assertTrue("expected a KuraException but got " + this.verificationFailure.getClass().getName(),
                this.verificationFailure instanceof KuraException);
        assertEquals(expectedErrorCode, ((KuraException) this.verificationFailure).getCode());
    }

    protected void thenTheProofHasStringClaim(final String name, final String expectedValue) {
        assertNotNull("expected a verification proof", this.proof);
        assertTrue("proof has no claim '" + name + "' in " + this.proof.getClaims(),
                this.proof.getClaims().containsKey(name));
        assertEquals(expectedValue, this.proof.getClaims().get(name));
    }

    protected void thenTheProofHasNullClaim(final String name) {
        assertNotNull("expected a verification proof", this.proof);
        assertTrue("proof has no claim '" + name + "' in " + this.proof.getClaims(),
                this.proof.getClaims().containsKey(name));
        assertNull("claim '" + name + "' should be null", this.proof.getClaims().get(name));
    }

    protected void thenTheProofClaimsCannotBeModified() {
        assertNotNull("expected a verification proof", this.proof);

        final Map<String, Object> claims = this.proof.getClaims();

        assertThrows(UnsupportedOperationException.class, () -> claims.put("injected", "value"));
    }

    protected void thenTheProofRecordsAVerificationTime() {
        assertNotNull("expected a verification proof", this.proof);
        assertNotNull("expected the proof to record when verification happened", this.proof.getVerifiedAt());
    }

    protected void thenTheProofExposesExpiresAt(final Instant expected) {
        assertNotNull("expected a verification proof", this.proof);
        assertTrue("expected the proof to expose exp", this.proof.getExpiresAt().isPresent());
        assertEquals(expected.getEpochSecond(), this.proof.getExpiresAt().get().getEpochSecond());
    }

    protected void thenTheProofExposesNoExpiresAt() {
        assertNotNull("expected a verification proof", this.proof);
        assertFalse("expected the proof to expose no exp", this.proof.getExpiresAt().isPresent());
    }

    protected void thenTheProofExposesNotBefore(final Instant expected) {
        assertNotNull("expected a verification proof", this.proof);
        assertTrue("expected the proof to expose nbf", this.proof.getNotBefore().isPresent());
        assertEquals(expected.getEpochSecond(), this.proof.getNotBefore().get().getEpochSecond());
    }

    protected void thenTheProofExposesNoNotBefore() {
        assertNotNull("expected a verification proof", this.proof);
        assertFalse("expected the proof to expose no nbf", this.proof.getNotBefore().isPresent());
    }

    protected void thenTheProofExposesIssuedAt(final Instant expected) {
        assertNotNull("expected a verification proof", this.proof);
        assertTrue("expected the proof to expose iat", this.proof.getIssuedAt().isPresent());
        assertEquals(expected.getEpochSecond(), this.proof.getIssuedAt().get().getEpochSecond());
    }

    protected void thenTheProofExposesNoIssuedAt() {
        assertNotNull("expected a verification proof", this.proof);
        assertFalse("expected the proof to expose no iat", this.proof.getIssuedAt().isPresent());
    }

    protected void thenTheProofExposesTokenId(final String expected) {
        assertNotNull("expected a verification proof", this.proof);
        assertTrue("expected the proof to expose jti", this.proof.getTokenID().isPresent());
        assertEquals(expected, this.proof.getTokenID().get());
    }

    protected void thenTheProofExposesNoTokenId() {
        assertNotNull("expected a verification proof", this.proof);
        assertFalse("expected the proof to expose no jti", this.proof.getTokenID().isPresent());
    }

    protected void thenTheKeystoreWasConsultedAgain() throws KuraException {
        verify(this.keystore.service(), atLeastOnce()).getEntry(anyString());
        verify(this.keystore.service(), atLeastOnce()).getEntries();
    }

    protected void thenTheKeystoreWasNotConsultedAgain() throws KuraException {
        verify(this.keystore.service(), never()).getEntries();
        verify(this.keystore.service(), never()).getEntry(anyString());
    }

    private void whenTheRequestIsVerified(final TokenVerifyRequest request) {
        resetVerificationOutcome();

        try {
            this.proof = this.verificationService.verify(request);
        } catch (final Exception e) {
            this.verificationFailure = e;
        }
    }

    private void resetIssuingOutcome() {
        this.issuedToken = null;
        this.issuedTokenInspector = null;
        this.issuingFailure = null;
    }

    private void resetVerificationOutcome() {
        this.proof = null;
        this.verificationFailure = null;
    }

    private JsonElement requireClaim(final String name) {
        thenATokenIsIssued();

        return this.issuedTokenInspector.claim(name)
                .orElseThrow(() -> new AssertionError("claim '" + name + "' not found in "
                        + this.issuedTokenInspector.payload()));
    }

    private JsonElement requireHeaderEntry(final String name) {
        thenATokenIsIssued();

        return this.issuedTokenInspector.headerEntry(name)
                .orElseThrow(() -> new AssertionError("header entry '" + name + "' not found in "
                        + this.issuedTokenInspector.header()));
    }

    private static boolean isPrimitiveString(final JsonElement element) {
        return element.isJsonPrimitive() && element.getAsJsonPrimitive().isString();
    }

    private static boolean isPrimitiveNumber(final JsonElement element) {
        return element.isJsonPrimitive() && element.getAsJsonPrimitive().isNumber();
    }

}
