/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt.common;

import java.lang.annotation.Annotation;

import org.eclipse.kura.core.token.jwt.issuer.JwtIssuingServiceOCD;

public final class IssuingConfig {

    private String keystoreTargetFilter = JwtIssuingServiceOCD.DEFAULT_KEYSTORE_TARGET_FILTER;
    private String signingKeyAlias = JwtIssuingServiceOCD.DEFAULT_SIGNING_KEY_ALIAS;
    private String issuer = JwtIssuingServiceOCD.DEFAULT_ISSUER;
    private int maximumLifetimeSeconds = JwtIssuingServiceOCD.DEFAULT_MAX_TOKEN_LIFETIME_SEC;

    private IssuingConfig() {
    }

    public static IssuingConfig defaults() {
        return new IssuingConfig();
    }

    public IssuingConfig withKeystoreTargetFilter(final String keystoreTargetFilter) {
        this.keystoreTargetFilter = keystoreTargetFilter;
        return this;
    }

    public IssuingConfig withSigningKeyAlias(final String signingKeyAlias) {
        this.signingKeyAlias = signingKeyAlias;
        return this;
    }

    public IssuingConfig withIssuer(final String issuer) {
        this.issuer = issuer;
        return this;
    }

    public IssuingConfig withMaximumLifetimeSeconds(final int maximumLifetimeSeconds) {
        this.maximumLifetimeSeconds = maximumLifetimeSeconds;
        return this;
    }

    public JwtIssuingServiceOCD toOcd() {
        return new JwtIssuingServiceOCD() {

            @Override
            public Class<? extends Annotation> annotationType() {
                return JwtIssuingServiceOCD.class;
            }

            @Override
            public String KeystoreService_target() {
                return IssuingConfig.this.keystoreTargetFilter;
            }

            @Override
            public String signing_key_alias() {
                return IssuingConfig.this.signingKeyAlias;
            }

            @Override
            public String issuer() {
                return IssuingConfig.this.issuer;
            }

            @Override
            public int maximum_lifetime_seconds() {
                return IssuingConfig.this.maximumLifetimeSeconds;
            }

        };
    }

}
