/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt.common;

import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.clearInvocations;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.security.KeyPair;
import java.security.KeyStore.Entry;
import java.security.KeyStore.PrivateKeyEntry;
import java.security.KeyStore.SecretKeyEntry;
import java.security.KeyStore.TrustedCertificateEntry;
import java.security.cert.Certificate;
import java.security.cert.X509Certificate;
import java.time.Instant;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

import javax.crypto.spec.SecretKeySpec;

import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.KuraException;
import org.eclipse.kura.configuration.ConfigurationService;
import org.eclipse.kura.core.testutil.pki.TestCA.TestCAException;
import org.eclipse.kura.security.keystore.KeystoreChangedEvent;
import org.eclipse.kura.security.keystore.KeystoreService;
import org.osgi.service.event.Event;

public final class KeystoreFixture {

    public static final String DEFAULT_PID = "org.eclipse.kura.core.keystore.FilesystemKeystoreServiceImpl";
    public static final String FOREIGN_PID = "org.eclipse.kura.core.keystore.AnotherKeystoreServiceImpl";

    private final String pid;
    private final Map<String, Entry> entries = new LinkedHashMap<>();
    private final KeystoreService keystoreService;

    public KeystoreFixture() {
        this(DEFAULT_PID);
    }

    public KeystoreFixture(final String pid) {
        this.pid = pid;
        this.keystoreService = mock(KeystoreService.class);

        try {
            when(this.keystoreService.getEntries()).thenReturn(this.entries);
            when(this.keystoreService.getEntry(anyString()))
                    .thenAnswer(invocation -> this.entries.get(invocation.getArgument(0, String.class)));
        } catch (final KuraException e) {
            throw new IllegalStateException("failed to set up the KeystoreService mock", e);
        }
    }

    public static KeystoreFixture alwaysFailing() {
        final KeystoreFixture fixture = new KeystoreFixture();

        try {
            when(fixture.keystoreService.getEntries()).thenThrow(new KuraException(KuraErrorCode.STORE_ERROR));
            when(fixture.keystoreService.getEntry(anyString())).thenThrow(new KuraException(KuraErrorCode.STORE_ERROR));
        } catch (final KuraException e) {
            throw new IllegalStateException("failed to set up the failing KeystoreService mock", e);
        }

        return fixture;
    }

    public KeystoreFixture withPrivateKeyEntry(final String alias, final KeyPair keyPair) throws TestCAException {
        return withPrivateKeyEntry(alias, keyPair, TestKeys.certificate(alias, keyPair));
    }

    public KeystoreFixture withPrivateKeyEntry(final String alias, final KeyPair keyPair,
            final X509Certificate certificate) {

        this.entries.put(alias, new PrivateKeyEntry(keyPair.getPrivate(), new Certificate[] { certificate }));

        return this;
    }

    public KeystoreFixture withNonRsaPrivateKeyEntry(final String alias) throws TestCAException {
        return withPrivateKeyEntry(alias, TestKeys.ecdsa(), TestKeys.certificate(alias, TestKeys.ecdsa()));
    }

    public KeystoreFixture withTrustedCertificate(final String alias, final KeyPair keyPair) throws TestCAException {
        return withTrustedCertificate(alias, TestKeys.certificate(alias, keyPair));
    }

    public KeystoreFixture withTrustedCertificate(final String alias, final KeyPair keyPair, final Instant validFrom,
            final Instant validTo) throws TestCAException {

        return withTrustedCertificate(alias, TestKeys.certificate(alias, keyPair, validFrom, validTo));
    }

    public KeystoreFixture withTrustedCertificate(final String alias, final X509Certificate certificate) {
        this.entries.put(alias, new TrustedCertificateEntry(certificate));

        return this;
    }

    public KeystoreFixture withSecretKeyEntry(final String alias) {
        this.entries.put(alias, new SecretKeyEntry(new SecretKeySpec(new byte[16], "AES")));

        return this;
    }

    public KeystoreFixture withoutEntry(final String alias) {
        this.entries.remove(alias);

        return this;
    }

    public KeystoreService service() {
        return this.keystoreService;
    }

    public String pid() {
        return this.pid;
    }

    public Map<String, Object> serviceProperties() {
        return Collections.singletonMap(ConfigurationService.KURA_SERVICE_PID, this.pid);
    }

    public KeystoreChangedEvent changedEvent() {
        return new KeystoreChangedEvent(this.pid);
    }

    public static KeystoreChangedEvent changedEventFrom(final String senderPid) {
        return new KeystoreChangedEvent(senderPid);
    }

    public static KeystoreChangedEvent changedEventWithoutSenderPid() {
        return new KeystoreChangedEvent(null);
    }

    public static Event unrelatedEventOnTheKeystoreTopic() {
        return new Event(KeystoreChangedEvent.EVENT_TOPIC,
                Collections.singletonMap(KeystoreChangedEvent.SENDER_PID_PROPERTY_KEY, DEFAULT_PID));
    }

    public void forgetRecordedInteractions() {
        clearInvocations(this.keystoreService);
    }

}
