/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt.common;

import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.cert.X509Certificate;
import java.security.interfaces.RSAPrivateKey;
import java.time.Duration;
import java.time.Instant;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

import org.bouncycastle.asn1.x500.X500Name;
import org.eclipse.kura.core.testutil.pki.TestCA;
import org.eclipse.kura.core.testutil.pki.TestCA.CertificateCreationOptions;
import org.eclipse.kura.core.testutil.pki.TestCA.TestCAException;

public final class TestKeys {

    private static final Duration DEFAULT_BACKDATE = Duration.ofMinutes(5);
    private static final Duration DEFAULT_VALIDITY = Duration.ofHours(1);

    private static final Map<Integer, KeyPair> RSA_KEY_PAIRS = new HashMap<>();

    private static KeyPair ecdsaKeyPair;

    private TestKeys() {
    }

    public static synchronized KeyPair rsa(final int index) throws TestCAException {
        KeyPair keyPair = RSA_KEY_PAIRS.get(index);

        if (keyPair == null) {
            keyPair = TestCA.generateKeyPair();
            RSA_KEY_PAIRS.put(index, keyPair);
        }

        return keyPair;
    }

    public static RSAPrivateKey rsaPrivateKey(final int index) throws TestCAException {
        return (RSAPrivateKey) rsa(index).getPrivate();
    }

    public static synchronized KeyPair ecdsa() throws TestCAException {
        if (ecdsaKeyPair == null) {
            try {
                final KeyPairGenerator generator = KeyPairGenerator.getInstance("EC");
                generator.initialize(256);
                ecdsaKeyPair = generator.generateKeyPair();
            } catch (final Exception e) {
                throw new TestCAException(e);
            }
        }

        return ecdsaKeyPair;
    }

    public static X509Certificate certificate(final String commonName, final KeyPair keyPair) throws TestCAException {
        final Instant now = Instant.now();

        return certificate(commonName, keyPair, now.minus(DEFAULT_BACKDATE), now.plus(DEFAULT_VALIDITY));
    }

    public static X509Certificate certificate(final String commonName, final KeyPair keyPair, final Instant validFrom,
            final Instant validTo) throws TestCAException {

        final boolean rsa = "RSA".equals(keyPair.getPrivate().getAlgorithm());

        return new TestCA(CertificateCreationOptions.builder(new X500Name("cn=" + commonName + ", dn=kura.test")) //
                .withSignatureAlgorithm(rsa ? "SHA256withRSA" : "SHA256withECDSA") //
                .withStartDate(Date.from(validFrom)) //
                .withEndDate(Date.from(validTo)) //
                .build(), keyPair).getCertificate();
    }

}
