/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt.common;

import java.security.PrivateKey;
import java.security.interfaces.ECPrivateKey;
import java.security.interfaces.RSAPrivateKey;
import java.time.Instant;
import java.util.List;
import java.util.Map;

import com.auth0.jwt.JWT;
import com.auth0.jwt.JWTCreator;
import com.auth0.jwt.algorithms.Algorithm;
import com.google.gson.Gson;
import com.google.gson.JsonObject;

public final class TestToken {

    private static final Gson GSON = new Gson();

    private final JWTCreator.Builder builder = JWT.create();

    private TestToken() {
    }

    public static TestToken builder() {
        return new TestToken();
    }

    public TestToken issuer(final String issuer) {
        this.builder.withIssuer(issuer);
        return this;
    }

    public TestToken subject(final String subject) {
        this.builder.withSubject(subject);
        return this;
    }

    public TestToken issuedAt(final Instant issuedAt) {
        this.builder.withIssuedAt(issuedAt);
        return this;
    }

    public TestToken expiresAt(final Instant expiresAt) {
        this.builder.withExpiresAt(expiresAt);
        return this;
    }

    public TestToken notBefore(final Instant notBefore) {
        this.builder.withNotBefore(notBefore);
        return this;
    }

    public TestToken tokenId(final String tokenId) {
        this.builder.withJWTId(tokenId);
        return this;
    }

    public TestToken audience(final String... audience) {
        this.builder.withAudience(audience);
        return this;
    }

    public TestToken keyId(final String keyId) {
        this.builder.withKeyId(keyId);
        return this;
    }

    public TestToken claim(final String name, final String value) {
        this.builder.withClaim(name, value);
        return this;
    }

    public TestToken claim(final String name, final Boolean value) {
        this.builder.withClaim(name, value);
        return this;
    }

    public TestToken claim(final String name, final List<?> value) {
        this.builder.withClaim(name, value);
        return this;
    }

    public TestToken claim(final String name, final Map<String, ?> value) {
        this.builder.withClaim(name, value);
        return this;
    }

    public TestToken nullClaim(final String name) {
        this.builder.withNullClaim(name);
        return this;
    }

    public String signedWith(final PrivateKey signingKey) {
        return this.builder.sign(algorithmFor(signingKey));
    }

    public static String withTamperedHeader(final String token) {
        final String[] segments = split(token);
        final JsonObject header = parse(segments[0]);

        header.addProperty("kid", "tampered-after-signing");

        return TokenInspector.encodeSegment(GSON.toJson(header)) + "." + segments[1] + "." + segments[2];
    }

    public static String withTamperedPayload(final String token) {
        final String[] segments = split(token);
        final JsonObject payload = parse(segments[1]);

        payload.addProperty("sub", "tampered.identity");

        return segments[0] + "." + TokenInspector.encodeSegment(GSON.toJson(payload)) + "." + segments[2];
    }

    public static String withTamperedSignature(final String token) {
        final String[] segments = split(token);
        final char first = segments[2].charAt(0);
        final String tamperedSignature = (first == 'A' ? 'B' : 'A') + segments[2].substring(1);

        return segments[0] + "." + segments[1] + "." + tamperedSignature;
    }

    private static Algorithm algorithmFor(final PrivateKey signingKey) {
        if (signingKey instanceof RSAPrivateKey rsaSigningKey) {
            return Algorithm.RSA256(null, rsaSigningKey);
        }

        if (signingKey instanceof ECPrivateKey ecSigningKey) {
            return Algorithm.ECDSA256(null, ecSigningKey);
        }

        throw new IllegalArgumentException("unsupported signing key type " + signingKey.getAlgorithm());
    }

    private static String[] split(final String token) {
        final String[] segments = token.split("\\.", -1);

        if (segments.length != 3) {
            throw new IllegalArgumentException("not a JWT, expected 3 segments but got " + segments.length);
        }

        return segments;
    }

    private static JsonObject parse(final String segment) {
        return GSON.fromJson(TokenInspector.decodeSegment(segment), JsonObject.class);
    }

}
