/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt.common;

import java.lang.annotation.Annotation;

import org.eclipse.kura.core.token.jwt.verifier.JwtVerificationServiceOCD;

public final class VerificationConfig {

    private String keystoreTargetFilter = JwtVerificationServiceOCD.DEFAULT_KEYSTORE_TARGET_FILTER;
    private String trustedIssuers = "";
    private String verificationKeyAliases = "";
    private int clockSkewSeconds = JwtVerificationServiceOCD.DEFAULT_CLOCK_SKEW_SECONDS;
    private boolean requireValidCertificate = JwtVerificationServiceOCD.DEFAULT_REQUIRE_VALID_CERTIFICATE;

    private VerificationConfig() {
    }

    public static VerificationConfig defaults() {
        return new VerificationConfig();
    }

    public VerificationConfig withKeystoreTargetFilter(final String keystoreTargetFilter) {
        this.keystoreTargetFilter = keystoreTargetFilter;
        return this;
    }

    public VerificationConfig withTrustedIssuers(final String trustedIssuers) {
        this.trustedIssuers = trustedIssuers;
        return this;
    }

    public VerificationConfig withVerificationKeyAliases(final String verificationKeyAliases) {
        this.verificationKeyAliases = verificationKeyAliases;
        return this;
    }

    public VerificationConfig withClockSkewSeconds(final int clockSkewSeconds) {
        this.clockSkewSeconds = clockSkewSeconds;
        return this;
    }

    public VerificationConfig withRequireValidCertificate(final boolean requireValidCertificate) {
        this.requireValidCertificate = requireValidCertificate;
        return this;
    }

    public JwtVerificationServiceOCD toOcd() {
        return new JwtVerificationServiceOCD() {

            @Override
            public Class<? extends Annotation> annotationType() {
                return JwtVerificationServiceOCD.class;
            }

            @Override
            public String KeystoreService_target() {
                return VerificationConfig.this.keystoreTargetFilter;
            }

            @Override
            public String trusted_issuers() {
                return VerificationConfig.this.trustedIssuers;
            }

            @Override
            public String verification_key_aliases() {
                return VerificationConfig.this.verificationKeyAliases;
            }

            @Override
            public int clock_skew_seconds() {
                return VerificationConfig.this.clockSkewSeconds;
            }

            @Override
            public boolean require_valid_certificate() {
                return VerificationConfig.this.requireValidCertificate;
            }

        };
    }

}
