/*******************************************************************************
 * Copyright (c) 2025 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.web;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;

import org.eclipse.kura.audit.AuditConstants;
import org.eclipse.kura.audit.AuditContext;
import org.junit.Test;

public class ConsoleTest {

    private HttpServletRequest request;
    private AuditContext result;

    // ----------------------------------------------------------------
    //
    // Scenarios
    //
    // ----------------------------------------------------------------

    @Test
    public void auditContextUsesRemoteAddrWhenXffHeaderIsPresent() {
        givenHttpRequestWithRemoteAddr("192.168.1.100");
        givenRequestHeader("X-FORWARDED-FOR", "6.6.6.6");

        whenInitAuditContextIsCalled();

        thenAuditIpIs("192.168.1.100");
    }

    @Test
    public void auditContextUsesRemoteAddrWhenXffHeaderIsAbsent() {
        givenHttpRequestWithRemoteAddr("192.168.1.100");

        whenInitAuditContextIsCalled();

        thenAuditIpIs("192.168.1.100");
    }

    @Test
    public void auditContextIncludesForwardedForFieldWhenXffHeaderIsPresent() {
        givenHttpRequestWithRemoteAddr("192.168.1.100");
        givenRequestHeader("X-FORWARDED-FOR", "6.6.6.6");

        whenInitAuditContextIsCalled();

        thenForwardedForFieldIs("6.6.6.6");
    }

    @Test
    public void auditContextOmitsForwardedForFieldWhenXffHeaderIsAbsent() {
        givenHttpRequestWithRemoteAddr("192.168.1.100");

        whenInitAuditContextIsCalled();

        thenForwardedForFieldIsAbsent();
    }

    @Test
    public void auditContextIpIsRemoteAddrEvenWhenSessionHasExistingAuditContext() {
        givenHttpRequestWithRemoteAddr("10.0.0.1");
        givenRequestHeader("X-FORWARDED-FOR", "1.2.3.4");
        givenSessionWithExistingAuditContext("10.0.0.1");

        whenInitAuditContextIsCalled();

        thenAuditIpIs("10.0.0.1");
        thenForwardedForFieldIs("1.2.3.4");
    }

    // ----------------------------------------------------------------
    //
    // Steps
    //
    // ----------------------------------------------------------------

    private void givenHttpRequestWithRemoteAddr(final String remoteAddr) {
        this.request = mock(HttpServletRequest.class);
        when(this.request.getRemoteAddr()).thenReturn(remoteAddr);
        when(this.request.getSession(false)).thenReturn(null);
        when(this.request.getRequestURI()).thenReturn("/admin/login/password");
    }

    private void givenRequestHeader(final String name, final String value) {
        when(this.request.getHeader(name)).thenReturn(value);
    }

    private void givenSessionWithExistingAuditContext(final String sessionIp) {
        final HttpSession session = mock(HttpSession.class);
        when(this.request.getSession(false)).thenReturn(session);

        final Map<String, String> props = new HashMap<>();
        props.put(AuditConstants.KEY_IP.getValue(), sessionIp);
        props.put(AuditConstants.KEY_ENTRY_POINT.getValue(), "WebConsole");
        final AuditContext sessionContext = new AuditContext(props);

        when(session.getAttribute("org.eclipse.kura.audit.context")).thenReturn(sessionContext);
    }

    private void whenInitAuditContextIsCalled() {
        this.result = new Console().initAuditContext(this.request);
    }

    private void thenAuditIpIs(final String expectedIp) {
        assertNotNull(this.result);
        assertEquals(expectedIp, this.result.getProperties().get(AuditConstants.KEY_IP.getValue()));
    }

    private void thenForwardedForFieldIs(final String expectedValue) {
        assertNotNull(this.result);
        assertEquals(expectedValue, this.result.getProperties().get("forwarded.for"));
    }

    private void thenForwardedForFieldIsAbsent() {
        assertNotNull(this.result);
        assertFalse("forwarded.for must not be present when X-Forwarded-For header is absent",
                this.result.getProperties().containsKey("forwarded.for"));
    }
}
