/*******************************************************************************
 * Copyright (c) 2021, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 * Content with portions generated by generative AI platform
 *******************************************************************************/
package org.eclipse.kura.core.keystore.crl;

import java.io.Closeable;
import java.io.File;
import java.net.URI;
import java.security.InvalidAlgorithmParameterException;
import java.security.NoSuchAlgorithmException;
import java.security.cert.CertStore;
import java.security.cert.X509CRL;
import java.security.cert.X509Certificate;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.OptionalLong;
import java.util.Set;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.ScheduledFuture;
import java.util.concurrent.TimeUnit;
import java.util.stream.Collectors;

import org.eclipse.kura.core.keystore.util.CRLUtil;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class CRLManager implements Closeable {

    private static final long MIN_RESCHEDULE_DELAY_MS = 30_000;

    private static final Logger logger = LoggerFactory.getLogger(CRLManager.class);

    private final CRLStore store;
    private final ScheduledExecutorService updateExecutor = Executors.newSingleThreadScheduledExecutor();
    private final ExecutorService downloadExecutor = Executors.newCachedThreadPool();

    private final List<DistributionPointState> referencedDistributionPoints = new ArrayList<>();
    private final long forceUpdateIntervalMs;
    private final long periodicReckeckIntervalMs;
    private final CRLVerifier verifier;

    private Optional<ScheduledFuture<?>> updateTask = Optional.empty();
    private Optional<Listener> listener;

    public CRLManager(final File storeFile, final long storeDelayMs, final long periodicRecheckIntervalMs,
            final long forceUpdateIntervalMs, final CRLVerifier verifier) {
        this.store = new CRLStore(storeFile, storeDelayMs);
        this.periodicReckeckIntervalMs = periodicRecheckIntervalMs;
        this.forceUpdateIntervalMs = forceUpdateIntervalMs;
        this.verifier = verifier;
        requestUpdate();
    }

    public void setListener(final Optional<Listener> listener) {
        this.listener = listener;
    }

    public synchronized boolean addDistributionPoint(final Set<URI> uris) {
        logger.info("referencing distribution points: {}", uris);

        final Optional<DistributionPointState> existing = this.referencedDistributionPoints.stream()
                .filter(p -> p.distributionPoints.equals(uris)).findAny();

        if (existing.isPresent()) {
            existing.get().ref();
            return false;
        } else {
            this.referencedDistributionPoints.add(new DistributionPointState(uris));
            requestUpdate();
            return true;
        }
    }

    public synchronized boolean removeDistributionPoint(final Set<URI> uris) {
        logger.info("unreferencing distribution points: {}", uris);

        if (this.referencedDistributionPoints.removeIf(p -> p.distributionPoints.equals(uris) && p.unref() <= 0)) {
            requestUpdate();
            return true;
        } else {
            return false;
        }
    }

    public boolean addTrustedCertificate(final X509Certificate entry) {

        final Set<URI> distributionPoints;

        try {
            distributionPoints = CRLUtil.getCrlURIs(entry);
        } catch (final Exception e) {
            logger.warn("failed to get distribution points for {}", entry.getSubjectX500Principal(), e);
            return false;
        }

        if (distributionPoints.isEmpty()) {
            logger.info("certificate {} has no CRL distribution points", entry.getSubjectX500Principal());
            return false;
        }

        return addDistributionPoint(distributionPoints);
    }

    public boolean removeTrustedCertificate(final X509Certificate entry) {

        try {
            final Set<URI> distributionPoints = CRLUtil.getCrlURIs(entry);

            return removeDistributionPoint(distributionPoints);

        } catch (final Exception e) {
            logger.warn("failed to get distribution points for {}", entry.getSubjectX500Principal(), e);
            return false;
        }
    }

    public synchronized List<X509CRL> getCrls() {
        return this.store.getCRLs()
                .stream()
                .map(StoredCRL::getCrl)
                .collect(Collectors.toList());
    }

    public CertStore getCertStore() throws InvalidAlgorithmParameterException, NoSuchAlgorithmException {
        return this.store.getCertStore();
    }

    public CRLStore getCRLStore() {
        return this.store;
    }

    @Override
    public void close() {
        this.listener = Optional.empty();
        this.updateTask.ifPresent(t -> t.cancel(false));
        this.updateExecutor.shutdownNow();
        this.downloadExecutor.shutdownNow();
    }

    private void requestUpdate() {
        if (this.updateTask.isPresent()) {
            this.updateTask.get().cancel(false);
        }

        this.updateTask = Optional.of(this.updateExecutor.schedule(() -> {
            try {
                update();
            } catch (final Exception e) {
                logger.warn("Error during CRL update", e);
            } finally {
                rescheduleBasedOnNextUpdate();
            }
        }, 5000, TimeUnit.MILLISECONDS));
    }

    private void rescheduleBasedOnNextUpdate() {
        final long nextUpdateDelayMs = this.store.getCRLs().stream().mapToLong(StoredCRL::getTimeToNextUpdateMs).min()
                .orElse(Long.MAX_VALUE);

        final long rawDelayMs = Math.min(nextUpdateDelayMs,
                Math.min(this.forceUpdateIntervalMs, this.periodicReckeckIntervalMs));
        final long scheduleDelayMs = Math.max(rawDelayMs, MIN_RESCHEDULE_DELAY_MS);

        if (this.updateTask.isPresent()) {
            this.updateTask.get().cancel(false);
        }

        logger.info("scheduling next CRL check in {} ms (nextUpdate-aligned)", scheduleDelayMs);
        this.updateTask = Optional.of(this.updateExecutor.schedule(() -> {
            try {
                update();
            } catch (final Exception e) {
                logger.warn("Error during CRL update", e);
            } finally {
                rescheduleBasedOnNextUpdate();
            }
        }, scheduleDelayMs, TimeUnit.MILLISECONDS));
    }

    private void update() {
        final long now = System.nanoTime();

        final List<PendingDownload> pendingDownloads = collectPendingDownloads(now);

        final List<DownloadResult> results = executeDownloads(pendingDownloads);

        final boolean changed = applyDownloadResults(results, now);

        if (changed) {
            this.listener.ifPresent(Listener::onCRLCacheChanged);
        }
    }

    private synchronized List<PendingDownload> collectPendingDownloads(final long now) {
        final List<PendingDownload> pending = new ArrayList<>();

        for (final DistributionPointState state : this.referencedDistributionPoints) {
            final Optional<StoredCRL> storedCrl = this.store.getCRLs().stream()
                    .filter(c -> c.getDistributionPoints().equals(state.distributionPoints)).findAny();

            if (storedCrl.isPresent() && storedCrl.get().isExpired()) {
                logger.warn("CRL expired for distribution points: {}", state.distributionPoints);
            }
            if (!storedCrl.isPresent()) {
                logger.warn("local CRL not accessible from distribution points: {}", state.distributionPoints);
            }

            if (needsDownload(state, storedCrl, now)) {
                pending.add(new PendingDownload(state, storedCrl,
                        CRLUtil.fetchCRL(state.distributionPoints, this.downloadExecutor)));
            }
        }

        return pending;
    }

    private List<DownloadResult> executeDownloads(final List<PendingDownload> pendingDownloads) {
        final List<DownloadResult> results = new ArrayList<>();

        for (final PendingDownload pending : pendingDownloads) {
            try {
                final X509CRL crl = pending.future.get(1, TimeUnit.MINUTES);
                results.add(new DownloadResult(pending, crl, null));
            } catch (final InterruptedException e) {
                Thread.currentThread().interrupt();
                logger.warn("failed to download CRL from {}", pending.state.distributionPoints, e);
                pending.future.cancel(true);
                results.add(new DownloadResult(pending, null, e));
            } catch (final Exception e) {
                logger.warn("failed to download CRL from {}", pending.state.distributionPoints, e);
                pending.future.cancel(true);
                results.add(new DownloadResult(pending, null, e));
            }
        }

        return results;
    }

    private synchronized boolean applyDownloadResults(final List<DownloadResult> results, final long now) {
        boolean changed = false;

        for (final DownloadResult result : results) {
            if (result.crl != null) {
                changed |= validateAndStoreCRL(now, result.pending.state, result.pending.storedCrl, result.crl);
            }
        }

        changed |= this.store.removeCRLs(c -> this.referencedDistributionPoints.stream()
                .noneMatch(p -> p.distributionPoints.equals(c.getDistributionPoints())));

        return changed;
    }

    private boolean needsDownload(final DistributionPointState state, final Optional<StoredCRL> storedCrl,
            final long now) {
        if (!storedCrl.isPresent() || storedCrl.get().isExpired()) {
            return true;
        }
        if (!state.lastDownloadInstantNanos.isPresent()) {
            return true;
        }
        if (TimeUnit.MILLISECONDS.convert(now - state.lastDownloadInstantNanos.getAsLong(),
                TimeUnit.NANOSECONDS) > this.forceUpdateIntervalMs) {
            return true;
        }
        return storedCrl.get().isNearingExpiry(this.forceUpdateIntervalMs);
    }

    private static class PendingDownload {

        final DistributionPointState state;
        final Optional<StoredCRL> storedCrl;
        final CompletableFuture<X509CRL> future;

        PendingDownload(final DistributionPointState state, final Optional<StoredCRL> storedCrl,
                final CompletableFuture<X509CRL> future) {
            this.state = state;
            this.storedCrl = storedCrl;
            this.future = future;
        }
    }

    private static class DownloadResult {

        final PendingDownload pending;
        final X509CRL crl;
        @SuppressWarnings("unused")
        final Exception error;

        DownloadResult(final PendingDownload pending, final X509CRL crl, final Exception error) {
            this.pending = pending;
            this.crl = crl;
            this.error = error;
        }
    }

    private boolean validateAndStoreCRL(final long now, final DistributionPointState state,
            final Optional<StoredCRL> storedCrl, final X509CRL newCrl) {

        if (storedCrl.isPresent()) {
            final X509CRL stored = storedCrl.get().getCrl();

            if (stored.equals(newCrl)) {
                logger.info("current CRL is up to date");
                state.lastDownloadInstantNanos = OptionalLong.of(now);
                return false;
            }

            if (!stored.getIssuerX500Principal().equals(newCrl.getIssuerX500Principal())) {
                logger.warn("CRL issuer differs, not updating CRL");
                return false;
            }
        }

        if (this.verifier.verifyCRL(newCrl)) {
            this.store.storeCRL(new StoredCRL(state.distributionPoints, newCrl));
            state.lastDownloadInstantNanos = OptionalLong.of(now);
            return true;
        } else {
            logger.warn("CRL verification failed");
            return false;
        }
    }

    private class DistributionPointState {

        private int refCnt = 1;
        private OptionalLong lastDownloadInstantNanos = OptionalLong.empty();
        private final Set<URI> distributionPoints;

        public DistributionPointState(Set<URI> distributionPoints) {
            this.distributionPoints = distributionPoints;
        }

        int ref() {
            this.refCnt++;
            return this.refCnt;
        }

        int unref() {
            this.refCnt--;
            return this.refCnt;
        }
    }

    public interface CRLVerifier {

        public boolean verifyCRL(final X509CRL crl);
    }

    public interface Listener {

        public void onCRLCacheChanged();
    }
}
