/*******************************************************************************
 * Copyright (c) 2023, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.internal.rest.identity.provider.dto;

import java.util.Set;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(name = "PermissionSetDTO", description = "Permissions defined by the system and available for assignment.")
public class PermissionDTO {

    @Schema(description = "Defined permission names.")
    private final Set<String> permissions;

    public PermissionDTO(Set<String> permissions) {
        this.permissions = permissions;
    }

    public Set<String> getPermissions() {
        return this.permissions;
    }

}
