<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.eclipse.kura</groupId>
        <artifactId>target-platform</artifactId>
        <version>6.0.0-SNAPSHOT</version>
    </parent>
    <artifactId>org.usb4java</artifactId>
    <version>2.0.0-SNAPSHOT</version>
    <packaging>bundle</packaging>
    <name>usb4java</name>
    <description>usb4java libraries using libusb</description>
    <url>usb4java.org/</url>

    <properties>
        <usb4java.version>1.2.0</usb4java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.usb4java</groupId>
            <artifactId>usb4java</artifactId>
            <version>${usb4java.version}</version>
        </dependency>
        <dependency>
            <groupId>org.usb4java</groupId>
            <artifactId>libusb4java</artifactId>
            <version>${usb4java.version}</version>
            <classifier>linux-arm</classifier>
        </dependency>
        <dependency>
            <groupId>org.usb4java</groupId>
            <artifactId>libusb4java</artifactId>
            <version>${usb4java.version}</version>
            <classifier>linux-x86_64</classifier>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-clean-plugin</artifactId>
                <configuration>
                    <verbose>true</verbose>
                    <filesets>
                        <fileset>
                            <directory>lib/</directory>
                            <followSymlinks>false</followSymlinks>
                        </fileset>
                    </filesets>
                </configuration>
            </plugin>

            <plugin>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-dependencies</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.basedir}/lib</outputDirectory>
                            <excludeClassifiers>
                                sources,osx-x86_64,osx-x86,osx-aarch_64,windows-x86,windows-x86_64,linux-x86
                            </excludeClassifiers>
                            <excludeTransitive>true</excludeTransitive>
                            <stripVersion>true</stripVersion>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <version>2.3.5</version> <!-- This exact version is required to be built properly -->
                <extensions>true</extensions>
                <configuration>
                    <manifestLocation>META-INF</manifestLocation>
                    <instructions>
                        <Bundle-SymbolicName>${project.artifactId}</Bundle-SymbolicName>
                        <Bundle-Name>${project.name}</Bundle-Name>
                        <Bundle-Version>${project.version}</Bundle-Version>
                        <Bundle-ClassPath>
                            .,libusb4java-linux-arm.jar,libusb4java-linux-x86_64.jar,usb4java.jar</Bundle-ClassPath>
                        <Include-Resource>
                            ${project.basedir}/lib,
                            ${project.basedir}/about.html,
                            about_files=${project.basedir}/about_files/
                        </Include-Resource>
                        <Export-Package>
                            org.usb4java.*;version="1.2.0"
                        </Export-Package>
                        <Require-Capability>
                            osgi.ee;filter:="(&amp;(osgi.ee=JavaSE)(version=1.8))"
                        </Require-Capability>
                    </instructions>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>