/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.internal.rest.auth;

import java.security.Principal;
import java.util.Optional;

import jakarta.servlet.http.HttpServletRequest;

import org.eclipse.kura.audit.AuditConstants;
import org.eclipse.kura.audit.AuditContext;
import org.eclipse.kura.identity.IdentityTokenService;
import org.eclipse.kura.identity.VerifiedAccessToken;
import org.eclipse.kura.rest.auth.AuthenticationProvider;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import jakarta.annotation.Priority;
import jakarta.ws.rs.container.ContainerRequestContext;

@Priority(150)
public class JwtAuthenticationProvider implements AuthenticationProvider {

    private static final Logger auditLogger = LoggerFactory.getLogger("AuditLogger");

    private final IdentityTokenService identityTokenService;

    public JwtAuthenticationProvider(final IdentityTokenService identityTokenService) {
        this.identityTokenService = identityTokenService;
    }

    @Override
    public Optional<Principal> authenticate(final HttpServletRequest request,
            final ContainerRequestContext requestContext) {
        final String authorization = requestContext.getHeaderString("Authorization");
        if (authorization == null || !authorization.startsWith("Bearer ")) {
            return Optional.empty();
        }

        final String token = authorization.substring("Bearer ".length()).trim();
        if (token.isEmpty()) {
            return Optional.empty();
        }

        final Optional<VerifiedAccessToken> decoded = this.identityTokenService.verifyAccessToken(token);
        if (!decoded.isPresent()) {
            return Optional.empty();
        }

        final String identityName = decoded.get().getIdentityName();
        final AuditContext auditContext = AuditContext.currentOrInternal();
        auditContext.getProperties().put(AuditConstants.KEY_IDENTITY.getValue(), identityName);
        auditLogger.info("{} Rest - Success - Authentication succeeded via JWT provider", auditContext);

        return Optional.of(() -> identityName);
    }

    @Override
    public void onEnabled() {
        // no need
    }

    @Override
    public void onDisabled() {
        // no need
    }
}
