/*******************************************************************************
 * Copyright (c) 2025 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.internal.rest.auth;

import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.Optional;
import java.util.Set;

import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.KuraException;
import org.eclipse.kura.identity.AssignedPermissions;
import org.eclipse.kura.identity.IdentityConfiguration;
import org.eclipse.kura.identity.IdentityConfigurationComponent;
import org.eclipse.kura.identity.IdentityService;
import org.eclipse.kura.identity.PasswordConfiguration;
import org.eclipse.kura.identity.PasswordHash;
import org.eclipse.kura.identity.Permission;
import org.eclipse.kura.identity.TokenConfiguration;

public class RestIdentityHelper {

    private final IdentityService identityService;

    public RestIdentityHelper(final IdentityService identityService) {
        this.identityService = identityService;
    }

    public void checkPassword(final String username, final char[] password) throws KuraException {
        identityService.checkPassword(username, password);
    }

    public boolean isPasswordChangeRequired(final String username) throws KuraException {
        return passwordConfiguration(username).map(PasswordConfiguration::isPasswordChangeNeeded).orElse(false);
    }

    public Optional<PasswordHash> getPasswordHash(final String username) throws KuraException {
        return passwordConfiguration(username).flatMap(PasswordConfiguration::getPasswordHash);
    }

    public Set<Permission> getAssignedPermissions(final String username) throws KuraException {
        return identityConfiguration(username, AssignedPermissions.class)
                .flatMap(c -> c.getComponent(AssignedPermissions.class))
                .map(AssignedPermissions::getPermissions)
                .orElse(Collections.emptySet());
    }

    public boolean identityExists(final String username) throws KuraException {
        return identityService.getIdentityConfiguration(username, Collections.emptySet()).isPresent();
    }

    public void checkPermission(final String username, final Permission permission) throws KuraException {
        identityService.checkPermission(username, permission);
    }

    public void updatePassword(final String username, final char[] newPassword, final boolean passwordChangeNeeded)
            throws KuraException {
        final PasswordConfiguration existingPasswordConfig = passwordConfiguration(username)
                .orElseThrow(() -> new KuraException(KuraErrorCode.SECURITY_EXCEPTION));

        final PasswordConfiguration updatedPasswordConfig = new PasswordConfiguration(passwordChangeNeeded,
                existingPasswordConfig.isPasswordAuthEnabled(), Optional.of(newPassword), Optional.empty());

        final IdentityConfiguration identityConfiguration = new IdentityConfiguration(username,
                Collections.singletonList(updatedPasswordConfig));

        identityService.updateIdentityConfiguration(identityConfiguration);
    }

    public PasswordHash computePasswordHash(final char[] password) throws KuraException {
        return identityService.computePasswordHash(password);
    }

    // Token authentication support

    /**
     * Finds an identity by its authentication token.
     * Works for both regular and temporary identities.
     *
     * @param token the authentication token
     * @return the identity name if found, empty otherwise
     * @throws KuraException if lookup fails
     */
    public Optional<String> getIdentityNameByToken(final String token) throws KuraException {
        return identityService.findIdentityByToken(token);
    }

    /**
     * Validates a token for a given identity.
     * Checks that the token matches and is not expired.
     *
     * @param identityName the identity name
     * @param token        the token to validate
     * @throws KuraException if the token is invalid, doesn't match, or is expired
     */
    public void checkToken(final String identityName, final String token) throws KuraException {
        Optional<IdentityConfiguration> config = identityService.getIdentityConfiguration(identityName,
                Set.of(TokenConfiguration.class));

        if (!config.isPresent()) {
            throw new KuraException(KuraErrorCode.SECURITY_EXCEPTION, "Identity not found");
        }

        TokenConfiguration tokenConfig = config.get().getComponent(TokenConfiguration.class)
                .orElseThrow(() -> new KuraException(KuraErrorCode.SECURITY_EXCEPTION, "No token configured"));

        if (!tokenConfig.isTokenAuthEnabled()) {
            throw new KuraException(KuraErrorCode.SECURITY_EXCEPTION, "Token authentication not enabled");
        }

        if (tokenConfig.isExpired()) {
            throw new KuraException(KuraErrorCode.SECURITY_EXCEPTION, "Token expired");
        }

        if (!tokenConfig.getToken().equals(token)) {
            throw new KuraException(KuraErrorCode.SECURITY_EXCEPTION, "Invalid token");
        }
    }

    private Optional<IdentityConfiguration> identityConfiguration(final String username,
            final Class<? extends IdentityConfigurationComponent>... components) throws KuraException {
        final Set<Class<? extends IdentityConfigurationComponent>> componentsToReturn = new HashSet<>(
                Arrays.asList(components));
        return identityService.getIdentityConfiguration(username, componentsToReturn);
    }

    private Optional<PasswordConfiguration> passwordConfiguration(final String username) throws KuraException {
        return identityConfiguration(username, PasswordConfiguration.class)
                .flatMap(c -> c.getComponent(PasswordConfiguration.class));
    }
}
