/*******************************************************************************
 * Copyright (c) 2023, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.internal.rest.auth;

import java.security.Principal;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;

import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.KuraException;
import org.eclipse.kura.audit.AuditConstants;
import org.eclipse.kura.audit.AuditContext;
import org.eclipse.kura.identity.LoginBannerService;
import org.eclipse.kura.identity.PasswordHash;
import org.eclipse.kura.identity.PasswordStrengthRequirements;
import org.eclipse.kura.identity.PasswordStrengthVerificationService;
import org.eclipse.kura.internal.rest.auth.dto.AuthenticationInfoDTO;
import org.eclipse.kura.internal.rest.auth.dto.AuthenticationResponseDTO;
import org.eclipse.kura.internal.rest.auth.dto.IdentityInfoDTO;
import org.eclipse.kura.internal.rest.auth.dto.UpdatePasswordDTO;
import org.eclipse.kura.internal.rest.auth.dto.UsernamePasswordDTO;
import org.eclipse.kura.internal.rest.auth.dto.XsrfTokenDTO;
import org.eclipse.kura.internal.rest.provider.RestServiceOptions;
import org.eclipse.kura.request.handler.jaxrs.DefaultExceptionHandler;
import org.eclipse.kura.util.validation.PasswordStrengthValidators;
import org.eclipse.kura.util.validation.Validator;
import org.eclipse.kura.util.validation.ValidatorOptions;
import org.osgi.service.cm.ConfigurationAdmin;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.headers.Header;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.parameters.RequestBody;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.security.SecurityRequirements;
import io.swagger.v3.oas.annotations.tags.Tag;

import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;
import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.WebApplicationException;
import jakarta.ws.rs.container.ContainerRequestContext;
import jakarta.ws.rs.core.Context;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response.Status;

@SuppressWarnings("restriction")
@Tag(name = "Session", description = "Authentication and session lifecycle; availability depends on REST service settings.")
@Path(SessionRestServiceConstants.BASE_PATH)
public class SessionRestService {

    private static final String AUDIT_FORMAT_STRING = "{} Rest - Failure - {}";
    private static final String INVALID_SESSION_MESSAGE = "Current session is not valid";
    private static final String BAD_USERNAME_OR_PASSWORD_MESSAGE = "Authentication failed as username or password not matching";
    private static final String PASSWORD_CHANGE_SAME_PASSWORD_MESSAGE = "Password change failed as previous password equals new one";

    private static final Logger auditLogger = LoggerFactory.getLogger("AuditLogger");

    private final RestIdentityHelper identityHelper;
    private final RestSessionHelper restSessionHelper;
    private final ConfigurationAdmin configAdmin;
    private final PasswordStrengthVerificationService passwordStrengthVerificationService;
    private final LoginBannerService loginBannerService;
    private RestServiceOptions options;

    public SessionRestService(final RestIdentityHelper identityHelper, final RestSessionHelper restSessionHelper,
            final ConfigurationAdmin configurationAdmin,
            final PasswordStrengthVerificationService passwordStrengthVerificationService,
            final LoginBannerService loginBannerService) {
        this.identityHelper = identityHelper;
        this.restSessionHelper = restSessionHelper;
        this.configAdmin = configurationAdmin;
        this.passwordStrengthVerificationService = passwordStrengthVerificationService;
        this.loginBannerService = loginBannerService;
    }

    public void setOptions(final RestServiceOptions options) {
        this.options = options;
    }

    @POST
    @Path(SessionRestServiceConstants.LOGIN_PASSWORD_PATH)
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    @SecurityRequirements
    @Operation(operationId = "post_session_v1_login_password", summary = "Create a password session",
            description = "Creates a session cookie. Fetch xsrfToken next. If passwordChangeNeeded is true, changePassword must precede API access.",
            requestBody = @RequestBody(required = true,
                    content = @Content(mediaType = MediaType.APPLICATION_JSON,
                            schema = @Schema(implementation = UsernamePasswordDTO.class))))
    @ApiResponse(responseCode = "200", description = "Authentication result.",
            headers = @Header(name = "Set-Cookie", description = "Session cookie lifecycle; preserve cookies between requests.",
                    schema = @Schema(type = "string")),
            content = @Content(mediaType = MediaType.APPLICATION_JSON,
                            schema = @Schema(implementation = AuthenticationResponseDTO.class)))
    @ApiResponse(responseCode = "400", ref = "#/components/responses/BadRequest")
    @ApiResponse(responseCode = "401", ref = "#/components/responses/Unauthorized")
    @ApiResponse(responseCode = "404", ref = "#/components/responses/Disabled")
    @ApiResponse(responseCode = "500", ref = "#/components/responses/InternalError")
    public AuthenticationResponseDTO authenticateWithUsernameAndPassword(final UsernamePasswordDTO usernamePassword,
            @Context final HttpServletRequest request) {

        if (!options.isSessionManagementEnabled() || !options.isPasswordAuthEnabled()) {
            throw new WebApplicationException(Status.NOT_FOUND);
        }

        final AuditContext auditContext = AuditContext.currentOrInternal();

        usernamePassword.validate();

        auditContext.getProperties().put(AuditConstants.KEY_IDENTITY.getValue(), usernamePassword.getUsername());

        try {

            this.identityHelper.checkPassword(usernamePassword.getUsername(),
                    usernamePassword.getPassword().toCharArray());

            final HttpSession session = this.restSessionHelper.createNewAuthenticatedSession(request,
                    usernamePassword.getUsername());

            final AuthenticationResponseDTO response = buildAuthenticationResponse(usernamePassword.getUsername(),
                    this.loginBannerService.getPostLoginBanner());

            if (response.isPasswordChangeNeeded()) {
                this.restSessionHelper.lockSession(session);
            }

            auditLogger.info("{} Rest - Success - Create session via password authentication succeeded", auditContext);

            return response;

        } catch (final KuraException e) {
            invalidateCurrentSession(request);
            auditLogger.warn(AUDIT_FORMAT_STRING, auditContext, BAD_USERNAME_OR_PASSWORD_MESSAGE);
            throw DefaultExceptionHandler.buildWebApplicationException(Status.UNAUTHORIZED,
                    BAD_USERNAME_OR_PASSWORD_MESSAGE);
        } catch (final Exception e) {
            invalidateCurrentSession(request);
            auditLogger.warn(AUDIT_FORMAT_STRING, auditContext, BAD_USERNAME_OR_PASSWORD_MESSAGE);
            throw DefaultExceptionHandler.buildWebApplicationException(Status.UNAUTHORIZED,
                    BAD_USERNAME_OR_PASSWORD_MESSAGE);
        }
    }

    @POST
    @Path(SessionRestServiceConstants.LOGIN_CERTIFICATE_PATH)
    @Produces(MediaType.APPLICATION_JSON)
    @SecurityRequirements
    @Operation(operationId = "post_session_v1_login_certificate", summary = "Create a certificate session",
            description = "Requires a trusted client certificate on a mutual-TLS port. Creates a session cookie; fetch xsrfToken next.")
    @ApiResponse(responseCode = "200", description = "Authentication result.",
            headers = @Header(name = "Set-Cookie", description = "Session cookie lifecycle; preserve cookies between requests.",
                    schema = @Schema(type = "string")),
            content = @Content(mediaType = MediaType.APPLICATION_JSON,
                            schema = @Schema(implementation = AuthenticationResponseDTO.class)))
    @ApiResponse(responseCode = "401", ref = "#/components/responses/Unauthorized")
    @ApiResponse(responseCode = "404", ref = "#/components/responses/Disabled")
    @ApiResponse(responseCode = "500", ref = "#/components/responses/InternalError")
    public AuthenticationResponseDTO authenticateWithCertificate(@Context final HttpServletRequest request,
            @Context final ContainerRequestContext requestContext) {
        if (!options.isSessionManagementEnabled() || !options.isCertificateAuthEnabled()) {
            throw new WebApplicationException(Status.NOT_FOUND);
        }

        try {

            final CertificateAuthenticationProvider certificateAuthProvider = new CertificateAuthenticationProvider(
                    identityHelper);

            final Optional<Principal> principal = certificateAuthProvider.authenticate(requestContext,
                    "Create session via certificate authentication");

            if (principal.isPresent()) {
                this.restSessionHelper.createNewAuthenticatedSession(request, principal.get().getName());
            } else {

                throw DefaultExceptionHandler.buildWebApplicationException(Status.UNAUTHORIZED,
                        "Certificate authentication failed");
            }

            return buildAuthenticationResponse(principal.get().getName(), this.loginBannerService.getPostLoginBanner());
        } catch (final Exception e) {
            invalidateCurrentSession(request);
            throw e;
        }
    }

    @GET
    @Path(SessionRestServiceConstants.XSRF_TOKEN_PATH)
    @SecurityRequirement(name = "sessionCookie")
    @Operation(operationId = "get_session_v1_xsrfToken", summary = "Read the session XSRF token",
            description = "Requires an existing session cookie. This is the only session-authenticated endpoint exempt from X-XSRF-Token.")
    @ApiResponse(responseCode = "200", description = "Authentication result.",
            content = @Content(mediaType = MediaType.APPLICATION_JSON,
                            schema = @Schema(implementation = XsrfTokenDTO.class)))
    @ApiResponse(responseCode = "401", ref = "#/components/responses/Unauthorized")
    @ApiResponse(responseCode = "404", ref = "#/components/responses/Disabled")
    @ApiResponse(responseCode = "500", ref = "#/components/responses/InternalError")
    public XsrfTokenDTO getXSRFToken(@Context final HttpServletRequest request,
            @Context final ContainerRequestContext requestContext) {
        if (!options.isSessionManagementEnabled()) {
            throw new WebApplicationException(Status.NOT_FOUND);
        }

        final Optional<HttpSession> session = this.restSessionHelper.getExistingSession(request);

        if (!session.isPresent()) {
            throw DefaultExceptionHandler.buildWebApplicationException(Status.UNAUTHORIZED, INVALID_SESSION_MESSAGE);
        }

        if (!this.restSessionHelper.getCurrentPrincipal(requestContext).isPresent()) {
            throw DefaultExceptionHandler.buildWebApplicationException(Status.UNAUTHORIZED, INVALID_SESSION_MESSAGE);
        }

        return new XsrfTokenDTO(this.restSessionHelper.getOrCreateXsrfToken(session.get()));
    }

    @POST
    @Path(SessionRestServiceConstants.CHANGE_PASSWORD_PATH)
    @Operation(operationId = "post_session_v1_changePassword", summary = "Change the current password",
            description = "Requires currentPassword and newPassword. Replaces the session; fetch a new XSRF token. Allowed for a locked session.",
            requestBody = @RequestBody(required = true,
                    content = @Content(mediaType = MediaType.APPLICATION_JSON,
                            schema = @Schema(implementation = UpdatePasswordDTO.class))))
    @ApiResponse(responseCode = "204", ref = "#/components/responses/SessionChanged")
    @ApiResponse(responseCode = "400", ref = "#/components/responses/BadRequest")
    @ApiResponse(responseCode = "401", ref = "#/components/responses/Unauthorized")
    @ApiResponse(responseCode = "500", ref = "#/components/responses/InternalError")
    public void updateUserPassword(@Context final ContainerRequestContext requestContext,
            @Context final HttpServletRequest request, final UpdatePasswordDTO passwordUpdate) {

        passwordUpdate.validate();

        try {
            final Optional<String> username = this.restSessionHelper.getCurrentPrincipal(requestContext)
                    .flatMap(c -> Optional.ofNullable(c.getName()));

            if (!username.isPresent()) {
                throw DefaultExceptionHandler.buildWebApplicationException(Status.UNAUTHORIZED,
                        INVALID_SESSION_MESSAGE);
            }

            this.identityHelper.checkPassword(username.get(), passwordUpdate.getCurrentPassword().toCharArray());

            final String newPassword = passwordUpdate.getNewPassword();

            validatePasswordStrength(newPassword);

            if (isSamePassword(username.get(), newPassword)) {
                throw DefaultExceptionHandler.buildWebApplicationException(Status.BAD_REQUEST,
                        PASSWORD_CHANGE_SAME_PASSWORD_MESSAGE);
            }

            this.identityHelper.updatePassword(username.get(), newPassword.toCharArray(), false);

            final HttpSession session = this.restSessionHelper.createNewAuthenticatedSession(request, username.get());
            this.restSessionHelper.unlockSession(session);

        } catch (final WebApplicationException e) {
            invalidateCurrentSession(request);
            throw e;
        } catch (final KuraException e) {
            invalidateCurrentSession(request);
            if (e.getCode() == KuraErrorCode.SECURITY_EXCEPTION) {
                auditLogger.warn(AUDIT_FORMAT_STRING, AuditContext.currentOrInternal(),
                        BAD_USERNAME_OR_PASSWORD_MESSAGE);
                throw DefaultExceptionHandler.buildWebApplicationException(Status.UNAUTHORIZED,
                        BAD_USERNAME_OR_PASSWORD_MESSAGE);
            }
            throw DefaultExceptionHandler.toWebApplicationException(e);
        } catch (final Exception e) {
            invalidateCurrentSession(request);
            auditLogger.warn(AUDIT_FORMAT_STRING, AuditContext.currentOrInternal(), BAD_USERNAME_OR_PASSWORD_MESSAGE);
            throw DefaultExceptionHandler.buildWebApplicationException(Status.UNAUTHORIZED,
                    BAD_USERNAME_OR_PASSWORD_MESSAGE);
        }
    }

    @POST
    @Path(SessionRestServiceConstants.LOGOUT_PATH)
    @Operation(operationId = "post_session_v1_logout", summary = "End the current session",
            description = "Invalidates the current session and expires request cookies. Session authentication requires X-XSRF-Token.")
    @ApiResponse(responseCode = "204", ref = "#/components/responses/SessionChanged")
    @ApiResponse(responseCode = "401", ref = "#/components/responses/Unauthorized")
    @ApiResponse(responseCode = "404", ref = "#/components/responses/Disabled")
    @ApiResponse(responseCode = "500", ref = "#/components/responses/InternalError")
    public void logout(@Context final HttpServletRequest request, @Context final HttpServletResponse response,
            @Context final ContainerRequestContext requestContext) {
        if (!options.isSessionManagementEnabled()) {
            throw new WebApplicationException(Status.NOT_FOUND);
        }

        if (!this.restSessionHelper.getCurrentPrincipal(requestContext).isPresent()) {
            throw DefaultExceptionHandler.buildWebApplicationException(Status.UNAUTHORIZED, INVALID_SESSION_MESSAGE);
        }

        this.restSessionHelper.logout(request, response);

        auditLogger.info("{} Rest - Success - Logout succeeded", AuditContext.currentOrInternal());
    }

    @GET
    @Path(SessionRestServiceConstants.CURRENT_IDENTITY)
    @Produces(MediaType.APPLICATION_JSON)
    @Operation(operationId = "get_session_v1_currentIdentity", summary = "Read the current identity",
            description = "Returns identity, password-change status and assigned permissions. Session authentication requires X-XSRF-Token.")
    @ApiResponse(responseCode = "200", description = "Authentication result.",
            content = @Content(mediaType = MediaType.APPLICATION_JSON,
                            schema = @Schema(implementation = IdentityInfoDTO.class)))
    @ApiResponse(responseCode = "401", ref = "#/components/responses/Unauthorized")
    @ApiResponse(responseCode = "404", ref = "#/components/responses/Disabled")
    @ApiResponse(responseCode = "500", ref = "#/components/responses/InternalError")
    public IdentityInfoDTO getCurrentIdentityInfo(@Context final ContainerRequestContext requestContext,
            @Context final HttpServletRequest request) {
        if (!options.isSessionManagementEnabled()) {
            throw new WebApplicationException(Status.NOT_FOUND);
        }

        final Optional<Principal> currentPrincipal = this.restSessionHelper.getCurrentPrincipal(requestContext);

        if (!currentPrincipal.isPresent()) {
            throw DefaultExceptionHandler.buildWebApplicationException(Status.UNAUTHORIZED, INVALID_SESSION_MESSAGE);
        }

        final String identityName = currentPrincipal.get().getName();
        try {
            final Set<String> permissions = this.identityHelper.getAssignedPermissions(identityName).stream()
                    .map(p -> p.getName()).collect(java.util.stream.Collectors.toSet());
            final boolean needsPasswordChange = this.identityHelper.isPasswordChangeRequired(identityName);

            return new IdentityInfoDTO(identityName, needsPasswordChange, permissions);
        } catch (final Exception e) {
            throw DefaultExceptionHandler.toWebApplicationException(e);
        }
    }

    @GET
    @Path(SessionRestServiceConstants.AUTHENTICATION_INFO)
    @Produces(MediaType.APPLICATION_JSON)
    @SecurityRequirements
    @Operation(operationId = "get_session_v1_authenticationInfo", summary = "Read authentication options",
            description = "Returns password-login availability, usable certificate-login ports and an optional pre-login banner.")
    @ApiResponse(responseCode = "200", description = "Authentication result.",
            content = @Content(mediaType = MediaType.APPLICATION_JSON,
                            schema = @Schema(implementation = AuthenticationInfoDTO.class)))
    @ApiResponse(responseCode = "500", ref = "#/components/responses/InternalError")
    public AuthenticationInfoDTO getAuthenticationMethodInfo() {

        final boolean isPasswordAuthEnabled = options.isPasswordAuthEnabled();
        final boolean isCertificateAuthenticationEnabled = options.isCertificateAuthEnabled();

        final String preLoginBannerMessage = loginBannerService.getPreLoginBanner().orElse(null);

        if (!isCertificateAuthenticationEnabled) {
            return new AuthenticationInfoDTO(isPasswordAuthEnabled, false, null, preLoginBannerMessage);
        }

        final Map<String, Object> httpServiceConfig = ConfigurationAdminHelper
                .loadHttpServiceConfigurationProperties(configAdmin);

        final Set<Integer> httpsClientAuthPorts = ConfigurationAdminHelper.getHttpsMutualAuthPorts(httpServiceConfig);

        if (!httpsClientAuthPorts.isEmpty()) {
            return new AuthenticationInfoDTO(isPasswordAuthEnabled, true, httpsClientAuthPorts, preLoginBannerMessage);
        } else {
            return new AuthenticationInfoDTO(isPasswordAuthEnabled, false, null, preLoginBannerMessage);
        }

    }

    private void validatePasswordStrength(final String newPassword) {
        PasswordStrengthRequirements passwordStrengthRequirements;
        try {
            passwordStrengthRequirements = this.passwordStrengthVerificationService.getPasswordStrengthRequirements();
        } catch (KuraException e) {
            throw DefaultExceptionHandler.toWebApplicationException(e);
        }

        final ValidatorOptions validationOptions = new ValidatorOptions(
                passwordStrengthRequirements.getPasswordMinimumLength(), passwordStrengthRequirements.digitsRequired(),
                passwordStrengthRequirements.bothCasesRequired(),
                passwordStrengthRequirements.specialCharactersRequired());

        final List<Validator<String>> validators = PasswordStrengthValidators.fromConfig(validationOptions);

        final List<String> errors = new ArrayList<>();

        for (final Validator<String> validator : validators) {
            validator.validate(newPassword, errors::add);

            if (!errors.isEmpty()) {
                throw DefaultExceptionHandler.buildWebApplicationException(Status.BAD_REQUEST,
                        "The new password does not satisfy password strenght requirements: " + errors.get(0));
            }
        }
    }

    private AuthenticationResponseDTO buildAuthenticationResponse(final String username,
            final Optional<String> message) {
        final boolean needsPasswordChange;
        try {
            needsPasswordChange = this.identityHelper.isPasswordChangeRequired(username);
        } catch (final Exception e) {
            throw DefaultExceptionHandler.buildWebApplicationException(Status.INTERNAL_SERVER_ERROR,
                    "An internal error occurred");
        }

        if (message.isPresent()) {
            return new AuthenticationResponseDTO(needsPasswordChange, message.get());
        }

        return new AuthenticationResponseDTO(needsPasswordChange);
    }

    private void invalidateCurrentSession(final HttpServletRequest request) {
        final HttpSession currentSession = request.getSession(false);

        if (currentSession != null) {
            currentSession.invalidate();
        }
    }

    private boolean isSamePassword(final String username, final String newPassword) {
        try {
            final Optional<PasswordHash> existingHash = this.identityHelper.getPasswordHash(username);
            if (!existingHash.isPresent()) {
                return false;
            }

            final PasswordHash newHash = this.identityHelper.computePasswordHash(newPassword.toCharArray());
            return existingHash.get().equals(newHash);
        } catch (final Exception e) {
            return false;
        }
    }
}
