/*******************************************************************************
 * Copyright (c) 2023, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.internal.rest.auth;

public class SessionRestServiceConstants {

    public static final String BASE_PATH = "/session";
    public static final String LOGIN_PASSWORD_PATH = "/v1/login/password";
    public static final String LOGIN_CERTIFICATE_PATH = "/v1/login/certificate";
    public static final String XSRF_TOKEN_PATH = "/v1/xsrfToken";
    public static final String CHANGE_PASSWORD_PATH = "/v1/changePassword";
    public static final String LOGOUT_PATH = "/v1/logout";
    public static final String CURRENT_IDENTITY = "/v1/currentIdentity";
    public static final String AUTHENTICATION_INFO = "/v1/authenticationInfo";
    public static final String BASE_PATH_V2 = "/session/v2";
    public static final String LOGIN_PASSWORD_PATH_V2 = "/login/password";
    public static final String LOGIN_CERTIFICATE_PATH_V2 = "/login/certificate";
    public static final String TOKEN_REFRESH_PATH_V2 = "/token/refresh";
    public static final String LOGOUT_PATH_V2 = "/logout";
    public static final String AUTHENTICATION_INFO_V2 = "/authenticationInfo";

    private SessionRestServiceConstants() {
    }
}
