/*******************************************************************************
 * Copyright (c) 2025 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.internal.rest.auth;

/**
 * Marker interface for principals that expose a token without requiring reflection.
 */
public interface TokenHolder {

    /**
     * Returns the token associated with the authenticated principal.
     * 
     * @return the token string or {@code null} when unavailable
     */
    String getToken();
}

