/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.internal.rest.auth;

import java.security.Principal;
import java.util.Optional;

import org.eclipse.kura.KuraException;
import org.eclipse.kura.rest.auth.AuthenticationProvider;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import jakarta.annotation.Priority;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.ws.rs.container.ContainerRequestContext;

/**
 * Authentication provider that validates authentication tokens for both regular and temporary identities.
 * This provider extracts tokens from the Authorization header and validates them
 * using the unified identity service.
 *
 * Supports token formats:
 * - "Bearer kura-temp-xxxxx" - temporary identity tokens
 * - "Bearer kura-token-xxxxx" - regular identity tokens
 * - "Kura-Token xxxxx" - simplified format for both types
 */
@Priority(150) // Between certificate (100) and password (200) authentication
public class TokenAuthenticationProvider implements AuthenticationProvider {

    private static final Logger logger = LoggerFactory.getLogger(TokenAuthenticationProvider.class);
    private static final String BEARER_PREFIX = "Bearer ";
    private static final String KURA_TOKEN_PREFIX = "Kura-Token ";

    private final RestIdentityHelper identityHelper;

    public TokenAuthenticationProvider(final RestIdentityHelper identityHelper) {
        this.identityHelper = identityHelper;
    }

    @Override
    public Optional<Principal> authenticate(final HttpServletRequest request,
            final ContainerRequestContext requestContext) {

        final String token = extractToken(request);
        if (token == null) {
            return Optional.empty();
        }

        try {
            // Find identity by token (works for both temporary and regular identities)
            Optional<String> identityName = identityHelper.getIdentityNameByToken(token);

            if (!identityName.isPresent()) {
                logger.debug("No identity found for provided token");
                return Optional.empty();
            }

            // Validate token (checks expiration, etc.)
            identityHelper.checkToken(identityName.get(), token);

            // Return principal with identity name (standard Principal, not TokenHolder)
            return Optional.of(() -> identityName.get());

        } catch (KuraException e) {
            logger.warn("Token authentication failed: {}", e.getMessage());
            logger.debug("Token authentication failure details", e);
            return Optional.empty();
        }
    }

    @Override
    public void onEnabled() {
        logger.info("Token authentication provider enabled");
    }

    @Override
    public void onDisabled() {
        logger.info("Token authentication provider disabled");
    }

    /**
     * Extracts authentication token from the Authorization header.
     *
     * Supports multiple formats:
     * - "Bearer kura-temp-*" - temporary identity tokens
     * - "Bearer kura-token-*" - regular identity tokens
     * - "Kura-Token *" - simplified format
     *
     * @param request the HTTP servlet request
     * @return the extracted token, or null if no valid token found
     */
    private String extractToken(HttpServletRequest request) {
        final String authHeader = request.getHeader("Authorization");
        if (authHeader == null) {
            return null;
        }

        if (authHeader.startsWith(BEARER_PREFIX)) {
            final String token = authHeader.substring(BEARER_PREFIX.length()).trim();
            // Accept tokens starting with "kura-temp-" (temporary) or "kura-token-" (regular)
            if (token.startsWith("kura-temp-") || token.startsWith("kura-token-")) {
                return token;
            }
        } else if (authHeader.startsWith(KURA_TOKEN_PREFIX)) {
            return authHeader.substring(KURA_TOKEN_PREFIX.length()).trim();
        }

        return null;
    }
}
