/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.container.provider;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotEquals;
import static org.junit.Assert.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.atLeastOnce;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.inOrder;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.Duration;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;

import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.KuraException;
import org.eclipse.kura.configuration.ComponentConfiguration;
import org.eclipse.kura.configuration.ConfigurationService;
import org.eclipse.kura.container.orchestration.ContainerConfiguration;
import org.eclipse.kura.container.orchestration.ContainerInstanceDescriptor;
import org.eclipse.kura.container.orchestration.ContainerOrchestrationService;
import org.eclipse.kura.container.orchestration.ContainerState;
import org.eclipse.kura.container.orchestration.ImageConfiguration;
import org.eclipse.kura.identity.AssignedPermissions;
import org.eclipse.kura.identity.IdentityConfiguration;
import org.eclipse.kura.identity.IdentityService;
import org.eclipse.kura.identity.PasswordConfiguration;
import org.eclipse.kura.identity.Permission;
import org.eclipse.kura.net.IPAddress;
import org.eclipse.kura.net.NetInterface;
import org.eclipse.kura.net.NetInterfaceAddress;
import org.eclipse.kura.net.NetworkService;
import org.eclipse.kura.security.token.TokenIssueRequest;
import org.eclipse.kura.security.token.TokenIssuingService;
import org.junit.After;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;
import org.mockito.ArgumentCaptor;
import org.mockito.InOrder;
import org.mockito.Mockito;

import com.google.gson.Gson;
import com.google.gson.JsonObject;

/**
 * Feature: Container instance identity integration with temporary identities and JWT token pairs.
 */
public class ContainerIdentityIntegrationTest {

    private static final String CONTAINER_NAME = "kura-test-container";
    private static final String IDENTITY_BASE_NAME = "container_kura_test_container";
    private static final String CONTAINER_IMAGE = "nginx";
    private static final String CONTAINER_TAG = "latest";
    private static final String PERMISSIONS = "rest.read,rest.write";
    private static final String CONTAINER_ID = "container-id";
    private static final String SECOND_CONTAINER_ID = "container-id-2";
    private static final String SURVIVING_CONTAINER_ID = "surviving-container-id";
    private static final String UPDATED_CONTAINER_NAME = CONTAINER_NAME + "-v2";
    private static final String INVALID_CONTAINER_NAME = "....@@@....";
    private static final String TMPFS_BASE_PROPERTY = "kura.tmpfs.base";
    private static final String JWT_FILE_CONTAINER_PATH = "/run/secrets/kura-jwt.json";
    private static final String JWT_FILE_VOLUME_VALUE = JWT_FILE_CONTAINER_PATH + ":ro";
    private static final String ACCESS_TOKEN_CONSUMER = "/token/jwt/v1/access";
    private static final String REFRESH_TOKEN_CONSUMER = "/token/jwt/v1/refresh";

    @Rule
    public TemporaryFolder tmpfsBase = new TemporaryFolder();

    private String previousTmpfsBaseProperty;

    private ContainerInstance containerInstance;
    private ContainerOrchestrationService containerOrchestrationService;
    private IdentityService identityService;
    private TokenIssuingService tokenIssuingService;
    private ConfigurationService configurationService;
    private Map<String, Object> properties;
    private CountDownLatch startLatch;
    private AtomicInteger createCount;
    private AtomicInteger deleteCount;
    private AtomicInteger startCount;
    private AtomicInteger pullCount;
    private AtomicInteger issuedAccessTokenCount;
    private AtomicInteger issuedRefreshTokenCount;
    private ArgumentCaptor<ContainerConfiguration> configurationCaptor;
    private final List<IdentityConfiguration> createdIdentities = new CopyOnWriteArrayList<>();
    private final List<Duration> identityLifetimes = new CopyOnWriteArrayList<>();
    private final List<TokenIssueRequest> issueRequests = new CopyOnWriteArrayList<>();

    @Before
    public void setUp() throws Exception {
        this.previousTmpfsBaseProperty = System.getProperty(TMPFS_BASE_PROPERTY);
        System.setProperty(TMPFS_BASE_PROPERTY, this.tmpfsBase.getRoot().getAbsolutePath());

        this.containerInstance = new ContainerInstance();
        this.containerOrchestrationService = Mockito.mock(ContainerOrchestrationService.class);
        this.identityService = Mockito.mock(IdentityService.class);
        this.tokenIssuingService = Mockito.mock(TokenIssuingService.class);
        this.configurationService = Mockito.mock(ConfigurationService.class);
        this.properties = new HashMap<>();
        this.startLatch = new CountDownLatch(1);
        this.createCount = new AtomicInteger(0);
        this.deleteCount = new AtomicInteger(0);
        this.startCount = new AtomicInteger(0);
        this.pullCount = new AtomicInteger(0);
        this.issuedAccessTokenCount = new AtomicInteger(0);
        this.issuedRefreshTokenCount = new AtomicInteger(0);
        this.configurationCaptor = ArgumentCaptor.forClass(ContainerConfiguration.class);

        this.containerInstance.setContainerOrchestrationService(this.containerOrchestrationService);
        this.containerInstance.setIdentityService(this.identityService);
        this.containerInstance.setConfigurationService(this.configurationService);

        when(this.containerOrchestrationService.listContainerDescriptors()).thenReturn(Collections.emptyList());
        doAnswer(invocation -> {
            this.pullCount.incrementAndGet();
            return null;
        }).when(this.containerOrchestrationService).pullImage(any(ImageConfiguration.class));
        when(this.tokenIssuingService.getMaximumLifetime()).thenReturn(Optional.empty());
    }

    @After
    public void tearDown() {
        this.containerInstance.deactivate();

        if (this.previousTmpfsBaseProperty != null) {
            System.setProperty(TMPFS_BASE_PROPERTY, this.previousTmpfsBaseProperty);
        } else {
            System.clearProperty(TMPFS_BASE_PROPERTY);
        }
    }

    @Test
    public void createsTemporaryIdentityAndInjectsJwtFile() throws Exception {
        givenIdentityIntegrationIsEnabled();
        givenTemporaryIdentitiesCanBeCreated();
        givenTokenIssuingServiceIsBound();
        givenContainerOrchestratorStartsSuccessfully();

        whenContainerInstanceIsActivated();

        thenTemporaryIdentityIsCreatedWithPermissions();
        thenStartContainerReceivesJwtEnvironment();
        thenJwtFileContainsTokenPair(this.configurationCaptor.getValue(), 1);
    }

    @Test
    public void createsTemporaryIdentityWithPasswordAuthDisabled() throws Exception {
        givenIdentityIntegrationIsEnabled();
        givenTemporaryIdentitiesCanBeCreated();
        givenTokenIssuingServiceIsBound();
        givenContainerOrchestratorStartsSuccessfully();

        whenContainerInstanceIsActivated();

        thenTemporaryIdentityHasPasswordAuthDisabled();
    }

    @Test
    public void issuesTokenPairForTemporaryIdentity() throws Exception {
        givenIdentityIntegrationIsEnabled();
        givenTemporaryIdentitiesCanBeCreated();
        givenTokenIssuingServiceIsBound();
        givenContainerOrchestratorStartsSuccessfully();

        whenContainerInstanceIsActivated();

        thenTokenIsIssuedForLatestIdentity(ACCESS_TOKEN_CONSUMER);
        thenTokenIsIssuedForLatestIdentity(REFRESH_TOKEN_CONSUMER);
    }

    @Test
    public void issuesTokenPairWithConfiguredDurations() throws Exception {
        givenIdentityIntegrationIsEnabled();
        givenJwtTokenDurations(30, 600);
        givenTemporaryIdentitiesCanBeCreated();
        givenTokenIssuingServiceIsBound();
        givenContainerOrchestratorStartsSuccessfully();

        whenContainerInstanceIsActivated();

        thenTokenIsIssuedWithLifetime(ACCESS_TOKEN_CONSUMER, Duration.ofSeconds(30));
        thenTokenIsIssuedWithLifetime(REFRESH_TOKEN_CONSUMER, Duration.ofSeconds(600));
    }

    @Test
    public void pullsImageBeforeIssuingTokenPair() throws Exception {
        givenIdentityIntegrationIsEnabled();
        givenTemporaryIdentitiesCanBeCreated();
        givenTokenIssuingServiceIsBound();
        givenContainerOrchestratorStartsSuccessfully();

        whenContainerInstanceIsActivated();

        thenImageIsPulledBeforeTokenPairIsIssuedAndContainerIsStarted();
    }

    @Test
    public void issuesNewTokenPairOnEachStartAttempt() throws Exception {
        givenIdentityIntegrationIsEnabled();
        givenRetryConfiguration(2);
        givenTemporaryIdentitiesCanBeCreated();
        givenTokenIssuingServiceIsBound();
        givenContainerOrchestratorFailsFirstAttemptThenStarts();

        whenContainerInstanceIsActivatedUntilCreated();

        thenTemporaryIdentityIsCreatedTimes(1);
        thenTokenPairIsIssuedTimes(2);
        thenJwtFileIsDeleted(this.configurationCaptor.getAllValues().get(0));
        thenJwtFileContainsTokenPair(latestConfiguration(), 2);
    }

    @Test
    public void retriesStartupWhenTokenIssuingFails() throws Exception {
        givenIdentityIntegrationIsEnabled();
        givenRetryConfiguration(2);
        givenTemporaryIdentitiesCanBeCreated();
        givenTokenIssuingServiceFailsOnce();
        givenContainerOrchestratorStartsSuccessfully();

        whenContainerInstanceIsActivatedUntilCreated();

        thenTemporaryIdentityIsCreatedTimes(1);
        thenContainerIsStartedTimes(1);
        thenStartContainerReceivesJwtEnvironment();
    }

    @Test
    public void retriesStartupWhenTokenIssuingServiceIsNotBound() throws Exception {
        givenIdentityIntegrationIsEnabled();
        givenRetryConfiguration(2);
        givenTemporaryIdentitiesCanBeCreated();
        givenTokenIssuingServiceIsBoundOnSecondImagePull();
        givenContainerOrchestratorStartsSuccessfully();

        whenContainerInstanceIsActivatedUntilCreated();

        thenTemporaryIdentityIsCreatedTimes(1);
        thenContainerIsStartedTimes(1);
        thenStartContainerReceivesJwtEnvironment();
    }

    @Test
    public void failsStartupWhenTokenIssuingKeepsFailingBeyondMaxRetries() throws Exception {
        givenIdentityIntegrationIsEnabled();
        givenRetryConfiguration(2);
        givenTemporaryIdentitiesCanBeCreated();
        givenTokenIssuingServiceAlwaysFails();
        givenContainerOrchestratorStartsSuccessfully();

        whenContainerInstanceIsActivatedUntilDisabled();

        thenImageIsPulledTimes(2);
        thenContainerIsNeverStarted();
        thenTemporaryIdentityIsDeleted();
    }

    @Test
    public void failsStartupWhenTemporaryIdentityCreationFails() throws Exception {
        givenIdentityIntegrationIsEnabled();
        givenTemporaryIdentityCreationFails();
        givenTokenIssuingServiceIsBound();
        givenContainerOrchestratorStartsSuccessfully();

        whenContainerInstanceIsActivatedUntilDisabled();

        thenTemporaryIdentityIsCreatedTimes(1);
        thenNoTokenIsIssued();
        thenContainerIsNeverStarted();
    }

    @Test
    public void generatesUniqueIdentityNamePerStart() throws Exception {
        givenIdentityIntegrationIsEnabled();
        givenTemporaryIdentitiesCanBeCreated();
        givenTokenIssuingServiceIsBound();
        givenContainerOrchestratorStartsSuccessfullyWithIds(CONTAINER_ID, SECOND_CONTAINER_ID);

        whenContainerInstanceIsActivatedUntilCreated();
        whenContainerInstanceIsDisabled();
        whenContainerInstanceIsEnabledUntilCreated();

        thenTemporaryIdentityIsCreatedTimes(2);
        thenTemporaryIdentityNamesStartWith(IDENTITY_BASE_NAME + "_");
        thenTemporaryIdentityNamesAreDifferent();
    }

    @Test
    public void generatesValidTemporaryIdentityNameFromInvalidContainerName() throws Exception {
        givenIdentityIntegrationIsEnabled(INVALID_CONTAINER_NAME);
        givenTemporaryIdentitiesCanBeCreated();
        givenTokenIssuingServiceIsBound();
        givenContainerOrchestratorStartsSuccessfully();

        whenContainerInstanceIsActivated();

        thenTemporaryIdentityNamesStartWith("container_auto_");
        thenStartContainerReceivesJwtEnvironment();
    }

    @Test
    public void deletesTemporaryIdentityWhenContainerIsDisabled() throws Exception {
        givenIdentityIntegrationIsEnabled();
        givenTemporaryIdentitiesCanBeCreated();
        givenTokenIssuingServiceIsBound();
        givenContainerOrchestratorStartsSuccessfully();

        whenContainerInstanceIsActivatedUntilCreated();
        whenContainerInstanceIsDisabled();

        thenTemporaryIdentityIsDeleted();
    }

    @Test
    public void recreatesTemporaryIdentityOnConfigurationChange() throws Exception {
        givenIdentityIntegrationIsEnabled();
        givenTemporaryIdentitiesCanBeCreated();
        givenTokenIssuingServiceIsBound();
        givenContainerOrchestratorStartsSuccessfullyWithIds(CONTAINER_ID, SECOND_CONTAINER_ID);

        whenContainerInstanceIsActivatedUntilCreated();
        whenContainerConfigurationIsUpdatedWithNewName();

        thenTemporaryIdentityIsRecreated();
        thenJwtFileContainsTokenPair(latestConfiguration(), 2);
    }

    @Test
    public void cleansUpTemporaryIdentityOnceAcrossMultipleShutdowns() throws Exception {
        givenIdentityIntegrationIsEnabled();
        givenTemporaryIdentitiesCanBeCreated();
        givenTokenIssuingServiceIsBound();
        givenContainerOrchestratorStartsSuccessfully();

        whenContainerInstanceIsActivatedUntilCreated();
        whenContainerInstanceIsDisabled();
        whenContainerInstanceIsDeactivated();

        thenTemporaryIdentityIsDeleted();
    }

    @Test
    public void injectsUrlEncodedIpv6RestBaseUrlForDockerBridge() throws Exception {
        givenIdentityIntegrationIsEnabled();
        givenTemporaryIdentitiesCanBeCreated();
        givenTokenIssuingServiceIsBound();
        givenContainerOrchestratorStartsSuccessfully();
        givenHttpsServiceIsEnabledOnPort(443);
        givenDockerBridgeAddressIs("fe80::7024:e3ff:feb9:997d%docker0");

        whenContainerInstanceIsActivated();

        thenRestBaseUrlIs("https://[fe80::7024:e3ff:feb9:997d%25docker0]:443/services");
    }

    @Test
    public void mountsJwtFileReadOnlyIntoContainer() throws Exception {
        givenIdentityIntegrationIsEnabled();
        givenUserConfiguredVolume();
        givenTemporaryIdentitiesCanBeCreated();
        givenTokenIssuingServiceIsBound();
        givenContainerOrchestratorStartsSuccessfully();

        whenContainerInstanceIsActivated();

        thenStartContainerReceivesReadOnlyJwtFileVolume();
        thenStartContainerReceivesUserConfiguredVolume();
    }

    @Test
    public void jwtFileSurvivesAfterContainerIsCreated() throws Exception {
        givenIdentityIntegrationIsEnabled();
        givenTemporaryIdentitiesCanBeCreated();
        givenTokenIssuingServiceIsBound();
        givenContainerOrchestratorStartsSuccessfully();

        whenContainerInstanceIsActivatedUntilCreated();

        thenJwtFileContainsTokenPair(this.configurationCaptor.getValue(), 1);
    }

    @Test
    public void deletesJwtFileWhenContainerIsDisabled() throws Exception {
        givenIdentityIntegrationIsEnabled();
        givenTemporaryIdentitiesCanBeCreated();
        givenTokenIssuingServiceIsBound();
        givenContainerOrchestratorStartsSuccessfully();

        whenContainerInstanceIsActivatedUntilCreated();
        whenContainerInstanceIsDisabled();

        thenTemporaryIdentityIsDeleted();
        thenJwtFileIsDeleted(this.configurationCaptor.getValue());
    }

    @Test
    public void deletesJwtFileOnConfigurationChange() throws Exception {
        givenIdentityIntegrationIsEnabled();
        givenTemporaryIdentitiesCanBeCreated();
        givenTokenIssuingServiceIsBound();
        givenContainerOrchestratorStartsSuccessfullyWithIds(CONTAINER_ID, SECOND_CONTAINER_ID);

        whenContainerInstanceIsActivatedUntilCreated();
        whenContainerConfigurationIsUpdatedWithNewName();

        thenContainerIsStartedTimes(2);
        thenJwtFileIsDeleted(this.configurationCaptor.getAllValues().get(0));
        thenJwtFileContainsTokenPair(latestConfiguration(), 2);
    }

    @Test
    public void deletesJwtFileOnDeactivate() throws Exception {
        givenIdentityIntegrationIsEnabled();
        givenTemporaryIdentitiesCanBeCreated();
        givenTokenIssuingServiceIsBound();
        givenContainerOrchestratorStartsSuccessfully();

        whenContainerInstanceIsActivatedUntilCreated();
        whenContainerInstanceIsDeactivated();

        thenJwtFileIsDeleted(this.configurationCaptor.getValue());
    }

    @Test
    public void deletesJwtFileOnStartupFailure() throws Exception {
        givenIdentityIntegrationIsEnabled();
        givenRetryConfiguration(1);
        givenTemporaryIdentitiesCanBeCreated();
        givenTokenIssuingServiceIsBound();
        givenContainerOrchestratorFailsToStart();

        whenContainerInstanceIsActivatedUntilDisabled();

        thenTemporaryIdentityIsDeleted();
        thenJwtFileIsDeleted(this.configurationCaptor.getValue());
    }

    @Test
    public void failsStartupWhenTmpfsBaseIsMissing() throws Exception {
        givenIdentityIntegrationIsEnabled();
        givenRetryConfiguration(1);
        givenTemporaryIdentitiesCanBeCreated();
        givenTokenIssuingServiceIsBound();
        givenContainerOrchestratorStartsSuccessfully();
        givenMissingTmpfsBase();

        whenContainerInstanceIsActivatedUntilDisabled();

        thenTemporaryIdentityIsDeleted();
        thenContainerIsNeverStarted();
    }

    @Test
    public void recreatesSurvivingContainerToRefreshCredentialsOnStartup() throws Exception {
        givenIdentityIntegrationIsEnabled();
        givenTemporaryIdentitiesCanBeCreated();
        givenTokenIssuingServiceIsBound();
        givenSurvivingContainerExists(SURVIVING_CONTAINER_ID);
        givenContainerOrchestratorStartsSuccessfully();

        whenContainerInstanceIsActivated();

        thenSurvivingContainerIsRecreated(SURVIVING_CONTAINER_ID);
        thenStartContainerReceivesJwtEnvironment();
        thenStartContainerReceivesReadOnlyJwtFileVolume();
    }

    /*
     * GIVEN
     */

    private void givenIdentityIntegrationIsEnabled() {
        givenIdentityIntegrationIsEnabled(CONTAINER_NAME);
    }

    private void givenIdentityIntegrationIsEnabled(final String containerName) {
        this.properties.put("container.enabled", true);
        this.properties.put("container.name", containerName);
        this.properties.put("kura.service.pid", containerName);
        this.properties.put("container.image", CONTAINER_IMAGE);
        this.properties.put("container.image.tag", CONTAINER_TAG);
        this.properties.put("container.identity.enabled", true);
        this.properties.put("container.permissions", PERMISSIONS);
    }

    private void givenJwtTokenDurations(final int accessTokenDuration, final int refreshTokenDuration) {
        this.properties.put("container.identity.jwt.access.token.duration", accessTokenDuration);
        this.properties.put("container.identity.jwt.refresh.token.duration", refreshTokenDuration);
    }

    private void givenRetryConfiguration(final int retries) {
        this.properties.put("container.image.download.retries", retries);
        this.properties.put("container.image.download.interval", 0);
    }

    private void givenTemporaryIdentitiesCanBeCreated() throws Exception {
        doAnswer(invocation -> {
            this.createdIdentities.add(invocation.getArgument(0));
            this.identityLifetimes.add(invocation.getArgument(1));
            this.createCount.incrementAndGet();
            return null;
        }).when(this.identityService).createTemporaryIdentity(any(IdentityConfiguration.class), any(Duration.class));

        doAnswer(invocation -> {
            this.deleteCount.incrementAndGet();
            return true;
        }).when(this.identityService).deleteIdentity(anyString());
    }

    private void givenTemporaryIdentityCreationFails() throws Exception {
        doAnswer(invocation -> {
            this.createCount.incrementAndGet();
            throw new KuraException(KuraErrorCode.INVALID_PARAMETER, "invalid identity");
        }).when(this.identityService).createTemporaryIdentity(any(IdentityConfiguration.class), any(Duration.class));
    }

    private void givenTokenIssuingServiceIsBound() throws Exception {
        givenTokenIssuingServiceIssuesTokens();
        this.containerInstance.setTokenIssuingService(this.tokenIssuingService);
    }

    private void givenTokenIssuingServiceIssuesTokens() throws Exception {
        when(this.tokenIssuingService.issue(any(TokenIssueRequest.class))).thenAnswer(invocation -> issueToken(
                invocation.getArgument(0)));
    }

    private void givenTokenIssuingServiceFailsOnce() throws Exception {
        final AtomicInteger calls = new AtomicInteger(0);

        when(this.tokenIssuingService.issue(any(TokenIssueRequest.class))).thenAnswer(invocation -> {
            if (calls.getAndIncrement() == 0) {
                throw new KuraException(KuraErrorCode.CONFIGURATION_ERROR, "not yet ready");
            }
            return issueToken(invocation.getArgument(0));
        });
        this.containerInstance.setTokenIssuingService(this.tokenIssuingService);
    }

    private void givenTokenIssuingServiceAlwaysFails() throws Exception {
        when(this.tokenIssuingService.issue(any(TokenIssueRequest.class)))
                .thenThrow(new KuraException(KuraErrorCode.CONFIGURATION_ERROR, "not yet ready"));
        this.containerInstance.setTokenIssuingService(this.tokenIssuingService);
    }

    private void givenTokenIssuingServiceIsBoundOnSecondImagePull() throws Exception {
        givenTokenIssuingServiceIssuesTokens();

        doAnswer(invocation -> {
            if (this.pullCount.incrementAndGet() == 2) {
                this.containerInstance.setTokenIssuingService(this.tokenIssuingService);
            }
            return null;
        }).when(this.containerOrchestrationService).pullImage(any(ImageConfiguration.class));
    }

    private void givenContainerOrchestratorStartsSuccessfully() throws Exception {
        doAnswer(invocation -> {
            this.startCount.incrementAndGet();
            this.startLatch.countDown();
            return CONTAINER_ID;
        }).when(this.containerOrchestrationService).startContainer(this.configurationCaptor.capture());
    }

    private void givenContainerOrchestratorStartsSuccessfullyWithIds(final String... containerIds) throws Exception {
        this.startLatch = new CountDownLatch(containerIds.length);
        final AtomicInteger index = new AtomicInteger(0);

        doAnswer(invocation -> {
            this.startCount.incrementAndGet();
            this.startLatch.countDown();
            final int current = Math.min(index.getAndIncrement(), containerIds.length - 1);
            return containerIds[current];
        }).when(this.containerOrchestrationService).startContainer(this.configurationCaptor.capture());
    }

    private void givenContainerOrchestratorFailsFirstAttemptThenStarts() throws Exception {
        doAnswer(invocation -> {
            if (this.startCount.incrementAndGet() == 1) {
                throw new KuraException(KuraErrorCode.SERVICE_UNAVAILABLE);
            }
            this.startLatch.countDown();
            return CONTAINER_ID;
        }).when(this.containerOrchestrationService).startContainer(this.configurationCaptor.capture());
    }

    private void givenContainerOrchestratorFailsToStart() throws Exception {
        doAnswer(invocation -> {
            this.startCount.incrementAndGet();
            throw new KuraException(KuraErrorCode.SERVICE_UNAVAILABLE);
        }).when(this.containerOrchestrationService).startContainer(this.configurationCaptor.capture());
    }

    private void givenUserConfiguredVolume() {
        this.properties.put("container.volume", "/host/data:/container/data");
    }

    private void givenSurvivingContainerExists(final String containerId) {
        final ContainerInstanceDescriptor descriptor = ContainerInstanceDescriptor.builder()
                .setContainerName(CONTAINER_NAME).setContainerImage(CONTAINER_IMAGE).setContainerID(containerId)
                .setContainerState(ContainerState.ACTIVE).build();
        when(this.containerOrchestrationService.listContainerDescriptors())
                .thenReturn(Collections.singletonList(descriptor));
    }

    private void givenMissingTmpfsBase() {
        System.setProperty(TMPFS_BASE_PROPERTY,
                Paths.get(this.tmpfsBase.getRoot().getAbsolutePath(), "missing").toString());
    }

    private void givenHttpsServiceIsEnabledOnPort(final int port) throws Exception {
        final ComponentConfiguration componentConfiguration = Mockito.mock(ComponentConfiguration.class);
        final Map<String, Object> httpServiceProperties = new HashMap<>();
        httpServiceProperties.put("https.ports", new Integer[] { port });
        when(componentConfiguration.getConfigurationProperties()).thenReturn(httpServiceProperties);
        when(this.configurationService.getComponentConfiguration("org.eclipse.kura.http.server.manager.HttpService"))
                .thenReturn(componentConfiguration);
    }

    @SuppressWarnings("unchecked")
    private void givenDockerBridgeAddressIs(final String address) throws Exception {
        final NetworkService networkService = Mockito.mock(NetworkService.class);
        final NetInterface<NetInterfaceAddress> docker0 = Mockito.mock(NetInterface.class);
        final NetInterfaceAddress interfaceAddress = Mockito.mock(NetInterfaceAddress.class);
        final IPAddress ipAddress = Mockito.mock(IPAddress.class);

        when(docker0.getName()).thenReturn("docker0");
        when(docker0.getNetInterfaceAddresses()).thenReturn(Collections.singletonList(interfaceAddress));
        when(interfaceAddress.getAddress()).thenReturn(ipAddress);
        when(ipAddress.getHostAddress()).thenReturn(address);
        when(networkService.getNetworkInterfaces()).thenReturn(Collections.singletonList(docker0));

        this.containerInstance.setNetworkService(networkService);
    }

    /*
     * WHEN
     */

    private void whenContainerInstanceIsActivated() {
        this.containerInstance.activate(this.properties);
    }

    private void whenContainerInstanceIsActivatedUntilCreated() throws InterruptedException {
        this.containerInstance.activate(this.properties);
        waitForContainerState("Created");
    }

    private void whenContainerInstanceIsActivatedUntilDisabled() throws InterruptedException {
        this.containerInstance.activate(this.properties);
        waitForContainerState("Disabled");
    }

    private void whenContainerConfigurationIsUpdatedWithNewName() throws InterruptedException {
        final Map<String, Object> updated = new HashMap<>(this.properties);
        updated.put("container.name", UPDATED_CONTAINER_NAME);
        updated.put("kura.service.pid", UPDATED_CONTAINER_NAME);

        this.containerInstance.updated(updated);
        waitForContainerState("Created");
    }

    private void whenContainerInstanceIsDisabled() {
        final Map<String, Object> disabled = new HashMap<>(this.properties);
        disabled.put("container.enabled", false);

        this.containerInstance.updated(disabled);
    }

    private void whenContainerInstanceIsEnabledUntilCreated() throws InterruptedException {
        this.containerInstance.updated(new HashMap<>(this.properties));
        waitForContainerState("Created");
    }

    private void whenContainerInstanceIsDeactivated() {
        this.containerInstance.deactivate();
    }

    /*
     * THEN
     */

    private void thenTemporaryIdentityIsCreatedWithPermissions() throws Exception {
        awaitCounterAtLeast(this.createCount, 1);

        final IdentityConfiguration configuration = this.createdIdentities.get(0);
        final Set<Permission> permissions = configuration.getComponent(AssignedPermissions.class).orElseThrow()
                .getPermissions();

        assertTrue(configuration.getName().startsWith(IDENTITY_BASE_NAME + "_"));
        assertTrue(permissions.contains(new Permission("rest.read")));
        assertTrue(permissions.contains(new Permission("rest.write")));
        assertEquals(Duration.ofSeconds(ContainerInstanceOptions.TEMPORARY_IDENTITY_LIFETIME_SECONDS),
                this.identityLifetimes.get(0));
    }

    private void thenTemporaryIdentityHasPasswordAuthDisabled() throws Exception {
        awaitCounterAtLeast(this.createCount, 1);

        final PasswordConfiguration passwordConfiguration = this.createdIdentities.get(0)
                .getComponent(PasswordConfiguration.class).orElseThrow();

        assertFalse(passwordConfiguration.isPasswordAuthEnabled());
        assertFalse(passwordConfiguration.isPasswordChangeNeeded());
        assertFalse(passwordConfiguration.getNewPassword().isPresent());
        assertFalse(passwordConfiguration.getPasswordHash().isPresent());
    }

    private void thenTemporaryIdentityIsCreatedTimes(final int times) throws Exception {
        awaitCounterAtLeast(this.createCount, times);
        assertEquals(times, this.createCount.get());
    }

    private void thenTemporaryIdentityNamesStartWith(final String prefix) throws Exception {
        awaitCounterAtLeast(this.createCount, 1);

        for (final IdentityConfiguration identity : this.createdIdentities) {
            assertTrue(identity.getName() + " does not start with " + prefix, identity.getName().startsWith(prefix));
        }
    }

    private void thenTemporaryIdentityNamesAreDifferent() {
        assertNotEquals(this.createdIdentities.get(0).getName(), this.createdIdentities.get(1).getName());
    }

    private void thenTokenIsIssuedForLatestIdentity(final String intendedConsumer) throws Exception {
        awaitStart();

        final TokenIssueRequest request = latestIssueRequestFor(intendedConsumer);

        assertEquals(latestIdentityName(), request.getIdentityName());
        assertEquals(Collections.singleton(intendedConsumer), request.getIntendedConsumers());
    }

    private void thenTokenIsIssuedWithLifetime(final String intendedConsumer, final Duration lifetime)
            throws Exception {
        awaitStart();

        final TokenIssueRequest request = latestIssueRequestFor(intendedConsumer);

        assertEquals(lifetime,
                Duration.between(request.getNotBefore().orElseThrow(), request.getExpiresAt().orElseThrow()));
    }

    private void thenTokenPairIsIssuedTimes(final int times) {
        assertEquals(times, this.issuedAccessTokenCount.get());
        assertEquals(times, this.issuedRefreshTokenCount.get());
    }

    private void thenNoTokenIsIssued() throws Exception {
        verify(this.tokenIssuingService, never()).issue(any(TokenIssueRequest.class));
    }

    private void thenImageIsPulledBeforeTokenPairIsIssuedAndContainerIsStarted() throws Exception {
        awaitStart();

        final InOrder order = inOrder(this.containerOrchestrationService, this.tokenIssuingService);
        order.verify(this.containerOrchestrationService).pullImage(any(ImageConfiguration.class));
        order.verify(this.tokenIssuingService, atLeastOnce()).issue(any(TokenIssueRequest.class));
        order.verify(this.containerOrchestrationService).startContainer(any(ContainerConfiguration.class));
    }

    private void thenImageIsPulledTimes(final int times) {
        assertEquals(times, this.pullCount.get());
    }

    private void thenStartContainerReceivesJwtEnvironment() throws Exception {
        awaitStart();

        final List<String> envVars = latestConfiguration().getContainerEnvVars();

        assertTrue(envVars.contains("KURA_IDENTITY_NAME=" + latestIdentityName()));
        assertTrue(envVars.contains("KURA_JWT_FILE=" + JWT_FILE_CONTAINER_PATH));
        assertTrue(envVars.stream().anyMatch(envVar -> envVar.startsWith("KURA_REST_BASE_URL=")));
        assertTrue(envVars.stream().noneMatch(envVar -> envVar.startsWith("KURA_TOKEN_FILE=")));
    }

    private void thenTemporaryIdentityIsDeleted() throws Exception {
        awaitCounterAtLeast(this.deleteCount, 1);
        assertEquals(1, this.deleteCount.get());
        verify(this.identityService).deleteIdentity(this.createdIdentities.get(0).getName());
    }

    private void thenTemporaryIdentityIsRecreated() throws Exception {
        awaitCounterAtLeast(this.createCount, 2);
        awaitCounterAtLeast(this.deleteCount, 1);

        assertEquals(2, this.createCount.get());
        assertEquals(1, this.deleteCount.get());
        verify(this.identityService).deleteIdentity(this.createdIdentities.get(0).getName());
        assertTrue(latestConfiguration().getContainerEnvVars().contains("KURA_IDENTITY_NAME=" + latestIdentityName()));
    }

    private void thenRestBaseUrlIs(final String expectedBaseUrl) throws Exception {
        awaitStart();

        assertTrue(latestConfiguration().getContainerEnvVars().contains("KURA_REST_BASE_URL=" + expectedBaseUrl));
    }

    private void thenStartContainerReceivesReadOnlyJwtFileVolume() throws Exception {
        awaitStart();

        final Path jwtFile = jwtFileHostPathOf(latestConfiguration());

        assertTrue(jwtFile.startsWith(Paths.get(this.tmpfsBase.getRoot().getAbsolutePath(), "kura-tokens")));
        assertEquals("kura-jwt.json", jwtFile.getFileName().toString());
    }

    private void thenStartContainerReceivesUserConfiguredVolume() {
        assertEquals("/container/data", latestConfiguration().getContainerVolumes().get("/host/data"));
    }

    private void thenJwtFileContainsTokenPair(final ContainerConfiguration configuration, final int tokenPairNumber)
            throws Exception {
        final Path jwtFile = jwtFileHostPathOf(configuration);
        final JsonObject tokenPair = new Gson()
                .fromJson(new String(Files.readAllBytes(jwtFile), StandardCharsets.UTF_8), JsonObject.class);

        assertEquals("Bearer", tokenPair.get("tokenType").getAsString());
        assertEquals("access-token-" + tokenPairNumber, tokenPair.get("accessToken").getAsString());
        assertEquals("refresh-token-" + tokenPairNumber, tokenPair.get("refreshToken").getAsString());
    }

    private void thenJwtFileIsDeleted(final ContainerConfiguration configuration) {
        final Path jwtFile = jwtFileHostPathOf(configuration);

        assertFalse(Files.exists(jwtFile));
        assertFalse(Files.exists(jwtFile.getParent()));
    }

    private void thenContainerIsStartedTimes(final int times) throws Exception {
        awaitCounterAtLeast(this.startCount, times);
        assertEquals(times, this.startCount.get());
    }

    private void thenContainerIsNeverStarted() throws Exception {
        verify(this.containerOrchestrationService, never()).startContainer(any(ContainerConfiguration.class));
    }

    private void thenSurvivingContainerIsRecreated(final String containerId) throws Exception {
        awaitStart();

        verify(this.containerOrchestrationService).stopContainer(containerId);
        verify(this.containerOrchestrationService).deleteContainer(containerId);
    }

    /*
     * Helpers
     */

    private String issueToken(final TokenIssueRequest request) {
        this.issueRequests.add(request);

        if (request.getIntendedConsumers().contains(ACCESS_TOKEN_CONSUMER)) {
            return "access-token-" + this.issuedAccessTokenCount.incrementAndGet();
        }

        return "refresh-token-" + this.issuedRefreshTokenCount.incrementAndGet();
    }

    private TokenIssueRequest latestIssueRequestFor(final String intendedConsumer) {
        return this.issueRequests.stream().filter(request -> request.getIntendedConsumers().contains(intendedConsumer))
                .reduce((first, second) -> second)
                .orElseThrow(() -> new AssertionError("no token issued for " + intendedConsumer));
    }

    private String latestIdentityName() {
        return this.createdIdentities.get(this.createdIdentities.size() - 1).getName();
    }

    private ContainerConfiguration latestConfiguration() {
        final List<ContainerConfiguration> configurations = this.configurationCaptor.getAllValues();
        return configurations.get(configurations.size() - 1);
    }

    private Path jwtFileHostPathOf(final ContainerConfiguration configuration) {
        return configuration.getContainerVolumes().entrySet().stream()
                .filter(entry -> JWT_FILE_VOLUME_VALUE.equals(entry.getValue())).map(entry -> Paths.get(entry.getKey()))
                .findFirst()
                .orElseThrow(() -> new IllegalStateException("JWT file volume not found in container configuration"));
    }

    private void awaitStart() throws InterruptedException {
        assertTrue("Container start was not invoked", this.startLatch.await(5, TimeUnit.SECONDS));
    }

    private void waitForContainerState(final String expectedState) throws InterruptedException {
        int attempts = 50;
        while (!expectedState.equals(this.containerInstance.getState()) && attempts-- > 0) {
            Thread.sleep(100);
        }
        assertEquals(expectedState, this.containerInstance.getState());
    }

    private void awaitCounterAtLeast(final AtomicInteger counter, final int expected) throws InterruptedException {
        int attempts = 50;
        while (counter.get() < expected && attempts-- > 0) {
            Thread.sleep(100);
        }
        assertTrue("Counter did not reach expected value", counter.get() >= expected);
    }
}
