/*******************************************************************************
 * Copyright (c) 2023, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.internal.rest.service.listing.provider.dto;

import java.util.AbstractMap.SimpleImmutableEntry;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Deque;
import java.util.List;
import java.util.Map.Entry;
import java.util.Objects;

import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.KuraException;
import org.eclipse.kura.internal.rest.service.listing.provider.util.FilterBuilder;

public class FilterDTO {

    static final int MAX_NESTING_DEPTH = 32;

    private final String name;
    private final String value;
    private final List<FilterDTO> and;
    private final List<FilterDTO> or;
    private final FilterDTO not;

    public FilterDTO(String name, String value, List<FilterDTO> and, List<FilterDTO> or, FilterDTO not) {
        this.name = name;
        this.value = value;
        this.and = and;
        this.or = or;
        this.not = not;
    }

    public String toOSGIFilter() {

        return toOSGIFilter(new FilterBuilder()).build();
    }

    public void validate() throws KuraException {
        int count = 0;

        if (name != null) {
            if (name.contains(" ")) {
                throw new KuraException(KuraErrorCode.BAD_REQUEST, "Name must contain no spaces");
            }

            if (name.trim().isEmpty()) {
                throw new KuraException(KuraErrorCode.BAD_REQUEST, "Name must not be empty");
            }

            count++;
        }

        if (and != null) {
            count++;
        }

        if (or != null) {
            count++;
        }

        if (not != null) {
            count++;
        }

        if (count != 1) {
            throw new KuraException(KuraErrorCode.BAD_REQUEST,
                    "Exactly one among the \"name\", \"and\", \"or\" and \"not\" properties must be specified");
        }

        validateNestingDepth();
    }

    // iterative on purpose: the filter tree comes from the request and must be checked before any recursive
    // processing (toOSGIFilter, OSGi filter parsing)
    private void validateNestingDepth() throws KuraException {
        final Deque<Entry<FilterDTO, Integer>> pending = new ArrayDeque<>();
        pending.push(new SimpleImmutableEntry<>(this, 1));

        while (!pending.isEmpty()) {
            final Entry<FilterDTO, Integer> current = pending.pop();
            final int depth = current.getValue();

            if (depth > MAX_NESTING_DEPTH) {
                throw new KuraException(KuraErrorCode.BAD_REQUEST,
                        "Filter nesting depth must not exceed " + MAX_NESTING_DEPTH);
            }

            for (final FilterDTO child : current.getKey().children()) {
                pending.push(new SimpleImmutableEntry<>(child, depth + 1));
            }
        }
    }

    private List<FilterDTO> children() {
        final List<FilterDTO> children = new ArrayList<>();

        if (and != null) {
            children.addAll(and);
        }
        if (or != null) {
            children.addAll(or);
        }
        if (not != null) {
            children.add(not);
        }

        children.removeIf(Objects::isNull);
        return children;
    }

    private FilterBuilder toOSGIFilter(final FilterBuilder filterBuilder) {
        if (name != null) {
            filterBuilder.property(name, value);
        } else if (and != null) {
            filterBuilder.and(b -> and.forEach(f -> f.toOSGIFilter(b)));
        } else if (or != null) {
            filterBuilder.or(b -> or.forEach(f -> f.toOSGIFilter(b)));
        } else if (not != null) {
            filterBuilder.not(not::toOSGIFilter);
        }

        return filterBuilder;
    }

}
