/*******************************************************************************
 * Copyright (c) 2025 Eurotech and/or its affiliates and others
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *  Eurotech
 *******************************************************************************/
/* Some portions generated by generative AI */
package org.eclipse.kura.linux.gpio.libgpiod;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.mockStatic;
import static org.mockito.Mockito.when;

import java.util.HashMap;
import java.util.Map;

import org.eclipse.kura.gpio.GPIOService;
import org.eclipse.kura.gpio.KuraGPIODirection;
import org.eclipse.kura.gpio.KuraGPIOMode;
import org.eclipse.kura.gpio.KuraGPIOPin;
import org.eclipse.kura.gpio.KuraGPIOTrigger;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.mockito.MockedStatic;

public class GPIOServiceImplTest extends CommonSteps {

    private MockedStatic<LibGpiodGPIOServiceFactory> libGpiodGPIOServiceFactoryMock;
    private GPIOService GPIOServiceMock;
    private GPIOServiceImpl gpioServiceImpl;
    private Map<Integer, String> resultPins;
    private KuraGPIOPin resultPin;

    @Before
    public void setup() {
        this.libGpiodGPIOServiceFactoryMock = mockStatic(LibGpiodGPIOServiceFactory.class);
        this.GPIOServiceMock = mock(GPIOService.class);
        this.libGpiodGPIOServiceFactoryMock.when(() -> LibGpiodGPIOServiceFactory.getInstance())
                .thenReturn(java.util.Optional.of(this.GPIOServiceMock));
        Map<Integer, String> availablePins = new HashMap<>();
        availablePins.put(1001, "GPIO_01");
        availablePins.put(1002, "GPIO_02");
        when(this.GPIOServiceMock.getAvailablePins()).thenReturn(availablePins);
    }

    @After
    public void cleanup() {
        this.libGpiodGPIOServiceFactoryMock.close();
    }

    @Test
    public void testActivateGPIOService() {
        givenGPIOServiceImpl();

        whenActivateGPIOService();

        thenNoExceptionOccurred();
    }

    @Test
    public void testDeactivateGPIOService() {
        givenGPIOServiceImpl();
        givenActivatedGPIOService();

        whenDeactivateGPIOService();

        thenNoExceptionOccurred();
    }

    @Test
    public void testGetPinByNameWithoutActivation() {
        givenGPIOServiceImpl();

        whenGetPinByName("GPIO_01");

        thenExceptionOccurred(IllegalStateException.class);
    }

    @Test
    public void testGetPinByNameWithActivation() {
        givenGPIOServicePin("GPIO_01");
        givenGPIOServiceImpl();
        givenActivatedGPIOService();

        whenGetPinByName("GPIO_01");

        thenPinIsNotNull();
    }

    @Test
    public void testGetPinByNameWithParametersWithoutActivation() {
        givenGPIOServicePin("GPIO_01", KuraGPIODirection.OUTPUT, KuraGPIOMode.OUTPUT_PUSH_PULL, KuraGPIOTrigger.NONE);
        givenGPIOServiceImpl();

        whenGetPinByName("GPIO_01", KuraGPIODirection.OUTPUT, KuraGPIOMode.OUTPUT_PUSH_PULL, KuraGPIOTrigger.NONE);

        thenExceptionOccurred(IllegalStateException.class);
    }

    @Test
    public void testGetPinByNameWithParametersWithActivation() {
        givenGPIOServicePin("GPIO_01", KuraGPIODirection.OUTPUT, KuraGPIOMode.OUTPUT_PUSH_PULL, KuraGPIOTrigger.NONE);
        givenGPIOServiceImpl();
        givenActivatedGPIOService();

        whenGetPinByName("GPIO_01", KuraGPIODirection.OUTPUT, KuraGPIOMode.OUTPUT_PUSH_PULL, KuraGPIOTrigger.NONE);

        thenPinIsNotNull();
    }

    @Test
    public void testGetPinByTerminalWithoutActivation() {
        givenGPIOServicePin(1002);
        givenGPIOServiceImpl();

        whenGetPinByTerminal(1002);

        thenExceptionOccurred(IllegalStateException.class);
    }

    @Test
    public void testGetPinByTerminalWithActivation() {
        givenGPIOServicePin(1002);
        givenGPIOServiceImpl();
        givenActivatedGPIOService();

        whenGetPinByTerminal(1002);

        thenPinIsNotNull();
    }

    @Test
    public void testGetPinByTerminalWithParametersWithoutActivation() {
        givenGPIOServicePin(2002, KuraGPIODirection.INPUT, KuraGPIOMode.INPUT_PULL_UP, KuraGPIOTrigger.BOTH_EDGES);
        givenGPIOServiceImpl();

        whenGetPinByTerminal(2002, KuraGPIODirection.INPUT, KuraGPIOMode.INPUT_PULL_UP, KuraGPIOTrigger.BOTH_EDGES);

        thenExceptionOccurred(IllegalStateException.class);
    }

    @Test
    public void testGetPinByTerminalWithParametersWithActivation() {
        givenGPIOServicePin(2002, KuraGPIODirection.INPUT, KuraGPIOMode.INPUT_PULL_UP, KuraGPIOTrigger.BOTH_EDGES);
        givenGPIOServiceImpl();
        givenActivatedGPIOService();

        whenGetPinByTerminal(2002, KuraGPIODirection.INPUT, KuraGPIOMode.INPUT_PULL_UP, KuraGPIOTrigger.BOTH_EDGES);

        thenPinIsNotNull();
    }

    @Test
    public void testGetAvailablePinsWithoutActivation() {
        givenGPIOServiceImpl();

        whenGetAvailablePins();

        thenExceptionOccurred(IllegalStateException.class);
    }

    @Test
    public void testGetAvailablePinsWithActivation() {
        givenGPIOServiceImpl();
        givenActivatedGPIOService();

        whenGetAvailablePins();

        thenAvailablePinsIsNotNullOrEmpty();
    }

    /*
     * Given
     */

    private void givenGPIOServiceImpl() {
        this.gpioServiceImpl = new GPIOServiceImpl();
    }

    private void givenActivatedGPIOService() {
        this.gpioServiceImpl.activate();
    }

    private void givenGPIOServicePin(String pinName) {
        KuraGPIOPin pinMock = mock(KuraGPIOPin.class);
        when(GPIOServiceMock.getPinByName(pinName)).thenReturn(pinMock);
    }

    private void givenGPIOServicePin(String pinName, KuraGPIODirection direction, KuraGPIOMode mode,
            KuraGPIOTrigger trigger) {
        KuraGPIOPin pinMock = mock(KuraGPIOPin.class);
        when(GPIOServiceMock.getPinByName(pinName, direction, mode, trigger)).thenReturn(pinMock);
    }

    private void givenGPIOServicePin(int pinTerminal) {
        KuraGPIOPin pinMock = mock(KuraGPIOPin.class);
        when(GPIOServiceMock.getPinByTerminal(pinTerminal)).thenReturn(pinMock);
    }

    private void givenGPIOServicePin(int pinTerminal, KuraGPIODirection direction, KuraGPIOMode mode,
            KuraGPIOTrigger trigger) {
        KuraGPIOPin pinMock = mock(KuraGPIOPin.class);
        when(GPIOServiceMock.getPinByTerminal(pinTerminal, direction, mode, trigger)).thenReturn(pinMock);
    }

    /*
     * When
     */

    private void whenActivateGPIOService() {
        try {
            this.gpioServiceImpl.activate();
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    private void whenDeactivateGPIOService() {
        try {
            this.gpioServiceImpl.deactivate();
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    private void whenGetPinByName(String pinName) {
        try {
            this.resultPin = this.gpioServiceImpl.getPinByName(pinName);
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    private void whenGetPinByName(String pinName, KuraGPIODirection direction, KuraGPIOMode mode,
            KuraGPIOTrigger trigger) {
        try {
            this.resultPin = this.gpioServiceImpl.getPinByName(pinName, direction, mode, trigger);
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    private void whenGetPinByTerminal(int terminal) {
        try {
            this.resultPin = this.gpioServiceImpl.getPinByTerminal(terminal);
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    private void whenGetPinByTerminal(int terminal, KuraGPIODirection direction, KuraGPIOMode mode,
            KuraGPIOTrigger trigger) {
        try {
            this.resultPin = this.gpioServiceImpl.getPinByTerminal(terminal, direction, mode, trigger);
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    private void whenGetAvailablePins() {
        try {
            this.resultPins = this.gpioServiceImpl.getAvailablePins();
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    /*
     * Then
     */

    private void thenPinIsNotNull() {
        assertNotNull(this.resultPin);
    }

    private void thenAvailablePinsIsNotNullOrEmpty() {
        assertNotNull(this.resultPins);
        assertFalse(this.resultPins.isEmpty());
    }
}