/*******************************************************************************
 * Copyright (c) 2025 Eurotech and/or its affiliates and others
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *  Eurotech
 *******************************************************************************/
/* Some portions generated by generative AI */
package org.eclipse.kura.linux.gpio.libgpiod;

import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.mockStatic;
import static org.mockito.Mockito.when;

import org.eclipse.kura.gpio.GPIOService;
import org.eclipse.kura.gpio.KuraGPIODirection;
import org.eclipse.kura.gpio.KuraGPIOMode;
import org.eclipse.kura.gpio.KuraGPIOPin;
import org.eclipse.kura.gpio.KuraGPIOTrigger;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.mockito.MockedStatic;

public class GPIOServiceImplTest extends StepsCollection {

    private MockedStatic<LibGpiodGPIOServiceFactory> libGpiodGPIOServiceFactoryMock;
    private GPIOService GPIOServiceMock;

    @Before
    public void setup() {
        this.libGpiodGPIOServiceFactoryMock = mockStatic(LibGpiodGPIOServiceFactory.class);
        this.GPIOServiceMock = mock(GPIOService.class);
        this.libGpiodGPIOServiceFactoryMock.when(() -> LibGpiodGPIOServiceFactory.getInstance())
                .thenReturn(java.util.Optional.of(this.GPIOServiceMock));
    }

    @After
    public void cleanup() {
        this.libGpiodGPIOServiceFactoryMock.close();
    }

    @Test
    public void testActivateGPIOService() {
        givenGPIOServiceImpl();

        whenActivateGPIOService();

        thenNoExceptionOccurred();
    }

    @Test
    public void testDeactivateGPIOService() {
        givenGPIOServiceImpl();
        givenActivatedGPIOService();

        whenDeactivateGPIOService();

        thenNoExceptionOccurred();
    }

    @Test
    public void testGetPinByNameWithoutActivation() {
        givenGPIOServiceImpl();

        whenGetPinByName("GPIO_01");

        thenExceptionOccurred(IllegalStateException.class);
    }

    @Test
    public void testGetPinByNameWithActivation() {
        givenGPIOServicePin("GPIO_01");
        givenGPIOServiceImpl();
        givenActivatedGPIOService();

        whenGetPinByName("GPIO_01");

        thenPinIsNotNull();
    }

    @Test
    public void testGetPinByNameWithParametersWithoutActivation() {
        givenGPIOServicePin("GPIO_01", KuraGPIODirection.OUTPUT, KuraGPIOMode.OUTPUT_PUSH_PULL, KuraGPIOTrigger.NONE);
        givenGPIOServiceImpl();

        whenGetPinByName("GPIO_01", KuraGPIODirection.OUTPUT, KuraGPIOMode.OUTPUT_PUSH_PULL, KuraGPIOTrigger.NONE);

        thenExceptionOccurred(IllegalStateException.class);
    }

    @Test
    public void testGetPinByNameWithParametersWithActivation() {
        givenGPIOServicePin("GPIO_01", KuraGPIODirection.OUTPUT, KuraGPIOMode.OUTPUT_PUSH_PULL, KuraGPIOTrigger.NONE);
        givenGPIOServiceImpl();
        givenActivatedGPIOService();

        whenGetPinByName("GPIO_01", KuraGPIODirection.OUTPUT, KuraGPIOMode.OUTPUT_PUSH_PULL, KuraGPIOTrigger.NONE);

        thenPinIsNotNull();
    }

    @Test
    public void testGetPinByTerminalWithoutActivation() {
        givenGPIOServicePin(1002);
        givenGPIOServiceImpl();

        whenGetPinByTerminal(1002);

        thenExceptionOccurred(IllegalStateException.class);
    }

    @Test
    public void testGetPinByTerminalWithActivation() {
        givenGPIOServicePin(1002);
        givenGPIOServiceImpl();
        givenActivatedGPIOService();

        whenGetPinByTerminal(1002);

        thenPinIsNotNull();
    }

    @Test
    public void testGetPinByTerminalWithParametersWithoutActivation() {
        givenGPIOServicePin(2002, KuraGPIODirection.INPUT, KuraGPIOMode.INPUT_PULL_UP, KuraGPIOTrigger.BOTH_EDGES);
        givenGPIOServiceImpl();

        whenGetPinByTerminal(2002, KuraGPIODirection.INPUT, KuraGPIOMode.INPUT_PULL_UP, KuraGPIOTrigger.BOTH_EDGES);

        thenExceptionOccurred(IllegalStateException.class);
    }

    @Test
    public void testGetPinByTerminalWithParametersWithActivation() {
        givenGPIOServicePin(2002, KuraGPIODirection.INPUT, KuraGPIOMode.INPUT_PULL_UP, KuraGPIOTrigger.BOTH_EDGES);
        givenGPIOServiceImpl();
        givenActivatedGPIOService();

        whenGetPinByTerminal(2002, KuraGPIODirection.INPUT, KuraGPIOMode.INPUT_PULL_UP, KuraGPIOTrigger.BOTH_EDGES);

        thenPinIsNotNull();
    }

    @Test
    public void testGetAvailablePinsWithoutActivation() {
        givenGPIOServiceImpl();

        whenGetAvailablePins();

        thenExceptionOccurred(IllegalStateException.class);
    }

    @Test
    public void testGetAvailablePinsWithActivation() {
        givenGPIOServiceImpl();
        givenActivatedGPIOService();

        whenGetAvailablePins();

        thenAvailablePinsIsNotNull();
    }

    /*
     * Given
     */

    private void givenGPIOServicePin(String pinName) {
        KuraGPIOPin pinMock = mock(KuraGPIOPin.class);
        when(GPIOServiceMock.getPinByName(pinName)).thenReturn(pinMock);
    }

    private void givenGPIOServicePin(String pinName, KuraGPIODirection direction, KuraGPIOMode mode,
            KuraGPIOTrigger trigger) {
        KuraGPIOPin pinMock = mock(KuraGPIOPin.class);
        when(GPIOServiceMock.getPinByName(pinName, direction, mode, trigger)).thenReturn(pinMock);
    }

    private void givenGPIOServicePin(int pinTerminal) {
        KuraGPIOPin pinMock = mock(KuraGPIOPin.class);
        when(GPIOServiceMock.getPinByTerminal(pinTerminal)).thenReturn(pinMock);
    }

    private void givenGPIOServicePin(int pinTerminal, KuraGPIODirection direction, KuraGPIOMode mode,
            KuraGPIOTrigger trigger) {
        KuraGPIOPin pinMock = mock(KuraGPIOPin.class);
        when(GPIOServiceMock.getPinByTerminal(pinTerminal, direction, mode, trigger)).thenReturn(pinMock);
    }
}