/*******************************************************************************
 * Copyright (c) 2025 Eurotech and/or its affiliates and others
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *  Eurotech
 *******************************************************************************/
/* Some portions generated by generative AI */
package org.eclipse.kura.linux.gpio.libgpiod;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.mockStatic;
import static org.mockito.Mockito.when;

import java.util.Optional;

import org.eclipse.kura.gpio.GPIOService;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.mockito.MockedStatic;

import com.sun.jna.Native;

public class LibGpiodGPIOServiceFactoryTest extends CommonSteps {

    private MockedStatic<Native> nativeMock;
    private LibGpiodVersionDetector.VersionDetectionInterface nativeInterfaceMock;
    private Optional<GPIOService> resultService;
    private Optional<GPIOService> resultServiceAgain;

    @Before
    public void setup() {
        this.nativeMock = mockStatic(Native.class);
        this.nativeInterfaceMock = mock(LibGpiodVersionDetector.VersionDetectionInterface.class);
        this.nativeMock.when(() -> Native.load("gpiod", LibGpiodVersionDetector.VersionDetectionInterface.class))
                .thenReturn(this.nativeInterfaceMock);
        LibGpiodGPIOServiceFactory.clearInstance();
    }

    @After
    public void cleanup() {
        this.nativeMock.close();
    }

    @Test
    public void testGetInstanceReturnsService1_6_X() {
        givenLibGpiodVersionDetector("1.6.3");

        whenGetFactoryInstance();

        thenNoExceptionOccurred();
        thenServiceIsPresent();
    }

    @Test
    public void testGetInstanceReturnsService2_X_X() {
        givenLibGpiodVersionDetector("2.2.2");

        whenGetFactoryInstance();

        thenNoExceptionOccurred();
        thenServiceIsPresent();
    }

    @Test
    public void testGetInstanceReturnsServiceUnknown() {
        givenLibGpiodVersionDetector("abcdef");

        whenGetFactoryInstance();

        thenNoExceptionOccurred();
        thenServiceIsNotPresent();
    }

    @Test
    public void testGetInstanceReturnsSameInstance() {
        givenLibGpiodVersionDetector("1.6.3");

        whenGetFactoryInstance();
        whenGetFactoryInstanceAgain();

        thenNoExceptionOccurred();
        thenServiceIsPresent();
        thenServicesAreSame();
    }

    /*
     * Given
     */

    private void givenLibGpiodVersionDetector(String version) {
        if (version.startsWith("1.6.")) {
            when(this.nativeInterfaceMock.gpiod_api_version()).thenThrow(new UnsatisfiedLinkError("Not found"));
            when(this.nativeInterfaceMock.gpiod_version_string()).thenReturn("1.6.3");
        } else if (version.startsWith("2.")) {
            when(this.nativeInterfaceMock.gpiod_api_version()).thenReturn("2.2.2");
            when(this.nativeInterfaceMock.gpiod_version_string()).thenThrow(new UnsatisfiedLinkError("Not found"));
        } else {
            when(this.nativeInterfaceMock.gpiod_api_version()).thenThrow(new UnsatisfiedLinkError("Not found"));
            when(this.nativeInterfaceMock.gpiod_version_string()).thenThrow(new UnsatisfiedLinkError("Not found"));
        }
    }

    /*
     * When
     */

    private void whenGetFactoryInstance() {
        try {
            this.resultService = LibGpiodGPIOServiceFactory.getInstance();
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    private void whenGetFactoryInstanceAgain() {
        try {
            this.resultServiceAgain = LibGpiodGPIOServiceFactory.getInstance();
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    /*
     * Then
     */

    private void thenServiceIsPresent() {
        assertTrue(this.resultService.isPresent());
    }

    private void thenServiceIsNotPresent() {
        assertFalse(this.resultService.isPresent());
    }

    private void thenServicesAreSame() {
        assertEquals(this.resultService.get(), this.resultServiceAgain.get());
    }
}