/*******************************************************************************
 * Copyright (c) 2025 Eurotech and/or its affiliates and others
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *  Eurotech
 *******************************************************************************/
/* Some portions generated by generative AI */
package org.eclipse.kura.linux.gpio.libgpiod;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyInt;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.io.File;
import java.io.IOException;
import java.lang.reflect.Field;
import java.nio.file.FileAlreadyExistsException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

import org.eclipse.kura.gpio.GPIOService;
import org.eclipse.kura.gpio.KuraGPIODirection;
import org.eclipse.kura.gpio.KuraGPIOMode;
import org.eclipse.kura.gpio.KuraGPIOPin;
import org.eclipse.kura.gpio.KuraGPIOTrigger;
import org.eclipse.kura.gpio.PinStatusListener;
import org.eclipse.kura.linux.gpio.libgpiod1.LibGpiodV1GPIOService;
import org.eclipse.kura.linux.gpio.libgpiod1.LibGpiodV1Native;
import org.eclipse.kura.linux.gpio.libgpiod1.LibGpiodV1Pin;
import org.mockito.Mockito;

import com.sun.jna.Pointer;

public class StepsCollection {

    protected static final String DEVICE_FOLDER = "/tmp/";

    // protected LibGpiodVersionDetector versionDetector;
    protected GPIOServiceImpl gpioServiceImpl;
    protected LibGpiodV1GPIOService v1Service;
    protected LibGpiodV1Pin v1Pin;
    protected Boolean v1PinValue;
    protected String message;

    protected Exception occurredException;
    protected KuraGPIOPin resultPin;
    protected KuraGPIOPin resultPinAgain;
    protected Map<Integer, String> resultPins;
    protected Optional<GPIOService> resultService;
    protected Optional<GPIOService> resultServiceAgain;
    protected PinStatusListener pinStatusListener;
    // protected LibGpiodVersionDetector.LibGpiodVersion resultVersion;
    // protected String resultVersionString;
    // protected LibGpiodVersionDetector.LibGpiodVersion resultVersionAgain;
    // protected String resultVersionStringAgain;

    protected LibGpiodV1Native mockNativeInterface;
    protected Pointer mockChipPointer1;
    protected Pointer mockChipPointer2;
    protected Pointer mockLinePointer1;
    protected Pointer mockLinePointer2;

    // private MockedStatic<Native> nativeMock;
    // private LibGpiodVersionDetector.VersionDetectionInterface nativeInterfaceMock;
    //
    // /*
    // * Setup and mocking
    // */
    // @Before
    // public void setup() {
    // this.nativeMock = mockStatic(Native.class);
    // this.nativeInterfaceMock = mock(LibGpiodVersionDetector.VersionDetectionInterface.class);
    // this.nativeMock.when(() -> Native.load("gpiod", LibGpiodVersionDetector.VersionDetectionInterface.class))
    // .thenReturn(this.nativeInterfaceMock);
    // }
    //
    // @After
    // public void cleanup() {
    // this.nativeMock.close();
    // }

    // @Before
    // public void setupMocks() throws Exception {
    // setupNativeMocks();
    // setupFileSystemMocks();
    // setupLibGpiodServiceMocks();
    // }

    protected void setupNativeMocks() throws Exception {
        mockNativeInterface = mock(LibGpiodV1Native.class);

        mockChipPointer1 = mock(Pointer.class);
        mockChipPointer2 = mock(Pointer.class);
        mockLinePointer1 = mock(Pointer.class);
        mockLinePointer2 = mock(Pointer.class);

        setLibGpiodNativeInstance(mockNativeInterface);

        when(mockNativeInterface.gpiod_version_string()).thenReturn("1.6.4");
        when(mockNativeInterface.gpiod_chip_open(anyString())).thenReturn(mockChipPointer1);
        when(mockNativeInterface.gpiod_chip_num_lines(any(Pointer.class))).thenReturn(32);
        when(mockNativeInterface.gpiod_chip_get_line(any(Pointer.class), anyInt())).thenReturn(mockLinePointer1);
        when(mockNativeInterface.gpiod_line_request_input(any(Pointer.class), anyString())).thenReturn(0);
        when(mockNativeInterface.gpiod_line_request_output(any(Pointer.class), anyString(), anyInt())).thenReturn(0);
        when(mockNativeInterface.gpiod_line_get_value(any(Pointer.class))).thenReturn(1);
        when(mockNativeInterface.gpiod_line_set_value(any(Pointer.class), anyInt())).thenReturn(0);
        when(mockNativeInterface.gpiod_line_offset(any(Pointer.class))).thenReturn(0);
        when(mockNativeInterface.gpiod_line_name(any(Pointer.class))).thenReturn("GPIO0");
        when(mockNativeInterface.gpiod_line_is_used(any(Pointer.class))).thenReturn(false);
        when(mockNativeInterface.gpiod_line_direction(any(Pointer.class)))
                .thenReturn(LibGpiodV1Native.GPIOD_LINE_DIRECTION_INPUT);
        when(mockNativeInterface.gpiod_line_bias(any(Pointer.class)))
                .thenReturn(LibGpiodV1Native.GPIOD_LINE_BIAS_PULL_UP);
        when(mockNativeInterface.gpiod_ctxless_find_line(anyString(), any(byte[].class), anyInt(), any()))
                .thenReturn(0);
    }

    protected void setupFileSystemMocks() {
        // For now, skip filesystem mocking and rely on implementation fallbacks
    }

    protected File createMockChipFile(String name) {
        File mockFile = mock(File.class);
        when(mockFile.getName()).thenReturn(name);
        when(mockFile.exists()).thenReturn(true);
        when(mockFile.getAbsolutePath()).thenReturn("/dev/" + name);
        return mockFile;
    }

    protected void setupLibGpiodServiceMocks() throws Exception {
        resetLibGpiodVersionDetector();
    }

    protected void setLibGpiodNativeInstance(LibGpiodV1Native mockInstance) throws Exception {
        try {
            Field instanceField = LibGpiodV1Native.class.getDeclaredField("INSTANCE");
            instanceField.setAccessible(true);

            try {
                Field modifiersField = Field.class.getDeclaredField("modifiers");
                modifiersField.setAccessible(true);
                modifiersField.setInt(instanceField, instanceField.getModifiers() & ~java.lang.reflect.Modifier.FINAL);
            } catch (NoSuchFieldException e) {
                // In newer Java versions, modifiers field is not accessible
                // Use alternative approach or skip this if not critical for tests
            }

            instanceField.set(null, mockInstance);
        } catch (Exception e) {
            // If field injection fails, tests will run without mocked native instance
            // This is acceptable for unit tests that focus on business logic
        }
    }

    protected void resetLibGpiodVersionDetector() throws Exception {
        Field versionField = LibGpiodVersionDetector.class.getDeclaredField("detectedVersion");
        versionField.setAccessible(true);
        versionField.set(null, null);

        Field versionStringField = LibGpiodVersionDetector.class.getDeclaredField("detectedVersionString");
        versionStringField.setAccessible(true);
        versionStringField.set(null, null);
    }

    protected void cleanupMocks() {
        if (mockNativeInterface != null) {
            Mockito.reset(mockNativeInterface);
        }
        if (mockChipPointer1 != null) {
            Mockito.reset(mockChipPointer1);
        }
        if (mockChipPointer2 != null) {
            Mockito.reset(mockChipPointer2);
        }
        if (mockLinePointer1 != null) {
            Mockito.reset(mockLinePointer1);
        }
        if (mockLinePointer2 != null) {
            Mockito.reset(mockLinePointer2);
        }
    }

    /*
     * Given
     */

    // protected void givenLibGpiodVersionDetector(String version) {
    // if (version.startsWith("1.6.")) {
    // when(this.nativeInterfaceMock.gpiod_api_version()).thenThrow(new UnsatisfiedLinkError("Not found"));
    // when(this.nativeInterfaceMock.gpiod_version_string()).thenReturn("1.6.3");
    // } else if (version.startsWith("2.")) {
    // when(this.nativeInterfaceMock.gpiod_api_version()).thenReturn("2.2.2");
    // when(this.nativeInterfaceMock.gpiod_version_string()).thenThrow(new UnsatisfiedLinkError("Not found"));
    // } else {
    // when(this.nativeInterfaceMock.gpiod_api_version()).thenThrow(new UnsatisfiedLinkError("Not found"));
    // when(this.nativeInterfaceMock.gpiod_version_string()).thenThrow(new UnsatisfiedLinkError("Not found"));
    // }
    // this.versionDetector = new LibGpiodVersionDetector();
    // }

    protected void givenGPIOServiceImpl() {
        this.gpioServiceImpl = new GPIOServiceImpl();
    }

    protected void givenActivatedGPIOService() {
        this.gpioServiceImpl.activate();
    }

    protected void givenV1GPIOService() {
        this.v1Service = new LibGpiodV1GPIOService() {

            @Override
            public void initialize() {
                this.availablePins.put("GPIO0_1", 1);
                this.availablePins.put("GPIO2_3", 2003);
                this.availablePins.put("GPIO5_23", 5023);
                this.initialized.set(true);
            }

            @Override
            protected String getDeviceFolderPath() {
                return DEVICE_FOLDER;
            }
        };
    }

    protected void givenV1GPIOServiceNotInitialized(String deviceFolderPath) {
        this.v1Service = new LibGpiodV1GPIOService() {

            @Override
            protected String getDeviceFolderPath() {
                return deviceFolderPath;
            }
        };
    }

    protected void givenTmpGpioChips() throws IOException {
        for (int i = 0; i < 3; i++) {
            try {
                Path newFilePath = Paths.get(DEVICE_FOLDER + "gpiochip" + i);
                Files.createFile(newFilePath);
            } catch (FileAlreadyExistsException e) {
                // Ignore if file already exists
            }
        }
    }

    protected void givenTmpGpioChips(int gpioChipNumber) throws IOException {
        try {
            Path newFilePath = Paths.get(DEVICE_FOLDER + "gpiochip" + gpioChipNumber);
            Files.createFile(newFilePath);
        } catch (FileAlreadyExistsException e) {
            // Ignore if file already exists
        }
    }

    protected void givenV1Pin(String pinName, int terminal) {
        String chipPath = "/dev/gpiochip" + terminal / 1000;
        Integer offset = terminal % 1000;
        this.v1Pin = new LibGpiodV1Pin(chipPath, offset, KuraGPIODirection.INPUT, KuraGPIOMode.INPUT_PULL_UP,
                KuraGPIOTrigger.NONE, pinName);
    }

    protected void givenV1Pin(String pinName, int terminal, KuraGPIODirection direction, KuraGPIOMode mode,
            KuraGPIOTrigger trigger) {
        String chipPath = "/dev/gpiochip" + terminal / 1000;
        Integer offset = terminal % 1000;
        this.v1Pin = new LibGpiodV1Pin(chipPath, offset, direction, mode, trigger, pinName);
    }

    protected void givenPinStatusListener() {
        this.pinStatusListener = mock(PinStatusListener.class);
    }

    /*
     * When
     */

    protected void whenActivateGPIOService() {
        try {
            this.gpioServiceImpl.activate();
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    protected void whenDeactivateGPIOService() {
        try {
            this.gpioServiceImpl.deactivate();
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    protected void whenGetPinByName(String pinName) {
        try {
            this.resultPin = this.gpioServiceImpl.getPinByName(pinName);
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    protected void whenGetPinByName(String pinName, KuraGPIODirection direction, KuraGPIOMode mode,
            KuraGPIOTrigger trigger) {
        try {
            this.resultPin = this.gpioServiceImpl.getPinByName(pinName, direction, mode, trigger);
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    protected void whenGetPinByTerminal(int terminal) {
        try {
            this.resultPin = this.gpioServiceImpl.getPinByTerminal(terminal);
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    protected void whenGetPinByTerminal(int terminal, KuraGPIODirection direction, KuraGPIOMode mode,
            KuraGPIOTrigger trigger) {
        try {
            this.resultPin = this.gpioServiceImpl.getPinByTerminal(terminal, direction, mode, trigger);
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    protected void whenGetAvailablePins() {
        try {
            this.resultPins = this.gpioServiceImpl.getAvailablePins();
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    protected void whenGetFactoryInstance() {
        try {
            this.resultService = LibGpiodGPIOServiceFactory.getInstance();
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    protected void whenGetFactoryInstanceAgain() {
        try {
            this.resultServiceAgain = LibGpiodGPIOServiceFactory.getInstance();
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    protected void whenCreateFactoryService() {
        try {
            this.resultService = LibGpiodGPIOServiceFactory.createService();
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    // protected void whenGetVersion() {
    // try {
    // this.resultVersion = versionDetector.getVersion();
    // } catch (Exception e) {
    // this.occurredException = e;
    // }
    // }
    //
    // protected void whenGetVersionString() {
    // try {
    // this.resultVersionString = versionDetector.getVersionString();
    // } catch (Exception e) {
    // this.occurredException = e;
    // }
    // }
    //
    // protected void whenGetVersionAgain() {
    // try {
    // this.resultVersionAgain = versionDetector.getVersion();
    // } catch (Exception e) {
    // this.occurredException = e;
    // }
    // }
    //
    // protected void whenGetVersionStringAgain() {
    // try {
    // this.resultVersionStringAgain = versionDetector.getVersionString();
    // } catch (Exception e) {
    // this.occurredException = e;
    // }
    // }
    //
    // protected void whenRedetectVersion() {
    // try {
    // versionDetector.redetect();
    // } catch (Exception e) {
    // this.occurredException = e;
    // }
    // }

    protected void whenV1ServiceGetPinByName(String pinName) {
        try {
            this.resultPin = this.v1Service.getPinByName(pinName);
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    protected void whenV1ServiceGetPinByNameAgain(String pinName) {
        try {
            this.resultPinAgain = this.v1Service.getPinByName(pinName);
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    protected void whenV1ServiceGetPinByName(String pinName, KuraGPIODirection direction, KuraGPIOMode mode,
            KuraGPIOTrigger trigger) {
        try {
            this.resultPin = this.v1Service.getPinByName(pinName, direction, mode, trigger);
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    protected void whenV1ServiceGetPinByTerminal(int pinTerminal) {
        try {
            this.resultPin = this.v1Service.getPinByTerminal(pinTerminal);
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    protected void whenV1ServiceGetPinByTerminalAgain(int pinTerminal) {
        try {
            this.resultPinAgain = this.v1Service.getPinByTerminal(pinTerminal);
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    protected void whenV1ServiceGetPinByTerminal(int pinTerminal, KuraGPIODirection direction, KuraGPIOMode mode,
            KuraGPIOTrigger trigger) {
        try {
            this.resultPin = this.v1Service.getPinByTerminal(pinTerminal, direction, mode, trigger);
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    protected void whenV1ServiceGetAvailablePins() {
        try {
            this.resultPins = this.v1Service.getAvailablePins();
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    protected void whenV1PinGetValue() {
        try {
            this.resultPin.getValue();
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    protected void whenV1PinSetValue(boolean value) {
        try {
            this.v1Pin.setValue(value);
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    protected void whenV1CacheIsCleared() {
        try {
            this.v1Service.clearCache();
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    protected void whenV1CacheIsRefreshed() {
        try {
            this.v1Service.refresh();
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    protected void whenV1PinIsOpened() {
        try {
            this.v1Pin.open();
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    protected void whenV1PinIsClosed() {
        try {
            this.v1Pin.close();
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    protected void whenV1PinValueIsRead() {
        try {
            this.v1PinValue = this.v1Pin.getValue();
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    protected void whenV1PinValueIsSetTo(boolean value) {
        try {
            this.v1Pin.setValue(value);
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    protected void whenV1PinAddPinStatusListener(PinStatusListener listener) {
        try {
            this.v1Pin.addPinStatusListener(listener);
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    protected void whenV1PinRemovePinStatusListener(PinStatusListener listener) {
        try {
            this.v1Pin.removePinStatusListener(listener);
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    protected void whenV1ServiceIsInitialized() {
        try {
            this.v1Service.initialize();
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    protected void whenV1PinToStringIsCalled() {
        try {
            this.message = this.v1Pin.toString();
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    /*
     * Then
     */

    protected <E extends Exception> void thenExceptionOccurred(Class<E> expectedException) {
        assertNotNull(this.occurredException);
        assertEquals(expectedException.getName(), this.occurredException.getClass().getName());
    }

    protected void thenNoExceptionOccurred() {
        assertNull(this.occurredException);
    }

    protected void thenPinIsNotNull() {
        assertNotNull(this.resultPin);
    }

    protected void thenPinIsNull() {
        assertNull(this.resultPin);
    }

    protected void thenAvailablePinsIsNotNullOrEmpty() {
        assertNotNull(this.resultPins);
        assertFalse(this.resultPins.isEmpty());
    }

    protected void thenAvailablePinsIsEmpty() {
        assertTrue(this.resultPins == null || this.resultPins.isEmpty());
    }

    protected void thenServiceIsPresent() {
        assertTrue(this.resultService.isPresent());
    }

    protected void thenServiceIsNotPresent() {
        assertFalse(this.resultService.isPresent());
    }

    protected void thenPinIs(String pinName, KuraGPIODirection direction, KuraGPIOMode mode, KuraGPIOTrigger trigger) {
        assertEquals(pinName, this.resultPin.getName());
        assertEquals(direction, this.resultPin.getDirection());
        assertEquals(mode, this.resultPin.getMode());
        assertEquals(trigger, this.resultPin.getTrigger());
    }

    protected void thenPinIs(int pinTerminal, KuraGPIODirection direction, KuraGPIOMode mode, KuraGPIOTrigger trigger) {
        assertEquals(pinTerminal, this.resultPin.getIndex());
        assertEquals(direction, this.resultPin.getDirection());
        assertEquals(mode, this.resultPin.getMode());
        assertEquals(trigger, this.resultPin.getTrigger());
    }

    protected void thenPinsAreSame() {
        assertEquals(this.resultPin, this.resultPinAgain);
    }

    protected void thenV1PinIsCreated() {
        assertNotNull(this.v1Pin);
        assertTrue(this.v1Pin instanceof LibGpiodV1Pin);
    }

    protected void thenV1PinHasCorrectParameters(String pinName, int pinTerminal, KuraGPIODirection direction,
            KuraGPIOMode mode, KuraGPIOTrigger trigger) {
        assertEquals(pinName, this.v1Pin.getName());
        assertEquals(pinTerminal, this.v1Pin.getIndex());
        assertEquals(direction, this.v1Pin.getDirection());
        assertEquals(mode, this.v1Pin.getMode());
        assertEquals(trigger, this.v1Pin.getTrigger());
    }

    protected void thenV1PinIsNotOpen() {
        assertFalse(v1Pin.isOpen());
    }

    protected void thenV1PinIsOpen() {
        assertTrue(v1Pin.isOpen());
    }

    protected void thenV1PinValueIsBoolean() {
        assertNotNull(this.v1PinValue);
        assertTrue(this.v1PinValue instanceof Boolean);
    }

    protected void thenV1PinValueReadIs(boolean expectedValue) {
        assertEquals(expectedValue, this.v1PinValue.booleanValue());
    }

    protected void thenV1PinIndexIs(int expectedIndex) {
        assertEquals(expectedIndex, this.v1Pin.getIndex());
    }

    protected void thenMessageIs(String expectedMessage) {
        assertEquals(expectedMessage, this.message);
    }

    // protected void thenVersionIs(LibGpiodVersionDetector.LibGpiodVersion expectedVersion) {
    // assertEquals(expectedVersion, this.resultVersion);
    // }
    //
    // protected void thenVersionStringIs(String expectedVersionString) {
    // assertEquals(expectedVersionString, this.resultVersionString);
    // }
    //
    // protected void thenVersionStringIsNotNull() {
    // assertNotNull(this.resultVersionString);
    // }
    //
    // protected void thenVersionIs(String version) {
    // assertNotNull(this.resultVersion);
    // assertTrue(this.resultVersion instanceof LibGpiodVersionDetector.LibGpiodVersion);
    // if (version.startsWith("1.6.")) {
    // assertEquals(LibGpiodVersionDetector.LibGpiodVersion.V1_6_X, this.resultVersion);
    // } else if (version.startsWith("2.")) {
    // assertEquals(LibGpiodVersionDetector.LibGpiodVersion.V2_X_X, this.resultVersion);
    // } else {
    // assertEquals(LibGpiodVersionDetector.LibGpiodVersion.UNKNOWN, this.resultVersion);
    // }
    // }
    //
    // protected void thenVersionsAreSame() {
    // assertEquals(this.resultVersion, this.resultVersionAgain);
    // }
    //
    // protected void thenVersionStringsAreSame() {
    // assertEquals(this.resultVersionString, this.resultVersionStringAgain);
    // }

    /*
     * Utilities
     */

    protected void reset() {
        this.occurredException = null;
        this.resultPin = null;
        this.resultPins = null;
        this.resultService = null;
        // this.resultVersion = null;
        // this.resultVersionString = null;
        cleanupMocks();
        // try {
        // setupMocks();
        // } catch (Exception e) {
        // throw new RuntimeException("Failed to reset mocks", e);
        // }
    }

    class PropertiesBuilder {

        private Map<String, Object> properties = new HashMap<>();

        public PropertiesBuilder add(String key, Object value) {
            this.properties.put(key, value);
            return this;
        }

        public Map<String, Object> build() {
            return this.properties;
        }
    }
}