/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.clock;

/**
 * Represents the synchronization state of the clock, as reported by a {@link ClockService}.
 *
 * @since 3.0
 */
public enum ClockSyncState {

    /**
     * The clock is currently synchronized with a remote time source.
     */
    SYNCED,

    /**
     * The clock is not currently synchronized with a remote time source.
     */
    NOT_SYNCED,

    /**
     * The clock synchronization failed. This state is reported only when a failure condition is positively
     * detected, for example the time daemon unit is reported by systemd in a <code>failed</code> state, or a
     * finite number of synchronization retries was configured and those retries have been exhausted. Where the
     * synchronization provider is configured to retry indefinitely, retries alone never lead to this state. It
     * is never inferred from how long the clock has been in the {@link #NOT_SYNCED} state: a device that has
     * just booted and is still reaching its time source is honestly {@link #NOT_SYNCED}, not {@link #FAILED}.
     */
    FAILED,

    /**
     * The synchronization state of the clock cannot be determined.
     */
    UNKNOWN;

}
