/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.clock;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * Represents the synchronization status of the clock, as reported by a {@link ClockService}.
 *
 * @since 3.0
 * @noimplement This class is not intended to be extended by clients.
 */
@ProviderType
public class ClockSyncStatus {

    private final ClockSyncState state;
    private final Date lastSync;
    private final String syncProvider;
    private final String failureReason;
    private final Integer retryCount;

    /**
     * Creates a new {@link ClockSyncStatus} instance.
     *
     * @param state
     *            the current clock synchronization state, cannot be <code>null</code>.
     * @param lastSync
     *            the {@link Date} the clock was last synchronized, can be <code>null</code> if the clock has not
     *            yet synchronized.
     * @param syncProvider
     *            the name of the synchronization provider that reported this status (e.g. {@code "java-ntp"},
     *            {@code "chrony-advanced"}), can be <code>null</code> if not known.
     * @param failureReason
     *            a human readable description of the detected failure, non-<code>null</code> only when the state
     *            is {@link ClockSyncState#FAILED}, <code>null</code> otherwise.
     * @param retryCount
     *            the number of consecutive failed synchronization attempts in the current cycle of the
     *            synchronization provider, can be <code>null</code> if the provider does not track retries.
     */
    public ClockSyncStatus(ClockSyncState state, Date lastSync, String syncProvider, String failureReason,
            Integer retryCount) {
        this.state = state;
        this.lastSync = lastSync;
        this.syncProvider = syncProvider;
        this.failureReason = failureReason;
        this.retryCount = retryCount;
    }

    /**
     * Returns the current clock synchronization state.
     *
     * @return the clock synchronization state, never <code>null</code>.
     */
    public ClockSyncState getState() {
        return this.state;
    }

    /**
     * Returns the {@link Date} the clock was last synchronized.
     *
     * @return the {@link Date} the clock was last synchronized, can be <code>null</code> if the clock has not
     *         yet synchronized.
     */
    public Date getLastSync() {
        return this.lastSync;
    }

    /**
     * Returns the name of the synchronization provider that reported this status.
     *
     * @return the name of the synchronization provider, can be <code>null</code> if not known.
     */
    public String getSyncProvider() {
        return this.syncProvider;
    }

    /**
     * Returns a human readable description of the detected failure.
     *
     * @return the description of the detected failure, non-<code>null</code> only when the state is
     *         {@link ClockSyncState#FAILED}, <code>null</code> otherwise.
     */
    public String getFailureReason() {
        return this.failureReason;
    }

    /**
     * Returns the number of consecutive failed synchronization attempts in the current cycle of the
     * synchronization provider.
     *
     * @return the number of consecutive failed synchronization attempts, can be <code>null</code> if the provider
     *         does not track retries.
     */
    public Integer getRetryCount() {
        return this.retryCount;
    }

}
