/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.clock;

/**
 * Represents the synchronization state of the clock, as reported by a {@link ClockService}.
 *
 * @since 3.0
 */
public enum ClockSyncState {

    /**
     * The clock is currently synchronized with a remote time source.
     */
    SYNCED,

    /**
     * The clock is not currently synchronized with a remote time source.
     */
    NOT_SYNCED,

    /**
     * The synchronization state of the clock cannot be determined.
     */
    UNKNOWN;

}
