/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.container.orchestration.provider.impl;

import java.util.Optional;

import org.eclipse.kura.system.SystemService;
import org.osgi.service.component.runtime.ServiceComponentRuntime;
import org.osgi.service.component.runtime.dto.ComponentDescriptionDTO;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.github.dockerjava.api.DockerClient;
import com.github.dockerjava.core.DefaultDockerClientConfig;
import com.github.dockerjava.core.DockerClientConfig;
import com.github.dockerjava.core.DockerClientImpl;
import com.github.dockerjava.httpclient5.ApacheDockerHttpClient;
import com.github.dockerjava.transport.DockerHttpClient;

public class ContainerOrchestrationActivator {

    private static final Logger logger = LoggerFactory.getLogger(ContainerOrchestrationActivator.class);
    private static final String SERVICE_COMPONENT_ID = "org.eclipse.kura.container.orchestration.provider.ContainerOrchestrationService";
    private static final String DOCKER_HOST_KEY = "kura.docker.host";
    private static final String DEFAULT_DOCKER_HOST = "unix:///var/run/docker.sock";

    private ServiceComponentRuntime scr;
    private String dockerHost = DEFAULT_DOCKER_HOST;

    public void setSystemService(final SystemService systemService) {
        this.dockerHost = systemService.getProperties().getProperty(DOCKER_HOST_KEY, DEFAULT_DOCKER_HOST);
    }

    public void setServiceComponentRuntime(final ServiceComponentRuntime scr) {
        this.scr = scr;
    }

    public void activate() {
        if (isDockerReachable()) {
            logger.info("Docker daemon reachable at {}, enabling Container Orchestration Service integration",
                    this.dockerHost);

            final Optional<ComponentDescriptionDTO> component = this.scr.getComponentDescriptionDTOs().stream()
                    .filter(c -> SERVICE_COMPONENT_ID.equals(c.name)).findAny();

            if (component.isPresent()) {
                this.scr.enableComponent(component.get());
            } else {
                logger.warn("cannot find ContainerOrchestrationService component");
            }
        } else {
            logger.info("Docker daemon not reachable at {}, not enabling Container Orchestration Service integration",
                    this.dockerHost);
        }
    }

    protected boolean isDockerReachable() {
        DockerClientConfig config = null;
        DockerHttpClient httpClient = null;
        DockerClient dockerClient = null;
        try {
            config = DefaultDockerClientConfig.createDefaultConfigBuilder().withDockerHost(this.dockerHost).build();
            httpClient = new ApacheDockerHttpClient.Builder().dockerHost(config.getDockerHost()).build();
            dockerClient = DockerClientImpl.getInstance(config, httpClient);
            dockerClient.pingCmd().exec();
            return true;
        } catch (Exception ex) {
            return false;
        } finally {
            if (dockerClient != null) {
                try {
                    dockerClient.close();
                } catch (Exception ex) {
                    logger.debug("Error closing Docker client", ex);
                }
            }
            if (httpClient != null) {
                try {
                    httpClient.close();
                } catch (Exception ex) {
                    logger.debug("Error closing Docker HTTP client", ex);
                }
            }
        }
    }
}
