/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 * Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.configuration;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import org.eclipse.kura.KuraException;
import org.eclipse.kura.configuration.ComponentConfiguration;
import org.junit.Test;

public class GetSnapshotTest {

    private static final long SNAPSHOT_ID = 1L;
    private static final String FAILING_PID = "failing.pid";
    private static final String HEALTHY_PID = "healthy.pid";
    private static final String DECRYPTED_MARKER = "decrypted";

    private Throwable decryptionFailure;
    private List<ComponentConfiguration> snapshot;
    private Throwable propagatedThrowable;

    /*
     * Scenarios
     */

    @Test
    public void returnsAllConfigurationsWhenDecryptionOfOneFails() {
        givenDecryptionOfOneConfigurationFailingWith(new IllegalStateException("decryption failure"));

        whenSnapshotIsRetrieved();

        thenNothingPropagated();
        thenSnapshotPidsAre(FAILING_PID, HEALTHY_PID);
        thenConfigurationDecrypted(HEALTHY_PID);
    }

    @Test
    public void propagatesVirtualMachineErrorDuringDecryption() {
        givenDecryptionOfOneConfigurationFailingWith(new OutOfMemoryError("simulated"));

        whenSnapshotIsRetrieved();

        thenPropagated(OutOfMemoryError.class);
    }

    /*
     * Steps
     */

    private void givenDecryptionOfOneConfigurationFailingWith(Throwable failure) {
        this.decryptionFailure = failure;
    }

    private void whenSnapshotIsRetrieved() {
        try {
            this.snapshot = createConfigurationService().getSnapshot(SNAPSHOT_ID);
        } catch (Throwable e) {
            this.propagatedThrowable = e;
        }
    }

    private void thenNothingPropagated() {
        assertNull(this.propagatedThrowable);
    }

    private void thenPropagated(Class<? extends Throwable> expected) {
        assertTrue("unexpected: " + this.propagatedThrowable, expected.isInstance(this.propagatedThrowable));
    }

    private void thenSnapshotPidsAre(String... expectedPids) {
        assertEquals(Arrays.asList(expectedPids),
                this.snapshot.stream().map(ComponentConfiguration::getPid).collect(Collectors.toList()));
    }

    private void thenConfigurationDecrypted(String pid) {
        final ComponentConfiguration configuration = this.snapshot.stream().filter(c -> pid.equals(c.getPid()))
                .findFirst().orElseThrow(AssertionError::new);
        assertEquals(true, configuration.getConfigurationProperties().get(DECRYPTED_MARKER));
    }

    /*
     * Utilities
     */

    private ConfigurationServiceImpl createConfigurationService() {
        return new ConfigurationServiceImpl() {

            @Override
            XmlComponentConfigurations loadEncryptedSnapshotFileContent(long snapshotID) throws KuraException {
                final XmlComponentConfigurations configurations = new XmlComponentConfigurations();
                configurations.setConfigurations(Arrays.asList(configuration(FAILING_PID), configuration(HEALTHY_PID)));
                return configurations;
            }

            @Override
            void decryptConfigurationProperties(Map<String, Object> configProperties) {
                if (FAILING_PID.equals(configProperties.get("pid"))) {
                    sneakyThrow(GetSnapshotTest.this.decryptionFailure);
                }
                configProperties.put(DECRYPTED_MARKER, true);
            }
        };
    }

    private static ComponentConfiguration configuration(String pid) {
        final Map<String, Object> properties = new HashMap<>();
        properties.put("pid", pid);
        return new ComponentConfigurationImpl(pid, null, properties);
    }

    @SuppressWarnings("unchecked")
    private static <E extends Throwable> void sneakyThrow(Throwable e) throws E {
        throw (E) e;
    }
}
