/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 * Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.configuration;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.atMost;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;

import org.eclipse.kura.KuraException;
import org.eclipse.kura.configuration.ComponentConfiguration;
import org.eclipse.kura.core.testutil.TestUtil;
import org.eclipse.kura.crypto.CryptoService;
import org.junit.After;
import org.junit.Test;
import org.osgi.framework.BundleContext;

public class LoadLatestSnapshotTest {

    private static final long SNAPSHOT_ID = 1L;
    private static final String PID = "test.pid";
    private static final String PLAIN_SNAPSHOT = "plain snapshot";
    private static final String MARSHALLED_SNAPSHOT = "marshalled snapshot";
    private static final String ENCRYPTED_SNAPSHOT = "encrypted snapshot";

    private final CryptoService cryptoService = mock(CryptoService.class);
    private Path snapshotsDirectory;
    private ConfigurationServiceImpl configurationService;
    private List<ComponentConfiguration> loadedConfigurations;
    private Throwable occurredException;

    /*
     * Scenarios
     */

    @Test
    public void loadsSnapshotAfterEncryptingPlainSnapshots() throws Exception {
        givenPlainSnapshotOnDisk();
        givenCryptoServiceDecryptingEncryptedSnapshots();

        whenLatestSnapshotIsLoaded();

        thenNoExceptionOccurred();
        thenLoadedConfigurationPidsAre(PID);
        thenSnapshotOnDiskIs(ENCRYPTED_SNAPSHOT);
    }

    @Test
    public void givesUpAfterOneRetryWhenDecryptionKeepsFailing() throws Exception {
        givenPlainSnapshotOnDisk();
        givenCryptoServiceNeverDecrypting();

        whenLatestSnapshotIsLoaded();

        thenNoExceptionOccurred();
        thenNoConfigurationsLoaded();
        thenSnapshotsEncryptedOnce();
    }

    @After
    public void tearDown() throws IOException {
        if (this.snapshotsDirectory != null) {
            for (final File file : this.snapshotsDirectory.toFile().listFiles()) {
                Files.delete(file.toPath());
            }
            Files.delete(this.snapshotsDirectory);
        }
    }

    /*
     * Steps
     */

    private void givenPlainSnapshotOnDisk() throws IOException, NoSuchFieldException {
        this.snapshotsDirectory = Files.createTempDirectory("snapshots");
        Files.write(snapshotFile(), PLAIN_SNAPSHOT.getBytes(StandardCharsets.UTF_8));

        this.configurationService = new ConfigurationServiceImpl() {

            @Override
            public Set<Long> getSnapshots() throws KuraException {
                return new TreeSet<>(Collections.singleton(SNAPSHOT_ID));
            }

            @Override
            String getSnapshotsDirectory() {
                return LoadLatestSnapshotTest.this.snapshotsDirectory.toString();
            }

            @Override
            protected <T> T unmarshal(String xmlString, Class<T> clazz) throws KuraException {
                return clazz.cast(snapshotContent());
            }

            @Override
            protected String marshal(Object object) {
                return MARSHALLED_SNAPSHOT;
            }
        };
        this.configurationService.setCryptoService(this.cryptoService);
        TestUtil.setFieldValue(this.configurationService, "bundleContext", mock(BundleContext.class));
    }

    private void givenCryptoServiceDecryptingEncryptedSnapshots() throws KuraException {
        when(this.cryptoService.encryptAes(any(char[].class))).thenReturn(ENCRYPTED_SNAPSHOT.toCharArray());
        when(this.cryptoService.decryptAes(any(char[].class)))
                .thenAnswer(invocation -> ENCRYPTED_SNAPSHOT.equals(new String((char[]) invocation.getArgument(0)))
                        ? MARSHALLED_SNAPSHOT.toCharArray()
                        : null);
    }

    private void givenCryptoServiceNeverDecrypting() throws KuraException {
        when(this.cryptoService.encryptAes(any(char[].class))).thenReturn(ENCRYPTED_SNAPSHOT.toCharArray());
        when(this.cryptoService.decryptAes(any(char[].class))).thenReturn(null);
    }

    @SuppressWarnings("unchecked")
    private void whenLatestSnapshotIsLoaded() {
        try {
            this.loadedConfigurations = (List<ComponentConfiguration>) TestUtil
                    .invokePrivate(this.configurationService, "loadLatestSnapshotConfigurations");
        } catch (Throwable e) {
            this.occurredException = e;
        }
    }

    private void thenNoExceptionOccurred() {
        assertNull(this.occurredException);
    }

    private void thenLoadedConfigurationPidsAre(String... expectedPids) {
        final String[] pids = this.loadedConfigurations.stream().map(ComponentConfiguration::getPid)
                .toArray(String[]::new);
        assertEquals(Arrays.asList(expectedPids), Arrays.asList(pids));
    }

    private void thenNoConfigurationsLoaded() {
        assertTrue(this.loadedConfigurations.isEmpty());
    }

    private void thenSnapshotOnDiskIs(String expectedContent) throws IOException {
        assertEquals(expectedContent, new String(Files.readAllBytes(snapshotFile()), StandardCharsets.UTF_8));
    }

    private void thenSnapshotsEncryptedOnce() throws KuraException {
        verify(this.cryptoService, times(1)).encryptAes(any(char[].class));
        verify(this.cryptoService, atMost(3)).decryptAes(any(char[].class));
    }

    /*
     * Utilities
     */

    private Path snapshotFile() {
        return this.snapshotsDirectory.resolve("snapshot_" + SNAPSHOT_ID + ".xml");
    }

    private static XmlComponentConfigurations snapshotContent() {
        final XmlComponentConfigurations configurations = new XmlComponentConfigurations();
        configurations.setConfigurations(
                Collections.singletonList(new ComponentConfigurationImpl(PID, null, new HashMap<>())));
        return configurations;
    }
}
