/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.selftest;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.util.Objects;
import java.util.Queue;
import java.util.concurrent.locks.Lock;

/** Fixtures for KJCS-017, KJCS-019, KJCS-020, KJCS-023, KJCS-102. */
public class Boundary {

    public int exposed;                                // expect: KJCS-X17-PublicMutableField
    public static int exposedStatic;                   // expect: KJCS-X17-PublicMutableField
    public static final int LIMIT = 10;
    protected int notPublic;

    public void unguarded(String name) {               // expect: KJCS-X13-UnvalidatedBoundaryParameter
        System.out.println(name.length());
    }

    public void guardedByRequireNonNull(String name) {
        Objects.requireNonNull(name, "name");
        System.out.println(name.length());
    }

    public void guardedByIfThrow(int port) {
        if (port < 1 || port > 65535) {
            throw new IllegalArgumentException("port");
        }
        exposed = port;
    }

    public void onlyBoolean(boolean flag) {
        exposed = flag ? 1 : 0;
    }

    public void assertIsNotValidation(String name) {
        assert name != null;                           // expect: KJCS-X14-AssertForValidation
        Objects.requireNonNull(name);
    }

    void packagePrivateNotBoundary(String name) {
        System.out.println(name.length());
    }

    void discarded(File f, Lock l, Queue<String> q, InputStream in, byte[] buf) throws IOException {
        f.delete();                                    // expect: KJCS-X15-DiscardedStatusResult
        l.tryLock();                                   // expect: KJCS-X15-DiscardedStatusResult
        q.offer("x");                                  // expect: KJCS-X15-DiscardedStatusResult
        in.read(buf);                                  // expect: KJCS-X15-DiscardedStatusResult
        boolean deleted = f.delete();
        if (!deleted) {
            throw new IOException("not deleted");
        }
    }

    void catches() {
        try {
            exposed = 1;
        } catch (Error e) {                            // expect: AvoidCatchingGenericException
            exposed = 2;
        }
        try {
            exposed = 1;
        } catch (Throwable t) {                        // expect: AvoidCatchingGenericException
            exposed = 2;
        }
        try {
            exposed = 1;
        } catch (RuntimeException e) {
            exposed = 2;
        }
        try {
            exposed = 1;
        } catch (IllegalStateException ignored) {      // expect: EmptyCatchBlock
        }
    }
}
