/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.selftest;

/** Fixtures for KJCS-001, KJCS-002, KJCS-004, KJCS-006. Each marked line names the rules expected to report on it. */
public class ControlFlow {

    void labels(int[] a) {
        outer:                                        // expect: LabeledStatement
        for (int i = 0; i < a.length; i++) {
            if (a[i] < 0) {
                break outer;
            }
        }
    }

    void oneExit(int[] a) {
        for (int i = 0; i < a.length; i++) {
            if (a[i] < 0) {
                break;
            }
        }
    }

    void twoExits(int[] a) {
        for (int i = 0; i < a.length; i++) {          // expect: KJCS-X01-LoopWithMultipleExits
            if (a[i] < 0) {
                break;
            }
            if (a[i] == 0) {
                continue;
            }
        }
    }

    void nestedLoopsEachWithOneExit(int[][] a) {
        for (int i = 0; i < a.length; i++) {
            for (int j = 0; j < a[i].length; j++) {
                if (a[i][j] < 0) {
                    break;
                }
            }
            if (a[i].length == 0) {
                continue;
            }
        }
    }

    void switchBreaksDoNotCount(int[] a) {
        for (int i = 0; i < a.length; i++) {
            switch (a[i]) {
                case 1:
                    a[i] = 2;
                    break;
                default:
                    a[i] = 0;
                    break;
            }
        }
    }

    int breakOutOfFinally(int[] a) {
        int r = 0;
        for (int i = 0; i < a.length; i++) {
            try {
                r = a[i];
            } finally {
                if (r < 0) {
                    break;                            // expect: KJCS-X02-JumpOutOfFinally
                }
            }
        }
        return r;
    }

    void loopInsideFinallyIsFine(int[] a) {
        try {
            a[0] = 1;
        } finally {
            for (int i = 0; i < a.length; i++) {
                if (a[i] < 0) {
                    break;
                }
            }
        }
    }

    int direct(int n) {
        return n <= 0 ? 0 : direct(n - 1);            // expect: KJCS-X03-DirectRecursion, KJCS-X10-UncheckedIntegerArithmetic
    }

    int thisQualified(int n) {
        return n <= 0 ? 0 : this.thisQualified(n - 1); // expect: KJCS-X03-DirectRecursion, KJCS-X10-UncheckedIntegerArithmetic
    }

    int overloadOfDifferentArity(int n) {
        return overloadOfDifferentArity(n, 0);
    }

    int overloadOfDifferentArity(int n, int acc) {
        return n + acc;                                // expect: KJCS-X10-UncheckedIntegerArithmetic
    }

    static final class Node {
        private Node next;
        private java.util.List<Node> children;
        private java.util.List<Runnable> tasks;

        void walk() {
            for (Node c : children) {
                c.walk();                              // expect: KJCS-X03-DirectRecursion
            }
        }

        static int fact(int n) {
            return n <= 1 ? 1 : Math.multiplyExact(n, Node.fact(Math.subtractExact(n, 1))); // expect: KJCS-X03-DirectRecursion
        }

        void runAll() {
            for (Runnable t : tasks) {
                t.run();                               // interface call: indirect, not reported by PMD
            }
        }

        void last() {
            if (next != null) {
                next.first();                          // different method: not recursion
            }
        }

        void first() {
        }
    }
}
