/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.selftest;

/** Fixtures for the reconfigured KJCS-005 limit (15) and the KJCS-013 logger name. */
public class LimitsAndNames {

    private static final Object LOG = new Object();
    private static final Object logger = new Object();   // expect: FieldNamingConventions

    int atLimit(int a) {
        int r = 0;
        if (a == 0) {
            r = 0;
        }
        if (a == 1) {
            r = 1;
        }
        if (a == 2) {
            r = 2;
        }
        if (a == 3) {
            r = 3;
        }
        if (a == 4) {
            r = 4;
        }
        if (a == 5) {
            r = 5;
        }
        if (a == 6) {
            r = 6;
        }
        if (a == 7) {
            r = 7;
        }
        if (a == 8) {
            r = 8;
        }
        if (a == 9) {
            r = 9;
        }
        if (a == 10) {
            r = 10;
        }
        if (a == 11) {
            r = 11;
        }
        if (a == 12) {
            r = 12;
        }
        if (a == 13) {
            r = 13;
        }
        if (a == 14) {
            r = 14;
        }
        return r;
    }

    int overLimit(int a) {                             // expect: CognitiveComplexity
        int r = 0;
        if (a == 0) {
            r = 0;
        }
        if (a == 1) {
            r = 1;
        }
        if (a == 2) {
            r = 2;
        }
        if (a == 3) {
            r = 3;
        }
        if (a == 4) {
            r = 4;
        }
        if (a == 5) {
            r = 5;
        }
        if (a == 6) {
            r = 6;
        }
        if (a == 7) {
            r = 7;
        }
        if (a == 8) {
            r = 8;
        }
        if (a == 9) {
            r = 9;
        }
        if (a == 10) {
            r = 10;
        }
        if (a == 11) {
            r = 11;
        }
        if (a == 12) {
            r = 12;
        }
        if (a == 13) {
            r = 13;
        }
        if (a == 14) {
            r = 14;
        }
        if (a == 15) {
            r = 15;
        }
        return r;
    }
}
