/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.selftest;

/** Fixtures for KJCS-007, KJCS-010. */
public class LoopsAndLifetime {

    double sum(double[] v) {
        double s = 0;
        for (double x = 0.0; x < 1.0; x += 0.1) {      // expect: KJCS-X04-FloatingPointLoopCounter
            s += x;
        }
        for (float y = 0f; y < 1f; y += 0.1f) {        // expect: KJCS-X04-FloatingPointLoopCounter
            s += y;
        }
        for (int i = 0; i < v.length; i++) {
            s += v[i];
        }
        return s;
    }

    @Override
    protected void finalize() {                        // expect: KJCS-X05-FinalizeOverride
    }

    void finalize(int notTheObjectMethod) {
    }
}
