/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.selftest;

import java.math.BigDecimal;

/** Fixtures for KJCS-014, KJCS-015, KJCS-101. */
public class Numbers {

    private int count;
    private static final int PERIOD_MS = 60 * 1000;

    Numbers(int count) {
        this.count = count;
    }

    int shadow() {
        int count = 3;                                 // expect: KJCS-X09-LocalShadowsField
        return count;
    }

    long arithmetic(int a, int b, long c) {
        int s = a + b;                                 // expect: KJCS-X10-UncheckedIntegerArithmetic
        long p = c * 2;                                // expect: KJCS-X10-UncheckedIntegerArithmetic
        int n = -a;                                    // expect: KJCS-X10-UncheckedIntegerArithmetic
        int m = Math.abs(b);                           // expect: KJCS-X10-UncheckedIntegerArithmetic
        c += a;                                        // expect: KJCS-X10-UncheckedIntegerArithmetic
        int safe = Math.addExact(a, b);
        int negativeLiteral = -1;
        long constant = PERIOD_MS * 2L;
        double notInteger = 1.5 * a;
        String notArithmetic = "n=" + a;
        for (int i = 0; i < a; i += 2) {
            safe++;
        }
        return s + p + n + m + c + safe + negativeLiteral + constant + (long) notInteger + notArithmetic.length(); // expect: KJCS-X10-UncheckedIntegerArithmetic
    }

    boolean floats(double x, float y, Double boxed) {
        boolean a = x == 0.0;                          // expect: KJCS-X11-FloatingPointEquality
        boolean b = y != 1f;                           // expect: KJCS-X11-FloatingPointEquality
        boolean c = Double.compare(x, 0.0) == 0;
        return a && b && c && boxed != null;
    }

    BigDecimal decimals(double d, long l) {
        BigDecimal bad = new BigDecimal(d);            // expect: KJCS-X12-BigDecimalFromDouble
        BigDecimal ok1 = BigDecimal.valueOf(d);
        BigDecimal ok2 = new BigDecimal("0.1");
        BigDecimal ok3 = new BigDecimal(l);
        return bad.add(ok1).add(ok2).add(ok3);
    }
}
