/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.util.zip;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.attribute.PosixFilePermission;
import java.util.Optional;

import org.apache.commons.io.IOUtils;
import org.eclipse.kura.executor.Command;
import org.eclipse.kura.executor.CommandExecutorService;
import org.eclipse.kura.executor.CommandStatus;
import org.eclipse.kura.executor.ExitStatus;
import org.junit.Test;

public class ExtractInADedicatedProcessTest {

    private static final String OUTPUT_FOLDER = "/tmp/kura_dedicated_process_test/out";
    private static final String PROCESS_ERROR_OUTPUT = "Too many files to unzip.";
    private static final int TIMEOUT_EXIT_CODE = 124;

    private CommandExecutorService executorService;
    private Command executedCommand;
    private byte[] archive;
    private InputStream archiveStream;
    private Optional<Exception> exception = Optional.empty();

    @Test
    public void archiveIsExtractedByADedicatedProcess() throws IOException {
        givenArchiveWithASingleFile();
        givenAnExtractionProcessExitingWith(0);

        whenArchiveIsUnzippedIn(OUTPUT_FOLDER);

        thenNoExceptionIsThrown();
        thenTheProcessRunsTheExtractionEntryPoint();
        thenTheProcessExtractsIn(OUTPUT_FOLDER);
    }

    @Test
    public void archiveIsStreamedToTheProcessStandardInput() throws IOException {
        givenArchiveWithMultipleFiles();
        givenAnExtractionProcessExitingWith(0);

        whenArchiveIsUnzippedIn(OUTPUT_FOLDER);

        thenNoExceptionIsThrown();
        thenTheArchiveIsHandedToTheProcessStandardInput();
    }

    @Test
    public void extractionLibrariesAreCopiedWhereTheCommandUserCanReadThem() throws IOException {
        givenArchiveWithASingleFile();
        givenAnExtractionProcessExitingWith(0);

        whenArchiveIsUnzippedIn(OUTPUT_FOLDER);

        thenNoExceptionIsThrown();
        thenTheProcessClassPathIsNotEmpty();
        thenEveryClassPathLibraryIsACopyInTheTemporaryFolder();
        thenEveryClassPathLibraryIsReadableByEveryUser();
    }

    @Test
    public void extractionProcessIsGivenATimeout() throws IOException {
        givenArchiveWithASingleFile();
        givenAnExtractionProcessExitingWith(0);

        whenArchiveIsUnzippedIn(OUTPUT_FOLDER);

        thenNoExceptionIsThrown();
        thenTheProcessIsGivenATimeout();
    }

    @Test
    public void failedExtractionReportsTheProcessErrorOutput() throws IOException {
        givenArchiveWithASingleFile();
        givenAnExtractionProcessFailingWith(PROCESS_ERROR_OUTPUT);

        whenArchiveIsUnzippedIn(OUTPUT_FOLDER);

        thenExceptionIsThrown(IOException.class);
        thenExceptionMessageContains(OUTPUT_FOLDER);
        thenExceptionMessageContains(PROCESS_ERROR_OUTPUT);
    }

    @Test
    public void extractionStoppedByTheWatchdogIsReportedAsATimeout() throws IOException {
        givenArchiveWithASingleFile();
        givenAnExtractionProcessStoppedByTheWatchdog();

        whenArchiveIsUnzippedIn(OUTPUT_FOLDER);

        thenExceptionIsThrown(IOException.class);
        thenExceptionMessageContains("did not complete within");
    }

    @Test
    public void extractionStoppedByTheTimeoutCommandIsReportedAsATimeout() throws IOException {
        givenArchiveWithASingleFile();
        givenAnExtractionProcessExitingWith(TIMEOUT_EXIT_CODE);

        whenArchiveIsUnzippedIn(OUTPUT_FOLDER);

        thenExceptionIsThrown(IOException.class);
        thenExceptionMessageContains("did not complete within");
    }

    private void givenArchiveWithASingleFile() throws IOException {
        this.archive = TestZipArchives.withSingleFile();
        this.archiveStream = new ByteArrayInputStream(this.archive);
    }

    private void givenArchiveWithMultipleFiles() throws IOException {
        this.archive = TestZipArchives.withMultipleFiles();
        this.archiveStream = new ByteArrayInputStream(this.archive);
    }

    private void givenAnExtractionProcessExitingWith(int exitCode) {
        givenAnExtractionProcess(exitCode, false, "");
    }

    private void givenAnExtractionProcessFailingWith(String errorOutput) {
        givenAnExtractionProcess(1, false, errorOutput);
    }

    private void givenAnExtractionProcessStoppedByTheWatchdog() {
        givenAnExtractionProcess(143, true, "");
    }

    private void givenAnExtractionProcess(int exitCode, boolean timedOut, String errorOutput) {
        this.executorService = mock(CommandExecutorService.class);

        when(this.executorService.execute(any(Command.class))).thenAnswer(invocation -> {
            this.executedCommand = invocation.getArgument(0);
            this.executedCommand.getErrorStream().write(errorOutput.getBytes(StandardCharsets.UTF_8));

            CommandStatus status = new CommandStatus(this.executedCommand, new ExtractionExitStatus(exitCode));
            status.setTimedout(timedOut);

            return status;
        });
    }

    private void whenArchiveIsUnzippedIn(String outputFolder) {
        try {
            UnZip.unZip(this.archiveStream, outputFolder, this.executorService);
        } catch (Exception e) {
            this.exception = Optional.of(e);
        }
    }

    private void thenTheProcessRunsTheExtractionEntryPoint() {
        String[] commandLine = this.executedCommand.getCommandLine();

        assertTrue(unquote(commandLine[0]).endsWith(File.separator + "java"));
        assertEquals("-cp", commandLine[1]);
        assertEquals(UnZip.class.getName(), commandLine[3]);
    }

    private void thenTheProcessExtractsIn(String outputFolder) {
        String[] commandLine = this.executedCommand.getCommandLine();

        assertEquals(outputFolder, unquote(commandLine[commandLine.length - 1]));
    }

    private void thenTheArchiveIsHandedToTheProcessStandardInput() throws IOException {
        assertSame(this.archiveStream, this.executedCommand.getInputStream());
        assertArrayEquals(this.archive, IOUtils.toByteArray(this.executedCommand.getInputStream()));
    }

    private void thenTheProcessClassPathIsNotEmpty() {
        assertTrue(processClassPath().length > 0);
    }

    private void thenEveryClassPathLibraryIsACopyInTheTemporaryFolder() {
        Path temporaryFolder = Paths.get(System.getProperty("java.io.tmpdir"));

        for (String entry : processClassPath()) {
            Path library = Paths.get(entry);

            if (Files.isRegularFile(library)) {
                assertTrue(entry + " is not a copy the command user can reach",
                        library.startsWith(temporaryFolder));
            }
        }
    }

    private void thenEveryClassPathLibraryIsReadableByEveryUser() throws IOException {
        for (String entry : processClassPath()) {
            Path library = Paths.get(entry);
            assertTrue(entry + " does not exist", Files.exists(library));

            if (Files.isRegularFile(library)) {
                assertTrue(entry + " is not readable by the command user",
                        Files.getPosixFilePermissions(library).contains(PosixFilePermission.OTHERS_READ));
            }
        }
    }

    private void thenTheProcessIsGivenATimeout() {
        assertTrue("the extraction process must not be allowed to run forever",
                this.executedCommand.getTimeout() > 0);
    }

    private void thenExceptionIsThrown(Class<? extends Exception> classz) {
        if (!this.exception.isPresent()) {
            fail("Exception expected");
        }

        assertEquals(classz, this.exception.get().getClass());
    }

    private void thenExceptionMessageContains(String messageContent) {
        String message = this.exception.get().getMessage();

        assertNotNull(message);
        assertTrue("'" + message + "' does not contain '" + messageContent + "'",
                message.contains(messageContent));
    }

    private void thenNoExceptionIsThrown() {
        assertFalse(this.exception.isPresent());
    }

    private String[] processClassPath() {
        return unquote(this.executedCommand.getCommandLine()[2]).split(File.pathSeparator);
    }

    private static String unquote(String argument) {
        return argument.substring(1, argument.length() - 1).replace("'\\''", "'");
    }

    private static class ExtractionExitStatus implements ExitStatus {

        private final int exitCode;

        ExtractionExitStatus(int exitCode) {
            this.exitCode = exitCode;
        }

        @Override
        public int getExitCode() {
            return this.exitCode;
        }

        @Override
        public boolean isSuccessful() {
            return this.exitCode == 0;
        }
    }
}
