/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.util.zip;

import static org.eclipse.kura.util.zip.TestZipArchives.FILE_CONTENT;
import static org.eclipse.kura.util.zip.TestZipArchives.FILE_NAME;
import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;
import static org.junit.Assume.assumeFalse;

import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.TimeUnit;
import java.util.function.Consumer;

import org.apache.commons.io.FileUtils;
import org.eclipse.kura.executor.Command;
import org.eclipse.kura.executor.CommandExecutorService;
import org.eclipse.kura.executor.CommandStatus;
import org.eclipse.kura.executor.Pid;
import org.eclipse.kura.executor.Signal;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

/**
 * Runs {@link UnZip#unZip(InputStream, String, CommandExecutorService)} end to end: the extraction process is really
 * spawned, with the command line, class path and quoting it builds, through an executor that runs commands in a shell
 * like the privileged one.
 */
public class ExtractInARealProcessTest {

    private static final String WORK_FOLDER = "/tmp/kura_real_process_test/";
    private static final String OUTPUT_FOLDER = WORK_FOLDER + "out";
    private static final String OUTPUT_FOLDER_WITH_SHELL_CHARACTERS = WORK_FOLDER + "it's a $HOME `folder`";

    private byte[] archive;
    private Optional<Exception> exception = Optional.empty();

    @Before
    public void checkAShellIsAvailable() {
        assumeFalse("the extraction process is spawned through a POSIX shell",
                System.getProperty("os.name").toLowerCase().contains("win"));
    }

    @After
    public void clean() throws IOException {
        FileUtils.deleteDirectory(new File(WORK_FOLDER));
    }

    @Test
    public void archiveIsExtractedByTheProcess() throws IOException {
        givenArchiveWithASingleFile();

        whenArchiveIsUnzippedIn(OUTPUT_FOLDER);

        thenNoExceptionIsThrown();
        thenFolderContainsTheArchiveFile(OUTPUT_FOLDER);
    }

    @Test
    public void outputFolderIsPassedVerbatimToTheProcess() throws IOException {
        givenArchiveWithASingleFile();

        whenArchiveIsUnzippedIn(OUTPUT_FOLDER_WITH_SHELL_CHARACTERS);

        thenNoExceptionIsThrown();
        thenFolderContainsTheArchiveFile(OUTPUT_FOLDER_WITH_SHELL_CHARACTERS);
    }

    @Test
    public void failureIsReportedWithTheProcessErrorOutput() throws IOException {
        givenArchiveWithAnEntryOutsideTheTargetFolder();

        whenArchiveIsUnzippedIn(OUTPUT_FOLDER);

        thenExceptionIsThrown();
        thenExceptionMessageContains("File is outside extraction target directory.");
        thenFolderDoesNotExist(OUTPUT_FOLDER);
    }

    private void givenArchiveWithASingleFile() throws IOException {
        this.archive = TestZipArchives.withSingleFile();
    }

    private void givenArchiveWithAnEntryOutsideTheTargetFolder() throws IOException {
        this.archive = TestZipArchives.withEntryOutsideTargetFolder();
    }

    private void whenArchiveIsUnzippedIn(String outputFolder) {
        try {
            UnZip.unZip(new ByteArrayInputStream(this.archive), outputFolder, new ShellExecutorService());
        } catch (Exception e) {
            this.exception = Optional.of(e);
        }
    }

    private void thenNoExceptionIsThrown() {
        this.exception.ifPresent(e -> fail("Unexpected exception: " + e));
    }

    private void thenExceptionIsThrown() {
        assertTrue("Exception expected", this.exception.isPresent());
        assertEquals(IOException.class, this.exception.get().getClass());
    }

    private void thenExceptionMessageContains(String messageContent) {
        String message = this.exception.get().getMessage();
        assertTrue("'" + message + "' does not contain '" + messageContent + "'", message.contains(messageContent));
    }

    private void thenFolderContainsTheArchiveFile(String folder) throws IOException {
        assertArrayEquals(new String[] { FILE_NAME }, new File(folder).list());
        assertEquals(FILE_CONTENT, FileUtils.readFileToString(new File(folder, FILE_NAME), StandardCharsets.UTF_8));
    }

    private void thenFolderDoesNotExist(String folder) {
        assertFalse(new File(folder).exists());
    }

    /**
     * Runs commands with "/bin/sh -c", feeding them the command input stream, like the privileged executor does.
     */
    private static class ShellExecutorService implements CommandExecutorService {

        @Override
        public CommandStatus execute(Command command) {
            try {
                Process process = new ProcessBuilder("/bin/sh", "-c", command.toString()).start();

                Thread input = pump(command.getInputStream(), process.getOutputStream());
                Thread error = pump(process.getErrorStream(), command.getErrorStream());

                boolean completed = process.waitFor(command.getTimeout(), TimeUnit.SECONDS);
                if (!completed) {
                    process.destroyForcibly().waitFor();
                }
                input.join();
                error.join();

                CommandStatus status = new CommandStatus(command, new TestExitStatus(process.exitValue()));
                status.setTimedout(!completed);
                return status;
            } catch (IOException | InterruptedException e) {
                throw new IllegalStateException(e);
            }
        }

        private static Thread pump(InputStream from, OutputStream to) {
            Thread pump = new Thread(() -> {
                try (OutputStream out = to) {
                    from.transferTo(out);
                } catch (IOException e) {
                    // The process exited before reading its whole input
                }
            });
            pump.start();
            return pump;
        }

        @Override
        public void execute(Command command, Consumer<CommandStatus> callback) {
            callback.accept(execute(command));
        }

        @Override
        public boolean stop(Pid pid, Signal signal) {
            throw new UnsupportedOperationException();
        }

        @Override
        public boolean kill(String[] commandLine, Signal signal) {
            throw new UnsupportedOperationException();
        }

        @Override
        public boolean isRunning(Pid pid) {
            throw new UnsupportedOperationException();
        }

        @Override
        public boolean isRunning(String[] commandLine) {
            throw new UnsupportedOperationException();
        }

        @Override
        public Map<String, Pid> getPids(String[] commandLine) {
            throw new UnsupportedOperationException();
        }
    }
}
