/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.util.zip;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

import org.apache.commons.io.FileUtils;

/**
 * Builds the zip archives needed by the zip tests, so that what makes an archive acceptable or not is stated in the
 * test code instead of being hidden inside a binary resource.
 */
final class TestZipArchives {

    static final int MAX_ALLOWED_ENTRIES = 1024;
    static final long MAX_ALLOWED_UNCOMPRESSED_SIZE = 100L * 1024 * 1024;

    static final String FILE_NAME = "file.txt";
    static final String FILE_CONTENT = "This is an awesome text file!\n";
    static final String OVERSIZED_ENTRY_NAME = "tooBigFile";
    static final String ESCAPING_ENTRY_NAME = "../".repeat(20) + "tmp/evil.txt";

    private static final int BUFFER_SIZE = 8192;

    private TestZipArchives() {
        // Do nothing...
    }

    static byte[] withSingleFile() throws IOException {
        return withTextFilesNamed(FILE_NAME);
    }

    static byte[] withMultipleFiles() throws IOException {
        return withTextFilesNamed(FILE_NAME, "file1.txt");
    }

    static byte[] withEntryCount(int entryCount) throws IOException {
        String[] entryNames = new String[entryCount];
        for (int i = 0; i < entryCount; i++) {
            entryNames[i] = "file" + (i + 1) + ".txt";
        }

        return withTextFilesNamed(entryNames);
    }

    static byte[] withUncompressedSize(long uncompressedSize) throws IOException {
        ByteArrayOutputStream archive = new ByteArrayOutputStream();

        try (ZipOutputStream zos = new ZipOutputStream(archive)) {
            zos.putNextEntry(new ZipEntry(OVERSIZED_ENTRY_NAME));

            byte[] buffer = new byte[BUFFER_SIZE];
            long written = 0;
            while (written < uncompressedSize) {
                int chunk = (int) Math.min(BUFFER_SIZE, uncompressedSize - written);
                zos.write(buffer, 0, chunk);
                written += chunk;
            }

            zos.closeEntry();
        }

        return archive.toByteArray();
    }

    static byte[] withEntryOutsideTargetFolder() throws IOException {
        return withTextFilesNamed("good.txt", ESCAPING_ENTRY_NAME);
    }

    static void writeTo(byte[] archive, String filePath) throws IOException {
        FileUtils.writeByteArrayToFile(new File(filePath), archive);
    }

    private static byte[] withTextFilesNamed(String... entryNames) throws IOException {
        ByteArrayOutputStream archive = new ByteArrayOutputStream();

        try (ZipOutputStream zos = new ZipOutputStream(archive)) {
            for (String entryName : entryNames) {
                zos.putNextEntry(new ZipEntry(entryName));
                zos.write(FILE_CONTENT.getBytes("UTF-8"));
                zos.closeEntry();
            }
        }

        return archive.toByteArray();
    }
}
