/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.util.zip;

import org.eclipse.kura.executor.ExitStatus;

/**
 * The exit status of a process, successful when its exit code is 0.
 */
final class TestExitStatus implements ExitStatus {

    private final int exitCode;

    TestExitStatus(int exitCode) {
        this.exitCode = exitCode;
    }

    @Override
    public int getExitCode() {
        return this.exitCode;
    }

    @Override
    public boolean isSuccessful() {
        return this.exitCode == 0;
    }
}
