/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 * Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.net.admin.visitor.linux.util;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;

public class ModemXchangeScriptTest {

    @Rule
    public TemporaryFolder folder = new TemporaryFolder();

    private ModemXchangeScript script;
    private ModemXchangeScript parsedScript;
    private String path;
    private Exception occurredException;

    @Test
    public void writeScriptWritesAllPairs() throws IOException {
        givenScriptWithPairs("AT", "OK", "ATDT*99#", "CONNECT");
        givenPathInExistingDirectory("chat");

        whenWriteScript();

        thenNoExceptionOccurred();
        thenFileContainsLines("OK\tAT", "CONNECT\tATDT*99#");
    }

    @Test
    public void writeScriptInMissingDirectoryReportsFileNotFound() throws IOException {
        givenScriptWithPairs("AT", "OK");
        givenPathInMissingDirectory("chat");

        whenWriteScript();

        thenExceptionOccurred(FileNotFoundException.class);
    }

    @Test
    public void parseFileReadsWrittenPairs() throws Exception {
        givenScriptWithPairs("AT", "OK", "ATDT*99#", "CONNECT");
        givenPathInExistingDirectory("chat");
        givenScriptWritten();

        whenParseFile();

        thenNoExceptionOccurred();
        thenParsedPairsAre("AT", "OK", "ATDT*99#", "CONNECT");
    }

    @Test
    public void parseFileOnUnreadablePathReportsFileNotFound() throws IOException {
        givenPathOfExistingDirectory();

        whenParseFile();

        thenExceptionOccurred(FileNotFoundException.class);
    }

    /*
     * Steps
     */

    private void givenScriptWithPairs(String... sendExpect) {
        this.script = new ModemXchangeScript();
        for (int i = 0; i < sendExpect.length; i += 2) {
            this.script.addmodemXchangePair(new ModemXchangePair(sendExpect[i], sendExpect[i + 1]));
        }
    }

    private void givenPathInExistingDirectory(String name) throws IOException {
        this.path = new File(this.folder.getRoot(), name).getAbsolutePath();
    }

    private void givenPathInMissingDirectory(String name) throws IOException {
        this.path = new File(new File(this.folder.getRoot(), "missing"), name).getAbsolutePath();
    }

    private void givenPathOfExistingDirectory() throws IOException {
        this.path = this.folder.newFolder("directory").getAbsolutePath();
    }

    private void givenScriptWritten() throws Exception {
        this.script.writeScript(this.path);
    }

    private void whenWriteScript() {
        try {
            this.script.writeScript(this.path);
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    private void whenParseFile() {
        try {
            this.parsedScript = ModemXchangeScript.parseFile(this.path);
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    private void thenNoExceptionOccurred() {
        assertNull(this.occurredException);
    }

    private void thenExceptionOccurred(Class<? extends Exception> expectedType) {
        assertNotNull(this.occurredException);
        assertTrue("unexpected exception: " + this.occurredException,
                expectedType.isInstance(this.occurredException));
        assertTrue(this.occurredException.getMessage().contains(this.path));
    }

    private void thenFileContainsLines(String... lines) throws IOException {
        assertEquals(Arrays.asList(lines), Files.readAllLines(new File(this.path).toPath(), StandardCharsets.UTF_8));
    }

    private void thenParsedPairsAre(String... sendExpect) {
        List<String> parsed = new ArrayList<>();
        ModemXchangePair pair = this.parsedScript.getFirstModemXchangePair();
        while (pair != null) {
            parsed.add(pair.getSendString());
            parsed.add(pair.getExpectString());
            pair = this.parsedScript.getNextModemXchangePair();
        }
        assertEquals(Arrays.asList(sendExpect), parsed);
    }
}
