#!/bin/bash

INSTALL_DIR=/opt/eclipse
WD_TMP_FILE=/tmp/watchdog
REFRESH_TIME=5
TIMEOUT_TIME=300
TIMESTAMP=$(date +%Y%m%d%H%M)
LOG=/tmp/kura_uninstall_${TIMESTAMP}.log

##############################################
# UTILITY FUNCTIONS
##############################################
# Run preRemove function and start watchdog if needed
function runPreRemove {
    if [ -f "${WD_TMP_FILE}" ]; then
        WATCHDOG_DEVICE=`cat ${WD_TMP_FILE}`
        preRemove &
        PID=$!
        START=$(date +%s)
        
        while [ -d "/proc/$PID" ]; do
            echo w > ${WATCHDOG_DEVICE}
            DELTA=$(($(date +%s) - $START))
            if [ "$DELTA" -ge "$TIMEOUT_TIME" ]; then
                echo "The installation process is not responding. It'll be stopped."
                kill -9 $PID >> /dev/null 2>&1
            fi
            sleep $REFRESH_TIME
        done
        stopWatchdog
    else
        preRemove &
        PID=$!
        START=$(date +%s)
        
        while [ -d "/proc/$PID" ]; do
            DELTA=$(($(date +%s) - $START))
            if [ "$DELTA" -ge "$TIMEOUT_TIME" ]; then
                echo "The installation process is not responding. It'll be stopped."
                kill -9 $PID >> /dev/null 2>&1
            fi
            sleep $REFRESH_TIME
        done
    fi

    # Remove dnsmasq leases file if it exists and is owned by 'kurad'
    DNSMASQ_LEASES_FILE="/var/lib/dhcp/dnsmasq.leases"
    if [ -f "${DNSMASQ_LEASES_FILE}" ]; then
        FILE_OWNER=$(stat -c '%U' "${DNSMASQ_LEASES_FILE}" 2>/dev/null)
        if [ "${FILE_OWNER}" = "kurad" ]; then
            rm -f "${DNSMASQ_LEASES_FILE}"
            echo "The dnsmasq leases file has been successfully removed."
        fi
    fi
}

# Deactivate watchdog device if possible
function stopWatchdog {
    if [ -n "${WATCHDOG_DEVICE}" ]; then
        echo V > ${WATCHDOG_DEVICE}
    fi
}

function restore_systemd_watchdog() {
    file_to_restore=""

    if [ -f /usr/lib/systemd/system.conf.d/zz-kura-disable-watchdog.conf ]; then
        file_to_restore="/usr/lib/systemd/system.conf.d/zz-kura-disable-watchdog.conf"
    fi
    if [ -f /usr/local/lib/systemd/system.conf.d/zz-kura-disable-watchdog.conf ]; then
        file_to_restore="/usr/local/lib/systemd/system.conf.d/zz-kura-disable-watchdog.conf"
    fi
    if [ -f /etc/systemd/system.conf.d/zz-kura-disable-watchdog.conf ]; then
        file_to_restore="/etc/systemd/system.conf.d/zz-kura-disable-watchdog.conf"
    fi

    if [ ! -z "${file_to_restore}" ]; then
        echo "Restoring systemd watchdog configuration: removing ${file_to_restore}"
        rm "${file_to_restore}"
        systemctl daemon-reload
    fi
}

# Pre-remove script
function preRemove {
    #Remove INIT scripts
    if [ -f /etc/init.d/kura ] ; then
        rm /etc/init.d/kura
        update-rc.d kura remove
    fi
    if [ -f /lib/systemd/system/kura.service ] ; then
        systemctl disable kura
        rm /lib/systemd/system/kura.service
    fi
    if [ -f /etc/init.d/firewall ] ; then
        rm /etc/init.d/firewall
        update-rc.d firewall remove
    fi
    if [ -f /lib/systemd/system/firewall.service ] ; then
        systemctl disable firewall
        rm /lib/systemd/system/firewall.service
    fi

    rm -f  /var/log/kura*.log
    rm -f  /var/log/kura*.gz
    rm -rf /tmp/.kura
    rm -rf /tmp/kura

    restore_systemd_watchdog

    if [ -d "${INSTALL_DIR}/kura" ] ; then
      ${INSTALL_DIR}/kura/.data/manage_kura_users.sh -u
      PARENT=`readlink -f ${INSTALL_DIR}/kura`
      rm -rf ${INSTALL_DIR}/kura
      rm -rf $PARENT
    fi
}
##############################################
# END UTILITY FUNCTIONS
##############################################

##############################################
# PRE-REMOVE SCRIPT
##############################################
echo ""
echo "Uninstalling KURA..."

PIDS=`pgrep java`

#Kill JVM and monit for installation
if [ -f "/var/run/kura.pid" ] ; then
  KURA_PID=`cat /var/run/kura.pid`

  for pid in "${PIDS[@]}"
  do
    if [ "$KURA_PID" == "$pid" ] ; then
      `kill $pid` >> "$LOG" 2>&1
    fi
  done
fi

runPreRemove >> "$LOG" 2>&1

mkdir -p /opt/eclipse/kura/log/
mv "$LOG" /opt/eclipse/kura/log/

echo ""
echo "Uninstalling KURA... Done!"
##############################################
# END PRE-REMOVE SCRIPT
##############################################
