#
#  Copyright (c) 2025 Eurotech and/or its affiliates and others
#
#  This program and the accompanying materials are made
#  available under the terms of the Eclipse Public License 2.0
#  which is available at https://www.eclipse.org/legal/epl-2.0/
#
#  SPDX-License-Identifier: EPL-2.0
#
#  Contributors:
#   Eurotech
#   Areti
#

kura.version=6.0.0-SNAPSHOT
#project modules
com.codeminders.hidapi.version=2.0.0-SNAPSHOT
org.eclipse.soda.dk.comm.version=2.0.0-SNAPSHOT
org.usb4java.version=2.0.0-SNAPSHOT
usb4java-javax.version=2.0.0-SNAPSHOT
com.gwt.user.version=2.0.0-SNAPSHOT
jdk.dio.version=2.0.0-SNAPSHOT
org.eclipse.kura.camel.sun.misc.version=2.0.0-SNAPSHOT
org.eclipse.kura.sun.misc.version=2.0.0-SNAPSHOT

org.moka7.version=2.0.0-SNAPSHOT

org.apache.activemq.artemis.version=3.0.0-SNAPSHOT
org.apache.activemq.artemis.upstream.version=2.6.4
org.xerial.sqlite-jdbc.version=3.42.0.0

#target platform commons versions
org.eclipse.paho.client.mqttv3.version=1.2.1
javax.usb.api.version=1.0.2
javax.usb.common.version=1.0.2
javax.usb.linux.version=1.0.3
org.apache.commons.commons-net.version=3.8.0
com.h2database.h2.version=2.1.214
slf4j.api.version=1.7.36
jcl.over.slf4j.version=1.7.36
log4j.version=2.23.1
jul.to.slf4j.version=1.7.36
org.apache.commons.lang3.version=3.12.0
com.google.protobuf.version=4.30.2
org.hamcrest.version=1.1.0.v20090501071000
org.hamcrest.core.version=1.3.0.v201303031735
org.hamcrest.integration.version=1.1.0.v201303031500
org.junit.version=4.12.0.v201504281640
commons-fileupload.version=2.0.0-M2
org.apache.commons.commons-io.version=2.18.0
commons-exec.version=1.3
commons-csv.version=1.4
org.apache.camel.camel-amqp.version=2.25.3
org.apache.camel.camel-core.version=2.25.3
org.apache.camel.camel-core-osgi.version=2.25.3
org.apache.camel.camel-jms.version=2.25.3
org.apache.camel.camel-script.version=2.25.3
org.apache.camel.camel-stream.version=2.25.3
apache-qpid-jms-client.version=0.45.0
apache-qpid-proton-j.version=0.33.2
mockito-core.version=4.8.1
byte-buddy.version=1.12.18
objenesis.version=3.3
osgi.annotation.version=8.1.0
com.google.gson.version=2.9.0
bluez-dbus-osgi.version=0.1.4

commons-beanutils.version=1.9.3
commons-collections.version=3.2.2
org.apache.geronimo.specs.json.version=1.0-alpha-1
org.apache.geronimo.specs.jms.version=1.0-alpha-2
org.apache.geronimo.specs.jta.version=1.1.1
guava.version=32.1.1-jre
failureaccess.version=1.0.1
io.netty.version=4.1.118.Final
org.jboss.logging.version=3.3.2.Final
spring.version=4.3.20.RELEASE_1

jakarta.activation-api.version=2.1.2
jakarta.annotation-api.version=2.1.1
jakarta.inject-api.version=2.0.1
jakarta.validation-api.version=3.0.2
jakarta.xml.bind-api.version=4.0.2
jakarta.xml.ws-api.version=4.0.2
jakarta.xml.soap-api.version=3.0.2
jakarta.ws.rs-api.version=3.1.0
jaxb-osgi.version=4.0.2
osgi-resource-locator.version=1.0.3
javassist.version=3.30.2-GA
mimepull.version=1.10.0

jakarta.activation-api.javax.version=1.2.2
jakarta.xml.bind-api.javax.version=2.3.3
jaxb-osgi.javax.version=2.3.9

org.bouncycastle.version=1.78.1

com.eurotech.gpsd4java.version=1.0.0
libsocket-can-osgi.version=2.0.0-SNAPSHOT

org.apache.servicemix.bundles.c3p0.version=0.9.5.5_1
hikaricp.version=2.7.9
quartz.version=2.3.2

org.apache.felix.dependencymanager.version=3.0.0
org.apache.felix.deploymentadmin.version=0.9.5
org.apache.felix.gogo.command.version=1.1.2

org.apache.felix.http.servlet-api.version=3.0.0
org.apache.felix.http.jetty12.version=1.0.2
org.apache.felix.http.bridge.version=5.1.8
org.apache.felix.http.proxy.version=4.0.0
org.apache.felix.http.wrappers.version=1.1.2
org.apache.felix.gogo.runtime.version=1.1.6
org.apache.felix.gogo.shell.version=1.1.4
org.apache.felix.scr.version=2.2.12

org.eclipse.equinox.cm.version=1.6.100
org.eclipse.equinox.common.version=3.19.100
org.eclipse.equinox.console.version=1.4.800
org.eclipse.equinox.event.version=1.7.100
org.eclipse.equinox.io.version=1.1.300
org.eclipse.equinox.launcher.version=1.6.900
org.eclipse.equinox.metatype.version=1.6.600
org.eclipse.equinox.preferences.version=3.11.100
org.eclipse.equinox.registry.version=3.12.100
org.eclipse.equinox.util.version=1.1.300
org.eclipse.equinox.wireadmin.version=1.0.800
org.eclipse.core.runtime.version=3.31.100
org.eclipse.core.jobs.version=3.15.400
org.eclipse.core.contenttype.version=3.9.500
org.eclipse.equinox.app.version=1.7.200

org.eclipse.jetty.version=12.0.14

org.eclipse.osgi.util.version=3.7.300
org.eclipse.osgi.version=3.21.0

org.eclipse.osgi-technology.rest.version=1.2.3

org.osgi.service.http.whiteboard.version=1.1.1
org.osgi.service.jakartars.version=2.0.0
org.osgi.service.servlet.version=2.0.0

org.osgi.service.cm.version=1.6.1
org.osgi.service.component.version=1.5.1
org.osgi.service.coordinator.version=1.0.2
org.osgi.service.device.version=1.1.1
org.osgi.service.event.version=1.4.1
org.osgi.service.log.stream.version=1.0.0
org.osgi.service.metatype.version=1.4.1
org.osgi.service.prefs.version=1.1.2
org.osgi.service.provisioning.version=1.2.0
org.osgi.service.upnp.version=1.2.1
org.osgi.service.useradmin.version=1.1.1
org.osgi.service.wireadmin.version=1.0.2
org.osgi.util.function.version=1.2.0
org.osgi.util.measurement.version=1.0.2
org.osgi.util.position.version=1.0.1
org.osgi.util.promise.version=1.3.0
org.osgi.util.pushstream.version=1.1.0
org.osgi.util.xml.version=1.0.2

org.knowhowlab.osgi.monitoradmin.version=1.0.3
org.apache.felix.useradmin.version=1.0.4.k1
org.apache.aries.spifly.dynamic.bundle.version=1.3.7
org.ow2.asm.version=9.7.1
hk2.version=3.1.1
jersey.version=3.1.9

com.eclipsesource.minimal-json.version=0.9.5

#test dependencies versions
moquette-broker.version=1.0.0-SNAPSHOT
log4j2-api-config.version=2.0.0-SNAPSHOT
org.jvnet.mimepull.version=1.10.0
io.dropwizard.metrics.version=3.2.2


org.osgi.service.component.annotations.version=1.5.1
org.osgi.service.metatype.annotations.version=1.4.1
kura.version=6.0.0-SNAPSHOT
org.eclipse.kura.api.version=3.0.0-SNAPSHOT
org.eclipse.kura.asset.provider.version=3.0.0-SNAPSHOT
org.eclipse.kura.asset.cloudlet.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.asset.helper.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.broker.artemis.core.version=2.0.0-SNAPSHOT
org.eclipse.kura.broker.artemis.simple.mqtt.version=2.0.0-SNAPSHOT
org.eclipse.kura.broker.artemis.xml.version=2.0.0-SNAPSHOT
org.eclipse.kura.core.version=2.0.0-SNAPSHOT
org.eclipse.kura.core.system.version=2.0.0-SNAPSHOT
org.eclipse.kura.core.certificates.version=2.0.0-SNAPSHOT
org.eclipse.kura.core.keystore.version=2.0.0-SNAPSHOT
org.eclipse.kura.cloud.base.provider.version=1.0.0-SNAPSHOT
org.eclipse.kura.core.cloud.command.version=1.0.0-SNAPSHOT
org.eclipse.kura.core.cloud.factory.version=2.0.0-SNAPSHOT
org.eclipse.kura.core.comm.version=2.0.0-SNAPSHOT
org.eclipse.kura.core.configuration.version=3.0.0-SNAPSHOT
org.eclipse.kura.core.crypto.version=2.0.0-SNAPSHOT
org.eclipse.kura.deployment.agent.version=2.0.0-SNAPSHOT
org.eclipse.kura.core.deployment.version=2.0.0-SNAPSHOT
org.eclipse.kura.core.identity.version=2.0.0-SNAPSHOT
org.eclipse.kura.core.inventory.version=2.0.0-SNAPSHOT
org.eclipse.kura.camel.version=2.0.0-SNAPSHOT
org.eclipse.kura.camel.cloud.factory.version=2.0.0-SNAPSHOT
org.eclipse.kura.camel.xml.version=2.0.0-SNAPSHOT
org.eclipse.kura.core.net.version=2.0.0-SNAPSHOT
org.eclipse.kura.core.status.version=2.0.0-SNAPSHOT
org.eclipse.kura.emulator.version=2.0.0-SNAPSHOT
org.eclipse.kura.emulator.clock.version=2.0.0-SNAPSHOT
org.eclipse.kura.emulator.gpio.version=2.0.0-SNAPSHOT
org.eclipse.kura.emulator.net.version=2.0.0-SNAPSHOT
org.eclipse.kura.emulator.position.version=2.0.0-SNAPSHOT
org.eclipse.kura.emulator.usb.version=2.0.0-SNAPSHOT
org.eclipse.kura.emulator.watchdog.version=2.0.0-SNAPSHOT
org.eclipse.kura.localization.version=2.0.0-SNAPSHOT
org.eclipse.kura.localization.resources.version=2.0.0-SNAPSHOT
org.eclipse.kura.driver.helper.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.driver.opcua.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.driver.block.version=2.0.0-SNAPSHOT
org.eclipse.kura.driver.s7plc.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.driver.ble.sensortag.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.driver.eddystone.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.driver.ibeacon.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.driver.gpio.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.linux.clock.version=2.0.0-SNAPSHOT
org.eclipse.kura.ble.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.ble.ibeacon.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.ble.eddystone.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.linux.command.version=2.0.0-SNAPSHOT
org.eclipse.kura.linux.net.version=3.0.0-SNAPSHOT
org.eclipse.kura.linux.systemd.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.linux.gpio.version=2.0.0-SNAPSHOT
org.eclipse.kura.linux.position.version=2.0.0-SNAPSHOT
org.eclipse.kura.linux.usb.version=2.0.0-SNAPSHOT
org.eclipse.kura.linux.watchdog.version=2.0.0-SNAPSHOT
org.eclipse.kura.nm.version=2.0.0-SNAPSHOT
org.eclipse.kura.net.configuration.version=2.0.0-SNAPSHOT
org.eclipse.kura.net.admin.firewall.version=2.0.0-SNAPSHOT
org.eclipse.kura.util.version=2.0.0-SNAPSHOT
org.eclipse.kura.protocol.can.version=4.0.0-SNAPSHOT
org.eclipse.kura.protocol.modbus.version=3.0.0-SNAPSHOT
org.eclipse.kura.demo.heater.version=2.0.0-SNAPSHOT
org.eclipse.kura.demo.modbus.version=3.0.0-SNAPSHOT
org.eclipse.kura.example.project.version=2.0.0-SNAPSHOT
org.eclipse.kura.example.publisher.version=2.0.0-SNAPSHOT
org.eclipse.kura.example.serial.publisher.version=2.0.0-SNAPSHOT
org.eclipse.kura.example.ble.tisensortag.version=2.0.0-SNAPSHOT
org.eclipse.kura.example.ble.tisensortag.dbus.version=2.0.0-SNAPSHOT
org.eclipse.kura.example.beacon.version=2.0.0-SNAPSHOT
org.eclipse.kura.example.beacon.scanner.version=2.0.0-SNAPSHOT
org.eclipse.kura.example.ibeacon.advertiser.version=2.0.0-SNAPSHOT
org.eclipse.kura.example.ibeacon.scanner.version=2.0.0-SNAPSHOT
org.eclipse.kura.example.eddystone.advertiser.version=2.0.0-SNAPSHOT
org.eclipse.kura.example.eddystone.scanner.version=2.0.0-SNAPSHOT
org.eclipse.kura.example.camel.aggregation.version=2.0.0-SNAPSHOT
org.eclipse.kura.example.camel.publisher.version=2.0.0-SNAPSHOT
org.eclipse.kura.example.camel.quickstart.version=2.0.0-SNAPSHOT
org.eclipse.kura.example.can.version=2.0.0-SNAPSHOT
org.eclipse.kura.example.gpio.version=2.0.0-SNAPSHOT
org.eclipse.kura.example.driver.sensehat.version=2.0.0-SNAPSHOT
org.eclipse.kura.example.identity.configuration.extension.version=2.0.0-SNAPSHOT
org.eclipse.kura.wire.devel.component.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.raspberrypi.sensehat.version=2.0.0-SNAPSHOT
org.eclipse.kura.raspberrypi.sensehat.example.version=2.0.0-SNAPSHOT
org.eclipse.kura.example.wire.math.singleport.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.example.wire.math.multiport.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.example.tamper.detection.version=2.0.0-SNAPSHOT
org.eclipse.kura.web2.version=3.0.0-SNAPSHOT
org.eclipse.kura.wire.camel.version=2.0.0-SNAPSHOT
org.eclipse.kura.wire.component.provider.version=3.0.0-SNAPSHOT
org.eclipse.kura.wire.h2db.component.provider.version=3.0.0-SNAPSHOT
org.eclipse.kura.wire.db.component.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.wire.script.filter.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.wire.helper.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.wire.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.rest.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.rest.asset.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.hook.file.move.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.misc.cloudcat.version=2.0.0-SNAPSHOT
org.eclipse.kura.json.marshaller.unmarshaller.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.xml.marshaller.unmarshaller.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.wire.component.join.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.cloudconnection.eclipseiot.mqtt.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.http.server.manager.version=2.0.0-SNAPSHOT
org.eclipse.kura.cloudconnection.raw.mqtt.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.web2.ext.version=2.0.0-SNAPSHOT
org.eclipse.kura.useradmin.store.version=2.0.0-SNAPSHOT
org.eclipse.kura.network.threat.manager.version=2.0.0-SNAPSHOT
org.eclipse.kura.core.tamper.detection.version=2.0.0-SNAPSHOT
org.eclipse.kura.log.filesystem.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.rest.cloudconnection.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.rest.configuration.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.rest.network.configuration.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.rest.inventory.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.rest.command.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.rest.packages.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.rest.position.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.rest.security.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.rest.identity.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.rest.service.listing.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.rest.system.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.rest.keystore.provider.version=1.0.0-SNAPSHOT
org.eclipse.kura.request.handler.jaxrs.version=2.0.0-SNAPSHOT
org.eclipse.kura.rest.wire.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.wire.ai.component.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.ai.triton.server.version=2.0.0-SNAPSHOT
org.eclipse.kura.container.orchestration.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.container.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.configuration.change.manager.version=2.0.0-SNAPSHOT
org.eclipse.kura.event.publisher.version=2.0.0-SNAPSHOT
org.eclipse.kura.db.sqlite.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.db.h2db.provider.version=1.0.0-SNAPSHOT
org.eclipse.kura.rest.network.status.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.wire.script.tools.version=2.0.0-SNAPSHOT
org.eclipse.kura.cloudconnection.sparkplug.mqtt.provider.version=2.0.0-SNAPSHOT
org.eclipse.kura.cloudconnection.kapua.mqtt.provider.version=1.0.0-SNAPSHOT

## features versions
org.eclipse.kura.driver.opcua.version=2.0.0-SNAPSHOT
org.eclipse.kura.driver.s7plc.version=2.0.0-SNAPSHOT
org.eclipse.kura.driver.ble.sensortag.version=2.0.0-SNAPSHOT
org.eclipse.kura.driver.eddystone.version=2.0.0-SNAPSHOT
org.eclipse.kura.driver.ibeacon.version=2.0.0-SNAPSHOT
org.eclipse.kura.driver.gpio.version=2.0.0-SNAPSHOT
org.eclipse.kura.driver.ble.xdk.version=2.0.0-SNAPSHOT
org.eclipse.kura.wire.script.filter.version=2.0.0-SNAPSHOT
org.eclipse.kura.wire.script.tools.feature.version=2.0.0-SNAPSHOT
org.eclipse.kura.db.sqlite.feature.version=2.0.0-SNAPSHOT
org.eclipse.kura.cloudconnection.sparkplug.mqtt.provider.feature.version=2.0.0-SNAPSHOT
org.eclipse.kura.cloudconnection.raw.mqtt.provider.feature.version=2.0.0-SNAPSHOT
