/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 * Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.driver.block.test;

import static org.junit.Assert.assertEquals;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyInt;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.eclipse.kura.driver.binary.BinaryData;
import org.eclipse.kura.driver.binary.Buffer;
import org.eclipse.kura.driver.binary.TypeUtil;
import org.eclipse.kura.driver.binary.adapter.ToBoolean;
import org.eclipse.kura.type.DataType;
import org.eclipse.kura.type.DoubleValue;
import org.eclipse.kura.type.TypedValue;
import org.junit.Test;

public class ConvertNumberToBooleanTest {

    private List<Boolean> results;

    /*
     * Scenarios
     */

    @Test
    public void positiveZeroIsFalse() {
        whenConvertedByAllConverters(0.0);

        thenAllConvertersReturn(false);
    }

    @Test
    public void negativeZeroIsFalse() {
        whenConvertedByAllConverters(-0.0);

        thenAllConvertersReturn(false);
    }

    @Test
    public void positiveValueIsTrue() {
        whenConvertedByAllConverters(2.0);

        thenAllConvertersReturn(true);
    }

    @Test
    public void negativeValueIsTrue() {
        whenConvertedByAllConverters(-3.5);

        thenAllConvertersReturn(true);
    }

    @Test
    public void smallestPositiveValueIsTrue() {
        whenConvertedByAllConverters(Double.MIN_VALUE);

        thenAllConvertersReturn(true);
    }

    @Test
    public void infinityIsTrue() {
        whenConvertedByAllConverters(Double.NEGATIVE_INFINITY);

        thenAllConvertersReturn(true);
    }

    @Test
    public void notANumberIsTrue() {
        whenConvertedByAllConverters(Double.NaN);

        thenAllConvertersReturn(true);
    }

    @Test
    public void convertsConcreteNumberTypesToBoolean() {
        whenConcreteNumbersAreConvertedToTypedBoolean((short) 0, 5, 7L, 0.0f, 2.5);

        thenResultsAre(false, true, true, false, true);
    }

    /*
     * Steps
     */

    private void whenConvertedByAllConverters(double value) {
        this.results = Arrays.asList(convertToTypedBoolean(value), convertFromTypedValue(value),
                convertWithToBoolean(value));
    }

    private void whenConcreteNumbersAreConvertedToTypedBoolean(Number... values) {
        this.results = new ArrayList<>();
        for (final Number value : values) {
            this.results.add(convertToTypedBoolean(value));
        }
    }

    private void thenResultsAre(Boolean... expected) {
        assertEquals(Arrays.asList(expected), this.results);
    }

    private void thenAllConvertersReturn(boolean expected) {
        assertEquals(Arrays.asList(expected, expected, expected), this.results);
    }

    /*
     * Utilities
     */

    @SuppressWarnings("unchecked")
    private static boolean convertToTypedBoolean(double value) {
        final Function<Number, TypedValue<?>> converter = TypeUtil.toTypedValue(Number.class, DataType.BOOLEAN);
        return (Boolean) converter.apply(value).getValue();
    }

    @SuppressWarnings("unchecked")
    private static boolean convertToTypedBoolean(Number value) {
        final Function<Number, TypedValue<?>> converter = (Function<Number, TypedValue<?>>) (Function<?, ?>) TypeUtil
                .toTypedValue(value.getClass(), DataType.BOOLEAN);
        return (Boolean) converter.apply(value).getValue();
    }

    private static boolean convertFromTypedValue(double value) {
        final Function<TypedValue<?>, Boolean> converter = TypeUtil.fromTypedValue(Boolean.class, DataType.DOUBLE);
        return converter.apply(new DoubleValue(value));
    }

    @SuppressWarnings("unchecked")
    private static boolean convertWithToBoolean(double value) {
        final BinaryData<Double> wrapped = mock(BinaryData.class);
        when(wrapped.read(any(Buffer.class), anyInt())).thenReturn(value);
        return new ToBoolean(wrapped).read(mock(Buffer.class), 0);
    }
}
