<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2025 Eurotech and/or its affiliates and others
  
    This program and the accompanying materials are made
    available under the terms of the Eclipse Public License 2.0
    which is available at https://www.eclipse.org/legal/epl-2.0/
 
    SPDX-License-Identifier: EPL-2.0
 
    Contributors:
     Eurotech
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.eclipse.kura</groupId>
    <artifactId>bom-equinox</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>BOM for the Equinox dependencies</name>

    <properties>
        <org.apache.felix.gogo.command.version>1.1.2</org.apache.felix.gogo.command.version>
        <org.apache.felix.gogo.runtime.version>1.1.6</org.apache.felix.gogo.runtime.version>
        <org.apache.felix.gogo.shell.version>1.1.4</org.apache.felix.gogo.shell.version>
        <org.apache.felix.scr.version>2.2.12</org.apache.felix.scr.version>
        <org.eclipse.core.contenttype.version>3.9.500</org.eclipse.core.contenttype.version>
        <org.eclipse.core.jobs.version>3.15.400</org.eclipse.core.jobs.version>
        <org.eclipse.core.runtime.version>3.31.100</org.eclipse.core.runtime.version>
        <org.eclipse.equinox.app.version>1.7.200</org.eclipse.equinox.app.version>
        <org.eclipse.equinox.cm.version>1.6.100</org.eclipse.equinox.cm.version>
        <org.eclipse.equinox.common.version>3.19.100</org.eclipse.equinox.common.version>
        <org.eclipse.equinox.console.version>1.4.800</org.eclipse.equinox.console.version>
        <org.eclipse.equinox.event.version>1.7.100</org.eclipse.equinox.event.version>
        <org.eclipse.equinox.io.version>1.1.300</org.eclipse.equinox.io.version>
        <org.eclipse.equinox.launcher.version>1.6.900</org.eclipse.equinox.launcher.version>
        <org.eclipse.equinox.metatype.version>1.6.600</org.eclipse.equinox.metatype.version>
        <org.eclipse.equinox.preferences.version>3.11.100</org.eclipse.equinox.preferences.version>
        <org.eclipse.equinox.registry.version>3.12.100</org.eclipse.equinox.registry.version>
        <org.eclipse.equinox.util.version>1.1.300</org.eclipse.equinox.util.version>
        <org.eclipse.equinox.wireadmin.version>1.0.800</org.eclipse.equinox.wireadmin.version>
        <org.eclipse.osgi.util.version>3.7.300</org.eclipse.osgi.util.version>
        <org.eclipse.osgi.version>3.21.0</org.eclipse.osgi.version>
        <org.osgi.service.cm.version>1.6.1</org.osgi.service.cm.version>
        <org.osgi.service.component.version>1.5.1</org.osgi.service.component.version>
        <org.osgi.service.coordinator.version>1.0.2</org.osgi.service.coordinator.version>
        <org.osgi.service.device.version>1.1.1</org.osgi.service.device.version>
        <org.osgi.service.event.version>1.4.1</org.osgi.service.event.version>
        <org.osgi.service.log.stream.version>1.0.0</org.osgi.service.log.stream.version>
        <org.osgi.service.metatype.version>1.4.1</org.osgi.service.metatype.version>
        <org.osgi.service.prefs.version>1.1.2</org.osgi.service.prefs.version>
        <org.osgi.service.provisioning.version>1.2.0</org.osgi.service.provisioning.version>
        <org.osgi.service.upnp.version>1.2.1</org.osgi.service.upnp.version>
        <org.osgi.service.useradmin.version>1.1.1</org.osgi.service.useradmin.version>
        <org.osgi.service.wireadmin.version>1.0.2</org.osgi.service.wireadmin.version>
        <org.osgi.util.function.version>1.2.0</org.osgi.util.function.version>
        <org.osgi.util.measurement.version>1.0.2</org.osgi.util.measurement.version>
        <org.osgi.util.position.version>1.0.1</org.osgi.util.position.version>
        <org.osgi.util.promise.version>1.3.0</org.osgi.util.promise.version>
        <org.osgi.util.pushstream.version>1.1.0</org.osgi.util.pushstream.version>
        <org.osgi.util.xml.version>1.0.2</org.osgi.util.xml.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.osgi</groupId>
                <artifactId>org.osgi.service.cm</artifactId>
                <version>${org.osgi.service.cm.version}</version>
            </dependency>
            <dependency>
                <groupId>org.osgi</groupId>
                <artifactId>org.osgi.service.component</artifactId>
                <version>${org.osgi.service.component.version}</version>
            </dependency>
            <dependency>
                <groupId>org.osgi</groupId>
                <artifactId>org.osgi.service.coordinator</artifactId>
                <version>${org.osgi.service.coordinator.version}</version>
            </dependency>
            <dependency>
                <groupId>org.osgi</groupId>
                <artifactId>org.osgi.service.device</artifactId>
                <version>${org.osgi.service.device.version}</version>
            </dependency>
            <dependency>
                <groupId>org.osgi</groupId>
                <artifactId>org.osgi.service.event</artifactId>
                <version>${org.osgi.service.event.version}</version>
            </dependency>
            <dependency>
                <groupId>org.osgi</groupId>
                <artifactId>org.osgi.service.log.stream</artifactId>
                <version>${org.osgi.service.log.stream.version}</version>
            </dependency>
            <dependency>
                <groupId>org.osgi</groupId>
                <artifactId>org.osgi.service.metatype</artifactId>
                <version>${org.osgi.service.metatype.version}</version>
            </dependency>
            <dependency>
                <groupId>org.osgi</groupId>
                <artifactId>org.osgi.service.prefs</artifactId>
                <version>${org.osgi.service.prefs.version}</version>
            </dependency>
            <dependency>
                <groupId>org.osgi</groupId>
                <artifactId>org.osgi.service.provisioning</artifactId>
                <version>${org.osgi.service.provisioning.version}</version>
            </dependency>
            <dependency>
                <groupId>org.osgi</groupId>
                <artifactId>org.osgi.service.upnp</artifactId>
                <version>${org.osgi.service.upnp.version}</version>
            </dependency>
            <dependency>
                <groupId>org.osgi</groupId>
                <artifactId>org.osgi.service.useradmin</artifactId>
                <version>${org.osgi.service.useradmin.version}</version>
            </dependency>
            <dependency>
                <groupId>org.osgi</groupId>
                <artifactId>org.osgi.service.wireadmin</artifactId>
                <version>${org.osgi.service.wireadmin.version}</version>
            </dependency>
            <dependency>
                <groupId>org.osgi</groupId>
                <artifactId>org.osgi.util.function</artifactId>
                <version>${org.osgi.util.function.version}</version>
            </dependency>
            <dependency>
                <groupId>org.osgi</groupId>
                <artifactId>org.osgi.util.measurement</artifactId>
                <version>${org.osgi.util.measurement.version}</version>
            </dependency>
            <dependency>
                <groupId>org.osgi</groupId>
                <artifactId>org.osgi.util.position</artifactId>
                <version>${org.osgi.util.position.version}</version>
            </dependency>
            <dependency>
                <groupId>org.osgi</groupId>
                <artifactId>org.osgi.util.promise</artifactId>
                <version>${org.osgi.util.promise.version}</version>
            </dependency>
            <dependency>
                <groupId>org.osgi</groupId>
                <artifactId>org.osgi.util.pushstream</artifactId>
                <version>${org.osgi.util.pushstream.version}</version>
            </dependency>
            <dependency>
                <groupId>org.osgi</groupId>
                <artifactId>org.osgi.util.xml</artifactId>
                <version>${org.osgi.util.xml.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.platform</groupId>
                <artifactId>org.eclipse.equinox.cm</artifactId>
                <version>${org.eclipse.equinox.cm.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.platform</groupId>
                <artifactId>org.eclipse.equinox.common</artifactId>
                <version>${org.eclipse.equinox.common.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.platform</groupId>
                <artifactId>org.eclipse.equinox.console</artifactId>
                <version>${org.eclipse.equinox.console.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.platform</groupId>
                <artifactId>org.eclipse.equinox.registry</artifactId>
                <version>${org.eclipse.equinox.registry.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.platform</groupId>
                <artifactId>org.eclipse.equinox.event</artifactId>
                <version>${org.eclipse.equinox.event.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.platform</groupId>
                <artifactId>org.eclipse.equinox.io</artifactId>
                <version>${org.eclipse.equinox.io.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.platform</groupId>
                <artifactId>org.eclipse.equinox.metatype</artifactId>
                <version>${org.eclipse.equinox.metatype.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.platform</groupId>
                <artifactId>org.eclipse.equinox.launcher</artifactId>
                <version>${org.eclipse.equinox.launcher.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.platform</groupId>
                <artifactId>org.eclipse.equinox.util</artifactId>
                <version>${org.eclipse.equinox.util.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.platform</groupId>
                <artifactId>org.eclipse.equinox.wireadmin</artifactId>
                <version>${org.eclipse.equinox.wireadmin.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.felix</groupId>
                <artifactId>org.apache.felix.scr</artifactId>
                <version>${org.apache.felix.scr.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.platform</groupId>
                <artifactId>org.eclipse.core.runtime</artifactId>
                <version>${org.eclipse.core.runtime.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.platform</groupId>
                <artifactId>org.eclipse.core.jobs</artifactId>
                <version>${org.eclipse.core.jobs.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.platform</groupId>
                <artifactId>org.eclipse.equinox.preferences</artifactId>
                <version>${org.eclipse.equinox.preferences.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.platform</groupId>
                <artifactId>org.eclipse.core.contenttype</artifactId>
                <version>${org.eclipse.core.contenttype.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.platform</groupId>
                <artifactId>org.eclipse.equinox.app</artifactId>
                <version>${org.eclipse.equinox.app.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.platform</groupId>
                <artifactId>org.eclipse.osgi</artifactId>
                <version>${org.eclipse.osgi.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.platform</groupId>
                <artifactId>org.eclipse.osgi.util</artifactId>
                <version>${org.eclipse.osgi.util.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.felix</groupId>
                <artifactId>org.apache.felix.gogo.command</artifactId>
                <version>${org.apache.felix.gogo.command.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.felix</groupId>
                <artifactId>org.apache.felix.gogo.runtime</artifactId>
                <version>${org.apache.felix.gogo.runtime.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.felix</groupId>
                <artifactId>org.apache.felix.gogo.shell</artifactId>
                <version>${org.apache.felix.gogo.shell.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.service.cm</artifactId>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.service.component</artifactId>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.service.coordinator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.service.device</artifactId>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.service.event</artifactId>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.service.log.stream</artifactId>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.service.metatype</artifactId>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.service.prefs</artifactId>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.service.provisioning</artifactId>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.service.upnp</artifactId>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.service.useradmin</artifactId>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.service.wireadmin</artifactId>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.util.function</artifactId>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.util.measurement</artifactId>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.util.position</artifactId>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.util.promise</artifactId>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.util.pushstream</artifactId>
        </dependency>
        <dependency>
            <groupId>org.osgi</groupId>
            <artifactId>org.osgi.util.xml</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.platform</groupId>
            <artifactId>org.eclipse.equinox.cm</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.platform</groupId>
            <artifactId>org.eclipse.equinox.common</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.platform</groupId>
            <artifactId>org.eclipse.equinox.console</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.platform</groupId>
            <artifactId>org.eclipse.equinox.registry</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.platform</groupId>
            <artifactId>org.eclipse.equinox.event</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.platform</groupId>
            <artifactId>org.eclipse.equinox.io</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.platform</groupId>
            <artifactId>org.eclipse.equinox.metatype</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.platform</groupId>
            <artifactId>org.eclipse.equinox.launcher</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.platform</groupId>
            <artifactId>org.eclipse.equinox.util</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.platform</groupId>
            <artifactId>org.eclipse.equinox.wireadmin</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.felix</groupId>
            <artifactId>org.apache.felix.scr</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.platform</groupId>
            <artifactId>org.eclipse.core.runtime</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.platform</groupId>
            <artifactId>org.eclipse.core.jobs</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.platform</groupId>
            <artifactId>org.eclipse.equinox.preferences</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.platform</groupId>
            <artifactId>org.eclipse.core.contenttype</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.platform</groupId>
            <artifactId>org.eclipse.equinox.app</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.platform</groupId>
            <artifactId>org.eclipse.osgi</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.platform</groupId>
            <artifactId>org.eclipse.osgi.util</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.felix</groupId>
            <artifactId>org.apache.felix.gogo.command</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.felix</groupId>
            <artifactId>org.apache.felix.gogo.runtime</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.felix</groupId>
            <artifactId>org.apache.felix.gogo.shell</artifactId>
        </dependency>
    </dependencies>

    <!--
        TODO: bumps current maven versions in a properties file that can be read by other projects
    -->
    <!-- <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>properties-maven-plugin</artifactId>
                <version>1.2.1</version>
                <executions>
                    <execution>
                        <phase>initialize</phase>
                        <goals>
                            <goal>write-project-properties</goal>
                        </goals>
                        <configuration>
                            <outputFile>
                                ${project.basedir}/../config/target-platform-equinox.properties
                            </outputFile>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build> -->
</project>