/*******************************************************************************
 * Copyright (c) 2011, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.internal.cloudconnection.eclipseiot.mqtt.cloud;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Optional;
import java.util.Set;

import org.eclipse.kura.KuraException;
import org.eclipse.kura.core.util.NetUtil;
import org.eclipse.kura.message.KuraBirthPayload;
import org.eclipse.kura.message.KuraBirthPayload.KuraBirthPayloadBuilder;
import org.eclipse.kura.message.KuraDeviceProfile;
import org.eclipse.kura.message.KuraDisconnectPayload;
import org.eclipse.kura.message.KuraPosition;
import org.eclipse.kura.net.IP4Address;
import org.eclipse.kura.net.IP6Address;
import org.eclipse.kura.net.NetInterface;
import org.eclipse.kura.net.NetInterfaceAddress;
import org.eclipse.kura.net.status.NetworkInterfaceIpAddressStatus;
import org.eclipse.kura.net.status.NetworkInterfaceStatus;
import org.eclipse.kura.net.status.NetworkInterfaceType;
import org.eclipse.kura.net.status.modem.ModemInterfaceStatus;
import org.eclipse.kura.position.PositionService;
import org.eclipse.kura.system.SystemAdminService;
import org.eclipse.kura.system.SystemService;
import org.osgi.util.position.Position;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Utility class to build lifecycle payload messages.
 */
public class LifeCyclePayloadBuilder {

    private static final String ERROR = "ERROR";

    private static final Logger logger = LoggerFactory.getLogger(LifeCyclePayloadBuilder.class);

    private static final String UNKNOWN = "UNKNOWN";

    private final CloudConnectionManagerImpl cloudConnectionManagerImpl;

    LifeCyclePayloadBuilder(CloudConnectionManagerImpl cloudConnectionManagerImpl) {
        this.cloudConnectionManagerImpl = cloudConnectionManagerImpl;
    }

    public KuraBirthPayload buildBirthPayload() {
        // build device profile
        KuraDeviceProfile deviceProfile = buildDeviceProfile();

        // build accept encoding
        String acceptEncoding = buildAcceptEncoding();

        // build device name
        CloudConnectionManagerOptions cso = this.cloudConnectionManagerImpl.getCloudConnectionManagerOptions();
        String deviceName = cso.getDeviceDisplayName();
        if (deviceName == null) {
            deviceName = this.cloudConnectionManagerImpl.getSystemService().getDeviceName();
        }

        String payloadEncoding = this.cloudConnectionManagerImpl.getCloudConnectionManagerOptions().getPayloadEncoding()
                .name();

        // build birth certificate
        KuraBirthPayloadBuilder birthPayloadBuilder = new KuraBirthPayloadBuilder();
        birthPayloadBuilder.withUptime(deviceProfile.getUptime()).withDisplayName(deviceName)
                .withModelName(deviceProfile.getModelName()).withModelId(deviceProfile.getModelId())
                .withPartNumber(deviceProfile.getPartNumber()).withSerialNumber(deviceProfile.getSerialNumber())
                .withFirmwareVersion(deviceProfile.getFirmwareVersion()).withBiosVersion(deviceProfile.getBiosVersion())
                .withCpuVersion(deviceProfile.getCpuVersion()).withOs(deviceProfile.getOs())
                .withOsVersion(deviceProfile.getOsVersion()).withJvmName(deviceProfile.getJvmName())
                .withJvmVersion(deviceProfile.getJvmVersion()).withJvmProfile(deviceProfile.getJvmProfile())
                .withKuraVersion(deviceProfile.getApplicationFrameworkVersion())
                .withConnectionInterface(deviceProfile.getConnectionInterface())
                .withConnectionIp(deviceProfile.getConnectionIp()).withAcceptEncoding(acceptEncoding)
                .withAvailableProcessors(deviceProfile.getAvailableProcessors())
                .withTotalMemory(deviceProfile.getTotalMemory()).withOsArch(deviceProfile.getOsArch())
                .withOsgiFramework(deviceProfile.getOsgiFramework())
                .withOsgiFrameworkVersion(deviceProfile.getOsgiFrameworkVersion()).withPayloadEncoding(payloadEncoding)
                .withJvmVendor(deviceProfile.getJvmVendor()).withJdkVendorVersion(deviceProfile.getJdkVendorVersion());

        if (this.cloudConnectionManagerImpl.imei != null && this.cloudConnectionManagerImpl.imei.length() > 0
                && !this.cloudConnectionManagerImpl.imei.equals(ERROR)) {
            birthPayloadBuilder.withModemImei(this.cloudConnectionManagerImpl.imei);
        }
        if (this.cloudConnectionManagerImpl.iccid != null && this.cloudConnectionManagerImpl.iccid.length() > 0
                && !this.cloudConnectionManagerImpl.iccid.equals(ERROR)) {
            birthPayloadBuilder.withModemIccid(this.cloudConnectionManagerImpl.iccid);
        }

        if (this.cloudConnectionManagerImpl.imsi != null && this.cloudConnectionManagerImpl.imsi.length() > 0
                && !this.cloudConnectionManagerImpl.imsi.equals(ERROR)) {
            birthPayloadBuilder.withModemImsi(this.cloudConnectionManagerImpl.imsi);
        }

        if (this.cloudConnectionManagerImpl.rssi != null && this.cloudConnectionManagerImpl.rssi.length() > 0) {
            birthPayloadBuilder.withModemRssi(this.cloudConnectionManagerImpl.rssi);
        }

        if (this.cloudConnectionManagerImpl.modemFwVer != null
                && this.cloudConnectionManagerImpl.modemFwVer.length() > 0
                && !this.cloudConnectionManagerImpl.modemFwVer.equals(ERROR)) {
            birthPayloadBuilder.withModemFirmwareVersion(this.cloudConnectionManagerImpl.modemFwVer);
        }

        if (deviceProfile.getLatitude() != null && deviceProfile.getLongitude() != null) {
            KuraPosition kuraPosition = new KuraPosition();
            kuraPosition.setLatitude(deviceProfile.getLatitude());
            kuraPosition.setLongitude(deviceProfile.getLongitude());
            kuraPosition.setAltitude(deviceProfile.getAltitude());
            birthPayloadBuilder.withPosition(kuraPosition);
        }

        return birthPayloadBuilder.build();
    }

    public KuraDisconnectPayload buildDisconnectPayload() {
        SystemService systemService = this.cloudConnectionManagerImpl.getSystemService();
        SystemAdminService sysAdminService = this.cloudConnectionManagerImpl.getSystemAdminService();
        CloudConnectionManagerOptions cloudOptions = this.cloudConnectionManagerImpl.getCloudConnectionManagerOptions();

        // build device name
        String deviceName = cloudOptions.getDeviceDisplayName();
        if (deviceName == null) {
            deviceName = systemService.getDeviceName();
        }

        return new KuraDisconnectPayload(sysAdminService.getUptime(), deviceName);
    }

    public KuraDeviceProfile buildDeviceProfile() {
        SystemService systemService = this.cloudConnectionManagerImpl.getSystemService();
        SystemAdminService sysAdminService = this.cloudConnectionManagerImpl.getSystemAdminService();
        Optional<PositionService> positionService = this.cloudConnectionManagerImpl.getPositionService();

        //
        // get the network information
        StringBuilder sbConnectionIp = new StringBuilder();
        StringBuilder sbConnectionInterface = new StringBuilder();
        Set<String> reportedInterfaceNames = new HashSet<>();

        appendActiveNetworkInterfaces(sbConnectionInterface, sbConnectionIp, reportedInterfaceNames);
        // NetworkService has no visibility on ModemManager-managed modem interfaces (e.g. QMI/MBIM wwan*),
        // so their IP is fetched separately from NetworkStatusService, when available.
        appendConnectedModemsWithIp(sbConnectionInterface, sbConnectionIp, reportedInterfaceNames);

        String connectionIp = !sbConnectionIp.isEmpty() ? sbConnectionIp.toString() : UNKNOWN;
        String connectionInterface = !sbConnectionInterface.isEmpty() ? sbConnectionInterface.toString() : UNKNOWN;

        //
        // get the position information
        double latitude = 0.0;
        double longitude = 0.0;
        double altitude = 0.0;
        if (positionService.isPresent()) {
            Position position = positionService.get().getPosition();
            if (position != null) {
                latitude = Math.toDegrees(position.getLatitude().getValue());
                longitude = Math.toDegrees(position.getLongitude().getValue());
                altitude = position.getAltitude().getValue();
            } else {
                logger.warn("Unresolved PositionService reference.");
            }
        }

        return buildKuraDeviceProfile(systemService, sysAdminService, connectionIp, connectionInterface, latitude,
                longitude, altitude);
    }

    private KuraDeviceProfile buildKuraDeviceProfile(SystemService systemService, SystemAdminService sysAdminService,
            String connectionIp, String connectionInterface, double latitude, double longitude, double altitude) {
        KuraDeviceProfile kuraDeviceProfile = new KuraDeviceProfile();
        kuraDeviceProfile.setUptime(sysAdminService.getUptime());
        kuraDeviceProfile.setDisplayName(systemService.getDeviceName());
        kuraDeviceProfile.setModelName(systemService.getModelName());
        kuraDeviceProfile.setModelId(systemService.getModelId());
        kuraDeviceProfile.setPartNumber(systemService.getPartNumber());
        kuraDeviceProfile.setSerialNumber(systemService.getSerialNumber());
        kuraDeviceProfile.setFirmwareVersion(systemService.getFirmwareVersion());
        kuraDeviceProfile.setBiosVersion(systemService.getBiosVersion());
        kuraDeviceProfile.setOs(systemService.getOsName());
        kuraDeviceProfile.setOsVersion(systemService.getOsVersion());
        kuraDeviceProfile.setCpuVersion(systemService.getCpuVersion());
        kuraDeviceProfile.setJvmName(systemService.getJavaVmName());
        kuraDeviceProfile.setJvmVersion(systemService.getJavaVmVersion() + " " + systemService.getJavaVmInfo());
        kuraDeviceProfile.setJvmProfile(systemService.getJavaVendor() + " " + systemService.getJavaVersion());
        kuraDeviceProfile.setApplicationFramework(KuraDeviceProfile.DEFAULT_APPLICATION_FRAMEWORK);
        kuraDeviceProfile.setApplicationFrameworkVersion(systemService.getKuraVersion());
        kuraDeviceProfile.setConnectionInterface(connectionInterface);
        kuraDeviceProfile.setConnectionIp(connectionIp);
        kuraDeviceProfile.setLatitude(latitude);
        kuraDeviceProfile.setLongitude(longitude);
        kuraDeviceProfile.setAltitude(altitude);
        kuraDeviceProfile.setAvailableProcessors(String.valueOf(systemService.getNumberOfProcessors()));
        kuraDeviceProfile.setTotalMemory(String.valueOf(systemService.getTotalMemory()));
        kuraDeviceProfile.setOsArch(systemService.getOsArch());
        kuraDeviceProfile.setOsgiFramework(systemService.getOsgiFwName());
        kuraDeviceProfile.setOsgiFrameworkVersion(systemService.getOsgiFwVersion());
        kuraDeviceProfile.setJvmVendor(systemService.getJavaVmVendor());
        kuraDeviceProfile.setJdkVendorVersion(systemService.getJdkVendorVersion());
        return kuraDeviceProfile;
    }

    private String buildConnectionIp(NetInterface<? extends NetInterfaceAddress> ni) {
        String connectionIp = UNKNOWN;
        List<? extends NetInterfaceAddress> nias = ni.getNetInterfaceAddresses();
        if (nias != null && !nias.isEmpty() && nias.get(0).getAddress() != null) {
            connectionIp = nias.get(0).getAddress().getHostAddress();
        }
        return connectionIp;
    }

    private String buildConnectionInterface(NetInterface<? extends NetInterfaceAddress> ni) {
        StringBuilder sb = new StringBuilder();
        sb.append(ni.getName()).append(" (").append(NetUtil.hardwareAddressToString(ni.getHardwareAddress()))
                .append(")");
        return sb.toString();
    }

    private void appendActiveNetworkInterfaces(StringBuilder sbConnectionInterface, StringBuilder sbConnectionIp,
            Set<String> reportedInterfaceNames) {
        this.cloudConnectionManagerImpl.getNetworkService().ifPresent(ns -> {
            try {
                for (NetInterface<? extends NetInterfaceAddress> ni : ns.getActiveNetworkInterfaces()) {
                    List<? extends NetInterfaceAddress> nias = ni.getNetInterfaceAddresses();
                    if (nias != null && !nias.isEmpty()) {
                        appendCsv(sbConnectionInterface, buildConnectionInterface(ni));
                        appendCsv(sbConnectionIp, buildConnectionIp(ni));
                        reportedInterfaceNames.add(ni.getName());
                    }
                }
            } catch (Exception se) {
                logger.warn("Error while getting ConnetionIP and ConnectionInterface", se);
            }
        });
    }

    private void appendConnectedModemsWithIp(StringBuilder sbConnectionInterface, StringBuilder sbConnectionIp,
            Set<String> reportedInterfaceNames) {
        for (final ModemInterfaceStatus modemStatus : getConnectedModemsWithIp(reportedInterfaceNames)) {
            appendCsv(sbConnectionInterface, buildConnectionInterface(modemStatus));
            appendCsv(sbConnectionIp, buildConnectionIp(modemStatus));
        }
    }

    private void appendCsv(StringBuilder sb, String value) {
        if (sb.length() > 0) {
            sb.append(",");
        }
        sb.append(value);
    }

    private List<ModemInterfaceStatus> getConnectedModemsWithIp(Set<String> reportedInterfaceNames) {
        final List<ModemInterfaceStatus> result = new ArrayList<>();

        this.cloudConnectionManagerImpl.getNetworkStatusService().ifPresent(networkStatusService -> {
            try {
                for (final String interfaceId : networkStatusService.getInterfaceIds()) {
                    networkStatusService.getNetworkStatus(interfaceId).ifPresent(status -> {
                        if (status.getType() == NetworkInterfaceType.MODEM
                                && !reportedInterfaceNames.contains(status.getInterfaceName())
                                && hasIpAddress(status)) {
                            result.add((ModemInterfaceStatus) status);
                        }
                    });
                }
            } catch (final KuraException e) {
                logger.warn("Error while getting modem connection info from NetworkStatusService", e);
            }
        });

        return result;
    }

    private boolean hasIpAddress(NetworkInterfaceStatus status) {
        return status.getInterfaceIp4Addresses().map(ips -> !ips.getAddresses().isEmpty()).orElse(false)
                || status.getInterfaceIp6Addresses().map(ips -> !ips.getAddresses().isEmpty()).orElse(false);
    }

    private String buildConnectionIp(ModemInterfaceStatus modemStatus) {
        final Optional<NetworkInterfaceIpAddressStatus<IP4Address>> ip4Addresses = modemStatus
                .getInterfaceIp4Addresses();
        if (ip4Addresses.isPresent() && !ip4Addresses.get().getAddresses().isEmpty()) {
            return ip4Addresses.get().getAddresses().get(0).getAddress().getHostAddress();
        }
        final Optional<NetworkInterfaceIpAddressStatus<IP6Address>> ip6Addresses = modemStatus
                .getInterfaceIp6Addresses();
        if (ip6Addresses.isPresent() && !ip6Addresses.get().getAddresses().isEmpty()) {
            return ip6Addresses.get().getAddresses().get(0).getAddress().getHostAddress();
        }
        return UNKNOWN;
    }

    private String buildConnectionInterface(ModemInterfaceStatus modemStatus) {
        return modemStatus.getInterfaceName() + " ("
                + NetUtil.hardwareAddressToString(modemStatus.getHardwareAddress()) + ")";
    }

    private String buildAcceptEncoding() {
        String acceptEncoding = "";
        CloudConnectionManagerOptions options = this.cloudConnectionManagerImpl.getCloudConnectionManagerOptions();
        if (options.getEncodeGzip()) {
            acceptEncoding = "gzip";
        }
        return acceptEncoding;
    }
}
