/*******************************************************************************
 * Copyright (c) 2023, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.internal.rest.security.provider;

import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;

import jakarta.ws.rs.Path;

import org.osgi.service.component.annotations.Component;

@Tag(name = "Security", description = "Protected operations require rest.security or kura.admin permission.")
@ApiResponses({
        @ApiResponse(responseCode = "400", ref = "#/components/responses/BadRequest"),
        @ApiResponse(responseCode = "401", ref = "#/components/responses/Unauthenticated"),
        @ApiResponse(responseCode = "403", ref = "#/components/responses/Forbidden"),
        @ApiResponse(responseCode = "500", ref = "#/components/responses/InternalError")
})
@Path("security/v1")
@Component(
    name = "org.eclipse.kura.internal.rest.security.provider.SecurityRestServiceV1",
    immediate = true,
    service = { org.eclipse.kura.internal.rest.security.provider.SecurityRestServiceV1.class },
    property = {
        "kura.service.pid=org.eclipse.kura.internal.rest.security.provider.SecurityRestServiceV1",
        "osgi.jakartars.resource=true" })
public class SecurityRestServiceV1 extends AbstractRestSecurityService {

    private static final String MQTT_APP_ID = "SEC-V1";

    @Override
    public String getMqttAppId() {
        return MQTT_APP_ID;
    }
}
