/*******************************************************************************
 * Copyright (c) 2025 Eurotech and/or its affiliates and others
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *  Eurotech
 *******************************************************************************/
/* Some portions generated by generative AI */
package org.eclipse.kura.linux.gpio.libgpiod2;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.mockStatic;
import static org.mockito.Mockito.when;

import java.io.IOException;
import java.nio.file.FileAlreadyExistsException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Map;

import org.eclipse.kura.gpio.KuraGPIODirection;
import org.eclipse.kura.gpio.KuraGPIOMode;
import org.eclipse.kura.gpio.KuraGPIOPin;
import org.eclipse.kura.gpio.KuraGPIOTrigger;
import org.eclipse.kura.linux.gpio.libgpiod.CommonSteps;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.mockito.MockedStatic;

import com.sun.jna.Native;
import com.sun.jna.Pointer;

public class LibGpiodV2GPIOServiceTest extends CommonSteps {

    private static final String DEVICE_FOLDER = "/tmp/";

    private MockedStatic<Native> nativeMock;
    private LibGpiodV2Native nativeInterfaceMock;
    private MockedStatic<LibGpiodV2NativeWrapper> nativeInterfaceWrapperMock;

    private LibGpiodV2GPIOService v2Service;
    private KuraGPIOPin resultPin;
    private KuraGPIOPin resultPinAgain;
    private Map<Integer, String> resultPins;

    @Before
    public void setup() throws IOException {
        this.nativeMock = mockStatic(Native.class);
        this.nativeInterfaceMock = mock(LibGpiodV2Native.class);
        this.nativeMock.when(() -> Native.load("gpiod", LibGpiodV2Native.class)).thenReturn(this.nativeInterfaceMock);
        this.nativeInterfaceWrapperMock = mockStatic(LibGpiodV2NativeWrapper.class);
        this.nativeInterfaceWrapperMock.when(() -> LibGpiodV2NativeWrapper.getInstance())
                .thenReturn(this.nativeInterfaceMock);

        Pointer chip0 = Pointer.createConstant(0);
        when(this.nativeInterfaceMock.gpiod_chip_open(DEVICE_FOLDER + "gpiochip0")).thenReturn(chip0);
        Pointer chipInfo0 = Pointer.createConstant(100);
        when(this.nativeInterfaceMock.gpiod_chip_get_info(chip0)).thenReturn(chipInfo0);
        when(this.nativeInterfaceMock.gpiod_chip_info_get_num_lines(chipInfo0)).thenReturn(5);
        for (int offset = 0; offset < 5; offset++) {
            Pointer lineInfo0 = Pointer.createConstant(offset);
            when(this.nativeInterfaceMock.gpiod_chip_get_line_info(chip0, offset)).thenReturn(lineInfo0);
            when(this.nativeInterfaceMock.gpiod_line_info_get_name(lineInfo0)).thenReturn("GPIO0_" + offset);
        }
        Pointer chip1 = Pointer.createConstant(1);
        when(this.nativeInterfaceMock.gpiod_chip_open(DEVICE_FOLDER + "gpiochip1")).thenReturn(chip1);
        Pointer chipInfo1 = Pointer.createConstant(101);
        when(this.nativeInterfaceMock.gpiod_chip_get_info(chip1)).thenReturn(chipInfo1);
        when(this.nativeInterfaceMock.gpiod_chip_info_get_num_lines(chipInfo1)).thenReturn(5);
        for (int offset = 0; offset < 5; offset++) {
            Pointer lineInfo1 = Pointer.createConstant(offset + 5);
            when(this.nativeInterfaceMock.gpiod_chip_get_line_info(chip1, offset)).thenReturn(lineInfo1);
            when(this.nativeInterfaceMock.gpiod_line_info_get_name(lineInfo1)).thenReturn("GPIO1_" + offset);
        }
        Pointer chip2 = Pointer.createConstant(2);
        when(this.nativeInterfaceMock.gpiod_chip_open(DEVICE_FOLDER + "gpiochip2")).thenReturn(chip2);
        Pointer chipInfo2 = Pointer.createConstant(102);
        when(this.nativeInterfaceMock.gpiod_chip_get_info(chip2)).thenReturn(chipInfo2);
        when(this.nativeInterfaceMock.gpiod_chip_info_get_num_lines(chipInfo2)).thenReturn(5);
        for (int offset = 0; offset < 5; offset++) {
            Pointer lineInfo2 = Pointer.createConstant(offset + 10);
            when(this.nativeInterfaceMock.gpiod_chip_get_line_info(chip2, offset)).thenReturn(lineInfo2);
            when(this.nativeInterfaceMock.gpiod_line_info_get_name(lineInfo2)).thenReturn("GPIO2_" + offset);
        }
        Pointer chip3 = Pointer.createConstant(3);
        when(this.nativeInterfaceMock.gpiod_chip_open(DEVICE_FOLDER + "gpiochip3")).thenReturn(chip3);
        Pointer chipInfo3 = Pointer.createConstant(103);
        when(this.nativeInterfaceMock.gpiod_chip_get_info(chip3)).thenReturn(chipInfo3);
        when(this.nativeInterfaceMock.gpiod_chip_info_get_num_lines(chipInfo3)).thenReturn(5);
        for (int offset = 0; offset < 5; offset++) {
            Pointer lineInfo3 = Pointer.createConstant(offset + 15);
            when(this.nativeInterfaceMock.gpiod_chip_get_line_info(chip3, offset)).thenReturn(lineInfo3);
            when(this.nativeInterfaceMock.gpiod_line_info_get_name(lineInfo3)).thenReturn("-");
        }
        Pointer chip4 = Pointer.createConstant(4);
        when(this.nativeInterfaceMock.gpiod_chip_open(DEVICE_FOLDER + "gpiochip4")).thenReturn(chip4);
        Pointer chipInfo4 = Pointer.createConstant(104);
        when(this.nativeInterfaceMock.gpiod_chip_get_info(chip4)).thenReturn(chipInfo4);
        when(this.nativeInterfaceMock.gpiod_chip_info_get_num_lines(chipInfo4)).thenReturn(5);
        for (int offset = 0; offset < 5; offset++) {
            Pointer lineInfo4 = Pointer.createConstant(offset + 20);
            when(this.nativeInterfaceMock.gpiod_chip_get_line_info(chip4, offset)).thenReturn(lineInfo4);
            when(this.nativeInterfaceMock.gpiod_line_info_get_name(lineInfo4)).thenReturn("");
        }
        Pointer chip5 = Pointer.createConstant(2);
        when(this.nativeInterfaceMock.gpiod_chip_open(DEVICE_FOLDER + "gpiochip5")).thenReturn(chip5);
        Pointer chipInfo5 = Pointer.createConstant(105);
        when(this.nativeInterfaceMock.gpiod_chip_get_info(chip5)).thenReturn(chipInfo5);
        when(this.nativeInterfaceMock.gpiod_chip_info_get_num_lines(chipInfo5)).thenReturn(5);
        for (int offset = 0; offset < 5; offset++) {
            Pointer lineInfo5 = Pointer.createConstant(offset + 25);
            when(this.nativeInterfaceMock.gpiod_chip_get_line_info(chip5, offset)).thenReturn(lineInfo5);
            when(this.nativeInterfaceMock.gpiod_line_info_get_name(lineInfo5)).thenReturn(null);
        }

        for (int i = 0; i < 6; i++) {
            Files.deleteIfExists(Paths.get(DEVICE_FOLDER + "gpiochip" + i));
        }
    }

    @After
    public void cleanup() {
        this.nativeMock.close();
        this.nativeInterfaceWrapperMock.close();
    }

    @Test
    public void testGetPinByNameWithNullName() {
        givenV2GPIOService();

        whenV2ServiceGetPinByName(null);

        thenExceptionOccurred(IllegalArgumentException.class);
    }

    @Test
    public void testGetPinByNameWithEmptyName() {
        givenV2GPIOService();

        whenV2ServiceGetPinByName("");

        thenExceptionOccurred(IllegalArgumentException.class);
    }

    @Test
    public void testGetPinByNameWithWhitespaceOnlyName() {
        givenV2GPIOService();

        whenV2ServiceGetPinByName("   ");

        thenExceptionOccurred(IllegalArgumentException.class);
    }

    @Test
    public void testGetPinByNameWithValidNameAndDefaultParameters() {
        givenV2GPIOService();

        whenV2ServiceGetPinByName("GPIO0_1");

        thenNoExceptionOccurred();
        thenPinIsNotNull();
        thenPinIs("GPIO0_1", KuraGPIODirection.INPUT, KuraGPIOMode.INPUT_PULL_UP, KuraGPIOTrigger.NONE);
    }

    @Test
    public void testGetPinByNameWithValidNameAndParameters() {
        givenV2GPIOService();

        whenV2ServiceGetPinByName("GPIO0_1", KuraGPIODirection.OUTPUT, KuraGPIOMode.OUTPUT_OPEN_DRAIN,
                KuraGPIOTrigger.NONE);

        thenNoExceptionOccurred();
        thenPinIsNotNull();
        thenPinIs("GPIO0_1", KuraGPIODirection.OUTPUT, KuraGPIOMode.OUTPUT_OPEN_DRAIN, KuraGPIOTrigger.NONE);
    }

    @Test
    public void testGetPinByNameNotInAvailablePins() {
        givenV2GPIOService();

        whenV2ServiceGetPinByName("GPIO_100");

        thenExceptionOccurred(IllegalArgumentException.class);
    }

    @Test
    public void testGetPinByNameFromCache() {
        givenV2GPIOService();

        whenV2ServiceGetPinByName("GPIO2_3");
        whenV2ServiceGetPinByNameAgain("GPIO2_3");

        thenNoExceptionOccurred();
        thenPinsAreSame();
    }

    @Test
    public void testGetPinByTerminalWithNegativeTerminal() {
        givenV2GPIOService();

        whenV2ServiceGetPinByTerminal(-1);

        thenExceptionOccurred(IllegalArgumentException.class);
    }

    @Test
    public void testGetPinByTerminalWithValidTerminal() {
        givenV2GPIOService();

        whenV2ServiceGetPinByTerminal(2003);

        thenNoExceptionOccurred();
        thenPinIsNotNull();
        thenPinIs(2003, KuraGPIODirection.INPUT, KuraGPIOMode.INPUT_PULL_UP, KuraGPIOTrigger.NONE);
    }

    @Test
    public void testGetPinByTerminalWithParameters() {
        givenV2GPIOService();

        whenV2ServiceGetPinByTerminal(2003, KuraGPIODirection.OUTPUT, KuraGPIOMode.OUTPUT_PUSH_PULL,
                KuraGPIOTrigger.NONE);

        thenNoExceptionOccurred();
        thenPinIsNotNull();
        thenPinIs(2003, KuraGPIODirection.OUTPUT, KuraGPIOMode.OUTPUT_PUSH_PULL, KuraGPIOTrigger.NONE);
    }

    @Test
    public void testGetPinByTerminalNotInAvailablePins() {
        givenV2GPIOService();

        whenV2ServiceGetPinByTerminal(9999);

        thenExceptionOccurred(IllegalArgumentException.class);
    }

    @Test
    public void testGetPinByTerminalNotValid() {
        givenV2GPIOService();

        whenV2ServiceGetPinByTerminal(2033);

        thenExceptionOccurred(IllegalArgumentException.class);
    }

    @Test
    public void testGetPinByTerminalWithoutChip() {
        givenV2GPIOService();

        whenV2ServiceGetPinByTerminal(5023);

        thenExceptionOccurred(IllegalArgumentException.class);
    }

    @Test
    public void testGetPinByTerminalFromCache() {
        givenV2GPIOService();

        whenV2ServiceGetPinByTerminal(2003);
        whenV2ServiceGetPinByTerminalAgain(2003);

        thenNoExceptionOccurred();
        thenPinsAreSame();
    }

    @Test
    public void testGetAvailablePins() {
        givenV2GPIOService();

        whenV2ServiceGetAvailablePins();

        thenNoExceptionOccurred();
        thenAvailablePinsIsNotNullOrEmpty();
    }

    @Test
    public void testClearCache() {
        givenV2GPIOService();

        whenV2CacheIsCleared();

        thenNoExceptionOccurred();
        thenV2CacheIsEmpty();
    }

    @Test
    public void testRefresh() {
        givenV2GPIOService();

        whenV2CacheIsRefreshed();

        thenNoExceptionOccurred();
        thenV2CacheIsEmpty();
    }

    @Test
    public void testServiceInitialization() throws IOException {
        givenV2GPIOServiceNotInitialized(DEVICE_FOLDER);
        givenTmpGpioChips();

        whenV2ServiceIsInitialized();
        whenV2ServiceGetAvailablePins();

        thenNoExceptionOccurred();
        thenAvailablePinsIsNotNullOrEmpty();
    }

    @Test
    public void testServiceInitializationWithNotExistingDeviceFolder() throws IOException {
        givenV2GPIOServiceNotInitialized("not_existing_folder");
        givenTmpGpioChips();

        whenV2ServiceIsInitialized();
        whenV2ServiceGetAvailablePins();

        thenNoExceptionOccurred();
        thenAvailablePinsIsEmpty();
    }

    @Test
    public void testServiceInitializationWithNotExistingGpioChips() throws IOException {
        givenV2GPIOServiceNotInitialized("/opt/");
        givenTmpGpioChips();

        whenV2ServiceIsInitialized();
        whenV2ServiceGetAvailablePins();

        thenNoExceptionOccurred();
        thenAvailablePinsIsEmpty();
    }

    @Test
    public void testServiceInitializationWithWrongPinName() throws IOException {
        givenV2GPIOServiceNotInitialized(DEVICE_FOLDER);
        givenTmpGpioChips(3);

        whenV2ServiceIsInitialized();
        whenV2ServiceGetAvailablePins();

        thenNoExceptionOccurred();
        thenAvailablePinsIsEmpty();
    }

    @Test
    public void testServiceInitializationWithEmptyPinName() throws IOException {
        givenV2GPIOServiceNotInitialized(DEVICE_FOLDER);
        givenTmpGpioChips(4);

        whenV2ServiceIsInitialized();
        whenV2ServiceGetAvailablePins();

        thenNoExceptionOccurred();
        thenAvailablePinsIsEmpty();
    }

    @Test
    public void testServiceInitializationWithNullPinName() throws IOException {
        givenV2GPIOServiceNotInitialized(DEVICE_FOLDER);
        givenTmpGpioChips(5);

        whenV2ServiceIsInitialized();
        whenV2ServiceGetAvailablePins();

        thenNoExceptionOccurred();
        thenAvailablePinsIsEmpty();
    }

    /*
     * Given
     */

    private void givenV2GPIOService() {
        this.v2Service = new LibGpiodV2GPIOService() {

            @Override
            public void initialize() {
                this.availablePins.put("GPIO0_1", 1);
                this.availablePins.put("GPIO2_3", 2003);
                this.availablePins.put("GPIO5_23", 5023);
                this.initialized.set(true);
            }

            @Override
            protected String getDeviceFolderPath() {
                return DEVICE_FOLDER;
            }
        };
    }

    private void givenV2GPIOServiceNotInitialized(String deviceFolderPath) {
        this.v2Service = new LibGpiodV2GPIOService() {

            @Override
            protected String getDeviceFolderPath() {
                return deviceFolderPath;
            }
        };
    }

    private void givenTmpGpioChips() throws IOException {
        for (int i = 0; i < 3; i++) {
            try {
                Path newFilePath = Paths.get(DEVICE_FOLDER + "gpiochip" + i);
                Files.createFile(newFilePath);
            } catch (FileAlreadyExistsException e) {
                // Ignore if file already exists
            }
        }
    }

    private void givenTmpGpioChips(int gpioChipNumber) throws IOException {
        try {
            Path newFilePath = Paths.get(DEVICE_FOLDER + "gpiochip" + gpioChipNumber);
            Files.createFile(newFilePath);
        } catch (FileAlreadyExistsException e) {
            // Ignore if file already exists
        }
    }

    /*
     * When
     */

    private void whenV2ServiceGetPinByName(String pinName) {
        try {
            this.resultPin = this.v2Service.getPinByName(pinName);
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    private void whenV2ServiceGetPinByNameAgain(String pinName) {
        try {
            this.resultPinAgain = this.v2Service.getPinByName(pinName);
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    private void whenV2ServiceGetPinByName(String pinName, KuraGPIODirection direction, KuraGPIOMode mode,
            KuraGPIOTrigger trigger) {
        try {
            this.resultPin = this.v2Service.getPinByName(pinName, direction, mode, trigger);
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    private void whenV2ServiceGetPinByTerminal(int pinTerminal) {
        try {
            this.resultPin = this.v2Service.getPinByTerminal(pinTerminal);
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    private void whenV2ServiceGetPinByTerminalAgain(int pinTerminal) {
        try {
            this.resultPinAgain = this.v2Service.getPinByTerminal(pinTerminal);
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    private void whenV2ServiceGetPinByTerminal(int pinTerminal, KuraGPIODirection direction, KuraGPIOMode mode,
            KuraGPIOTrigger trigger) {
        try {
            this.resultPin = this.v2Service.getPinByTerminal(pinTerminal, direction, mode, trigger);
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    private void whenV2ServiceGetAvailablePins() {
        try {
            this.resultPins = this.v2Service.getAvailablePins();
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    private void whenV2CacheIsCleared() {
        try {
            this.v2Service.clearCache();
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    private void whenV2CacheIsRefreshed() {
        try {
            this.v2Service.refresh();
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    private void whenV2ServiceIsInitialized() {
        try {
            this.v2Service.initialize();
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    /*
     * Then
     */

    private void thenPinIsNotNull() {
        assertNotNull(this.resultPin);
    }

    private void thenAvailablePinsIsNotNullOrEmpty() {
        assertNotNull(this.resultPins);
        assertFalse(this.resultPins.isEmpty());
    }

    private void thenAvailablePinsIsEmpty() {
        assertTrue(this.resultPins == null || this.resultPins.isEmpty());
    }

    private void thenV2CacheIsEmpty() {
        assertTrue(this.v2Service.getPinCache().isEmpty());
    }

    private void thenPinIs(String pinName, KuraGPIODirection direction, KuraGPIOMode mode, KuraGPIOTrigger trigger) {
        assertEquals(pinName, this.resultPin.getName());
        assertEquals(direction, this.resultPin.getDirection());
        assertEquals(mode, this.resultPin.getMode());
        assertEquals(trigger, this.resultPin.getTrigger());
    }

    private void thenPinIs(int pinTerminal, KuraGPIODirection direction, KuraGPIOMode mode, KuraGPIOTrigger trigger) {
        assertEquals(pinTerminal, this.resultPin.getIndex());
        assertEquals(direction, this.resultPin.getDirection());
        assertEquals(mode, this.resultPin.getMode());
        assertEquals(trigger, this.resultPin.getTrigger());
    }

    private void thenPinsAreSame() {
        assertEquals(this.resultPin, this.resultPinAgain);
    }

}