/*******************************************************************************
 * Copyright (c) 2025 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.rest.provider.test;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoInteractions;

import java.lang.reflect.Method;
import java.security.Principal;

import org.eclipse.kura.identity.Permission;
import org.eclipse.kura.identity.TemporaryIdentityService;
import org.eclipse.kura.internal.rest.auth.TokenHolder;
import org.eclipse.kura.internal.rest.provider.AuthenticationFilter;
import org.junit.Before;
import org.junit.Test;
import org.mockito.ArgumentCaptor;
import org.mockito.Mockito;

/**
 * Feature: AuthenticationFilter authorizes TokenHolder principals through the TemporaryIdentityService.
 */
public class AuthenticationFilterTemporaryTokenTest {

    private AuthenticationFilter authenticationFilter;
    private TemporaryIdentityService temporaryIdentityService;
    private Principal tokenHolderPrincipal;
    private boolean authorizationResult;

    @Before
    public void setUp() {
        this.authenticationFilter = new AuthenticationFilter();
        this.temporaryIdentityService = Mockito.mock(TemporaryIdentityService.class);
        this.authenticationFilter.setTemporaryIdentityService(this.temporaryIdentityService);
    }

    @Test
    public void authorizesTokenHolderWithValidPermission() throws Exception {
        givenTokenHolderPrincipalWithToken("kura-temp-valid", "temp-user");
        givenTemporaryIdentityServiceAcceptsPermission();

        whenRoleIsChecked("assets");

        thenPermissionWasValidatedForToken("kura-temp-valid", "rest.assets");
        thenAuthorizationResultIs(true);
    }

    @Test
    public void deniesAccessWhenTokenIsNull() throws Exception {
        givenTokenHolderPrincipalWithToken(null, "temp-user");
        givenTemporaryIdentityServiceAcceptsPermission();

        whenRoleIsChecked("assets");

        thenTemporaryServiceIsNotInvoked();
        thenAuthorizationResultIs(false);
    }

    private void givenTokenHolderPrincipalWithToken(final String token, final String name) {
        this.tokenHolderPrincipal = new StubTokenHolder(name, token);
    }

    private void givenTemporaryIdentityServiceAcceptsPermission() throws Exception {
        doAnswer(invocation -> null).when(this.temporaryIdentityService).checkTemporaryPermission(anyString(),
                any(Permission.class));
    }

    private void whenRoleIsChecked(final String role) throws Exception {
        this.authorizationResult = invokeIsUserInRole(this.tokenHolderPrincipal, role);
    }

    private void thenPermissionWasValidatedForToken(final String expectedToken, final String expectedPermissionName)
            throws Exception {
        final ArgumentCaptor<Permission> permissionCaptor = ArgumentCaptor.forClass(Permission.class);
        verify(this.temporaryIdentityService).checkTemporaryPermission(eq(expectedToken), permissionCaptor.capture());
        assertTrue("Permission name should match",
                expectedPermissionName.equals(permissionCaptor.getValue().getName()));
    }

    private void thenAuthorizationResultIs(final boolean expected) {
        if (expected) {
            assertTrue("Authorization should have succeeded", this.authorizationResult);
        } else {
            assertFalse("Authorization should have failed", this.authorizationResult);
        }
    }

    private void thenTemporaryServiceIsNotInvoked() {
        verifyNoInteractions(this.temporaryIdentityService);
    }

    private boolean invokeIsUserInRole(final Principal principal, final String role) throws Exception {
        final Method method = AuthenticationFilter.class.getDeclaredMethod("isUserInRole", Principal.class, String.class);
        method.setAccessible(true);
        return (Boolean) method.invoke(this.authenticationFilter, principal, role);
    }

    private static final class StubTokenHolder implements Principal, TokenHolder {

        private final String name;
        private final String token;

        StubTokenHolder(final String name, final String token) {
            this.name = name;
            this.token = token;
        }

        @Override
        public String getName() {
            return this.name;
        }

        @Override
        public String getToken() {
            return this.token;
        }
    }
}
