/*******************************************************************************
 * Copyright (c) 2025 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.rest.provider.test;

import static org.junit.Assert.fail;

import java.util.Collections;
import java.util.Dictionary;
import java.util.Hashtable;
import java.util.Optional;
import java.util.Set;
import java.util.concurrent.TimeUnit;
import java.util.stream.Collectors;

import org.eclipse.kura.core.testutil.requesthandler.AbstractRequestHandlerTest;
import org.eclipse.kura.core.testutil.requesthandler.RestTransport;
import org.eclipse.kura.core.testutil.requesthandler.Transport.MethodSpec;
import org.eclipse.kura.core.testutil.requesthandler.Transport.Response;
import org.eclipse.kura.core.testutil.service.ServiceUtil;
import org.eclipse.kura.identity.Permission;
import org.eclipse.kura.identity.TemporaryIdentityService;
import org.junit.After;
import org.junit.Test;
import org.osgi.framework.BundleContext;
import org.osgi.framework.FrameworkUtil;
import org.osgi.framework.ServiceRegistration;
import org.osgi.service.useradmin.Role;
import org.osgi.service.useradmin.UserAdmin;

import jakarta.annotation.security.RolesAllowed;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;

/**
 * Feature: Temporary token based REST authorization.
 */
public class TemporaryTokenRestAuthorizationTest extends AbstractRequestHandlerTest {

    private Optional<ServiceRegistration<?>> serviceRegistration = Optional.empty();
    private Optional<String> temporaryToken = Optional.empty();

    public TemporaryTokenRestAuthorizationTest() {
        super(new RestTransport("testservice"));
    }

    @Test
    public void allowsAccessWhenTemporaryTokenHasRequiredPermission() throws Exception {
        givenRestResourceProtectedByRoleInventory();
        givenNoBasicCredentials();
        givenPermissionIsDefined("rest.inventory");
        givenTemporaryIdentityTokenWithPermissions(Set.of("rest.inventory"));

        whenRequestIsPerformedWithTemporaryTokenHeader();
        whenRequestIsPerformed(new MethodSpec("GET"), "/requireInventory");

        thenResponseCodeIs(200);
    }

    @Test
    public void deniesAccessWhenTemporaryTokenLacksRequiredPermission() throws Exception {
        givenRestResourceProtectedByRoleInventory();
        givenNoBasicCredentials();
        givenPermissionIsDefined("rest.inventory");
        givenTemporaryIdentityTokenWithPermissions(Collections.emptySet());

        whenRequestIsPerformedWithTemporaryTokenHeader();
        whenRequestIsPerformed(new MethodSpec("GET"), "/requireInventory");

        thenResponseCodeIs(403);
    }

    /*
     * GIVEN
     */

    private void givenRestResourceProtectedByRoleInventory() {
        final BundleContext bundleContext = FrameworkUtil.getBundle(TemporaryTokenRestAuthorizationTest.class)
                .getBundleContext();

        final Dictionary<String, Object> properties = new Hashtable<>();
        properties.put("osgi.jakartars.resource", true);

        this.serviceRegistration = Optional
                .of(bundleContext.registerService(InventoryRoleService.class, new InventoryRoleService(), properties));

        final RestTransport restTransport = (RestTransport) this.transport;

        for (int i = 0; i < 100; i++) {
            final Response response = restTransport.runRequest("/ping", new MethodSpec("GET"));

            if (response.getStatus() != 404 && response.getStatus() != 503) {
                return;
            }

            try {
                synchronized (this) {
                    this.wait(100);
                }
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                fail("Interrupted while waiting for service startup");
            }
        }
    }

    private void givenNoBasicCredentials() {
        ((RestTransport) this.transport).setBasicCredentials(Optional.empty());
    }

    private void givenPermissionIsDefined(final String permission) throws Exception {
        final UserAdmin userAdmin = ServiceUtil.trackService(UserAdmin.class, Optional.empty()).get(30,
                TimeUnit.SECONDS);

        final String roleName = "kura.permission." + permission;
        if (userAdmin.getRole(roleName) == null) {
            userAdmin.createRole(roleName, Role.GROUP);
        }
    }

    private void givenTemporaryIdentityTokenWithPermissions(final Set<String> permissions) throws Exception {
        final TemporaryIdentityService temporaryIdentityService = ServiceUtil
                .trackService(TemporaryIdentityService.class, Optional.empty()).get(30, TimeUnit.SECONDS);

        final Set<Permission> asPermissions = permissions.stream().map(Permission::new).collect(Collectors.toSet());

        this.temporaryToken = Optional
                .of(temporaryIdentityService.createTemporaryIdentity("container_ci", asPermissions));
    }

    /*
     * WHEN
     */

    private void whenRequestIsPerformedWithTemporaryTokenHeader() {
        final String token = this.temporaryToken.orElseThrow(() -> new IllegalStateException("token not available"));
        ((RestTransport) this.transport).setHeader("Authorization", "Kura-Token " + token);
    }

    /*
     * Services
     */

    @Path("testservice")
    public static class InventoryRoleService extends TestService {

        @GET
        @Path("requireInventory")
        @RolesAllowed("inventory")
        public String requireInventory() {
            return "ok";
        }
    }

    public static abstract class TestService {

        @GET
        @Path("/ping")
        public String ping() {
            return "ok";
        }
    }

    @After
    public void tearDown() throws Exception {
        this.serviceRegistration.ifPresent(ServiceRegistration::unregister);
        this.serviceRegistration = Optional.empty();

        if (this.temporaryToken.isPresent()) {
            final TemporaryIdentityService temporaryIdentityService = ServiceUtil
                    .trackService(TemporaryIdentityService.class, Optional.empty()).get(30, TimeUnit.SECONDS);
            temporaryIdentityService.deleteTemporaryIdentity(this.temporaryToken.get());
        }
        this.temporaryToken = Optional.empty();
    }
}
