/*******************************************************************************
 * Copyright (c) 2025 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.rest.provider.test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import java.lang.reflect.Constructor;
import java.security.Principal;

import org.eclipse.kura.internal.rest.auth.TokenHolder;
import org.junit.Test;

/**
 * Feature: Temporary token principals expose their token through the TokenHolder interface.
 */
public class TemporaryTokenPrincipalTest {

    private Object principalInstance;
    private TokenHolder tokenHolder;

    @Test
    public void exposesTokenThroughTokenHolder() throws Exception {
        givenTemporaryTokenPrincipal("temp-user", "kura-temp-123");

        whenPrincipalIsViewedAsTokenHolder();

        thenPrincipalImplementsTokenHolder();
        thenTokenAndNameAreExposed("kura-temp-123", "temp-user");
    }

    private void givenTemporaryTokenPrincipal(final String name, final String token) throws Exception {
        final Class<?> principalClass = Class.forName(
                "org.eclipse.kura.internal.rest.auth.TemporaryTokenAuthenticationProvider$TemporaryTokenPrincipal");
        final Constructor<?> constructor = principalClass.getDeclaredConstructor(String.class, String.class);
        constructor.setAccessible(true);

        this.principalInstance = constructor.newInstance(name, token);
    }

    private void whenPrincipalIsViewedAsTokenHolder() {
        this.tokenHolder = (TokenHolder) this.principalInstance;
    }

    private void thenPrincipalImplementsTokenHolder() {
        assertTrue("Principal should implement TokenHolder", this.principalInstance instanceof TokenHolder);
    }

    private void thenTokenAndNameAreExposed(final String expectedToken, final String expectedName) {
        assertEquals(expectedToken, this.tokenHolder.getToken());
        assertEquals(expectedName, ((Principal) this.principalInstance).getName());
    }
}
