/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 * Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.data;

import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import org.eclipse.kura.data.listener.DataServiceListener;
import org.junit.Test;
import org.osgi.service.component.ComponentContext;

public class NotifyDataServiceListenersTest {

    private static final String TOPIC = "topic";
    private static final byte[] PAYLOAD = new byte[] { 1, 2, 3 };

    private final ComponentContext componentContext = mock(ComponentContext.class);
    private final DataServiceListenerS dataServiceListeners = new DataServiceListenerS(this.componentContext);
    private final org.eclipse.kura.data.DataServiceListener failingService = mock(
            org.eclipse.kura.data.DataServiceListener.class);
    private final org.eclipse.kura.data.DataServiceListener healthyService = mock(
            org.eclipse.kura.data.DataServiceListener.class);
    private final DataServiceListener failingListener = mock(DataServiceListener.class);
    private final DataServiceListener healthyListener = mock(DataServiceListener.class);
    private Throwable propagatedThrowable;

    /*
     * Scenarios
     */

    @Test
    public void notifiesServicesAndListeners() {
        givenRegisteredServices(this.healthyService);
        givenAddedListeners(this.healthyListener);

        whenMessageArrives();

        thenNothingPropagated();
        thenServiceNotifiedOfMessage(this.healthyService);
        thenListenerNotifiedOfMessage(this.healthyListener);
    }

    @Test
    public void notifiesRemainingServicesAndListenersWhenOneThrowsException() {
        givenServiceFailingWith(this.failingService, new IllegalStateException("listener failure"));
        givenListenerFailingWith(this.failingListener, new IllegalStateException("listener failure"));
        givenRegisteredServices(this.failingService, this.healthyService);
        givenAddedListeners(this.failingListener, this.healthyListener);

        whenMessageArrives();

        thenNothingPropagated();
        thenServiceNotifiedOfMessage(this.healthyService);
        thenListenerNotifiedOfMessage(this.healthyListener);
    }

    @Test
    public void notifiesRemainingServicesAndListenersWhenOneFailsWithLinkageError() {
        givenServiceFailingWith(this.failingService, new NoClassDefFoundError("uninstalled bundle class"));
        givenListenerFailingWith(this.failingListener, new NoClassDefFoundError("uninstalled bundle class"));
        givenRegisteredServices(this.failingService, this.healthyService);
        givenAddedListeners(this.failingListener, this.healthyListener);

        whenMessageArrives();

        thenNothingPropagated();
        thenServiceNotifiedOfMessage(this.healthyService);
        thenListenerNotifiedOfMessage(this.healthyListener);
    }

    @Test
    public void propagatesVirtualMachineErrorFromListener() {
        givenListenerFailingWith(this.failingListener, new OutOfMemoryError("simulated"));
        givenRegisteredServices();
        givenAddedListeners(this.failingListener, this.healthyListener);

        whenMessageArrives();

        thenPropagated(OutOfMemoryError.class);
    }

    /*
     * Steps
     */

    private void givenRegisteredServices(org.eclipse.kura.data.DataServiceListener... services) {
        when(this.componentContext.locateServices("DataServiceListener")).thenReturn(services);
    }

    private void givenAddedListeners(DataServiceListener... listeners) {
        for (final DataServiceListener listener : listeners) {
            this.dataServiceListeners.add(listener);
        }
    }

    private void givenServiceFailingWith(org.eclipse.kura.data.DataServiceListener service, Throwable failure) {
        doThrow(failure).when(service).onMessageArrived(TOPIC, PAYLOAD, 1, false);
    }

    private void givenListenerFailingWith(DataServiceListener listener, Throwable failure) {
        doThrow(failure).when(listener).onMessageArrived(TOPIC, PAYLOAD, 1, false);
    }

    private void whenMessageArrives() {
        try {
            this.dataServiceListeners.onMessageArrived(TOPIC, PAYLOAD, 1, false);
        } catch (Throwable e) {
            this.propagatedThrowable = e;
        }
    }

    private void thenNothingPropagated() {
        assertNull(this.propagatedThrowable);
    }

    private void thenPropagated(Class<? extends Throwable> expected) {
        assertTrue("unexpected: " + this.propagatedThrowable, expected.isInstance(this.propagatedThrowable));
    }

    private void thenServiceNotifiedOfMessage(org.eclipse.kura.data.DataServiceListener service) {
        verify(service).onMessageArrived(TOPIC, PAYLOAD, 1, false);
    }

    private void thenListenerNotifiedOfMessage(DataServiceListener listener) {
        verify(listener).onMessageArrived(TOPIC, PAYLOAD, 1, false);
    }
}
