/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 * Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.data;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.locks.Condition;
import java.util.concurrent.locks.ReentrantLock;

import org.eclipse.kura.core.testutil.TestUtil;
import org.junit.Test;

public class PublisherSignalingTest {

    private final DataServiceImpl dataService = new DataServiceImpl();
    private Thread suspendedPublisher;
    private Throwable publisherFailure;

    /*
     * Scenarios
     */

    @Test
    public void signalingPublisherSetsPendingNotificationAndReleasesLock() throws Throwable {
        givenNoPendingNotification();

        whenPublisherIsSignaled();

        thenNotificationIsPending(true);
        thenLockIsReleased();
    }

    @Test
    public void suspendingPublisherWithPendingNotificationReturnsAndReleasesLock() throws Throwable {
        givenPublisherEnabled();
        givenPendingNotification();

        whenPublisherIsSuspended();

        thenNotificationIsPending(false);
        thenLockIsReleased();
    }

    @Test
    public void suspendedPublisherResumesWhenSignaled() throws Throwable {
        givenPublisherEnabled();
        givenNoPendingNotification();
        givenPublisherSuspendedInBackground();

        whenPublisherIsSignaled();

        thenSuspendedPublisherResumes();
        thenNotificationIsPending(false);
        thenLockIsReleased();
    }

    /*
     * Steps
     */

    private void givenPublisherEnabled() throws NoSuchFieldException {
        ((AtomicBoolean) TestUtil.getFieldValue(this.dataService, "publisherEnabled")).set(true);
    }

    private void givenPendingNotification() throws NoSuchFieldException {
        TestUtil.setFieldValue(this.dataService, "notifyPending", true);
    }

    private void givenNoPendingNotification() throws NoSuchFieldException {
        TestUtil.setFieldValue(this.dataService, "notifyPending", false);
    }

    private void givenPublisherSuspendedInBackground() throws InterruptedException, NoSuchFieldException {
        this.suspendedPublisher = new Thread(() -> {
            try {
                suspendPublisher();
            } catch (Throwable e) {
                this.publisherFailure = e;
            }
        });
        this.suspendedPublisher.start();

        final ReentrantLock lock = lock();
        final long deadline = System.nanoTime() + TimeUnit.SECONDS.toNanos(10);
        while (!hasWaiters(lock) && System.nanoTime() < deadline) {
            Thread.sleep(10);
        }
        assertTrue("publisher did not suspend", hasWaiters(lock));
    }

    private void whenPublisherIsSignaled() throws Throwable {
        TestUtil.invokePrivate(this.dataService, "signalPublisher");
    }

    private void whenPublisherIsSuspended() throws Throwable {
        suspendPublisher();
    }

    private void thenNotificationIsPending(boolean expected) throws NoSuchFieldException {
        assertEquals(expected, TestUtil.getFieldValue(this.dataService, "notifyPending"));
    }

    private void thenLockIsReleased() throws NoSuchFieldException {
        assertFalse(lock().isLocked());
    }

    private void thenSuspendedPublisherResumes() throws InterruptedException {
        this.suspendedPublisher.join(TimeUnit.SECONDS.toMillis(10));
        assertFalse("publisher still suspended", this.suspendedPublisher.isAlive());
        assertNull(this.publisherFailure);
    }

    /*
     * Utilities
     */

    private ReentrantLock lock() throws NoSuchFieldException {
        return (ReentrantLock) TestUtil.getFieldValue(this.dataService, "lock");
    }

    private boolean hasWaiters(ReentrantLock lock) {
        lock.lock();
        try {
            return lock.hasWaiters(
                    (Condition) TestUtil.getFieldValue(this.dataService, "lockCondition"));
        } catch (NoSuchFieldException e) {
            throw new IllegalStateException(e);
        } finally {
            lock.unlock();
        }
    }

    private void suspendPublisher() throws Throwable {
        final Class<?> publishManagerClass = Class.forName(DataServiceImpl.class.getName() + "$PublishManager");
        final Constructor<?> constructor = publishManagerClass.getDeclaredConstructor(DataServiceImpl.class);
        constructor.setAccessible(true);
        final Object publishManager = constructor.newInstance(this.dataService);
        final Method suspend = publishManagerClass.getDeclaredMethod("suspendPublisher", long.class, TimeUnit.class);
        suspend.setAccessible(true);
        try {
            suspend.invoke(publishManager, -1L, TimeUnit.NANOSECONDS);
        } catch (InvocationTargetException e) {
            throw e.getCause();
        }
    }
}
