/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 * Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.data;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import java.lang.reflect.Constructor;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.locks.Condition;
import java.util.concurrent.locks.Lock;

import org.eclipse.kura.core.testutil.TestUtil;
import org.junit.After;
import org.junit.Test;

public class SuspendPublisherTest {

    private static final long INDEFINITELY = -1;

    private final DataServiceImpl dataService = new DataServiceImpl();
    private Object publishManager;
    private CompletableFuture<Long> suspension;

    @Test
    public void suspendedPublisherResumesWhenSignalled() throws Throwable {
        givenPublisherEnabled();
        givenPublishManager();

        whenPublisherIsSuspended(INDEFINITELY, TimeUnit.NANOSECONDS);
        whenPublisherIsSignalled();

        thenPublisherResumesWithin(5, TimeUnit.SECONDS);
        thenNoNotificationIsPending();
    }

    @Test
    public void suspendedPublisherKeepsWaitingOnWakeUpWithoutNotification() throws Throwable {
        givenPublisherEnabled();
        givenPublishManager();

        whenPublisherIsSuspended(INDEFINITELY, TimeUnit.NANOSECONDS);
        whenConditionIsSignalledWithoutNotification();

        thenPublisherIsStillSuspendedAfter(300, TimeUnit.MILLISECONDS);
    }

    @Test
    public void suspendedPublisherResumesAfterTimeout() throws Throwable {
        givenPublisherEnabled();
        givenPublishManager();

        whenPublisherIsSuspended(200, TimeUnit.MILLISECONDS);

        thenPublisherResumesWithin(5, TimeUnit.SECONDS);
        thenPublisherWasSuspendedAtLeast(200, TimeUnit.MILLISECONDS);
    }

    @Test
    public void publisherWithTimeoutResumesWhenSignalled() throws Throwable {
        givenPublisherEnabled();
        givenPublishManager();

        whenPublisherIsSuspended(1, TimeUnit.MINUTES);
        whenPublisherIsSignalled();

        thenPublisherResumesWithin(5, TimeUnit.SECONDS);
        thenNoNotificationIsPending();
    }

    @Test
    public void publisherDoesNotSuspendWhenNotificationIsPending() throws Throwable {
        givenPublisherEnabled();
        givenPublishManager();
        givenNotificationPending();

        whenPublisherIsSuspended(INDEFINITELY, TimeUnit.NANOSECONDS);

        thenPublisherResumesWithin(5, TimeUnit.SECONDS);
        thenNoNotificationIsPending();
    }

    @Test
    public void disabledPublisherDoesNotSuspend() throws Throwable {
        givenPublishManager();

        whenPublisherIsSuspended(INDEFINITELY, TimeUnit.NANOSECONDS);

        thenPublisherResumesWithin(5, TimeUnit.SECONDS);
    }

    @After
    public void releasePublisher() throws Throwable {
        if (this.suspension != null && !this.suspension.isDone()) {
            whenPublisherIsSignalled();
            this.suspension.get(5, TimeUnit.SECONDS);
        }
    }

    /*
     * Steps
     */

    private void givenPublisherEnabled() throws NoSuchFieldException {
        ((AtomicBoolean) TestUtil.getFieldValue(this.dataService, "publisherEnabled")).set(true);
    }

    private void givenPublishManager() throws Exception {
        final Class<?> publishManagerClass = Class.forName(DataServiceImpl.class.getName() + "$PublishManager");
        final Constructor<?> constructor = publishManagerClass.getDeclaredConstructor(DataServiceImpl.class);
        constructor.setAccessible(true);
        this.publishManager = constructor.newInstance(this.dataService);
    }

    private void givenNotificationPending() throws NoSuchFieldException {
        TestUtil.setFieldValue(this.dataService, "notifyPending", true);
    }

    private void whenPublisherIsSuspended(final long timeout, final TimeUnit timeUnit) throws InterruptedException {
        this.suspension = CompletableFuture.supplyAsync(() -> {
            final long start = System.nanoTime();
            try {
                TestUtil.invokePrivate(this.publishManager, "suspendPublisher",
                        new Class<?>[] { long.class, TimeUnit.class }, timeout, timeUnit);
            } catch (Throwable e) {
                throw new IllegalStateException(e);
            }
            return System.nanoTime() - start;
        });
        // let the publisher reach the wait before the next step
        Thread.sleep(100);
    }

    private void whenPublisherIsSignalled() throws Throwable {
        TestUtil.invokePrivate(this.dataService, "signalPublisher");
    }

    private void whenConditionIsSignalledWithoutNotification() throws NoSuchFieldException {
        final Lock lock = (Lock) TestUtil.getFieldValue(this.dataService, "lock");
        final Condition condition = (Condition) TestUtil.getFieldValue(this.dataService, "lockCondition");
        lock.lock();
        try {
            condition.signalAll();
        } finally {
            lock.unlock();
        }
    }

    private void thenPublisherResumesWithin(final long timeout, final TimeUnit timeUnit) throws Exception {
        this.suspension.get(timeout, timeUnit);
        assertTrue(this.suspension.isDone());
    }

    private void thenPublisherIsStillSuspendedAfter(final long time, final TimeUnit timeUnit)
            throws InterruptedException {
        Thread.sleep(timeUnit.toMillis(time));
        assertFalse(this.suspension.isDone());
    }

    private void thenPublisherWasSuspendedAtLeast(final long time, final TimeUnit timeUnit) throws Exception {
        assertTrue(this.suspension.get() >= timeUnit.toNanos(time));
    }

    private void thenNoNotificationIsPending() throws NoSuchFieldException {
        assertFalse((Boolean) TestUtil.getFieldValue(this.dataService, "notifyPending"));
    }
}
