/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 * Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.deployment.agent.impl;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;
import static org.mockserver.model.HttpRequest.request;
import static org.mockserver.model.HttpResponse.response;

import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.nio.file.Files;

import org.eclipse.kura.KuraRuntimeException;
import org.eclipse.kura.core.testutil.TestUtil;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;
import org.mockserver.integration.ClientAndServer;
import org.mockserver.socket.PortFactory;

public class FetchRemoteDeploymentPackageTest {

    private static final byte[] PACKAGE_CONTENT = "deployment package content".getBytes();

    private static ClientAndServer server;

    private final DeploymentAgent deploymentAgent = new DeploymentAgent();
    private File downloadedFile;
    private Throwable occurredException;

    /*
     * Scenarios
     */

    @Test
    public void downloadsPackageAfterFollowingRedirect() throws IOException {
        givenServerRedirectingBeforeContent(1);

        whenRemotePackageIsFetched();

        thenNoExceptionOccurred();
        thenDownloadedFileContainsPackage();
        thenRequestCountIs(2);
    }

    @Test
    public void downloadsPackageAfterRedirectsUpToTheLimit() throws IOException {
        givenServerRedirectingBeforeContent(DeploymentAgent.MAX_REDIRECTS);

        whenRemotePackageIsFetched();

        thenNoExceptionOccurred();
        thenDownloadedFileContainsPackage();
        thenRequestCountIs(DeploymentAgent.MAX_REDIRECTS + 1);
    }

    @Test
    public void failsWhenRedirectLoopExceedsTheLimit() {
        givenServerRedirectingForever();

        whenRemotePackageIsFetched();

        thenExceptionOccurred(IOException.class);
        thenNoFileDownloaded();
        thenRequestCountIs(DeploymentAgent.MAX_REDIRECTS + 1);
    }

    @Test
    public void failsWhenRedirectHasNoLocation() {
        givenServerRedirectingWithoutLocation();

        whenRemotePackageIsFetched();

        thenExceptionOccurred(KuraRuntimeException.class);
        thenNoFileDownloaded();
        thenRequestCountIs(1);
    }

    @BeforeClass
    public static void startServer() {
        server = ClientAndServer.startClientAndServer(PortFactory.findFreePort());
    }

    @AfterClass
    public static void stopServer() {
        server.stop();
    }

    @After
    public void tearDown() throws IOException {
        server.reset();
        if (this.downloadedFile != null) {
            Files.deleteIfExists(this.downloadedFile.toPath());
        }
    }

    /*
     * Steps
     */

    private void givenServerRedirectingBeforeContent(int redirects) {
        for (int hop = 0; hop < redirects; hop++) {
            addRedirect("/" + hop, "/" + (hop + 1));
        }
        server.when(request().withMethod("GET").withPath("/" + redirects))
                .respond(response().withStatusCode(200).withBody(PACKAGE_CONTENT));
    }

    private void givenServerRedirectingForever() {
        addRedirect("/0", "/0");
    }

    private void givenServerRedirectingWithoutLocation() {
        server.when(request().withMethod("GET").withPath("/0")).respond(response().withStatusCode(302));
    }

    private void whenRemotePackageIsFetched() {
        try {
            final URL url = new URL(serverUrl("/0"));
            this.downloadedFile = (File) TestUtil.invokePrivate(this.deploymentAgent, "getFileFromRemote",
                    new Class<?>[] { URL.class }, url);
        } catch (Throwable e) {
            this.occurredException = e;
        }
    }

    private void thenNoExceptionOccurred() {
        assertNull(this.occurredException);
    }

    private void thenExceptionOccurred(Class<? extends Throwable> expected) {
        assertTrue("unexpected exception: " + this.occurredException, expected.isInstance(this.occurredException));
    }

    private void thenDownloadedFileContainsPackage() throws IOException {
        assertArrayEquals(PACKAGE_CONTENT, Files.readAllBytes(this.downloadedFile.toPath()));
    }

    private void thenNoFileDownloaded() {
        assertNull(this.downloadedFile);
    }

    private void thenRequestCountIs(int expected) {
        assertEquals(expected, server.retrieveRecordedRequests(request()).length);
    }

    /*
     * Utilities
     */

    private static void addRedirect(String path, String location) {
        server.when(request().withMethod("GET").withPath(path))
                .respond(response().withStatusCode(302).withHeader("Location", serverUrl(location)));
    }

    private static String serverUrl(String path) {
        return "http://localhost:" + server.getLocalPort() + path;
    }
}
