/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_codeminders_hidapi_HIDDeviceInfo */

#ifndef _Included_com_codeminders_hidapi_HIDDeviceInfo
#define _Included_com_codeminders_hidapi_HIDDeviceInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_codeminders_hidapi_HIDDeviceInfo
 * Method:    open
 * Signature: ()Lcom/codeminders/hidapi/HIDDevice;
 */
JNIEXPORT jobject JNICALL Java_com_codeminders_hidapi_HIDDeviceInfo_open
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
