/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 * Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.internal.wire.fifo;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.locks.ReentrantLock;

import org.eclipse.kura.core.testutil.TestUtil;
import org.eclipse.kura.type.TypedValue;
import org.eclipse.kura.type.TypedValues;
import org.eclipse.kura.wire.WireEnvelope;
import org.eclipse.kura.wire.WireHelperService;
import org.eclipse.kura.wire.WireRecord;
import org.eclipse.kura.wire.WireSupport;
import org.junit.After;
import org.junit.Test;
import org.osgi.service.component.ComponentContext;
import org.osgi.service.wireadmin.Wire;

public class StopFifoTest {

    private static final long TIMEOUT_SECONDS = 10;

    private final Fifo fifo = new Fifo();
    private final CountDownLatch emitStarted = new CountDownLatch(1);
    private final CountDownLatch releaseEmit = new CountDownLatch(1);
    private Thread emitterThread;
    private Thread blockedSubmitter;

    /*
     * Scenarios
     */

    @Test
    public void deactivationReleasesBlockedSubmitterAndStopsEmitter() throws Exception {
        givenBlockingFifoWithCapacity(1);
        givenEmitterBusyWithFirstEnvelope();
        givenQueueFull();
        givenSubmitterBlockedOnFullQueue();

        whenFifoIsDeactivated();
        whenEmitterFinishesCurrentEnvelope();

        thenBlockedSubmitterReturns();
        thenEmitterThreadTerminates();
        thenEmitterLockIsReleased();
    }

    @After
    public void tearDown() {
        this.releaseEmit.countDown();
    }

    /*
     * Steps
     */

    private void givenBlockingFifoWithCapacity(int capacity) throws NoSuchFieldException {
        final WireHelperService wireHelperService = mock(WireHelperService.class);
        when(wireHelperService.newWireSupport(any(), any())).thenReturn(new BlockingWireSupport());
        this.fifo.bindWireHelperService(wireHelperService);

        final Map<String, Object> properties = new HashMap<>();
        properties.put("discard.envelopes", false);
        properties.put("queue.capacity", capacity);
        this.fifo.activate(properties, mock(ComponentContext.class));
        this.emitterThread = (Thread) TestUtil.getFieldValue(this.fifo, "emitterThread");
    }

    private void givenEmitterBusyWithFirstEnvelope() throws InterruptedException {
        this.fifo.onWireReceive(envelope());
        assertTrue("emitter did not start", this.emitStarted.await(TIMEOUT_SECONDS, TimeUnit.SECONDS));
    }

    private void givenQueueFull() {
        this.fifo.onWireReceive(envelope());
    }

    private void givenSubmitterBlockedOnFullQueue() throws InterruptedException {
        this.blockedSubmitter = new Thread(() -> this.fifo.onWireReceive(envelope()));
        this.blockedSubmitter.start();

        final long deadline = System.nanoTime() + TimeUnit.SECONDS.toNanos(TIMEOUT_SECONDS);
        while (this.blockedSubmitter.getState() != Thread.State.WAITING && System.nanoTime() < deadline) {
            this.blockedSubmitter.join(10);
        }
        assertEquals("submitter is not blocked", Thread.State.WAITING, this.blockedSubmitter.getState());
    }

    private void whenFifoIsDeactivated() {
        this.fifo.deactivate();
    }

    private void whenEmitterFinishesCurrentEnvelope() {
        this.releaseEmit.countDown();
    }

    private void thenBlockedSubmitterReturns() throws InterruptedException {
        this.blockedSubmitter.join(TimeUnit.SECONDS.toMillis(TIMEOUT_SECONDS));
        assertFalse("submitter still blocked", this.blockedSubmitter.isAlive());
    }

    private void thenEmitterThreadTerminates() throws InterruptedException {
        this.emitterThread.join(TimeUnit.SECONDS.toMillis(TIMEOUT_SECONDS));
        assertFalse("emitter thread still running", this.emitterThread.isAlive());
    }

    private void thenEmitterLockIsReleased() throws NoSuchFieldException {
        assertFalse(((ReentrantLock) TestUtil.getFieldValue(this.emitterThread, "lock")).isLocked());
    }

    /*
     * Utilities
     */

    private static WireEnvelope envelope() {
        final Map<String, TypedValue<?>> properties = Collections.singletonMap("key",
                TypedValues.newStringValue("value"));
        return new WireEnvelope("emitter", Collections.singletonList(new WireRecord(properties)));
    }

    private class BlockingWireSupport implements WireSupport {

        @Override
        public void emit(List<WireRecord> wireRecords) {
            StopFifoTest.this.emitStarted.countDown();
            try {
                StopFifoTest.this.releaseEmit.await(TIMEOUT_SECONDS, TimeUnit.SECONDS);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            }
        }

        @Override
        public void updated(Wire wire, Object value) {
            // not used
        }

        @Override
        public void producersConnected(Wire[] wires) {
            // not used
        }

        @Override
        public Object polled(Wire wire) {
            return null;
        }

        @Override
        public void consumersConnected(Wire[] wires) {
            // not used
        }
    }
}
