/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 * Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.net.admin.modem;

import static org.junit.Assert.assertTrue;
import static org.mockito.Mockito.CALLS_REAL_METHODS;
import static org.mockito.Mockito.mock;

import java.lang.reflect.Method;
import java.util.concurrent.TimeUnit;

import org.eclipse.kura.net.admin.modem.sierra.mc87xx.SierraMc87xx;
import org.eclipse.kura.net.admin.modem.sierra.usb598.SierraUsb598;
import org.eclipse.kura.net.admin.modem.telit.generic.TelitModem;
import org.junit.After;
import org.junit.Test;

public class ModemSleepInterruptTest {

    private static final long SLEEP_MILLIS = TimeUnit.SECONDS.toMillis(30);

    private Object modem;
    private Class<?> modemClass;
    private long elapsedMillis;
    private boolean interruptedAfterSleep;

    /*
     * Scenarios
     */

    @Test
    public void sierraMc87xxSleepKeepsInterruptStatus() throws Exception {
        givenModem(SierraMc87xx.class);
        givenCurrentThreadInterrupted();

        whenModemSleeps();

        thenSleepReturnedImmediately();
        thenInterruptStatusIsPreserved();
    }

    @Test
    public void sierraUsb598SleepKeepsInterruptStatus() throws Exception {
        givenModem(SierraUsb598.class);
        givenCurrentThreadInterrupted();

        whenModemSleeps();

        thenSleepReturnedImmediately();
        thenInterruptStatusIsPreserved();
    }

    @Test
    public void telitModemSleepKeepsInterruptStatus() throws Exception {
        givenModem(TelitModem.class);
        givenCurrentThreadInterrupted();

        whenModemSleeps();

        thenSleepReturnedImmediately();
        thenInterruptStatusIsPreserved();
    }

    @After
    public void clearInterruptStatus() {
        Thread.interrupted();
    }

    /*
     * Steps
     */

    private void givenModem(Class<?> modemClass) {
        this.modemClass = modemClass;
        this.modem = mock(modemClass, CALLS_REAL_METHODS);
    }

    private void givenCurrentThreadInterrupted() {
        Thread.currentThread().interrupt();
    }

    private void whenModemSleeps() throws Exception {
        final Method sleep = this.modemClass.getDeclaredMethod("sleep", long.class);
        sleep.setAccessible(true);

        final long start = System.nanoTime();
        sleep.invoke(this.modem, SLEEP_MILLIS);
        this.elapsedMillis = TimeUnit.NANOSECONDS.toMillis(System.nanoTime() - start);
        this.interruptedAfterSleep = Thread.currentThread().isInterrupted();
    }

    private void thenSleepReturnedImmediately() {
        assertTrue("sleep took " + this.elapsedMillis + " ms", this.elapsedMillis < SLEEP_MILLIS / 2);
    }

    private void thenInterruptStatusIsPreserved() {
        assertTrue(this.interruptedAfterSleep);
    }
}
