/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.internal.rest.auth.dto;

import org.eclipse.kura.request.handler.jaxrs.DefaultExceptionHandler;

import jakarta.ws.rs.core.Response.Status;

public class RefreshTokenDTO {

    private String refreshToken;

    public String getRefreshToken() {
        return refreshToken;
    }

    public void setRefreshToken(final String refreshToken) {
        this.refreshToken = refreshToken;
    }

    public void validate() {
        if (this.refreshToken == null || this.refreshToken.trim().isEmpty()) {
            throw DefaultExceptionHandler.buildWebApplicationException(Status.BAD_REQUEST, "refreshToken is required");
        }
    }
}
