/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.internal.rest.auth.dto;

import org.eclipse.kura.identity.TokenPair;

public class TokenAuthenticationResponseDTO {

    private final String accessToken;
    private final String refreshToken;
    private final long accessTokenExpiresAt;
    private final long refreshTokenExpiresAt;
    private final String tokenFamilyId;
    private final boolean passwordChangeNeeded;
    private final String message;

    public TokenAuthenticationResponseDTO(final TokenPair tokenPair, final boolean passwordChangeNeeded) {
        this(tokenPair, passwordChangeNeeded, null);
    }

    public TokenAuthenticationResponseDTO(final TokenPair tokenPair, final boolean passwordChangeNeeded,
            final String message) {
        this.accessToken = tokenPair.getAccessToken();
        this.refreshToken = tokenPair.getRefreshToken();
        this.accessTokenExpiresAt = tokenPair.getAccessTokenExpiresAt();
        this.refreshTokenExpiresAt = tokenPair.getRefreshTokenExpiresAt();
        this.tokenFamilyId = tokenPair.getTokenFamilyId();
        this.passwordChangeNeeded = passwordChangeNeeded;
        this.message = message;
    }

    public String getAccessToken() {
        return accessToken;
    }

    public String getRefreshToken() {
        return refreshToken;
    }

    public long getAccessTokenExpiresAt() {
        return accessTokenExpiresAt;
    }

    public long getRefreshTokenExpiresAt() {
        return refreshTokenExpiresAt;
    }

    public String getTokenFamilyId() {
        return tokenFamilyId;
    }

    public boolean isPasswordChangeNeeded() {
        return passwordChangeNeeded;
    }

    public String getMessage() {
        return message;
    }
}
