/*******************************************************************************
 * Copyright (c) 2011, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.data;

import java.util.List;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.function.Consumer;

import org.eclipse.kura.data.listener.DataServiceListener;
import org.osgi.service.component.ComponentContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/*
 * The following represents an exception to Semantic Versioning conventions.
 * Though the class implements the org.eclipse.kura.data.listener.DataServiceListener API,
 * it is actually an API consumer (it calls into the API implementors).
 */
class DataServiceListenerS implements DataServiceListener {

    private static final Logger logger = LoggerFactory.getLogger(DataServiceListenerS.class);

    private static final String DATA_SERVICE_LISTENER_REFERENCE = "DataServiceListener";

    private final ComponentContext ctx;
    private final List<DataServiceListener> listeners;

    public DataServiceListenerS(ComponentContext ctx) {
        this.ctx = ctx;
        // thread-safe list implementation
        this.listeners = new CopyOnWriteArrayList<>();
    }

    @Override
    public void onConnectionEstablished() {
        notifyAll("onConnectionEstablished", org.eclipse.kura.data.DataServiceListener::onConnectionEstablished,
                DataServiceListener::onConnectionEstablished);
    }

    @Override
    public void onDisconnecting() {
        notifyAll("onDisconnecting", org.eclipse.kura.data.DataServiceListener::onDisconnecting,
                DataServiceListener::onDisconnecting);
    }

    @Override
    public void onDisconnected() {
        notifyAll("onDisconnected", org.eclipse.kura.data.DataServiceListener::onDisconnected,
                DataServiceListener::onDisconnected);
    }

    @Override
    public void onConnectionLost(Throwable cause) {
        notifyAll("onConnectionLost", service -> service.onConnectionLost(cause),
                listener -> listener.onConnectionLost(cause));
    }

    @Override
    public void onMessageArrived(String topic, byte[] payload, int qos, boolean retained) {
        notifyAll("onMessageArrived", service -> service.onMessageArrived(topic, payload, qos, retained),
                listener -> listener.onMessageArrived(topic, payload, qos, retained));
    }

    @Override
    public void onMessagePublished(int messageId, String topic) {
        notifyAll("onMessagePublished", service -> service.onMessagePublished(messageId, topic),
                listener -> listener.onMessagePublished(messageId, topic));
    }

    @Override
    public void onMessageConfirmed(int messageId, String topic) {
        notifyAll("onMessageConfirmed", service -> service.onMessageConfirmed(messageId, topic),
                listener -> listener.onMessageConfirmed(messageId, topic));
    }

    public void prepend(DataServiceListener listener) {
        this.listeners.add(0, listener);
    }

    public void add(DataServiceListener listener) {
        this.listeners.add(listener);
    }

    public void remove(DataServiceListener listener) {
        this.listeners.remove(listener);
    }

    private void notifyAll(final String event,
            final Consumer<org.eclipse.kura.data.DataServiceListener> serviceNotification,
            final Consumer<DataServiceListener> listenerNotification) {
        Object[] services = this.ctx.locateServices(DATA_SERVICE_LISTENER_REFERENCE);
        if (services != null) {
            for (Object service : services) {
                notifyIsolated(
                        () -> serviceNotification.accept((org.eclipse.kura.data.DataServiceListener) service));
            }
        } else {
            logger.debug("No registered listener services. Ignoring {}", event);
        }

        if (!this.listeners.isEmpty()) {
            for (DataServiceListener listener : this.listeners) {
                notifyIsolated(() -> listenerNotification.accept(listener));
            }
        } else {
            logger.warn("No registered listeners. Ignoring {}", event);
        }
    }

    // A failing listener must not prevent the notification of the others, nor propagate to the caller. LinkageError
    // is included because a listener provided by an updated or uninstalled bundle can fail with NoClassDefFoundError.
    // Virtual machine errors are not contained.
    private static void notifyIsolated(final Runnable notification) {
        try {
            notification.run();
        } catch (Exception | LinkageError e) {
            logger.warn("Unexpected exception from listener", e);
        }
    }
}
