/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 * Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.internal.wire.db.common;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import java.util.function.BiFunction;

import org.junit.After;
import org.junit.Test;

public class GetTableSizeTest {

    private static final String TABLE = "RECORDS";
    private static final BiFunction<String, Object[], String> FORMATTER = MessageFormat::format;

    private final CommonDbServiceProvider provider = new CommonDbServiceProvider();
    private Connection connection;
    private Integer tableSize;
    private Exception occurredException;

    /*
     * Scenarios
     */

    @Test
    public void returnsTheNumberOfRows() throws SQLException {
        givenDatabaseTableWithRows(3);

        whenTableSizeIsRequested();

        thenNoExceptionOccurred();
        thenTableSizeIs(3);
    }

    @Test
    public void returnsZeroForAnEmptyTable() throws SQLException {
        givenDatabaseTableWithRows(0);

        whenTableSizeIsRequested();

        thenNoExceptionOccurred();
        thenTableSizeIs(0);
    }

    @Test
    public void failsWhenTheCountQueryReturnsNoRow() throws SQLException {
        givenCountQueryReturningNoRow();

        whenTableSizeIsRequested();

        thenSqlExceptionOccurred();
    }

    @After
    public void tearDown() throws SQLException {
        if (this.connection != null) {
            this.connection.close();
        }
    }

    /*
     * Steps
     */

    private void givenDatabaseTableWithRows(int rows) throws SQLException {
        this.connection = DriverManager.getConnection("jdbc:h2:mem:tablesize" + System.nanoTime());
        try (Statement statement = this.connection.createStatement()) {
            statement.execute("CREATE TABLE " + TABLE + " (ID INT)");
            for (int i = 0; i < rows; i++) {
                statement.execute("INSERT INTO " + TABLE + " VALUES (" + i + ")");
            }
        }
    }

    private void givenCountQueryReturningNoRow() throws SQLException {
        final ResultSet resultSet = mock(ResultSet.class);
        when(resultSet.next()).thenReturn(false);
        final Statement statement = mock(Statement.class);
        when(statement.executeQuery(anyString())).thenReturn(resultSet);
        this.connection = mock(Connection.class);
        when(this.connection.createStatement()).thenReturn(statement);
    }

    private void whenTableSizeIsRequested() {
        try {
            this.tableSize = this.provider.getTableSize(TABLE, this.connection, FORMATTER);
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    private void thenNoExceptionOccurred() {
        assertNull(this.occurredException);
    }

    private void thenTableSizeIs(int expected) {
        assertEquals(Integer.valueOf(expected), this.tableSize);
    }

    private void thenSqlExceptionOccurred() {
        assertTrue("unexpected: " + this.occurredException, this.occurredException instanceof SQLException);
    }
}
