/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 * Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.linux.watchdog;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.List;

import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;

public class RebootCauseFileDirectoryTest {

    @Rule
    public TemporaryFolder folder = new TemporaryFolder();

    private File rebootCauseFile;

    @Test
    public void rebootCauseIsWrittenInNewDirectory() throws IOException {
        givenRebootCauseFileIn("new", "directory");

        whenRebootCauseIsWritten("watchdog");

        thenRebootCauseFileContains("watchdog");
        thenNoTemporaryFileIsLeft();
    }

    @Test
    public void rebootCauseIsNotWrittenWhenParentIsAFile() throws IOException {
        givenRegularFile("parent");
        givenRebootCauseFileIn("parent");

        whenRebootCauseIsWritten("watchdog");

        thenRebootCauseFileDoesNotExist();
    }

    /*
     * Steps
     */

    private void givenRegularFile(final String name) throws IOException {
        assertTrue(new File(this.folder.getRoot(), name).createNewFile());
    }

    private void givenRebootCauseFileIn(final String... directories) {
        File directory = this.folder.getRoot();
        for (final String name : directories) {
            directory = new File(directory, name);
        }
        this.rebootCauseFile = new File(directory, "reboot_cause");
    }

    private void whenRebootCauseIsWritten(final String cause) {
        new RebootCauseFileWriter(this.rebootCauseFile.getPath()).writeRebootCause(cause);
    }

    private void thenRebootCauseFileContains(final String cause) throws IOException {
        final List<String> lines = Files.readAllLines(this.rebootCauseFile.toPath(), StandardCharsets.UTF_8);
        assertEquals(2, lines.size());
        assertTrue(Long.parseLong(lines.get(0)) > 0);
        assertEquals(cause, lines.get(1));
    }

    private void thenNoTemporaryFileIsLeft() {
        assertArrayEquals(new String[] { "reboot_cause" }, this.rebootCauseFile.getParentFile().list());
    }

    private void thenRebootCauseFileDoesNotExist() {
        assertFalse(this.rebootCauseFile.exists());
    }
}
