/*******************************************************************************
 * Copyright (c) 2011, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *  Red Hat Inc
 *******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.web.server.servlet;

import static java.util.Objects.isNull;

import java.io.File;
import java.io.FileOutputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.UnsupportedEncodingException;
import java.net.URL;
import java.net.URLDecoder;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.stream.Collectors;

import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.fileupload.FileItem;
import org.apache.commons.fileupload.FileUploadException;
import org.apache.commons.fileupload.disk.DiskFileItem;
import org.apache.commons.fileupload.disk.DiskFileItemFactory;
import org.apache.commons.fileupload.servlet.FileCleanerCleanup;
import org.apache.commons.fileupload.servlet.ServletFileUpload;
import org.apache.commons.io.FileCleaningTracker;
import org.apache.commons.io.IOUtils;
import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.KuraException;
import org.eclipse.kura.command.PasswordCommandService;
import org.eclipse.kura.configuration.ComponentConfiguration;
import org.eclipse.kura.configuration.ConfigurationService;
import org.eclipse.kura.core.configuration.ComponentConfigurationImpl;
import org.eclipse.kura.core.configuration.XmlComponentConfigurations;
import org.eclipse.kura.executor.UnprivilegedExecutorService;
import org.eclipse.kura.deployment.agent.DeploymentAgentService;
import org.eclipse.kura.marshalling.Unmarshaller;
import org.eclipse.kura.rest.configuration.api.ComponentConfigurationList;
import org.eclipse.kura.rest.configuration.api.DTOUtil;
import org.eclipse.kura.system.SystemService;
import org.eclipse.kura.util.service.ServiceUtil;
import org.eclipse.kura.util.zip.UnZip;
import org.eclipse.kura.web.server.KuraRemoteServiceServlet;
import org.eclipse.kura.web.server.RequiredPermissions.Mode;
import org.eclipse.kura.web.server.util.AssetConfigValidator;
import org.eclipse.kura.web.server.util.ServiceLocator;
import org.eclipse.kura.web.shared.GwtKuraException;
import org.eclipse.kura.web.shared.GwtSafeHtmlUtils;
import org.eclipse.kura.web.shared.KuraPermission;
import org.eclipse.kura.web.shared.model.GwtConfigComponent;
import org.eclipse.kura.web.shared.model.GwtConfigParameter;
import org.eclipse.kura.web.shared.model.GwtXSRFToken;
import org.osgi.framework.Bundle;
import org.osgi.framework.BundleContext;
import org.osgi.framework.FrameworkUtil;
import org.osgi.framework.ServiceReference;
import org.osgi.service.metatype.MetaTypeInformation;
import org.osgi.service.metatype.MetaTypeService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.gson.Gson;

public class FileServlet extends AuditServlet {

    private static final String CANNOT_CLOSE_INPUT_STREAM = "Cannot close input stream";

    private static final String CANNOT_CLOSE_OUTPUT_STREAM = "Cannot close output stream";

    private static final String XSRF_TOKEN = "xsrfToken";

    private static final String ERROR_PARSING_THE_FILE_UPLOAD_REQUEST = "Error parsing the file upload request";

    private static final String ERROR_PARSING_QUERY_STRING = "Error parsing query string.";

    private static final String REQUEST_PATH_INFO_NOT_FOUND = "Request path info not found";

    private static final long serialVersionUID = -5016170117606322129L;

    private static Logger logger = LoggerFactory.getLogger(FileServlet.class);

    private static final String JAVA_IO_TMPDIR = "java.io.tmpdir";
    private static final String EXPECTED_1_FILE_PATTERN = "expected 1 file item but found {}";

    // Properties of the command service configuration
    private static final String COMMAND_ENABLE = "command.enable";
    private static final String COMMAND_WORKING_DIRECTORY = "command.working.directory";
    private static final String PRIVILEGED_COMMAND_SERVICE_ENABLE = "privileged.command.service.enable";

    private DiskFileItemFactory diskFileItemFactory;
    private FileCleaningTracker fileCleaningTracker;

    private final BundleContext bundleContext;

    public FileServlet() {
        super("UI FileServlet", "Handle upload request");
        this.bundleContext = FrameworkUtil.getBundle(FileServlet.class).getBundleContext();
    }

    @Override
    public void destroy() {
        super.destroy();

        logger.info("Servlet {} destroyed", getServletName());

        if (this.fileCleaningTracker != null) {
            logger.info("Number of temporary files tracked: {}", this.fileCleaningTracker.getTrackCount());
        }
    }

    @Override
    public void init() throws ServletException {
        super.init();

        logger.info("Servlet {} initialized", getServletName());

        ServletContext ctx = getServletContext();
        this.fileCleaningTracker = FileCleanerCleanup.getFileCleaningTracker(ctx);

        int sizeThreshold = getFileUploadInMemorySizeThreshold();
        File repository = new File(System.getProperty(JAVA_IO_TMPDIR));

        logger.info("DiskFileItemFactory.DEFAULT_SIZE_THRESHOLD: {}", DiskFileItemFactory.DEFAULT_SIZE_THRESHOLD);
        logger.info("DiskFileItemFactory: using size threshold of: {}", sizeThreshold);

        this.diskFileItemFactory = new DiskFileItemFactory(sizeThreshold, repository);
        this.diskFileItemFactory.setFileCleaningTracker(this.fileCleaningTracker);
    }

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        resp.setContentType("image/jpeg");

        String reqPathInfo = req.getPathInfo();

        if (reqPathInfo == null) {
            logger.error(REQUEST_PATH_INFO_NOT_FOUND);
            throw new ServletException(REQUEST_PATH_INFO_NOT_FOUND);
        }

        logger.debug("req.getRequestURI(): {}", req.getRequestURI());
        logger.debug("req.getRequestURL(): {}", req.getRequestURL());
        logger.debug("req.getPathInfo(): {}", req.getPathInfo());

        if (reqPathInfo.startsWith("/icon")) {
            doGetIcon(req, resp);
        } else {
            logger.error("Unknown request path info: {}", reqPathInfo);
            throw new ServletException("Unknown request path info: " + reqPathInfo);
        }
    }

    @Override
    protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        resp.setContentType("text/html");

        String reqPathInfo = req.getPathInfo();
        if (reqPathInfo == null) {
            logger.error(REQUEST_PATH_INFO_NOT_FOUND);
            throw new ServletException(REQUEST_PATH_INFO_NOT_FOUND);
        }

        if (reqPathInfo.startsWith("/deploy")) {
            KuraRemoteServiceServlet.requirePermissions(req, Mode.ALL, new String[] { KuraPermission.PACKAGES_ADMIN });
            doPostDeploy(req);
        } else if (reqPathInfo.equals("/configuration/snapshot")) {
            KuraRemoteServiceServlet.requirePermissions(req, Mode.ALL, new String[] { KuraPermission.ADMIN });
            doPostConfigurationSnapshot(req);
        } else if (reqPathInfo.equals("/command")) {
            KuraRemoteServiceServlet.requirePermissions(req, Mode.ALL, new String[] { KuraPermission.DEVICE });
            doPostCommand(req, resp);
        } else if (reqPathInfo.equals("/asset")) {
            KuraRemoteServiceServlet.requirePermissions(req, Mode.ALL, new String[] { KuraPermission.WIRES_ADMIN });
            doPostAsset(req, resp);
        } else {
            logger.error("Unknown request path info: {}", reqPathInfo);
            throw new ServletException("Unknown request path info: " + reqPathInfo);
        }

    }

    private void doGetIcon(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        String queryString = req.getQueryString();

        if (queryString == null) {
            logger.error(ERROR_PARSING_QUERY_STRING);
            throw new ServletException(ERROR_PARSING_QUERY_STRING);
        }

        // Parse the query string
        Map<String, String> pairs;
        try {
            pairs = parseQueryString(queryString);
        } catch (UnsupportedEncodingException e) {
            logger.error(ERROR_PARSING_QUERY_STRING, e);
            throw new ServletException("Error parsing query string: " + e.getLocalizedMessage());
        }

        // Check for malformed request
        if (pairs == null || pairs.size() != 1) {
            logger.error(ERROR_PARSING_QUERY_STRING);
            throw new ServletException(ERROR_PARSING_QUERY_STRING);
        }

        final boolean factories;
        final String pid;
        if (pairs.containsKey("factoryId")) {
            factories = true;
            pid = pairs.get("factoryId");
        } else {
            factories = false;
            pid = pairs.get("pid");
        }

        if (pid != null && pid.length() > 0) {
            Bundle[] bundles = this.bundleContext.getBundles();
            ServiceLocator locator = ServiceLocator.getInstance();

            final MetaTypeService mts;
            try {
                mts = locator.getService(MetaTypeService.class);
            } catch (GwtKuraException e) {
                logger.error("Error getting MetaTypeService", e);
                throw new ServletException("Error getting MetaTypeService", e);
            }

            // Iterate over bundles to find PID
            for (Bundle b : bundles) {
                MetaTypeInformation mti = mts.getMetaTypeInformation(b);

                if (mti == null) {
                    continue;
                }

                final String[] ids = factories ? mti.getFactoryPids() : mti.getPids();

                for (String p : ids) {
                    if (p.equals(pid)) {
                        try (InputStream is = mti.getObjectClassDefinition(pid, null).getIcon(32)) {
                            if (is == null) {
                                logger.error("Error reading icon file.");
                                throw new ServletException("Error reading icon file.");
                            }
                            try (OutputStream os = resp.getOutputStream()) {
                                IOUtils.copy(is, os);
                            }
                        }

                        // break for loop ... only send one icon
                        break;
                    }
                }
            }
        } else {
            logger.error(ERROR_PARSING_QUERY_STRING);
            throw new ServletException(ERROR_PARSING_QUERY_STRING);
        }

    }

    private Map<String, String> parseQueryString(String queryString) throws UnsupportedEncodingException {
        Map<String, String> qp = new HashMap<>();

        String[] pairs = queryString.split("&");
        for (String p : pairs) {
            int index = p.indexOf('=');
            qp.put(URLDecoder.decode(p.substring(0, index), StandardCharsets.UTF_8.name()),
                    URLDecoder.decode(p.substring(index + 1), StandardCharsets.UTF_8.name()));
        }
        return qp;
    }

    private void doPostCommand(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        UploadRequest upload = new UploadRequest(this.diskFileItemFactory);

        try {
            upload.parse(req);
        } catch (FileUploadException e) {
            logger.error(ERROR_PARSING_THE_FILE_UPLOAD_REQUEST);
            throw new ServletException(ERROR_PARSING_THE_FILE_UPLOAD_REQUEST);
        }

        // BEGIN XSRF - Servlet dependent code
        Map<String, String> formFields = upload.getFormFields();

        try {
            GwtXSRFToken token = new GwtXSRFToken(formFields.get(XSRF_TOKEN));
            KuraRemoteServiceServlet.checkXSRFToken(req, token);
        } catch (Exception e) {
            throw new ServletException("Security error: please retry this operation correctly.");
        }
        // END XSRF security check

        List<FileItem> fileItems = upload.getFileItems();

        try {
            if (!fileItems.isEmpty()) {
                unZipInCommandWorkingDirectory(fileItems.get(0));
            }
        } catch (IOException | ServletException | IllegalStateException e) {
            reportExtractionFailure(resp, e);
        } finally {
            for (FileItem fileItem : fileItems) {
                fileItem.delete();
            }
        }
    }

    private void unZipInCommandWorkingDirectory(FileItem archive) throws ServletException, IOException {
        final ServiceReference<PasswordCommandService> commandServiceReference = this.bundleContext
                .getServiceReference(PasswordCommandService.class);

        if (isNull(commandServiceReference)
                || !Boolean.TRUE.equals(commandServiceReference.getProperty(COMMAND_ENABLE))) {
            throw new ServletException("The command service is not enabled");
        }

        String workingDir = (String) commandServiceReference.getProperty(COMMAND_WORKING_DIRECTORY);
        if (isNull(workingDir) || workingDir.isEmpty() || !Files.isDirectory(Paths.get(workingDir))) {
            workingDir = System.getProperty(JAVA_IO_TMPDIR, "/tmp");
        }

        try (InputStream is = archive.getInputStream()) {
            if (Boolean.TRUE.equals(commandServiceReference.getProperty(PRIVILEGED_COMMAND_SERVICE_ENABLE))) {
                UnZip.unZip(is, workingDir);
            } else {
                UnZip.unZip(is, workingDir, unprivilegedExecutorService());
            }
        }
    }

    // The command tab shows the body of the response as the reason why the upload failed
    private static void reportExtractionFailure(HttpServletResponse resp, Exception e) throws IOException {
        String reason = e.getMessage() != null ? e.getMessage() : e.toString();
        logger.warn("Unable to extract the uploaded archive: {}", reason);

        resp.setStatus(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
        resp.setCharacterEncoding(StandardCharsets.UTF_8.name());
        resp.getWriter().write(GwtSafeHtmlUtils.htmlEscape(reason));
    }

    private static UnprivilegedExecutorService unprivilegedExecutorService() throws ServletException {
        try {
            return ServiceLocator.getInstance().getService(UnprivilegedExecutorService.class);
        } catch (GwtKuraException e) {
            throw new ServletException("Unable to locate the command executor service", e);
        }
    }

    private void doPostAsset(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        UploadRequest upload = new UploadRequest(this.diskFileItemFactory);
        List<String> errors = new ArrayList<>();

        HttpSession session = req.getSession(false);

        try {
            upload.parse(req);
        } catch (FileUploadException e) {
            errors.add(ERROR_PARSING_THE_FILE_UPLOAD_REQUEST);
            resp.getWriter().write("Error parsing the file upload request.");
            throw new IOException(e);
        }

        Map<String, String> formFields = upload.getFormFields();
        try {
            // BEGIN XSRF - Servlet dependent code
            GwtXSRFToken token = new GwtXSRFToken(formFields.get(XSRF_TOKEN));
            KuraRemoteServiceServlet.checkXSRFToken(req, token);
            // END XSRF security check

            List<FileItem> fileItems = upload.getFileItems();
            int fileItemsSize = fileItems.size();
            if (fileItemsSize != 1) {
                logger.error(EXPECTED_1_FILE_PATTERN, fileItemsSize);
                errors.add("Security error: please retry this operation.");
                throw new ServletException();
            }

            FileItem fileItem = fileItems.get(0);
            byte[] data = fileItem.get();
            String csvString = new String(data, StandardCharsets.UTF_8);
            String assetPid = formFields.get("assetPid");
            String driverPid = formFields.get("driverPid");
            Boolean nullValueAsEmptyString = Boolean.parseBoolean(formFields.get("doEmptyStringConversion"));

            List<GwtConfigParameter> parametersFromCsv = AssetConfigValidator.get().validateCsv(csvString, driverPid,
                    errors, nullValueAsEmptyString);

            final GwtConfigComponent config = new GwtConfigComponent();
            config.setParameters(parametersFromCsv);

            session.setAttribute("kura.csv.config." + assetPid, config);

        } catch (GwtKuraException e) {
            logger.error("Error updating device configuration", e);
            throw new ServletException(e);
        } catch (ServletException ex) {
            if (!errors.isEmpty()) {
                StringBuilder sb = new StringBuilder();
                errors.forEach(line -> sb.append(line).append("\n"));
                try {
                    resp.getWriter().write(sb.toString());
                } catch (Exception e) {
                    logger.error("Error while writing output", e);
                }
            } else {
                logger.error("Servlet exception.", ex);
            }
            throw ex;
        } catch (Exception ex2) {
            logger.warn("Security error: please retry this operation correctly.", ex2);
            resp.getWriter().write("Security error: please retry this operation.");
            throw ex2;
        }

    }

    private void doPostConfigurationSnapshot(HttpServletRequest req) throws ServletException {

        UploadRequest upload = new UploadRequest(this.diskFileItemFactory);

        try {
            upload.parse(req);
        } catch (FileUploadException e) {
            logger.error(ERROR_PARSING_THE_FILE_UPLOAD_REQUEST);
            throw new ServletException(ERROR_PARSING_THE_FILE_UPLOAD_REQUEST);
        }

        // BEGIN XSRF - Servlet dependent code
        Map<String, String> formFields = upload.getFormFields();

        try {
            GwtXSRFToken token = new GwtXSRFToken(formFields.get(XSRF_TOKEN));
            KuraRemoteServiceServlet.checkXSRFToken(req, token);
        } catch (Exception e) {
            throw new ServletException("Security error: please retry this operation correctly.", e);
        }
        // END XSRF security check

        List<FileItem> fileItems = upload.getFileItems();
        int fileItemsSize = fileItems.size();
        if (fileItemsSize != 1) {
            logger.error(EXPECTED_1_FILE_PATTERN, fileItemsSize);
            throw new ServletException("Wrong number of file items");
        }

        FileItem fileItem = fileItems.get(0);
        byte[] data = fileItem.get();
        String fileItemString = new String(data, StandardCharsets.UTF_8);

        final List<ComponentConfiguration> configImpls;

        String fileName = fileItem.getName();

        if (fileName != null) {
            fileName = fileName.toLowerCase();
        } else {
            fileName = "";
        }

        if (fileName.endsWith("xml")) {
            configImpls = parseXmlSnapshot(fileItemString);
        } else if (fileName.endsWith("json")) {
            configImpls = parseJsonSnapshot(fileItemString);
        } else {
            throw new ServletException("Unsupported content type");
        }

        ServiceLocator locator = ServiceLocator.getInstance();
        try {

            ConfigurationService cs = locator.getService(ConfigurationService.class);
            List<ComponentConfiguration> configs = new ArrayList<>();
            configs.addAll(configImpls);

            cs.updateConfigurations(configs);

            //
            // Add an additional delay after the configuration update
            // to give the time to the device to apply the received
            // configuration
            SystemService ss = locator.getService(SystemService.class);
            long delay = Long.parseLong(ss.getProperties().getProperty("console.updateConfigDelay", "5000"));
            if (delay > 0) {
                Thread.sleep(delay);
            }
        } catch (Exception e) {
            logger.error("Error updating device configuration");
            throw new ServletException("Error updating device configuration");
        }
    }

    private List<ComponentConfiguration> parseXmlSnapshot(String xmlString) throws ServletException {
        XmlComponentConfigurations xmlConfigs;
        try {
            xmlConfigs = unmarshal(xmlString, XmlComponentConfigurations.class);
        } catch (Exception e) {
            throw new ServletException("Error unmarshaling device configuration");
        }
        return xmlConfigs.getConfigurations();
    }

    private List<ComponentConfiguration> parseJsonSnapshot(String jsonString) throws ServletException {
        final ComponentConfigurationList configs;
        try {
            configs = new Gson().fromJson(jsonString, ComponentConfigurationList.class);
        } catch (Exception e) {
            throw new ServletException("Error unmarshaling device configuration");
        }
        return configs.getConfigs().stream().map(c -> new ComponentConfigurationImpl(c.getPid(), null,
                DTOUtil.dtosToConfigurationProperties(c.getProperties()))).collect(Collectors.toList());
    }

    private void doPostDeployUpload(HttpServletRequest req, HttpSession session) throws ServletException, IOException {
        ServiceLocator locator = ServiceLocator.getInstance();
        DeploymentAgentService deploymentAgentService;
        try {
            deploymentAgentService = locator.getService(DeploymentAgentService.class);
        } catch (GwtKuraException e) {
            logger.error("Error locating DeploymentAgentService");
            throw new ServletException("Error locating DeploymentAgentService", e);
        }

        // Check that we have a file upload request
        boolean isMultipart = ServletFileUpload.isMultipartContent(req);
        if (!isMultipart) {
            logger.error("Not a file upload request");
            throw new ServletException("Not a file upload request");
        }

        UploadRequest upload = new UploadRequest(this.diskFileItemFactory);

        try {
            upload.parse(req);
        } catch (FileUploadException e) {
            logger.error(ERROR_PARSING_THE_FILE_UPLOAD_REQUEST);
            throw new ServletException(ERROR_PARSING_THE_FILE_UPLOAD_REQUEST, e);
        }

        // BEGIN XSRF - Servlet dependent code
        Map<String, String> formFields = upload.getFormFields();

        try {
            GwtXSRFToken token = new GwtXSRFToken(formFields.get(XSRF_TOKEN));
            KuraRemoteServiceServlet.checkXSRFToken(req, token);
        } catch (Exception e) {
            throw new ServletException("Security error: please retry this operation correctly.", e);
        }
        // END XSRF security check

        List<FileItem> fileItems = null;
        InputStream is = null;
        File localFile = null;
        OutputStream os = null;
        boolean successful = false;

        try {
            fileItems = upload.getFileItems();

            int fileItemsSize = fileItems.size();
            if (fileItemsSize != 1) {
                logger.error(EXPECTED_1_FILE_PATTERN, fileItemsSize);
                throw new ServletException("Wrong number of file items");
            }

            FileItem item = fileItems.get(0);
            String filename = item.getName();
            is = item.getInputStream();

            String filePath = System.getProperty(JAVA_IO_TMPDIR) + File.separator + UUID.randomUUID() + ".dp";

            localFile = new File(filePath);
            if (localFile.exists() && !localFile.delete()) {
                logger.error("Cannot delete file: {}", filePath);
                throw new ServletException("Cannot delete file: " + filePath);
            }

            try {
                localFile.createNewFile();
                localFile.deleteOnExit();
            } catch (IOException e) {
                logger.error("Cannot create file: {}", filePath);
                throw new ServletException("Cannot create file: " + filePath);
            }

            try {
                os = new FileOutputStream(localFile);
            } catch (FileNotFoundException e) {
                logger.error("Cannot find file: {}", filePath);
                throw new ServletException("Cannot find file: " + filePath);
            }

            logger.info("Copying uploaded package file to file: {}", filePath);

            try {
                IOUtils.copy(is, os);
            } catch (IOException e) {
                logger.error("Failed to copy deployment package file: {}", filename);
                throw new ServletException("Failed to copy deployment package file: " + filename);
            }

            try {
                os.close();
            } catch (IOException e) {
                logger.warn(CANNOT_CLOSE_OUTPUT_STREAM, e);
            }

            URL url = localFile.toURI().toURL();
            String sUrl = url.toString();

            logger.info("Installing package...");
            try {
                deploymentAgentService.installDeploymentPackageAsync(sUrl);
                successful = true;
            } catch (Exception e) {
                logger.error("Package installation failed");
                throw new ServletException("Package installation failed", e);
            }

        } finally {
            if (os != null) {
                try {
                    os.close();
                } catch (IOException e) {
                    logger.warn(CANNOT_CLOSE_OUTPUT_STREAM, e);
                }
            }
            if (localFile != null && !successful) {
                try {
                    localFile.delete();
                } catch (Exception e) {
                    logger.warn("Cannot delete file");
                }
            }
            if (is != null) {
                try {
                    is.close();
                } catch (IOException e) {
                    logger.warn(CANNOT_CLOSE_INPUT_STREAM, e);
                }
            }
            if (fileItems != null) {
                for (FileItem fileItem : fileItems) {
                    fileItem.delete();
                }
            }
        }
    }

    private void doPostDeploy(HttpServletRequest req) throws ServletException, IOException {

        ServiceLocator locator = ServiceLocator.getInstance();
        DeploymentAgentService deploymentAgentService;
        try {
            deploymentAgentService = locator.getService(DeploymentAgentService.class);
        } catch (GwtKuraException e) {
            logger.error("Error locating DeploymentAgentService");
            throw new ServletException("Error locating DeploymentAgentService", e);
        }

        HttpSession session = req.getSession(false);

        String reqPathInfo = req.getPathInfo();
        if (reqPathInfo.endsWith("url")) {

            String packageDownloadUrl = req.getParameter("packageUrl");
            if (packageDownloadUrl == null) {
                logger.error("Deployment package URL parameter missing");
                throw new ServletException("Deployment package URL parameter missing");
            }

            // BEGIN XSRF - Servlet dependent code
            String tokenId = req.getParameter(XSRF_TOKEN);

            try {
                GwtXSRFToken token = new GwtXSRFToken(tokenId);
                KuraRemoteServiceServlet.checkXSRFToken(req, token);
            } catch (Exception e) {
                throw new ServletException("Security error: please retry this operation correctly.", e);
            }
            // END XSRF security check

            try {
                logger.info("Installing package...");
                deploymentAgentService.installDeploymentPackageAsync(packageDownloadUrl);
            } catch (Exception e) {
                logger.error("Failed to install package at URL {}", packageDownloadUrl);
                throw new ServletException("Error installing deployment package", e);
            }

        } else if (reqPathInfo.endsWith("upload")) {
            doPostDeployUpload(req, session);
        } else {
            logger.error("Unsupported package deployment request");
            throw new ServletException("Unsupported package deployment request");
        }
    }

    static long getFileUploadSizeMax() {
        ServiceLocator locator = ServiceLocator.getInstance();

        long sizeMax = -1;
        try {
            SystemService systemService = locator.getService(SystemService.class);
            sizeMax = Long.parseLong(systemService.getProperties().getProperty("file.upload.size.max", "-1"));
        } catch (GwtKuraException e) {
            logger.error("Error locating SystemService", e);
        }

        return sizeMax;
    }

    private static int getFileUploadInMemorySizeThreshold() {
        ServiceLocator locator = ServiceLocator.getInstance();

        int sizeThreshold = DiskFileItemFactory.DEFAULT_SIZE_THRESHOLD;
        try {
            SystemService systemService = locator.getService(SystemService.class);
            sizeThreshold = Integer
                    .parseInt(systemService.getProperties().getProperty("file.upload.in.memory.size.threshold",
                            String.valueOf(DiskFileItemFactory.DEFAULT_SIZE_THRESHOLD)));
        } catch (GwtKuraException e) {
            logger.error("Error locating SystemService", e);
        }

        return sizeThreshold;
    }

    private ServiceReference<Unmarshaller>[] getXmlUnmarshallers() {
        String filterString = String.format("(&(kura.service.pid=%s))",
                "org.eclipse.kura.xml.marshaller.unmarshaller.provider");
        return ServiceUtil.getServiceReferences(FrameworkUtil.getBundle(FileServlet.class).getBundleContext(),
                Unmarshaller.class, filterString);
    }

    private void ungetServiceReferences(final ServiceReference<?>[] refs) {
        ServiceUtil.ungetServiceReferences(FrameworkUtil.getBundle(FileServlet.class).getBundleContext(), refs);
    }

    protected <T> T unmarshal(String xmlString, Class<T> clazz) throws KuraException {
        T result = null;
        ServiceReference<Unmarshaller>[] unmarshallerSRs = getXmlUnmarshallers();
        try {
            for (final ServiceReference<Unmarshaller> unmarshallerSR : unmarshallerSRs) {
                Unmarshaller unmarshaller = FrameworkUtil.getBundle(FileServlet.class).getBundleContext()
                        .getService(unmarshallerSR);
                result = unmarshaller.unmarshal(xmlString, clazz);
            }
        } catch (Exception e) {
            logger.warn("Failed to extract persisted configuration.");
        } finally {
            ungetServiceReferences(unmarshallerSRs);
        }
        if (result == null) {
            throw new KuraException(KuraErrorCode.DECODER_ERROR, "configuration");
        }
        return result;
    }
}

class UploadRequest extends ServletFileUpload {

    private static Logger logger = LoggerFactory.getLogger(UploadRequest.class);

    Map<String, String> formFields;
    List<FileItem> fileItems;

    public UploadRequest(DiskFileItemFactory diskFileItemFactory) {
        super(diskFileItemFactory);
        setSizeMax(FileServlet.getFileUploadSizeMax());
        // contrary to what the name says, this method does not set the number of
        // allowed files but the number of parts
        // (files and fields)
        setFileCountMax(10L);
        this.formFields = new HashMap<>();
        this.fileItems = new ArrayList<>();
    }

    public void parse(HttpServletRequest req) throws FileUploadException {

        logger.debug("upload.getFileSizeMax(): {}", getFileSizeMax());
        logger.debug("upload.getSizeMax(): {}", getSizeMax());

        // Parse the request
        List<FileItem> items = null;
        items = parseRequest(req);

        // Process the uploaded items
        Iterator<FileItem> iter = items.iterator();
        while (iter.hasNext()) {
            FileItem item = iter.next();

            if (item.isFormField()) {
                String name = item.getFieldName();
                String value = item.getString();

                logger.debug("Form field item name: {}, value: {}", name, value);

                this.formFields.put(name, value);
            } else {
                String fieldName = item.getFieldName();
                String fileName = item.getName();
                String contentType = item.getContentType();
                boolean isInMemory = item.isInMemory();
                long sizeInBytes = item.getSize();

                logger.debug("File upload item name: {}, fileName: {}, contentType: {}, isInMemory: {}, size: {}",
                        new Object[] { fieldName, fileName, contentType, isInMemory, sizeInBytes });

                this.fileItems.add(item);
            }
        }
    }

    public Map<String, String> getFormFields() {
        return this.formFields;
    }

    public List<FileItem> getFileItems() {
        return this.fileItems;
    }
}
