/*******************************************************************************
 * Copyright (c) 2021, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.testutil.requesthandler;

import java.io.IOException;
import java.net.InetSocketAddress;
import java.net.ServerSocket;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import java.util.Random;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;

import org.eclipse.kura.KuraException;
import org.eclipse.kura.configuration.ConfigurationService;
import org.eclipse.kura.core.data.util.MqttTopicUtil;
import org.eclipse.kura.core.testutil.service.ServiceUtil;
import org.eclipse.kura.data.DataTransportService;
import org.eclipse.kura.data.DataTransportToken;
import org.eclipse.kura.data.transport.listener.DataTransportListener;
import org.eclipse.kura.marshalling.Marshaller;
import org.eclipse.kura.marshalling.Unmarshaller;
import org.eclipse.kura.message.KuraPayload;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import io.moquette.broker.Server;
import io.moquette.broker.config.FluentConfig;
import io.moquette.broker.config.IConfig;

public class MqttTransport implements Transport {

    private static final Logger logger = LoggerFactory.getLogger(MqttTransport.class);

    private static final String MQTT_DATA_TRANSPORT_FACTORY_PID = "org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport";

    private static final String DEFAULT_CLOUD_SERVICE_PID = "org.eclipse.kura.cloud.CloudService";
    private static final String DEFAULT_MQTT_DATA_TRANSPORT_SERVICE_PID = "org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport";
    private static final int DEFAULT_MQTT_BROKER_PORT = 1883;

    private static Server mqttBroker;
    private static int mqttBrokerPort = DEFAULT_MQTT_BROKER_PORT;

    private DataTransportInspector observerInspector;

    private Marshaller jsonMarshaller;
    private Unmarshaller jsonUnmarshaller;

    private String appId;

    private AtomicBoolean initialized = new AtomicBoolean(false);

    public MqttTransport(final String appId) {
        this.appId = appId;
    }

    @Override
    public void init() {
        if (!initialized.compareAndSet(false, true)) {
            return;
        }

        try {
            startMoquetteBroker();

            final ConfigurationService configurationService = ServiceUtil
                    .trackService(ConfigurationService.class, Optional.empty()).get(1, TimeUnit.MINUTES);
            final DataTransportService mqttDataTransport = ServiceUtil
                    .trackService(DataTransportService.class, Optional.empty()).get(1, TimeUnit.MINUTES);
            jsonMarshaller = ServiceUtil
                    .trackService(Marshaller.class,
                            Optional.of("(kura.service.pid=org.eclipse.kura.json.marshaller.unmarshaller.provider)"))
                    .get(1, TimeUnit.MINUTES);
            jsonUnmarshaller = ServiceUtil
                    .trackService(Unmarshaller.class,
                            Optional.of("(kura.service.pid=org.eclipse.kura.json.marshaller.unmarshaller.provider)"))
                    .get(1, TimeUnit.MINUTES);

            ServiceUtil.updateComponentConfiguration(configurationService, DEFAULT_MQTT_DATA_TRANSPORT_SERVICE_PID,
                    getConfigForLocalBroker("test")).get(30, TimeUnit.SECONDS);

            final Map<String, Object> cloudServiceProperties = new HashMap<>();
            cloudServiceProperties.put("payload.encoding", "simple-json");
            /*
             * Set a control topic without $ as prefix: some brokers do not allow access to topics starting with $ (like
             * moquette, mosquitto)
             */
            cloudServiceProperties.put("topic.control-prefix", "EDC");

            ServiceUtil.updateComponentConfiguration(configurationService, DEFAULT_CLOUD_SERVICE_PID,
                    cloudServiceProperties).get(30, TimeUnit.SECONDS);

            final DataTransportService observer = getOrCreateObserverTransport(configurationService);
            observerInspector = new DataTransportInspector(observer, true);
            new DataTransportInspector(mqttDataTransport, false);

            ensureConnected(mqttDataTransport);
            ensureConnected(observer);

        } catch (final Exception e) {
            initialized.set(false);
            throw new RuntimeException(e);
        }
    }

    private void ensureConnected(final DataTransportService dataTransportService) throws Exception {
        if (dataTransportService.isConnected()) {
            return;
        }

        Exception lastException = null;

        for (int attempt = 0; attempt < 8; attempt++) {
            if (dataTransportService.isConnected()) {
                return;
            }

            try {
                dataTransportService.connect();
            } catch (final Exception e) {
                if (dataTransportService.isConnected() || isAlreadyConnectedError(e)) {
                    return;
                }
                lastException = e;
            }

            if (waitUntilConnected(dataTransportService, 15, TimeUnit.SECONDS)) {
                return;
            }

            lastException = new IllegalStateException("Unable to connect data transport service");

            TimeUnit.MILLISECONDS.sleep(500);
        }

        if (lastException != null) {
            throw lastException;
        }

        throw new IllegalStateException("Unable to connect data transport service");
    }

    private boolean waitUntilConnected(final DataTransportService dataTransportService, final long timeout,
            final TimeUnit timeoutUnit) throws InterruptedException {
        final long deadline = System.nanoTime() + timeoutUnit.toNanos(timeout);

        while (System.nanoTime() < deadline) {
            if (dataTransportService.isConnected()) {
                return true;
            }

            TimeUnit.MILLISECONDS.sleep(100);
        }

        return dataTransportService.isConnected();
    }

    private boolean isAlreadyConnectedError(final Throwable throwable) {
        Throwable current = throwable;

        while (current != null) {
            final String message = current.getMessage();

            if (message != null && message.toLowerCase().contains("already connected")) {
                return true;
            }

            current = current.getCause();
        }

        return false;
    }

    private DataTransportService getOrCreateObserverTransport(final ConfigurationService configurationService)
            throws Exception {
        final String observerPid = "observer-" + this.appId;
        final Map<String, Object> observerConfiguration = getConfigForLocalBroker(observerPid);

        try {
            return createObserverTransport(configurationService, observerPid, observerConfiguration);
        } catch (final Exception e) {
            if (!isAlreadyExistingPid(e)) {
                throw e;
            }
        }

        ServiceUtil.deleteFactoryConfiguration(configurationService, observerPid).get(30, TimeUnit.SECONDS);

        return createObserverTransport(configurationService, observerPid, observerConfiguration);
    }

    private DataTransportService createObserverTransport(final ConfigurationService configurationService,
            final String observerPid, final Map<String, Object> observerConfiguration) throws Exception {
        return ServiceUtil
                .createFactoryConfiguration(configurationService, DataTransportService.class, observerPid,
                        MQTT_DATA_TRANSPORT_FACTORY_PID, observerConfiguration)
                .get(30, TimeUnit.SECONDS);
    }

    private boolean isAlreadyExistingPid(final Throwable throwable) {
        Throwable current = throwable;

        while (current != null) {
            final String message = current.getMessage();

            if (message != null && message.contains("already exists")) {
                return true;
            }

            current = current.getCause();
        }

        return false;
    }

    @Override
    public Response runRequest(String resource, MethodSpec method) {
        return runRequest(resource, method, null);
    }

    @Override
    public Response runRequest(String resource, MethodSpec method, String requestBody) {
        try {
            final KuraPayload requestPayload = new KuraPayload();

            if (requestBody != null) {
                requestPayload.setBody(requestBody.getBytes(StandardCharsets.UTF_8));
            }

            final KuraPayload response = observerInspector.runRequest(adaptResource(resource, method), requestPayload)
                    .get(10, TimeUnit.SECONDS);

            final int status = (int) (long) response.getMetric("response.code");
            final Optional<String> body = Optional.ofNullable(response.getBody())
                    .map(s -> new String(s, StandardCharsets.UTF_8));

            return new Response(status, body);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    private String adaptResource(final String resource, final MethodSpec method) {
        return method.getRequestHandlerMethod() + resource;
    }

    private Map<String, Object> getConfigForLocalBroker(final String clientId) throws KuraException {
        final Map<String, Object> properties = new HashMap<>();

        properties.put("broker-url", "mqtt://localhost:" + mqttBrokerPort + "/");
        properties.put("username", "mqtt");
        properties.put("client-id", clientId);
        properties.put("topic.context.account-name", "mqtt");

        return properties;
    }

    private static void startMoquetteBroker() throws IOException {
        if (mqttBroker != null) {
            logger.info("Moquette broker already running");
            return;
        }

        RuntimeException startException = null;

        for (int attempt = 0; attempt < 3; attempt++) {
            mqttBrokerPort = findAvailablePort(mqttBrokerPort);

            final IConfig brokerConfig = new FluentConfig().port(mqttBrokerPort).host("0.0.0.0").disablePersistence()
                    .build();
            brokerConfig.setProperty(IConfig.NETTY_MAX_BYTES_PROPERTY_NAME, "16777216");

            try {
                mqttBroker = new Server();
                mqttBroker.startServer(brokerConfig);
                Runtime.getRuntime().addShutdownHook(new Thread(MqttTransport::stopMoquetteBroker));
                logger.info("Moquette broker started on port {}", mqttBrokerPort);
                return;
            } catch (final RuntimeException e) {
                startException = e;
                mqttBroker = null;

                if (!isAddressInUse(e)) {
                    throw e;
                }
            }
        }

        if (startException != null) {
            throw startException;
        }
    }

    private static boolean isAddressInUse(final Throwable throwable) {
        Throwable current = throwable;

        while (current != null) {
            if (current instanceof java.net.BindException) {
                return true;
            }

            current = current.getCause();
        }

        return false;
    }

    private static int findAvailablePort(final int preferredPort) throws IOException {
        if (isPortAvailable(preferredPort)) {
            return preferredPort;
        }

        try (ServerSocket socket = new ServerSocket(0)) {
            return socket.getLocalPort();
        }
    }

    private static boolean isPortAvailable(final int port) {
        try (ServerSocket socket = new ServerSocket()) {
            socket.setReuseAddress(true);
            socket.bind(new InetSocketAddress("0.0.0.0", port));
            return true;
        } catch (final IOException e) {
            return false;
        }
    }

    private static void stopMoquetteBroker() {
        if (mqttBroker != null) {
            mqttBroker.stopServer();
            mqttBroker = null;
            logger.info("Moquette broker stopped");
        }
    }

    private class DataTransportInspector {

        private final DataTransportService dataTransportService;
        private final Random random = new Random();

        private Optional<CompletableFuture<Void>> disconnectFuture = Optional.empty();
        private Optional<MessageLookup> messageLookup = Optional.empty();

        DataTransportInspector(final DataTransportService dataTransportService, final boolean subscribe) {
            this.dataTransportService = dataTransportService;

            dataTransportService.addDataTransportListener(new DataTransportListener() {

                @Override
                public void onConnectionEstablished(boolean newSession) {
                    if (subscribe) {
                        try {
                            dataTransportService.subscribe("#", 0);
                        } catch (Exception e) {
                            logger.warn("failed to subscribe", e);
                        }
                    }
                }

                @Override
                public void onDisconnecting() {
                    // do nothing
                }

                @Override
                public void onDisconnected() {
                    if (disconnectFuture.isPresent()) {
                        disconnectFuture.get().complete(null);
                    }
                    disconnectFuture = Optional.empty();
                }

                @Override
                public void onConfigurationUpdating(boolean wasConnected) {
                    // do nothing

                }

                @Override
                public void onConfigurationUpdated(boolean wasConnected) {
                    // do nothing
                }

                @Override
                public void onConnectionLost(Throwable cause) {
                    if (disconnectFuture.isPresent()) {
                        disconnectFuture.get().complete(null);
                    }
                    disconnectFuture = Optional.empty();
                }

                @Override
                public void onMessageArrived(String topic, byte[] payload, int qos, boolean retained) {
                    if (!messageLookup.isPresent()) {
                        return;
                    }

                    final MessageLookup lookup = messageLookup.get();

                    if (MqttTopicUtil.isMatched(lookup.topicFilter, topic)) {
                        lookup.future.complete(payload);
                        messageLookup = Optional.empty();
                    }
                }

                @Override
                public void onMessageConfirmed(DataTransportToken token) {
                    // do nothing
                }

            });

            if (subscribe && dataTransportService.isConnected()) {
                try {
                    dataTransportService.subscribe("#", 0);
                } catch (Exception e) {
                    logger.warn("failed to subscribe", e);
                }
            }
        }

        private class MessageLookup {

            private final CompletableFuture<byte[]> future;
            private final String topicFilter;

            public MessageLookup(CompletableFuture<byte[]> future, String topicFilter) {
                this.future = future;
                this.topicFilter = topicFilter;
            }
        }

        CompletableFuture<KuraPayload> runRequest(final String resource, final KuraPayload request)
                throws KuraException {

            final String requestId = Integer.toString(random.nextInt());

            request.addMetric("requester.client.id", "test");
            request.addMetric("request.id", requestId);

            final byte[] data = jsonMarshaller.marshal(request).getBytes(StandardCharsets.UTF_8);

            final String topic = "EDC/mqtt/test/" + appId + "/" + resource;

            final CompletableFuture<byte[]> message = new CompletableFuture<>();

            this.messageLookup = Optional
                    .of(new MessageLookup(message, "EDC/mqtt/test/" + appId + "/REPLY/" + requestId));

            dataTransportService.publish(topic, data, 0, false);

            return message.thenApply(d -> {
                try {
                    return jsonUnmarshaller.unmarshal(new String(d), KuraPayload.class);
                } catch (final Exception e) {
                    throw new RuntimeException(e);
                }
            }).whenComplete((ok, ex) -> this.messageLookup = Optional.empty());

        }
    }

}
