/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.rest.provider.test.jwt;

import org.eclipse.kura.rest.provider.test.util.AbstractJwtRestScenario;
import org.junit.Test;

public class AccessTokenAuthenticationTest extends AbstractJwtRestScenario {

    @Test
    public void anAccessTokenGrantsAccessToAProtectedResource() throws Exception {
        givenAnIdentityWithPermissions(ASSETS_PERMISSION);
        givenATokenPairIssuedToTheIdentity();

        whenTheProtectedResourceIsAccessedWith(bearer(theAccessToken()));

        thenResponseCodeIs(200);
    }

    @Test
    public void aLowercaseBearerSchemeIsAccepted() throws Exception {
        givenAnIdentityWithPermissions(ASSETS_PERMISSION);
        givenATokenPairIssuedToTheIdentity();

        whenTheProtectedResourceIsAccessedWith(header("bearer " + theAccessToken()));

        thenResponseCodeIs(200);
    }

    @Test
    public void aMalformedBearerHeaderIsRejected() {

        whenTheProtectedResourceIsAccessedWith(header("Bearer"));

        thenResponseCodeIs(401);
    }

    @Test
    public void anAccessTokenDoesNotGrantPermissionsTheIdentityLacks() throws Exception {
        givenAnIdentityWithPermissions();
        givenATokenPairIssuedToTheIdentity();

        whenTheProtectedResourceIsAccessedWith(bearer(theAccessToken()));

        thenResponseCodeIs(403);
    }

    @Test
    public void aRefreshTokenIsNotAcceptedAsAnAccessToken() throws Exception {
        givenAnIdentityWithPermissions(ASSETS_PERMISSION);
        givenATokenPairIssuedToTheIdentity();

        whenTheProtectedResourceIsAccessedWith(bearer(theRefreshToken()));

        thenResponseCodeIs(401);
    }

    @Test
    public void anAccessTokenForgedForAnotherIdentityIsRejected() throws Exception {
        givenAnIdentityWithPermissions(ASSETS_PERMISSION);
        givenATokenPairIssuedToTheIdentity();

        whenTheProtectedResourceIsAccessedWith(bearer(theAccessTokenForgedFor("admin")));

        thenResponseCodeIs(401);
    }

    @Test
    public void anAccessTokenIsRejectedAfterTheIdentityIsDeleted() throws Exception {
        givenAnIdentityWithPermissions(ASSETS_PERMISSION);
        givenATokenPairIssuedToTheIdentity();
        givenTheIdentityIs(IdentityChange.DELETED);

        whenTheProtectedResourceIsAccessedWith(bearer(theAccessToken()));

        thenResponseCodeIs(401);
    }

    @Test
    public void anAccessTokenIsRejectedOnceTheIdentityMustChangeItsPassword() throws Exception {
        givenAnIdentityWithPermissions(ASSETS_PERMISSION);
        givenATokenPairIssuedToTheIdentity();
        givenTheIdentityIs(IdentityChange.REQUIRED_TO_CHANGE_PASSWORD);

        whenTheProtectedResourceIsAccessedWith(bearer(theAccessToken()));

        thenResponseCodeIs(401);
    }
}
