/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.rest.provider.test.jwt;

import java.time.Duration;
import java.util.Map;

import org.eclipse.kura.rest.provider.test.util.AbstractJwtRestScenario;
import org.junit.Test;

public class IssueTokenPairTest extends AbstractJwtRestScenario {

    @Test
    public void aTokenPairIsIssuedToAnIdentityAuthenticatedWithBasicCredentials() throws Exception {
        givenAnIdentityWithPermissions(ASSETS_PERMISSION);

        whenATokenPairIsRequestedWith(basic(IDENTITY));

        thenATokenPairIsReturned();
        thenResponseContainsHeader("Cache-Control", "no-store");
        thenResponseContainsHeader("Pragma", "no-cache");
    }

    @Test
    public void theTokensLastForTheConfiguredDurations() throws Exception {
        givenTheRestServiceProperties(Map.of(ACCESS_TOKEN_DURATION, 30, REFRESH_TOKEN_DURATION, 300));
        givenAnIdentityWithPermissions(ASSETS_PERMISSION);

        whenATokenPairIsRequestedWith(basic(IDENTITY));

        thenATokenPairIsReturned();
        thenTheTokensLast(Duration.ofSeconds(30), Duration.ofSeconds(300));
    }

    @Test
    public void theTokenLifetimesAreCappedByTheIssuer() throws Exception {
        givenTheRestServiceProperties(Map.of(REFRESH_TOKEN_DURATION, (int) MAXIMUM_TOKEN_LIFETIME.toSeconds() * 2));
        givenAnIdentityWithPermissions(ASSETS_PERMISSION);

        whenATokenPairIsRequestedWith(basic(IDENTITY));

        thenATokenPairIsReturned();
        thenTheTokensLast(Duration.ofSeconds(60), MAXIMUM_TOKEN_LIFETIME);
    }

    @Test
    public void aTokenPairIsNotIssuedToAnUnauthenticatedCaller() {

        whenATokenPairIsRequestedWith(NO_AUTHORIZATION);

        thenResponseCodeIs(401);
    }

    @Test
    public void aTokenPairIsNotIssuedToACallerAuthenticatedWithAnAccessToken() throws Exception {
        givenAnIdentityWithPermissions(ASSETS_PERMISSION);
        givenATokenPairIssuedToTheIdentity();

        whenATokenPairIsRequestedWith(bearer(theAccessToken()));

        thenResponseCodeIs(401);
    }

    @Test
    public void issuingFailsWhenTheIssuerIsMisconfigured() throws Exception {
        givenAnIdentityWithPermissions(ASSETS_PERMISSION);
        givenTheIssuerSigningKeyAlias(MISSING_KEY_ALIAS);

        whenATokenPairIsRequestedWith(basic(IDENTITY));

        thenResponseCodeIs(500);
    }
}
