/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.rest.provider.test.jwt;

import java.util.Map;

import org.eclipse.kura.rest.provider.test.util.AbstractJwtRestScenario;
import org.junit.Test;

public class JwtAuthenticationConfigurationTest extends AbstractJwtRestScenario {

    @Test
    public void theIssueEndpointIsNotFoundWhenJwtAuthenticationIsDisabled() throws Exception {
        givenAnIdentityWithPermissions(ASSETS_PERMISSION);
        givenTheRestServiceProperties(Map.of(JWT_ENABLED, false));

        whenATokenPairIsRequestedWith(basic(IDENTITY));

        thenResponseCodeIs(404);
    }

    @Test
    public void theRefreshEndpointIsNotFoundWhenJwtAuthenticationIsDisabled() throws Exception {
        givenAnIdentityWithPermissions(ASSETS_PERMISSION);
        givenATokenPairIssuedToTheIdentity();
        givenTheRestServiceProperties(Map.of(JWT_ENABLED, false));

        whenTheRefreshEndpointReceives(theRefreshToken());

        thenResponseCodeIs(404);
    }

    @Test
    public void anAccessTokenIsRejectedAfterJwtAuthenticationIsDisabled() throws Exception {
        givenAnIdentityWithPermissions(ASSETS_PERMISSION);
        givenATokenPairIssuedToTheIdentity();
        givenTheRestServiceProperties(Map.of(JWT_ENABLED, false));

        whenTheProtectedResourceIsAccessedWith(bearer(theAccessToken()));

        thenResponseCodeIs(401);
    }

    @Test
    public void tokensCannotBeIssuedWhenNoIssuingServiceMatchesTheTarget() throws Exception {
        givenAnIdentityWithPermissions(ASSETS_PERMISSION);
        givenTheRestServiceProperties(Map.of(ISSUING_SERVICE_TARGET, UNMATCHED_TARGET));

        whenATokenPairIsRequestedWith(basic(IDENTITY));

        thenResponseCodeIs(404);
    }

    @Test
    public void anAccessTokenIsRejectedWhenNoVerificationServiceMatchesTheTarget() throws Exception {
        givenAnIdentityWithPermissions(ASSETS_PERMISSION);
        givenATokenPairIssuedToTheIdentity();
        givenTheRestServiceProperties(Map.of(VERIFICATION_SERVICE_TARGET, UNMATCHED_TARGET));

        whenTheProtectedResourceIsAccessedWith(bearer(theAccessToken()));

        thenResponseCodeIs(401);
    }

    @Test
    public void theRefreshEndpointIsNotFoundWhenNoVerificationServiceMatchesTheTarget() throws Exception {
        givenAnIdentityWithPermissions(ASSETS_PERMISSION);
        givenATokenPairIssuedToTheIdentity();
        givenTheRestServiceProperties(Map.of(VERIFICATION_SERVICE_TARGET, UNMATCHED_TARGET));

        whenTheRefreshEndpointReceives(theRefreshToken());

        thenResponseCodeIs(404);
    }

    @Test
    public void jwtAuthenticationRecoversWhenTheVerificationServiceMatchesAgain() throws Exception {
        givenAnIdentityWithPermissions(ASSETS_PERMISSION);
        givenATokenPairIssuedToTheIdentity();
        givenTheRestServiceProperties(Map.of(VERIFICATION_SERVICE_TARGET, UNMATCHED_TARGET));
        givenTheRestServiceProperties(Map.of(VERIFICATION_SERVICE_TARGET, DEFAULT_VERIFICATION_SERVICE_TARGET));

        whenTheProtectedResourceIsAccessedWith(bearer(theAccessToken()));

        thenResponseCodeIs(200);
    }
}
