/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.rest.provider.test.jwt;

import java.time.Duration;
import java.util.Map;

import org.eclipse.kura.rest.provider.test.util.AbstractJwtRestScenario;
import org.junit.Test;

public class RefreshTokenReplayTest extends AbstractJwtRestScenario {

    /*
     * The verifier accepts expired tokens within its clock skew tolerance (30 seconds by default), so a used refresh
     * token stays tracked for the configured retention after its expiry, even if other exchanges happen meanwhile.
     */
    @Test
    public void aUsedRefreshTokenCannotBeReplayedAfterItsExpiry() throws Exception {
        givenTheRestServiceProperties(Map.of(REFRESH_TOKEN_DURATION, 1, USED_REFRESH_TOKEN_RETENTION, 60));
        givenAnIdentityWithPermissions(ASSETS_PERMISSION);
        givenATokenPairIssuedToTheIdentity();
        givenTheRefreshTokenWasExchangedWithStatus(200);
        givenTimePasses(Duration.ofSeconds(2));
        givenTheRefreshTokenWasExchangedWithStatus(200);

        whenTheRefreshEndpointReceives(theFirstExchangedRefreshToken());

        thenResponseCodeIs(401);
    }
}
