/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.rest.provider.test.jwt;

import org.eclipse.kura.rest.provider.test.util.AbstractJwtRestScenario;
import org.junit.Test;

public class RefreshTokenPairTest extends AbstractJwtRestScenario {

    @Test
    public void aRefreshTokenIsExchangedWithoutOtherCredentials() throws Exception {
        givenAnIdentityWithPermissions(ASSETS_PERMISSION);
        givenATokenPairIssuedToTheIdentity();

        whenTheRefreshEndpointReceives(theRefreshToken());

        thenATokenPairIsReturned();
        thenTheReturnedRefreshTokenDiffersFromTheExchangedOne();
        thenTheReturnedAccessTokenGrantsAccessToTheProtectedResource();
    }

    @Test
    public void surroundingWhitespaceInTheBodyIsIgnored() throws Exception {
        givenAnIdentityWithPermissions(ASSETS_PERMISSION);
        givenATokenPairIssuedToTheIdentity();

        whenTheRefreshEndpointReceives("\n  " + theRefreshToken() + "  \n");

        thenATokenPairIsReturned();
    }

    @Test
    public void aRefreshTokenCannotBeExchangedTwice() throws Exception {
        givenAnIdentityWithPermissions(ASSETS_PERMISSION);
        givenATokenPairIssuedToTheIdentity();
        givenTheRefreshTokenWasExchangedWithStatus(200);

        whenTheRefreshEndpointReceives(theFirstExchangedRefreshToken());

        thenResponseCodeIs(401);
    }

    @Test
    public void anAccessTokenCannotBeExchanged() throws Exception {
        givenAnIdentityWithPermissions(ASSETS_PERMISSION);
        givenATokenPairIssuedToTheIdentity();

        whenTheRefreshEndpointReceives(theAccessToken());

        thenResponseCodeIs(401);
    }

    @Test
    public void anEmptyBodyIsRefused() {

        whenTheRefreshEndpointReceives("  \n");

        thenResponseCodeIs(400);
    }

    @Test
    public void aBodyOverTheLimitIsRefused() {

        whenTheRefreshEndpointReceives("a".repeat(MAX_REFRESH_TOKEN_BYTES + 1));

        thenResponseCodeIs(413);
    }

    @Test
    public void aBodyOfExactlyTheLimitIsRead() {

        whenTheRefreshEndpointReceives("a".repeat(MAX_REFRESH_TOKEN_BYTES));

        thenResponseCodeIs(401);
    }

    @Test
    public void aRefreshTokenOfADeletedIdentityIsRefused() throws Exception {
        givenAnIdentityWithPermissions(ASSETS_PERMISSION);
        givenATokenPairIssuedToTheIdentity();
        givenTheIdentityIs(IdentityChange.DELETED);

        whenTheRefreshEndpointReceives(theRefreshToken());

        thenResponseCodeIs(401);
    }

    /*
     * JwtRestService refuses the exchange with 403, but the AuditFilter reports a 403 on an unauthenticated request,
     * like the refresh one, as 401.
     */
    @Test
    public void aRefreshTokenCannotBeExchangedOnceTheIdentityMustChangeItsPassword() throws Exception {
        givenAnIdentityWithPermissions(ASSETS_PERMISSION);
        givenATokenPairIssuedToTheIdentity();
        givenTheIdentityIs(IdentityChange.REQUIRED_TO_CHANGE_PASSWORD);

        whenTheRefreshEndpointReceives(theRefreshToken());

        thenResponseCodeIs(401);
    }

    @Test
    public void aRefreshTokenRemainsUsableWhenIssuingFails() throws Exception {
        givenAnIdentityWithPermissions(ASSETS_PERMISSION);
        givenATokenPairIssuedToTheIdentity();
        givenTheIssuerSigningKeyAlias(MISSING_KEY_ALIAS);
        givenTheRefreshTokenWasExchangedWithStatus(500);
        givenTheIssuerSigningKeyAlias(SIGNING_KEY_ALIAS);

        whenTheRefreshEndpointReceives(theRefreshToken());

        thenATokenPairIsReturned();
    }
}
