/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.container.provider.token;

import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.time.Duration;
import java.time.Instant;
import java.util.concurrent.atomic.AtomicReference;

import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.KuraException;
import org.eclipse.kura.security.token.TokenIssueRequest;
import org.eclipse.kura.security.token.TokenIssuingService;

import com.google.gson.Gson;

public class ContainerTokenProvisioner {

    private static final String ACCESS_TOKEN_CONSUMER = "/token/jwt/v1/access";
    private static final String REFRESH_TOKEN_CONSUMER = "/token/jwt/v1/refresh";
    private static final String TOKEN_TYPE = "Bearer";

    private static final Gson GSON = new Gson();

    private final AtomicReference<TokenIssuingService> tokenIssuingService = new AtomicReference<>();
    private final TokenFileManager tokenFileManager = new TokenFileManager();

    public void setTokenIssuingService(final TokenIssuingService tokenIssuingService) {
        this.tokenIssuingService.set(tokenIssuingService);
    }

    public void unsetTokenIssuingService(final TokenIssuingService tokenIssuingService) {
        this.tokenIssuingService.compareAndSet(tokenIssuingService, null);
    }

    public Path provision(final String identityName, final Duration accessTokenDuration,
            final Duration refreshTokenDuration) throws KuraException {
        final TokenIssuingService issuer = this.tokenIssuingService.get();

        if (issuer == null) {
            throw new KuraException(KuraErrorCode.SERVICE_UNAVAILABLE, "TokenIssuingService not available");
        }

        final Instant now = Instant.now();
        final String accessToken = issue(issuer, identityName, ACCESS_TOKEN_CONSUMER, now, accessTokenDuration);
        final String refreshToken = issue(issuer, identityName, REFRESH_TOKEN_CONSUMER, now, refreshTokenDuration);

        final TokenPair tokenPair = new TokenPair(accessToken, cappedLifetime(accessTokenDuration, issuer),
                refreshToken, cappedLifetime(refreshTokenDuration, issuer));

        return this.tokenFileManager.write(GSON.toJson(tokenPair).getBytes(StandardCharsets.UTF_8));
    }

    public void cleanup() {
        this.tokenFileManager.cleanup();
    }

    private static String issue(final TokenIssuingService issuer, final String identityName,
            final String intendedConsumer, final Instant now, final Duration duration) throws KuraException {
        return issuer.issue(TokenIssueRequest.builder(identityName) //
                .intendedConsumer(intendedConsumer) //
                .notBefore(now) //
                .expiresAt(now.plus(duration)) //
                .build());
    }

    private static Duration cappedLifetime(final Duration requested, final TokenIssuingService issuer) {
        return issuer.getMaximumLifetime().filter(maximum -> maximum.compareTo(requested) < 0).orElse(requested);
    }

    @SuppressWarnings("unused")
    private static final class TokenPair {

        private final String tokenType = TOKEN_TYPE; // NOSONAR
        private final String accessToken;
        private final long accessTokenExpiresInSeconds;
        private final String refreshToken;
        private final long refreshTokenExpiresInSeconds;

        private TokenPair(final String accessToken, final Duration accessTokenLifetime, final String refreshToken,
                final Duration refreshTokenLifetime) {
            this.accessToken = accessToken;
            this.accessTokenExpiresInSeconds = accessTokenLifetime.toSeconds();
            this.refreshToken = refreshToken;
            this.refreshTokenExpiresInSeconds = refreshTokenLifetime.toSeconds();
        }
    }
}
