/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt.roundtrip;

import org.eclipse.kura.core.testutil.pki.TestCA.TestCAException;
import org.eclipse.kura.core.token.jwt.common.AbstractJwtScenario;
import org.eclipse.kura.core.token.jwt.common.IssuingConfig;
import org.eclipse.kura.core.token.jwt.common.VerificationConfig;
import org.junit.Test;

public class AliasMismatchTest extends AbstractJwtScenario {

    private static final String ISSUER_ALIAS = "jwt-signing-key";
    private static final String TRUSTSTORE_ALIAS = "gateway-ca-2026";
    private static final int SIGNING_KEY = 0;

    @Test
    public void aTokenVerifiesWhenTheTrustStoreNamesTheSameCertificateDifferently() throws TestCAException {
        givenTheSameCertificateUnderTwoAliases();
        givenAnIssuerSigningWithTheIssuerAlias();
        givenAVerifierTrustingOnlyTheTrustStoreAlias();

        whenATokenIsIssuedFor(TEST_IDENTITY);
        whenTheIssuedTokenIsVerified();

        thenTheTokenIsVerifiedFor(TEST_IDENTITY);
    }

    @Test
    public void theKeyIdNamesTheIssuerAliasAndNotTheTrustStoreAlias() throws TestCAException {
        givenTheSameCertificateUnderTwoAliases();
        givenAnIssuerSigningWithTheIssuerAlias();
        givenAVerifierTrustingOnlyTheTrustStoreAlias();

        whenATokenIsIssuedFor(TEST_IDENTITY);

        thenIssuedTokenHeaderHas("kid", ISSUER_ALIAS);
    }

    private void givenTheSameCertificateUnderTwoAliases() throws TestCAException {
        givenKeystorePrivateKeyEntry(ISSUER_ALIAS, SIGNING_KEY);
        givenKeystoreTrustedCertificate(TRUSTSTORE_ALIAS, SIGNING_KEY);
    }

    private void givenAnIssuerSigningWithTheIssuerAlias() {
        givenTheIssuerIsBoundToTheKeystore();
        givenTheIssuerIsActivatedWith(IssuingConfig.defaults().withSigningKeyAlias(ISSUER_ALIAS));
    }

    private void givenAVerifierTrustingOnlyTheTrustStoreAlias() {
        givenTheVerifierIsBoundToTheKeystore();
        givenTheVerifierIsActivatedWith(VerificationConfig.defaults() //
                .withVerificationKeyAliases(TRUSTSTORE_ALIAS));
    }

}
