/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt.roundtrip;

import org.eclipse.kura.core.testutil.pki.TestCA.TestCAException;
import org.eclipse.kura.core.token.jwt.common.AbstractJwtScenario;
import org.eclipse.kura.core.token.jwt.common.IssuingConfig;
import org.eclipse.kura.core.token.jwt.common.VerificationConfig;
import org.junit.Test;

import com.auth0.jwt.exceptions.SignatureVerificationException;

public class ForeignSigningKeyTest extends AbstractJwtScenario {

    private static final String SIGNING_ALIAS_IN_USE = "jwt-signing-key";
    private static final String TRUSTED_ALIAS = "the-only-trusted-certificate";

    private static final int SIGNING_KEY = 0;
    private static final int FOREIGN_KEY = 1;

    @Test
    public void aTokenSignedWithATrustedKeyIsAccepted() throws TestCAException {
        givenAnIssuerSigningWithKey(SIGNING_KEY);
        givenAVerifierTrustingOnlyTheCertificateOfKey(SIGNING_KEY);

        whenATokenIsIssuedFor(TEST_IDENTITY);
        whenTheIssuedTokenIsVerified();

        thenTheTokenIsVerifiedFor(TEST_IDENTITY);
    }

    @Test
    public void aTokenSignedWithAKeyTheVerifierDoesNotTrustIsRejected() throws TestCAException {
        givenAnIssuerSigningWithKey(SIGNING_KEY);
        givenAVerifierTrustingOnlyTheCertificateOfKey(FOREIGN_KEY);

        whenATokenIsIssuedFor(TEST_IDENTITY);
        whenTheIssuedTokenIsVerified();

        thenVerificationFailedBecauseOf(SignatureVerificationException.class);
        thenNoVerificationProofIsProduced();
    }

    private void givenAnIssuerSigningWithKey(final int keyIndex) throws TestCAException {
        givenKeystorePrivateKeyEntry(SIGNING_ALIAS_IN_USE, keyIndex);
        givenTheIssuerIsBoundToTheKeystore();
        givenTheIssuerIsActivatedWith(IssuingConfig.defaults().withSigningKeyAlias(SIGNING_ALIAS_IN_USE));
    }

    private void givenAVerifierTrustingOnlyTheCertificateOfKey(final int keyIndex) throws TestCAException {
        givenKeystoreTrustedCertificate(TRUSTED_ALIAS, keyIndex);
        givenTheVerifierIsBoundToTheKeystore();
        givenTheVerifierIsActivatedWith(VerificationConfig.defaults().withVerificationKeyAliases(TRUSTED_ALIAS));
    }

}
