/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt.roundtrip;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import java.util.List;

import org.eclipse.kura.core.testutil.pki.TestCA.TestCAException;
import org.eclipse.kura.core.token.jwt.common.AbstractJwtScenario;
import org.eclipse.kura.core.token.jwt.common.IssuingConfig;
import org.eclipse.kura.core.token.jwt.common.TokenInspector;
import org.eclipse.kura.core.token.jwt.common.VerificationConfig;
import org.eclipse.kura.security.token.TokenIssueRequest;
import org.junit.Test;

public class IssueAndVerifyTest extends AbstractJwtScenario {

    private static final String REST_CONSUMER = "kura.rest";
    private static final String WEB_CONSUMER = "kura.web";
    private static final int SIGNING_KEY = 0;

    @Test
    public void anIssuedTokenIsVerifiedForTheRequestedIdentity() throws TestCAException {
        givenAnIssuerAndAVerifierSharingOneKeystore();

        whenATokenIsIssuedAndVerified(TokenIssueRequest.builder(TEST_IDENTITY).build());

        thenTheTokenIsVerifiedFor(TEST_IDENTITY);
    }

    @Test
    public void theIssuerAndTheCustomClaimsSurviveTheRoundTrip() throws TestCAException {
        givenAnIssuerAndAVerifierSharingOneKeystore();

        whenATokenIsIssuedAndVerified(TokenIssueRequest.builder(TEST_IDENTITY) //
                .claim("role", "admin") //
                .claim("permissions", List.of("kura.admin")) //
                .build());

        thenTheProofHasStringClaim("iss", DEFAULT_ISSUER);
        thenTheProofHasStringClaim("role", "admin");
        thenTheProofHasClaimNamed("permissions");
    }

    @Test
    public void theAudienceSurvivesTheRoundTrip() throws TestCAException {
        givenAnIssuerAndAVerifierSharingOneKeystore();

        whenATokenIsIssuedAndVerifiedOnBehalfOf(REST_CONSUMER);

        thenTheTokenIsVerifiedFor(TEST_IDENTITY);
    }

    @Test
    public void theTokenIdentifierSurvivesTheRoundTrip() throws TestCAException {
        givenAnIssuerAndAVerifierSharingOneKeystore();

        whenATokenIsIssuedAndVerified(TokenIssueRequest.builder(TEST_IDENTITY).build());

        thenTheProofExposesTheIssuedTokenIdentifier();
    }

    @Test
    public void theExpirationSurvivesTheRoundTrip() throws TestCAException {
        givenAnIssuerAndAVerifierSharingOneKeystore();

        whenATokenIsIssuedAndVerified(TokenIssueRequest.builder(TEST_IDENTITY).build());

        thenTheProofExposesTheIssuedExpiration();
    }

    private void givenAnIssuerAndAVerifierSharingOneKeystore() throws TestCAException {
        givenKeystorePrivateKeyEntry(SIGNING_ALIAS, SIGNING_KEY);
        givenTheIssuerIsBoundToTheKeystore();
        givenTheIssuerIsActivatedWith(IssuingConfig.defaults().withSigningKeyAlias(SIGNING_ALIAS));
        givenTheVerifierIsBoundToTheKeystore();
        givenTheVerifierIsActivatedWith(VerificationConfig.defaults().withTrustedIssuers(DEFAULT_ISSUER));
    }

    private void whenATokenIsIssuedAndVerified(final TokenIssueRequest request) {
        whenATokenIsIssued(request);

        thenATokenIsIssued();

        whenTheIssuedTokenIsVerified();
    }

    private void whenATokenIsIssuedAndVerifiedOnBehalfOf(final String intendedConsumer) {
        whenATokenIsIssued(TokenIssueRequest.builder(TEST_IDENTITY) //
                .intendedConsumer(WEB_CONSUMER) //
                .intendedConsumer(REST_CONSUMER) //
                .build());

        thenATokenIsIssued();

        whenATokenIsVerifiedFor(issuedToken(), intendedConsumer);
    }

    private void thenTheProofHasClaimNamed(final String name) {
        assertTrue("the proof has no claim '" + name + "' in " + proof().getClaims(),
                proof().getClaims().containsKey(name));
    }

    private void thenTheProofExposesTheIssuedTokenIdentifier() {
        final String issuedTokenId = TokenInspector.of(issuedToken()).claim("jti").get().getAsString();

        thenTheProofExposesTokenId(issuedTokenId);
    }

    private void thenTheProofExposesTheIssuedExpiration() {
        final long issuedExpiration = TokenInspector.of(issuedToken()).claim("exp").get().getAsLong();

        assertTrue("the proof exposes no expiration", proof().getExpiresAt().isPresent());
        assertEquals(issuedExpiration, proof().getExpiresAt().get().getEpochSecond());
    }

}
