/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt.roundtrip;

import static org.junit.Assert.assertNotEquals;
import static org.junit.Assert.assertNotNull;

import org.eclipse.kura.core.testutil.pki.TestCA.TestCAException;
import org.eclipse.kura.core.token.jwt.common.AbstractJwtScenario;
import org.eclipse.kura.core.token.jwt.common.IssuingConfig;
import org.eclipse.kura.core.token.jwt.common.TestKeys;
import org.eclipse.kura.core.token.jwt.common.VerificationConfig;
import org.junit.Test;

import com.auth0.jwt.exceptions.SignatureVerificationException;

public class KeyRotationTest extends AbstractJwtScenario {

    private static final int KEY_BEFORE_ROTATION = 0;
    private static final int KEY_AFTER_ROTATION = 1;

    private String tokenIssuedBeforeRotation;
    private String tokenIssuedAfterRotation;

    @Test
    public void aTokenIssuedBeforeTheRotationNoLongerVerifies() throws TestCAException {
        givenAnIssuerAndAVerifierSharingOneKeystore();
        givenATokenWasIssuedBeforeTheRotation();
        givenTheSigningKeyWasRotated();

        whenATokenIsVerified(this.tokenIssuedBeforeRotation);

        thenVerificationFailedBecauseOf(SignatureVerificationException.class);
        thenNoVerificationProofIsProduced();
    }

    @Test
    public void aTokenIssuedAfterTheRotationVerifies() throws TestCAException {
        givenAnIssuerAndAVerifierSharingOneKeystore();
        givenATokenWasIssuedBeforeTheRotation();
        givenTheSigningKeyWasRotated();

        whenATokenIsIssuedFor(TEST_IDENTITY);
        whenTheIssuedTokenIsVerified();

        thenTheTokenIsVerifiedFor(TEST_IDENTITY);
    }

    @Test
    public void theRotationProducesADifferentToken() throws TestCAException {
        givenAnIssuerAndAVerifierSharingOneKeystore();
        givenATokenWasIssuedBeforeTheRotation();
        givenTheSigningKeyWasRotated();

        whenATokenIsIssuedAfterTheRotation();

        thenBothTokensWereIssued();
        thenTheTwoTokensDiffer();
    }

    private void givenAnIssuerAndAVerifierSharingOneKeystore() throws TestCAException {
        givenKeystorePrivateKeyEntry(SIGNING_ALIAS, KEY_BEFORE_ROTATION);
        givenTheIssuerIsBoundToTheKeystore();
        givenTheIssuerIsActivatedWith(IssuingConfig.defaults().withSigningKeyAlias(SIGNING_ALIAS));
        givenTheVerifierIsBoundToTheKeystore();
        givenTheVerifierIsActivatedWith(VerificationConfig.defaults());
    }

    private void givenATokenWasIssuedBeforeTheRotation() {
        whenATokenIsIssuedFor(TEST_IDENTITY);

        thenATokenIsIssued();

        this.tokenIssuedBeforeRotation = issuedToken();
    }

    private void givenTheSigningKeyWasRotated() throws TestCAException {
        keystore().withPrivateKeyEntry(SIGNING_ALIAS, TestKeys.rsa(KEY_AFTER_ROTATION));

        givenTheBoundKeystoreAnnouncedAChange();
    }

    private void whenATokenIsIssuedAfterTheRotation() {
        whenATokenIsIssuedFor(TEST_IDENTITY);

        this.tokenIssuedAfterRotation = issuedToken();
    }

    private void thenBothTokensWereIssued() {
        assertNotNull("no token was issued before the rotation", this.tokenIssuedBeforeRotation);
        assertNotNull("no token was issued after the rotation", this.tokenIssuedAfterRotation);
    }

    private void thenTheTwoTokensDiffer() {
        assertNotEquals("the rotation did not change the issued token", this.tokenIssuedBeforeRotation,
                this.tokenIssuedAfterRotation);
    }

}
