/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 * Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.net.admin.monitor;

import java.util.function.BooleanSupplier;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Runs a monitoring task repeatedly, waiting between runs, until a stop is requested.
 */
final class MonitorLoop {

    private static final Logger LOGGER = LoggerFactory.getLogger(MonitorLoop.class);

    interface Wait {

        void await() throws InterruptedException;
    }

    private MonitorLoop() {
    }

    static void run(final String name, final BooleanSupplier stopRequested, final Runnable monitor,
            final Wait wait) {
        while (!stopRequested.getAsBoolean()) {
            try {
                monitor.run();
            } catch (Exception | LinkageError e) {
                LOGGER.error("Exception while monitoring {}", name, e);
            } catch (VirtualMachineError e) {
                // not contained: the monitor stops, report it before propagating
                LOGGER.error("{} monitor stopped by a virtual machine error", name, e);
                throw e;
            }

            // wait also after a failed run, so that a persistent failure does not turn the loop into a busy loop
            try {
                wait.await();
            } catch (InterruptedException e) {
                LOGGER.debug("{} monitor interrupted", name, e);
                Thread.currentThread().interrupt();
            }
        }
    }
}
