/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.configuration;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.util.Dictionary;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

import org.eclipse.kura.KuraException;
import org.eclipse.kura.configuration.ComponentConfiguration;
import org.eclipse.kura.configuration.Password;
import org.eclipse.kura.core.configuration.metatype.Tad;
import org.eclipse.kura.core.configuration.metatype.Tocd;
import org.eclipse.kura.core.configuration.metatype.Tscalar;
import org.eclipse.kura.core.testutil.TestUtil;
import org.eclipse.kura.crypto.CryptoService;
import org.junit.Test;
import org.osgi.framework.Bundle;
import org.osgi.framework.BundleContext;
import org.osgi.framework.ServiceReference;
import org.osgi.service.cm.Configuration;
import org.osgi.service.cm.ConfigurationAdmin;
import org.osgi.service.component.ComponentContext;
import org.osgi.service.metatype.MetaTypeService;

public class PasswordTypePreservationTest {

    private static final String FACTORY_PID = "org.eclipse.kura.test.PasswordFactory";
    private static final String PID = "org.eclipse.kura.test.PasswordFactory-1";
    private static final String SERVICE_PID = "servicePid";
    private static final String PASSWORD_PROPERTY = "password";
    private static final String OTHER_PROPERTY = "otherProperty";
    private static final String SECRET = "aSecret";
    private static final String NEW_SECRET = "aNewSecret";
    private static final String OTHER_VALUE = "aValue";

    private ConfigurationServiceImpl configurationService;
    private ConfigurationAdmin configurationAdmin;
    private Configuration configuration;
    private Dictionary<String, Object> storedProperties;
    private ComponentConfiguration readBackConfiguration;

    @Test
    public void passwordSurvivesConfigurationAdminWhenMetatypeIsNotTrackedYet() throws Throwable {
        givenConfigurationService();
        givenFactoryConfigurationWithPassword();
        givenNoRegisteredMetatype();

        whenConfigurationIsReadBack();

        thenConfigurationAdminHoldsAPlainString();
        thenReadBackPropertyIsAPassword(SECRET);
    }

    @Test
    public void passwordIsRestoredFromTheMetatypeWhenTracked() throws Throwable {
        givenConfigurationService();
        givenFactoryConfigurationWithPassword();
        givenRegisteredMetatype(PASSWORD_PROPERTY, Tscalar.PASSWORD);

        whenConfigurationIsReadBack();

        thenReadBackPropertyIsAPassword(SECRET);
    }

    @Test
    public void metatypeWinsOverTheKnownPasswordProperties() throws Throwable {
        givenConfigurationService();
        givenFactoryConfigurationWithPassword();
        givenRegisteredMetatype(PASSWORD_PROPERTY, Tscalar.STRING);

        whenConfigurationIsReadBack();

        thenReadBackPropertyIsAPlainString(SECRET);
    }

    @Test
    public void propertiesThatWereNeverPasswordsAreLeftUntouched() throws Throwable {
        givenConfigurationService();
        givenFactoryConfigurationWithoutPassword();
        givenNoRegisteredMetatype();

        whenConfigurationIsReadBack();

        thenReadBackPropertyIsAPlainString(SECRET);
    }

    @Test
    public void passwordChangedAtRuntimeIsStillAPassword() throws Throwable {
        givenConfigurationService();
        givenFactoryConfigurationWithPassword();
        givenRegisteredMetatype(PASSWORD_PROPERTY, Tscalar.PASSWORD);

        whenPasswordIsUpdatedTo(NEW_SECRET);
        whenConfigurationIsReadBack();

        thenConfigurationAdminHoldsAPlainString();
        thenReadBackPropertyIsAPassword(NEW_SECRET);
    }

    @Test
    public void passwordSetForTheFirstTimeAtRuntimeIsAPassword() throws Throwable {
        givenConfigurationService();
        givenFactoryConfigurationWithoutPassword();
        givenRegisteredMetatype(PASSWORD_PROPERTY, Tscalar.PASSWORD);

        whenPasswordIsUpdatedTo(NEW_SECRET);
        whenConfigurationIsReadBack();

        thenReadBackPropertyIsAPassword(NEW_SECRET);
    }

    @Test
    public void passwordSetAtRuntimeWithoutAnAttributeDefinitionIsAPassword() throws Throwable {
        givenConfigurationService();
        givenFactoryConfigurationWithoutPassword();
        givenRegisteredMetatypeWithoutThePasswordAttributeDefinition();

        whenPasswordIsUpdatedTo(NEW_SECRET);
        whenConfigurationIsReadBack();

        thenConfigurationAdminHoldsAPlainString();
        thenReadBackPropertyIsAPassword(NEW_SECRET);
    }

    @Test
    public void passwordSurvivesAnUpdateThatDoesNotTouchIt() throws Throwable {
        givenConfigurationService();
        givenFactoryConfigurationWithPassword();
        givenRegisteredMetatypeWithoutThePasswordAttributeDefinition();

        whenOtherPropertyIsUpdatedTo(OTHER_VALUE);
        whenConfigurationIsReadBack();

        thenReadBackPropertyIsAPassword(SECRET);
    }

    @Test
    public void passwordIsStillAPasswordAfterTheMetatypeIsRegistered() throws Throwable {
        givenConfigurationService();
        givenFactoryConfigurationWithPassword();
        givenNoRegisteredMetatype();

        whenMetatypeWithoutThePasswordAttributeDefinitionIsRegistered();
        whenConfigurationIsReadBack();

        thenReadBackPropertyIsAPassword(SECRET);
    }

    @Test
    public void rollbackRestoresThePasswordTypeOfTheTargetSnapshot() throws Throwable {
        givenConfigurationService();
        givenFactoryConfigurationWithoutPassword();
        givenRegisteredMetatypeWithoutThePasswordAttributeDefinition();

        whenRolledBackToAConfigurationHolding(new Password(NEW_SECRET));
        whenConfigurationIsReadBack();

        thenReadBackPropertyIsAPassword(NEW_SECRET);
    }

    @Test
    public void rollbackToAPlainStringDropsTheTrackedPasswordName() throws Throwable {
        givenConfigurationService();
        givenFactoryConfigurationWithPassword();
        givenRegisteredMetatypeWithoutThePasswordAttributeDefinition();

        whenRolledBackToAConfigurationHolding(NEW_SECRET);
        whenConfigurationIsReadBack();

        thenReadBackPropertyIsAPlainString(NEW_SECRET);
    }

    @Test
    public void passwordArrayKeepsItsTypeWhenMetatypeIsNotTrackedYet() throws Throwable {
        givenConfigurationService();
        givenFactoryConfigurationWithAPasswordArray();
        givenNoRegisteredMetatype();

        whenConfigurationIsReadBack();

        thenReadBackPropertyIsAPasswordArray(SECRET, NEW_SECRET);
    }

    private void givenConfigurationService() throws Throwable {
        this.configurationService = new ConfigurationServiceImpl();

        this.configurationAdmin = mock(ConfigurationAdmin.class);
        this.configurationService.setConfigurationAdmin(this.configurationAdmin);
        this.configurationService.setCryptoService(givenPassThroughCryptoService());

        Configuration factoryConfiguration = mock(Configuration.class);
        when(factoryConfiguration.getPid()).thenReturn(SERVICE_PID);
        when(this.configurationAdmin.createFactoryConfiguration(FACTORY_PID, null)).thenReturn(factoryConfiguration);

        this.configuration = mock(Configuration.class);
        when(this.configurationAdmin.getConfiguration(SERVICE_PID, "?")).thenReturn(this.configuration);
        doAnswer(invocation -> {
            this.storedProperties = invocation.getArgument(0);
            return null;
        }).when(this.configuration).update(any(Dictionary.class));
        when(this.configuration.getProperties()).thenAnswer(invocation -> this.storedProperties);

        TestUtil.setFieldValue(this.configurationService, "ctx", givenComponentContext());
    }

    private ComponentContext givenComponentContext() {
        BundleContext bundleContext = mock(BundleContext.class);

        ServiceReference<MetaTypeService> metaTypeServiceReference = mock(ServiceReference.class);
        MetaTypeService metaTypeService = mock(MetaTypeService.class);
        when(bundleContext.getServiceReference(MetaTypeService.class)).thenReturn(metaTypeServiceReference);
        when(bundleContext.getService(metaTypeServiceReference)).thenReturn(metaTypeService);
        when(metaTypeService.getMetaTypeInformation(any())).thenReturn(null);

        ComponentContext componentContext = mock(ComponentContext.class);
        when(componentContext.getBundleContext()).thenReturn(bundleContext);
        return componentContext;
    }

    private CryptoService givenPassThroughCryptoService() throws KuraException {
        CryptoService cryptoService = mock(CryptoService.class);
        when(cryptoService.encryptAes(any(char[].class))).thenAnswer(invocation -> invocation.getArgument(0));
        when(cryptoService.decryptAes(any(char[].class))).thenAnswer(invocation -> invocation.getArgument(0));
        return cryptoService;
    }

    private void givenFactoryConfigurationWithPassword() throws KuraException {
        Map<String, Object> properties = new HashMap<>();
        properties.put(PASSWORD_PROPERTY, new Password(SECRET));

        this.configurationService.createFactoryConfiguration(FACTORY_PID, PID, properties, false);
    }

    private void givenFactoryConfigurationWithoutPassword() throws KuraException {
        Map<String, Object> properties = new HashMap<>();
        properties.put(PASSWORD_PROPERTY, SECRET);

        this.configurationService.createFactoryConfiguration(FACTORY_PID, PID, properties, false);
    }

    private void givenFactoryConfigurationWithAPasswordArray() throws KuraException {
        Map<String, Object> properties = new HashMap<>();
        properties.put(PASSWORD_PROPERTY, new Password[] { new Password(SECRET), new Password(NEW_SECRET) });

        this.configurationService.createFactoryConfiguration(FACTORY_PID, PID, properties, false);
    }

    private void givenNoRegisteredMetatype() throws Throwable {
        TestUtil.setFieldValue(this.configurationService, "ocds", new HashMap<String, Tocd>());
    }

    private void givenRegisteredMetatype(String propertyName, Tscalar type) throws Throwable {
        Tad attributeDefinition = new Tad();
        attributeDefinition.setId(propertyName);
        attributeDefinition.setName(propertyName);
        attributeDefinition.setType(type);
        attributeDefinition.setCardinality(0);
        attributeDefinition.setRequired(false);

        Tocd ocd = new Tocd();
        ocd.setId(FACTORY_PID);
        ocd.addAD(attributeDefinition);

        Map<String, Tocd> ocds = new HashMap<>();
        ocds.put(FACTORY_PID, ocd);
        TestUtil.setFieldValue(this.configurationService, "ocds", ocds);
    }

    private void givenRegisteredMetatypeWithoutThePasswordAttributeDefinition() throws Throwable {
        Map<String, Tocd> ocds = new HashMap<>();
        ocds.put(FACTORY_PID, ocdWithoutThePasswordAttributeDefinition());
        TestUtil.setFieldValue(this.configurationService, "ocds", ocds);
    }

    private Tocd ocdWithoutThePasswordAttributeDefinition() {
        Tad attributeDefinition = new Tad();
        attributeDefinition.setId(OTHER_PROPERTY);
        attributeDefinition.setName(OTHER_PROPERTY);
        attributeDefinition.setType(Tscalar.STRING);
        attributeDefinition.setCardinality(0);
        attributeDefinition.setRequired(false);

        Tocd ocd = new Tocd();
        ocd.setId(FACTORY_PID);
        ocd.addAD(attributeDefinition);
        return ocd;
    }

    private void whenMetatypeWithoutThePasswordAttributeDefinitionIsRegistered() throws KuraException {
        this.configurationService.registerComponentOCD(FACTORY_PID, ocdWithoutThePasswordAttributeDefinition(), true,
                mock(Bundle.class));
    }

    private void whenOtherPropertyIsUpdatedTo(String value) throws Throwable {
        Map<String, Object> properties = new HashMap<>();
        properties.put(OTHER_PROPERTY, value);

        TestUtil.invokePrivate(this.configurationService, "updateConfigurationInternal",
                new Class<?>[] { String.class, Map.class, boolean.class }, PID, properties, false);
    }

    private void whenRolledBackToAConfigurationHolding(Object passwordValue) throws Throwable {
        Map<String, Object> properties = new HashMap<>();
        properties.put(PASSWORD_PROPERTY, passwordValue);

        TestUtil.invokePrivate(this.configurationService, "rollbackConfigurationInternal",
                new Class<?>[] { ComponentConfiguration.class, Optional.class },
                new ComponentConfigurationImpl(PID, null, properties), Optional.of(this.configuration));
    }

    private void whenPasswordIsUpdatedTo(String newSecret) throws Throwable {
        Map<String, Object> properties = new HashMap<>();
        properties.put(PASSWORD_PROPERTY, new Password(newSecret));

        TestUtil.invokePrivate(this.configurationService, "updateConfigurationInternal",
                new Class<?>[] { String.class, Map.class, boolean.class }, PID, properties, false);
    }

    private void whenConfigurationIsReadBack() throws Throwable {
        this.readBackConfiguration = (ComponentConfiguration) TestUtil.invokePrivate(this.configurationService,
                "getConfigurableComponentConfiguration", PID);
    }

    private void thenConfigurationAdminHoldsAPlainString() {
        assertNotNull(this.storedProperties);
        assertTrue("ConfigurationAdmin can only hold plain strings",
                this.storedProperties.get(PASSWORD_PROPERTY) instanceof String);
    }

    private void thenReadBackPropertyIsAPassword(String expectedValue) {
        assertNotNull(this.readBackConfiguration);
        Object value = this.readBackConfiguration.getConfigurationProperties().get(PASSWORD_PROPERTY);
        assertTrue("expected a Password but was " + (value == null ? "null" : value.getClass().getName()),
                value instanceof Password);
        assertEquals(expectedValue, value.toString());
    }

    private void thenReadBackPropertyIsAPasswordArray(String... expectedValues) {
        assertNotNull(this.readBackConfiguration);
        Object value = this.readBackConfiguration.getConfigurationProperties().get(PASSWORD_PROPERTY);
        assertTrue("expected a Password[] but was " + (value == null ? "null" : value.getClass().getName()),
                value instanceof Password[]);

        Password[] passwords = (Password[]) value;
        assertEquals(expectedValues.length, passwords.length);
        for (int i = 0; i < expectedValues.length; i++) {
            assertEquals(expectedValues[i], passwords[i].toString());
        }
    }

    private void thenReadBackPropertyIsAPlainString(String expectedValue) {
        assertNotNull(this.readBackConfiguration);
        Object value = this.readBackConfiguration.getConfigurationProperties().get(PASSWORD_PROPERTY);
        assertTrue("expected a String but was " + (value == null ? "null" : value.getClass().getName()),
                value instanceof String);
        assertEquals(expectedValue, value);
    }
}
