/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.configuration;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.util.Arrays;
import java.util.Map;

import org.eclipse.kura.configuration.ConfigurableComponent;
import org.eclipse.kura.configuration.ConfigurationService;
import org.eclipse.kura.configuration.SelfConfiguringComponent;
import org.eclipse.kura.core.testutil.TestUtil;
import org.junit.Test;
import org.osgi.framework.Constants;
import org.osgi.framework.ServiceReference;
import org.osgi.service.cm.ConfigurationAdmin;

public class SelfConfiguringComponentRegistrationTest {

    private static final String KURA_PID = "org.eclipse.kura.test.SelfConfiguringService";
    private static final String SERVICE_PID = "org.eclipse.kura.test.SelfConfiguringService";
    private static final String CONFIGURABLE_KURA_PID = "org.eclipse.kura.test.ConfigurableService";

    private ConfigurationServiceImpl configurationService;
    private ServiceReference<SelfConfiguringComponent> selfConfiguringReference;
    private ServiceReference<ConfigurableComponent> configurableReference;

    @Test
    public void selfConfiguringComponentWithoutServicePidIsTracked() throws Throwable {
        givenConfigurationService();
        givenSelfConfiguringComponentReference(KURA_PID, null);

        whenSelfConfiguringComponentIsAdded();

        thenPidIsTracked(KURA_PID);
        thenServicePidOf(KURA_PID, KURA_PID);
    }

    @Test
    public void selfConfiguringComponentWithServicePidKeepsIt() throws Throwable {
        givenConfigurationService();
        givenSelfConfiguringComponentReference(KURA_PID, "aDifferentServicePid");

        whenSelfConfiguringComponentIsAdded();

        thenPidIsTracked(KURA_PID);
        thenServicePidOf(KURA_PID, "aDifferentServicePid");
    }

    @Test
    public void selfConfiguringComponentWithoutKuraServicePidIsNotTracked() throws Throwable {
        givenConfigurationService();
        givenSelfConfiguringComponentReference(null, SERVICE_PID);

        whenSelfConfiguringComponentIsAdded();

        thenNoPidIsTracked();
    }

    @Test
    public void selfConfiguringComponentWithoutServicePidIsUntrackedOnRemoval() throws Throwable {
        givenConfigurationService();
        givenSelfConfiguringComponentReference(KURA_PID, null);
        givenTrackedSelfConfiguringComponent();

        whenSelfConfiguringComponentIsRemoved();

        thenNoPidIsTracked();
    }

    @Test
    public void duplicatedServicePidIsReducedToASingleValue() throws Throwable {
        givenConfigurationService();
        givenConfigurableComponentReference(CONFIGURABLE_KURA_PID, Arrays.asList(SERVICE_PID, SERVICE_PID));

        whenConfigurableComponentIsAdded();

        thenPidIsTracked(CONFIGURABLE_KURA_PID);
        thenServicePidOf(CONFIGURABLE_KURA_PID, SERVICE_PID);
    }

    @Test
    public void duplicatedServicePidArrayIsReducedToASingleValue() throws Throwable {
        givenConfigurationService();
        givenConfigurableComponentReference(CONFIGURABLE_KURA_PID, new String[] { SERVICE_PID, SERVICE_PID });

        whenConfigurableComponentIsAdded();

        thenPidIsTracked(CONFIGURABLE_KURA_PID);
        thenServicePidOf(CONFIGURABLE_KURA_PID, SERVICE_PID);
    }

    @Test
    public void ambiguousServicePidIsRejected() throws Throwable {
        givenConfigurationService();
        givenConfigurableComponentReference(CONFIGURABLE_KURA_PID, Arrays.asList(SERVICE_PID, "anotherServicePid"));

        whenConfigurableComponentIsAdded();

        thenNoPidIsTracked();
    }

    private void givenConfigurationService() throws Throwable {
        this.configurationService = new ConfigurationServiceImpl();
        this.configurationService.setConfigurationAdmin(mock(ConfigurationAdmin.class));
    }

    @SuppressWarnings("unchecked")
    private void givenSelfConfiguringComponentReference(String kuraPid, Object servicePid) {
        this.selfConfiguringReference = mock(ServiceReference.class);
        when(this.selfConfiguringReference.getProperty(ConfigurationService.KURA_SERVICE_PID)).thenReturn(kuraPid);
        when(this.selfConfiguringReference.getProperty(Constants.SERVICE_PID)).thenReturn(servicePid);
    }

    @SuppressWarnings("unchecked")
    private void givenConfigurableComponentReference(String kuraPid, Object servicePid) {
        this.configurableReference = mock(ServiceReference.class);
        when(this.configurableReference.getProperty(ConfigurationService.KURA_SERVICE_PID)).thenReturn(kuraPid);
        when(this.configurableReference.getProperty(Constants.SERVICE_PID)).thenReturn(servicePid);
    }

    private void givenTrackedSelfConfiguringComponent() {
        this.configurationService.addSelfConfiguringComponent(this.selfConfiguringReference);

        assertTrue(this.configurationService.getConfigurableComponentPids().contains(KURA_PID));
    }

    private void whenSelfConfiguringComponentIsAdded() {
        this.configurationService.addSelfConfiguringComponent(this.selfConfiguringReference);
    }

    private void whenSelfConfiguringComponentIsRemoved() {
        this.configurationService.removeSelfConfiguringComponent(this.selfConfiguringReference);
    }

    private void whenConfigurableComponentIsAdded() {
        this.configurationService.addConfigurableComponent(this.configurableReference);
    }

    private void thenPidIsTracked(String pid) {
        assertTrue(this.configurationService.getConfigurableComponentPids().contains(pid));
    }

    private void thenNoPidIsTracked() {
        assertTrue(this.configurationService.getConfigurableComponentPids().isEmpty());
    }

    @SuppressWarnings("unchecked")
    private void thenServicePidOf(String pid, String expectedServicePid) throws Throwable {
        Map<String, String> servicePidByPid = (Map<String, String>) TestUtil.getFieldValue(this.configurationService,
                "servicePidByPid");

        assertFalse(servicePidByPid.isEmpty());
        assertEquals(expectedServicePid, servicePidByPid.get(pid));
    }
}
