/*******************************************************************************
 * Copyright (c) 2011, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *  Red Hat Inc
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.comm;

import static org.eclipse.kura.comm.CommURI.parseString;

import java.io.IOException;

import javax.comm.NoSuchPortException;
import javax.comm.PortInUseException;
import javax.microedition.io.Connection;

import org.eclipse.kura.comm.CommURI;
import org.osgi.service.io.ConnectionFactory;

public class CommConnectionFactory implements ConnectionFactory {

    @Override
    public Connection createConnection(String name, int mode, boolean timeouts) throws IOException {
        try {
            return newConnection(parseString(name), mode, timeouts);
        } catch (IOException e) {
            throw e; // re-throw
        } catch (Exception | LinkageError e) {
            // LinkageError covers the native serial library failing to load
            throw new IOException(e);
        }
    }

    // package-private for testing purpose
    Connection newConnection(CommURI commUri, int mode, boolean timeouts)
            throws IOException, NoSuchPortException, PortInUseException {
        return new CommConnectionImpl(commUri, mode, timeouts);
    }
}
