#!/bin/bash

##############################################
# POST INSTALL SCRIPT
##############################################
mkdir -p /opt/eclipse >> /tmp/kura_install.log 2>&1
unzip /tmp/kura-*.zip -d /opt/eclipse >> /tmp/kura_install.log 2>&1

#install KURA files
sh /opt/eclipse/kura-*/install/kura_install.sh >> /tmp/kura_install.log 2>&1

#clean up
rm -rf /opt/eclipse/kura/install >> /tmp/kura_install.log 2>&1
rm /tmp/kura-*.zip >> /tmp/kura_install.log 2>&1

#move the log file
mv /tmp/kura_install.log /opt/eclipse/kura/configuration/

#flush all cached filesystem to disk
sync

echo ""
echo "Finished. KURA has been installed to /opt/eclipse/kura and will start automatically after a reboot"
exit 0
#############################################
# END POST INSTALL SCRIPT
##############################################

