#!/bin/bash

INSTALL_DIR=/opt/eclipse
WD_TMP_FILE=/tmp/watchdog
REFRESH_TIME=5

##############################################
# UTILITY FUNCTIONS
##############################################
# Start refresh watchdog device
function startRefreshWatchdog {
    if [ -f "${WD_TMP_FILE}" ]; then
        WATCHDOG_DEVICE=`cat ${WD_TMP_FILE}`
        refreshWatchdog &
        PID=$!
    fi
}

# Refresh watchdog device
function refreshWatchdog {
    for (( ; ; ))
    do
        echo w > ${WATCHDOG_DEVICE}
        sleep $REFRESH_TIME
    done
}

# Deactivate watchdog device if possible
function stopWatchdog {
    if [ -n "${PID}" ]; then
        kill -9 $PID >> /dev/null 2>&1
    fi
    if [ -n "${WATCHDOG_DEVICE}" ]; then
        echo V > ${WATCHDOG_DEVICE}
    fi
}
##############################################
# END UTILITY FUNCTIONS
##############################################

##############################################
# PRE-INSTALL SCRIPT
##############################################
PIDS=`pgrep java`

echo ""
echo "Installing Kura..."
echo "Installing Kura..." > /tmp/kura_install.log 2>&1

#Kill JVM and monit for installation
if [ -f "/var/run/kura.pid" ] ; then
  KURA_PID=`cat /var/run/kura.pid`

  for pid in "${PIDS[@]}"
  do
    if [ "$KURA_PID" == "$pid" ] ; then
      `kill $pid` >> /tmp/kura_install.log 2>&1
    fi
  done
fi

#Get watchdog device and start refreshing
startRefreshWatchdog

#clean up old installation if present
rm -fr /opt/eclipse/* >> /tmp/kura_install.log 2>&1
rm -fr ${INSTALL_DIR}/kura* >> /tmp/kura_install.log 2>&1
rm -fr /tmp/.kura/ >> /tmp/kura_install.log 2>&1
rm /tmp/coninfo-* >> /tmp/kura_install.log 2>&1
rm /var/log/kura.log >> /tmp/kura_install.log 2>&1
rm kura-*.zip >> /tmp/kura_install.log 2>&1

echo ""
stopWatchdog
##############################################
# END PRE-INSTALL SCRIPT
##############################################

