#!/bin/bash

INSTALL_DIR=/opt/eclipse
WD_TMP_FILE=/tmp/watchdog
REFRESH_TIME=5

##############################################
# UTILITY FUNCTIONS
##############################################
# Start refresh watchdog device
function startRefreshWatchdog {
    if [ -f "${WD_TMP_FILE}" ]; then
        WATCHDOG_DEVICE=`cat ${WD_TMP_FILE}`
        refreshWatchdog &
        PID=$!
    fi
}

# Refresh watchdog device
function refreshWatchdog {
    for (( ; ; ))
    do
        echo w > ${WATCHDOG_DEVICE}
        sleep $REFRESH_TIME
    done
}

# Deactivate watchdog device if possible
function stopWatchdog {
    if [ -n "${PID}" ]; then
        kill -9 $PID >> /dev/null 2>&1
    fi
    if [ -n "${WATCHDOG_DEVICE}" ]; then
        echo V > ${WATCHDOG_DEVICE}
    fi
}
##############################################
# END UTILITY FUNCTIONS
##############################################

##############################################
# PRE-REMOVE SCRIPT
##############################################
PIDS=`pgrep java`

echo ""
echo "Uninstalling KURA..."

#Kill JVM and monit for installation
if [ -f "/var/run/kura.pid" ] ; then
  KURA_PID=`cat /var/run/kura.pid`

  for pid in "${PIDS[@]}"
  do
    if [ "$KURA_PID" == "$pid" ] ; then
      `kill $pid` >> /tmp/kura_install.log 2>&1
    fi
  done
fi

#Get watchdog device and start refreshing
startRefreshWatchdog

#Remove INIT scripts
rm /etc/init.d/kura
update-rc.d kura remove

#Delete Eclipse directory if present
if [ -d "${INSTALL_DIR}/kura/data" ] ; then
  rm -rf ${INSTALL_DIR}/kura/data
fi

if [ -d "${INSTALL_DIR}/kura" ] ; then
  rm -rf ${INSTALL_DIR}/kura
fi

stopWatchdog
