/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt.issuer;

import java.time.Instant;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import org.eclipse.kura.core.testutil.pki.TestCA.TestCAException;
import org.eclipse.kura.core.token.jwt.common.AbstractJwtScenario;
import org.eclipse.kura.core.token.jwt.common.IssuingConfig;
import org.eclipse.kura.security.token.TokenIssueRequest;
import org.junit.Test;

public class CustomClaimTypesTest extends AbstractJwtScenario {

    private static final Instant A_POINT_IN_TIME = Instant.parse("2026-09-02T08:15:30Z");

    @Test
    public void aStringClaimIsIssuedAsAJsonString() throws TestCAException {
        givenAnIssuerWithASigningKey();

        whenATokenIsRequestedWithClaim("role", "admin");

        thenIssuedTokenHasStringClaim("role", "admin");
    }

    @Test
    public void aBooleanClaimIsIssuedAsAJsonBoolean() throws TestCAException {
        givenAnIssuerWithASigningKey();

        whenATokenIsRequestedWithClaim("password_change_needed", Boolean.TRUE);

        thenIssuedTokenHasBooleanClaim("password_change_needed", true);
    }

    @Test
    public void anIntegerClaimIsIssuedAsAJsonNumber() throws TestCAException {
        givenAnIssuerWithASigningKey();

        whenATokenIsRequestedWithClaim("failed_attempts", Integer.valueOf(3));

        thenIssuedTokenHasIntegralClaim("failed_attempts", 3L);
    }

    @Test
    public void aLongClaimIsIssuedAsAJsonNumber() throws TestCAException {
        givenAnIssuerWithASigningKey();

        whenATokenIsRequestedWithClaim("sequence_number", Long.valueOf(9_000_000_000L));

        thenIssuedTokenHasIntegralClaim("sequence_number", 9_000_000_000L);
    }

    @Test
    public void aDoubleClaimIsIssuedAsAJsonNumber() throws TestCAException {
        givenAnIssuerWithASigningKey();

        whenATokenIsRequestedWithClaim("trust_score", Double.valueOf(0.75d));

        thenIssuedTokenHasDecimalClaim("trust_score", 0.75d, 0.0001d);
    }

    @Test
    public void anInstantClaimIsIssuedAsANumericDate() throws TestCAException {
        givenAnIssuerWithASigningKey();

        whenATokenIsRequestedWithClaim("enrolled_at", A_POINT_IN_TIME);

        thenIssuedTokenHasIntegralClaim("enrolled_at", A_POINT_IN_TIME.getEpochSecond());
    }

    @Test
    public void aListClaimIsIssuedAsAJsonArray() throws TestCAException {
        givenAnIssuerWithASigningKey();

        whenATokenIsRequestedWithClaim("permissions", List.of("kura.admin", "kura.cloud.connection.admin"));

        thenIssuedTokenHasStringArrayClaim("permissions", List.of("kura.admin", "kura.cloud.connection.admin"));
    }

    @Test
    public void aMapClaimIsIssuedAsAJsonObject() throws TestCAException {
        givenAnIssuerWithASigningKey();

        whenATokenIsRequestedWithClaim("device", stringKeyedMap("model", "reliagate-20-25"));

        thenIssuedTokenHasObjectClaimWithEntry("device", "model", "reliagate-20-25");
    }

    @Test
    public void aNullClaimIsIssuedAsAJsonNull() throws TestCAException {
        givenAnIssuerWithASigningKey();

        whenATokenIsRequestedWithClaim("tenant", null);

        thenIssuedTokenHasNullClaim("tenant");
    }

    @Test
    public void claimsOfDifferentTypesAreIssuedTogether() throws TestCAException {
        givenAnIssuerWithASigningKey();

        whenATokenIsRequestedWithSeveralClaimTypes();

        thenIssuedTokenHasStringClaim("role", "admin");
        thenIssuedTokenHasBooleanClaim("password_change_needed", false);
        thenIssuedTokenHasIntegralClaim("failed_attempts", 0L);
        thenIssuedTokenHasStringArrayClaim("permissions", List.of("kura.admin"));
        thenIssuedTokenHasNullClaim("tenant");
    }

    private void givenAnIssuerWithASigningKey() throws TestCAException {
        givenKeystorePrivateKeyEntry(SIGNING_ALIAS, 0);
        givenTheIssuerIsBoundToTheKeystore();
        givenTheIssuerIsActivatedWith(IssuingConfig.defaults().withSigningKeyAlias(SIGNING_ALIAS));
    }

    private void whenATokenIsRequestedWithClaim(final String name, final Object value) {
        whenATokenIsIssued(TokenIssueRequest.builder(TEST_IDENTITY) //
                .claim(name, value) //
                .build());
    }

    private void whenATokenIsRequestedWithSeveralClaimTypes() {
        whenATokenIsIssued(TokenIssueRequest.builder(TEST_IDENTITY) //
                .claim("role", "admin") //
                .claim("password_change_needed", Boolean.FALSE) //
                .claim("failed_attempts", Integer.valueOf(0)) //
                .claim("permissions", List.of("kura.admin")) //
                .claim("tenant", null) //
                .build());
    }

    private static Map<String, Object> stringKeyedMap(final String key, final Object value) {
        final Map<String, Object> map = new LinkedHashMap<>();
        map.put(key, value);

        return map;
    }

}
