/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt.issuer;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import java.time.Duration;

import org.eclipse.kura.core.token.jwt.common.IssuingConfig;
import org.junit.Test;

public class IssuingOptionsTest {

    private IssuingConfig config;
    private JwtIssuingServiceOptions options;

    @Test
    public void aPositiveMaximumLifetimeBecomesADuration() {
        givenAConfigurationWithMaximumLifetimeSeconds(3600);

        whenTheOptionsAreParsed();

        thenTheMaximumLifetimeIs(Duration.ofSeconds(3600));
    }

    @Test
    public void aMaximumLifetimeOfOneSecondBecomesADuration() {
        givenAConfigurationWithMaximumLifetimeSeconds(1);

        whenTheOptionsAreParsed();

        thenTheMaximumLifetimeIs(Duration.ofSeconds(1));
    }

    @Test
    public void aZeroMaximumLifetimeMeansNoCap() {
        givenAConfigurationWithMaximumLifetimeSeconds(0);

        whenTheOptionsAreParsed();

        thenThereIsNoMaximumLifetime();
    }

    @Test
    public void aNegativeMaximumLifetimeMeansNoCap() {
        givenAConfigurationWithMaximumLifetimeSeconds(-1);

        whenTheOptionsAreParsed();

        thenThereIsNoMaximumLifetime();
    }

    @Test
    public void theSigningKeyAliasAndTheIssuerArePassedThrough() {
        givenAConfigurationWith("gateway-signing-key", "kura.gateway");

        whenTheOptionsAreParsed();

        thenTheSigningKeyAliasIs("gateway-signing-key");
        thenTheIssuerIs("kura.gateway");
    }

    private void givenAConfigurationWithMaximumLifetimeSeconds(final int maximumLifetimeSeconds) {
        this.config = IssuingConfig.defaults().withMaximumLifetimeSeconds(maximumLifetimeSeconds);
    }

    private void givenAConfigurationWith(final String signingKeyAlias, final String issuer) {
        this.config = IssuingConfig.defaults().withSigningKeyAlias(signingKeyAlias).withIssuer(issuer);
    }

    private void whenTheOptionsAreParsed() {
        this.options = new JwtIssuingServiceOptions(this.config.toOcd());
    }

    private void thenTheMaximumLifetimeIs(final Duration expected) {
        assertTrue("expected a maximum lifetime to be configured", this.options.getMaximumLifetime().isPresent());
        assertEquals(expected, this.options.getMaximumLifetime().get());
    }

    private void thenThereIsNoMaximumLifetime() {
        assertFalse("expected no maximum lifetime to be configured", this.options.getMaximumLifetime().isPresent());
    }

    private void thenTheSigningKeyAliasIs(final String expected) {
        assertEquals(expected, this.options.getSigningKeyAlias());
    }

    private void thenTheIssuerIs(final String expected) {
        assertEquals(expected, this.options.getIssuer());
    }

}
