/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt.issuer;

import java.time.Duration;
import java.time.Instant;

import org.eclipse.kura.core.testutil.pki.TestCA.TestCAException;
import org.eclipse.kura.core.token.jwt.common.AbstractJwtScenario;
import org.eclipse.kura.core.token.jwt.common.IssuingConfig;
import org.eclipse.kura.security.token.TokenIssueRequest;
import org.junit.Test;

public class MaximumLifetimeTest extends AbstractJwtScenario {

    private static final int CAP_SECONDS = 3600;
    private static final int NO_CAP = 0;

    private Instant requestedExpiration;

    @Test
    public void aRequestedExpirationBelowTheCapIsPreserved() throws TestCAException {
        givenAnIssuerWithAMaximumLifetimeOf(CAP_SECONDS);

        whenATokenIsRequestedExpiringIn(Duration.ofSeconds(CAP_SECONDS / 2));

        thenIssuedTokenExpiresAt(this.requestedExpiration);
    }

    @Test
    public void aRequestedExpirationExactlyAtTheCapIsPreserved() throws TestCAException {
        givenAnIssuerWithAMaximumLifetimeOf(CAP_SECONDS);

        whenATokenIsRequestedExpiringIn(Duration.ofSeconds(CAP_SECONDS));

        thenIssuedTokenExpiresAt(this.requestedExpiration);
    }

    @Test
    public void aRequestedExpirationBeyondTheCapIsClampedToTheCap() throws TestCAException {
        givenAnIssuerWithAMaximumLifetimeOf(CAP_SECONDS);

        whenATokenIsRequestedExpiringIn(Duration.ofSeconds(CAP_SECONDS * 10L));

        thenIssuedTokenExpiresAtIssueTimePlus(Duration.ofSeconds(CAP_SECONDS));
    }

    @Test
    public void withoutARequestedExpirationTheCapIsApplied() throws TestCAException {
        givenAnIssuerWithAMaximumLifetimeOf(CAP_SECONDS);

        whenATokenIsIssuedFor(TEST_IDENTITY);

        thenIssuedTokenExpiresAtIssueTimePlus(Duration.ofSeconds(CAP_SECONDS));
    }

    @Test
    public void withoutACapARequestedExpirationIsPreserved() throws TestCAException {
        givenAnIssuerWithAMaximumLifetimeOf(NO_CAP);

        whenATokenIsRequestedExpiringIn(Duration.ofDays(365));

        thenIssuedTokenExpiresAt(this.requestedExpiration);
    }

    @Test
    public void withoutACapAndWithoutARequestedExpirationTheTokenNeverExpires() throws TestCAException {
        givenAnIssuerWithAMaximumLifetimeOf(NO_CAP);

        whenATokenIsIssuedFor(TEST_IDENTITY);

        thenATokenIsIssued();
        thenIssuedTokenHasNoClaim("exp");
    }

    @Test
    public void anExpirationInThePastIsPreservedAsRequested() throws TestCAException {
        givenAnIssuerWithAMaximumLifetimeOf(CAP_SECONDS);

        whenATokenIsRequestedExpiringIn(Duration.ofSeconds(-120));

        thenIssuedTokenExpiresAt(this.requestedExpiration);
    }

    private void givenAnIssuerWithAMaximumLifetimeOf(final int maximumLifetimeSeconds) throws TestCAException {
        givenKeystorePrivateKeyEntry(SIGNING_ALIAS, 0);
        givenTheIssuerIsBoundToTheKeystore();
        givenTheIssuerIsActivatedWith(IssuingConfig.defaults() //
                .withSigningKeyAlias(SIGNING_ALIAS) //
                .withMaximumLifetimeSeconds(maximumLifetimeSeconds));
    }

    private void whenATokenIsRequestedExpiringIn(final Duration lifetime) {
        this.requestedExpiration = Instant.now().plus(lifetime);

        whenATokenIsIssued(TokenIssueRequest.builder() //
                .identityName(TEST_IDENTITY) //
                .expiresAt(this.requestedExpiration) //
                .build());
    }

}
