/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt.issuer;

import java.time.Duration;
import java.time.Instant;

import org.eclipse.kura.core.testutil.pki.TestCA.TestCAException;
import org.eclipse.kura.core.token.jwt.common.AbstractJwtScenario;
import org.eclipse.kura.core.token.jwt.common.IssuingConfig;
import org.eclipse.kura.security.token.TokenIssueRequest;
import org.junit.Test;

public class NotBeforeClaimTest extends AbstractJwtScenario {

    private static final int CAP_SECONDS = 60;

    private Instant requestedNotBefore;

    @Test
    public void aRequestedNotBeforeIsIssuedAsRequested() throws TestCAException {
        givenAnIssuerWithAMaximumLifetimeOf(CAP_SECONDS);

        whenATokenIsRequestedNotValidBefore(Duration.ofSeconds(30));

        thenIssuedTokenIsNotBeforeAt(this.requestedNotBefore);
    }

    @Test
    public void aNotBeforeBeyondTheMaximumLifetimeIsNotClamped() throws TestCAException {
        givenAnIssuerWithAMaximumLifetimeOf(CAP_SECONDS);

        whenATokenIsRequestedNotValidBefore(Duration.ofSeconds(CAP_SECONDS * 100L));

        thenIssuedTokenIsNotBeforeAt(this.requestedNotBefore);
    }

    @Test
    public void aNotBeforeIsIndependentOfTheCappedExpiration() throws TestCAException {
        givenAnIssuerWithAMaximumLifetimeOf(CAP_SECONDS);

        whenATokenIsRequestedNotValidBefore(Duration.ofSeconds(CAP_SECONDS * 100L));

        thenIssuedTokenIsNotBeforeAt(this.requestedNotBefore);
        thenIssuedTokenExpiresAtIssueTimePlus(Duration.ofSeconds(CAP_SECONDS));
    }

    @Test
    public void withoutARequestedNotBeforeNoNotBeforeClaimIsIssued() throws TestCAException {
        givenAnIssuerWithAMaximumLifetimeOf(CAP_SECONDS);

        whenATokenIsIssuedFor(TEST_IDENTITY);

        thenATokenIsIssued();
        thenIssuedTokenHasNoClaim("nbf");
    }

    private void givenAnIssuerWithAMaximumLifetimeOf(final int maximumLifetimeSeconds) throws TestCAException {
        givenKeystorePrivateKeyEntry(SIGNING_ALIAS, 0);
        givenTheIssuerIsBoundToTheKeystore();
        givenTheIssuerIsActivatedWith(IssuingConfig.defaults() //
                .withSigningKeyAlias(SIGNING_ALIAS) //
                .withMaximumLifetimeSeconds(maximumLifetimeSeconds));
    }

    private void whenATokenIsRequestedNotValidBefore(final Duration delay) {
        this.requestedNotBefore = Instant.now().plus(delay);

        whenATokenIsIssued(TokenIssueRequest.builder(TEST_IDENTITY) //
                .notBefore(this.requestedNotBefore) //
                .build());
    }

}
