/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt.issuer;

import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.core.testutil.pki.TestCA.TestCAException;
import org.eclipse.kura.core.token.jwt.common.AbstractJwtScenario;
import org.eclipse.kura.core.token.jwt.common.IssuingConfig;
import org.junit.Test;

public class SigningKeyResolutionTest extends AbstractJwtScenario {

    private static final String CONFIGURED_ALIAS = "gateway-signing-key";
    private static final String ANOTHER_ALIAS = "some-other-entry";

    @Test
    public void anRsaPrivateKeyEntryEnablesIssuing() throws TestCAException {
        givenKeystorePrivateKeyEntry(CONFIGURED_ALIAS, 0);
        givenAnIssuerSigningWith(CONFIGURED_ALIAS);

        whenATokenIsIssuedFor(TEST_IDENTITY);

        thenATokenIsIssued();
    }

    @Test
    public void aMissingSigningKeyDisablesIssuing() throws TestCAException {
        givenKeystorePrivateKeyEntry(ANOTHER_ALIAS, 0);
        givenAnIssuerSigningWith(CONFIGURED_ALIAS);

        whenATokenIsIssuedFor(TEST_IDENTITY);

        thenIssuingFailedWith(KuraErrorCode.CONFIGURATION_ERROR);
        thenNoTokenIsIssued();
    }

    @Test
    public void anEmptyKeystoreDisablesIssuing() throws TestCAException {
        givenAnIssuerSigningWith(CONFIGURED_ALIAS);

        whenATokenIsIssuedFor(TEST_IDENTITY);

        thenIssuingFailedWith(KuraErrorCode.CONFIGURATION_ERROR);
        thenNoTokenIsIssued();
    }

    @Test
    public void aTrustedCertificateEntryCannotSignTokens() throws TestCAException {
        givenKeystoreTrustedCertificate(CONFIGURED_ALIAS, 0);
        givenAnIssuerSigningWith(CONFIGURED_ALIAS);

        whenATokenIsIssuedFor(TEST_IDENTITY);

        thenIssuingFailedWith(KuraErrorCode.CONFIGURATION_ERROR);
        thenNoTokenIsIssued();
    }

    @Test
    public void aNonRsaPrivateKeyEntryCannotSignTokens() throws TestCAException {
        givenKeystorePrivateKeyEntryWithNonRsaKey(CONFIGURED_ALIAS);
        givenAnIssuerSigningWith(CONFIGURED_ALIAS);

        whenATokenIsIssuedFor(TEST_IDENTITY);

        thenIssuingFailedWith(KuraErrorCode.CONFIGURATION_ERROR);
        thenNoTokenIsIssued();
    }

    @Test
    public void aKeystoreThatFailsDisablesIssuingWithoutPropagatingTheFailure() throws TestCAException {
        givenAKeystoreThatAlwaysFails();
        givenAnIssuerSigningWith(CONFIGURED_ALIAS);

        whenATokenIsIssuedFor(TEST_IDENTITY);

        thenIssuingFailedWith(KuraErrorCode.CONFIGURATION_ERROR);
        thenNoTokenIsIssued();
    }

    private void givenAnIssuerSigningWith(final String alias) {
        givenTheIssuerIsBoundToTheKeystore();
        givenTheIssuerIsActivatedWith(IssuingConfig.defaults().withSigningKeyAlias(alias));
    }

}
