/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt.issuer;

import org.eclipse.kura.core.testutil.pki.TestCA.TestCAException;
import org.eclipse.kura.core.token.jwt.common.AbstractJwtScenario;
import org.eclipse.kura.core.token.jwt.common.IssuingConfig;
import org.junit.Test;

public class SigningKeyHeaderTest extends AbstractJwtScenario {

    private static final String CONFIGURED_ALIAS = "gateway-signing-key";

    @Test
    public void theKeyIdHeaderCarriesTheConfiguredSigningAlias() throws TestCAException {
        givenAnIssuerSigningWith(CONFIGURED_ALIAS);

        whenATokenIsIssuedFor(TEST_IDENTITY);

        thenIssuedTokenHeaderHas("kid", CONFIGURED_ALIAS);
    }

    @Test
    public void tokensAreSignedWithRs256() throws TestCAException {
        givenAnIssuerSigningWith(CONFIGURED_ALIAS);

        whenATokenIsIssuedFor(TEST_IDENTITY);

        thenIssuedTokenHeaderHas("alg", "RS256");
        thenIssuedTokenHeaderHas("typ", "JWT");
    }

    @Test
    public void theIssuerClaimCarriesTheConfiguredIssuer() throws TestCAException {
        givenAnIssuerSigningWith(CONFIGURED_ALIAS);

        whenATokenIsIssuedFor(TEST_IDENTITY);

        thenIssuedTokenHasStringClaim("iss", DEFAULT_ISSUER);
    }

    private void givenAnIssuerSigningWith(final String alias) throws TestCAException {
        givenKeystorePrivateKeyEntry(alias, 0);
        givenTheIssuerIsBoundToTheKeystore();
        givenTheIssuerIsActivatedWith(IssuingConfig.defaults().withSigningKeyAlias(alias));
    }

}
