/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt.issuer;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.core.testutil.pki.TestCA.TestCAException;
import org.eclipse.kura.core.token.jwt.common.AbstractJwtScenario;
import org.eclipse.kura.core.token.jwt.common.IssuingConfig;
import org.eclipse.kura.security.token.TokenIssueRequest;
import org.junit.Test;

public class UnsupportedClaimValuesTest extends AbstractJwtScenario {

    @Test
    public void aByteArrayClaimIsRejected() throws TestCAException {
        givenAnIssuerWithASigningKey();

        whenATokenIsRequestedWithClaim("payload", new byte[] { 1, 2, 3 });

        thenIssuingFailedWith(KuraErrorCode.BAD_REQUEST);
        thenNoTokenIsIssued();
    }

    @Test
    public void anArbitraryObjectClaimIsRejected() throws TestCAException {
        givenAnIssuerWithASigningKey();

        whenATokenIsRequestedWithClaim("payload", new Object());

        thenIssuingFailedWith(KuraErrorCode.BAD_REQUEST);
        thenNoTokenIsIssued();
    }

    @Test
    public void aMapWithNonStringKeysIsRejected() throws TestCAException {
        givenAnIssuerWithASigningKey();

        whenATokenIsRequestedWithClaim("device", mapWithKey(Integer.valueOf(1)));

        thenIssuingFailedWith(KuraErrorCode.BAD_REQUEST);
        thenNoTokenIsIssued();
    }

    @Test
    public void aMapWithAnUnsupportedValueIsRejected() throws TestCAException {
        givenAnIssuerWithASigningKey();

        whenATokenIsRequestedWithClaim("device", mapWithValue(new Object()));

        thenIssuingFailedWith(KuraErrorCode.BAD_REQUEST);
        thenNoTokenIsIssued();
    }

    @Test
    public void aListWithAnUnsupportedElementIsRejected() throws TestCAException {
        givenAnIssuerWithASigningKey();

        whenATokenIsRequestedWithClaim("permissions", listWithElement(new Object()));

        thenIssuingFailedWith(KuraErrorCode.BAD_REQUEST);
        thenNoTokenIsIssued();
    }

    @Test
    public void aRejectedClaimDoesNotStopTheServiceFromIssuingLater() throws TestCAException {
        givenAnIssuerWithASigningKey();
        givenAClaimValueWasAlreadyRejected();

        whenATokenIsRequestedWithClaim("role", "admin");

        thenATokenIsIssued();
        thenIssuedTokenHasStringClaim("role", "admin");
    }

    private void givenAnIssuerWithASigningKey() throws TestCAException {
        givenKeystorePrivateKeyEntry(SIGNING_ALIAS, 0);
        givenTheIssuerIsBoundToTheKeystore();
        givenTheIssuerIsActivatedWith(IssuingConfig.defaults().withSigningKeyAlias(SIGNING_ALIAS));
    }

    private void givenAClaimValueWasAlreadyRejected() {
        whenATokenIsRequestedWithClaim("payload", new Object());

        thenIssuingFailedWith(KuraErrorCode.BAD_REQUEST);
    }

    private void whenATokenIsRequestedWithClaim(final String name, final Object value) {
        whenATokenIsIssued(TokenIssueRequest.builder(TEST_IDENTITY) //
                .claim(name, value) //
                .build());
    }

    private static Map<Object, Object> mapWithKey(final Object key) {
        final Map<Object, Object> map = new LinkedHashMap<>();
        map.put(key, "value");

        return map;
    }

    private static Map<String, Object> mapWithValue(final Object value) {
        final Map<String, Object> map = new LinkedHashMap<>();
        map.put("model", value);

        return map;
    }

    private static List<Object> listWithElement(final Object element) {
        final List<Object> list = new ArrayList<>();
        list.add(element);

        return list;
    }

}
