<?xml version="1.0" encoding="UTF-8"?>

<!--

    Copyright (c) 2017, 2026 Eurotech and/or its affiliates and others

    This program and the accompanying materials are made
    available under the terms of the Eclipse Public License 2.0
    which is available at https://www.eclipse.org/legal/epl-2.0/

    SPDX-License-Identifier: EPL-2.0

    Contributors:
     Eurotech

-->

<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
    xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.eclipse.kura</groupId>
        <artifactId>com.codeminders.hidapi-parent</artifactId>
        <version>2.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>com.codeminders.hidapi</artifactId>
    <packaging>jar</packaging>

    <name>Java API for working with Human Interface USB Devices (HID)</name>
    <description>JNI wrapper around C/C++ HIDAPI library providing simple java API to work with devices such as USB gamepads, joysticks, keyboards etc.</description>
    <url>http://code.google.com/p/javahidapi</url>

    <licenses>
        <license>
            <name>New BSD License</name>
            <url>http://opensource.org/licenses/BSD-3-Clause</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
    <scm>
        <connection>scm:hg:http://code.google.com/p/javahidapi</connection>
        <developerConnection>scm:hg:https://code.google.com/p/javahidapi</developerConnection>
        <url>http://code.google.com/p/javahidapi</url>
    </scm>
    <developers>
        <developer>
            <id>lord</id>
            <name>Vadim Zaliva</name>
            <email>lord@codeminders.com</email>
        </developer>
        <developer>
            <id>Alexander Sova</id>
            <name>Vadim Zaliva</name>
            <email>bird@codeminders.com</email>
        </developer>
        <developer>
            <id>dshmyga</id>
            <name>Denis Shmyga</name>
            <email>dshmyga@codeminders.com</email>
        </developer>
    </developers>

    <dependencies>
        <dependency>
            <groupId>org.eclipse.platform</groupId>
            <artifactId>org.eclipse.osgi</artifactId>
        </dependency>
    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
            </resource>
            <resource>
                <directory>.</directory>
                <includes>
                    <include>plugin.xml</include>
                </includes>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>biz.aQute.bnd</groupId>
                <artifactId>bnd-maven-plugin</artifactId>
                <configuration>
                    <bnd><![CDATA[
                        Bundle-SymbolicName: ${project.artifactId}
                        -includeresource: about.html,\
                            about_files=about_files/
                        Export-Package: com.codeminders.hidapi
                        ]]></bnd>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
