/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.internal.rest.provider;

import java.io.IOException;
import java.util.Arrays;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import jakarta.annotation.Priority;
import jakarta.annotation.security.RolesAllowed;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.ws.rs.Priorities;
import jakarta.ws.rs.container.ContainerRequestContext;
import jakarta.ws.rs.container.ContainerRequestFilter;
import jakarta.ws.rs.container.ResourceInfo;
import jakarta.ws.rs.core.Context;
import jakarta.ws.rs.core.Response;
import jakarta.ws.rs.core.Response.Status;
import jakarta.ws.rs.core.SecurityContext;
import jakarta.ws.rs.ext.Provider;

@Provider
@Priority(Priorities.AUTHORIZATION)
public class AuthorizationFilter implements ContainerRequestFilter {

    private static final Logger logger = LoggerFactory.getLogger(AuthorizationFilter.class);

    @Context
    private ResourceInfo resourceInfo;

    @Context
    private HttpServletRequest request;

    @Override
    public void filter(final ContainerRequestContext context) throws IOException {
        final RolesAllowed rolesAllowed = resourceInfo.getResourceMethod().getAnnotation(RolesAllowed.class);

        if (rolesAllowed != null) {
            final SecurityContext securityContext = context.getSecurityContext();
            final String rolesAllowedValue = Arrays.toString(rolesAllowed.value());

            if (securityContext == null) {
                logger.warn("Rest request rejected: missing authentication for {} {} (required roles: {})",
                        request.getMethod(), request.getRequestURI(), rolesAllowedValue);
                context.abortWith(Response.status(Status.FORBIDDEN).build());
                return;
            }

            if (securityContext.getUserPrincipal() == null) {
                logger.warn("Rest request rejected: missing user principal for {} {} (required roles: {})",
                        request.getMethod(), request.getRequestURI(), rolesAllowedValue);
                context.abortWith(Response.status(Status.FORBIDDEN).build());
                return;
            }

            for (final String role : rolesAllowed.value()) {
                if (securityContext.isUserInRole(role)) {
                    return;
                }
            }

            logger.warn("Rest request rejected: user '{}' not authorized for {} {} (required roles: {})",
                    securityContext.getUserPrincipal().getName(), request.getMethod(), request.getRequestURI(),
                    rolesAllowedValue);
            context.abortWith(Response.status(Status.FORBIDDEN).build());
        }
    }

}
