/*******************************************************************************
 * Copyright (c) 2025 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.internal.rest.provider;

import java.io.IOException;
import java.security.Principal;
import java.util.Iterator;
import java.util.Optional;
import java.util.Set;
import java.util.TreeSet;

import org.eclipse.kura.audit.AuditConstants;
import org.eclipse.kura.audit.AuditContext;
import org.eclipse.kura.identity.IdentityService;
import org.eclipse.kura.identity.Permission;
import org.eclipse.kura.rest.auth.AuthenticationProvider;

import jakarta.annotation.Priority;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.ws.rs.Priorities;
import jakarta.ws.rs.container.ContainerRequestContext;
import jakarta.ws.rs.container.ContainerRequestFilter;
import jakarta.ws.rs.core.Context;
import jakarta.ws.rs.core.SecurityContext;
import jakarta.ws.rs.ext.Provider;

@Provider
@Priority(Priorities.AUTHENTICATION)
public class AuthenticationFilter implements ContainerRequestFilter {

    private static final String KURA_ADMIN_PERMISSION = "kura.admin";

    private final Set<AuthenticationProviderHolder> authenticationProviders = new TreeSet<>();
    private IdentityService identityService;

    @Context
    private HttpServletRequest request;
    @Context
    private HttpServletResponse response;

    public void setIdentityService(final IdentityService identityService) {
        this.identityService = identityService;
    }

    public void registerAuthenticationProvider(final AuthenticationProvider authenticationProvider) {
        synchronized (this.authenticationProviders) {
            final AuthenticationProviderHolder holder = new AuthenticationProviderHolder(authenticationProvider);
            this.authenticationProviders.add(holder);
            holder.onEnabled();
        }
    }

    public void unregisterAuthenticationProvider(final AuthenticationProvider authenticationProvider) {
        synchronized (this.authenticationProviders) {
            final AuthenticationProviderHolder holder = new AuthenticationProviderHolder(authenticationProvider);
            if (this.authenticationProviders.remove(holder)) {
                holder.onDisabled();
            }
        }
    }

    @Override
    public void filter(final ContainerRequestContext requestContext) throws IOException {

        RestServiceUtils.initAuditContext(requestContext, request);

        final Optional<Principal> principal = authenticate(requestContext);
        final boolean isSecure = requestContext.getUriInfo().getRequestUri().getScheme().equals("https");

        if (principal.isPresent()) {
            final AuditContext auditContext = AuditContext.currentOrInternal();
            auditContext.getProperties().put(AuditConstants.KEY_IDENTITY.getValue(), principal.get().getName());

            requestContext.setSecurityContext(new SecurityContext() {

                final Principal currentPrincipal = principal.get();

                @Override
                public String getAuthenticationScheme() {
                    return null;
                }

                @Override
                public Principal getUserPrincipal() {
                    return currentPrincipal;
                }

                @Override
                public boolean isSecure() {
                    return isSecure;
                }

                @Override
                public boolean isUserInRole(final String role) {
                    return AuthenticationFilter.this.isUserInRole(currentPrincipal, role);
                }
            });
        }
    }

    private Optional<Principal> authenticate(final ContainerRequestContext requestContext) {
        synchronized (this.authenticationProviders) {
            for (final AuthenticationProviderHolder provider : this.authenticationProviders) {
                final Optional<Principal> principal = provider.authenticate(request, requestContext);

                if (principal.isPresent()) {
                    return principal;
                }
            }
        }

        return Optional.empty();
    }

    private boolean isUserInRole(final Principal requestUser, final String role) {
        // Unified authorization path for all identities (regular and temporary)
        try {
            this.identityService.checkPermission(requestUser.getName(), new Permission("rest." + role));
            return true;
        } catch (final Exception e) {
            try {
                this.identityService.checkPermission(requestUser.getName(), new Permission(KURA_ADMIN_PERMISSION));
                return true;
            } catch (final Exception ignored) {
                return false;
            }
        }
    }

    public void close() {
        synchronized (this.authenticationProviders) {
            final Iterator<AuthenticationProviderHolder> iter = this.authenticationProviders.iterator();
            while (iter.hasNext()) {
                iter.next().onDisabled();
                iter.remove();
            }
        }
    }
}
