/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.internal.rest.provider;

import java.util.Collections;

import jakarta.annotation.Priority;
import jakarta.ws.rs.Priorities;
import jakarta.ws.rs.container.ContainerRequestContext;
import jakarta.ws.rs.container.ContainerResponseContext;
import jakarta.ws.rs.container.ContainerResponseFilter;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response.Status;

@Priority(Priorities.USER - 1)
public class ErrorEntityFilter implements ContainerResponseFilter {

    @Override
    public void filter(final ContainerRequestContext requestContext, final ContainerResponseContext responseContext) {
        final int status = responseContext.getStatus();
        if (status < 400 || responseContext.hasEntity()) {
            return;
        }

        final Status knownStatus = Status.fromStatusCode(status);
        final String message = knownStatus == null ? "Request failed" : knownStatus.getReasonPhrase();
        responseContext.setEntity(Collections.singletonMap("message", message), null, MediaType.APPLICATION_JSON_TYPE);
    }
}
