/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.internal.rest.provider;

import java.io.IOException;
import java.util.Collections;
import java.util.Set;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import jakarta.annotation.Priority;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.ws.rs.Priorities;
import jakarta.ws.rs.container.ContainerRequestContext;
import jakarta.ws.rs.container.ContainerRequestFilter;
import jakarta.ws.rs.core.Context;
import jakarta.ws.rs.core.Response;
import jakarta.ws.rs.ext.Provider;

@Provider
@Priority(Priorities.AUTHENTICATION - 100)
class IncomingPortCheckFilter implements ContainerRequestFilter {

    private static final Logger logger = LoggerFactory.getLogger(IncomingPortCheckFilter.class);

    @Context
    private HttpServletRequest request;

    private Set<Integer> allowedPorts = Collections.emptySet();

    public void setAllowedPorts(final Set<Integer> allowedPorts) {
        this.allowedPorts = allowedPorts;
    }

    @Override
    public void filter(final ContainerRequestContext requestContext) throws IOException {

        RestServiceUtils.initAuditContext(requestContext, request);

        if (allowedPorts.isEmpty()) {
            return;
        }

        final int port = request.getLocalPort();

        if (!allowedPorts.contains(port)) {
            logger.warn("Rest request rejected on port {} for {} {} (allowed ports: {})", port, request.getMethod(),
                    request.getRequestURI(), allowedPorts);
            requestContext.abortWith(Response.status(Response.Status.NOT_FOUND).build());
        }
    }

}
