/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt.verifier;

import java.time.Instant;

import org.eclipse.kura.core.testutil.pki.TestCA.TestCAException;
import org.eclipse.kura.core.token.jwt.common.AbstractJwtScenario;
import org.eclipse.kura.core.token.jwt.common.TestKeys;
import org.eclipse.kura.core.token.jwt.common.TestToken;
import org.eclipse.kura.core.token.jwt.common.VerificationConfig;
import org.junit.Test;

import com.auth0.jwt.exceptions.SignatureVerificationException;
import com.auth0.jwt.exceptions.TokenExpiredException;

public class AnchorFailureTriageTest extends AbstractJwtScenario {

    private static final String STRANGER_ALIAS = "trusted-stranger";
    private static final String SIGNER_ALIAS = "trusted-signer";

    private static final int SIGNER_KEY = 0;
    private static final int STRANGER_KEY = 1;
    private static final int UNTRUSTED_KEY = 2;

    @Test
    public void verificationContinuesPastACertificateThatDoesNotHoldTheSigningKey() throws TestCAException {
        givenKeystoreTrustedCertificate(STRANGER_ALIAS, STRANGER_KEY);
        givenKeystoreTrustedCertificate(SIGNER_ALIAS, SIGNER_KEY);
        givenAVerifierWithoutClockSkewTolerance();

        whenATokenSignedWithIsVerified(SIGNER_KEY);

        thenTheTokenIsVerifiedFor(TEST_IDENTITY);
    }

    @Test
    public void anExpiredTokenIsNotRetriedAgainstTheRemainingCertificates() throws TestCAException {
        givenKeystoreTrustedCertificate(SIGNER_ALIAS, SIGNER_KEY);
        givenKeystoreTrustedCertificate(STRANGER_ALIAS, STRANGER_KEY);
        givenAVerifierWithoutClockSkewTolerance();

        whenAnExpiredTokenSignedWithIsVerified(SIGNER_KEY);

        thenVerificationFailedBecauseOf(TokenExpiredException.class);
        thenNoVerificationProofIsProduced();
    }

    @Test
    public void anExpiredTokenIsReportedAsExpiredEvenWhenAnotherCertificateIsTriedFirst() throws TestCAException {
        givenKeystoreTrustedCertificate(STRANGER_ALIAS, STRANGER_KEY);
        givenKeystoreTrustedCertificate(SIGNER_ALIAS, SIGNER_KEY);
        givenAVerifierWithoutClockSkewTolerance();

        whenAnExpiredTokenSignedWithIsVerified(SIGNER_KEY);

        thenVerificationFailedBecauseOf(TokenExpiredException.class);
        thenNoVerificationProofIsProduced();
    }

    @Test
    public void aTokenNoTrustedCertificateCanVerifyIsRejectedOnTheSignature() throws TestCAException {
        givenKeystoreTrustedCertificate(STRANGER_ALIAS, STRANGER_KEY);
        givenKeystoreTrustedCertificate(SIGNER_ALIAS, SIGNER_KEY);
        givenAVerifierWithoutClockSkewTolerance();

        whenATokenSignedWithIsVerified(UNTRUSTED_KEY);

        thenVerificationFailedBecauseOf(SignatureVerificationException.class);
        thenNoVerificationProofIsProduced();
    }

    private void givenAVerifierWithoutClockSkewTolerance() {
        givenTheVerifierIsBoundToTheKeystore();
        givenTheVerifierIsActivatedWith(VerificationConfig.defaults().withClockSkewSeconds(0));
    }

    private void whenATokenSignedWithIsVerified(final int keyIndex) throws TestCAException {
        whenATokenIsVerified(TestToken.builder() //
                .issuer(DEFAULT_ISSUER) //
                .subject(TEST_IDENTITY) //
                .signedWith(TestKeys.rsaPrivateKey(keyIndex)));
    }

    private void whenAnExpiredTokenSignedWithIsVerified(final int keyIndex) throws TestCAException {
        whenATokenIsVerified(TestToken.builder() //
                .issuer(DEFAULT_ISSUER) //
                .subject(TEST_IDENTITY) //
                .expiresAt(Instant.now().minusSeconds(120)) //
                .signedWith(TestKeys.rsaPrivateKey(keyIndex)));
    }

}
