/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt.verifier;

import org.eclipse.kura.core.testutil.pki.TestCA.TestCAException;
import org.eclipse.kura.core.token.jwt.common.AbstractJwtScenario;
import org.eclipse.kura.core.token.jwt.common.TestKeys;
import org.eclipse.kura.core.token.jwt.common.TestToken;
import org.eclipse.kura.core.token.jwt.common.VerificationConfig;
import org.junit.Test;

import com.auth0.jwt.exceptions.InvalidClaimException;

public class AudienceMatchingTest extends AbstractJwtScenario {

    private static final String SIGNER_ALIAS = "trusted-signer";
    private static final int SIGNER_KEY = 0;

    private static final String REST_CONSUMER = "kura.rest";
    private static final String WEB_CONSUMER = "kura.web";

    @Test
    public void anIntendedConsumerThatIsTheOnlyAudienceIsAccepted() throws TestCAException {
        givenAnActivatedVerifier();

        whenATokenForIsVerifiedOnBehalfOf(new String[] { REST_CONSUMER }, REST_CONSUMER);

        thenTheTokenIsVerifiedFor(TEST_IDENTITY);
    }

    @Test
    public void anIntendedConsumerAmongSeveralAudiencesIsAccepted() throws TestCAException {
        givenAnActivatedVerifier();

        whenATokenForIsVerifiedOnBehalfOf(new String[] { WEB_CONSUMER, REST_CONSUMER }, REST_CONSUMER);

        thenTheTokenIsVerifiedFor(TEST_IDENTITY);
    }

    @Test
    public void anIntendedConsumerMissingFromTheAudienceIsRejected() throws TestCAException {
        givenAnActivatedVerifier();

        whenATokenForIsVerifiedOnBehalfOf(new String[] { WEB_CONSUMER }, REST_CONSUMER);

        thenVerificationFailedBecauseOf(InvalidClaimException.class);
        thenNoVerificationProofIsProduced();
    }

    @Test
    public void anIntendedConsumerIsRejectedWhenTheTokenCarriesNoAudience() throws TestCAException {
        givenAnActivatedVerifier();

        whenATokenWithoutAnAudienceIsVerifiedOnBehalfOf(REST_CONSUMER);

        thenVerificationFailedBecauseOf(InvalidClaimException.class);
        thenNoVerificationProofIsProduced();
    }

    @Test
    public void theAudienceIsNotCheckedWhenNoIntendedConsumerIsRequested() throws TestCAException {
        givenAnActivatedVerifier();

        whenATokenForIsVerifiedWithoutAnIntendedConsumer(WEB_CONSUMER);

        thenTheTokenIsVerifiedFor(TEST_IDENTITY);
    }

    private void givenAnActivatedVerifier() throws TestCAException {
        givenKeystoreTrustedCertificate(SIGNER_ALIAS, SIGNER_KEY);
        givenTheVerifierIsBoundToTheKeystore();
        givenTheVerifierIsActivatedWith(VerificationConfig.defaults());
    }

    private void whenATokenForIsVerifiedOnBehalfOf(final String[] audience, final String intendedConsumer)
            throws TestCAException {

        whenATokenIsVerifiedFor(tokenWithAudience(audience), intendedConsumer);
    }

    private void whenATokenForIsVerifiedWithoutAnIntendedConsumer(final String audience) throws TestCAException {
        whenATokenIsVerified(tokenWithAudience(new String[] { audience }));
    }

    private void whenATokenWithoutAnAudienceIsVerifiedOnBehalfOf(final String intendedConsumer)
            throws TestCAException {

        whenATokenIsVerifiedFor(TestToken.builder() //
                .issuer(DEFAULT_ISSUER) //
                .subject(TEST_IDENTITY) //
                .signedWith(TestKeys.rsaPrivateKey(SIGNER_KEY)), intendedConsumer);
    }

    private static String tokenWithAudience(final String[] audience) throws TestCAException {
        return TestToken.builder() //
                .issuer(DEFAULT_ISSUER) //
                .subject(TEST_IDENTITY) //
                .audience(audience) //
                .signedWith(TestKeys.rsaPrivateKey(SIGNER_KEY));
    }

}
