/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt.verifier;

import java.time.Instant;

import org.eclipse.kura.core.testutil.pki.TestCA.TestCAException;
import org.eclipse.kura.core.token.jwt.common.AbstractJwtScenario;
import org.eclipse.kura.core.token.jwt.common.TestKeys;
import org.eclipse.kura.core.token.jwt.common.TestToken;
import org.eclipse.kura.core.token.jwt.common.VerificationConfig;
import org.junit.Test;

public class CertificateValidityTest extends AbstractJwtScenario {

    private static final String SIGNER_ALIAS = "trusted-signer";
    private static final String STRANGER_ALIAS = "trusted-stranger";

    private static final int SIGNER_KEY = 0;
    private static final int STRANGER_KEY = 1;

    @Test
    public void anExpiredCertificateIsNotUsedWhenAValidCertificateIsRequired() throws TestCAException {
        givenAnExpiredCertificateFor(SIGNER_ALIAS, SIGNER_KEY);
        givenAVerifierRequiringValidCertificates(true);

        whenATokenSignedWithIsVerified(SIGNER_KEY);

        thenVerificationFailedWithoutAnUnderlyingCause();
        thenNoVerificationProofIsProduced();
    }

    @Test
    public void aNotYetValidCertificateIsNotUsedWhenAValidCertificateIsRequired() throws TestCAException {
        givenANotYetValidCertificateFor(SIGNER_ALIAS, SIGNER_KEY);
        givenAVerifierRequiringValidCertificates(true);

        whenATokenSignedWithIsVerified(SIGNER_KEY);

        thenVerificationFailedWithoutAnUnderlyingCause();
        thenNoVerificationProofIsProduced();
    }

    @Test
    public void anExpiredCertificateIsUsedWhenNoValidCertificateIsRequired() throws TestCAException {
        givenAnExpiredCertificateFor(SIGNER_ALIAS, SIGNER_KEY);
        givenAVerifierRequiringValidCertificates(false);

        whenATokenSignedWithIsVerified(SIGNER_KEY);

        thenTheTokenIsVerifiedFor(TEST_IDENTITY);
    }

    @Test
    public void aCertificateOutsideItsValidityPeriodDoesNotBlockTheOthers() throws TestCAException {
        givenAnExpiredCertificateFor(STRANGER_ALIAS, STRANGER_KEY);
        givenKeystoreTrustedCertificate(SIGNER_ALIAS, SIGNER_KEY);
        givenAVerifierRequiringValidCertificates(true);

        whenATokenSignedWithIsVerified(SIGNER_KEY);

        thenTheTokenIsVerifiedFor(TEST_IDENTITY);
    }

    @Test
    public void whenEveryCertificateIsOutsideItsValidityPeriodNoSignatureFailureIsReported() throws TestCAException {
        givenAnExpiredCertificateFor(STRANGER_ALIAS, STRANGER_KEY);
        givenANotYetValidCertificateFor(SIGNER_ALIAS, SIGNER_KEY);
        givenAVerifierRequiringValidCertificates(true);

        whenATokenSignedWithIsVerified(SIGNER_KEY);

        thenVerificationFailedWithoutAnUnderlyingCause();
        thenNoVerificationProofIsProduced();
    }

    private void givenAnExpiredCertificateFor(final String alias, final int keyIndex) throws TestCAException {
        final Instant now = Instant.now();

        givenKeystoreTrustedCertificate(alias, keyIndex, now.minusSeconds(3600), now.minusSeconds(1800));
    }

    private void givenANotYetValidCertificateFor(final String alias, final int keyIndex) throws TestCAException {
        final Instant now = Instant.now();

        givenKeystoreTrustedCertificate(alias, keyIndex, now.plusSeconds(1800), now.plusSeconds(3600));
    }

    private void givenAVerifierRequiringValidCertificates(final boolean requireValidCertificate) {
        givenTheVerifierIsBoundToTheKeystore();
        givenTheVerifierIsActivatedWith(VerificationConfig.defaults() //
                .withRequireValidCertificate(requireValidCertificate));
    }

    private void whenATokenSignedWithIsVerified(final int keyIndex) throws TestCAException {
        whenATokenIsVerified(TestToken.builder() //
                .issuer(DEFAULT_ISSUER) //
                .subject(TEST_IDENTITY) //
                .signedWith(TestKeys.rsaPrivateKey(keyIndex)));
    }

}
