/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt.verifier;

import java.time.Instant;

import org.eclipse.kura.core.testutil.pki.TestCA.TestCAException;
import org.eclipse.kura.core.token.jwt.common.AbstractJwtScenario;
import org.eclipse.kura.core.token.jwt.common.TestKeys;
import org.eclipse.kura.core.token.jwt.common.TestToken;
import org.eclipse.kura.core.token.jwt.common.VerificationConfig;
import org.junit.Test;

import com.auth0.jwt.exceptions.InvalidClaimException;
import com.auth0.jwt.exceptions.TokenExpiredException;

public class ClockSkewToleranceTest extends AbstractJwtScenario {

    private static final String SIGNER_ALIAS = "trusted-signer";
    private static final int SIGNER_KEY = 0;

    private static final int TOLERANCE_SECONDS = 30;
    private static final int NO_TOLERANCE = 0;

    private static final long WITHIN_TOLERANCE_SECONDS = 10L;
    private static final long BEYOND_TOLERANCE_SECONDS = 120L;

    @Test
    public void aTokenThatExpiredWithinTheToleranceIsAccepted() throws TestCAException {
        givenAVerifierToleratingASkewOf(TOLERANCE_SECONDS);

        whenATokenExpiringInIsVerified(-WITHIN_TOLERANCE_SECONDS);

        thenTheTokenIsVerifiedFor(TEST_IDENTITY);
    }

    @Test
    public void aTokenThatExpiredBeyondTheToleranceIsRejected() throws TestCAException {
        givenAVerifierToleratingASkewOf(TOLERANCE_SECONDS);

        whenATokenExpiringInIsVerified(-BEYOND_TOLERANCE_SECONDS);

        thenVerificationFailedBecauseOf(TokenExpiredException.class);
        thenNoVerificationProofIsProduced();
    }

    @Test
    public void aTokenNotYetValidWithinTheToleranceIsAccepted() throws TestCAException {
        givenAVerifierToleratingASkewOf(TOLERANCE_SECONDS);

        whenATokenNotValidBeforeIsVerified(WITHIN_TOLERANCE_SECONDS);

        thenTheTokenIsVerifiedFor(TEST_IDENTITY);
    }

    @Test
    public void aTokenNotYetValidBeyondTheToleranceIsRejected() throws TestCAException {
        givenAVerifierToleratingASkewOf(TOLERANCE_SECONDS);

        whenATokenNotValidBeforeIsVerified(BEYOND_TOLERANCE_SECONDS);

        thenVerificationFailedBecauseOf(InvalidClaimException.class);
        thenNoVerificationProofIsProduced();
    }

    @Test
    public void aTokenIssuedInTheFutureWithinTheToleranceIsAccepted() throws TestCAException {
        givenAVerifierToleratingASkewOf(TOLERANCE_SECONDS);

        whenATokenIssuedInIsVerified(WITHIN_TOLERANCE_SECONDS);

        thenTheTokenIsVerifiedFor(TEST_IDENTITY);
    }

    @Test
    public void aTokenIssuedInTheFutureBeyondTheToleranceIsRejected() throws TestCAException {
        givenAVerifierToleratingASkewOf(TOLERANCE_SECONDS);

        whenATokenIssuedInIsVerified(BEYOND_TOLERANCE_SECONDS);

        thenVerificationFailedBecauseOf(InvalidClaimException.class);
        thenNoVerificationProofIsProduced();
    }

    @Test
    public void withoutAnyToleranceATokenThatJustExpiredIsRejected() throws TestCAException {
        givenAVerifierToleratingASkewOf(NO_TOLERANCE);

        whenATokenExpiringInIsVerified(-5L);

        thenVerificationFailedBecauseOf(TokenExpiredException.class);
        thenNoVerificationProofIsProduced();
    }

    @Test
    public void withoutAnyToleranceATokenThatIsStillValidIsAccepted() throws TestCAException {
        givenAVerifierToleratingASkewOf(NO_TOLERANCE);

        whenATokenExpiringInIsVerified(BEYOND_TOLERANCE_SECONDS);

        thenTheTokenIsVerifiedFor(TEST_IDENTITY);
    }

    private void givenAVerifierToleratingASkewOf(final int clockSkewSeconds) throws TestCAException {
        givenKeystoreTrustedCertificate(SIGNER_ALIAS, SIGNER_KEY);
        givenTheVerifierIsBoundToTheKeystore();
        givenTheVerifierIsActivatedWith(VerificationConfig.defaults().withClockSkewSeconds(clockSkewSeconds));
    }

    private void whenATokenExpiringInIsVerified(final long secondsFromNow) throws TestCAException {
        whenATokenIsVerified(TestToken.builder() //
                .issuer(DEFAULT_ISSUER) //
                .subject(TEST_IDENTITY) //
                .expiresAt(Instant.now().plusSeconds(secondsFromNow)) //
                .signedWith(TestKeys.rsaPrivateKey(SIGNER_KEY)));
    }

    private void whenATokenNotValidBeforeIsVerified(final long secondsFromNow) throws TestCAException {
        whenATokenIsVerified(TestToken.builder() //
                .issuer(DEFAULT_ISSUER) //
                .subject(TEST_IDENTITY) //
                .notBefore(Instant.now().plusSeconds(secondsFromNow)) //
                .signedWith(TestKeys.rsaPrivateKey(SIGNER_KEY)));
    }

    private void whenATokenIssuedInIsVerified(final long secondsFromNow) throws TestCAException {
        whenATokenIsVerified(TestToken.builder() //
                .issuer(DEFAULT_ISSUER) //
                .subject(TEST_IDENTITY) //
                .issuedAt(Instant.now().plusSeconds(secondsFromNow)) //
                .signedWith(TestKeys.rsaPrivateKey(SIGNER_KEY)));
    }

}
