/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt.verifier;

import org.eclipse.kura.core.testutil.pki.TestCA.TestCAException;
import org.eclipse.kura.core.token.jwt.common.AbstractJwtScenario;
import org.eclipse.kura.core.token.jwt.common.TestKeys;
import org.eclipse.kura.core.token.jwt.common.TestToken;
import org.eclipse.kura.core.token.jwt.common.VerificationConfig;
import org.junit.Test;

import com.auth0.jwt.exceptions.SignatureVerificationException;

public class KeyIdSelectionTest extends AbstractJwtScenario {

    private static final String SIGNER_ALIAS = "trusted-signer";
    private static final String STRANGER_ALIAS = "trusted-stranger";
    private static final String UNKNOWN_ALIAS = "an-alias-this-truststore-does-not-have";

    private static final int SIGNER_KEY = 0;
    private static final int STRANGER_KEY = 1;
    private static final int UNTRUSTED_KEY = 2;

    @Test
    public void aKeyIdNamingTheCertificateThatHoldsTheKeyVerifiesTheToken() throws TestCAException {
        givenKeystoreTrustedCertificate(SIGNER_ALIAS, SIGNER_KEY);
        givenAnActivatedVerifier();

        whenATokenSignedWithIsVerified(SIGNER_KEY, SIGNER_ALIAS);

        thenTheTokenIsVerifiedFor(TEST_IDENTITY);
    }

    @Test
    public void aKeyIdNamingACertificateThatDoesNotHoldTheKeyFallsBackToTheOthers() throws TestCAException {
        givenKeystoreTrustedCertificate(STRANGER_ALIAS, STRANGER_KEY);
        givenKeystoreTrustedCertificate(SIGNER_ALIAS, SIGNER_KEY);
        givenAnActivatedVerifier();

        whenATokenSignedWithIsVerified(SIGNER_KEY, STRANGER_ALIAS);

        thenTheTokenIsVerifiedFor(TEST_IDENTITY);
    }

    @Test
    public void anUnresolvableKeyIdFallsBackToEveryTrustedCertificate() throws TestCAException {
        givenKeystoreTrustedCertificate(STRANGER_ALIAS, STRANGER_KEY);
        givenKeystoreTrustedCertificate(SIGNER_ALIAS, SIGNER_KEY);
        givenAnActivatedVerifier();

        whenATokenSignedWithIsVerified(SIGNER_KEY, UNKNOWN_ALIAS);

        thenTheTokenIsVerifiedFor(TEST_IDENTITY);
    }

    @Test
    public void aTokenWithoutAKeyIdIsVerifiedAgainstEveryTrustedCertificate() throws TestCAException {
        givenKeystoreTrustedCertificate(STRANGER_ALIAS, STRANGER_KEY);
        givenKeystoreTrustedCertificate(SIGNER_ALIAS, SIGNER_KEY);
        givenAnActivatedVerifier();

        whenATokenWithoutAKeyIdSignedWithIsVerified(SIGNER_KEY);

        thenTheTokenIsVerifiedFor(TEST_IDENTITY);
    }

    @Test
    public void aKeyIdCannotMakeAnUntrustedSignatureAcceptable() throws TestCAException {
        givenKeystoreTrustedCertificate(SIGNER_ALIAS, SIGNER_KEY);
        givenAnActivatedVerifier();

        whenATokenSignedWithIsVerified(UNTRUSTED_KEY, SIGNER_ALIAS);

        thenVerificationFailedBecauseOf(SignatureVerificationException.class);
        thenNoVerificationProofIsProduced();
    }

    private void givenAnActivatedVerifier() {
        givenTheVerifierIsBoundToTheKeystore();
        givenTheVerifierIsActivatedWith(VerificationConfig.defaults());
    }

    private void whenATokenSignedWithIsVerified(final int keyIndex, final String keyId) throws TestCAException {
        whenATokenIsVerified(TestToken.builder() //
                .issuer(DEFAULT_ISSUER) //
                .subject(TEST_IDENTITY) //
                .keyId(keyId) //
                .signedWith(TestKeys.rsaPrivateKey(keyIndex)));
    }

    private void whenATokenWithoutAKeyIdSignedWithIsVerified(final int keyIndex) throws TestCAException {
        whenATokenIsVerified(TestToken.builder() //
                .issuer(DEFAULT_ISSUER) //
                .subject(TEST_IDENTITY) //
                .signedWith(TestKeys.rsaPrivateKey(keyIndex)));
    }

}
