/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt.verifier;

import org.eclipse.kura.core.testutil.pki.TestCA.TestCAException;
import org.eclipse.kura.core.token.jwt.common.AbstractJwtScenario;
import org.eclipse.kura.core.token.jwt.common.TestKeys;
import org.eclipse.kura.core.token.jwt.common.TestToken;
import org.eclipse.kura.core.token.jwt.common.VerificationConfig;
import org.junit.Test;

import com.auth0.jwt.exceptions.AlgorithmMismatchException;
import com.auth0.jwt.exceptions.JWTDecodeException;
import com.auth0.jwt.exceptions.SignatureVerificationException;

public class MalformedTokenTest extends AbstractJwtScenario {

    private static final String SIGNER_ALIAS = "trusted-signer";
    private static final int SIGNER_KEY = 0;

    private static final String NOT_A_TOKEN = "this-is-not-a-jwt";
    private static final String TOO_FEW_SEGMENTS = "aGVhZGVy.cGF5bG9hZA";
    private static final String TOO_MANY_SEGMENTS = "aGVhZGVy.cGF5bG9hZA.c2lnbmF0dXJl.ZXh0cmE";
    private static final String NOT_BASE64_SEGMENTS = "!!!.!!!.!!!";

    @Test
    public void aStringThatIsNotATokenIsRejectedAsAnAuthenticationFailure() throws TestCAException {
        givenAnActivatedVerifier();

        whenATokenIsVerified(NOT_A_TOKEN);

        thenVerificationFailedBecauseOf(JWTDecodeException.class);
        thenNoVerificationProofIsProduced();
    }

    @Test
    public void aTokenWithTooFewSegmentsIsRejectedAsAnAuthenticationFailure() throws TestCAException {
        givenAnActivatedVerifier();

        whenATokenIsVerified(TOO_FEW_SEGMENTS);

        thenVerificationFailedBecauseOf(JWTDecodeException.class);
        thenNoVerificationProofIsProduced();
    }

    @Test
    public void aTokenWithTooManySegmentsIsRejectedAsAnAuthenticationFailure() throws TestCAException {
        givenAnActivatedVerifier();

        whenATokenIsVerified(TOO_MANY_SEGMENTS);

        thenVerificationFailedBecauseOf(JWTDecodeException.class);
        thenNoVerificationProofIsProduced();
    }

    @Test
    public void aTokenWhoseSegmentsAreNotBase64IsRejectedAsAnAuthenticationFailure() throws TestCAException {
        givenAnActivatedVerifier();

        whenATokenIsVerified(NOT_BASE64_SEGMENTS);

        thenVerificationFailedBecauseOf(JWTDecodeException.class);
        thenNoVerificationProofIsProduced();
    }

    @Test
    public void aTokenWithATamperedHeaderIsRejected() throws TestCAException {
        givenAnActivatedVerifier();

        whenATokenIsVerified(TestToken.withTamperedHeader(aWellFormedToken()));

        thenVerificationFailedBecauseOf(SignatureVerificationException.class);
        thenNoVerificationProofIsProduced();
    }

    @Test
    public void aTokenWithATamperedPayloadIsRejected() throws TestCAException {
        givenAnActivatedVerifier();

        whenATokenIsVerified(TestToken.withTamperedPayload(aWellFormedToken()));

        thenVerificationFailedBecauseOf(SignatureVerificationException.class);
        thenNoVerificationProofIsProduced();
    }

    @Test
    public void aTokenWithATamperedSignatureIsRejected() throws TestCAException {
        givenAnActivatedVerifier();

        whenATokenIsVerified(TestToken.withTamperedSignature(aWellFormedToken()));

        thenVerificationFailedBecauseOf(SignatureVerificationException.class);
        thenNoVerificationProofIsProduced();
    }

    @Test
    public void aTokenSignedWithADifferentAlgorithmIsRejected() throws TestCAException {
        givenAnActivatedVerifier();

        whenATokenIsVerified(TestToken.builder() //
                .issuer(DEFAULT_ISSUER) //
                .subject(TEST_IDENTITY) //
                .signedWith(TestKeys.ecdsa().getPrivate()));

        thenVerificationFailedBecauseOf(AlgorithmMismatchException.class);
        thenNoVerificationProofIsProduced();
    }

    @Test
    public void aWellFormedTokenIsStillAcceptedAfterAMalformedOne() throws TestCAException {
        givenAnActivatedVerifier();
        givenAMalformedTokenWasAlreadyRejected();

        whenATokenIsVerified(aWellFormedToken());

        thenTheTokenIsVerifiedFor(TEST_IDENTITY);
    }

    private void givenAnActivatedVerifier() throws TestCAException {
        givenKeystoreTrustedCertificate(SIGNER_ALIAS, SIGNER_KEY);
        givenTheVerifierIsBoundToTheKeystore();
        givenTheVerifierIsActivatedWith(VerificationConfig.defaults());
    }

    private void givenAMalformedTokenWasAlreadyRejected() {
        whenATokenIsVerified(NOT_A_TOKEN);

        thenVerificationFailedBecauseOf(JWTDecodeException.class);
    }

    private static String aWellFormedToken() throws TestCAException {
        return TestToken.builder() //
                .issuer(DEFAULT_ISSUER) //
                .subject(TEST_IDENTITY) //
                .signedWith(TestKeys.rsaPrivateKey(SIGNER_KEY));
    }

}
