/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt.verifier;

import org.eclipse.kura.core.testutil.pki.TestCA.TestCAException;
import org.eclipse.kura.core.token.jwt.common.AbstractJwtScenario;
import org.eclipse.kura.core.token.jwt.common.TestKeys;
import org.eclipse.kura.core.token.jwt.common.TestToken;
import org.eclipse.kura.core.token.jwt.common.VerificationConfig;
import org.junit.Test;

public class SubjectClaimTest extends AbstractJwtScenario {

    private static final String SIGNER_ALIAS = "trusted-signer";
    private static final int SIGNER_KEY = 0;

    @Test
    public void aTokenCarryingASubjectIsVerifiedForThatIdentity() throws TestCAException {
        givenAnActivatedVerifier();

        whenATokenWithSubjectIsVerified("another.user");

        thenTheTokenIsVerifiedFor("another.user");
    }

    @Test
    public void aTokenWithoutASubjectIsRejected() throws TestCAException {
        givenAnActivatedVerifier();

        whenATokenWithoutASubjectIsVerified();

        thenVerificationFailedAsAuthenticationFailure();
        thenNoVerificationProofIsProduced();
    }

    @Test
    public void aTokenWithAnEmptySubjectIsRejected() throws TestCAException {
        givenAnActivatedVerifier();

        whenATokenWithSubjectIsVerified("");

        thenVerificationFailedAsAuthenticationFailure();
        thenNoVerificationProofIsProduced();
    }

    @Test
    public void aTokenWithABlankSubjectIsRejected() throws TestCAException {
        givenAnActivatedVerifier();

        whenATokenWithSubjectIsVerified("   ");

        thenVerificationFailedAsAuthenticationFailure();
        thenNoVerificationProofIsProduced();
    }

    @Test
    public void theRejectionOfAMissingSubjectCarriesNoUnderlyingCause() throws TestCAException {
        givenAnActivatedVerifier();

        whenATokenWithoutASubjectIsVerified();

        thenVerificationFailedWithoutAnUnderlyingCause();
    }

    private void givenAnActivatedVerifier() throws TestCAException {
        givenKeystoreTrustedCertificate(SIGNER_ALIAS, SIGNER_KEY);
        givenTheVerifierIsBoundToTheKeystore();
        givenTheVerifierIsActivatedWith(VerificationConfig.defaults());
    }

    private void whenATokenWithSubjectIsVerified(final String subject) throws TestCAException {
        whenATokenIsVerified(TestToken.builder() //
                .issuer(DEFAULT_ISSUER) //
                .subject(subject) //
                .signedWith(TestKeys.rsaPrivateKey(SIGNER_KEY)));
    }

    private void whenATokenWithoutASubjectIsVerified() throws TestCAException {
        whenATokenIsVerified(TestToken.builder() //
                .issuer(DEFAULT_ISSUER) //
                .signedWith(TestKeys.rsaPrivateKey(SIGNER_KEY)));
    }

}
