/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt.verifier;

import org.eclipse.kura.core.testutil.pki.TestCA.TestCAException;
import org.eclipse.kura.core.token.jwt.common.AbstractJwtScenario;
import org.eclipse.kura.core.token.jwt.common.TestKeys;
import org.eclipse.kura.core.token.jwt.common.TestToken;
import org.eclipse.kura.core.token.jwt.common.VerificationConfig;
import org.junit.Test;

import com.auth0.jwt.exceptions.InvalidClaimException;

public class TrustedIssuersTest extends AbstractJwtScenario {

    private static final String SIGNER_ALIAS = "trusted-signer";
    private static final int SIGNER_KEY = 0;

    private static final String CONFIGURED_ISSUERS = "kura,kura.gateway";
    private static final String PADDED_ISSUERS = " kura.gateway , kura.cloud ";

    @Test
    public void anyIssuerIsAcceptedWhenNoTrustedIssuerIsConfigured() throws TestCAException {
        givenAVerifierTrustingIssuers("");

        whenATokenIssuedByIsVerified("someone.else");

        thenTheTokenIsVerifiedFor(TEST_IDENTITY);
    }

    @Test
    public void aTokenWithoutAnIssuerIsAcceptedWhenNoTrustedIssuerIsConfigured() throws TestCAException {
        givenAVerifierTrustingIssuers("");

        whenATokenWithoutAnIssuerIsVerified();

        thenTheTokenIsVerifiedFor(TEST_IDENTITY);
    }

    @Test
    public void aConfiguredIssuerIsAccepted() throws TestCAException {
        givenAVerifierTrustingIssuers(CONFIGURED_ISSUERS);

        whenATokenIssuedByIsVerified("kura.gateway");

        thenTheTokenIsVerifiedFor(TEST_IDENTITY);
    }

    @Test
    public void anIssuerThatIsNotConfiguredIsRejected() throws TestCAException {
        givenAVerifierTrustingIssuers(CONFIGURED_ISSUERS);

        whenATokenIssuedByIsVerified("someone.else");

        thenVerificationFailedBecauseOf(InvalidClaimException.class);
        thenNoVerificationProofIsProduced();
    }

    @Test
    public void anIssuerThatOnlySharesAPrefixWithAConfiguredOneIsRejected() throws TestCAException {
        givenAVerifierTrustingIssuers(CONFIGURED_ISSUERS);

        whenATokenIssuedByIsVerified("kura.gateway.attacker");

        thenVerificationFailedBecauseOf(InvalidClaimException.class);
        thenNoVerificationProofIsProduced();
    }

    @Test
    public void aTokenWithoutAnIssuerIsRejectedWhenTrustedIssuersAreConfigured() throws TestCAException {
        givenAVerifierTrustingIssuers(CONFIGURED_ISSUERS);

        whenATokenWithoutAnIssuerIsVerified();

        thenVerificationFailedBecauseOf(InvalidClaimException.class);
        thenNoVerificationProofIsProduced();
    }

    @Test
    public void whitespaceAroundAConfiguredIssuerIsIgnored() throws TestCAException {
        givenAVerifierTrustingIssuers(PADDED_ISSUERS);

        whenATokenIssuedByIsVerified("kura.gateway");

        thenTheTokenIsVerifiedFor(TEST_IDENTITY);
    }

    private void givenAVerifierTrustingIssuers(final String trustedIssuers) throws TestCAException {
        givenKeystoreTrustedCertificate(SIGNER_ALIAS, SIGNER_KEY);
        givenTheVerifierIsBoundToTheKeystore();
        givenTheVerifierIsActivatedWith(VerificationConfig.defaults().withTrustedIssuers(trustedIssuers));
    }

    private void whenATokenIssuedByIsVerified(final String issuer) throws TestCAException {
        whenATokenIsVerified(TestToken.builder() //
                .issuer(issuer) //
                .subject(TEST_IDENTITY) //
                .signedWith(TestKeys.rsaPrivateKey(SIGNER_KEY)));
    }

    private void whenATokenWithoutAnIssuerIsVerified() throws TestCAException {
        whenATokenIsVerified(TestToken.builder() //
                .subject(TEST_IDENTITY) //
                .signedWith(TestKeys.rsaPrivateKey(SIGNER_KEY)));
    }

}
