/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt.verifier;

import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.core.testutil.pki.TestCA.TestCAException;
import org.eclipse.kura.core.token.jwt.common.AbstractJwtScenario;
import org.eclipse.kura.core.token.jwt.common.TestKeys;
import org.eclipse.kura.core.token.jwt.common.TestToken;
import org.eclipse.kura.core.token.jwt.common.VerificationConfig;
import org.junit.Test;

import com.auth0.jwt.exceptions.SignatureVerificationException;

public class TrustAnchorLoadingTest extends AbstractJwtScenario {

    private static final String LISTED_ALIAS = "trusted-listed";
    private static final String UNLISTED_ALIAS = "trusted-unlisted";
    private static final String NON_RSA_ALIAS = "trusted-elliptic-curve";
    private static final String SECRET_ALIAS = "a-secret-key";

    private static final int LISTED_KEY = 0;
    private static final int UNLISTED_KEY = 1;

    @Test
    public void aTrustedCertificateEntryBecomesATrustAnchor() throws TestCAException {
        givenKeystoreTrustedCertificate(LISTED_ALIAS, LISTED_KEY);
        givenAVerifierRestrictedToAliases("");

        whenATokenSignedWithIsVerified(LISTED_KEY);

        thenTheTokenIsVerifiedFor(TEST_IDENTITY);
    }

    @Test
    public void thePrivateKeyEntryCertificateBecomesATrustAnchor() throws TestCAException {
        givenKeystorePrivateKeyEntry(LISTED_ALIAS, LISTED_KEY);
        givenAVerifierRestrictedToAliases("");

        whenATokenSignedWithIsVerified(LISTED_KEY);

        thenTheTokenIsVerifiedFor(TEST_IDENTITY);
    }

    @Test
    public void everyUsableCertificateIsATrustAnchorWhenNoAliasIsListed() throws TestCAException {
        givenKeystoreTrustedCertificate(LISTED_ALIAS, LISTED_KEY);
        givenKeystoreTrustedCertificate(UNLISTED_ALIAS, UNLISTED_KEY);
        givenAVerifierRestrictedToAliases("");

        whenATokenSignedWithIsVerified(UNLISTED_KEY);

        thenTheTokenIsVerifiedFor(TEST_IDENTITY);
    }

    @Test
    public void aListedAliasIsUsedForVerification() throws TestCAException {
        givenKeystoreTrustedCertificate(LISTED_ALIAS, LISTED_KEY);
        givenKeystoreTrustedCertificate(UNLISTED_ALIAS, UNLISTED_KEY);
        givenAVerifierRestrictedToAliases(LISTED_ALIAS);

        whenATokenSignedWithIsVerified(LISTED_KEY);

        thenTheTokenIsVerifiedFor(TEST_IDENTITY);
    }

    @Test
    public void anAliasThatIsNotListedIsNotUsedForVerification() throws TestCAException {
        givenKeystoreTrustedCertificate(LISTED_ALIAS, LISTED_KEY);
        givenKeystoreTrustedCertificate(UNLISTED_ALIAS, UNLISTED_KEY);
        givenAVerifierRestrictedToAliases(LISTED_ALIAS);

        whenATokenSignedWithIsVerified(UNLISTED_KEY);

        thenVerificationFailedBecauseOf(SignatureVerificationException.class);
        thenNoVerificationProofIsProduced();
    }

    @Test
    public void aTrustStoreHoldingOnlyANonRsaCertificateLeavesVerificationUnavailable() throws TestCAException {
        givenKeystoreTrustedCertificateForNonRsaKey(NON_RSA_ALIAS);
        givenAVerifierRestrictedToAliases("");

        whenATokenSignedWithIsVerified(LISTED_KEY);

        thenVerificationFailedWith(KuraErrorCode.CONFIGURATION_ERROR);
        thenNoVerificationProofIsProduced();
    }

    @Test
    public void aTrustStoreHoldingOnlyASecretKeyLeavesVerificationUnavailable() throws TestCAException {
        givenKeystoreSecretKeyEntry(SECRET_ALIAS);
        givenAVerifierRestrictedToAliases("");

        whenATokenSignedWithIsVerified(LISTED_KEY);

        thenVerificationFailedWith(KuraErrorCode.CONFIGURATION_ERROR);
        thenNoVerificationProofIsProduced();
    }

    @Test
    public void anEmptyTrustStoreLeavesVerificationUnavailable() throws TestCAException {
        givenAVerifierRestrictedToAliases("");

        whenATokenSignedWithIsVerified(LISTED_KEY);

        thenVerificationFailedWith(KuraErrorCode.CONFIGURATION_ERROR);
        thenNoVerificationProofIsProduced();
    }

    @Test
    public void anAliasListThatMatchesNothingLeavesVerificationUnavailable() throws TestCAException {
        givenKeystoreTrustedCertificate(UNLISTED_ALIAS, UNLISTED_KEY);
        givenAVerifierRestrictedToAliases("an-alias-that-is-not-in-the-truststore");

        whenATokenSignedWithIsVerified(UNLISTED_KEY);

        thenVerificationFailedWith(KuraErrorCode.CONFIGURATION_ERROR);
        thenNoVerificationProofIsProduced();
    }

    @Test
    public void aKeystoreThatFailsLeavesVerificationUnavailableWithoutPropagatingTheFailure() throws TestCAException {
        givenAKeystoreThatAlwaysFails();
        givenAVerifierRestrictedToAliases("");

        whenATokenSignedWithIsVerified(LISTED_KEY);

        thenVerificationFailedWith(KuraErrorCode.CONFIGURATION_ERROR);
        thenNoVerificationProofIsProduced();
    }

    private void givenAVerifierRestrictedToAliases(final String verificationKeyAliases) {
        givenTheVerifierIsBoundToTheKeystore();
        givenTheVerifierIsActivatedWith(VerificationConfig.defaults() //
                .withVerificationKeyAliases(verificationKeyAliases));
    }

    private void whenATokenSignedWithIsVerified(final int keyIndex) throws TestCAException {
        whenATokenIsVerified(TestToken.builder() //
                .issuer(DEFAULT_ISSUER) //
                .subject(TEST_IDENTITY) //
                .signedWith(TestKeys.rsaPrivateKey(keyIndex)));
    }

}
