/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt.verifier;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertThrows;
import static org.junit.Assert.assertTrue;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

import org.eclipse.kura.core.token.jwt.common.VerificationConfig;
import org.junit.Test;

public class VerificationOptionsTest {

    private VerificationConfig config;
    private JwtVerificationServiceOptions options;

    @Test
    public void aNullListYieldsNoTrustedIssuers() {
        givenTrustedIssuers(null);

        whenTheOptionsAreParsed();

        thenThereAreNoTrustedIssuers();
    }

    @Test
    public void anEmptyListYieldsNoTrustedIssuers() {
        givenTrustedIssuers("");

        whenTheOptionsAreParsed();

        thenThereAreNoTrustedIssuers();
    }

    @Test
    public void aBlankListYieldsNoTrustedIssuers() {
        givenTrustedIssuers("   ");

        whenTheOptionsAreParsed();

        thenThereAreNoTrustedIssuers();
    }

    @Test
    public void aCommaSeparatedListIsSplitIntoValues() {
        givenTrustedIssuers("kura,kura.gateway");

        whenTheOptionsAreParsed();

        thenTheTrustedIssuersAreExactly(List.of("kura", "kura.gateway"));
    }

    @Test
    public void surroundingWhitespaceIsTrimmedFromEveryValue() {
        givenTrustedIssuers("  kura , kura.gateway  ");

        whenTheOptionsAreParsed();

        thenTheTrustedIssuersAreExactly(List.of("kura", "kura.gateway"));
    }

    @Test
    public void emptyAndBlankEntriesAreDropped() {
        givenTrustedIssuers("kura,, ,kura.gateway,");

        whenTheOptionsAreParsed();

        thenTheTrustedIssuersAreExactly(List.of("kura", "kura.gateway"));
    }

    @Test
    public void repeatedEntriesAreKeptOnlyOnce() {
        givenTrustedIssuers("kura,kura");

        whenTheOptionsAreParsed();

        thenTheTrustedIssuersAreExactly(List.of("kura"));
    }

    @Test
    public void theConfiguredOrderIsPreserved() {
        givenTrustedIssuers("third,first,second");

        whenTheOptionsAreParsed();

        thenTheTrustedIssuersAreExactly(List.of("third", "first", "second"));
    }

    @Test
    public void theParsedValuesCannotBeModified() {
        givenTrustedIssuers("kura");

        whenTheOptionsAreParsed();

        thenTheTrustedIssuersCannotBeModified();
    }

    @Test
    public void theVerificationKeyAliasesAreParsedTheSameWay() {
        givenVerificationKeyAliases("  first-alias , , second-alias ");

        whenTheOptionsAreParsed();

        thenTheVerificationKeyAliasesAreExactly(List.of("first-alias", "second-alias"));
    }

    @Test
    public void theClockSkewAndTheCertificateRequirementArePassedThrough() {
        givenAClockSkewOfSecondsAndRequiredValidCertificates(90, false);

        whenTheOptionsAreParsed();

        thenTheClockSkewToleranceIs(90L);
        thenValidCertificatesAreNotRequired();
    }

    private void givenTrustedIssuers(final String trustedIssuers) {
        this.config = VerificationConfig.defaults().withTrustedIssuers(trustedIssuers);
    }

    private void givenVerificationKeyAliases(final String verificationKeyAliases) {
        this.config = VerificationConfig.defaults().withVerificationKeyAliases(verificationKeyAliases);
    }

    private void givenAClockSkewOfSecondsAndRequiredValidCertificates(final int clockSkewSeconds,
            final boolean requireValidCertificate) {

        this.config = VerificationConfig.defaults() //
                .withClockSkewSeconds(clockSkewSeconds) //
                .withRequireValidCertificate(requireValidCertificate);
    }

    private void whenTheOptionsAreParsed() {
        this.options = new JwtVerificationServiceOptions(this.config.toOcd());
    }

    private void thenThereAreNoTrustedIssuers() {
        assertTrue("expected no trusted issuers but got " + this.options.getTrustedIssuers(),
                this.options.getTrustedIssuers().isEmpty());
    }

    private void thenTheTrustedIssuersAreExactly(final List<String> expected) {
        assertEquals(expected, new ArrayList<>(this.options.getTrustedIssuers()));
    }

    private void thenTheVerificationKeyAliasesAreExactly(final List<String> expected) {
        assertEquals(expected, new ArrayList<>(this.options.getVerificationKeyAliases()));
    }

    private void thenTheTrustedIssuersCannotBeModified() {
        final Set<String> trustedIssuers = this.options.getTrustedIssuers();

        assertThrows(UnsupportedOperationException.class, () -> trustedIssuers.add("injected"));
    }

    private void thenTheClockSkewToleranceIs(final long expectedSeconds) {
        assertEquals(expectedSeconds, this.options.getClockSkewToleranceSec());
    }

    private void thenValidCertificatesAreNotRequired() {
        assertFalse("expected valid certificates not to be required", this.options.isRequireValidCertificate());
    }

}
