/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt.verifier;

import java.time.Instant;

import org.eclipse.kura.core.testutil.pki.TestCA.TestCAException;
import org.eclipse.kura.core.token.jwt.common.AbstractJwtScenario;
import org.eclipse.kura.core.token.jwt.common.TestKeys;
import org.eclipse.kura.core.token.jwt.common.TestToken;
import org.eclipse.kura.core.token.jwt.common.VerificationConfig;
import org.junit.Test;

public class VerificationProofTest extends AbstractJwtScenario {

    private static final String SIGNER_ALIAS = "trusted-signer";
    private static final int SIGNER_KEY = 0;

    private static final String TOKEN_ID = "b1a4f1e2-0000-4000-8000-000000000001";

    private final Instant issuedAt = Instant.now().minusSeconds(60);
    private final Instant notBefore = this.issuedAt;
    private final Instant expiresAt = this.issuedAt.plusSeconds(3600);

    @Test
    public void theProofNamesTheIdentityCarriedByTheSubjectClaim() throws TestCAException {
        givenAnActivatedVerifier();

        whenAFullyPopulatedTokenIsVerified();

        thenTheTokenIsVerifiedFor(TEST_IDENTITY);
    }

    @Test
    public void theProofRecordsWhenVerificationHappened() throws TestCAException {
        givenAnActivatedVerifier();

        whenAFullyPopulatedTokenIsVerified();

        thenTheProofRecordsAVerificationTime();
    }

    @Test
    public void theProofExposesTheRegisteredAndTheCustomClaims() throws TestCAException {
        givenAnActivatedVerifier();

        whenAFullyPopulatedTokenIsVerified();

        thenTheProofHasStringClaim("iss", DEFAULT_ISSUER);
        thenTheProofHasStringClaim("sub", TEST_IDENTITY);
        thenTheProofHasStringClaim("role", "admin");
    }

    @Test
    public void theProofExposesANullValuedClaimAsNull() throws TestCAException {
        givenAnActivatedVerifier();

        whenAFullyPopulatedTokenIsVerified();

        thenTheProofHasNullClaim("tenant");
    }

    @Test
    public void theProofClaimsCannotBeModified() throws TestCAException {
        givenAnActivatedVerifier();

        whenAFullyPopulatedTokenIsVerified();

        thenTheProofClaimsCannotBeModified();
    }

    @Test
    public void theProofExposesTheTimeClaimsAndTheTokenIdentifier() throws TestCAException {
        givenAnActivatedVerifier();

        whenAFullyPopulatedTokenIsVerified();

        thenTheProofExposesIssuedAt(this.issuedAt);
        thenTheProofExposesNotBefore(this.notBefore);
        thenTheProofExposesExpiresAt(this.expiresAt);
        thenTheProofExposesTokenId(TOKEN_ID);
    }

    @Test
    public void aMinimalTokenExposesNoneOfTheOptionalClaims() throws TestCAException {
        givenAnActivatedVerifier();

        whenAMinimalTokenIsVerified();

        thenTheTokenIsVerifiedFor(TEST_IDENTITY);
        thenTheProofExposesNoIssuedAt();
        thenTheProofExposesNoNotBefore();
        thenTheProofExposesNoExpiresAt();
        thenTheProofExposesNoTokenId();
    }

    private void givenAnActivatedVerifier() throws TestCAException {
        givenKeystoreTrustedCertificate(SIGNER_ALIAS, SIGNER_KEY);
        givenTheVerifierIsBoundToTheKeystore();
        givenTheVerifierIsActivatedWith(VerificationConfig.defaults());
    }

    private void whenAFullyPopulatedTokenIsVerified() throws TestCAException {
        whenATokenIsVerified(TestToken.builder() //
                .issuer(DEFAULT_ISSUER) //
                .subject(TEST_IDENTITY) //
                .issuedAt(this.issuedAt) //
                .notBefore(this.notBefore) //
                .expiresAt(this.expiresAt) //
                .tokenId(TOKEN_ID) //
                .claim("role", "admin") //
                .nullClaim("tenant") //
                .signedWith(TestKeys.rsaPrivateKey(SIGNER_KEY)));
    }

    private void whenAMinimalTokenIsVerified() throws TestCAException {
        whenATokenIsVerified(TestToken.builder() //
                .issuer(DEFAULT_ISSUER) //
                .subject(TEST_IDENTITY) //
                .signedWith(TestKeys.rsaPrivateKey(SIGNER_KEY)));
    }

}
