<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2016, 2025 Eurotech and/or its affiliates and others
  
    This program and the accompanying materials are made
    available under the terms of the Eclipse Public License 2.0
    which is available at https://www.eclipse.org/legal/epl-2.0/
 
    SPDX-License-Identifier: EPL-2.0
 
    Contributors:
     Red Hat Inc
     Eurotech
-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.eclipse.kura</groupId>
		<artifactId>kura</artifactId>
		<version>6.0.0-SNAPSHOT</version>
	</parent>

	<artifactId>org.eclipse.kura.camel.xml</artifactId>
	<version>2.0.0-SNAPSHOT</version>
	<packaging>eclipse-plugin</packaging>

	<properties>
		<kura.basedir>${project.basedir}/..</kura.basedir>
		
		<!-- These version properties will be migrated to specific bundle in future -->
		<spring.version>4.3.20.RELEASE_1</spring.version>
		<org.apache.camel.version>2.25.3</org.apache.camel.version>
		<apache-qpid-jms-client.version>0.45.0</apache-qpid-jms-client.version>
		<apache-qpid-proton-j.version>0.33.2</apache-qpid-proton-j.version>
	</properties>
	
	<!-- These particular dependencies will be migrated to specific bundle in future -->
	<dependencies>
		<dependency>
                <groupId>org.apache.camel</groupId>
                <artifactId>camel-amqp</artifactId>
                <version>${org.apache.camel.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.camel</groupId>
                <artifactId>camel-core</artifactId>
                <version>${org.apache.camel.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.camel</groupId>
                <artifactId>camel-core-osgi</artifactId>
                <version>${org.apache.camel.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.camel</groupId>
                <artifactId>camel-jms</artifactId>
                <version>${org.apache.camel.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.camel</groupId>
                <artifactId>camel-script</artifactId>
                <version>${org.apache.camel.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.camel</groupId>
                <artifactId>camel-stream</artifactId>
                <version>${org.apache.camel.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.qpid</groupId>
                <artifactId>qpid-jms-client</artifactId>
                <version>${apache-qpid-jms-client.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.qpid</groupId>
                <artifactId>proton-j</artifactId>
                <version>${apache-qpid-proton-j.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.servicemix.bundles</groupId>
                <artifactId>org.apache.servicemix.bundles.spring-beans</artifactId>
                <version>${spring.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.servicemix.bundles</groupId>
                <artifactId>org.apache.servicemix.bundles.spring-context</artifactId>
                <version>${spring.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.servicemix.bundles</groupId>
                <artifactId>org.apache.servicemix.bundles.spring-core</artifactId>
                <version>${spring.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.servicemix.bundles</groupId>
                <artifactId>org.apache.servicemix.bundles.spring-expression</artifactId>
                <version>${spring.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.servicemix.bundles</groupId>
                <artifactId>org.apache.servicemix.bundles.spring-jms</artifactId>
                <version>${spring.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.servicemix.bundles</groupId>
                <artifactId>org.apache.servicemix.bundles.spring-tx</artifactId>
                <version>${spring.version}</version>
            </dependency>
	</dependencies>

</project>
