/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.internal.rest.auth;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import org.eclipse.kura.internal.rest.auth.RestSessionHelper.XsrfTokenStatus;
import org.junit.Test;

import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpSession;

public class RestSessionHelperTest {

    private static final String XSRF_TOKEN_HEADER = "X-XSRF-Token";
    private static final String SESSION_TOKEN = "1e3f1e33-3c4d-4b1f-9d6a-4e1b0f7c5a21";

    private final HttpServletRequest request = mock(HttpServletRequest.class);
    private final HttpSession session = mock(HttpSession.class);
    private final RestSessionHelper sessionHelper = new RestSessionHelper(mock(RestIdentityHelper.class));

    private XsrfTokenStatus status;

    @Test
    public void shouldReportMissingTokenIfHeaderIsNotProvided() {
        givenSessionWithXsrfToken(SESSION_TOKEN);
        givenNoXsrfTokenHeader();

        whenXsrfTokenStatusIsRetrieved();

        thenStatusIs(XsrfTokenStatus.MISSING);
    }

    @Test
    public void shouldReportInvalidTokenIfHeaderDoesNotMatchSessionToken() {
        givenSessionWithXsrfToken(SESSION_TOKEN);
        givenXsrfTokenHeader("not-the-session-token");

        whenXsrfTokenStatusIsRetrieved();

        thenStatusIs(XsrfTokenStatus.INVALID);
    }

    @Test
    public void shouldReportInvalidTokenIfSessionIsNotPresent() {
        givenNoSession();
        givenXsrfTokenHeader(SESSION_TOKEN);

        whenXsrfTokenStatusIsRetrieved();

        thenStatusIs(XsrfTokenStatus.INVALID);
    }

    @Test
    public void shouldReportInvalidTokenIfSessionHasNoToken() {
        givenSessionWithXsrfToken(null);
        givenXsrfTokenHeader(SESSION_TOKEN);

        whenXsrfTokenStatusIsRetrieved();

        thenStatusIs(XsrfTokenStatus.INVALID);
    }

    @Test
    public void shouldReportValidTokenIfHeaderMatchesSessionToken() {
        givenSessionWithXsrfToken(SESSION_TOKEN);
        givenXsrfTokenHeader(SESSION_TOKEN);

        whenXsrfTokenStatusIsRetrieved();

        thenStatusIs(XsrfTokenStatus.VALID);
    }

    private void givenNoSession() {
        when(this.request.getSession(false)).thenReturn(null);
    }

    private void givenSessionWithXsrfToken(final String token) {
        when(this.request.getSession(false)).thenReturn(this.session);
        when(this.session.getAttribute(SessionAttributes.XSRF_TOKEN.getValue())).thenReturn(token);
    }

    private void givenNoXsrfTokenHeader() {
        when(this.request.getHeader(XSRF_TOKEN_HEADER)).thenReturn(null);
    }

    private void givenXsrfTokenHeader(final String token) {
        when(this.request.getHeader(XSRF_TOKEN_HEADER)).thenReturn(token);
    }

    private void whenXsrfTokenStatusIsRetrieved() {
        this.status = this.sessionHelper.getXsrfTokenStatus(this.request);
    }

    private void thenStatusIs(final XsrfTokenStatus expected) {
        assertEquals(expected, this.status);
    }

}
