/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 * Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.comm;

import static org.junit.Assert.assertSame;
import static org.junit.Assert.assertTrue;

import java.io.IOException;

import javax.comm.NoSuchPortException;
import javax.microedition.io.Connection;

import org.eclipse.kura.comm.CommURI;
import org.junit.Test;

public class CreateCommConnectionTest {

    private static final String PORT_URI = "comm:/dev/ttyS0;baudrate=9600";

    private Throwable connectionFailure;
    private Throwable propagatedThrowable;

    /*
     * Scenarios
     */

    @Test
    public void rethrowsIOException() {
        final IOException failure = new IOException("port failure");
        givenConnectionFailsWith(failure);

        whenConnectionIsCreated();

        thenPropagatedIs(failure);
    }

    @Test
    public void wrapsCheckedPortExceptionInIOException() {
        final NoSuchPortException failure = new NoSuchPortException();
        givenConnectionFailsWith(failure);

        whenConnectionIsCreated();

        thenPropagatedIOExceptionCausedBy(failure);
    }

    @Test
    public void wrapsNativeLibraryLinkageErrorInIOException() {
        final UnsatisfiedLinkError failure = new UnsatisfiedLinkError("native serial library not found");
        givenConnectionFailsWith(failure);

        whenConnectionIsCreated();

        thenPropagatedIOExceptionCausedBy(failure);
    }

    @Test
    public void propagatesVirtualMachineError() {
        givenConnectionFailsWith(new OutOfMemoryError("simulated"));

        whenConnectionIsCreated();

        thenPropagatedType(OutOfMemoryError.class);
    }

    /*
     * Steps
     */

    private void givenConnectionFailsWith(Throwable failure) {
        this.connectionFailure = failure;
    }

    private void whenConnectionIsCreated() {
        final CommConnectionFactory factory = new CommConnectionFactory() {

            @Override
            Connection newConnection(CommURI commUri, int mode, boolean timeouts) {
                return sneakyThrow(CreateCommConnectionTest.this.connectionFailure);
            }
        };
        try {
            factory.createConnection(PORT_URI, 3, false);
        } catch (Throwable e) {
            this.propagatedThrowable = e;
        }
    }

    private void thenPropagatedIs(Throwable expected) {
        assertSame(expected, this.propagatedThrowable);
    }

    private void thenPropagatedIOExceptionCausedBy(Throwable expectedCause) {
        assertTrue("unexpected: " + this.propagatedThrowable, this.propagatedThrowable instanceof IOException);
        assertSame(expectedCause, this.propagatedThrowable.getCause());
    }

    private void thenPropagatedType(Class<? extends Throwable> expected) {
        assertTrue("unexpected: " + this.propagatedThrowable, expected.isInstance(this.propagatedThrowable));
    }

    /*
     * Utilities
     */

    @SuppressWarnings("unchecked")
    private static <T, E extends Throwable> T sneakyThrow(Throwable e) throws E {
        throw (E) e;
    }
}
