/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 * Content with portions generated by generative AI platform
 *******************************************************************************/
package org.eclipse.kura.core.keystore.crl.test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import java.io.File;
import java.io.FileWriter;
import java.io.Writer;
import java.net.URI;
import java.nio.file.Files;
import java.security.cert.X509CRL;
import java.util.Base64;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.Set;
import java.util.concurrent.TimeUnit;

import org.bouncycastle.asn1.x500.X500Name;
import org.eclipse.kura.core.keystore.crl.CRLStore;
import org.eclipse.kura.core.keystore.crl.StoredCRL;
import org.eclipse.kura.core.testutil.pki.TestCA;
import org.eclipse.kura.core.testutil.pki.TestCA.CRLCreationOptions;
import org.eclipse.kura.core.testutil.pki.TestCA.CertificateCreationOptions;
import org.junit.Test;

import com.eclipsesource.json.Json;
import com.eclipsesource.json.JsonArray;
import com.eclipsesource.json.JsonObject;

public class StoredCRLLazyDecodeTest {

    private static final Set<URI> DISTRIBUTION_POINTS = Collections.singleton(URI.create("http://foo/bar.crl"));

    private TestCA ca;
    private X509CRL crl;
    private StoredCRL storedCrl;
    private JsonObject json;
    private File storeFile;
    private CRLStore store;

    @Test
    public void storedCrlIsSerializedWithMetadataAndLoadedWithoutDecoding() throws Exception {
        givenCertificateAuthority("cn=Test CA, dc=bar.com");
        givenCrl();

        whenStoredCrlIsSerializedToJson();
        whenStoredCrlIsLoadedFromJson();

        thenJsonContainsIssuerAndNextUpdate();
        thenLoadedCrlHasMetadata();
        thenLoadedCrlMatchesOriginal();
    }

    @Test
    public void legacyJsonWithoutMetadataIsLoadedAndUpgraded() throws Exception {
        givenCertificateAuthority("cn=Legacy CA, dc=bar.com");
        givenCrl();
        givenLegacyJson();

        whenStoredCrlIsLoadedFromJson();

        thenLoadedCrlIsFlaggedAsLegacy();
        thenLoadedCrlMatchesOriginal();
        thenReserializedJsonContainsMetadata();
    }

    @Test
    public void sameEncodingIsRecognized() throws Exception {
        givenCertificateAuthority("cn=Test CA, dc=bar.com");
        givenCrl();
        givenStoredCrl();

        thenStoredCrlHasSameEncodingAs(this.crl);
        thenStoredCrlHasDifferentEncodingThan(new TestCA(
                CertificateCreationOptions.builder(new X500Name("cn=Other CA, dc=bar.com")).build())
                .generateCRL(CRLCreationOptions.builder().build()));
    }

    @Test
    public void crlStoreReloadsBodiesFromFilesLazily() throws Exception {
        givenCertificateAuthority("cn=Test CA, dc=bar.com");
        givenCrl();
        givenLegacyJson();
        givenLegacyStoreFile();
        givenStoreUpgradedAndClosed();

        whenCrlStoreIsOpened();

        thenStoreContainsOneCrlFor(this.ca);
        thenStoredCrlBodyIsBackedByFile();
    }

    @Test
    public void crlStoreUpgradesLegacyFileOnLoad() throws Exception {
        givenCertificateAuthority("cn=Test CA, dc=bar.com");
        givenCrl();
        givenLegacyJson();
        givenLegacyStoreFile();

        whenCrlStoreIsOpened();

        thenStoreContainsOneCrlFor(this.ca);
        thenStoreFileIsRewrittenWithMetadata();
    }

    private void givenCertificateAuthority(final String dn) throws Exception {
        this.ca = new TestCA(CertificateCreationOptions.builder(new X500Name(dn)).build());
    }

    private void givenCrl() throws Exception {
        this.crl = this.ca.generateCRL(CRLCreationOptions.builder()
                .withEndDate(new Date(System.currentTimeMillis() + TimeUnit.DAYS.toMillis(1))).build());
    }

    private void givenStoredCrl() throws Exception {
        this.storedCrl = new StoredCRL(DISTRIBUTION_POINTS, this.crl);
    }

    private void givenLegacyJson() throws Exception {
        final JsonArray dps = new JsonArray();
        dps.add(DISTRIBUTION_POINTS.iterator().next().toString());
        this.json = new JsonObject().add("dps", dps).add("body",
                Base64.getEncoder().encodeToString(this.crl.getEncoded()));
    }

    private void givenLegacyStoreFile() throws Exception {
        this.storeFile = Files.createTempFile("crlstore", ".crl").toFile();
        try (final Writer out = new FileWriter(this.storeFile)) {
            new JsonArray().add(this.json).writeTo(out);
        }
    }

    private void whenStoredCrlIsSerializedToJson() throws Exception {
        givenStoredCrl();
        this.json = this.storedCrl.toJson();
    }

    private void whenStoredCrlIsLoadedFromJson() throws Exception {
        this.storedCrl = StoredCRL.fromJson(Json.parse(this.json.toString()).asObject(),
                Files.createTempDirectory("crlbodies"));
    }

    private void givenStoreUpgradedAndClosed() throws Exception {
        whenCrlStoreIsOpened();
        thenStoreFileIsRewrittenWithMetadata();
    }

    private void whenCrlStoreIsOpened() {
        this.store = new CRLStore(this.storeFile, 100);
    }

    private void thenJsonContainsIssuerAndNextUpdate() {
        assertEquals(this.crl.getIssuerX500Principal().getName(), this.json.getString("issuer", null));
        assertEquals(this.crl.getNextUpdate().getTime(), this.json.getLong("nextUpdate", -1));
    }

    private void thenLoadedCrlHasMetadata() {
        assertTrue(this.storedCrl.isLoadedWithMetadata());
        assertEquals(this.crl.getIssuerX500Principal(), this.storedCrl.getIssuer());
        assertEquals(this.crl.getNextUpdate(), this.storedCrl.getNextUpdate().get());
        assertFalse(this.storedCrl.isExpired());
        assertEquals(DISTRIBUTION_POINTS, this.storedCrl.getDistributionPoints());
    }

    private void thenLoadedCrlIsFlaggedAsLegacy() {
        assertFalse(this.storedCrl.isLoadedWithMetadata());
        assertEquals(this.crl.getIssuerX500Principal(), this.storedCrl.getIssuer());
    }

    private void thenLoadedCrlMatchesOriginal() {
        assertEquals(this.crl, this.storedCrl.getCrl());
        assertTrue(this.storedCrl.getTimeToNextUpdateMs() > 0);
    }

    private void thenReserializedJsonContainsMetadata() {
        final JsonObject upgraded = this.storedCrl.toJson();
        assertNotNull(upgraded.get("issuer"));
        assertNotNull(upgraded.get("nextUpdate"));
    }

    private void thenStoredCrlHasSameEncodingAs(final X509CRL other) throws Exception {
        assertTrue(this.storedCrl.hasSameEncoding(other));
    }

    private void thenStoredCrlHasDifferentEncodingThan(final X509CRL other) throws Exception {
        assertFalse(this.storedCrl.hasSameEncoding(other));
    }

    private void thenStoreContainsOneCrlFor(final TestCA authority) {
        final List<StoredCRL> crls = this.store.getCRLs();
        assertEquals(1, crls.size());
        assertEquals(this.crl.getIssuerX500Principal(), crls.get(0).getIssuer());
        assertEquals(this.crl, crls.get(0).getCrl());
    }

    private void thenStoredCrlBodyIsBackedByFile() {
        final StoredCRL loaded = this.store.getCRLs().get(0);
        assertTrue(loaded.isPersisted());
        assertTrue(loaded.isLoadedWithMetadata());
        assertTrue(loaded.getBodyFile().get().toFile().isFile());
    }

    private void thenStoreFileIsRewrittenWithMetadata() throws Exception {
        final long deadline = System.currentTimeMillis() + 5000;
        String content = "";
        while (System.currentTimeMillis() < deadline && !content.contains("\"issuer\"")) {
            Thread.sleep(100);
            content = new String(Files.readAllBytes(this.storeFile.toPath()));
        }
        this.store.close();
        assertTrue(content.contains("\"issuer\""));
        assertTrue(content.contains("\"nextUpdate\""));
        assertTrue(content.contains("\"file\""));
        assertFalse(content.contains("\"body\""));
        final File bodyDirectory = new File(this.storeFile.getParent(), this.storeFile.getName() + ".d");
        assertEquals(1, bodyDirectory.list((dir, name) -> name.endsWith(".crl")).length);
    }
}
