/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 * Content with portions generated by generative AI platform
 *******************************************************************************/
package org.eclipse.kura.core.keystore;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;
import static org.mockito.Mockito.mock;

import java.io.File;
import java.nio.file.Paths;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

import org.eclipse.kura.crypto.CryptoService;
import org.junit.Test;

public class KeystorePathValidationTest {

    @Test
    public void shouldAcceptPathContainingSpaces() {
        givenKeystorePath("/opt/my keystores/keystore.ks");

        whenOptionsAreCreated();

        thenNoExceptionIsThrown();
        thenKeystorePathIs(Paths.get("/opt/my keystores/keystore.ks").toString());
    }

    @Test
    public void shouldAcceptPathWithPlatformSeparators() {
        givenKeystorePath(new File(new File("keystores"), "keystore.ks").getPath());

        whenOptionsAreCreated();

        thenNoExceptionIsThrown();
        thenKeystorePathIs(Paths.get("keystores", "keystore.ks").toString());
    }

    @Test
    public void shouldNormalizeRedundantPathSegments() {
        givenKeystorePath("/opt/./kura/../keystore.ks");

        whenOptionsAreCreated();

        thenNoExceptionIsThrown();
        thenKeystorePathIs(Paths.get("/opt/keystore.ks").toString());
    }

    @Test
    public void shouldRejectInvalidPath() {
        givenKeystorePath("/opt/key\0store.ks");

        whenOptionsAreCreated();

        thenIllegalArgumentExceptionIsThrown("Invalid keystore path");
    }

    private final Map<String, Object> properties = new HashMap<>();
    private Optional<FilesystemKeystoreServiceOptions> options = Optional.empty();
    private Optional<Exception> exception = Optional.empty();

    private void givenKeystorePath(final String keystorePath) {
        this.properties.put("keystore.path", keystorePath);
        this.properties.put("keystore.password", "changeit");
    }

    private void whenOptionsAreCreated() {
        try {
            this.options = Optional.of(new FilesystemKeystoreServiceOptions(this.properties, mock(CryptoService.class)));
        } catch (final Exception e) {
            this.exception = Optional.of(e);
        }
    }

    private void thenNoExceptionIsThrown() {
        if (this.exception.isPresent()) {
            fail("unexpected exception: " + this.exception.get());
        }
    }

    private void thenKeystorePathIs(final String expectedPath) {
        assertTrue(this.options.isPresent());
        assertEquals(expectedPath, this.options.get().getKeystorePath());
    }

    private void thenIllegalArgumentExceptionIsThrown(final String expectedMessage) {
        assertTrue(this.exception.isPresent());
        assertTrue(this.exception.get() instanceof IllegalArgumentException);
        assertNotNull(this.exception.get().getMessage());
        assertEquals(expectedMessage, this.exception.get().getMessage());
    }
}
