#!/bin/bash

INSTALL_DIR=/opt/eclipse
TIMESTAMP=`date +%Y%m%d%H%M%S`
LOG=/tmp/kura_install_${TIMESTAMP}.log
WD_TMP_FILE=/tmp/watchdog
REFRESH_TIME=5

##############################################
# UTILITY FUNCTIONS
##############################################
# Start refresh watchdog device
function startRefreshWatchdog {
    if [ -f "${WD_TMP_FILE}" ]; then
        WATCHDOG_DEVICE=`cat ${WD_TMP_FILE}`
        echo "Got watchdog ${WATCHDOG_DEVICE}" >> ${LOG} 2>&1
        refreshWatchdog &
        PID=$!
    fi
}

# Refresh watchdog device
function refreshWatchdog {
    for (( ; ; ))
    do
        echo w > ${WATCHDOG_DEVICE}
        sleep $REFRESH_TIME
    done
}

# Deactivate watchdog device if possible
function stopWatchdog {
    if [ -n "${PID}" ]; then
        kill -9 $PID >> /dev/null 2>&1
    fi
    if [ -n "${WATCHDOG_DEVICE}" ]; then
        echo V > ${WATCHDOG_DEVICE}
    fi
}
##############################################
# END UTILITY FUNCTIONS
##############################################

##############################################
# POST INSTALL SCRIPT
##############################################
#Get watchdog device and start refreshing
startRefreshWatchdog

mkdir -p ${INSTALL_DIR} >> ${LOG} 2>&1
unzip /tmp/kura_*.zip -d ${INSTALL_DIR} >> ${LOG} 2>&1

#install KURA files
sh ${INSTALL_DIR}/kura_*/install/kura_install.sh >> ${LOG} 2>&1

#clean up
rm -rf ${INSTALL_DIR}/kura/install >> ${LOG} 2>&1
rm /tmp/kura_*.zip >> ${LOG} 2>&1

#move the log file
mkdir -p ${INSTALL_DIR}/kura/log
mv ${LOG} ${INSTALL_DIR}/kura/log/

#flush all cached filesystem to disk
sync

echo ""
echo "Finished. KURA has been installed to ${INSTALL_DIR}/kura and will start automatically after a reboot"
stopWatchdog
exit 0
#############################################
# END POST INSTALL SCRIPT
##############################################

