/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.identity.test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

import java.time.Duration;
import java.util.HashSet;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.concurrent.Callable;
import java.util.concurrent.TimeUnit;
import java.util.stream.Collectors;

import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.KuraException;
import org.eclipse.kura.core.testutil.service.ServiceUtil;
import org.eclipse.kura.identity.AssignedPermissions;
import org.eclipse.kura.identity.IdentityConfiguration;
import org.eclipse.kura.identity.IdentityService;
import org.eclipse.kura.identity.PasswordConfiguration;
import org.eclipse.kura.identity.Permission;
import org.junit.After;
import org.junit.Test;

/**
 * Feature: Manage temporary identities.
 */
public class TemporaryIdentityServiceTest extends IdentityServiceTestBase {

    private final IdentityService identityService;

    private Optional<Exception> exception = Optional.empty();
    private Optional<Object> result = Optional.empty();

    private String identityName;
    private String password;
    private Set<String> permissions;
    private final Set<String> createdPermissions = new HashSet<>();
    private final Set<String> createdIdentities = new HashSet<>();

    public TemporaryIdentityServiceTest() {
        super();
        try {
            this.identityService = ServiceUtil.trackService(IdentityService.class, Optional.empty()).get(30,
                    TimeUnit.SECONDS);
        } catch (Exception e) {
            fail("failed to setup test environment");
            throw new IllegalStateException("unreachable");
        }
    }

    @After
    public void cleanup() {
        for (final String identity : this.createdIdentities) {
            try {
                this.identityService.deleteTemporaryIdentity(identity);
            } catch (Exception e) {
                // no need
            }
        }
        this.createdIdentities.clear();

        for (final String permission : this.createdPermissions) {
            try {
                this.identityService.deletePermission(new Permission(permission));
            } catch (Exception e) {
                // no need
            }
        }
        this.createdPermissions.clear();
    }

    @Test
    public void shouldCreateTemporaryIdentity() {
        givenIdentityName("container_test");
        givenPermissions("rest.asset.read", "rest.configuration.write");
        givenExistingPermissions("rest.asset.read", "rest.configuration.write");

        whenTemporaryIdentityIsCreated();

        thenNoExceptionIsThrown();
    }

    @Test
    public void shouldCheckTemporaryPermission() {
        givenIdentityName("container_test");
        givenPermissions("rest.asset.read");
        givenExistingPermissions("rest.asset.read");
        givenExistingTemporaryIdentity();

        whenPermissionIsChecked("rest.asset.read");

        thenNoExceptionIsThrown();
    }

    @Test
    public void shouldFailToCheckNonAssignedPermission() {
        givenIdentityName("container_test");
        givenPermissions("rest.asset.read");
        givenExistingPermissions("rest.asset.read", "rest.configuration.write");
        givenExistingTemporaryIdentity();

        whenPermissionIsChecked("rest.configuration.write");

        thenSecurityExceptionIsThrown();
    }

    @Test
    public void shouldDeleteTemporaryIdentity() {
        givenIdentityName("container_test");
        givenPermissions("rest.asset.read");
        givenExistingPermissions("rest.asset.read");
        givenExistingTemporaryIdentity();

        whenTemporaryIdentityIsDeleted();

        thenNoExceptionIsThrown();
        thenTemporaryIdentityServiceReportsDeleted(true);
    }

    @Test
    public void shouldReturnFalseWhenDeletingNonExistentTemporaryIdentity() {
        whenTemporaryIdentityIsDeleted("invalid-token");

        thenNoExceptionIsThrown();
        thenTemporaryIdentityServiceReportsDeleted(false);
    }

    @Test
    public void shouldFailToCreateTemporaryIdentityWithNonexistentPermission() {
        givenIdentityName("container_test");
        givenPermissions("nonexistent.permission");

        whenTemporaryIdentityIsCreated();

        thenExceptionIsThrown(KuraException.class);
    }

    @Test
    public void shouldAuthenticateWithPasswordForTemporaryIdentity() {
        givenIdentityName("container_test_password");
        givenPermissions("rest.asset.read");
        givenExistingPermissions("rest.asset.read");
        givenPassword("SecurePassword123!");
        givenExistingTemporaryIdentityWithPassword();

        whenPasswordIsChecked("SecurePassword123!");

        thenNoExceptionIsThrown();
    }

    @Test
    public void shouldFailAuthenticationWithWrongPassword() {
        givenIdentityName("container_test_password");
        givenPermissions("rest.asset.read");
        givenExistingPermissions("rest.asset.read");
        givenPassword("SecurePassword123!");
        givenExistingTemporaryIdentityWithPassword();

        whenPasswordIsChecked("WrongPassword123!");

        thenSecurityExceptionIsThrown();
    }

    // Given methods
    private void givenIdentityName(final String name) {
        this.identityName = name;
    }

    private void givenPermissions(final String... permissionNames) {
        this.permissions = new HashSet<>(Set.of(permissionNames));
    }

    private void givenExistingPermissions(final String... permissionNames) {
        for (String permissionName : permissionNames) {
            try {
                this.identityService.createPermission(new Permission(permissionName));
                this.createdPermissions.add(permissionName);
            } catch (Exception e) {
                fail("failed to create permission");
            }
        }
    }

    private void givenExistingTemporaryIdentity() {
        try {
            final AssignedPermissions assignedPermissions = new AssignedPermissions(
                    this.permissions.stream().map(Permission::new).collect(Collectors.toSet()));
            final IdentityConfiguration identityConfiguration = new IdentityConfiguration(this.identityName,
                    List.of(assignedPermissions));

            this.identityService.createTemporaryIdentity(identityConfiguration, Duration.ofHours(1));
            this.createdIdentities.add(this.identityName);
        } catch (KuraException e) {
            fail("Failed to create temporary identity for test setup");
        }
    }

    private void givenPassword(final String pwd) {
        this.password = pwd;
    }

    private void givenExistingTemporaryIdentityWithPassword() {
        try {
            final AssignedPermissions assignedPermissions = new AssignedPermissions(
                    this.permissions.stream().map(Permission::new).collect(Collectors.toSet()));
            final PasswordConfiguration passwordConfiguration = new PasswordConfiguration(
                    false, true, Optional.of(this.password.toCharArray()), Optional.empty());
            final IdentityConfiguration identityConfiguration = new IdentityConfiguration(this.identityName,
                    List.of(assignedPermissions, passwordConfiguration));

            this.identityService.createTemporaryIdentity(identityConfiguration, Duration.ofHours(1));
            this.createdIdentities.add(this.identityName);
        } catch (KuraException e) {
            fail("Failed to create temporary identity for test setup: " + e.getMessage());
        }
    }

    // When methods
    private void whenTemporaryIdentityIsCreated() {
        call(() -> {
            final AssignedPermissions assignedPermissions = new AssignedPermissions(
                    this.permissions.stream().map(Permission::new).collect(Collectors.toSet()));
            final IdentityConfiguration identityConfiguration = new IdentityConfiguration(this.identityName,
                    List.of(assignedPermissions));

            this.identityService.createTemporaryIdentity(identityConfiguration, Duration.ofHours(1));
            this.createdIdentities.add(this.identityName);
            return null;
        });
    }

    private void whenTemporaryIdentityIsDeleted() {
        call(() -> this.identityService.deleteTemporaryIdentity(this.identityName));
    }

    private void whenTemporaryIdentityIsDeleted(final String token) {
        call(() -> this.identityService.deleteTemporaryIdentity(token));
    }

    private void whenPermissionIsChecked(final String permissionName) {
        callVoid(() -> {
            this.identityService.checkPermission(this.identityName, new Permission(permissionName));
            return null;
        });
    }

    private void whenPasswordIsChecked(final String pwd) {
        callVoid(() -> {
            this.identityService.checkPassword(this.identityName, pwd.toCharArray());
            return null;
        });
    }

    // Then methods
    private void thenNoExceptionIsThrown() {
        assertEquals(Optional.empty(), this.exception);
    }

    private void thenExceptionIsThrown(final Class<? extends Exception> clazz) {
        assertEquals(Optional.of(clazz), this.exception.map(Object::getClass));
    }

    private void thenTemporaryIdentityServiceReportsDeleted(final boolean deleted) {
        assertEquals(Optional.of(deleted), this.result);
    }

    private void thenSecurityExceptionIsThrown() {
        assertEquals(Optional.of(KuraException.class), this.exception.map(Object::getClass));
        final KuraException ex = (KuraException) this.exception.get();
        assertEquals(KuraErrorCode.SECURITY_EXCEPTION, ex.getCode());
    }

    private void call(final Callable<?> callable) {
        try {
            this.exception = Optional.empty();
            this.result = Optional.ofNullable(callable.call());
        } catch (Exception e) {
            this.exception = Optional.of(e);
        }
    }

    private void callVoid(final Callable<Void> callable) {
        try {
            this.exception = Optional.empty();
            this.result = Optional.empty();
            callable.call();
        } catch (Exception e) {
            this.exception = Optional.of(e);
        }
    }
}
