/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.identity.test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import java.time.Duration;
import java.util.HashSet;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;
import java.util.concurrent.Callable;
import java.util.concurrent.TimeUnit;
import java.util.stream.Collectors;

import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.KuraException;
import org.eclipse.kura.core.testutil.service.ServiceUtil;
import org.eclipse.kura.identity.AssignedPermissions;
import org.eclipse.kura.identity.IdentityConfiguration;
import org.eclipse.kura.identity.IdentityService;
import org.eclipse.kura.identity.Permission;
import org.eclipse.kura.identity.TokenConfiguration;
import org.junit.After;
import org.junit.Test;

/**
 * Feature: Manage temporary identities.
 */
public class TemporaryIdentityServiceTest extends IdentityServiceTestBase {

    private final IdentityService identityService;

    private Optional<Exception> exception = Optional.empty();
    private Optional<Object> result = Optional.empty();

    private String identityName;
    private Set<String> permissions;
    private String temporaryToken;
    private final Set<String> createdPermissions = new HashSet<>();
    private final Set<String> createdIdentities = new HashSet<>();

    public TemporaryIdentityServiceTest() {
        super();
        try {
            this.identityService = ServiceUtil.trackService(IdentityService.class, Optional.empty()).get(30,
                    TimeUnit.SECONDS);
        } catch (Exception e) {
            fail("failed to setup test environment");
            throw new IllegalStateException("unreachable");
        }
    }

    @After
    public void cleanup() {
        for (final String identity : this.createdIdentities) {
            try {
                this.identityService.deleteTemporaryIdentity(identity);
            } catch (Exception e) {
                // no need
            }
        }
        this.createdIdentities.clear();

        for (final String permission : this.createdPermissions) {
            try {
                this.identityService.deletePermission(new Permission(permission));
            } catch (Exception e) {
                // no need
            }
        }
        this.createdPermissions.clear();
    }

    @Test
    public void shouldCreateTemporaryIdentity() {
        givenIdentityName("container_test");
        givenPermissions("rest.asset.read", "rest.configuration.write");
        givenExistingPermissions("rest.asset.read", "rest.configuration.write");
        givenTemporaryToken();

        whenTemporaryIdentityIsCreated();
        whenTemporaryTokenIsResolved();

        thenNoExceptionIsThrown();
        thenTemporaryTokenStartsWithPrefix("kura-temp-");
        thenTemporaryTokenCanBeResolvedToIdentity();
    }

    @Test
    public void shouldValidateTemporaryToken() {
        givenIdentityName("container_test");
        givenPermissions("rest.asset.read");
        givenExistingPermissions("rest.asset.read");
        givenTemporaryToken();
        givenExistingTemporaryIdentity();

        whenTemporaryTokenIsResolved();

        thenNoExceptionIsThrown();
        thenValidatedIdentityNameMatches();
    }

    @Test
    public void shouldCheckTemporaryPermission() {
        givenIdentityName("container_test");
        givenPermissions("rest.asset.read");
        givenExistingPermissions("rest.asset.read");
        givenTemporaryToken();
        givenExistingTemporaryIdentity();

        whenPermissionIsChecked("rest.asset.read");

        thenNoExceptionIsThrown();
    }

    @Test
    public void shouldFailToCheckNonAssignedPermission() {
        givenIdentityName("container_test");
        givenPermissions("rest.asset.read");
        givenExistingPermissions("rest.asset.read", "rest.configuration.write");
        givenTemporaryToken();
        givenExistingTemporaryIdentity();

        whenPermissionIsChecked("rest.configuration.write");

        thenSecurityExceptionIsThrown();
    }

    @Test
    public void shouldDeleteTemporaryIdentity() {
        givenIdentityName("container_test");
        givenPermissions("rest.asset.read");
        givenExistingPermissions("rest.asset.read");
        givenTemporaryToken();
        givenExistingTemporaryIdentity();

        whenTemporaryIdentityIsDeleted();

        thenNoExceptionIsThrown();
        thenTemporaryIdentityServiceReportsDeleted(true);

        whenTemporaryTokenIsResolved();

        thenTemporaryTokenIsNoLongerValid();
    }

    @Test
    public void shouldReturnFalseWhenDeletingNonExistentTemporaryIdentity() {
        whenTemporaryIdentityIsDeleted("invalid-token");

        thenNoExceptionIsThrown();
        thenTemporaryIdentityServiceReportsDeleted(false);
    }

    @Test
    public void shouldFailToCreateTemporaryIdentityWithNonexistentPermission() {
        givenIdentityName("container_test");
        givenPermissions("nonexistent.permission");
        givenTemporaryToken();

        whenTemporaryIdentityIsCreated();

        thenExceptionIsThrown(KuraException.class);
    }

    @Test
    public void shouldFailToValidateInvalidToken() {
        whenTemporaryTokenIsResolved("invalid-token");

        thenTemporaryTokenIsNotResolved();
    }

    // Given methods
    private void givenIdentityName(final String name) {
        this.identityName = name;
    }

    private void givenPermissions(final String... permissionNames) {
        this.permissions = new HashSet<>(Set.of(permissionNames));
    }

    private void givenExistingPermissions(final String... permissionNames) {
        for (String permissionName : permissionNames) {
            try {
                this.identityService.createPermission(new Permission(permissionName));
                this.createdPermissions.add(permissionName);
            } catch (Exception e) {
                fail("failed to create permission");
            }
        }
    }

    private void givenTemporaryToken() {
        this.temporaryToken = "kura-temp-" + UUID.randomUUID().toString();
    }

    private void givenExistingTemporaryIdentity() {
        try {
            final AssignedPermissions assignedPermissions = new AssignedPermissions(this.permissions.stream()
                    .map(Permission::new).collect(Collectors.toSet()));
            final TokenConfiguration tokenConfiguration = new TokenConfiguration(this.temporaryToken, Optional.empty());
            final IdentityConfiguration identityConfiguration = new IdentityConfiguration(this.identityName,
                    List.of(tokenConfiguration, assignedPermissions));

            this.identityService.createTemporaryIdentity(this.identityName, identityConfiguration, Duration.ofHours(1));
            this.createdIdentities.add(this.identityName);
        } catch (KuraException e) {
            fail("Failed to create temporary identity for test setup");
        }
    }

    // When methods
    private void whenTemporaryIdentityIsCreated() {
        call(() -> {
            final AssignedPermissions assignedPermissions = new AssignedPermissions(this.permissions.stream()
                    .map(Permission::new).collect(Collectors.toSet()));
            final TokenConfiguration tokenConfiguration = new TokenConfiguration(this.temporaryToken, Optional.empty());
            final IdentityConfiguration identityConfiguration = new IdentityConfiguration(this.identityName,
                    List.of(tokenConfiguration, assignedPermissions));

            this.identityService.createTemporaryIdentity(this.identityName, identityConfiguration, Duration.ofHours(1));
            this.createdIdentities.add(this.identityName);
            return null;
        });
    }

    private void whenTemporaryIdentityIsDeleted() {
        call(() -> this.identityService.deleteTemporaryIdentity(this.identityName));
    }

    private void whenTemporaryIdentityIsDeleted(final String token) {
        call(() -> this.identityService.deleteTemporaryIdentity(token));
    }

    private void whenTemporaryTokenIsResolved() {
        call(() -> this.identityService.findIdentityByToken(this.temporaryToken));
    }

    private void whenTemporaryTokenIsResolved(final String token) {
        call(() -> this.identityService.findIdentityByToken(token));
    }

    private void whenPermissionIsChecked(final String permissionName) {
        callVoid(() -> {
            this.identityService.checkPermission(this.identityName, new Permission(permissionName));
            return null;
        });
    }

    // Then methods
    private void thenNoExceptionIsThrown() {
        assertEquals(Optional.empty(), this.exception);
    }

    private void thenExceptionIsThrown(final Class<? extends Exception> clazz) {
        assertEquals(Optional.of(clazz), this.exception.map(Object::getClass));
    }

    private void thenTemporaryTokenStartsWithPrefix(final String prefix) {
        assertTrue("Token should start with prefix " + prefix, this.temporaryToken.startsWith(prefix));
    }

    private void thenValidatedIdentityNameMatches() {
        assertEquals("Validated identity name should match", this.identityName,
                ((Optional<?>) expectResult(Optional.class)).orElse(null));
    }

    private void thenTemporaryIdentityServiceReportsDeleted(final boolean deleted) {
        assertEquals(Optional.of(deleted), this.result);
    }

    private void thenTemporaryTokenIsNoLongerValid() {
        final Optional<?> resolved = (Optional<?>) expectResult(Optional.class);
        assertFalse("Token should no longer be valid after deletion", resolved.isPresent());
    }

    private void thenTemporaryTokenCanBeResolvedToIdentity() {
        final Optional<?> resolved = (Optional<?>) expectResult(Optional.class);
        assertEquals("Identity name should match", this.identityName, resolved.orElse(null));
    }

    private void thenTemporaryTokenIsNotResolved() {
        final Optional<?> resolved = (Optional<?>) expectResult(Optional.class);
        assertFalse("Token should not be resolved", resolved.isPresent());
    }

    private void thenSecurityExceptionIsThrown() {
        assertEquals(Optional.of(KuraException.class), this.exception.map(Object::getClass));
        final KuraException ex = (KuraException) this.exception.get();
        assertEquals(KuraErrorCode.SECURITY_EXCEPTION, ex.getCode());
    }

    // Helper methods
    private <T> T expectResult(final Class<T> ty) {
        return this.result.filter(ty::isInstance).map(ty::cast)
                .orElseThrow(() -> new IllegalStateException("unexpected return type"));
    }

    private void call(final Callable<?> callable) {
        try {
            this.exception = Optional.empty();
            this.result = Optional.empty();
            this.result = Optional.of(callable.call());
        } catch (Exception e) {
            this.exception = Optional.of(e);
        }
    }

    private void callVoid(final Callable<Void> callable) {
        try {
            this.exception = Optional.empty();
            this.result = Optional.empty();
            callable.call();
        } catch (Exception e) {
            this.exception = Optional.of(e);
        }
    }
}
