/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.internal.cloudconnection.eclipseiot.mqtt.cloud;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;
import static org.mockito.Mockito.doReturn;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.spy;
import static org.mockito.Mockito.when;

import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

import org.eclipse.kura.message.KuraBirthPayload;
import org.eclipse.kura.net.NetInterface;
import org.eclipse.kura.net.NetInterfaceAddress;
import org.eclipse.kura.net.NetworkService;
import org.eclipse.kura.net.status.NetworkStatusService;
import org.eclipse.kura.net.status.modem.ModemConnectionStatus;
import org.eclipse.kura.net.status.modem.ModemInterfaceStatus;
import org.eclipse.kura.net.status.modem.Sim;
import org.eclipse.kura.system.SystemAdminService;
import org.eclipse.kura.system.SystemService;
import org.junit.Before;
import org.junit.Test;

public class BirthPayloadModemEidTest {

    private static final String DISPLAY_NAME = "displayName";
    private static final String VALID_EID = "89049032000001000000123456789012";

    private CloudConnectionManagerImpl cloudConnectionManagerImpl;
    private NetworkStatusService networkStatusService;
    private KuraBirthPayload birthPayload;

    @Test
    public void shouldPublishModemEidOfActivePrimarySim() throws Exception {
        givenModemWithSims(buildSim(true, true, VALID_EID));

        whenModemProfileIsReadAndBirthPayloadIsBuilt();

        thenBirthPayloadHasModemEid(VALID_EID);
    }

    @Test
    public void shouldNotPublishModemEidWhenNoSimIsActiveAndPrimary() throws Exception {
        givenModemWithSims(buildSim(false, true, VALID_EID), buildSim(true, false, VALID_EID));

        whenModemProfileIsReadAndBirthPayloadIsBuilt();

        thenBirthPayloadHasNoModemEid();
    }

    @Test
    public void shouldNotPublishModemEidWhenSimHasEmptyEid() throws Exception {
        givenModemWithSims(buildSim(true, true, ""));

        whenModemProfileIsReadAndBirthPayloadIsBuilt();

        thenBirthPayloadHasNoModemEid();
    }

    @Test
    public void shouldNotPublishModemEidWhenSimHasBlankEid() throws Exception {
        givenModemWithSims(buildSim(true, true, "   "));

        whenModemProfileIsReadAndBirthPayloadIsBuilt();

        thenBirthPayloadHasNoModemEid();
    }

    @Test
    public void shouldNotPublishModemEidWhenSimReportsErrorEid() throws Exception {
        givenModemWithSims(buildSim(true, true, "ERROR"));

        whenModemProfileIsReadAndBirthPayloadIsBuilt();

        thenBirthPayloadHasNoModemEid();
    }

    @Test
    public void shouldNotPublishModemEidWhenNoModemIsAvailable() throws Exception {
        givenNoModem();

        whenModemProfileIsReadAndBirthPayloadIsBuilt();

        thenBirthPayloadHasNoModemEid();
    }

    @Before
    public void setUp() throws Exception {
        final SystemService systemService = mock(SystemService.class);
        final NetworkService networkService = mock(NetworkService.class);
        when(networkService.getActiveNetworkInterfaces())
                .thenReturn(Collections.<NetInterface<? extends NetInterfaceAddress>> emptyList());

        final Map<String, Object> properties = new HashMap<>();
        properties.put("device.display-name", "custom");
        properties.put("device.custom-name", DISPLAY_NAME);

        this.cloudConnectionManagerImpl = spy(new CloudConnectionManagerImpl());
        this.cloudConnectionManagerImpl.setSystemService(systemService);
        this.cloudConnectionManagerImpl.setSystemAdminService(mock(SystemAdminService.class));
        this.cloudConnectionManagerImpl.setNetworkService(networkService);
        doReturn(new CloudConnectionManagerOptions(properties, systemService)).when(this.cloudConnectionManagerImpl)
                .getCloudConnectionManagerOptions();

        this.networkStatusService = mock(NetworkStatusService.class);
        this.cloudConnectionManagerImpl.setNetworkStatusService(this.networkStatusService);
    }

    private void givenModemWithSims(Sim... sims) throws Exception {
        final ModemInterfaceStatus modemStatus = ModemInterfaceStatus.builder().withInterfaceId("1-8")
                .withInterfaceName("wwan0").withConnectionStatus(ModemConnectionStatus.CONNECTED)
                .withSerialNumber("imei").withAvailableSims(Arrays.asList(sims)).build();
        when(this.networkStatusService.getInterfaceIds()).thenReturn(Arrays.asList("1-8"));
        when(this.networkStatusService.getNetworkStatus("1-8")).thenReturn(Optional.of(modemStatus));
    }

    private void givenNoModem() throws Exception {
        when(this.networkStatusService.getInterfaceIds()).thenReturn(Collections.<String> emptyList());
    }

    private void whenModemProfileIsReadAndBirthPayloadIsBuilt() {
        this.cloudConnectionManagerImpl.readModemProfile();
        this.birthPayload = new LifeCyclePayloadBuilder(this.cloudConnectionManagerImpl).buildBirthPayload();
    }

    private void thenBirthPayloadHasModemEid(String expectedEid) {
        assertEquals(expectedEid, this.birthPayload.getModemEid());
        assertEquals(DISPLAY_NAME, this.birthPayload.getDisplayName());
    }

    private void thenBirthPayloadHasNoModemEid() {
        assertNull(this.birthPayload.getModemEid());
        assertEquals(DISPLAY_NAME, this.birthPayload.getDisplayName());
    }

    private static Sim buildSim(boolean active, boolean primary, String eid) {
        return Sim.builder().withActive(active).withPrimary(primary).withIccid("iccid").withImsi("imsi")
                .withEid(eid).build();
    }
}
