/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 * Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.system;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

import java.lang.reflect.Field;
import java.util.Properties;

import org.eclipse.kura.system.SystemService;
import org.junit.Test;

public class MarketplaceCompatibilityVersionTest {

    private final SystemServiceImpl systemService = new SystemServiceImpl();
    private final Properties kuraProperties = new Properties();
    private String marketplaceCompatibilityVersion;

    /*
     * Scenarios
     */

    @Test
    public void configuredCompatibilityVersionIsNormalised() throws Exception {
        givenProperty(SystemService.KEY_KURA_VERSION, "KURA_5.6.3");
        givenProperty(SystemService.KEY_KURA_MARKETPLACE_COMPATIBILITY_VERSION, "KURA_5.6.0-SNAPSHOT");
        givenKuraProperties();

        whenMarketplaceCompatibilityVersionIsRequested();

        thenMarketplaceCompatibilityVersionIs("5.6.0.SNAPSHOT");
    }

    @Test
    public void kuraVersionIsUsedWhenNoCompatibilityVersionIsConfigured() throws Exception {
        givenProperty(SystemService.KEY_KURA_VERSION, "KURA-5.6.3");
        givenKuraProperties();

        whenMarketplaceCompatibilityVersionIsRequested();

        thenMarketplaceCompatibilityVersionIs("5.6.3");
    }

    @Test
    public void noVersionIsReportedWhenNeitherVersionIsConfigured() throws Exception {
        givenKuraProperties();

        whenMarketplaceCompatibilityVersionIsRequested();

        thenNoMarketplaceCompatibilityVersionIsReported();
    }

    /*
     * Steps
     */

    private void givenProperty(final String key, final String value) {
        this.kuraProperties.setProperty(key, value);
    }

    private void givenKuraProperties() throws Exception {
        final Field field = SystemServiceImpl.class.getDeclaredField("kuraProperties");
        field.setAccessible(true);
        field.set(this.systemService, this.kuraProperties);
    }

    private void whenMarketplaceCompatibilityVersionIsRequested() {
        this.marketplaceCompatibilityVersion = this.systemService.getKuraMarketplaceCompatibilityVersion();
    }

    private void thenMarketplaceCompatibilityVersionIs(final String expected) {
        assertEquals(expected, this.marketplaceCompatibilityVersion);
    }

    private void thenNoMarketplaceCompatibilityVersionIsReported() {
        assertNull(this.marketplaceCompatibilityVersion);
    }
}
