/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 * Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.system;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

public class NumberOfProcessorsTest {

    private final SystemServiceImpl systemService = new SystemServiceImpl();
    private int numberOfProcessors;

    /*
     * Scenarios
     */

    @Test
    public void reportsProcessorsAvailableToTheRuntime() {
        whenNumberOfProcessorsIsRequested();

        thenNumberOfProcessorsIs(Runtime.getRuntime().availableProcessors());
        thenAtLeastOneProcessorIsReported();
    }

    /*
     * Steps
     */

    private void whenNumberOfProcessorsIsRequested() {
        this.numberOfProcessors = this.systemService.getNumberOfProcessors();
    }

    private void thenNumberOfProcessorsIs(int expected) {
        assertEquals(expected, this.numberOfProcessors);
    }

    private void thenAtLeastOneProcessorIsReported() {
        assertTrue(this.numberOfProcessors >= 1);
    }
}
