/*******************************************************************************
 * Copyright (c) 2025, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.rest.provider.test;

import static org.junit.Assert.fail;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Dictionary;
import java.util.Hashtable;
import java.util.Iterator;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.TimeUnit;

import org.eclipse.kura.core.testutil.requesthandler.AbstractRequestHandlerTest;
import org.eclipse.kura.core.testutil.requesthandler.RestTransport;
import org.eclipse.kura.core.testutil.requesthandler.Transport.MethodSpec;
import org.eclipse.kura.core.testutil.requesthandler.Transport.Response;
import org.eclipse.kura.core.testutil.service.ServiceUtil;
import org.eclipse.kura.crypto.CryptoService;
import org.junit.After;
import org.junit.Test;
import org.osgi.framework.BundleContext;
import org.osgi.framework.FrameworkUtil;
import org.osgi.framework.ServiceRegistration;
import org.osgi.service.cm.Configuration;
import org.osgi.service.cm.ConfigurationAdmin;
import org.osgi.service.useradmin.Group;
import org.osgi.service.useradmin.Role;
import org.osgi.service.useradmin.User;
import org.osgi.service.useradmin.UserAdmin;

import com.eclipsesource.json.Json;
import com.eclipsesource.json.JsonObject;

import jakarta.annotation.security.RolesAllowed;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;

public class PasswordChangeSessionTest extends AbstractRequestHandlerTest {

    private static final String PASSWORD_STRENGTH_VERIFICATION_SERVICE_PID = "org.eclipse.kura.identity.PasswordStrengthVerificationService";

    private final List<ServiceRegistration<?>> registeredServices = new ArrayList<>();

    public PasswordChangeSessionTest() {
        super(new RestTransport("testservice"));
    }

    @Test
    public void shouldAllowResourceAccessAfterPasswordChangeWithoutRelogin() {
        givenPasswordStrengthDoesNotRestrictChange();
        givenServiceRequiresAssetsRole();
        givenNoBasicCredentials();
        givenIdentityRequiringPasswordChange();
        givenUserIsLoggedIn();
        givenXsrfToken();

        whenPasswordIsChanged();
        whenXsrfTokenIsObtained();
        whenProtectedResourceIsRequested();

        thenResourceAccessIsGranted();
    }

    @After
    public void cleanUp() {
        this.registeredServices.forEach(ServiceRegistration::unregister);
    }

    private void givenNoBasicCredentials() {
        givenBasicCredentials(Optional.empty());
    }

    private void givenBasicCredentials(final Optional<String> basicCredentials) {
        ((RestTransport) this.transport).setBasicCredentials(basicCredentials);
    }

    private void givenPasswordStrengthDoesNotRestrictChange() {
        givenConfiguration(PASSWORD_STRENGTH_VERIFICATION_SERVICE_PID, "new.password.min.length", 1,
                "new.password.require.digits", false, "new.password.require.special.characters", false,
                "new.password.require.both.cases", false);
    }

    private void givenServiceRequiresAssetsRole() {
        givenService(new RequiresAssetsRole());
    }

    private void givenIdentityRequiringPasswordChange() {
        givenIdentity("foo", Optional.of("bar"), Arrays.asList("rest.assets"), true);
    }

    private void givenUserIsLoggedIn() {
        givenSuccessfulRequest("http", 8080, new MethodSpec("POST"), "/session/v1/login/password",
                "{\"username\":\"foo\",\"password\":\"bar\"}");
    }

    private void givenConfiguration(final String pid, final Object... properties) {
        try {
            final ConfigurationAdmin configAdmin = ServiceUtil.trackService(ConfigurationAdmin.class, Optional.empty())
                    .get(30, TimeUnit.SECONDS);

            final Configuration configuration = configAdmin.getConfiguration(pid, "?");

            final Dictionary<String, Object> configurationProperties = Optional
                    .ofNullable(configuration.getProperties()).orElseGet(Hashtable::new);

            final Iterator<Object> iter = Arrays.asList(properties).iterator();

            while (iter.hasNext()) {
                final String key = (String) iter.next();
                final Object value = iter.next();

                configurationProperties.put(key, value);
            }

            configuration.update(configurationProperties);

        } catch (Exception e) {
            fail("cannot update configuration");
        }
    }

    @SuppressWarnings("unchecked")
    private <T extends TestService> void givenService(final T service) {
        final BundleContext bundleContext = FrameworkUtil.getBundle(PasswordChangeSessionTest.class).getBundleContext();

        final Dictionary<String, Object> properties = new Hashtable<>();
        properties.put("osgi.jakartars.resource", true);

        registeredServices.add(bundleContext.registerService((Class<T>) service.getClass(), service, properties));

        final RestTransport restTransport = (RestTransport) this.transport;

        for (int i = 0; i < 100; i++) {
            final Response response = restTransport.runRequest("/ping", new MethodSpec("GET"));

            if (response.getStatus() != 404 && response.getStatus() != 503) {
                break;
            }

            try {
                synchronized (this) {
                    this.wait(100);
                }
            } catch (InterruptedException e) {
                fail("Interrupted while waiting for service startup");
                return;
            }
        }
    }

    private void givenIdentity(final String username, final Optional<String> password, final List<String> roles,
            final boolean needsPasswordChange) {
        final UserAdmin userAdmin;

        try {
            userAdmin = ServiceUtil.trackService(UserAdmin.class, Optional.empty()).get(30, TimeUnit.SECONDS);
        } catch (Exception e) {
            fail("failed to track UserAdmin");
            return;
        }

        final User user = getOrCreateRole(userAdmin, "kura.user." + username, User.class);

        if (password.isPresent()) {
            try {
                final CryptoService cryptoService = ServiceUtil.trackService(CryptoService.class, Optional.empty())
                        .get(30, TimeUnit.SECONDS);

                user.getCredentials().put("kura.password", cryptoService.sha256Hash(password.get()));

            } catch (Exception e) {
                fail("failed to compute password hash");
            }
        }

        if (needsPasswordChange) {
            user.getProperties().put("kura.need.password.change", "true");
        } else {
            user.getProperties().remove("kura.need.password.change");
        }

        for (final String role : roles) {
            getOrCreateRole(userAdmin, "kura.permission." + role, Group.class).addMember(user);
        }
    }

    private void givenSuccessfulRequest(final String proto, final int port, final MethodSpec method,
            final String resource, final String body) {
        whenRequestIsPerformed(proto, port, method, resource, body);
        thenRequestSucceeds();
    }

    private void givenXsrfToken() {
        whenXsrfTokenIsObtained();
    }

    private void whenPasswordIsChanged() {
        whenRequestIsPerformed("http", 8080, new MethodSpec("POST"), "/session/v1/changePassword",
                "{\"currentPassword\":\"bar\",\"newPassword\":\"baz\"}");
    }

    private void whenProtectedResourceIsRequested() {
        whenRequestIsPerformed(new MethodSpec("GET"), "/requireAssets");
    }

    private void whenRequestIsPerformed(final String proto, final int port, final MethodSpec method,
            final String resource, final String body) {
        final RestTransport restTransport = (RestTransport) this.transport;

        this.response = Optional
                .of(restTransport.runRequest(proto + "://localhost:" + port + "/services", resource, method, body));
    }

    private void whenXsrfTokenIsObtained() {
        final RestTransport restTransport = (RestTransport) this.transport;

        final Response response = restTransport.runRequest("http://localhost:8080/services", "/session/v1/xsrfToken",
                new MethodSpec("GET"), null);

        final JsonObject object = Json
                .parse(response.getBody().orElseThrow(() -> new IllegalStateException("no response body"))).asObject();

        final String token = object.get("xsrfToken").asString();

        restTransport.setHeader("X-XSRF-Token", token);
    }

    private void thenResourceAccessIsGranted() {
        thenResponseCodeIs(200);
    }

    @SuppressWarnings("unchecked")
    private <T extends Role> T getOrCreateRole(final UserAdmin userAdmin, final String name, final Class<T> classz) {
        final Role existing = userAdmin.getRole(name);

        if (classz.isInstance(existing)) {
            return (T) existing;
        }

        final int type;

        if (classz == User.class) {
            type = Role.USER;
        } else if (classz == Group.class) {
            type = Role.GROUP;
        } else {
            fail("Unsupported role type");
            return null;
        }

        return (T) userAdmin.createRole(name, type);
    }

    public static abstract class TestService {

        @GET
        @Path("/ping")
        public String ping() {
            return "ok";
        }

    }

    @Path("testservice")
    public static class RequiresAssetsRole extends TestService {

        @GET
        @Path("requireAssets")
        @RolesAllowed("assets")
        public String requireAssets() {
            return "Hello";
        }
    }
}
