/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.rest.provider.test.util;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotEquals;
import static org.junit.Assert.fail;

import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.ArrayList;
import java.util.Base64;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Hashtable;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.concurrent.TimeUnit;

import org.eclipse.kura.configuration.ConfigurationService;
import org.eclipse.kura.core.testutil.requesthandler.AbstractRequestHandlerTest;
import org.eclipse.kura.core.testutil.requesthandler.RestTransport;
import org.eclipse.kura.core.testutil.requesthandler.Transport.MethodSpec;
import org.eclipse.kura.core.testutil.requesthandler.Transport.Response;
import org.eclipse.kura.core.testutil.service.ServiceUtil;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.osgi.framework.FrameworkUtil;
import org.osgi.framework.ServiceRegistration;

import com.eclipsesource.json.JsonObject;

/**
 * Shared steps of the JWT REST scenarios. JWT authentication is enabled with the default configuration before each
 * scenario, and the configuration is restored after it.
 */
public abstract class AbstractJwtRestScenario extends AbstractRequestHandlerTest {

    public enum IdentityChange {
        DELETED,
        REQUIRED_TO_CHANGE_PASSWORD
    }

    protected static final String IDENTITY = "jwt-alice";
    protected static final String ASSETS_PERMISSION = "rest.assets";
    protected static final int MAX_REFRESH_TOKEN_BYTES = 8 * 1024;

    protected static final String JWT_ENABLED = "auth.jwt.enabled";
    protected static final String ACCESS_TOKEN_DURATION = "auth.jwt.access.token.duration";
    protected static final String REFRESH_TOKEN_DURATION = "auth.jwt.refresh.token.duration";
    protected static final String USED_REFRESH_TOKEN_RETENTION = "auth.jwt.used.refresh.token.retention";
    protected static final String ISSUING_SERVICE_TARGET = "TokenIssuingService.target";
    protected static final String VERIFICATION_SERVICE_TARGET = "TokenVerificationService.target";
    protected static final String DEFAULT_VERIFICATION_SERVICE_TARGET = //
            "(objectClass=org.eclipse.kura.security.token.TokenVerificationService)";
    protected static final String UNMATCHED_TARGET = "(kura.service.pid=does.not.exist)";

    protected static final String SIGNING_KEY_ALIAS = TokenServicesFixture.SIGNING_KEY_ALIAS;
    protected static final String MISSING_KEY_ALIAS = TokenServicesFixture.MISSING_KEY_ALIAS;
    protected static final Duration MAXIMUM_TOKEN_LIFETIME = TokenServicesFixture.MAXIMUM_TOKEN_LIFETIME;

    protected static final Optional<String> NO_AUTHORIZATION = Optional.empty();

    private static final String PASSWORD = "Jwt-Password-1!";
    private static final String SERVICES_URL = "http://localhost:8080/services/";
    private static final String REST_SERVICE_PID = "org.eclipse.kura.internal.rest.provider.RestService";
    private static final Map<String, Object> DEFAULT_JWT_CONFIGURATION = Map.of( //
            JWT_ENABLED, false, //
            ACCESS_TOKEN_DURATION, 60, //
            REFRESH_TOKEN_DURATION, 900, //
            USED_REFRESH_TOKEN_RETENTION, 300, //
            ISSUING_SERVICE_TARGET, "(objectClass=org.eclipse.kura.security.token.TokenIssuingService)", //
            VERIFICATION_SERVICE_TARGET, DEFAULT_VERIFICATION_SERVICE_TARGET);

    private static final TokenServicesFixture tokenServices = new TokenServicesFixture();

    private final IdentityFixture identities = new IdentityFixture();
    private ServiceRegistration<ProtectedResource> protectedResource;

    private JsonObject tokenPair;
    private String accessToken;
    private String refreshToken;
    private final List<String> exchangedRefreshTokens = new ArrayList<>();

    protected AbstractJwtRestScenario() {
        super(new RestTransport("token/jwt/v1"));
    }

    @BeforeClass
    public static void setUpTokenServices() throws Exception {
        tokenServices.setUp();
    }

    @AfterClass
    public static void tearDownTokenServices() throws Exception {
        tokenServices.tearDown();
    }

    @Before
    public void setUp() throws Exception {
        givenTheRestServiceProperties(Map.of(JWT_ENABLED, true));
        registerProtectedResource();
    }

    @After
    public void tearDown() throws Exception {
        if (this.protectedResource != null) {
            this.protectedResource.unregister();
        }

        this.identities.deleteAll();
        tokenServices.useIssuerSigningKeyAlias(SIGNING_KEY_ALIAS);
        givenTheRestServiceProperties(DEFAULT_JWT_CONFIGURATION);
    }

    /*
     * Given
     */

    protected void givenTheRestServiceProperties(final Map<String, Object> properties) throws Exception {
        final Map<String, Object> configuration = new HashMap<>(DEFAULT_JWT_CONFIGURATION);
        configuration.put(JWT_ENABLED, true);
        configuration.putAll(properties);

        final ConfigurationService configurationService = ServiceUtil
                .trackService(ConfigurationService.class, Optional.empty()).get(30, TimeUnit.SECONDS);

        ServiceUtil.updateComponentConfiguration(configurationService, REST_SERVICE_PID, configuration).get(30,
                TimeUnit.SECONDS);
    }

    protected void givenTheIssuerSigningKeyAlias(final String alias) throws Exception {
        tokenServices.useIssuerSigningKeyAlias(alias);
    }

    protected void givenAnIdentityWithPermissions(final String... permissions) throws Exception {
        this.identities.create(IDENTITY, PASSWORD, List.of(permissions));
    }

    protected void givenTheIdentityIs(final IdentityChange change) throws Exception {
        switch (change) {
        case DELETED -> this.identities.delete(IDENTITY);
        case REQUIRED_TO_CHANGE_PASSWORD -> this.identities.requirePasswordChange(IDENTITY);
        }
    }

    protected void givenATokenPairIssuedToTheIdentity() {
        whenATokenPairIsRequestedWith(basic(IDENTITY));

        thenATokenPairIsReturned();
    }

    protected void givenTheRefreshTokenWasExchangedWithStatus(final int status) {
        whenTheRefreshEndpointReceives(theRefreshToken());

        thenResponseCodeIs(status);

        if (status == 200) {
            thenATokenPairIsReturned();
        }
    }

    protected void givenTimePasses(final Duration duration) throws InterruptedException {
        Thread.sleep(duration.toMillis());
    }

    /*
     * When
     */

    protected void whenATokenPairIsRequestedWith(final Optional<String> authorization) {
        authorizeWith(authorization);
        whenRequestIsPerformed(new MethodSpec("POST"), "/issue");
    }

    protected void whenTheProtectedResourceIsAccessedWith(final Optional<String> authorization) {
        authorizeWith(authorization);
        this.response = Optional.of(restTransport().runRequest(SERVICES_URL,
                ProtectedResource.PATH + ProtectedResource.ASSETS_PATH, new MethodSpec("GET"), null));
    }

    protected void whenTheRefreshEndpointReceives(final String body) {
        authorizeWith(NO_AUTHORIZATION);
        restTransport().setHeader("Content-Type", "text/plain");
        whenRequestIsPerformed(new MethodSpec("POST"), "/refresh", body);
        restTransport().removeHeader("Content-Type");

        if (expectResponse().getStatus() == 200) {
            this.exchangedRefreshTokens.add(body.trim());
        }
    }

    /*
     * Then
     */

    protected void thenATokenPairIsReturned() {
        thenResponseCodeIs(200);

        final JsonObject tokenPair = expectJsonResponse();
        assertEquals(Set.of("tokenType", "accessToken", "accessTokenExpiresInSeconds", "refreshToken",
                "refreshTokenExpiresInSeconds"), new HashSet<>(tokenPair.names()));
        assertEquals("Bearer", tokenPair.get("tokenType").asString());

        this.tokenPair = tokenPair;
        this.accessToken = tokenPair.get("accessToken").asString();
        this.refreshToken = tokenPair.get("refreshToken").asString();
        assertFalse(this.accessToken.isEmpty());
        assertFalse(this.refreshToken.isEmpty());
    }

    // checks both the lifetime reported to the client and the one of the issued tokens
    protected void thenTheTokensLast(final Duration accessTokenDuration, final Duration refreshTokenDuration) {
        assertEquals(accessTokenDuration.toSeconds(), this.tokenPair.get("accessTokenExpiresInSeconds").asLong());
        assertEquals(refreshTokenDuration.toSeconds(), this.tokenPair.get("refreshTokenExpiresInSeconds").asLong());
        assertEquals(accessTokenDuration, lifetime(this.accessToken));
        assertEquals(refreshTokenDuration, lifetime(this.refreshToken));
    }

    protected void thenResponseContainsHeader(final String headerName, final String expectedHeaderValue) {
        assertEquals(List.of(expectedHeaderValue), expectResponse().getHeader(headerName));
    }

    protected void thenTheReturnedRefreshTokenDiffersFromTheExchangedOne() {
        assertNotEquals(this.exchangedRefreshTokens.get(this.exchangedRefreshTokens.size() - 1), this.refreshToken);
    }

    protected void thenTheReturnedAccessTokenGrantsAccessToTheProtectedResource() {
        whenTheProtectedResourceIsAccessedWith(bearer(theAccessToken()));

        thenResponseCodeIs(200);
    }

    /*
     * Step arguments
     */

    protected String theAccessToken() {
        return this.accessToken;
    }

    protected String theRefreshToken() {
        return this.refreshToken;
    }

    protected String theFirstExchangedRefreshToken() {
        return this.exchangedRefreshTokens.get(0);
    }

    protected String theAccessTokenForgedFor(final String identityName) {
        final String forgedToken = Jwt.withSubject(this.accessToken, identityName);
        assertNotEquals("the token was not altered", this.accessToken, forgedToken);
        return forgedToken;
    }

    protected static Optional<String> basic(final String identityName) {
        final String credentials = identityName + ":" + PASSWORD;
        return header("Basic " + Base64.getEncoder().encodeToString(credentials.getBytes(StandardCharsets.UTF_8)));
    }

    protected static Optional<String> bearer(final String token) {
        return header("Bearer " + token);
    }

    protected static Optional<String> header(final String authorization) {
        return Optional.of(authorization);
    }

    /*
     * Helpers
     */

    private void authorizeWith(final Optional<String> authorization) {
        restTransport().setBasicCredentials(Optional.empty());
        authorization.ifPresentOrElse(value -> restTransport().setHeader("Authorization", value),
                () -> restTransport().removeHeader("Authorization"));
    }

    private static Duration lifetime(final String token) {
        final JsonObject claims = Jwt.claims(token);
        return Duration.ofSeconds(claims.get("exp").asLong() - claims.get("nbf").asLong());
    }

    private RestTransport restTransport() {
        return (RestTransport) this.transport;
    }

    private void registerProtectedResource() throws InterruptedException {
        final Hashtable<String, Object> properties = new Hashtable<>();
        properties.put("osgi.jakartars.resource", true);

        this.protectedResource = FrameworkUtil.getBundle(AbstractJwtRestScenario.class).getBundleContext()
                .registerService(ProtectedResource.class, new ProtectedResource(), properties);

        for (int i = 0; i < 100; i++) {
            final Response ping = restTransport().runRequest(SERVICES_URL,
                    ProtectedResource.PATH + ProtectedResource.PING_PATH, new MethodSpec("GET"), null);

            if (ping.getStatus() == 200) {
                return;
            }

            Thread.sleep(100);
        }

        fail("the protected resource was not registered");
    }
}
