/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.rest.provider.test.util;

import java.util.HashSet;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.concurrent.TimeUnit;

import org.eclipse.kura.core.testutil.service.ServiceUtil;
import org.eclipse.kura.crypto.CryptoService;
import org.osgi.service.useradmin.Group;
import org.osgi.service.useradmin.Role;
import org.osgi.service.useradmin.User;
import org.osgi.service.useradmin.UserAdmin;

/**
 * Creates and removes identities through {@link UserAdmin}, using the same role naming as the Kura identity service.
 */
public class IdentityFixture {

    private static final String USER_PREFIX = "kura.user.";
    private static final String PERMISSION_PREFIX = "kura.permission.";
    private static final String PASSWORD_CHANGE_NEEDED = "kura.need.password.change";

    private final Set<String> createdIdentities = new HashSet<>();

    @SuppressWarnings("unchecked")
    public void create(final String name, final String password, final List<String> permissions) throws Exception {
        final User user = getOrCreateRole(USER_PREFIX + name, User.class, Role.USER);
        user.getCredentials().put("kura.password", service(CryptoService.class).sha256Hash(password));
        this.createdIdentities.add(name);

        for (final String permission : permissions) {
            getOrCreateRole(PERMISSION_PREFIX + permission, Group.class, Role.GROUP).addMember(user);
        }
    }

    @SuppressWarnings("unchecked")
    public void requirePasswordChange(final String name) throws Exception {
        final Role user = service(UserAdmin.class).getRole(USER_PREFIX + name);
        user.getProperties().put(PASSWORD_CHANGE_NEEDED, "true");
    }

    public void delete(final String name) throws Exception {
        service(UserAdmin.class).removeRole(USER_PREFIX + name);
        this.createdIdentities.remove(name);
    }

    public void deleteAll() throws Exception {
        for (final String name : Set.copyOf(this.createdIdentities)) {
            delete(name);
        }
    }

    private static <T extends Role> T getOrCreateRole(final String name, final Class<T> type, final int roleType)
            throws Exception {
        final UserAdmin userAdmin = service(UserAdmin.class);
        final Role existing = userAdmin.getRole(name);

        if (existing != null && existing.getType() == roleType) {
            return type.cast(existing);
        }

        return type.cast(userAdmin.createRole(name, roleType));
    }

    private static <T> T service(final Class<T> serviceClass) throws Exception {
        return ServiceUtil.trackService(serviceClass, Optional.empty()).get(30, TimeUnit.SECONDS);
    }
}
