/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.rest.provider.test.util;

import java.nio.charset.StandardCharsets;
import java.util.Base64;

import com.eclipsesource.json.Json;
import com.eclipsesource.json.JsonObject;

/**
 * Reads and alters the payload of a signed JWT, without touching its signature.
 */
public final class Jwt {

    private Jwt() {
    }

    public static JsonObject claims(final String token) {
        final String payload = token.split("\\.")[1];
        return Json.parse(new String(Base64.getUrlDecoder().decode(payload), StandardCharsets.UTF_8)).asObject();
    }

    public static String withSubject(final String token, final String subject) {
        final String[] parts = token.split("\\.");
        final String forgedPayload = claims(token).set("sub", subject).toString();

        return parts[0] + "." + Base64.getUrlEncoder().withoutPadding()
                .encodeToString(forgedPayload.getBytes(StandardCharsets.UTF_8)) + "." + parts[2];
    }
}
