/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.rest.provider.test.util;

import jakarta.annotation.security.RolesAllowed;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;

/**
 * A REST resource that requires the {@code rest.assets} permission.
 */
@Path(ProtectedResource.PATH)
public class ProtectedResource {

    public static final String PATH = "jwttest";
    public static final String PING_PATH = "/ping";
    public static final String ASSETS_PATH = "/assets";

    @GET
    @Path(PING_PATH)
    public String ping() {
        return "ok";
    }

    @GET
    @Path(ASSETS_PATH)
    @RolesAllowed("assets")
    public String assets() {
        return "ok";
    }
}
