/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.rest.provider.test.util;

import java.io.File;
import java.nio.file.Files;
import java.security.KeyPair;
import java.security.KeyStore.PrivateKeyEntry;
import java.security.cert.Certificate;
import java.security.cert.X509Certificate;
import java.time.Duration;
import java.util.Hashtable;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.TimeUnit;
import java.util.function.BooleanSupplier;

import org.bouncycastle.asn1.x500.X500Name;
import org.eclipse.kura.configuration.ConfigurationService;
import org.eclipse.kura.core.testutil.pki.TestCA;
import org.eclipse.kura.core.testutil.pki.TestCA.CertificateCreationOptions;
import org.eclipse.kura.core.testutil.service.ServiceUtil;
import org.eclipse.kura.security.keystore.KeystoreService;
import org.eclipse.kura.security.token.TokenIssueRequest;
import org.eclipse.kura.security.token.TokenIssuingService;
import org.eclipse.kura.security.token.TokenVerificationService;
import org.eclipse.kura.security.token.TokenVerifyRequest;
import org.osgi.service.cm.Configuration;
import org.osgi.service.cm.ConfigurationAdmin;

/**
 * Provides a real {@link TokenIssuingService} and {@link TokenVerificationService}, backed by
 * {@code org.eclipse.kura.core.token.jwt} and a dedicated key store holding an RSA signing key.
 */
public class TokenServicesFixture {

    private static final String KEYSTORE_PID = "org.eclipse.kura.rest.provider.test.JwtKeystore";
    private static final String KEYSTORE_FACTORY_PID = "org.eclipse.kura.core.keystore.FilesystemKeystoreServiceImpl";
    private static final String ISSUER_PID = "org.eclipse.kura.core.token.jwt.issuer.JwtIssuingService";
    private static final String VERIFIER_PID = "org.eclipse.kura.core.token.jwt.verifier.JwtVerificationService";
    public static final String SIGNING_KEY_ALIAS = "jwt-signing-key";
    public static final String MISSING_KEY_ALIAS = "missing-key";
    public static final Duration MAXIMUM_TOKEN_LIFETIME = Duration.ofHours(1);
    private static final String KEYSTORE_TARGET = "(kura.service.pid=" + KEYSTORE_PID + ")";
    private static final String PROBE_CONSUMER = "probe";
    private static final Duration TIMEOUT = Duration.ofSeconds(30);

    private String issuerSigningKeyAlias = SIGNING_KEY_ALIAS;

    public void setUp() throws Exception {
        createKeystoreWithSigningKey();
        configure(VERIFIER_PID, Map.of("KeystoreService.target", KEYSTORE_TARGET));
        configureIssuer(SIGNING_KEY_ALIAS);

        waitUntil(TokenServicesFixture::tokensCanBeIssuedAndVerified, "token services are not ready");
    }

    public void tearDown() throws Exception {
        configurationAdmin().getConfiguration(ISSUER_PID, "?").delete();
        configurationAdmin().getConfiguration(VERIFIER_PID, "?").delete();
        ServiceUtil.deleteFactoryConfiguration(configurationService(), KEYSTORE_PID).get(TIMEOUT.toSeconds(),
                TimeUnit.SECONDS);
    }

    /**
     * Configures the alias of the key used by the issuer: tokens can be issued only with {@link #SIGNING_KEY_ALIAS}.
     */
    public void useIssuerSigningKeyAlias(final String alias) throws Exception {
        if (alias.equals(this.issuerSigningKeyAlias)) {
            return;
        }

        configureIssuer(alias);
        this.issuerSigningKeyAlias = alias;

        final boolean issuingExpected = SIGNING_KEY_ALIAS.equals(alias);
        waitUntil(() -> tokensCanBeIssuedAndVerified() == issuingExpected,
                "the issuer did not apply the signing key alias " + alias);
    }

    private void createKeystoreWithSigningKey() throws Exception {
        final File keystoreFile = new File(Files.createTempDirectory(null).toFile(), "jwt.ks");

        final KeystoreService keystore = ServiceUtil
                .createFactoryConfiguration(configurationService(), KeystoreService.class, KEYSTORE_PID,
                        KEYSTORE_FACTORY_PID, Map.of("keystore.path", keystoreFile.getAbsolutePath()))
                .get(TIMEOUT.toSeconds(), TimeUnit.SECONDS);

        final TestCA ca = new TestCA(CertificateCreationOptions.builder(new X500Name("cn=jwt-ca, dc=bar.com")).build());
        final KeyPair keyPair = TestCA.generateKeyPair();
        final X509Certificate certificate = ca.createAndSignCertificate(
                CertificateCreationOptions.builder(new X500Name("cn=jwt-signer, dc=bar.com")).build(), keyPair);

        keystore.setEntry(SIGNING_KEY_ALIAS,
                new PrivateKeyEntry(keyPair.getPrivate(), new Certificate[] { certificate, ca.getCertificate() }));
    }

    private void configureIssuer(final String signingKeyAlias) throws Exception {
        configure(ISSUER_PID, Map.of("KeystoreService.target", KEYSTORE_TARGET, "signing.key.alias", signingKeyAlias,
                "maximum.lifetime.seconds", (int) MAXIMUM_TOKEN_LIFETIME.toSeconds()));
    }

    private static void configure(final String pid, final Map<String, Object> properties) throws Exception {
        final Configuration configuration = configurationAdmin().getConfiguration(pid, "?");
        configuration.update(new Hashtable<>(properties));
    }

    private static boolean tokensCanBeIssuedAndVerified() {
        try {
            final String token = service(TokenIssuingService.class).issue(
                    TokenIssueRequest.builder("probe").intendedConsumer(PROBE_CONSUMER).build());
            service(TokenVerificationService.class)
                    .verify(TokenVerifyRequest.builder(token).intendedConsumer(PROBE_CONSUMER).build());
            return true;
        } catch (final Exception e) {
            return false;
        }
    }

    private static void waitUntil(final BooleanSupplier condition, final String failureMessage)
            throws InterruptedException {
        final long deadline = System.nanoTime() + TIMEOUT.toNanos();

        while (!condition.getAsBoolean()) {
            if (System.nanoTime() > deadline) {
                throw new IllegalStateException(failureMessage);
            }

            Thread.sleep(200);
        }
    }

    private static <T> T service(final Class<T> serviceClass) throws Exception {
        return ServiceUtil.trackService(serviceClass, Optional.empty()).get(TIMEOUT.toSeconds(), TimeUnit.SECONDS);
    }

    private static ConfigurationService configurationService() throws Exception {
        return service(ConfigurationService.class);
    }

    private static ConfigurationAdmin configurationAdmin() throws Exception {
        return service(ConfigurationAdmin.class);
    }
}
