/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 * Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.internal.ble;

import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertSame;
import static org.mockito.Mockito.mock;

import org.eclipse.kura.core.testutil.TestUtil;
import org.eclipse.kura.system.SystemService;
import org.junit.Test;

public class SystemServiceBindingTest {

    private final BluetoothLeServiceImpl bluetoothLeService = new BluetoothLeServiceImpl();
    private final SystemService boundSystemService = mock(SystemService.class);
    private final SystemService otherSystemService = mock(SystemService.class);

    /*
     * Scenarios
     */

    @Test
    public void unsetBoundSystemServiceClearsReference() throws NoSuchFieldException {
        givenSystemServiceBound(this.boundSystemService);

        whenSystemServiceUnset(this.boundSystemService);

        thenSystemServiceReferenceIsNull();
    }

    @Test
    public void unsetDifferentSystemServiceKeepsReference() throws NoSuchFieldException {
        givenSystemServiceBound(this.boundSystemService);

        whenSystemServiceUnset(this.otherSystemService);

        thenSystemServiceReferenceIs(this.boundSystemService);
    }

    /*
     * Steps
     */

    private void givenSystemServiceBound(SystemService systemService) {
        this.bluetoothLeService.setSystemService(systemService);
    }

    private void whenSystemServiceUnset(SystemService systemService) {
        this.bluetoothLeService.unsetSystemService(systemService);
    }

    private void thenSystemServiceReferenceIsNull() throws NoSuchFieldException {
        assertNull(TestUtil.getFieldValue(this.bluetoothLeService, "systemService"));
    }

    private void thenSystemServiceReferenceIs(SystemService expected) throws NoSuchFieldException {
        assertSame(expected, TestUtil.getFieldValue(this.bluetoothLeService, "systemService"));
    }
}
