/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 * Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.net.admin.modem.sierra;

import static org.junit.Assert.assertArrayEquals;

import org.junit.Test;

public class HipFramingTest {

    private static final byte FRAME = (byte) 0x7E;
    private static final byte ESCAPE = (byte) 0x7D;
    private static final byte MESSAGE_ID = (byte) 0x2B;
    private static final byte PARAMETER = (byte) 0x00;

    private byte[] payload;
    private byte[] message;

    /*
     * Scenarios
     */

    @Test
    public void framesPayloadWithoutSpecialBytes() {
        givenPayload(0x01, 0x02, 0x03);

        whenHipRequestIsBuilt();

        thenMessageIs(FRAME, 0x00, 0x03, MESSAGE_ID, PARAMETER, 0x01, 0x02, 0x03, FRAME);
    }

    @Test
    public void escapesFrameAndEscapeBytesInPayload() {
        givenPayload(0x01, 0x7E, 0x02, 0x7D);

        whenHipRequestIsBuilt();

        thenMessageIs(FRAME, 0x00, 0x04, MESSAGE_ID, PARAMETER, 0x01, ESCAPE, 0x5E, 0x02, ESCAPE, 0x5D, FRAME);
    }

    @Test
    public void escapesConsecutiveSpecialBytes() {
        givenPayload(0x7E, 0x7E, 0x7D);

        whenHipRequestIsBuilt();

        thenMessageIs(FRAME, 0x00, 0x03, MESSAGE_ID, PARAMETER, ESCAPE, 0x5E, ESCAPE, 0x5E, ESCAPE, 0x5D, FRAME);
    }

    @Test
    public void escapesSpecialByteInPayloadLength() {
        givenPayloadOfLength(0x7E);

        whenHipRequestIsBuilt();

        thenMessageStartsWith(FRAME, 0x00, ESCAPE, 0x5E, MESSAGE_ID, PARAMETER);
    }

    /*
     * Steps
     */

    private void givenPayload(int... bytes) {
        this.payload = toBytes(bytes);
    }

    private void givenPayloadOfLength(int length) {
        this.payload = new byte[length];
    }

    private void whenHipRequestIsBuilt() {
        this.message = new Hip(this.payload).getHIPmessage();
    }

    private void thenMessageIs(int... expected) {
        assertArrayEquals(toBytes(expected), this.message);
    }

    private void thenMessageStartsWith(int... expected) {
        final byte[] start = new byte[expected.length];
        System.arraycopy(this.message, 0, start, 0, expected.length);
        assertArrayEquals(toBytes(expected), start);
    }

    /*
     * Utilities
     */

    private static byte[] toBytes(int... values) {
        final byte[] result = new byte[values.length];
        for (int i = 0; i < values.length; i++) {
            result[i] = (byte) values[i];
        }
        return result;
    }
}
