/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt.lifecycle;

import java.time.Duration;

import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.KuraException;
import org.eclipse.kura.core.testutil.pki.TestCA.TestCAException;
import org.eclipse.kura.core.token.jwt.common.AbstractJwtScenario;
import org.eclipse.kura.core.token.jwt.common.IssuingConfig;
import org.eclipse.kura.core.token.jwt.common.TestKeys;
import org.eclipse.kura.core.token.jwt.common.TestToken;
import org.eclipse.kura.core.token.jwt.common.VerificationConfig;
import org.junit.Test;

public class DeactivationTest extends AbstractJwtScenario {

    private static final String TRUST_ALIAS = "trusted-signer";
    private static final int SIGNER_KEY = 0;
    private static final int MAXIMUM_LIFETIME_SECONDS = 600;

    @Test
    public void deactivationDisablesTheServices() throws TestCAException {
        givenActivatedServicesWithKeyMaterial();
        givenTheIssuerReportsMaximumLifetime(Duration.ofSeconds(MAXIMUM_LIFETIME_SECONDS));

        whenTheServicesAreDeactivated();

        thenIssuingIsUnavailable();
        thenTheIssuerReportsNoMaximumLifetime();
        thenVerificationIsUnavailable();
    }

    @Test
    public void unbindingTheBoundKeystoreAfterDeactivationLeavesTheServicesDisabled()
            throws TestCAException, KuraException {

        givenActivatedAndDeactivatedServices();

        whenTheBoundKeystoreIsUnbound();

        thenIssuingIsUnavailable();
        thenTheIssuerReportsNoMaximumLifetime();
        thenVerificationIsUnavailable();
        thenTheKeystoreWasNotConsultedAgain();
    }

    @Test
    public void bindingAKeystoreAfterDeactivationDoesNotRestoreTheServices() throws TestCAException, KuraException {
        givenActivatedAndDeactivatedServices();

        whenTheKeystoreIsBoundAgain();

        thenIssuingIsUnavailable();
        thenTheIssuerReportsNoMaximumLifetime();
        thenVerificationIsUnavailable();
        thenTheKeystoreWasNotConsultedAgain();
    }

    @Test
    public void aKeystoreChangeAfterDeactivationDoesNotRestoreTheServices() throws TestCAException, KuraException {
        givenActivatedAndDeactivatedServices();

        whenTheBoundKeystoreAnnouncesAChange();

        thenIssuingIsUnavailable();
        thenTheIssuerReportsNoMaximumLifetime();
        thenVerificationIsUnavailable();
        thenTheKeystoreWasNotConsultedAgain();
    }

    private void givenActivatedAndDeactivatedServices() throws TestCAException {
        givenActivatedServicesWithKeyMaterial();
        givenTheServicesWereDeactivated();
    }

    private void givenActivatedServicesWithKeyMaterial() throws TestCAException {
        givenKeystorePrivateKeyEntry(SIGNING_ALIAS, SIGNER_KEY);
        givenKeystoreTrustedCertificate(TRUST_ALIAS, SIGNER_KEY);
        givenTheIssuerIsBoundToTheKeystore();
        givenTheIssuerIsActivatedWith(IssuingConfig.defaults() //
                .withSigningKeyAlias(SIGNING_ALIAS) //
                .withMaximumLifetimeSeconds(MAXIMUM_LIFETIME_SECONDS));
        givenTheVerifierIsBoundToTheKeystore();
        givenTheVerifierIsActivatedWith(VerificationConfig.defaults());
    }

    private void thenIssuingIsUnavailable() {
        whenATokenIsIssuedFor(TEST_IDENTITY);

        thenNoTokenIsIssued();
        thenIssuingFailedWith(KuraErrorCode.CONFIGURATION_ERROR);
    }

    private void thenVerificationIsUnavailable() throws TestCAException {
        whenATokenIsVerified(aTokenSignedWithTheSignerKey());

        thenNoVerificationProofIsProduced();
        thenVerificationFailedWith(KuraErrorCode.CONFIGURATION_ERROR);
    }

    private static String aTokenSignedWithTheSignerKey() throws TestCAException {
        return TestToken.builder() //
                .issuer(DEFAULT_ISSUER) //
                .subject(TEST_IDENTITY) //
                .signedWith(TestKeys.rsaPrivateKey(SIGNER_KEY));
    }

}
