/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt.lifecycle;

import org.eclipse.kura.KuraException;
import org.eclipse.kura.core.testutil.pki.TestCA.TestCAException;
import org.eclipse.kura.core.token.jwt.common.AbstractJwtScenario;
import org.eclipse.kura.core.token.jwt.common.IssuingConfig;
import org.eclipse.kura.core.token.jwt.common.VerificationConfig;
import org.junit.Test;

public class KeystoreChangeFilteringTest extends AbstractJwtScenario {

    private static final int SIGNER_KEY = 0;

    @Test
    public void aChangeAnnouncedByAnotherKeystoreDoesNotReloadKeyMaterial() throws TestCAException, KuraException {
        givenActivatedServicesWithKeyMaterial();

        whenAForeignKeystoreAnnouncesAChange();

        thenTheKeystoreWasNotConsultedAgain();
    }

    @Test
    public void aChangeWithoutASenderPidDoesNotReloadKeyMaterial() throws TestCAException, KuraException {
        givenActivatedServicesWithKeyMaterial();

        whenAKeystoreChangeWithoutSenderPidIsDelivered();

        thenTheKeystoreWasNotConsultedAgain();
    }

    @Test
    public void anUnrelatedEventOnTheKeystoreTopicDoesNotReloadKeyMaterial() throws TestCAException, KuraException {
        givenActivatedServicesWithKeyMaterial();

        whenAnUnrelatedEventOnTheKeystoreTopicIsDelivered();

        thenTheKeystoreWasNotConsultedAgain();
    }

    @Test
    public void aChangeAnnouncedByTheBoundKeystoreDoesReloadKeyMaterial() throws TestCAException, KuraException {
        givenActivatedServicesWithKeyMaterial();

        whenTheBoundKeystoreAnnouncesAChange();

        thenTheKeystoreWasConsultedAgain();
    }

    @Test
    public void anIgnoredEventLeavesTheServicesWorking() throws TestCAException {
        givenActivatedServicesWithKeyMaterial();
        givenAForeignKeystoreAnnouncedAChange();

        whenATokenIsIssuedFor(TEST_IDENTITY);

        thenATokenIsIssued();
    }

    @Test
    public void anIgnoredEventLeavesVerificationWorking() throws TestCAException {
        givenActivatedServicesWithKeyMaterial();
        givenAForeignKeystoreAnnouncedAChange();
        givenATokenWasIssued();

        whenTheIssuedTokenIsVerified();

        thenTheTokenIsVerifiedFor(TEST_IDENTITY);
    }

    private void givenActivatedServicesWithKeyMaterial() throws TestCAException {
        givenKeystorePrivateKeyEntry(SIGNING_ALIAS, SIGNER_KEY);
        givenTheIssuerIsBoundToTheKeystore();
        givenTheIssuerIsActivatedWith(IssuingConfig.defaults().withSigningKeyAlias(SIGNING_ALIAS));
        givenTheVerifierIsBoundToTheKeystore();
        givenTheVerifierIsActivatedWith(VerificationConfig.defaults());
    }

    private void givenATokenWasIssued() {
        whenATokenIsIssuedFor(TEST_IDENTITY);

        thenATokenIsIssued();
    }

}
