/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt.lifecycle;

import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.core.testutil.pki.TestCA.TestCAException;
import org.eclipse.kura.core.token.jwt.common.AbstractJwtScenario;
import org.eclipse.kura.core.token.jwt.common.IssuingConfig;
import org.eclipse.kura.core.token.jwt.common.TestKeys;
import org.eclipse.kura.core.token.jwt.common.TestToken;
import org.eclipse.kura.core.token.jwt.common.VerificationConfig;
import org.junit.Test;

public class KeystoreChangeReloadTest extends AbstractJwtScenario {

    private static final String TRUST_ALIAS = "trusted-signer";
    private static final int SIGNER_KEY = 0;

    @Test
    public void aSigningKeyAddedAfterActivationBecomesUsable() throws TestCAException {
        givenAnActivatedIssuer();
        givenIssuingIsNotAvailableYet();
        givenKeystorePrivateKeyEntry(SIGNING_ALIAS, SIGNER_KEY);
        givenTheBoundKeystoreAnnouncedAChange();

        whenATokenIsIssuedFor(TEST_IDENTITY);

        thenATokenIsIssued();
        thenIssuedTokenHeaderHas("kid", SIGNING_ALIAS);
    }

    @Test
    public void aTrustedCertificateAddedAfterActivationBecomesUsable() throws TestCAException {
        givenAnActivatedVerifier();
        givenVerificationIsNotAvailableYetFor(aTokenSignedWithTheSignerKey());
        givenKeystoreTrustedCertificate(TRUST_ALIAS, SIGNER_KEY);
        givenTheBoundKeystoreAnnouncedAChange();

        whenATokenIsVerified(aTokenSignedWithTheSignerKey());

        thenTheTokenIsVerifiedFor(TEST_IDENTITY);
    }

    @Test
    public void aSigningKeyRemovedAfterActivationStopsIssuing() throws TestCAException {
        givenKeystorePrivateKeyEntry(SIGNING_ALIAS, SIGNER_KEY);
        givenAnActivatedIssuer();
        givenATokenCouldBeIssued();
        givenKeystoreWithoutEntry(SIGNING_ALIAS);
        givenTheBoundKeystoreAnnouncedAChange();

        whenATokenIsIssuedFor(TEST_IDENTITY);

        thenNoTokenIsIssued();
        thenIssuingFailedWith(KuraErrorCode.CONFIGURATION_ERROR);
    }

    @Test
    public void aTrustedCertificateRemovedAfterActivationStopsVerification() throws TestCAException {
        givenKeystoreTrustedCertificate(TRUST_ALIAS, SIGNER_KEY);
        givenAnActivatedVerifier();
        givenATokenCouldBeVerified();
        givenKeystoreWithoutEntry(TRUST_ALIAS);
        givenTheBoundKeystoreAnnouncedAChange();

        whenATokenIsVerified(aTokenSignedWithTheSignerKey());

        thenNoVerificationProofIsProduced();
        thenVerificationFailedWith(KuraErrorCode.CONFIGURATION_ERROR);
    }

    private void givenAnActivatedIssuer() {
        givenTheIssuerIsBoundToTheKeystore();
        givenTheIssuerIsActivatedWith(IssuingConfig.defaults().withSigningKeyAlias(SIGNING_ALIAS));
    }

    private void givenAnActivatedVerifier() {
        givenTheVerifierIsBoundToTheKeystore();
        givenTheVerifierIsActivatedWith(VerificationConfig.defaults());
    }

    private void givenATokenCouldBeIssued() {
        whenATokenIsIssuedFor(TEST_IDENTITY);

        thenATokenIsIssued();
    }

    private void givenATokenCouldBeVerified() throws TestCAException {
        whenATokenIsVerified(aTokenSignedWithTheSignerKey());

        thenTheTokenIsVerifiedFor(TEST_IDENTITY);
    }

    private static String aTokenSignedWithTheSignerKey() throws TestCAException {
        return TestToken.builder() //
                .issuer(DEFAULT_ISSUER) //
                .subject(TEST_IDENTITY) //
                .signedWith(TestKeys.rsaPrivateKey(SIGNER_KEY));
    }

}
