/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt.lifecycle;

import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.core.testutil.pki.TestCA.TestCAException;
import org.eclipse.kura.core.token.jwt.common.AbstractJwtScenario;
import org.eclipse.kura.core.token.jwt.common.IssuingConfig;
import org.eclipse.kura.core.token.jwt.common.TestKeys;
import org.eclipse.kura.core.token.jwt.common.TestToken;
import org.eclipse.kura.core.token.jwt.common.VerificationConfig;
import org.junit.Test;

public class KeystoreUnbindingTest extends AbstractJwtScenario {

    private static final String TRUST_ALIAS = "trusted-signer";
    private static final int SIGNER_KEY = 0;

    @Test
    public void unbindingTheBoundKeystoreDisablesIssuing() throws TestCAException {
        givenActivatedServicesWithKeyMaterial();
        givenTheBoundKeystoreWasUnbound();

        whenATokenIsIssuedFor(TEST_IDENTITY);

        thenNoTokenIsIssued();
        thenIssuingFailedWith(KuraErrorCode.CONFIGURATION_ERROR);
    }

    @Test
    public void unbindingTheBoundKeystoreDisablesVerification() throws TestCAException {
        givenActivatedServicesWithKeyMaterial();
        givenTheBoundKeystoreWasUnbound();

        whenATokenIsVerified(aTokenSignedWithTheSignerKey());

        thenNoVerificationProofIsProduced();
        thenVerificationFailedWith(KuraErrorCode.CONFIGURATION_ERROR);
    }

    @Test
    public void unbindingADifferentKeystoreInstanceLeavesIssuingWorking() throws TestCAException {
        givenActivatedServicesWithKeyMaterial();
        givenADifferentKeystoreInstanceWasUnbound();

        whenATokenIsIssuedFor(TEST_IDENTITY);

        thenATokenIsIssued();
    }

    @Test
    public void unbindingADifferentKeystoreInstanceLeavesVerificationWorking() throws TestCAException {
        givenActivatedServicesWithKeyMaterial();
        givenADifferentKeystoreInstanceWasUnbound();

        whenATokenIsVerified(aTokenSignedWithTheSignerKey());

        thenTheTokenIsVerifiedFor(TEST_IDENTITY);
    }

    private void givenActivatedServicesWithKeyMaterial() throws TestCAException {
        givenKeystorePrivateKeyEntry(SIGNING_ALIAS, SIGNER_KEY);
        givenKeystoreTrustedCertificate(TRUST_ALIAS, SIGNER_KEY);
        givenTheIssuerIsBoundToTheKeystore();
        givenTheIssuerIsActivatedWith(IssuingConfig.defaults().withSigningKeyAlias(SIGNING_ALIAS));
        givenTheVerifierIsBoundToTheKeystore();
        givenTheVerifierIsActivatedWith(VerificationConfig.defaults());
    }

    private static String aTokenSignedWithTheSignerKey() throws TestCAException {
        return TestToken.builder() //
                .issuer(DEFAULT_ISSUER) //
                .subject(TEST_IDENTITY) //
                .signedWith(TestKeys.rsaPrivateKey(SIGNER_KEY));
    }

}
