/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt.lifecycle;

import org.eclipse.kura.core.testutil.pki.TestCA.TestCAException;
import org.eclipse.kura.core.token.jwt.common.AbstractJwtScenario;
import org.eclipse.kura.core.token.jwt.common.IssuingConfig;
import org.eclipse.kura.core.token.jwt.common.TestKeys;
import org.eclipse.kura.core.token.jwt.common.TestToken;
import org.eclipse.kura.core.token.jwt.common.VerificationConfig;
import org.junit.Test;

import com.auth0.jwt.exceptions.SignatureVerificationException;

public class ReconfigurationTest extends AbstractJwtScenario {

    private static final String FIRST_ALIAS = "first-signing-key";
    private static final String SECOND_ALIAS = "second-signing-key";

    private static final int FIRST_KEY = 0;
    private static final int SECOND_KEY = 1;

    @Test
    public void aNewSigningKeyAliasTakesEffectOnTheNextIssuedToken() throws TestCAException {
        givenAnIssuerSigningWith(FIRST_ALIAS);
        givenTheIssuerWasReconfiguredWith(IssuingConfig.defaults().withSigningKeyAlias(SECOND_ALIAS));

        whenATokenIsIssuedFor(TEST_IDENTITY);

        thenATokenIsIssued();
        thenIssuedTokenHeaderHas("kid", SECOND_ALIAS);
    }

    @Test
    public void aNewIssuerTakesEffectOnTheNextIssuedToken() throws TestCAException {
        givenAnIssuerSigningWith(FIRST_ALIAS);
        givenTheIssuerWasReconfiguredWith(IssuingConfig.defaults() //
                .withSigningKeyAlias(FIRST_ALIAS) //
                .withIssuer("kura.gateway"));

        whenATokenIsIssuedFor(TEST_IDENTITY);

        thenIssuedTokenHasStringClaim("iss", "kura.gateway");
    }

    @Test
    public void aSigningKeyAliasThatCannotBeResolvedDisablesIssuing() throws TestCAException {
        givenAnIssuerSigningWith(FIRST_ALIAS);
        givenTheIssuerWasReconfiguredWith(IssuingConfig.defaults().withSigningKeyAlias("no-such-alias"));

        whenATokenIsIssuedFor(TEST_IDENTITY);

        thenNoTokenIsIssued();
    }

    @Test
    public void narrowingTheVerificationAliasesTakesEffectImmediately() throws TestCAException {
        givenAVerifierAcceptingEveryAlias();
        givenTheVerifierWasReconfiguredWith(VerificationConfig.defaults() //
                .withVerificationKeyAliases(FIRST_ALIAS));

        whenATokenSignedWithIsVerified(SECOND_KEY);

        thenVerificationFailedBecauseOf(SignatureVerificationException.class);
        thenNoVerificationProofIsProduced();
    }

    @Test
    public void wideningTheVerificationAliasesTakesEffectImmediately() throws TestCAException {
        givenAVerifierRestrictedTo(FIRST_ALIAS);
        givenTheVerifierWasReconfiguredWith(VerificationConfig.defaults());

        whenATokenSignedWithIsVerified(SECOND_KEY);

        thenTheTokenIsVerifiedFor(TEST_IDENTITY);
    }

    @Test
    public void aNewTrustedIssuerTakesEffectImmediately() throws TestCAException {
        givenAVerifierAcceptingEveryAlias();
        givenTheVerifierWasReconfiguredWith(VerificationConfig.defaults().withTrustedIssuers("kura.gateway"));

        whenATokenSignedWithIsVerified(FIRST_KEY);

        thenNoVerificationProofIsProduced();
    }

    private void givenAnIssuerSigningWith(final String alias) throws TestCAException {
        givenKeystorePrivateKeyEntry(FIRST_ALIAS, FIRST_KEY);
        givenKeystorePrivateKeyEntry(SECOND_ALIAS, SECOND_KEY);
        givenTheIssuerIsBoundToTheKeystore();
        givenTheIssuerIsActivatedWith(IssuingConfig.defaults().withSigningKeyAlias(alias));
    }

    private void givenAVerifierAcceptingEveryAlias() throws TestCAException {
        givenBothTrustedCertificates();
        givenTheVerifierIsBoundToTheKeystore();
        givenTheVerifierIsActivatedWith(VerificationConfig.defaults());
    }

    private void givenAVerifierRestrictedTo(final String alias) throws TestCAException {
        givenBothTrustedCertificates();
        givenTheVerifierIsBoundToTheKeystore();
        givenTheVerifierIsActivatedWith(VerificationConfig.defaults().withVerificationKeyAliases(alias));
    }

    private void givenBothTrustedCertificates() throws TestCAException {
        givenKeystoreTrustedCertificate(FIRST_ALIAS, FIRST_KEY);
        givenKeystoreTrustedCertificate(SECOND_ALIAS, SECOND_KEY);
    }

    private void whenATokenSignedWithIsVerified(final int keyIndex) throws TestCAException {
        whenATokenIsVerified(TestToken.builder() //
                .issuer(DEFAULT_ISSUER) //
                .subject(TEST_IDENTITY) //
                .signedWith(TestKeys.rsaPrivateKey(keyIndex)));
    }

}
