/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 * Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.internal.rest.deployment.agent;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import static org.junit.Assume.assumeTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.io.IOException;
import java.io.InputStream;
import java.lang.management.ManagementFactory;

import javax.ws.rs.WebApplicationException;

import org.glassfish.jersey.media.multipart.FormDataContentDisposition;
import org.junit.Test;

public class UploadDeploymentPackageTest {

    private static final int ATTEMPTS = 50;

    private final DeploymentRestService deploymentRestService = new DeploymentRestService();
    private int failedUploads;
    private int internalServerErrors;
    private long openDescriptorsBefore;
    private long openDescriptorsAfter;

    /*
     * Scenarios
     */

    @Test
    public void releasesTheUploadedFileWhenTheUploadStreamFails() {
        givenUnixFileDescriptorCount();

        whenUploadsFailRepeatedly();

        thenEveryUploadFailedWithInternalServerError();
        thenNoFileDescriptorIsLeaked();
    }

    /*
     * Steps
     */

    private void givenUnixFileDescriptorCount() {
        assumeTrue(ManagementFactory.getOperatingSystemMXBean() instanceof com.sun.management.UnixOperatingSystemMXBean);
    }

    private void whenUploadsFailRepeatedly() {
        this.openDescriptorsBefore = openFileDescriptors();
        for (int i = 0; i < ATTEMPTS; i++) {
            try {
                this.deploymentRestService.installUploadedDeploymentPackage(failingStream(), fileDetails());
            } catch (WebApplicationException e) {
                this.failedUploads++;
                if (e.getResponse().getStatus() == 500) {
                    this.internalServerErrors++;
                }
            }
        }
        this.openDescriptorsAfter = openFileDescriptors();
    }

    private void thenEveryUploadFailedWithInternalServerError() {
        assertEquals(ATTEMPTS, this.failedUploads);
        assertEquals(ATTEMPTS, this.internalServerErrors);
    }

    private void thenNoFileDescriptorIsLeaked() {
        assertTrue("open file descriptors grew from " + this.openDescriptorsBefore + " to " + this.openDescriptorsAfter,
                this.openDescriptorsAfter - this.openDescriptorsBefore < ATTEMPTS / 2);
    }

    /*
     * Utilities
     */

    private static InputStream failingStream() {
        return new InputStream() {

            @Override
            public int read() throws IOException {
                throw new IOException("connection reset during upload");
            }

            @Override
            public int read(byte[] b, int off, int len) throws IOException {
                throw new IOException("connection reset during upload");
            }
        };
    }

    private static FormDataContentDisposition fileDetails() {
        final FormDataContentDisposition details = mock(FormDataContentDisposition.class);
        when(details.getFileName()).thenReturn("package.dp");
        return details;
    }

    private static long openFileDescriptors() {
        return ((com.sun.management.UnixOperatingSystemMXBean) ManagementFactory.getOperatingSystemMXBean())
                .getOpenFileDescriptorCount();
    }
}
