/*******************************************************************************
 * Copyright (c) 2011, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.certificate;

import java.util.List;

import org.eclipse.kura.KuraException;
import org.eclipse.kura.message.KuraApplicationTopic;
import org.eclipse.kura.message.KuraPayload;
import org.osgi.annotation.versioning.ProviderType;

/**
 * The CertificatesService is used to manage the storage, listing and retrieval of public certificates
 * from a key store.
 *
 * @noimplement This interface is not intended to be implemented by clients.
 */
@ProviderType
public interface CertificatesService {

    /**
     * verifySignature is a method that takes the topic used
     * to send the message and the signed message to verify the correctness of the signature.
     *
     * @param kuraAppTopic
     *            The application topic part used to send the message
     * @param kuraPayload
     *            The kuraPayload message received and that needs to be verified
     * @return A boolean value that is true if the signature received corresponds with the signature
     *         calculated from the message content. False otherwise.
     * @since 2.0
     *
     */
    public boolean verifySignature(KuraApplicationTopic kuraAppTopic, KuraPayload kuraPayload);

    /**
     * Return the list of the installed {@KuraCertificate}
     * 
     * @return a list of {@KuraCertificate}
     * @throws KuraException
     * 
     * @since 2.2
     */
    public List<KuraCertificateEntry> getCertificates() throws KuraException;

    /**
     * Return the {@KuraCertificate} identified by its id
     * 
     * @param id
     *            the id of the certificate
     * @return the {@KuraCertificate}
     * @throws KuraException
     * 
     * @since 2.2
     */
    public KuraCertificateEntry getCertificateEntry(String id) throws KuraException;

    /**
     * Update the {@KuraCertificate} in a keystore
     * 
     * @param id
     *            the id of the certificate
     * @param certificate
     *            the new certificate
     * @throws KuraException
     * 
     * @since 2.2
     */
    public void updateCertificate(KuraCertificateEntry certificate) throws KuraException;

    /**
     * Add a {@KuraCertificate} in a keystore
     * 
     * @param certificate
     *            the new certificate
     * @throws KuraException
     * 
     * @since 2.2
     */
    public void addCertificate(KuraCertificateEntry certificate) throws KuraException;

    /**
     * Delete the certificate identified by its id
     * 
     * @param id
     *            the id of the certificate
     * @throws KuraException
     * 
     * @since 2.2
     */
    public void deleteCertificate(String id) throws KuraException;

}
