/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.linux.clock.test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.fail;
import static org.mockito.Mockito.mock;

import java.util.HashMap;
import java.util.Hashtable;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.TimeUnit;

import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.KuraException;
import org.eclipse.kura.clock.ClockService;
import org.eclipse.kura.clock.ClockSyncState;
import org.eclipse.kura.clock.ClockSyncStatus;
import org.eclipse.kura.core.testutil.service.ServiceUtil;
import org.eclipse.kura.crypto.CryptoService;
import org.eclipse.kura.executor.PrivilegedExecutorService;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;
import org.osgi.framework.BundleContext;
import org.osgi.framework.FrameworkUtil;
import org.osgi.framework.ServiceRegistration;
import org.osgi.service.cm.Configuration;
import org.osgi.service.cm.ConfigurationAdmin;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class ClockServiceSyncStatusIntegrationTest {

    private static final String CLOCK_SERVICE_PID = "org.eclipse.kura.clock.ClockService";
    private static final long TRACK_TIMEOUT_SECONDS = 30;
    private static final long POLL_DEADLINE_MILLIS = 30000;
    private static final long POLL_INTERVAL_MILLIS = 200;

    private static ServiceRegistration<PrivilegedExecutorService> executorRegistration;
    private static ServiceRegistration<CryptoService> cryptoRegistration;

    private ConfigurationAdmin configurationAdmin;
    private ClockService clockService;
    private ClockSyncStatus status;
    private KuraException thrownException;

    @BeforeClass
    public static void registerMockDependencies() {
        BundleContext context = FrameworkUtil.getBundle(ClockServiceSyncStatusIntegrationTest.class)
                .getBundleContext();

        PrivilegedExecutorService executorMock = mock(PrivilegedExecutorService.class);
        CryptoService cryptoMock = mock(CryptoService.class);

        executorRegistration = context.registerService(PrivilegedExecutorService.class, executorMock, null);
        cryptoRegistration = context.registerService(CryptoService.class, cryptoMock, null);
    }

    @AfterClass
    public static void unregisterMockDependencies() {
        if (executorRegistration != null) {
            executorRegistration.unregister();
        }
        if (cryptoRegistration != null) {
            cryptoRegistration.unregister();
        }
    }

    @Test
    public void scenarioADisabledServiceThrowsServiceUnavailable() throws Exception {
        givenConfigurationAdminIsAvailable();
        givenClockServiceConfiguredAndTracked(disabledProperties());

        whenGetSyncStatusEventuallyThrowsServiceUnavailable();

        thenExceptionHasErrorCode(KuraErrorCode.SERVICE_UNAVAILABLE);
    }

    @Test
    public void scenarioBJavaNtpProviderWithNoNetworkReportsUnknownStatus() throws Exception {
        givenConfigurationAdminIsAvailable();
        givenClockServiceConfiguredAndTracked(javaNtpNeverSyncProperties());

        whenGetSyncStatusEventuallyBecomesAvailable();

        thenStatusStateIs(ClockSyncState.UNKNOWN);
        thenStatusLastSyncIsNull();
        thenStatusSyncProviderIs("java-ntp");
    }

    private void givenConfigurationAdminIsAvailable() throws Exception {
        this.configurationAdmin = ServiceUtil.trackService(ConfigurationAdmin.class, Optional.empty())
                .get(TRACK_TIMEOUT_SECONDS, TimeUnit.SECONDS);
    }

    private void givenClockServiceConfiguredAndTracked(Map<String, Object> properties) throws Exception {
        CompletableFuture<ClockService> tracked = ServiceUtil.trackService(ClockService.class, Optional.empty());

        Configuration configuration = this.configurationAdmin.getConfiguration(CLOCK_SERVICE_PID, null);
        configuration.update(new Hashtable<>(properties));

        this.clockService = tracked.get(TRACK_TIMEOUT_SECONDS, TimeUnit.SECONDS);
    }

    private void whenGetSyncStatusEventuallyThrowsServiceUnavailable() throws Exception {
        long deadline = System.currentTimeMillis() + POLL_DEADLINE_MILLIS;

        while (System.currentTimeMillis() < deadline) {
            try {
                this.status = this.clockService.getSyncStatus();
            } catch (KuraException e) {
                this.thrownException = e;
                return;
            }
            Thread.sleep(POLL_INTERVAL_MILLIS);
        }

        fail("clock service never became unavailable within the poll deadline");
    }

    private void whenGetSyncStatusEventuallyBecomesAvailable() throws Exception {
        long deadline = System.currentTimeMillis() + POLL_DEADLINE_MILLIS;
        KuraException lastFailure = null;

        while (System.currentTimeMillis() < deadline) {
            try {
                this.status = this.clockService.getSyncStatus();
                return;
            } catch (KuraException e) {
                lastFailure = e;
            }
            Thread.sleep(POLL_INTERVAL_MILLIS);
        }

        fail("clock service never became available within the poll deadline: "
                + (lastFailure != null ? lastFailure.getMessage() : "unknown"));
    }

    private void thenExceptionHasErrorCode(KuraErrorCode expected) {
        assertNotNull("expected a KuraException to be thrown", this.thrownException);
        assertEquals(expected, this.thrownException.getCode());
    }

    private void thenStatusStateIs(ClockSyncState expected) {
        assertNotNull("expected a status to be returned", this.status);
        assertEquals(expected, this.status.getState());
    }

    private void thenStatusLastSyncIsNull() {
        assertNull(this.status.getLastSync());
    }

    private void thenStatusSyncProviderIs(String expected) {
        assertEquals(expected, this.status.getSyncProvider());
    }

    private static Map<String, Object> disabledProperties() {
        Map<String, Object> properties = new HashMap<>();
        properties.put("enabled", false);
        return properties;
    }

    private static Map<String, Object> javaNtpNeverSyncProperties() {
        Map<String, Object> properties = new HashMap<>();
        properties.put("enabled", true);
        properties.put("clock.provider", "java-ntp");
        properties.put("clock.ntp.refresh-interval", -1);
        return properties;
    }
}
