/*******************************************************************************
 * Copyright (c) 2017, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.certificates;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.io.IOException;
import java.security.GeneralSecurityException;
import java.security.KeyStore.TrustedCertificateEntry;
import java.security.cert.X509Certificate;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.eclipse.kura.KuraException;
import org.eclipse.kura.certificate.KuraCertificateEntry;
import org.eclipse.kura.core.testutil.TestUtil;
import org.eclipse.kura.crypto.CryptoService;
import org.eclipse.kura.security.keystore.KeystoreService;
import org.junit.BeforeClass;
import org.junit.Test;

public class CertificatesManagerTest {

    private static CertificatesManager certificatesManager;

    @BeforeClass
    public static void setup() {
        certificatesManager = new CertificatesManager();
    }

    @Test
    public void returnCertificateTest()
            throws NoSuchFieldException, KuraException, GeneralSecurityException, IOException {
        X509Certificate certMock = mock(X509Certificate.class);
        KeystoreService ksMock = mock(KeystoreService.class);
        when(ksMock.getEntry("certTest")).thenReturn(new TrustedCertificateEntry(certMock));
        Map<String, KeystoreService> keystoreServices = new HashMap<>();
        keystoreServices.put("keystoreTest", ksMock);
        TestUtil.setFieldValue(certificatesManager, "keystoreServices", keystoreServices);

        String id = "keystoreTest:certTest";
        KuraCertificateEntry kuraCertificate = certificatesManager.getCertificateEntry(id);
        assertEquals("keystoreTest", kuraCertificate.getKeystoreId());
        assertEquals("certTest", kuraCertificate.getAlias());
        assertNotNull(kuraCertificate.getCertificateEntry());
    }

    @Test
    public void verifySignatureTest() {
        // Not implemented, always returns true
        CertificatesManager manager = new CertificatesManager();
        assertTrue(manager.verifySignature(null, null));
    }

    @Test
    public void getCertificatesTest()
            throws KuraException, NoSuchFieldException, GeneralSecurityException, IOException {
        X509Certificate certMock = mock(X509Certificate.class);
        KeystoreService ksMock = mock(KeystoreService.class);
        Map<String, java.security.KeyStore.Entry> entries = new HashMap<>();
        entries.put("certTest1", new TrustedCertificateEntry(certMock));
        entries.put("certTest2", new TrustedCertificateEntry(certMock));
        when(ksMock.getEntries()).thenReturn(entries);
        Map<String, KeystoreService> keystoreServices = new HashMap<>();
        keystoreServices.put("keystoreTest", ksMock);
        TestUtil.setFieldValue(certificatesManager, "keystoreServices", keystoreServices);

        List<KuraCertificateEntry> kuraCertificates = certificatesManager.getCertificates();
        assertEquals(2, kuraCertificates.size());
        assertEquals("keystoreTest", kuraCertificates.get(0).getKeystoreId());
        assertEquals("certTest2", kuraCertificates.get(0).getAlias());
    }

    @Test
    public void getCertificateTest() throws KuraException, NoSuchFieldException, GeneralSecurityException, IOException {
        X509Certificate certMock = mock(X509Certificate.class);
        KeystoreService ksMock = mock(KeystoreService.class);
        when(ksMock.getEntry("certTest")).thenReturn(new TrustedCertificateEntry(certMock));
        Map<String, KeystoreService> keystoreServices = new HashMap<>();
        keystoreServices.put("keystoreTest", ksMock);
        TestUtil.setFieldValue(certificatesManager, "keystoreServices", keystoreServices);

        String id = "keystoreTest:certTest";
        KuraCertificateEntry kuraCertificate = certificatesManager.getCertificateEntry(id);
        assertEquals("keystoreTest", kuraCertificate.getKeystoreId());
        assertEquals("certTest", kuraCertificate.getAlias());
    }

    @Test
    public void addCertificateTest() throws KuraException, NoSuchFieldException, GeneralSecurityException, IOException {
        X509Certificate certMock = mock(X509Certificate.class);
        KeystoreService ksMock = mock(KeystoreService.class);
        when(ksMock.getEntry("certTest")).thenReturn(new TrustedCertificateEntry(certMock));
        Map<String, KeystoreService> keystoreServices = new HashMap<>();
        keystoreServices.put("keystoreTest", ksMock);
        TestUtil.setFieldValue(certificatesManager, "keystoreServices", keystoreServices);

        String id = "keystoreTest:certTest";
        KuraCertificateEntry kuraCertificate = new KuraCertificateEntry("keystoreTest", "certTest", certMock);
        certificatesManager.addCertificate(kuraCertificate);
        kuraCertificate = certificatesManager.getCertificateEntry(id);
        assertEquals("keystoreTest", kuraCertificate.getKeystoreId());
        assertEquals("certTest", kuraCertificate.getAlias());
        verify(ksMock).setEntry(eq("certTest"), any());
    }

    @Test
    public void updateCertificateTest()
            throws KuraException, NoSuchFieldException, GeneralSecurityException, IOException {
        X509Certificate certMock = mock(X509Certificate.class);
        KeystoreService ksMock = mock(KeystoreService.class);
        when(ksMock.getEntry("certTest")).thenReturn(new TrustedCertificateEntry(certMock));
        Map<String, KeystoreService> keystoreServices = new HashMap<>();
        keystoreServices.put("keystoreTest", ksMock);
        TestUtil.setFieldValue(certificatesManager, "keystoreServices", keystoreServices);

        String id = "keystoreTest:certTest";
        KuraCertificateEntry kuraCertificate = new KuraCertificateEntry("keystoreTest", "certTest", certMock);
        certificatesManager.updateCertificate(kuraCertificate);
        kuraCertificate = certificatesManager.getCertificateEntry(id);
        assertEquals("keystoreTest", kuraCertificate.getKeystoreId());
        assertEquals("certTest", kuraCertificate.getAlias());
        verify(ksMock).setEntry(eq("certTest"), any());
    }

    @Test
    public void deleteCertificateTest()
            throws KuraException, NoSuchFieldException, GeneralSecurityException, IOException {
        KeystoreService ksMock = mock(KeystoreService.class);
        Map<String, KeystoreService> keystoreServices = new HashMap<>();
        keystoreServices.put("keystoreTest", ksMock);
        TestUtil.setFieldValue(certificatesManager, "keystoreServices", keystoreServices);

        String id = "keystoreTest:certTest";
        certificatesManager.deleteCertificate(id);
        verify(ksMock).deleteEntry("certTest");
    }

    String getDefaultKeyStore(CertificatesManager manager) throws NoSuchFieldException {
        return (String) TestUtil.getFieldValue(manager, "DEFAULT_KEYSTORE");
    }

    CryptoService createMockCryptoService(String keyStorePath, String keyStorePassword) throws NoSuchFieldException {
        CryptoService mockService = mock(CryptoService.class);
        when(mockService.getKeyStorePassword(keyStorePath)).thenReturn(keyStorePassword.toCharArray());

        return mockService;
    }

}
