/*******************************************************************************
 * Copyright (c) 2017, 2026 Eurotech and/or its affiliates and others
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.cloud.app.command;

import static java.nio.charset.StandardCharsets.UTF_8;
import static org.eclipse.kura.cloudconnection.request.RequestHandlerMessageConstants.ARGS_KEY;
import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.KuraException;
import org.eclipse.kura.cloud.CloudClient;
import org.eclipse.kura.cloud.CloudService;
import org.eclipse.kura.cloudconnection.message.KuraMessage;
import org.eclipse.kura.configuration.Password;
import org.eclipse.kura.core.linux.executor.LinuxExitStatus;
import org.eclipse.kura.core.testutil.TestUtil;
import org.eclipse.kura.crypto.CryptoService;
import org.eclipse.kura.executor.Command;
import org.eclipse.kura.executor.CommandStatus;
import org.eclipse.kura.executor.PrivilegedExecutorService;
import org.eclipse.kura.executor.UnprivilegedExecutorService;
import org.eclipse.kura.message.KuraPayload;
import org.eclipse.kura.message.KuraRequestPayload;
import org.eclipse.kura.message.KuraResponsePayload;
import org.junit.Test;
import org.mockito.ArgumentCaptor;
import org.osgi.service.component.ComponentException;

public class CommandCloudAppTest {

    public static final String METRIC_RESPONSE_CODE = "response.code";

    private UnprivilegedExecutorService unprivilegedExecutorServiceMock;
    private PrivilegedExecutorService privilegedExecutorServiceMock;

    @Test
    public void testUpdatedDecryptException() throws KuraException, NoSuchFieldException {
        String passKey = "command.password.value";
        char[] password = "encpass".toCharArray();

        CommandCloudApp cca = new CommandCloudApp();

        Map<String, Object> properties = new HashMap<>();
        properties.put(passKey, new String(password));
        properties.put("key", "value");
        properties.put("command.enable", false);

        cca.updated(properties);

        @SuppressWarnings("unchecked")
        Map<String, Object> props = (Map<String, Object>) TestUtil.getFieldValue(cca, "properties");

        assertEquals(3, props.size());
        assertEquals("value", props.get("key"));
        assertEquals(false, props.get("command.enable"));
        assertTrue(props.get(passKey) instanceof Password);
        assertArrayEquals(password, ((Password) props.get(passKey)).getPassword());
    }

    @Test
    public void testUpdatedSuperActivateExec() throws KuraException, NoSuchFieldException {
        String passKey = "command.password.value";
        char[] password = "encpass".toCharArray();
        char[] decpass = "decpass".toCharArray();

        CryptoService csMock = mock(CryptoService.class);
        when(csMock.decryptAes(password)).thenReturn(decpass);

        Map<String, Object> properties = new HashMap<>();
        properties.put(passKey, new String(password));
        properties.put("key", "value");
        properties.put("command.enable", true);

        CloudService clsMock = mock(CloudService.class);
        when(clsMock.newCloudClient(anyString())).thenThrow(new KuraException(KuraErrorCode.CLOSED_DEVICE));

        CommandCloudApp cca = new CommandCloudApp();
        cca.setCryptoService(csMock);

        try {
            cca.updated(properties);
        } catch (ComponentException e) {
        }

        TestUtil.setFieldValue(cca, "currentStatus", true);

        @SuppressWarnings("unchecked")
        Map<String, Object> props = (Map<String, Object>) TestUtil.getFieldValue(cca, "properties");

        assertEquals(3, props.size());
        assertEquals("value", props.get("key"));
        assertEquals(true, props.get("command.enable"));
        assertTrue(props.get(passKey) instanceof Password);
        assertArrayEquals(decpass, ((Password) props.get(passKey)).getPassword());
        assertTrue((boolean) TestUtil.getFieldValue(cca, "currentStatus"));
    }

    @Test
    public void testUpdatedSuperActivate() throws KuraException, NoSuchFieldException {
        String passKey = "command.password.value";
        char[] password = "encpass".toCharArray();
        char[] decpass = "decpass".toCharArray();

        CryptoService csMock = mock(CryptoService.class);
        when(csMock.decryptAes(password)).thenReturn(decpass);

        Map<String, Object> properties = new HashMap<>();
        properties.put(passKey, new String(password));
        properties.put("key", "value");
        properties.put("command.enable", true);

        CloudClient ccMock = mock(CloudClient.class);

        CloudService clsMock = mock(CloudService.class);
        when(clsMock.newCloudClient(anyString())).thenReturn(ccMock);

        CommandCloudApp cca = new CommandCloudApp();
        TestUtil.setFieldValue(cca, "currentStatus", true);
        cca.setCryptoService(csMock);

        try {
            cca.updated(properties);
        } catch (ComponentException e) {
        }

        @SuppressWarnings("unchecked")
        Map<String, Object> props = (Map<String, Object>) TestUtil.getFieldValue(cca, "properties");

        assertEquals(3, props.size());
        assertEquals("value", props.get("key"));
        assertEquals(true, props.get("command.enable"));
        assertTrue(props.get(passKey) instanceof Password);
        assertArrayEquals(decpass, ((Password) props.get(passKey)).getPassword());
        assertTrue((boolean) TestUtil.getFieldValue(cca, "currentStatus"));
    }

    @Test
    public void testUpdatedSuperDeactivate() throws KuraException, NoSuchFieldException {
        String passKey = "command.password.value";
        char[] password = "encpass".toCharArray();
        char[] decpass = "decpass".toCharArray();

        CryptoService csMock = mock(CryptoService.class);
        when(csMock.decryptAes(password)).thenReturn(decpass);

        Map<String, Object> properties = new HashMap<>();
        properties.put(passKey, new String(password));
        properties.put("key", "value");
        properties.put("command.enable", false);

        CommandCloudApp cca = new CommandCloudApp();
        cca.setCryptoService(csMock);
        TestUtil.setFieldValue(cca, "currentStatus", true);

        cca.updated(properties);

        @SuppressWarnings("unchecked")
        Map<String, Object> props = (Map<String, Object>) TestUtil.getFieldValue(cca, "properties");

        assertEquals(3, props.size());
        assertEquals("value", props.get("key"));
        assertEquals(false, props.get("command.enable"));
        assertTrue(props.get(passKey) instanceof Password);
        assertArrayEquals(decpass, ((Password) props.get(passKey)).getPassword());
    }

    @Test
    public void testGetDefaultWorkDirSystem() throws Throwable {
        Map<String, Object> properties = new HashMap<>();

        CommandCloudApp cca = new CommandCloudApp();
        TestUtil.setFieldValue(cca, "properties", properties);

        Object result = TestUtil.invokePrivate(cca, "getDefaultWorkDir", null);

        assertEquals(System.getProperty("java.io.tmpdir"), result);
    }

    @Test
    public void testGetDefaultWorkDirConfigured() throws Throwable {
        Map<String, Object> properties = new HashMap<>();
        String wd = "/wd";
        properties.put("command.working.directory", wd);

        CommandCloudApp cca = new CommandCloudApp();
        TestUtil.setFieldValue(cca, "properties", properties);

        Object result = TestUtil.invokePrivate(cca, "getDefaultWorkDir", null);

        assertEquals(wd, result);
    }

    @Test
    public void testGetDefaultTimeout() throws Throwable {
        Map<String, Object> properties = new HashMap<>();
        int timeout = 10;
        properties.put("command.timeout", timeout);

        CommandCloudApp cca = new CommandCloudApp();
        TestUtil.setFieldValue(cca, "properties", properties);

        Object result = TestUtil.invokePrivate(cca, "getDefaultTimeout", null);

        assertEquals(timeout, result);
    }

    @Test
    public void testGetTimeoutDefault() throws Throwable {
        Map<String, Object> properties = new HashMap<>();
        int timeout = 10;
        properties.put("command.timeout", timeout);

        CommandCloudApp cca = new CommandCloudApp();
        TestUtil.setFieldValue(cca, "properties", properties);

        KuraCommandRequestPayload payload = new KuraCommandRequestPayload("cmd");
        Object result = TestUtil.invokePrivate(cca, "getTimeout", payload);

        assertEquals(timeout, result);
    }

    @Test
    public void testGetTimeoutFromPayload() throws Throwable {
        Map<String, Object> properties = new HashMap<>();
        int timeout = 10;
        properties.put("command.timeout", timeout);

        CommandCloudApp cca = new CommandCloudApp();
        TestUtil.setFieldValue(cca, "properties", properties);

        KuraCommandRequestPayload payload = new KuraCommandRequestPayload("cmd");
        payload.setTimeout(15);
        Object result = TestUtil.invokePrivate(cca, "getTimeout", payload);

        assertEquals(15, result);
    }

    @Test
    public void testGetDefaultEnvironmentNull() throws Throwable {
        Map<String, Object> properties = new HashMap<>();

        CommandCloudApp cca = new CommandCloudApp();
        TestUtil.setFieldValue(cca, "properties", properties);

        Object result = TestUtil.invokePrivate(cca, "getDefaultEnvironment", null);

        assertNull(result);
    }

    @Test
    public void testGetDefaultEnvironment() throws Throwable {
        Map<String, Object> properties = new HashMap<>();
        String env = "e1 e2 e3";
        properties.put("command.environment", env);

        CommandCloudApp cca = new CommandCloudApp();
        TestUtil.setFieldValue(cca, "properties", properties);

        Object[] result = (Object[]) TestUtil.invokePrivate(cca, "getDefaultEnvironment", null);

        assertArrayEquals(new Object[] { "e1", "e2", "e3" }, result);
    }

    @Test
    public void testGetEnvironmentDefault() throws Throwable {
        Map<String, Object> properties = new HashMap<>();
        String env = "e1 e2 e3";
        properties.put("command.environment", env);

        CommandCloudApp cca = new CommandCloudApp();
        TestUtil.setFieldValue(cca, "properties", properties);

        KuraCommandRequestPayload payload = new KuraCommandRequestPayload("cmd");
        Object[] result = (Object[]) TestUtil.invokePrivate(cca, "getEnvironment", payload);

        assertArrayEquals(new Object[] { "e1", "e2", "e3" }, result);
    }

    @Test
    public void testGetEnvironmentFromPayload() throws Throwable {
        Map<String, Object> properties = new HashMap<>();
        String env = "e1 e2 e3";
        properties.put("command.environment", env);

        CommandCloudApp cca = new CommandCloudApp();
        TestUtil.setFieldValue(cca, "properties", properties);

        KuraCommandRequestPayload payload = new KuraCommandRequestPayload("cmd");
        String[] environmentPairs = new String[] { "env1", "env2" };
        payload.setEnvironmentPairs(environmentPairs);
        Object[] result = (Object[]) TestUtil.invokePrivate(cca, "getEnvironment", payload);

        assertArrayEquals(environmentPairs, result);
    }

    @Test
    public void testVerifyPasswords() throws Throwable {
        CommandCloudApp cca = new CommandCloudApp();

        Password commandPassword = null;
        String receivedPassword = null;
        boolean result = (boolean) TestUtil.invokePrivate(cca, "verifyPasswords", commandPassword, receivedPassword);
        assertTrue(result);

        commandPassword = null;
        receivedPassword = "";
        result = (boolean) TestUtil.invokePrivate(cca, "verifyPasswords", commandPassword, receivedPassword);
        assertTrue(result);

        commandPassword = null;
        receivedPassword = "foo";
        result = (boolean) TestUtil.invokePrivate(cca, "verifyPasswords", commandPassword, receivedPassword);
        assertFalse(result);

        commandPassword = new Password("");
        receivedPassword = null;
        result = (boolean) TestUtil.invokePrivate(cca, "verifyPasswords", commandPassword, receivedPassword);
        assertTrue(result);

        commandPassword = new Password("");
        receivedPassword = "bar";
        result = (boolean) TestUtil.invokePrivate(cca, "verifyPasswords", commandPassword, receivedPassword);
        assertFalse(result);

        commandPassword = new Password("");
        receivedPassword = "";
        result = (boolean) TestUtil.invokePrivate(cca, "verifyPasswords", commandPassword, receivedPassword);
        assertTrue(result);

        commandPassword = new Password("foo");
        receivedPassword = "foo";
        result = (boolean) TestUtil.invokePrivate(cca, "verifyPasswords", commandPassword, receivedPassword);
        assertTrue(result);

        commandPassword = new Password("foo");
        receivedPassword = "bar";
        result = (boolean) TestUtil.invokePrivate(cca, "verifyPasswords", commandPassword, receivedPassword);
        assertFalse(result);
    }

    @Test
    public void testPrepareResponseNoTimeoutNoException() throws Throwable {
        String err = "err";
        String out = "out";
        ByteArrayOutputStream baos = new ByteArrayOutputStream(3);
        baos.write(out.getBytes(UTF_8));
        ByteArrayOutputStream baes = new ByteArrayOutputStream(3);
        baes.write(err.getBytes(UTF_8));
        int exitVal = 0;

        KuraCommandResponsePayload resp = new KuraCommandResponsePayload(KuraResponsePayload.RESPONSE_CODE_OK);
        CommandStatus status = new CommandStatus(new Command(new String[] {}), new LinuxExitStatus(0));
        status.setErrorStream(baes);
        status.setOutputStream(baos);
        status.setTimedout(false);

        CommandCloudApp cca = new CommandCloudApp();

        TestUtil.invokePrivate(cca, "prepareResponse", resp, status, baos, baes);

        assertEquals("Response expected not to be changed", KuraResponsePayload.RESPONSE_CODE_OK,
                resp.getResponseCode());
        assertEquals(err, resp.getStderr());
        assertEquals(out, resp.getStdout());
        assertFalse(resp.isTimedout());
        assertEquals(exitVal, resp.getExitCode().intValue());
    }

    @Test
    public void testPrepareResponseNoTimeoutException() throws Throwable {
        String err = "err";
        String out = "out";
        ByteArrayOutputStream baos = new ByteArrayOutputStream(3);
        baos.write(out.getBytes(UTF_8));
        ByteArrayOutputStream baes = new ByteArrayOutputStream(3);
        baes.write(err.getBytes(UTF_8));

        KuraCommandResponsePayload resp = new KuraCommandResponsePayload(KuraResponsePayload.RESPONSE_CODE_OK);
        CommandStatus status = new CommandStatus(new Command(new String[] {}), new LinuxExitStatus(1));
        status.setErrorStream(baes);
        status.setOutputStream(baos);
        status.setTimedout(false);

        CommandCloudApp cca = new CommandCloudApp();

        TestUtil.invokePrivate(cca, "prepareResponse", resp, status, baos, baes);

        assertEquals("Response expected to be changed", KuraResponsePayload.RESPONSE_CODE_ERROR,
                resp.getResponseCode());
        assertEquals(err, resp.getStderr());
        assertEquals(out, resp.getStdout());
        assertFalse(resp.isTimedout());
        assertEquals(err, resp.getExceptionMessage());
    }

    @Test
    public void testPrepareTimeoutResponse() throws Throwable {
        String err = "err";
        String out = "out";
        ByteArrayOutputStream baos = new ByteArrayOutputStream(3);
        baos.write(out.getBytes(UTF_8));
        ByteArrayOutputStream baes = new ByteArrayOutputStream(3);
        baes.write(err.getBytes(UTF_8));

        KuraCommandResponsePayload resp = new KuraCommandResponsePayload(KuraResponsePayload.RESPONSE_CODE_OK);
        CommandStatus status = new CommandStatus(new Command(new String[] {}), new LinuxExitStatus(0));
        status.setErrorStream(baes);
        status.setOutputStream(baos);
        status.setTimedout(true);

        CommandCloudApp cca = new CommandCloudApp();

        TestUtil.invokePrivate(cca, "prepareResponse", resp, status, baos, baes);

        assertEquals("Response expected not to be changed", KuraResponsePayload.RESPONSE_CODE_OK,
                resp.getResponseCode());
        assertEquals(err, resp.getStderr());
        assertEquals(out, resp.getStdout());
        assertTrue(resp.isTimedout());
    }

    @Test
    public void testPrepareCommandArray() throws Throwable {
        CommandCloudApp cca = new CommandCloudApp();

        String cmd = "cmd";
        KuraCommandRequestPayload payload = new KuraCommandRequestPayload(cmd);
        String[] arguments = new String[] { "arg1", "arg2" };
        payload.setArguments(arguments);
        String[] result = (String[]) TestUtil.invokePrivate(cca, "prepareCommandArray", payload, cmd);

        assertArrayEquals(new String[] { "cmd", "arg1", "arg2" }, result);
    }

    @Test(expected = KuraException.class)
    public void testDoExecNoResources() throws Throwable {
        CommandCloudApp cca = new CommandCloudApp();
        TestUtil.setFieldValue(cca, "currentStatus", true);

        List<String> resources = Collections.emptyList();
        Map<String, Object> reqResources = new HashMap<>();
        reqResources.put(ARGS_KEY.value(), resources);
        KuraRequestPayload reqPayload = null;
        KuraMessage message = new KuraMessage(reqPayload, reqResources);

        cca.doExec(null, message);
    }

    @Test(expected = KuraException.class)
    public void testDoExecTooManyResources() throws Throwable {
        CommandCloudApp cca = new CommandCloudApp();

        TestUtil.setFieldValue(cca, "currentStatus", true);

        List<String> resources = new ArrayList<>();
        resources.add("command");
        resources.add("test");
        Map<String, Object> reqResources = new HashMap<>();
        reqResources.put(ARGS_KEY.value(), resources);

        KuraRequestPayload reqPayload = null;

        KuraMessage message = new KuraMessage(reqPayload, reqResources);

        cca.doExec(null, message);
    }

    @Test(expected = KuraException.class)
    public void testDoExecWrongCommand() throws Throwable {
        CommandCloudApp cca = new CommandCloudApp();

        List<String> resources = new ArrayList<>();
        resources.add("cmd");
        Map<String, Object> reqResources = new HashMap<>();
        reqResources.put(ARGS_KEY.value(), resources);
        KuraRequestPayload reqPayload = null;
        KuraMessage message = new KuraMessage(reqPayload, reqResources);

        cca.doExec(null, message);
    }

    @Test(expected = KuraException.class)
    public void testDoExecServiceDisabled() throws Throwable {
        CommandCloudApp cca = new CommandCloudApp();
        Map<String, Object> properties = new HashMap<>();
        properties.put("command.enable", false);

        cca.updated(properties);

        List<String> resources = new ArrayList<>();
        resources.add("command");
        Map<String, Object> reqResources = new HashMap<>();
        reqResources.put(ARGS_KEY.value(), resources);
        KuraRequestPayload reqPayload = null;
        KuraMessage message = new KuraMessage(reqPayload, reqResources);

        cca.doExec(null, message);
    }

    @Test
    public void testDoExec() throws Throwable {
        KuraPayload kcrp = new KuraCommandResponsePayload(KuraResponsePayload.RESPONSE_CODE_OK);
        byte[] body = "testbody".getBytes();
        kcrp.setBody(body);

        CommandCloudApp cca = new CommandCloudApp() {

            @Override
            public KuraPayload execute(KuraPayload reqPayload) {
                return kcrp;
            }
        };

        TestUtil.setFieldValue(cca, "currentStatus", true);

        List<String> resources = new ArrayList<>();
        resources.add("command");
        Map<String, Object> reqResources = new HashMap<>();
        reqResources.put(ARGS_KEY.value(), resources);
        KuraRequestPayload reqPayload = null;

        KuraMessage message = new KuraMessage(reqPayload, reqResources);

        KuraMessage response = cca.doExec(null, message);

        assertNotNull(response);
        assertArrayEquals(body, response.getPayload().getBody());
    }

    @Test
    public void testExecuteDisabled() throws KuraException {
        CommandCloudApp cca = new CommandCloudApp();

        Map<String, Object> properties = new HashMap<>();
        properties.put("command.enable", false);

        cca.updated(properties);

        String cmd = "command";
        String pass = "pass";

        try {
            cca.execute(cmd, pass);
            fail("Exception expected - command execution not allowed");
        } catch (KuraException e) {
            assertEquals(KuraErrorCode.OPERATION_NOT_SUPPORTED, e.getCode());
        }
    }

    @Test
    public void testExecuteUnprivileged() throws KuraException, IOException {
        String wd = "/tmp";
        String cmd = wd + "/command";
        String pass = "pass";

        if (System.getProperty("os.name").contains("Windows")) {
            cmd += ".bat";
        } else {
            cmd += ".sh";
        }

        ByteArrayOutputStream baos = new ByteArrayOutputStream(3);
        baos.write("OK".getBytes(UTF_8));
        ByteArrayOutputStream baes = new ByteArrayOutputStream(3);
        baes.write("err".getBytes(UTF_8));
        CommandStatus status = new CommandStatus(new Command(new String[] {}), new LinuxExitStatus(0));
        status.setErrorStream(baes);
        status.setOutputStream(baos);
        status.setTimedout(false);

        UnprivilegedExecutorService unprivilegedExecutorServiceMock = mock(UnprivilegedExecutorService.class);
        when(unprivilegedExecutorServiceMock.execute(any())).thenReturn(status);

        PrivilegedExecutorService privilegedExecutorServiceMock = mock(PrivilegedExecutorService.class);

        CommandCloudApp cca = new CommandCloudApp();
        cca.setUnprivilegedExecutorService(unprivilegedExecutorServiceMock);
        cca.setPrivilegedExecutorService(privilegedExecutorServiceMock);

        Map<String, Object> properties = new HashMap<>();
        properties.put("command.password.value", "pass");
        properties.put("command.enable", true);
        properties.put("command.working.directory", wd);
        properties.put("command.timeout", 10);

        try {
            cca.updated(properties);
        } catch (Exception e) {
            // ignore the expected exception
        }

        File f = new File(cmd);
        f.createNewFile();
        f.setExecutable(true);
        f.deleteOnExit();

        FileWriter fw = new FileWriter(f);
        fw.write("sleep 1\necho OK");
        fw.close();

        String out = cca.execute(cmd, pass);

        assertTrue(out.trim().endsWith("OK"));
        verify(privilegedExecutorServiceMock, times(0)).execute(any());
        verify(unprivilegedExecutorServiceMock, times(1)).execute(any());
    }

    @Test
    public void testExecutePrivileged() throws KuraException, IOException {
        String wd = "/tmp";
        String cmd = wd + "/command";
        String pass = "pass";

        if (System.getProperty("os.name").contains("Windows")) {
            cmd += ".bat";
        } else {
            cmd += ".sh";
        }

        ByteArrayOutputStream baos = new ByteArrayOutputStream(3);
        baos.write("OK".getBytes(UTF_8));
        ByteArrayOutputStream baes = new ByteArrayOutputStream(3);
        baes.write("err".getBytes(UTF_8));
        CommandStatus status = new CommandStatus(new Command(new String[] {}), new LinuxExitStatus(0));
        status.setErrorStream(baes);
        status.setOutputStream(baos);
        status.setTimedout(false);

        UnprivilegedExecutorService unprivilegedExecutorServiceMock = mock(UnprivilegedExecutorService.class);
        when(unprivilegedExecutorServiceMock.execute(any())).thenReturn(status);

        PrivilegedExecutorService privilegedExecutorServiceMock = mock(PrivilegedExecutorService.class);
        when(privilegedExecutorServiceMock.execute(any())).thenReturn(status);

        CommandCloudApp cca = new CommandCloudApp();
        cca.setUnprivilegedExecutorService(unprivilegedExecutorServiceMock);
        cca.setPrivilegedExecutorService(privilegedExecutorServiceMock);

        Map<String, Object> properties = new HashMap<>();
        properties.put("command.password.value", "pass");
        properties.put("command.enable", true);
        properties.put("command.working.directory", wd);
        properties.put("command.timeout", 10);
        properties.put("privileged.command.service.enable", true);

        try {
            cca.updated(properties);
        } catch (Exception e) {
            // ignore the expected exception
        }

        File f = new File(cmd);
        f.createNewFile();
        f.setExecutable(true);
        f.deleteOnExit();

        FileWriter fw = new FileWriter(f);
        fw.write("sleep 1\necho OK");
        fw.close();

        String out = cca.execute(cmd, pass);

        assertTrue(out.trim().endsWith("OK"));
        verify(unprivilegedExecutorServiceMock, times(0)).execute(any());
        verify(privilegedExecutorServiceMock, times(1)).execute(any());
    }

    @Test
    public void testExecuteTimeout() throws KuraException, IOException {
        String wd = "/tmp";
        String cmd = wd + "/command_timeout";
        String pass = "pass";

        if (System.getProperty("os.name").contains("Windows")) {
            cmd += ".bat";
        } else {
            cmd += ".sh";
        }

        ByteArrayOutputStream baos = new ByteArrayOutputStream(3);
        baos.write("NOK".getBytes(UTF_8));
        ByteArrayOutputStream baes = new ByteArrayOutputStream(3);
        baes.write("err".getBytes(UTF_8));
        CommandStatus status = new CommandStatus(new Command(new String[] {}), new LinuxExitStatus(0));
        status.setErrorStream(baes);
        status.setOutputStream(baos);
        status.setTimedout(false);

        UnprivilegedExecutorService unprivilegedExecutorServiceMock = mock(UnprivilegedExecutorService.class);
        when(unprivilegedExecutorServiceMock.execute(any())).thenReturn(status);

        PrivilegedExecutorService privilegedExecutorServiceMock = mock(PrivilegedExecutorService.class);

        CommandCloudApp cca = new CommandCloudApp();
        cca.setUnprivilegedExecutorService(unprivilegedExecutorServiceMock);
        cca.setPrivilegedExecutorService(privilegedExecutorServiceMock);

        Map<String, Object> properties = new HashMap<>();
        properties.put("command.password.value", "pass");
        properties.put("command.enable", true);
        properties.put("command.working.directory", wd);
        properties.put("command.timeout", 1);

        try {
            cca.updated(properties);
        } catch (Exception e) {
            // ignore the expected exception
        }

        File f = new File(cmd);
        f.createNewFile();
        f.setExecutable(true);
        f.deleteOnExit();

        FileWriter fw = new FileWriter(f);
        fw.write("echo NOK 1>&2\nsleep 2\necho OK");
        fw.close();

        String out = cca.execute(cmd, pass);

        assertEquals("NOK", out.trim());
        verify(privilegedExecutorServiceMock, times(0)).execute(any());
    }

    @Test(expected = KuraException.class)
    public void testExecutePayloadNoCommand() throws KuraException, IOException {
        String wd = "/tmp";

        ByteArrayOutputStream baos = new ByteArrayOutputStream(3);
        baos.write("OK".getBytes(UTF_8));
        ByteArrayOutputStream baes = new ByteArrayOutputStream(3);
        baes.write("err".getBytes(UTF_8));
        CommandStatus status = new CommandStatus(new Command(new String[] {}), new LinuxExitStatus(0));
        status.setErrorStream(baes);
        status.setOutputStream(baos);
        status.setTimedout(false);

        UnprivilegedExecutorService unprivilegedExecutorServiceMock = mock(UnprivilegedExecutorService.class);
        when(unprivilegedExecutorServiceMock.execute(any())).thenReturn(status);

        PrivilegedExecutorService privilegedExecutorServiceMock = mock(PrivilegedExecutorService.class);

        CommandCloudApp cca = new CommandCloudApp();
        cca.setUnprivilegedExecutorService(unprivilegedExecutorServiceMock);
        cca.setPrivilegedExecutorService(privilegedExecutorServiceMock);

        Map<String, Object> properties = new HashMap<>();
        properties.put("command.password.value", "pass");
        properties.put("command.enable", true);
        properties.put("command.working.directory", wd);
        properties.put("command.timeout", 1);

        try {
            cca.updated(properties);
        } catch (Exception e) {
            // ignore the expected exception
        }

        KuraPayload payload = new KuraPayload();
        payload.addMetric("command.password", "pass");
        payload.addMetric("command.command", "");

        cca.execute(payload);
        verify(privilegedExecutorServiceMock, times(0)).execute(any());
    }

    @Test(expected = KuraException.class)
    public void testExecutePayloadPasswordError() throws KuraException, IOException {
        String wd = "/tmp";

        CommandCloudApp cca = new CommandCloudApp();

        Map<String, Object> properties = new HashMap<>();
        properties.put("command.password.value", "pass");
        properties.put("command.enable", true);
        properties.put("command.working.directory", wd);

        try {
            cca.updated(properties);
        } catch (Exception e) {
            // ignore the expected exception
        }

        KuraPayload payload = new KuraPayload();
        payload.addMetric("command.password", "pss");
        payload.addMetric("command.command", "sleep");

        cca.execute(payload);
    }

    @Test
    public void testExecutePayload() throws KuraException, IOException {
        String wd = "/tmp";
        String cmd = wd + "/command_payload";

        if (System.getProperty("os.name").contains("Windows")) {
            cmd += ".bat";
        } else {
            cmd += ".sh";
        }

        ByteArrayOutputStream baos = new ByteArrayOutputStream(3);
        baos.write("OK".getBytes(UTF_8));
        ByteArrayOutputStream baes = new ByteArrayOutputStream(3);
        baes.write("err".getBytes(UTF_8));
        CommandStatus status = new CommandStatus(new Command(new String[] {}), new LinuxExitStatus(0));
        status.setErrorStream(baes);
        status.setOutputStream(baos);
        status.setTimedout(false);

        UnprivilegedExecutorService unprivilegedExecutorServiceMock = mock(UnprivilegedExecutorService.class);
        when(unprivilegedExecutorServiceMock.execute(any())).thenReturn(status);

        PrivilegedExecutorService privilegedExecutorServiceMock = mock(PrivilegedExecutorService.class);

        CommandCloudApp cca = new CommandCloudApp();
        cca.setUnprivilegedExecutorService(unprivilegedExecutorServiceMock);
        cca.setPrivilegedExecutorService(privilegedExecutorServiceMock);

        Map<String, Object> properties = new HashMap<>();
        properties.put("command.password.value", "pass");
        properties.put("command.enable", true);
        properties.put("command.working.directory", wd);
        properties.put("command.timeout", 2);

        try {
            cca.updated(properties);
        } catch (Exception e) {
            // ignore the expected exception
        }

        File f = new File(cmd);
        f.createNewFile();
        f.setExecutable(true);
        f.deleteOnExit();

        FileWriter fw = new FileWriter(f);
        fw.write("sleep 1\necho OK");
        fw.close();

        KuraPayload payload = new KuraPayload();
        payload.addMetric("command.password", "pass");
        payload.addMetric("command.command", cmd);
        payload.setBody("zip".getBytes()); // try unzip for good measure...

        KuraPayload response = cca.execute(payload);

        assertNotNull(response);
        verify(privilegedExecutorServiceMock, times(0)).execute(any());
    }

    @Test
    public void testZipIsExtractedByTheUnprivilegedExecutor() throws KuraException, IOException {
        Path workDir = Files.createTempDirectory("command-cloud-app-test");
        try {
            CommandCloudApp cca = givenCommandCloudApp(false, workDir);

            cca.execute(commandPayload("ls", zipWithFiles(1)));

            ArgumentCaptor<Command> commands = ArgumentCaptor.forClass(Command.class);
            verify(this.unprivilegedExecutorServiceMock, times(2)).execute(commands.capture());
            verify(this.privilegedExecutorServiceMock, times(0)).execute(any());

            List<Command> executed = commands.getAllValues();
            assertNotNull("the archive is extracted first, by a command reading it", executed.get(0).getInputStream());
            assertEquals("ls", executed.get(1).getCommandLine()[0]);
        } finally {
            deleteRecursively(workDir);
        }
    }

    @Test
    public void testZipIsExtractedDirectlyWhenPrivileged() throws KuraException, IOException {
        Path workDir = Files.createTempDirectory("command-cloud-app-test");
        try {
            CommandCloudApp cca = givenCommandCloudApp(true, workDir);

            cca.execute(commandPayload("ls", zipWithFiles(1)));

            ArgumentCaptor<Command> commands = ArgumentCaptor.forClass(Command.class);
            verify(this.privilegedExecutorServiceMock, times(1)).execute(commands.capture());
            verify(this.unprivilegedExecutorServiceMock, times(0)).execute(any());

            assertEquals("only the command is executed", "ls", commands.getValue().getCommandLine()[0]);
            assertEquals(Collections.singletonList("file1.txt"), listFiles(workDir));
            assertEquals("content of file1.txt", new String(Files.readAllBytes(workDir.resolve("file1.txt")), UTF_8));
        } finally {
            deleteRecursively(workDir);
        }
    }

    @Test
    public void testZipExceedingTheLimitsIsRejectedWhenPrivileged() throws KuraException, IOException {
        Path workDir = Files.createTempDirectory("command-cloud-app-test");
        try {
            CommandCloudApp cca = givenCommandCloudApp(true, workDir);

            try {
                cca.execute(commandPayload("ls", zipWithFiles(1025)));
                fail("KuraException expected");
            } catch (KuraException e) {
                assertEquals(KuraErrorCode.DECODER_ERROR, e.getCode());
            }

            verify(this.privilegedExecutorServiceMock, times(0)).execute(any());
            verify(this.unprivilegedExecutorServiceMock, times(0)).execute(any());
            assertEquals("the partial extraction is removed", Collections.emptyList(), listFiles(workDir));
        } finally {
            deleteRecursively(workDir);
        }
    }

    private CommandCloudApp givenCommandCloudApp(boolean privileged, Path workDir) {
        CommandStatus status = new CommandStatus(new Command(new String[] {}), new LinuxExitStatus(0));

        this.unprivilegedExecutorServiceMock = mock(UnprivilegedExecutorService.class);
        when(this.unprivilegedExecutorServiceMock.execute(any())).thenReturn(status);
        this.privilegedExecutorServiceMock = mock(PrivilegedExecutorService.class);
        when(this.privilegedExecutorServiceMock.execute(any())).thenReturn(status);

        CommandCloudApp cca = new CommandCloudApp();
        cca.setUnprivilegedExecutorService(this.unprivilegedExecutorServiceMock);
        cca.setPrivilegedExecutorService(this.privilegedExecutorServiceMock);

        Map<String, Object> properties = new HashMap<>();
        properties.put("command.enable", true);
        properties.put("command.timeout", 10);
        properties.put("command.working.directory", workDir.toString());
        properties.put("privileged.command.service.enable", privileged);
        cca.updated(properties);

        return cca;
    }

    private static KuraPayload commandPayload(String command, byte[] zip) {
        KuraPayload payload = new KuraPayload();
        payload.addMetric("command.command", command);
        payload.setBody(zip);
        return payload;
    }

    private static byte[] zipWithFiles(int count) throws IOException {
        ByteArrayOutputStream archive = new ByteArrayOutputStream();

        try (ZipOutputStream zos = new ZipOutputStream(archive)) {
            for (int i = 1; i <= count; i++) {
                String name = "file" + i + ".txt";
                zos.putNextEntry(new ZipEntry(name));
                zos.write(("content of " + name).getBytes(UTF_8));
                zos.closeEntry();
            }
        }

        return archive.toByteArray();
    }

    private static List<String> listFiles(Path folder) throws IOException {
        try (Stream<Path> files = Files.list(folder)) {
            return files.map(file -> file.getFileName().toString()).sorted().collect(Collectors.toList());
        }
    }

    private static void deleteRecursively(Path folder) throws IOException {
        try (Stream<Path> paths = Files.walk(folder)) {
            for (Path path : (Iterable<Path>) paths.sorted(Comparator.reverseOrder())::iterator) {
                Files.deleteIfExists(path);
            }
        }
    }
}
