/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 * Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.cloud.app.command;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.util.concurrent.atomic.AtomicInteger;

import org.junit.Test;

public class ProcessMonitorThreadTest {

    private final AtomicInteger failedCloses = new AtomicInteger();
    private final ByteArrayOutputStream processInput = new ByteArrayOutputStream();
    private FakeProcess process;
    private ProcessMonitorThread monitor;

    /*
     * Scenarios
     */

    @Test
    public void processResultIsCollectedWhenStreamsFailToClose() throws InterruptedException {
        givenProcessWithStreamsFailingOnClose("output\n", "error\n", 3);

        whenProcessIsMonitored("input");

        thenStdoutIs("output\n");
        thenStderrIs("error\n");
        thenExitValueIs(3);
        thenProcessReceived("input\n");
        thenNoExceptionIsReported();
        thenAllStreamsWereClosed();
        thenProcessIsDestroyed();
    }

    /*
     * Steps
     */

    private void givenProcessWithStreamsFailingOnClose(final String stdout, final String stderr, final int exitValue) {
        this.process = new FakeProcess(failingOnClose(stdout), failingOnClose(stderr), new OutputStream() {

            @Override
            public void write(int b) {
                ProcessMonitorThreadTest.this.processInput.write(b);
            }

            @Override
            public void close() throws IOException {
                ProcessMonitorThreadTest.this.failedCloses.incrementAndGet();
                throw new IOException("close failure");
            }
        }, exitValue);
    }

    private void whenProcessIsMonitored(final String stdin) throws InterruptedException {
        this.monitor = new ProcessMonitorThread(this.process, stdin, 0);
        this.monitor.start();
        this.monitor.join(10000);
        assertFalse("monitor still running", this.monitor.isAlive());
    }

    private void thenStdoutIs(final String expected) {
        assertEquals(expected, this.monitor.getStdout());
    }

    private void thenStderrIs(final String expected) {
        assertEquals(expected, this.monitor.getStderr());
    }

    private void thenExitValueIs(final int expected) {
        assertEquals(Integer.valueOf(expected), this.monitor.getExitValue());
    }

    private void thenProcessReceived(final String expected) {
        assertEquals(expected, new String(this.processInput.toByteArray(), StandardCharsets.UTF_8));
    }

    private void thenNoExceptionIsReported() {
        assertNull(this.monitor.getException());
    }

    private void thenAllStreamsWereClosed() {
        // each input stream is closed by its gobbler and by the monitor, the output stream by the writer and by
        // the monitor
        assertTrue(this.failedCloses.get() >= 4);
    }

    private void thenProcessIsDestroyed() {
        assertTrue(this.process.destroyed);
    }

    /*
     * Utilities
     */

    private InputStream failingOnClose(final String content) {
        return new ByteArrayInputStream(content.getBytes(StandardCharsets.UTF_8)) {

            @Override
            public void close() throws IOException {
                ProcessMonitorThreadTest.this.failedCloses.incrementAndGet();
                throw new IOException("close failure");
            }
        };
    }

    private static final class FakeProcess extends Process {

        private final InputStream inputStream;
        private final InputStream errorStream;
        private final OutputStream outputStream;
        private final int exitValue;
        private volatile boolean destroyed;

        FakeProcess(InputStream inputStream, InputStream errorStream, OutputStream outputStream, int exitValue) {
            this.inputStream = inputStream;
            this.errorStream = errorStream;
            this.outputStream = outputStream;
            this.exitValue = exitValue;
        }

        @Override
        public OutputStream getOutputStream() {
            return this.outputStream;
        }

        @Override
        public InputStream getInputStream() {
            return this.inputStream;
        }

        @Override
        public InputStream getErrorStream() {
            return this.errorStream;
        }

        @Override
        public int waitFor() {
            return this.exitValue;
        }

        @Override
        public int exitValue() {
            return this.exitValue;
        }

        @Override
        public void destroy() {
            this.destroyed = true;
        }
    }
}
