/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 * Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.cloud.app.command;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;

import org.junit.Test;

public class StreamGobblerTest {

    private InputStream stream;
    private boolean closeAttempted;
    private StreamGobbler gobbler;

    /*
     * Scenarios
     */

    @Test
    public void streamContentIsCollectedWhenCloseFails() throws InterruptedException {
        givenStreamThatFailsOnClose("process output\n");

        whenStreamIsConsumed();

        thenCollectedContentIs("process output\n");
        thenCloseWasAttempted();
    }

    @Test
    public void readFailureEndsConsumption() throws InterruptedException {
        givenStreamThatFailsOnRead();

        whenStreamIsConsumed();

        thenCollectedContentIs("");
        thenCloseWasAttempted();
    }

    /*
     * Steps
     */

    private void givenStreamThatFailsOnClose(final String content) {
        this.stream = new ByteArrayInputStream(content.getBytes(StandardCharsets.UTF_8)) {

            @Override
            public void close() throws IOException {
                StreamGobblerTest.this.closeAttempted = true;
                throw new IOException("close failure");
            }
        };
    }

    private void givenStreamThatFailsOnRead() {
        this.stream = new InputStream() {

            @Override
            public int read() throws IOException {
                throw new IOException("read failure");
            }

            @Override
            public void close() {
                StreamGobblerTest.this.closeAttempted = true;
            }
        };
    }

    private void whenStreamIsConsumed() throws InterruptedException {
        this.gobbler = new StreamGobbler(this.stream, "stdout");
        this.gobbler.start();
        this.gobbler.join(5000);
        assertFalse("gobbler still running", this.gobbler.isAlive());
    }

    private void thenCollectedContentIs(final String expected) {
        assertEquals(expected, this.gobbler.getStreamAsString());
    }

    private void thenCloseWasAttempted() {
        assertTrue(this.closeAttempted);
    }
}
