/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.util.zip;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import java.io.File;
import java.io.IOException;
import java.util.Optional;

import org.apache.commons.io.FileUtils;
import org.junit.After;
import org.junit.Test;

public class CleanUpAfterFailedUnZipTest {

    private static final String WORK_FOLDER = "/tmp/kura_cleanup_test/";
    private static final String OUTPUT_FOLDER = WORK_FOLDER + "out/";
    private static final String PRESERVED_FILE = "keepme.txt";
    private static final String TEST_CLASSES_FOLDER = "target/test-classes/";

    private String inputFilePath;
    private Optional<Exception> exception = Optional.empty();

    @After
    public void clean() throws IOException {
        FileUtils.deleteDirectory(new File(WORK_FOLDER));
    }

    @Test
    public void noFilesLeftBehindWhenTooManyEntries() {
        givenCompressedFileInWorkFolder("tooManyCompressedFiles.zip");

        whenFileIsUnzippedIn(OUTPUT_FOLDER);

        thenExceptionIsThrown(IllegalStateException.class);
        thenExceptionMessageContains("Too many files to unzip.");
        thenFolderDoesNotExist(OUTPUT_FOLDER);
    }

    @Test
    public void noFilesLeftBehindWhenFileIsTooBig() {
        givenCompressedFileInWorkFolder("tooBigCompressedFile.zip");

        whenFileIsUnzippedIn(OUTPUT_FOLDER);

        thenExceptionIsThrown(IllegalStateException.class);
        thenExceptionMessageContains("File being unzipped is too big.");
        thenFolderDoesNotExist(OUTPUT_FOLDER);
    }

    @Test
    public void noFilesLeftBehindWhenPathIsIllegal() {
        givenCompressedFileInWorkFolder("illegalPathCompressedFile.zip");

        whenFileIsUnzippedIn(OUTPUT_FOLDER);

        thenExceptionIsThrown(IOException.class);
        thenExceptionMessageContains("File is outside extraction target directory.");
        thenFolderDoesNotExist(OUTPUT_FOLDER);
    }

    @Test
    public void preexistingFilesArePreservedOnFailure() {
        givenCompressedFileInWorkFolder("tooManyCompressedFiles.zip");
        givenExistingOutputFolderContaining(PRESERVED_FILE);

        whenFileIsUnzippedIn(OUTPUT_FOLDER);

        thenExceptionIsThrown(IllegalStateException.class);
        thenFolderContainsOnly(OUTPUT_FOLDER, PRESERVED_FILE);
    }

    @Test
    public void extractedFilesAreKeptOnSuccess() {
        givenCompressedFileInWorkFolder("singleCompressedFile.zip");

        whenFileIsUnzippedIn(OUTPUT_FOLDER);

        thenNoExceptionIsThrown();
        thenFolderContainsOnly(OUTPUT_FOLDER, "file.txt");
    }

    private void givenCompressedFileInWorkFolder(String inputFileName) {
        this.inputFilePath = WORK_FOLDER + inputFileName;
        try {
            FileUtils.copyFile(new File(TEST_CLASSES_FOLDER + inputFileName), new File(this.inputFilePath));
        } catch (IOException e) {
            throw new IllegalStateException("Unable to prepare the test input file", e);
        }
    }

    private void givenExistingOutputFolderContaining(String fileName) {
        try {
            FileUtils.writeStringToFile(new File(OUTPUT_FOLDER + fileName), "do not delete me", "UTF-8");
        } catch (IOException e) {
            throw new IllegalStateException("Unable to prepare the preexisting file", e);
        }
    }

    private void whenFileIsUnzippedIn(String outputFolder) {
        try {
            UnZip.unZipFile(this.inputFilePath, outputFolder);
        } catch (Exception e) {
            this.exception = Optional.of(e);
        }
    }

    private void thenExceptionIsThrown(final Class<? extends Exception> classz) {
        if (!this.exception.isPresent()) {
            fail("Exception expected");
        }

        assertEquals(classz, this.exception.get().getClass());
    }

    private void thenExceptionMessageContains(final String messageContent) {
        assertTrue(this.exception.get().getMessage().contains(messageContent));
    }

    private void thenNoExceptionIsThrown() {
        assertFalse(this.exception.isPresent());
    }

    private void thenFolderDoesNotExist(String folder) {
        assertFalse(new File(folder).exists());
    }

    private void thenFolderContainsOnly(String folder, String... expectedFileNames) {
        File outputFolder = new File(folder);
        assertTrue(outputFolder.isDirectory());

        String[] actualFileNames = outputFolder.list();
        assertArrayEquals(expectedFileNames, actualFileNames);
    }
}
