/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.util.zip;

import static org.eclipse.kura.util.zip.TestZipArchives.FILE_NAME;
import static org.eclipse.kura.util.zip.TestZipArchives.MAX_ALLOWED_ENTRIES;
import static org.eclipse.kura.util.zip.TestZipArchives.MAX_ALLOWED_UNCOMPRESSED_SIZE;
import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import java.io.File;
import java.io.IOException;
import java.util.Optional;

import org.apache.commons.io.FileUtils;
import org.junit.After;
import org.junit.Test;

public class CleanUpAfterFailedUnZipTest {

    private static final String WORK_FOLDER = "/tmp/kura_cleanup_test/";
    private static final String INPUT_ZIP_FILE = WORK_FOLDER + "input.zip";
    private static final String OUTPUT_FOLDER = WORK_FOLDER + "out/";
    private static final String PRESERVED_FILE = "keepme.txt";

    private Optional<Exception> exception = Optional.empty();

    @After
    public void clean() throws IOException {
        FileUtils.deleteDirectory(new File(WORK_FOLDER));
    }

    @Test
    public void noFilesLeftBehindWhenTooManyEntries() throws IOException {
        givenArchiveWithEntryCount(MAX_ALLOWED_ENTRIES + 1);

        whenArchiveIsUnzippedIn(OUTPUT_FOLDER);

        thenExceptionIsThrown(IllegalStateException.class);
        thenExceptionMessageContains("Too many files to unzip.");
        thenFolderDoesNotExist(OUTPUT_FOLDER);
    }

    @Test
    public void noFilesLeftBehindWhenFileIsTooBig() throws IOException {
        givenArchiveWithUncompressedSize(MAX_ALLOWED_UNCOMPRESSED_SIZE + 1024 * 1024);

        whenArchiveIsUnzippedIn(OUTPUT_FOLDER);

        thenExceptionIsThrown(IllegalStateException.class);
        thenExceptionMessageContains("File being unzipped is too big.");
        thenFolderDoesNotExist(OUTPUT_FOLDER);
    }

    @Test
    public void noFilesLeftBehindWhenPathIsIllegal() throws IOException {
        givenArchiveWithAnEntryOutsideTheTargetFolder();

        whenArchiveIsUnzippedIn(OUTPUT_FOLDER);

        thenExceptionIsThrown(IOException.class);
        thenExceptionMessageContains("File is outside extraction target directory.");
        thenFolderDoesNotExist(OUTPUT_FOLDER);
    }

    @Test
    public void preexistingFilesArePreservedOnFailure() throws IOException {
        givenArchiveWithEntryCount(MAX_ALLOWED_ENTRIES + 1);
        givenExistingOutputFolderContaining(PRESERVED_FILE);

        whenArchiveIsUnzippedIn(OUTPUT_FOLDER);

        thenExceptionIsThrown(IllegalStateException.class);
        thenFolderContainsOnly(OUTPUT_FOLDER, PRESERVED_FILE);
    }

    @Test
    public void extractedFilesAreKeptOnSuccess() throws IOException {
        givenArchiveWithASingleFile();

        whenArchiveIsUnzippedIn(OUTPUT_FOLDER);

        thenNoExceptionIsThrown();
        thenFolderContainsOnly(OUTPUT_FOLDER, FILE_NAME);
    }

    private void givenArchiveWithASingleFile() throws IOException {
        TestZipArchives.writeTo(TestZipArchives.withSingleFile(), INPUT_ZIP_FILE);
    }

    private void givenArchiveWithEntryCount(int entryCount) throws IOException {
        TestZipArchives.writeTo(TestZipArchives.withEntryCount(entryCount), INPUT_ZIP_FILE);
    }

    private void givenArchiveWithUncompressedSize(long uncompressedSize) throws IOException {
        TestZipArchives.writeTo(TestZipArchives.withUncompressedSize(uncompressedSize), INPUT_ZIP_FILE);
    }

    private void givenArchiveWithAnEntryOutsideTheTargetFolder() throws IOException {
        TestZipArchives.writeTo(TestZipArchives.withEntryOutsideTargetFolder(), INPUT_ZIP_FILE);
    }

    private void givenExistingOutputFolderContaining(String fileName) throws IOException {
        FileUtils.writeStringToFile(new File(OUTPUT_FOLDER + fileName), "do not delete me", "UTF-8");
    }

    private void whenArchiveIsUnzippedIn(String outputFolder) {
        try {
            UnZip.unZipFile(INPUT_ZIP_FILE, outputFolder);
        } catch (Exception e) {
            this.exception = Optional.of(e);
        }
    }

    private void thenExceptionIsThrown(final Class<? extends Exception> classz) {
        if (!this.exception.isPresent()) {
            fail("Exception expected");
        }

        assertEquals(classz, this.exception.get().getClass());
    }

    private void thenExceptionMessageContains(final String messageContent) {
        assertTrue(this.exception.get().getMessage().contains(messageContent));
    }

    private void thenNoExceptionIsThrown() {
        assertFalse(this.exception.isPresent());
    }

    private void thenFolderDoesNotExist(String folder) {
        assertFalse(new File(folder).exists());
    }

    private void thenFolderContainsOnly(String folder, String... expectedFileNames) {
        File outputFolder = new File(folder);
        assertTrue(outputFolder.isDirectory());

        String[] actualFileNames = outputFolder.list();
        assertArrayEquals(expectedFileNames, actualFileNames);
    }
}
