/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.util.zip;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import java.io.File;
import java.io.IOException;

import org.apache.commons.io.FileUtils;
import org.junit.After;
import org.junit.Test;

public class DetectZipCompressionTest {

    private static final String WORK_FOLDER = "/tmp/kura_detection_test/";
    private static final String INPUT_FILE = WORK_FOLDER + "input";

    private byte[] content;
    private boolean detected;

    @After
    public void clean() throws IOException {
        FileUtils.deleteDirectory(new File(WORK_FOLDER));
    }

    @Test
    public void zipArchiveFileIsDetected() throws IOException {
        givenFileContaining(TestZipArchives.withSingleFile());

        whenFileIsChecked();

        thenInputIsCompressed();
    }

    @Test
    public void textFileIsNotDetected() throws IOException {
        givenFileContaining("This is not an archive".getBytes("UTF-8"));

        whenFileIsChecked();

        thenInputIsNotCompressed();
    }

    @Test
    public void emptyFileIsNotDetected() throws IOException {
        givenFileContaining(new byte[0]);

        whenFileIsChecked();

        thenInputIsNotCompressed();
    }

    @Test
    public void fileWithTruncatedMagicNumberIsNotDetected() throws IOException {
        givenFileContaining(new byte[] { 0x50 });

        whenFileIsChecked();

        thenInputIsNotCompressed();
    }

    @Test
    public void zipArchiveBytesAreDetected() throws IOException {
        givenContent(TestZipArchives.withSingleFile());

        whenContentIsChecked();

        thenInputIsCompressed();
    }

    @Test
    public void textBytesAreNotDetected() throws IOException {
        givenContent("This is not an archive".getBytes("UTF-8"));

        whenContentIsChecked();

        thenInputIsNotCompressed();
    }

    private void givenContent(byte[] fileContent) {
        this.content = fileContent;
    }

    private void givenFileContaining(byte[] fileContent) throws IOException {
        FileUtils.writeByteArrayToFile(new File(INPUT_FILE), fileContent);
    }

    private void whenFileIsChecked() throws IOException {
        this.detected = UnZip.isZipCompressed(INPUT_FILE);
    }

    private void whenContentIsChecked() {
        this.detected = UnZip.isZipCompressed(this.content);
    }

    private void thenInputIsCompressed() {
        assertTrue(this.detected);
    }

    private void thenInputIsNotCompressed() {
        assertFalse(this.detected);
    }
}
