/*******************************************************************************
 * Copyright (c) 2023, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.internal.rest.cloudconnection.provider;

import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

import org.eclipse.kura.cloudconnection.request.RequestHandler;
import org.eclipse.kura.cloudconnection.request.RequestHandlerRegistry;
import org.eclipse.kura.configuration.ComponentConfiguration;
import org.eclipse.kura.configuration.ConfigurationService;
import org.eclipse.kura.crypto.CryptoService;
import org.eclipse.kura.internal.rest.cloudconnection.provider.dto.CloudComponentFactories;
import org.eclipse.kura.internal.rest.cloudconnection.provider.dto.CloudComponentInstances;
import org.eclipse.kura.internal.rest.cloudconnection.provider.dto.CloudConnectionFactoryPidAndCloudEndpointPid;
import org.eclipse.kura.internal.rest.cloudconnection.provider.dto.CloudEndpointPidRequest;
import org.eclipse.kura.internal.rest.cloudconnection.provider.dto.ConnectedStatus;
import org.eclipse.kura.internal.rest.cloudconnection.provider.dto.PidAndFactoryPidAndCloudEndpointPid;
import org.eclipse.kura.request.handler.jaxrs.DefaultExceptionHandler;
import org.eclipse.kura.request.handler.jaxrs.JaxRsRequestHandlerProxy;
import org.eclipse.kura.rest.configuration.api.ComponentConfigurationList;
import org.eclipse.kura.rest.configuration.api.DTOUtil;
import org.eclipse.kura.rest.configuration.api.PidAndFactoryPid;
import org.eclipse.kura.rest.configuration.api.PidSet;
import org.eclipse.kura.rest.configuration.api.UpdateComponentConfigurationRequest;
import org.osgi.service.useradmin.Role;
import org.osgi.service.useradmin.UserAdmin;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.parameters.RequestBody;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;

import jakarta.annotation.security.RolesAllowed;
import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.DELETE;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.PUT;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.Response;

import org.osgi.service.component.annotations.Activate;
import org.osgi.service.component.annotations.Component;
import org.osgi.service.component.annotations.Reference;
import org.osgi.service.component.annotations.ReferenceCardinality;
import org.osgi.service.component.annotations.ReferencePolicy;
@Tag(name = "Cloud connection", description = "Requires rest.cloudconnection or kura.admin permission.")
@ApiResponses({
        @ApiResponse(responseCode = "400", ref = "#/components/responses/BadRequest"),
        @ApiResponse(responseCode = "401", ref = "#/components/responses/Unauthenticated"),
        @ApiResponse(responseCode = "403", ref = "#/components/responses/Forbidden"),
        @ApiResponse(responseCode = "404", ref = "#/components/responses/NotFound"),
        @ApiResponse(responseCode = "500", ref = "#/components/responses/InternalError")
})
@Path("cloudconnection/v1")
@Component(
    name = "org.eclipse.kura.internal.rest.cloudconnection.provider.CloudConnectionRestService",
    immediate = true,
    service = { org.eclipse.kura.internal.rest.cloudconnection.provider.CloudConnectionRestService.class },
    property = {
        "kura.service.pid=org.eclipse.kura.internal.rest.cloudconnection.provider.CloudConnectionRestService",
        "osgi.jakartars.resource=true" })
public class CloudConnectionRestService {

    private static final Logger logger = LoggerFactory.getLogger(CloudConnectionRestService.class);

    private static final String MQTT_APP_ID = "CLD-V1";
    private static final String REST_ROLE_NAME = "cloudconnection";
    private static final String KURA_PERMISSION_REST_ROLE = "kura.permission.rest." + REST_ROLE_NAME;

    private final RequestHandler requestHandler = new JaxRsRequestHandlerProxy(this);

    private CloudConnectionService cloudConnectionService;
    private CloudConnectionManagerBridge cloudConnectionManagerBridge;
    private ConfigurationService configurationService;
    private CryptoService cryptoService;

    @Reference(name = "UserAdmin", service = org.osgi.service.useradmin.UserAdmin.class, unbind = "-")
    public void bindUserAdmin(UserAdmin userAdmin) {
        userAdmin.createRole(KURA_PERMISSION_REST_ROLE, Role.GROUP);
    }

    @Reference(name = "CryptoService", service = org.eclipse.kura.crypto.CryptoService.class, unbind = "-")
    public void bindCryptoService(CryptoService cryptoService) {
        this.cryptoService = cryptoService;
    }

    @Reference(name = "RequestHandlerRegistry",
            service = org.eclipse.kura.cloudconnection.request.RequestHandlerRegistry.class,
            cardinality = ReferenceCardinality.MULTIPLE,
            policy = ReferencePolicy.DYNAMIC,
            unbind = "unbindRequestHandlerRegistry")
    public void bindRequestHandlerRegistry(RequestHandlerRegistry registry) {
        try {
            registry.registerRequestHandler(MQTT_APP_ID, this.requestHandler);
        } catch (final Exception e) {
            logger.warn("Failed to register {} request handler", MQTT_APP_ID, e);
        }
    }

    @Reference(name = "ConfigurationService", service = org.eclipse.kura.configuration.ConfigurationService.class, unbind = "-")
    public void bindConfigurationService(ConfigurationService configurationService) {
        this.configurationService = configurationService;
    }

    public void unbindRequestHandlerRegistry(RequestHandlerRegistry registry) {
        try {
            registry.unregister(MQTT_APP_ID);
        } catch (final Exception e) {
            logger.warn("Failed to unregister {} request handler", MQTT_APP_ID, e);
        }
    }

    @Activate
    public void activate() {
        this.cloudConnectionService = new CloudConnectionService(this.configurationService);
        this.cloudConnectionManagerBridge = new CloudConnectionManagerBridge();
    }

    @GET
    @RolesAllowed(REST_ROLE_NAME)
    @Path("/instances")
    @Produces(MediaType.APPLICATION_JSON)
    @Operation(operationId = "get_cloudconnection_v1_instances", summary = "List cloud component instances",
            description = "Returns cloud endpoint and pub/sub instances.")
    @ApiResponse(responseCode = "200", description = "Requested data.",
            content = @Content(mediaType = MediaType.APPLICATION_JSON, schema = @Schema(implementation = CloudComponentInstances.class)))
    public CloudComponentInstances findCloudComponentInstances() {
        try {
            return new CloudComponentInstances(this.cloudConnectionService.findCloudEndpointInstances(),
                    this.cloudConnectionService.findPubsubInstances());
        } catch (Exception e) {
            throw DefaultExceptionHandler.toWebApplicationException(e);
        }
    }

    @POST
    @RolesAllowed(REST_ROLE_NAME)
    @Path("/cloudEndpoint/stackComponentPids")
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    @Operation(operationId = "post_cloudconnection_v1_cloudEndpoint_stackComponentPids", summary = "List stack component PIDs",
            description = "Returns component PIDs for the requested cloud endpoint stack.",
            requestBody = @RequestBody(required = true, content = @Content(mediaType = MediaType.APPLICATION_JSON,
                    schema = @Schema(implementation = CloudConnectionFactoryPidAndCloudEndpointPid.class))))
    @ApiResponse(responseCode = "200", description = "Requested data.",
            content = @Content(mediaType = MediaType.APPLICATION_JSON, schema = @Schema(implementation = PidSet.class)))
    public PidSet getStackComponentsPids(
            final CloudConnectionFactoryPidAndCloudEndpointPid cloudConnectionFactoryPidAndCloudEndpointPid) {
        try {
            Set<String> pidSet = this.cloudConnectionService.getStackComponentsPids(
                    cloudConnectionFactoryPidAndCloudEndpointPid.getCloudConnectionFactoryPid(),
                    cloudConnectionFactoryPidAndCloudEndpointPid.getCloudEndpointPid());

            return new PidSet(pidSet);
        } catch (Exception e) {
            throw DefaultExceptionHandler.toWebApplicationException(e);
        }
    }

    @POST
    @RolesAllowed(REST_ROLE_NAME)
    @Path("/cloudEndpoint")
    @Consumes(MediaType.APPLICATION_JSON)
    @Operation(operationId = "post_cloudconnection_v1_cloudEndpoint", summary = "Create cloud endpoint",
            description = "Creates a cloud endpoint from the requested factory.",
            requestBody = @RequestBody(required = true, content = @Content(mediaType = MediaType.APPLICATION_JSON,
                    schema = @Schema(implementation = CloudConnectionFactoryPidAndCloudEndpointPid.class))))
    @ApiResponse(responseCode = "200", ref = "#/components/responses/EmptySuccess")
    public Response createCloudEndpoint(
            final CloudConnectionFactoryPidAndCloudEndpointPid cloudConnectionFactoryPidAndCloudEndpointPid) {
        try {
            this.cloudConnectionService.createCloudEndpointFromFactory(
                    cloudConnectionFactoryPidAndCloudEndpointPid.getCloudConnectionFactoryPid(),
                    cloudConnectionFactoryPidAndCloudEndpointPid.getCloudEndpointPid());
        } catch (Exception e) {
            throw DefaultExceptionHandler.toWebApplicationException(e);
        }

        return Response.ok().build();
    }

    @DELETE
    @RolesAllowed(REST_ROLE_NAME)
    @Path("/cloudEndpoint")
    @Consumes(MediaType.APPLICATION_JSON)
    @Operation(operationId = "delete_cloudconnection_v1_cloudEndpoint", summary = "Delete cloud endpoint",
            description = "Deletes the requested cloud endpoint.",
            requestBody = @RequestBody(required = true, content = @Content(mediaType = MediaType.APPLICATION_JSON,
                    schema = @Schema(implementation = CloudConnectionFactoryPidAndCloudEndpointPid.class))))
    @ApiResponse(responseCode = "200", ref = "#/components/responses/EmptySuccess")
    public Response deleteCloudEndpoint(
            final CloudConnectionFactoryPidAndCloudEndpointPid cloudConnectionFactoryPidAndCloudEndpointPid) {
        try {
            this.cloudConnectionService.deleteCloudEndpointFromFactory(
                    cloudConnectionFactoryPidAndCloudEndpointPid.getCloudConnectionFactoryPid(),
                    cloudConnectionFactoryPidAndCloudEndpointPid.getCloudEndpointPid());
        } catch (Exception e) {
            throw DefaultExceptionHandler.toWebApplicationException(e);
        }

        return Response.ok().build();
    }

    @GET
    @RolesAllowed(REST_ROLE_NAME)
    @Path("/factories")
    @Produces(MediaType.APPLICATION_JSON)
    @Operation(operationId = "get_cloudconnection_v1_factories", summary = "List cloud component factories",
            description = "Returns available cloud endpoint and pub/sub factories.")
    @ApiResponse(responseCode = "200", description = "Requested data.",
            content = @Content(mediaType = MediaType.APPLICATION_JSON, schema = @Schema(implementation = CloudComponentFactories.class)))
    public CloudComponentFactories getCloudComponentFactories() {
        try {
            return this.cloudConnectionService.getCloudComponentFactories();
        } catch (Exception e) {
            throw DefaultExceptionHandler.toWebApplicationException(e);
        }
    }

    @POST
    @RolesAllowed(REST_ROLE_NAME)
    @Path("/pubSub")
    @Consumes(MediaType.APPLICATION_JSON)
    @Operation(operationId = "post_cloudconnection_v1_pubSub", summary = "Create pub/sub instance",
            description = "Creates a pub/sub instance attached to the requested endpoint.",
            requestBody = @RequestBody(required = true, content = @Content(mediaType = MediaType.APPLICATION_JSON,
                    schema = @Schema(implementation = PidAndFactoryPidAndCloudEndpointPid.class))))
    @ApiResponse(responseCode = "200", ref = "#/components/responses/EmptySuccess")
    public Response createPubSubInstance(
            final PidAndFactoryPidAndCloudEndpointPid pidAndFactoryPidAndCloudEndpointPid) {
        try {
            this.cloudConnectionService.createPubSubInstance(pidAndFactoryPidAndCloudEndpointPid.getPid(),
                    pidAndFactoryPidAndCloudEndpointPid.getFactoryPid(),
                    pidAndFactoryPidAndCloudEndpointPid.getCloudEndpointPid());
        } catch (Exception e) {
            throw DefaultExceptionHandler.toWebApplicationException(e);
        }

        return Response.ok().build();
    }

    @DELETE
    @RolesAllowed(REST_ROLE_NAME)
    @Path("/pubSub")
    @Consumes(MediaType.APPLICATION_JSON)
    @Operation(operationId = "delete_cloudconnection_v1_pubSub", summary = "Delete pub/sub instance",
            description = "Deletes the requested pub/sub instance.",
            requestBody = @RequestBody(required = true, content = @Content(mediaType = MediaType.APPLICATION_JSON,
                    schema = @Schema(implementation = PidAndFactoryPid.class))))
    @ApiResponse(responseCode = "200", ref = "#/components/responses/EmptySuccess")
    public Response deletePubSubInstance(final PidAndFactoryPid pidAndFactoryPid) {
        try {
            this.cloudConnectionService.deletePubSubInstance(pidAndFactoryPid.getPid());
        } catch (Exception e) {
            throw DefaultExceptionHandler.toWebApplicationException(e);
        }

        return Response.ok().build();
    }

    @POST
    @RolesAllowed(REST_ROLE_NAME)
    @Path("/configurations")
    @Consumes(MediaType.APPLICATION_JSON)
    @Operation(operationId = "post_cloudconnection_v1_configurations", summary = "Read cloud configurations",
            description = "Returns configurations for requested pub/sub and stack component PIDs.",
            requestBody = @RequestBody(required = true, content = @Content(mediaType = MediaType.APPLICATION_JSON,
                    schema = @Schema(implementation = PidSet.class))))
    @ApiResponse(responseCode = "200", description = "Requested data.",
            content = @Content(mediaType = MediaType.APPLICATION_JSON, schema = @Schema(implementation = ComponentConfigurationList.class)))
    public ComponentConfigurationList getConfigurations(final PidSet pidSet) {
        try {
            List<ComponentConfiguration> result = this.cloudConnectionService.getPubSubConfiguration(pidSet.getPids());

            result.addAll(this.cloudConnectionService.getStackConfigurationsByPid(pidSet.getPids()));

            return new ComponentConfigurationList(
                    result.stream().map(c -> DTOUtil.toComponentConfigurationDTO(c, this.cryptoService, false)
                            .replacePasswordsWithPlaceholder()).collect(Collectors.toList()));

        } catch (Exception e) {
            throw DefaultExceptionHandler.toWebApplicationException(e);
        }
    }

    @PUT
    @RolesAllowed(REST_ROLE_NAME)
    @Path("/configurations")
    @Consumes(MediaType.APPLICATION_JSON)
    @Operation(operationId = "put_cloudconnection_v1_configurations", summary = "Update stack configurations",
            description = "Applies component configurations and optionally takes a snapshot.",
            requestBody = @RequestBody(required = true, content = @Content(mediaType = MediaType.APPLICATION_JSON,
                    schema = @Schema(implementation = UpdateComponentConfigurationRequest.class))))
    @ApiResponse(responseCode = "200", ref = "#/components/responses/EmptySuccess")
    public Response updateStackComponentConfigurations(
            UpdateComponentConfigurationRequest updateComponentConfigurationRequest) {
        try {
            this.cloudConnectionService.updateStackComponentConfiguration(
                    updateComponentConfigurationRequest.getComponentConfigurations(),
                    updateComponentConfigurationRequest.isTakeSnapshot());
        } catch (Exception e) {
            throw DefaultExceptionHandler.toWebApplicationException(e);
        }

        return Response.ok().build();
    }

    @POST
    @RolesAllowed(REST_ROLE_NAME)
    @Path("/cloudEndpoint/connect")
    @Consumes(MediaType.APPLICATION_JSON)
    @Operation(operationId = "post_cloudconnection_v1_cloudEndpoint_connect", summary = "Connect cloud endpoint",
            description = "Connects the requested cloud endpoint.",
            requestBody = @RequestBody(required = true, content = @Content(mediaType = MediaType.APPLICATION_JSON,
                    schema = @Schema(implementation = CloudEndpointPidRequest.class))))
    @ApiResponse(responseCode = "200", ref = "#/components/responses/EmptySuccess")
    public Response connectCloudEndpoint(CloudEndpointPidRequest cloudEndpointPid) {
        try {
            this.cloudConnectionManagerBridge.connectCloudEndpoint(cloudEndpointPid.getCloudEndpointPid());
        } catch (Exception e) {
            throw DefaultExceptionHandler.toWebApplicationException(e);
        }

        return Response.ok().build();
    }

    @POST
    @RolesAllowed(REST_ROLE_NAME)
    @Path("/cloudEndpoint/disconnect")
    @Consumes(MediaType.APPLICATION_JSON)
    @Operation(operationId = "post_cloudconnection_v1_cloudEndpoint_disconnect", summary = "Disconnect cloud endpoint",
            description = "Disconnects the requested cloud endpoint.",
            requestBody = @RequestBody(required = true, content = @Content(mediaType = MediaType.APPLICATION_JSON,
                    schema = @Schema(implementation = CloudEndpointPidRequest.class))))
    @ApiResponse(responseCode = "200", ref = "#/components/responses/EmptySuccess")
    public Response disconnectCloudEndpoint(CloudEndpointPidRequest cloudEndpointPid) {
        try {
            this.cloudConnectionManagerBridge.disconnectCloudEndpoint(cloudEndpointPid.getCloudEndpointPid());
        } catch (Exception e) {
            throw DefaultExceptionHandler.toWebApplicationException(e);
        }

        return Response.ok().build();
    }

    @POST
    @RolesAllowed(REST_ROLE_NAME)
    @Path("/cloudEndpoint/isConnected")
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    @Operation(operationId = "post_cloudconnection_v1_cloudEndpoint_isConnected", summary = "Read cloud endpoint connection status",
            description = "Returns whether the requested cloud endpoint is connected.",
            requestBody = @RequestBody(required = true, content = @Content(mediaType = MediaType.APPLICATION_JSON,
                    schema = @Schema(implementation = CloudEndpointPidRequest.class))))
    @ApiResponse(responseCode = "200", description = "Requested data.",
            content = @Content(mediaType = MediaType.APPLICATION_JSON, schema = @Schema(implementation = ConnectedStatus.class)))
    public ConnectedStatus isConnectedCloudEndpoint(CloudEndpointPidRequest cloudEndpointPid) {
        try {
            return new ConnectedStatus(
                    this.cloudConnectionManagerBridge.isConnectedCloudEndpoint(cloudEndpointPid.getCloudEndpointPid()));
        } catch (Exception e) {
            throw DefaultExceptionHandler.toWebApplicationException(e);
        }
    }

}
