/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt;

import static org.eclipse.kura.core.token.jwt.TestJwtServiceOCD.aConfiguration;
import static org.eclipse.kura.core.token.jwt.TokenSpec.signedWith;

import org.eclipse.kura.security.token.jwt.JwtIssueRequest;
import org.junit.Test;

public class CertificateValidityTest extends JwtServiceTestBase {

    private static final boolean REQUIRED = true;
    private static final boolean NOT_REQUIRED = false;

    private static final String VALID_PEER = "valid-peer";
    private static final String EXPIRED_PEER = "expired-peer";
    private static final String ANOTHER_EXPIRED_PEER = "another-expired-peer";
    private static final String NOT_YET_VALID_PEER = "not-yet-valid-peer";

    @Test
    public void verificationSucceedsWhenTheCertificateIsWithinItsValidityPeriod() {
        givenAServiceRequiringCertificateValidity(REQUIRED);
        givenATrustedPeer(VALID_PEER);
        givenABoundKeystore();
        givenAnActiveService();

        whenTheTokenIsVerified(signedWith(VALID_PEER));

        thenTheTokenIsVerified();
    }

    @Test
    public void verificationFailsWhenTheCertificateHasExpired() {
        givenAServiceRequiringCertificateValidity(REQUIRED);
        givenAnExpiredTrustedPeer(EXPIRED_PEER);
        givenABoundKeystore();
        givenAnActiveService();

        whenTheTokenIsVerified(signedWith(EXPIRED_PEER));

        thenTheFailureIsAnUnacceptableToken();
    }

    @Test
    public void verificationSucceedsWhenTheCertificateHasExpiredAndValidityIsNotRequired() {
        givenAServiceRequiringCertificateValidity(NOT_REQUIRED);
        givenAnExpiredTrustedPeer(EXPIRED_PEER);
        givenABoundKeystore();
        givenAnActiveService();

        whenTheTokenIsVerified(signedWith(EXPIRED_PEER));

        thenTheTokenIsVerified();
    }

    @Test
    public void verificationFailsWhenTheCertificateIsNotYetValid() {
        givenAServiceRequiringCertificateValidity(REQUIRED);
        givenANotYetValidTrustedPeer(NOT_YET_VALID_PEER);
        givenABoundKeystore();
        givenAnActiveService();

        whenTheTokenIsVerified(signedWith(NOT_YET_VALID_PEER));

        thenTheFailureIsAnUnacceptableToken();
    }

    @Test
    public void verificationSucceedsWhenTheCertificateIsNotYetValidAndValidityIsNotRequired() {
        givenAServiceRequiringCertificateValidity(NOT_REQUIRED);
        givenANotYetValidTrustedPeer(NOT_YET_VALID_PEER);
        givenABoundKeystore();
        givenAnActiveService();

        whenTheTokenIsVerified(signedWith(NOT_YET_VALID_PEER));

        thenTheTokenIsVerified();
    }

    @Test
    public void issuingStillWorksButVerificationFailsWhenTheOwnSigningCertificateHasExpired() {
        givenAServiceRequiringCertificateValidity(REQUIRED);
        givenASigningKeyWithAnExpiredCertificate(SIGNING_KEY_ALIAS);
        givenABoundKeystore();
        givenAnActiveService();

        whenATokenIsIssued(JwtIssueRequest.builder().subject("bob").build());

        thenTheTokenIsIssued();
        whenTheIssuedTokenIsVerified();
        thenTheFailureIsAnUnacceptableToken();
    }

    @Test
    public void verificationFallsBackToTheNextCandidateWhenOneCertificateIsExpired() {
        givenAServiceRequiringCertificateValidity(REQUIRED);
        givenAnExpiredTrustedPeer(EXPIRED_PEER);
        givenATrustedPeer(VALID_PEER);
        givenABoundKeystore();
        givenAnActiveService();

        whenTheTokenIsVerified(signedWith(VALID_PEER).withoutKeyId());

        thenTheTokenIsVerified();
    }

    @Test
    public void verificationFailsWhenEveryCandidateCertificateIsExpired() {
        givenAServiceRequiringCertificateValidity(REQUIRED);
        givenAnExpiredTrustedPeer(EXPIRED_PEER);
        givenAnExpiredTrustedPeer(ANOTHER_EXPIRED_PEER);
        givenABoundKeystore();
        givenAnActiveService();

        whenTheTokenIsVerified(signedWith(EXPIRED_PEER).withoutKeyId());

        thenTheFailureIsAnUnacceptableToken();
    }

    @Test
    public void relaxingTheCertificateValidityRequirementTakesEffectAfterReconfiguration() {
        givenAServiceRequiringCertificateValidity(REQUIRED);
        givenAnExpiredTrustedPeer(EXPIRED_PEER);
        givenABoundKeystore();
        givenAnActiveService();
        givenConfiguration(aConfiguration().withRequireValidCertificate(NOT_REQUIRED));

        whenTheServiceIsUpdated();

        whenTheTokenIsVerified(signedWith(EXPIRED_PEER));
        thenTheTokenIsVerified();
    }

    private void givenAServiceRequiringCertificateValidity(final boolean required) {
        givenConfiguration(aConfiguration().withRequireValidCertificate(required));
    }

}
