/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt;

import org.eclipse.kura.security.token.jwt.JwtIssueRequest;
import org.junit.Test;

public class KeystoreBindingTest extends JwtServiceTestBase {

    @Test
    public void issueFailsWhenNoKeystoreIsBound() {
        givenDefaultConfiguration();
        givenAnActiveService();

        whenATokenIsIssued(JwtIssueRequest.builder().subject("bob").build());

        thenTheFailureIsAMisconfiguration();
    }

    @Test
    public void verifyFailsWhenNoKeystoreIsBound() {
        givenDefaultConfiguration();
        givenAnActiveService();

        whenAWellFormedButUnsignedTokenIsVerified();

        thenTheFailureIsAMisconfiguration();
    }

    @Test
    public void issuingAndVerificationSucceedWhenABoundKeystoreHoldsTheSigningKey() {
        givenDefaultConfiguration();
        givenASigningKey();
        givenABoundKeystore();
        givenAnActiveService();

        whenATokenIsIssued(JwtIssueRequest.builder().subject("bob").build());

        thenTheTokenIsIssued();
        whenTheIssuedTokenIsVerified();
        thenTheTokenIsVerified();
    }

    @Test
    public void issuingSucceedsWhenTheKeystoreIsBoundBeforeActivation() {
        givenDefaultConfiguration();
        givenASigningKey();
        givenABoundKeystore();

        whenTheServiceIsActivated();

        thenIssuingIsPossible();
    }

    @Test
    public void issuingAndVerificationAreDisabledWhenTheKeystoreIsUnbound() {
        givenDefaultConfiguration();
        givenASigningKey();
        givenABoundKeystore();
        givenAnActiveService();
        givenAPreviouslyIssuedToken();

        whenTheKeystoreIsUnbound();

        thenIssuingIsNotPossible();
        thenThePreviouslyIssuedTokenIsNoLongerVerifiable();
    }

    @Test
    public void issuingAndVerificationSurviveTheUnbindingOfADifferentKeystore() {
        givenDefaultConfiguration();
        givenASigningKey();
        givenABoundKeystore();
        givenAnActiveService();
        givenAPreviouslyIssuedToken();

        whenADifferentKeystoreIsUnbound();

        thenIssuingIsPossible();
        thenThePreviouslyIssuedTokenIsStillVerifiable();
    }

    @Test
    public void issuingAndVerificationAreDisabledAfterDeactivation() {
        givenDefaultConfiguration();
        givenASigningKey();
        givenABoundKeystore();
        givenAnActiveService();
        givenAPreviouslyIssuedToken();

        whenTheServiceIsDeactivated();

        thenIssuingIsNotPossible();
        thenThePreviouslyIssuedTokenIsNoLongerVerifiable();
    }

    @Test
    public void issuingAndVerificationAreDisabledWhenTheKeystoreCannotBeListed() {
        givenDefaultConfiguration();
        givenABoundKeystoreThatCannotBeListed();

        whenTheServiceIsActivated();

        thenIssuingIsNotPossible();
        whenAWellFormedButUnsignedTokenIsVerified();
        thenTheFailureIsAMisconfiguration();
    }

    @Test
    public void issueRejectsANullRequest() {
        givenDefaultConfiguration();
        givenASigningKey();
        givenABoundKeystore();
        givenAnActiveService();

        whenATokenIsIssued(null);

        thenAnExceptionOfTypeIsThrown(NullPointerException.class);
    }

    @Test
    public void verifyRejectsANullRequest() {
        givenDefaultConfiguration();
        givenASigningKey();
        givenABoundKeystore();
        givenAnActiveService();

        whenANullVerifyRequestIsSubmitted();

        thenAnExceptionOfTypeIsThrown(NullPointerException.class);
    }

}
