/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt;

import static org.eclipse.kura.core.token.jwt.TestJwtServiceOCD.aConfiguration;
import static org.eclipse.kura.core.token.jwt.TokenSpec.signedWith;

import org.eclipse.kura.security.token.jwt.JwtIssueRequest;
import org.junit.Test;

public class SigningKeyResolutionTest extends JwtServiceTestBase {

    private static final String PEER = "peer-a";
    private static final String CUSTOM_SIGNING_ALIAS = "my-signing-key";
    private static final String UNKNOWN_ALIAS = "does-not-exist";

    @Test
    public void issuingIsDisabledButVerificationWorksWhenNoSigningAliasIsConfigured() {
        givenConfiguration(aConfiguration().withSigningKeyAlias(null));
        givenATrustedPeer(PEER);
        givenABoundKeystore();
        givenAnActiveService();

        whenTheTokenIsVerified(signedWith(PEER));

        thenTheTokenIsVerified();
        thenIssuingIsNotPossible();
        thenTheFailureIsAMissingSigningKey();
    }

    @Test
    public void issuingIsDisabledButVerificationWorksWhenTheSigningAliasIsNotInTheKeystore() {
        givenDefaultConfiguration();
        givenATrustedPeer(PEER);
        givenABoundKeystore();
        givenAnActiveService();

        whenTheTokenIsVerified(signedWith(PEER));

        thenTheTokenIsVerified();
        thenIssuingIsNotPossible();
        thenTheFailureIsAMissingSigningKey();
    }

    @Test
    public void verifiedClaimsAreExposedWhenAForeignTokenIsAccepted() {
        givenConfiguration(aConfiguration().withSigningKeyAlias(null));
        givenATrustedPeer(PEER);
        givenABoundKeystore();
        givenAnActiveService();

        whenTheTokenIsVerified(signedWith(PEER));

        thenTheVerifiedIssuerIs(JwtServiceOCD.DEFAULT_ISSUER);
        thenTheVerifiedSubjectIs(TEST_SUBJECT);
    }

    @Test
    public void issuingAndVerificationAreDisabledWhenTheSigningAliasIsATrustedCertificateEntry() {
        givenDefaultConfiguration();
        givenATrustedPeer(SIGNING_KEY_ALIAS);
        givenATrustedPeer(PEER);
        givenABoundKeystore();
        givenAnActiveService();

        whenTheTokenIsVerified(signedWith(PEER));

        thenTheFailureIsAMisconfiguration();
        thenIssuingIsNotPossible();
        thenTheFailureIsAMisconfiguration();
    }

    @Test
    public void issuingAndVerificationAreDisabledWhenTheSigningKeyIsNotRsa() {
        givenDefaultConfiguration();
        givenANonRsaSigningKey(SIGNING_KEY_ALIAS);
        givenATrustedPeer(PEER);
        givenABoundKeystore();
        givenAnActiveService();

        whenTheTokenIsVerified(signedWith(PEER));

        thenTheFailureIsAMisconfiguration();
        thenIssuingIsNotPossible();
        thenTheFailureIsAMisconfiguration();
    }

    @Test
    public void theSigningAliasIsNotWhitelistedWhenItCannotBeResolved() {
        givenConfiguration(aConfiguration().withVerificationKeyAliases(UNKNOWN_ALIAS));
        givenATrustedPeer(PEER);
        givenABoundKeystore();
        givenAnActiveService();

        whenTheTokenIsVerified(signedWith(PEER));

        thenTheFailureIsNoMatchingCertificate();
        thenIssuingIsNotPossible();
        thenTheFailureIsAMissingSigningKey();
    }

    @Test
    public void theIssuedTokenCarriesTheConfiguredSigningAliasAsKeyId() {
        givenConfiguration(aConfiguration().withSigningKeyAlias(CUSTOM_SIGNING_ALIAS));
        givenASigningKey(CUSTOM_SIGNING_ALIAS);
        givenABoundKeystore();
        givenAnActiveService();

        whenATokenIsIssued(JwtIssueRequest.builder().subject("bob").build());

        thenTheTokenIsIssued();
        thenTheIssuedTokenHasKeyId(CUSTOM_SIGNING_ALIAS);
    }

}
