/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt;

import java.nio.charset.StandardCharsets;
import java.security.PrivateKey;
import java.security.Signature;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;
import java.util.Optional;

import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;

final class TestTokenSigner {

    private static final String RS256 = "RS256";
    private static final String HS256 = "HS256";
    private static final String NONE = "none";

    private final Optional<PrivateKey> signingKey;
    private final Optional<byte[]> hmacSecret;

    private String headerAlgorithm;
    private Optional<String> keyId = Optional.empty();
    private Optional<String> issuer = Optional.empty();
    private Optional<String> subject = Optional.empty();
    private Optional<Instant> issuedAt = Optional.empty();

    private TestTokenSigner(final Optional<PrivateKey> signingKey, final Optional<byte[]> hmacSecret,
            final String headerAlgorithm) {
        this.signingKey = signingKey;
        this.hmacSecret = hmacSecret;
        this.headerAlgorithm = headerAlgorithm;
    }

    static TestTokenSigner using(final PrivateKey signingKey) {
        return new TestTokenSigner(Optional.of(signingKey), Optional.empty(), RS256);
    }

    static TestTokenSigner usingHmac(final byte[] secret) {
        return new TestTokenSigner(Optional.empty(), Optional.of(secret), HS256);
    }

    static TestTokenSigner unsigned() {
        return new TestTokenSigner(Optional.empty(), Optional.empty(), NONE);
    }

    TestTokenSigner algorithm(final String headerAlgorithm) {
        this.headerAlgorithm = headerAlgorithm;
        return this;
    }

    TestTokenSigner keyId(final String keyId) {
        this.keyId = Optional.of(keyId);
        return this;
    }

    TestTokenSigner issuer(final String issuer) {
        this.issuer = Optional.of(issuer);
        return this;
    }

    TestTokenSigner subject(final String subject) {
        this.subject = Optional.of(subject);
        return this;
    }

    TestTokenSigner issuedAt(final Instant issuedAt) {
        this.issuedAt = Optional.of(issuedAt);
        return this;
    }

    String sign() throws Exception {
        final List<String> header = new ArrayList<>();
        header.add(stringMember("alg", this.headerAlgorithm));
        header.add(stringMember("typ", "JWT"));
        this.keyId.ifPresent(value -> header.add(stringMember("kid", value)));

        final List<String> payload = new ArrayList<>();
        this.issuer.ifPresent(value -> payload.add(stringMember("iss", value)));
        this.subject.ifPresent(value -> payload.add(stringMember("sub", value)));
        this.issuedAt.ifPresent(value -> payload.add(numberMember("iat", value.getEpochSecond())));

        final String signingInput = encode(asObject(header)) + "." + encode(asObject(payload));

        return signingInput + "." + encodeBytes(signatureOf(signingInput));
    }

    private byte[] signatureOf(final String signingInput) throws Exception {
        final byte[] input = signingInput.getBytes(StandardCharsets.US_ASCII);

        if (this.signingKey.isPresent()) {
            final Signature signature = Signature.getInstance("SHA256withRSA");
            signature.initSign(this.signingKey.get());
            signature.update(input);
            return signature.sign();
        }

        if (this.hmacSecret.isPresent()) {
            final Mac mac = Mac.getInstance("HmacSHA256");
            mac.init(new SecretKeySpec(this.hmacSecret.get(), "HmacSHA256"));
            return mac.doFinal(input);
        }

        return new byte[0];
    }

    private static String asObject(final List<String> members) {
        return "{" + String.join(",", members) + "}";
    }

    private static String stringMember(final String name, final String value) {
        return "\"" + escape(name) + "\":\"" + escape(value) + "\"";
    }

    private static String numberMember(final String name, final long value) {
        return "\"" + escape(name) + "\":" + value;
    }

    private static String escape(final String value) {
        return value.replace("\\", "\\\\").replace("\"", "\\\"");
    }

    private static String encode(final String json) {
        return encodeBytes(json.getBytes(StandardCharsets.UTF_8));
    }

    private static String encodeBytes(final byte[] bytes) {
        return Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);
    }

}
