/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt;

import java.lang.annotation.Annotation;

final class TestJwtServiceOCD implements JwtServiceOCD {

    private String keystoreServiceTarget = JwtServiceOCD.DEFAULT_KEYSTORE_TARGET_FILTER;
    private String signingKeyAlias = JwtServiceOCD.DEFAULT_SIGNING_KEY_ALIAS;
    private String issuer = JwtServiceOCD.DEFAULT_ISSUER;
    private String trustedIssuers = "";
    private String verificationKeyAliases = "";
    private int maximumLifetimeSeconds = JwtServiceOCD.DEFAULT_MAX_TOKEN_LIFETIME_SEC;
    private int clockSkewSeconds = JwtServiceOCD.DEFAULT_CLOCK_SKEW_SECONDS;
    private boolean requireValidCertificate = JwtServiceOCD.DEFAULT_REQUIRE_VALID_CERTIFICATE;

    static TestJwtServiceOCD aConfiguration() {
        return new TestJwtServiceOCD();
    }

    TestJwtServiceOCD withKeystoreServiceTarget(final String target) {
        this.keystoreServiceTarget = target;
        return this;
    }

    TestJwtServiceOCD withSigningKeyAlias(final String alias) {
        this.signingKeyAlias = alias;
        return this;
    }

    TestJwtServiceOCD withIssuer(final String issuer) {
        this.issuer = issuer;
        return this;
    }

    TestJwtServiceOCD withTrustedIssuers(final String trustedIssuers) {
        this.trustedIssuers = trustedIssuers;
        return this;
    }

    TestJwtServiceOCD withVerificationKeyAliases(final String verificationKeyAliases) {
        this.verificationKeyAliases = verificationKeyAliases;
        return this;
    }

    TestJwtServiceOCD withMaximumLifetimeSeconds(final int maximumLifetimeSeconds) {
        this.maximumLifetimeSeconds = maximumLifetimeSeconds;
        return this;
    }

    TestJwtServiceOCD withClockSkewSeconds(final int clockSkewSeconds) {
        this.clockSkewSeconds = clockSkewSeconds;
        return this;
    }

    TestJwtServiceOCD withRequireValidCertificate(final boolean requireValidCertificate) {
        this.requireValidCertificate = requireValidCertificate;
        return this;
    }

    @Override
    public String KeystoreService_target() {
        return this.keystoreServiceTarget;
    }

    @Override
    public String signing_key_alias() {
        return this.signingKeyAlias;
    }

    @Override
    public String issuer() {
        return this.issuer;
    }

    @Override
    public String trusted_issuers() {
        return this.trustedIssuers;
    }

    @Override
    public String verification_key_aliases() {
        return this.verificationKeyAliases;
    }

    @Override
    public int maximum_lifetime_seconds() {
        return this.maximumLifetimeSeconds;
    }

    @Override
    public int clock_skew_seconds() {
        return this.clockSkewSeconds;
    }

    @Override
    public boolean require_valid_certificate() {
        return this.requireValidCertificate;
    }

    @Override
    public Class<? extends Annotation> annotationType() {
        return JwtServiceOCD.class;
    }

}
