/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt;

import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;
import java.util.Optional;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

final class TestTokenInspector {

    private static final Pattern STRING_VALUE = Pattern.compile("\"((?:\\\\.|[^\"\\\\])*)\"");

    private final String header;
    private final String payload;
    private final int segmentCount;

    private TestTokenInspector(final String header, final String payload, final int segmentCount) {
        this.header = header;
        this.payload = payload;
        this.segmentCount = segmentCount;
    }

    static TestTokenInspector of(final String token) {
        final String[] segments = token.split("\\.", -1);

        final String header = segments.length > 0 ? decode(segments[0]) : "";
        final String payload = segments.length > 1 ? decode(segments[1]) : "";

        return new TestTokenInspector(header, payload, segments.length);
    }

    int segmentCount() {
        return this.segmentCount;
    }

    String header() {
        return this.header;
    }

    String payload() {
        return this.payload;
    }

    boolean headerHasMember(final String name) {
        return hasMember(this.header, name);
    }

    boolean payloadHasMember(final String name) {
        return hasMember(this.payload, name);
    }

    Optional<String> headerString(final String name) {
        return string(this.header, name);
    }

    Optional<String> payloadString(final String name) {
        return string(this.payload, name);
    }

    Optional<Long> payloadNumber(final String name) {
        final Matcher matcher = Pattern.compile(key(name) + "\\s*(-?\\d+)").matcher(this.payload);

        return matcher.find() ? Optional.of(Long.parseLong(matcher.group(1))) : Optional.empty();
    }

    Optional<List<String>> payloadStringArray(final String name) {
        final Matcher matcher = Pattern.compile(key(name) + "\\s*\\[([^\\]]*)\\]").matcher(this.payload);

        if (!matcher.find()) {
            return Optional.empty();
        }

        final List<String> values = new ArrayList<>();
        final Matcher elements = STRING_VALUE.matcher(matcher.group(1));
        while (elements.find()) {
            values.add(unescape(elements.group(1)));
        }

        return Optional.of(values);
    }

    private static boolean hasMember(final String json, final String name) {
        return Pattern.compile(key(name)).matcher(json).find();
    }

    private static Optional<String> string(final String json, final String name) {
        final Matcher matcher = Pattern.compile(key(name) + "\\s*" + STRING_VALUE.pattern()).matcher(json);

        return matcher.find() ? Optional.of(unescape(matcher.group(1))) : Optional.empty();
    }

    private static String key(final String name) {
        return "\"" + Pattern.quote(name) + "\"\\s*:";
    }

    private static String unescape(final String value) {
        return value.replace("\\\"", "\"").replace("\\\\", "\\");
    }

    private static String decode(final String segment) {
        return new String(Base64.getUrlDecoder().decode(segment), StandardCharsets.UTF_8);
    }

}
