/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt;

import java.util.Optional;

final class TokenSpec {

    enum SignatureKind {
        RSA,
        HMAC,
        NONE
    }

    private final SignatureKind signatureKind;
    private final Optional<String> signerAlias;

    private Optional<String> keyId;
    private Optional<String> explicitIssuer = Optional.empty();
    private boolean useConfiguredIssuer = true;

    private TokenSpec(final SignatureKind signatureKind, final Optional<String> signerAlias) {
        this.signatureKind = signatureKind;
        this.signerAlias = signerAlias;
        this.keyId = signerAlias;
    }

    static TokenSpec signedWith(final String signerAlias) {
        return new TokenSpec(SignatureKind.RSA, Optional.of(signerAlias));
    }

    static TokenSpec signedWithHmac() {
        return new TokenSpec(SignatureKind.HMAC, Optional.empty());
    }

    static TokenSpec unsigned() {
        return new TokenSpec(SignatureKind.NONE, Optional.empty());
    }

    TokenSpec withKeyId(final String keyId) {
        this.keyId = Optional.of(keyId);
        return this;
    }

    TokenSpec withoutKeyId() {
        this.keyId = Optional.empty();
        return this;
    }

    TokenSpec issuedBy(final String issuer) {
        this.explicitIssuer = Optional.of(issuer);
        this.useConfiguredIssuer = false;
        return this;
    }

    TokenSpec withoutIssuer() {
        this.explicitIssuer = Optional.empty();
        this.useConfiguredIssuer = false;
        return this;
    }

    SignatureKind signatureKind() {
        return this.signatureKind;
    }

    Optional<String> signerAlias() {
        return this.signerAlias;
    }

    Optional<String> keyId() {
        return this.keyId;
    }

    Optional<String> issuer(final String configuredIssuer) {
        return this.useConfiguredIssuer ? Optional.of(configuredIssuer) : this.explicitIssuer;
    }

}
