/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt;

import static org.eclipse.kura.core.token.jwt.TestJwtServiceOCD.aConfiguration;

import java.time.Duration;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.Optional;

import org.eclipse.kura.security.token.jwt.JwtIssueRequest;
import org.junit.Test;

public class TokenLifetimeTest extends JwtServiceTestBase {

    private static final int UNLIMITED = 0;
    private static final int ONE_HOUR = 3600;
    private static final int ONE_MINUTE = 60;

    @Test
    public void theTokenHasNoExpirationWhenNoLifetimeIsConfiguredAndNoneIsRequested() {
        givenAnActiveServiceCappingLifetimeAt(UNLIMITED);

        whenATokenIsIssued(JwtIssueRequest.builder().build());

        thenTheTokenIsIssued();
        thenTheIssuedTokenHasNoClaim("exp");
    }

    @Test
    public void theRequestedExpirationIsHonouredWhenNoLifetimeIsConfigured() {
        givenAnActiveServiceCappingLifetimeAt(UNLIMITED);

        final Instant expiresAt = wholeSecondsFromNow(Duration.ofDays(10));

        whenATokenIsIssued(JwtIssueRequest.builder().expiresAt(expiresAt).build());

        thenTheTokenIsIssued();
        thenTheIssuedTokenHasNumericClaim("exp", expiresAt.getEpochSecond());
    }

    @Test
    public void theExpirationIsCappedToTheMaximumLifetimeWhenNoneIsRequested() {
        givenAnActiveServiceCappingLifetimeAt(ONE_HOUR);

        whenATokenIsIssued(JwtIssueRequest.builder().build());

        thenTheTokenIsIssued();
        thenTheIssuedTokenExpiresAfterTheIssuingWindowPlus(Duration.ofSeconds(ONE_HOUR));
    }

    @Test
    public void theExpirationIsCappedWhenALongerLifetimeIsRequested() {
        givenAnActiveServiceCappingLifetimeAt(ONE_HOUR);

        whenATokenIsIssued(JwtIssueRequest.builder().expiresAt(wholeSecondsFromNow(Duration.ofHours(2))).build());

        thenTheTokenIsIssued();
        thenTheIssuedTokenExpiresAfterTheIssuingWindowPlus(Duration.ofSeconds(ONE_HOUR));
    }

    @Test
    public void theRequestedExpirationIsHonouredWhenShorterThanTheMaximumLifetime() {
        givenAnActiveServiceCappingLifetimeAt(ONE_HOUR);

        final Instant expiresAt = wholeSecondsFromNow(Duration.ofSeconds(ONE_MINUTE));

        whenATokenIsIssued(JwtIssueRequest.builder().expiresAt(expiresAt).build());

        thenTheTokenIsIssued();
        thenTheIssuedTokenHasNumericClaim("exp", expiresAt.getEpochSecond());
    }

    @Test
    public void theRequestedExpirationIsHonouredWhenEqualToTheMaximumLifetime() {
        givenAnActiveServiceCappingLifetimeAt(ONE_HOUR);

        final Instant expiresAt = wholeSecondsFromNow(Duration.ofSeconds(ONE_HOUR));

        whenATokenIsIssued(JwtIssueRequest.builder().expiresAt(expiresAt).build());

        thenTheTokenIsIssued();
        thenTheIssuedTokenHasNumericClaim("exp", expiresAt.getEpochSecond());
    }

    @Test
    public void theExpirationIsCappedWhenRequestedJustPastTheMaximumLifetime() {
        givenAnActiveServiceCappingLifetimeAt(ONE_HOUR);

        whenATokenIsIssued(JwtIssueRequest.builder() //
                .expiresAt(wholeSecondsFromNow(Duration.ofSeconds(ONE_HOUR + 2))) //
                .build());

        thenTheTokenIsIssued();
        thenTheIssuedTokenExpiresAfterTheIssuingWindowPlus(Duration.ofSeconds(ONE_HOUR));
    }

    @Test
    public void aPastExpirationIsHonouredAndYieldsAnImmediatelyInvalidToken() {
        givenAnActiveServiceCappingLifetimeAt(ONE_HOUR);

        final Instant expiresAt = wholeSecondsFromNow(Duration.ofHours(-1));

        whenATokenIsIssued(JwtIssueRequest.builder().expiresAt(expiresAt).build());

        thenTheTokenIsIssued();
        thenTheIssuedTokenHasNumericClaim("exp", expiresAt.getEpochSecond());
        whenTheIssuedTokenIsVerified();
        thenTheFailureIsAnUnacceptableToken();
    }

    @Test
    public void theReportedMaximumLifetimeReflectsTheConfiguration() {
        givenAnActiveServiceCappingLifetimeAt(ONE_HOUR);

        whenATokenIsIssued(JwtIssueRequest.builder().build());

        thenTheTokenIsIssued();
        thenTheReportedMaximumLifetimeIs(Optional.of(Duration.ofSeconds(ONE_HOUR)));
    }

    @Test
    public void anUnlimitedMaximumLifetimeIsReportedAsAbsent() {
        givenAnActiveServiceCappingLifetimeAt(UNLIMITED);

        whenATokenIsIssued(JwtIssueRequest.builder().build());

        thenTheTokenIsIssued();
        thenTheReportedMaximumLifetimeIs(Optional.empty());
    }

    @Test
    public void aReducedMaximumLifetimeAppliesToTokensIssuedAfterTheChange() {
        givenAnActiveServiceCappingLifetimeAt(ONE_HOUR);
        givenConfiguration(aConfiguration().withMaximumLifetimeSeconds(ONE_MINUTE));

        whenTheServiceIsUpdated();

        thenIssuingIsPossible();
        thenTheIssuedTokenExpiresAfterTheIssuingWindowPlus(Duration.ofSeconds(ONE_MINUTE));
        thenTheReportedMaximumLifetimeIs(Optional.of(Duration.ofSeconds(ONE_MINUTE)));
    }

    private void givenAnActiveServiceCappingLifetimeAt(final int maximumLifetimeSeconds) {
        givenConfiguration(aConfiguration().withMaximumLifetimeSeconds(maximumLifetimeSeconds));
        givenASigningKey();
        givenABoundKeystore();
        givenAnActiveService();
    }

    private static Instant wholeSecondsFromNow(final Duration offset) {
        return Instant.now().truncatedTo(ChronoUnit.SECONDS).plus(offset);
    }

}
