/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt;

import static org.eclipse.kura.core.token.jwt.TokenSpec.signedWith;
import static org.eclipse.kura.core.token.jwt.TokenSpec.signedWithHmac;
import static org.eclipse.kura.core.token.jwt.TokenSpec.unsigned;

import org.junit.Test;

public class TokenForgeryRejectionTest extends JwtServiceTestBase {

    private static final String TRUSTED_PEER = "trusted-peer";
    private static final String OTHER_TRUSTED_PEER = "other-trusted-peer";
    private static final String UNTRUSTED_KEY = "untrusted-key";
    private static final String UNKNOWN_ALIAS = "no-such-alias";

    @Test
    public void verificationFailsWhenTheTokenIsNotAJwt() {
        givenAnActiveServiceWithTrustedPeers();

        whenTheRawTokenIsVerified("not-a-jwt");

        thenTheFailureIsAnUndecodableToken();
    }

    @Test
    public void verificationFailsWhenTheTokenHasTooFewSegments() {
        givenAnActiveServiceWithTrustedPeers();

        whenTheRawTokenIsVerified("aaaa.bbbb");

        thenTheFailureIsAnUndecodableToken();
    }

    @Test
    public void verificationFailsWhenTheTokenSegmentsAreNotJson() {
        givenAnActiveServiceWithTrustedPeers();

        whenTheRawTokenIsVerified("a.b.c");

        thenTheFailureIsAnUndecodableToken();
    }

    @Test
    public void verificationFailsWhenThePayloadHasBeenTampered() {
        givenAnActiveServiceWithTrustedPeers();
        givenAPreviouslyIssuedToken();

        whenThePreviouslyIssuedTokenIsVerifiedWithATamperedPayload();

        thenTheFailureIsAnUnacceptableToken();
    }

    @Test
    public void verificationFailsWhenTheSignatureHasBeenTampered() {
        givenAnActiveServiceWithTrustedPeers();
        givenAPreviouslyIssuedToken();

        whenThePreviouslyIssuedTokenIsVerifiedWithATamperedSignature();

        thenTheFailureIsAnUnacceptableToken();
    }

    @Test
    public void verificationFailsWhenTheAlgorithmIsNone() {
        givenAnActiveServiceWithTrustedPeers();

        whenTheTokenIsVerified(unsigned());

        thenTheFailureIsAnUnacceptableToken();
    }

    @Test
    public void verificationFailsWhenTheAlgorithmIsHmac() {
        givenAnActiveServiceWithTrustedPeers();

        whenTheTokenIsVerified(signedWithHmac());

        thenTheFailureIsAnUnacceptableToken();
    }

    @Test
    public void verificationFailsWhenTheKeyIdIsSpoofed() {
        givenAnActiveServiceWithTrustedPeers();

        whenTheTokenIsVerified(signedWith(OTHER_TRUSTED_PEER).withKeyId(TRUSTED_PEER));

        thenTheFailureIsAnUnacceptableToken();
    }

    @Test
    public void verificationFailsWhenTheKeyIdIsUnknown() {
        givenAnActiveServiceWithTrustedPeers();

        whenTheTokenIsVerified(signedWith(TRUSTED_PEER).withKeyId(UNKNOWN_ALIAS));

        thenTheFailureIsNoMatchingCertificate();
    }

    @Test
    public void verificationFailsWhenTheKeyIdIsAbsentAndTheSignerIsUntrusted() {
        givenAnActiveServiceWithTrustedPeers();
        givenAnUntrustedKeyPair(UNTRUSTED_KEY);

        whenTheTokenIsVerified(signedWith(UNTRUSTED_KEY).withoutKeyId());

        thenTheFailureIsAnUnacceptableToken();
    }

    @Test
    public void verificationSucceedsWhenTheKeyIdIsAbsentAndTheSignerIsTrusted() {
        givenAnActiveServiceWithTrustedPeers();

        whenTheTokenIsVerified(signedWith(TRUSTED_PEER).withoutKeyId());

        thenTheTokenIsVerified();
    }

    @Test
    public void theRequestRejectsABlankToken() {
        whenAVerifyRequestIsBuiltWithToken("   ");

        thenAnExceptionOfTypeIsThrown(IllegalArgumentException.class);
    }

    @Test
    public void theRequestRejectsANullToken() {
        whenAVerifyRequestIsBuiltWithToken(null);

        thenAnExceptionOfTypeIsThrown(NullPointerException.class);
    }

    @Test
    public void theRequestRejectsAMissingToken() {
        whenAVerifyRequestIsBuiltWithoutAToken();

        thenAnExceptionOfTypeIsThrown(NullPointerException.class);
    }

    private void givenAnActiveServiceWithTrustedPeers() {
        givenDefaultConfiguration();
        givenASigningKey();
        givenATrustedPeer(TRUSTED_PEER);
        givenATrustedPeer(OTHER_TRUSTED_PEER);
        givenABoundKeystore();
        givenAnActiveService();
    }

}
