/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt;

import static org.eclipse.kura.core.token.jwt.TestJwtServiceOCD.aConfiguration;
import static org.eclipse.kura.core.token.jwt.TokenSpec.signedWith;

import org.eclipse.kura.security.token.jwt.JwtIssueRequest;
import org.junit.Test;

public class TrustedIssuersTest extends JwtServiceTestBase {

    private static final String OWN_ISSUER = "my-gateway";
    private static final String PARTNER_A = "partner-a";
    private static final String PARTNER_B = "partner-b";
    private static final String ROGUE = "rogue-gateway";

    private static final String PARTNER_CERT = "partner-cert";
    private static final String UNTRUSTED_KEY = "untrusted-key";

    @Test
    public void theSelfIssuedTokenVerifiesWhenNoTrustedIssuersAreConfigured() {
        givenAnActiveServiceTrusting("");

        whenATokenIsIssued(JwtIssueRequest.builder().subject("bob").build());

        thenTheTokenIsIssued();
        whenTheIssuedTokenIsVerified();
        thenTheTokenIsVerified();
    }

    @Test
    public void theSelfIssuedTokenStillVerifiesWhenTrustedIssuersAreConfigured() {
        givenAnActiveServiceTrusting(PARTNER_A + "," + PARTNER_B);

        whenATokenIsIssued(JwtIssueRequest.builder().subject("bob").build());

        thenTheTokenIsIssued();
        whenTheIssuedTokenIsVerified();
        thenTheTokenIsVerified();
        whenTheTokenIsVerified(signedWith(PARTNER_CERT).issuedBy(PARTNER_A));
        thenTheTokenIsVerified();
        whenTheTokenIsVerified(signedWith(PARTNER_CERT).issuedBy(PARTNER_B));
        thenTheTokenIsVerified();
    }

    @Test
    public void aForeignTokenVerifiesWhenItsIssuerIsTrusted() {
        givenAnActiveServiceTrusting(PARTNER_A);

        whenTheTokenIsVerified(signedWith(PARTNER_CERT).issuedBy(PARTNER_A));

        thenTheVerifiedIssuerIs(PARTNER_A);
    }

    @Test
    public void aForeignTokenIsRejectedWhenItsIssuerIsNotTrusted() {
        givenAnActiveServiceTrusting(PARTNER_A);

        whenTheTokenIsVerified(signedWith(PARTNER_CERT).issuedBy(ROGUE));

        thenTheFailureIsAnUnacceptableToken();
    }

    @Test
    public void aTokenWithoutAnIssuerIsRejected() {
        givenAnActiveServiceTrusting(PARTNER_A);

        whenTheTokenIsVerified(signedWith(PARTNER_CERT).withoutIssuer());

        thenTheFailureIsAnUnacceptableToken();
    }

    @Test
    public void aTokenWithAnEmptyIssuerIsRejected() {
        givenAnActiveServiceTrusting(PARTNER_A);

        whenTheTokenIsVerified(signedWith(PARTNER_CERT).issuedBy(""));

        thenTheFailureIsAnUnacceptableToken();
    }

    @Test
    public void theTrustedIssuerListIsParsedFromCsvIgnoringWhitespaceAndBlanks() {
        givenAnActiveServiceTrusting("  " + PARTNER_A + " , ,  " + PARTNER_B + "  ");

        whenTheTokenIsVerified(signedWith(PARTNER_CERT).issuedBy(PARTNER_A));

        thenTheVerifiedIssuerIs(PARTNER_A);
        whenTheTokenIsVerified(signedWith(PARTNER_CERT).issuedBy(PARTNER_B));
        thenTheVerifiedIssuerIs(PARTNER_B);
    }

    @Test
    public void listingTheConfiguredIssuerExplicitlyIsHarmless() {
        givenAnActiveServiceTrusting(OWN_ISSUER + "," + PARTNER_A);

        whenATokenIsIssued(JwtIssueRequest.builder().subject("bob").build());

        thenTheTokenIsIssued();
        whenTheIssuedTokenIsVerified();
        thenTheTokenIsVerified();
        whenTheTokenIsVerified(signedWith(PARTNER_CERT).issuedBy(PARTNER_A));
        thenTheTokenIsVerified();
    }

    @Test
    public void aTrustedIssuerAddedByReconfigurationIsAccepted() {
        givenAnActiveServiceTrusting("");
        givenConfiguration(aConfiguration().withIssuer(OWN_ISSUER).withTrustedIssuers(PARTNER_A));

        whenTheServiceIsUpdated();

        whenTheTokenIsVerified(signedWith(PARTNER_CERT).issuedBy(PARTNER_A));
        thenTheVerifiedIssuerIs(PARTNER_A);
    }

    @Test
    public void aTrustedIssuerDoesNotGrantTrustToAnUnknownSigningKey() {
        givenAnActiveServiceTrusting(PARTNER_A);
        givenAnUntrustedKeyPair(UNTRUSTED_KEY);

        whenTheTokenIsVerified(signedWith(UNTRUSTED_KEY).issuedBy(PARTNER_A));

        thenTheFailureIsNoMatchingCertificate();
    }

    private void givenAnActiveServiceTrusting(final String trustedIssuers) {
        givenConfiguration(aConfiguration().withIssuer(OWN_ISSUER).withTrustedIssuers(trustedIssuers));
        givenASigningKey();
        givenATrustedPeer(PARTNER_CERT);
        givenABoundKeystore();
        givenAnActiveService();
    }

}
