/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.token.jwt;

import static org.eclipse.kura.core.token.jwt.TestJwtServiceOCD.aConfiguration;
import static org.eclipse.kura.core.token.jwt.TokenSpec.signedWith;

import org.eclipse.kura.security.token.jwt.JwtIssueRequest;
import org.junit.Test;

public class VerificationKeyAliasesTest extends JwtServiceTestBase {

    private static final String PEER_A = "peer-a";
    private static final String PEER_B = "peer-b";
    private static final String EC_PEER = "ec-peer";
    private static final String SECRET_KEY = "aes-secret";
    private static final String TLS_CA = "tls-ca";
    private static final String UNKNOWN_ALIAS = "does-not-exist";

    @Test
    public void everyTrustedRsaEntryCanVerifyWhenAliasesAreNotRestricted() {
        givenDefaultConfiguration();
        givenASigningKey();
        givenATrustedPeer(PEER_A);
        givenATrustedPeer(PEER_B);
        givenABoundKeystore();
        givenAnActiveService();

        whenTheTokenIsVerified(signedWith(PEER_A));

        thenTheTokenIsVerified();
        whenTheTokenIsVerified(signedWith(PEER_B));
        thenTheTokenIsVerified();
    }

    @Test
    public void theSigningKeyCertificateCanVerifyWhenAliasesAreNotRestricted() {
        givenDefaultConfiguration();
        givenASigningKey();
        givenATrustedPeer(PEER_A);
        givenABoundKeystore();
        givenAnActiveService();

        whenATokenIsIssued(JwtIssueRequest.builder().subject("bob").build());

        thenTheTokenIsIssued();
        whenTheIssuedTokenIsVerified();
        thenTheTokenIsVerified();
    }

    @Test
    public void onlyWhitelistedAliasesCanVerifyWhenAliasesAreRestricted() {
        givenConfiguration(aConfiguration().withVerificationKeyAliases(PEER_A));
        givenASigningKey();
        givenATrustedPeer(PEER_A);
        givenATrustedPeer(PEER_B);
        givenABoundKeystore();
        givenAnActiveService();

        whenTheTokenIsVerified(signedWith(PEER_A));

        thenTheTokenIsVerified();
    }

    @Test
    public void tokensFromTrustedButNotWhitelistedKeysAreRejected() {
        givenConfiguration(aConfiguration().withVerificationKeyAliases(PEER_A));
        givenASigningKey();
        givenATrustedPeer(PEER_A);
        givenATrustedPeer(PEER_B);
        givenABoundKeystore();
        givenAnActiveService();

        whenTheTokenIsVerified(signedWith(PEER_B));

        thenTheFailureIsNoMatchingCertificate();
    }

    @Test
    public void theSigningAliasIsAlwaysWhitelistedWhenAliasesAreRestricted() {
        givenConfiguration(aConfiguration().withVerificationKeyAliases(PEER_A));
        givenASigningKey();
        givenATrustedPeer(PEER_A);
        givenABoundKeystore();
        givenAnActiveService();

        whenATokenIsIssued(JwtIssueRequest.builder().subject("bob").build());

        thenTheTokenIsIssued();
        whenTheIssuedTokenIsVerified();
        thenTheTokenIsVerified();
    }

    @Test
    public void unknownWhitelistedAliasesAreIgnored() {
        givenConfiguration(aConfiguration().withVerificationKeyAliases(PEER_A + "," + UNKNOWN_ALIAS));
        givenASigningKey();
        givenATrustedPeer(PEER_A);
        givenABoundKeystore();
        givenAnActiveService();

        whenTheTokenIsVerified(signedWith(PEER_A));

        thenTheTokenIsVerified();
    }

    @Test
    public void theAliasListIsParsedFromCsvIgnoringWhitespaceAndBlanks() {
        givenConfiguration(aConfiguration().withVerificationKeyAliases("  " + PEER_A + " , ,  " + PEER_B + "  "));
        givenASigningKey();
        givenATrustedPeer(PEER_A);
        givenATrustedPeer(PEER_B);
        givenABoundKeystore();
        givenAnActiveService();

        whenTheTokenIsVerified(signedWith(PEER_A));

        thenTheTokenIsVerified();
        whenTheTokenIsVerified(signedWith(PEER_B));
        thenTheTokenIsVerified();
    }

    @Test
    public void nonRsaTrustedCertificatesDoNotBreakVerification() {
        givenDefaultConfiguration();
        givenASigningKey();
        givenANonRsaTrustedPeer(EC_PEER);
        givenATrustedPeer(PEER_A);
        givenABoundKeystore();
        givenAnActiveService();

        whenTheTokenIsVerified(signedWith(PEER_A).withoutKeyId());

        thenTheTokenIsVerified();
    }

    @Test
    public void nonRsaTrustedCertificatesAreNotVerificationCandidates() {
        givenDefaultConfiguration();
        givenASigningKey();
        givenANonRsaTrustedPeer(EC_PEER);
        givenATrustedPeer(PEER_A);
        givenABoundKeystore();
        givenAnActiveService();

        whenTheTokenIsVerified(signedWith(PEER_A).withKeyId(EC_PEER));

        thenTheFailureIsNoMatchingCertificate();
    }

    @Test
    public void secretKeyEntriesAreNotVerificationCandidates() {
        givenDefaultConfiguration();
        givenASigningKey();
        givenASecretKey(SECRET_KEY);
        givenATrustedPeer(PEER_A);
        givenABoundKeystore();
        givenAnActiveService();

        whenTheTokenIsVerified(signedWith(PEER_A).withKeyId(SECRET_KEY));

        thenTheFailureIsNoMatchingCertificate();
    }

    @Test
    public void aTlsCertificateAuthorityCanMintTokensWhenAliasesAreNotRestricted() {
        givenDefaultConfiguration();
        givenASigningKey();
        givenATrustedPeer(TLS_CA);
        givenABoundKeystore();
        givenAnActiveService();

        whenTheTokenIsVerified(signedWith(TLS_CA).withoutKeyId());

        thenTheTokenIsVerified();
    }

    @Test
    public void aTlsCertificateAuthorityCannotMintTokensWhenAliasesAreRestricted() {
        givenConfiguration(aConfiguration().withVerificationKeyAliases(SIGNING_KEY_ALIAS));
        givenASigningKey();
        givenATrustedPeer(TLS_CA);
        givenABoundKeystore();
        givenAnActiveService();

        whenTheTokenIsVerified(signedWith(TLS_CA).withoutKeyId());

        thenTheFailureIsAnUnacceptableToken();
    }

}
