/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.identity;

import java.util.Optional;

import org.eclipse.kura.KuraException;
import org.osgi.annotation.versioning.ProviderType;

@ProviderType
public interface IdentityTokenService {

    public TokenPair issueTokenPair(String identityName) throws KuraException;

    public TokenPair refreshTokenPair(String refreshToken) throws KuraException;

    public Optional<VerifiedAccessToken> verifyAccessToken(String accessToken);

    public void revokeTokenFamily(String tokenFamilyId);
}
