/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.identity;

import static java.util.Objects.requireNonNull;

import java.time.Instant;
import java.util.Objects;
import java.util.Optional;

import org.osgi.annotation.versioning.ProviderType;

/**
 * Describes the token-based authentication configuration for an identity.
 * Token authentication can be used for both regular and temporary identities.
 *
 * @noextend This class is not intended to be subclassed by clients.
 * @since 2.8.0
 */
@ProviderType
public class TokenConfiguration implements IdentityConfigurationComponent {

    private final String token;
    private final Optional<Instant> expiration;
    private final boolean tokenAuthEnabled;

    /**
     * Creates a new token configuration.
     *
     * @param token             the authentication token for this identity. Must not be null.
     * @param expiration        the expiration time for the token, or empty if the token does not expire.
     * @param tokenAuthEnabled  a {@code boolean} indicating whether token authentication is
     *                         enabled for the given identity.
     */
    public TokenConfiguration(String token, Optional<Instant> expiration, boolean tokenAuthEnabled) {
        this.token = requireNonNull(token, "token cannot be null");
        this.expiration = requireNonNull(expiration, "expiration cannot be null");
        this.tokenAuthEnabled = tokenAuthEnabled;
    }

    /**
     * Creates a new token configuration with token authentication enabled.
     *
     * @param token      the authentication token for this identity. Must not be null.
     * @param expiration the expiration time for the token, or empty if the token does not expire.
     */
    public TokenConfiguration(String token, Optional<Instant> expiration) {
        this(token, expiration, true);
    }

    /**
     * Returns the authentication token.
     *
     * @return the token string.
     */
    public String getToken() {
        return token;
    }

    /**
     * Returns the expiration time for the token, if any.
     *
     * @return the expiration time, or empty if the token does not expire.
     */
    public Optional<Instant> getExpiration() {
        return expiration;
    }

    /**
     * Defines whether token authentication is enabled for the given identity.
     *
     * @return a {@code boolean} indicating whether token authentication is
     *         enabled for the given identity.
     */
    public boolean isTokenAuthEnabled() {
        return tokenAuthEnabled;
    }

    /**
     * Checks if the token has expired.
     *
     * @return {@code true} if the token has an expiration time and the current time
     *         is after that expiration time, {@code false} otherwise.
     */
    public boolean isExpired() {
        return expiration.map(exp -> Instant.now().isAfter(exp)).orElse(false);
    }

    @Override
    public int hashCode() {
        return Objects.hash(token, expiration, tokenAuthEnabled);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (!(obj instanceof TokenConfiguration)) {
            return false;
        }
        TokenConfiguration other = (TokenConfiguration) obj;
        return Objects.equals(token, other.token)
                && Objects.equals(expiration, other.expiration)
                && tokenAuthEnabled == other.tokenAuthEnabled;
    }

    @Override
    public String toString() {
        return "TokenConfiguration [tokenAuthEnabled=" + tokenAuthEnabled
                + ", expiration=" + expiration + ", expired=" + isExpired() + "]";
    }
}
