/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.identity;

import java.util.Objects;

import org.osgi.annotation.versioning.ProviderType;

@ProviderType
public class VerifiedAccessToken {

    private final String identityName;
    private final String tokenId;
    private final String tokenFamilyId;
    private final long expiresAt;

    public VerifiedAccessToken(final String identityName, final String tokenId, final String tokenFamilyId,
            final long expiresAt) {
        this.identityName = Objects.requireNonNull(identityName, "identityName");
        this.tokenId = Objects.requireNonNull(tokenId, "tokenId");
        this.tokenFamilyId = Objects.requireNonNull(tokenFamilyId, "tokenFamilyId");
        this.expiresAt = expiresAt;
    }

    public String getIdentityName() {
        return identityName;
    }

    public String getTokenId() {
        return tokenId;
    }

    public String getTokenFamilyId() {
        return tokenFamilyId;
    }

    public long getExpiresAt() {
        return expiresAt;
    }
}
