/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 * Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.deployment.download.impl;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.eclipse.kura.core.deployment.DownloadStatus;
import org.eclipse.kura.core.deployment.download.DeploymentPackageDownloadOptions;
import org.eclipse.kura.core.deployment.download.DownloadOptions;
import org.eclipse.kura.core.deployment.progress.ProgressEvent;
import org.junit.Test;

public class FollowDownloadRedirectsTest {

    private static final String INITIAL_URL = "http://fakeUrl/fakeData";
    private static final byte[] DATA = "test".getBytes();

    private final ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
    private final List<String> requestedUrls = new ArrayList<>();
    private int redirectsBeforeContent;
    private String redirectLocation;
    private Exception occurredException;
    private String transferProgressStatus;

    /*
     * Scenarios
     */

    @Test
    public void followsRedirectToFinalLocation() {
        givenServerRedirects(1, "http://fakeUrl/final");

        whenDownloadStarts();

        thenNoExceptionOccurred();
        thenTransferProgressStatusIs(DownloadStatus.COMPLETED);
        thenDownloadedDataAreCorrect();
        thenRequestedUrlsAre(INITIAL_URL, "http://fakeUrl/final");
    }

    @Test
    public void followsRedirectsUpToTheLimit() {
        givenServerRedirects(HttpDownloadCountingOutputStream.MAX_REDIRECTS, "http://fakeUrl/next");

        whenDownloadStarts();

        thenNoExceptionOccurred();
        thenTransferProgressStatusIs(DownloadStatus.COMPLETED);
        thenDownloadedDataAreCorrect();
        thenRequestedUrlCountIs(HttpDownloadCountingOutputStream.MAX_REDIRECTS + 1);
    }

    @Test
    public void failsWhenRedirectLoopExceedsTheLimit() {
        givenServerRedirects(Integer.MAX_VALUE, INITIAL_URL);

        whenDownloadStarts();

        thenExceptionOccurred();
        thenTransferProgressStatusIs(DownloadStatus.FAILED);
        thenNoDataDownloaded();
        thenRequestedUrlCountIs(HttpDownloadCountingOutputStream.MAX_REDIRECTS + 1);
    }

    @Test
    public void failsWhenRedirectHasNoLocation() {
        givenServerRedirects(1, null);

        whenDownloadStarts();

        thenExceptionOccurred();
        thenNoDataDownloaded();
        thenRequestedUrlCountIs(1);
    }

    /*
     * Steps
     */

    private void givenServerRedirects(int redirectsBeforeContent, String redirectLocation) {
        this.redirectsBeforeContent = redirectsBeforeContent;
        this.redirectLocation = redirectLocation;
    }

    private void whenDownloadStarts() {
        try {
            createDownloadStream().startWork();
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    private void thenNoExceptionOccurred() {
        assertNull(this.occurredException);
    }

    private void thenExceptionOccurred() {
        assertNotNull(this.occurredException);
    }

    private void thenTransferProgressStatusIs(DownloadStatus expected) {
        assertEquals(expected, DownloadStatus.valueOf(this.transferProgressStatus));
    }

    private void thenDownloadedDataAreCorrect() {
        assertArrayEquals(DATA, this.outputStream.toByteArray());
    }

    private void thenNoDataDownloaded() {
        assertEquals(0, this.outputStream.size());
    }

    private void thenRequestedUrlsAre(String... expected) {
        assertEquals(Arrays.asList(expected), this.requestedUrls);
    }

    private void thenRequestedUrlCountIs(int expected) {
        assertEquals(expected, this.requestedUrls.size());
    }

    /*
     * Utilities
     */

    private HttpDownloadCountingOutputStream createDownloadStream() {
        final DeploymentPackageDownloadOptions requestOptions = new DeploymentPackageDownloadOptions("fakeUri",
                "fakeDpName", "fakeDpVersion");
        requestOptions.setJobId(123);

        final DownloadOptions downloadOptions = new DownloadOptions();
        downloadOptions.setRequestOptions(requestOptions);
        downloadOptions.setAlreadyDownloaded(0);
        downloadOptions.setCallback(this::progressChanged);
        downloadOptions.setDownloadURL(INITIAL_URL);
        downloadOptions.setOut(this.outputStream);

        return new HttpDownloadCountingOutputStream(downloadOptions) {

            @Override
            protected HttpURLConnection openConnection(URL localUrl) throws IOException {
                return mockServerResponse(localUrl);
            }
        };
    }

    private HttpURLConnection mockServerResponse(URL url) throws IOException {
        final HttpURLConnection connection = mock(HttpURLConnection.class);
        final boolean redirect = this.requestedUrls.size() < this.redirectsBeforeContent;
        this.requestedUrls.add(url.toString());

        if (redirect) {
            when(connection.getResponseCode()).thenReturn(HttpURLConnection.HTTP_MOVED_TEMP);
            when(connection.getHeaderField("Location")).thenReturn(this.redirectLocation);
        } else {
            when(connection.getResponseCode()).thenReturn(HttpURLConnection.HTTP_OK);
            when(connection.getInputStream()).thenReturn(new ByteArrayInputStream(DATA));
            when(connection.getHeaderField("Content-Length")).thenReturn(String.valueOf(DATA.length));
        }
        return connection;
    }

    private void progressChanged(ProgressEvent progress) {
        this.transferProgressStatus = progress.getTransferStatus();
    }
}
