<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2025 Eurotech and/or its affiliates and others

    This program and the accompanying materials are made
    available under the terms of the Eclipse Public License 2.0
    which is available at https://www.eclipse.org/legal/epl-2.0/

    SPDX-License-Identifier: EPL-2.0

    Contributors:
     Eurotech
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>org.eclipse.kura</groupId>
    <artifactId>kura-bom</artifactId>
    <version>6.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>Kura BOM</name>

    <distributionManagement>
        <repository>
            <id>repo.eclipse.org</id>
            <name>Kura Repository - Releases</name>
            <url>https://repo.eclipse.org/content/repositories/kura-releases/</url>
        </repository>
        <snapshotRepository>
            <id>repo.eclipse.org</id>
            <name>Kura Repository - Snapshots</name>
            <url>https://repo.eclipse.org/content/repositories/kura-snapshots/</url>
        </snapshotRepository>
    </distributionManagement>

    <properties>
        <org.eclipse.kura.ai.triton.server.version>2.0.0-SNAPSHOT</org.eclipse.kura.ai.triton.server.version>
        <org.eclipse.kura.api.version>3.0.0-SNAPSHOT</org.eclipse.kura.api.version>
        <org.eclipse.kura.broker.artemis.core.version>2.0.0-SNAPSHOT</org.eclipse.kura.broker.artemis.core.version>
        <org.eclipse.kura.broker.artemis.simple.mqtt.version>2.0.0-SNAPSHOT</org.eclipse.kura.broker.artemis.simple.mqtt.version>
        <org.eclipse.kura.broker.artemis.xml.version>2.0.0-SNAPSHOT</org.eclipse.kura.broker.artemis.xml.version>
        <org.eclipse.kura.camel.version>2.0.0-SNAPSHOT</org.eclipse.kura.camel.version>
        <org.eclipse.kura.camel.cloud.factory.version>2.0.0-SNAPSHOT</org.eclipse.kura.camel.cloud.factory.version>
        <org.eclipse.kura.camel.xml.version>2.0.0-SNAPSHOT</org.eclipse.kura.camel.xml.version>
        <org.eclipse.kura.cloud.base.provider.version>1.0.0-SNAPSHOT</org.eclipse.kura.cloud.base.provider.version>
        <org.eclipse.kura.cloudconnection.eclipseiot.mqtt.provider.version>2.0.0-SNAPSHOT</org.eclipse.kura.cloudconnection.eclipseiot.mqtt.provider.version>
        <org.eclipse.kura.cloudconnection.kapua.mqtt.provider.version>1.0.0-SNAPSHOT</org.eclipse.kura.cloudconnection.kapua.mqtt.provider.version>
        <org.eclipse.kura.cloudconnection.raw.mqtt.provider.version>2.0.0-SNAPSHOT</org.eclipse.kura.cloudconnection.raw.mqtt.provider.version>
        <org.eclipse.kura.cloudconnection.sparkplug.mqtt.provider.version>2.0.0-SNAPSHOT</org.eclipse.kura.cloudconnection.sparkplug.mqtt.provider.version>
        <org.eclipse.kura.configuration.change.manager.version>2.0.0-SNAPSHOT</org.eclipse.kura.configuration.change.manager.version>
        <org.eclipse.kura.container.orchestration.provider.version>2.0.0-SNAPSHOT</org.eclipse.kura.container.orchestration.provider.version>
        <org.eclipse.kura.container.provider.version>2.0.0-SNAPSHOT</org.eclipse.kura.container.provider.version>
        <org.eclipse.kura.core.version>2.0.0-SNAPSHOT</org.eclipse.kura.core.version>
        <org.eclipse.kura.core.certificates.version>2.0.0-SNAPSHOT</org.eclipse.kura.core.certificates.version>
        <org.eclipse.kura.core.cloud.factory.version>2.0.0-SNAPSHOT</org.eclipse.kura.core.cloud.factory.version>
        <org.eclipse.kura.core.comm.version>2.0.0-SNAPSHOT</org.eclipse.kura.core.comm.version>
        <org.eclipse.kura.core.configuration.version>3.0.0-SNAPSHOT</org.eclipse.kura.core.configuration.version>
        <org.eclipse.kura.core.crypto.version>2.0.0-SNAPSHOT</org.eclipse.kura.core.crypto.version>
        <org.eclipse.kura.core.deployment.version>2.0.0-SNAPSHOT</org.eclipse.kura.core.deployment.version>
        <org.eclipse.kura.core.identity.version>2.0.0-SNAPSHOT</org.eclipse.kura.core.identity.version>
        <org.eclipse.kura.core.inventory.version>2.0.0-SNAPSHOT</org.eclipse.kura.core.inventory.version>
        <org.eclipse.kura.core.keystore.version>2.0.0-SNAPSHOT</org.eclipse.kura.core.keystore.version>
        <org.eclipse.kura.core.net.version>2.0.0-SNAPSHOT</org.eclipse.kura.core.net.version>
        <org.eclipse.kura.core.status.version>2.0.0-SNAPSHOT</org.eclipse.kura.core.status.version>
        <org.eclipse.kura.core.system.version>2.0.0-SNAPSHOT</org.eclipse.kura.core.system.version>
        <org.eclipse.kura.rest.tamper.detection.provider.version>1.0.0-SNAPSHOT</org.eclipse.kura.rest.tamper.detection.provider.version>
        <org.eclipse.kura.db.h2db.provider.version>1.0.0-SNAPSHOT</org.eclipse.kura.db.h2db.provider.version>
        <org.eclipse.kura.db.sqlite.provider.version>2.0.0-SNAPSHOT</org.eclipse.kura.db.sqlite.provider.version>
        <org.eclipse.kura.deployment.agent.version>2.0.0-SNAPSHOT</org.eclipse.kura.deployment.agent.version>
        <org.eclipse.kura.driver.ble.sensortag.provider.version>2.0.0-SNAPSHOT</org.eclipse.kura.driver.ble.sensortag.provider.version>
        <org.eclipse.kura.driver.block.version>2.0.0-SNAPSHOT</org.eclipse.kura.driver.block.version>
        <org.eclipse.kura.driver.gpio.provider.version>2.0.0-SNAPSHOT</org.eclipse.kura.driver.gpio.provider.version>
        <org.eclipse.kura.driver.helper.provider.version>2.0.0-SNAPSHOT</org.eclipse.kura.driver.helper.provider.version>
        <org.eclipse.kura.driver.opcua.provider.version>2.0.0-SNAPSHOT</org.eclipse.kura.driver.opcua.provider.version>
        <org.eclipse.kura.driver.s7plc.provider.version>2.0.0-SNAPSHOT</org.eclipse.kura.driver.s7plc.provider.version>
        <org.eclipse.kura.emulator.version>2.0.0-SNAPSHOT</org.eclipse.kura.emulator.version>
        <org.eclipse.kura.emulator.clock.version>2.0.0-SNAPSHOT</org.eclipse.kura.emulator.clock.version>
        <org.eclipse.kura.emulator.gpio.version>2.0.0-SNAPSHOT</org.eclipse.kura.emulator.gpio.version>
        <org.eclipse.kura.emulator.net.version>2.0.0-SNAPSHOT</org.eclipse.kura.emulator.net.version>
        <org.eclipse.kura.emulator.position.version>2.0.0-SNAPSHOT</org.eclipse.kura.emulator.position.version>
        <org.eclipse.kura.emulator.usb.version>2.0.0-SNAPSHOT</org.eclipse.kura.emulator.usb.version>
        <org.eclipse.kura.emulator.watchdog.version>2.0.0-SNAPSHOT</org.eclipse.kura.emulator.watchdog.version>
        <org.eclipse.kura.event.publisher.version>2.0.0-SNAPSHOT</org.eclipse.kura.event.publisher.version>
        <org.eclipse.kura.hook.file.move.provider.version>2.0.0-SNAPSHOT</org.eclipse.kura.hook.file.move.provider.version>
        <org.eclipse.kura.http.server.manager.version>2.0.0-SNAPSHOT</org.eclipse.kura.http.server.manager.version>
        <org.eclipse.kura.json.marshaller.unmarshaller.provider.version>2.0.0-SNAPSHOT</org.eclipse.kura.json.marshaller.unmarshaller.provider.version>
        <org.eclipse.kura.linux.clock.version>2.0.0-SNAPSHOT</org.eclipse.kura.linux.clock.version>
        <org.eclipse.kura.linux.gpio.version>2.0.0-SNAPSHOT</org.eclipse.kura.linux.gpio.version>
        <org.eclipse.kura.linux.net.version>3.0.0-SNAPSHOT</org.eclipse.kura.linux.net.version>
        <org.eclipse.kura.linux.systemd.provider.version>2.0.0-SNAPSHOT</org.eclipse.kura.linux.systemd.provider.version>
        <org.eclipse.kura.linux.usb.version>2.0.0-SNAPSHOT</org.eclipse.kura.linux.usb.version>
        <org.eclipse.kura.linux.usb.aarch64.version>2.0.0-SNAPSHOT</org.eclipse.kura.linux.usb.aarch64.version>
        <org.eclipse.kura.linux.usb.x86_64.version>2.0.0-SNAPSHOT</org.eclipse.kura.linux.usb.x86_64.version>
        <org.eclipse.kura.linux.watchdog.version>2.0.0-SNAPSHOT</org.eclipse.kura.linux.watchdog.version>
        <org.eclipse.kura.log.filesystem.provider.version>2.0.0-SNAPSHOT</org.eclipse.kura.log.filesystem.provider.version>
        <org.eclipse.kura.misc.cloudcat.version>2.0.0-SNAPSHOT</org.eclipse.kura.misc.cloudcat.version>
        <org.eclipse.kura.net.admin.firewall.version>2.0.0-SNAPSHOT</org.eclipse.kura.net.admin.firewall.version>
        <org.eclipse.kura.net.configuration.version>2.0.0-SNAPSHOT</org.eclipse.kura.net.configuration.version>
        <org.eclipse.kura.network.threat.manager.version>2.0.0-SNAPSHOT</org.eclipse.kura.network.threat.manager.version>
        <org.eclipse.kura.nm.version>2.0.0-SNAPSHOT</org.eclipse.kura.nm.version>
        <org.eclipse.kura.protocol.modbus.version>3.0.0-SNAPSHOT</org.eclipse.kura.protocol.modbus.version>
        <org.eclipse.kura.request.handler.jaxrs.version>2.0.0-SNAPSHOT</org.eclipse.kura.request.handler.jaxrs.version>
        <org.eclipse.kura.rest.cloudconnection.provider.version>2.0.0-SNAPSHOT</org.eclipse.kura.rest.cloudconnection.provider.version>
        <org.eclipse.kura.rest.configuration.provider.version>2.0.0-SNAPSHOT</org.eclipse.kura.rest.configuration.provider.version>
        <org.eclipse.kura.rest.identity.provider.version>2.0.0-SNAPSHOT</org.eclipse.kura.rest.identity.provider.version>
        <org.eclipse.kura.rest.inventory.provider.version>2.0.0-SNAPSHOT</org.eclipse.kura.rest.inventory.provider.version>
        <org.eclipse.kura.rest.keystore.provider.version>1.0.0-SNAPSHOT</org.eclipse.kura.rest.keystore.provider.version>
        <org.eclipse.kura.rest.network.configuration.provider.version>2.0.0-SNAPSHOT</org.eclipse.kura.rest.network.configuration.provider.version>
        <org.eclipse.kura.rest.network.status.provider.version>2.0.0-SNAPSHOT</org.eclipse.kura.rest.network.status.provider.version>
        <org.eclipse.kura.rest.packages.provider.version>2.0.0-SNAPSHOT</org.eclipse.kura.rest.packages.provider.version>
        <org.eclipse.kura.rest.provider.version>2.0.0-SNAPSHOT</org.eclipse.kura.rest.provider.version>
        <org.eclipse.kura.rest.security.provider.version>2.0.0-SNAPSHOT</org.eclipse.kura.rest.security.provider.version>
        <org.eclipse.kura.rest.service.listing.provider.version>2.0.0-SNAPSHOT</org.eclipse.kura.rest.service.listing.provider.version>
        <org.eclipse.kura.rest.system.provider.version>2.0.0-SNAPSHOT</org.eclipse.kura.rest.system.provider.version>
        <org.eclipse.kura.stress.version>2.0.0-SNAPSHOT</org.eclipse.kura.stress.version>
        <org.eclipse.kura.useradmin.store.version>2.0.0-SNAPSHOT</org.eclipse.kura.useradmin.store.version>
        <org.eclipse.kura.util.version>2.0.0-SNAPSHOT</org.eclipse.kura.util.version>
        <org.eclipse.kura.wire.camel.version>2.0.0-SNAPSHOT</org.eclipse.kura.wire.camel.version>
        <org.eclipse.kura.xml.marshaller.unmarshaller.provider.version>2.0.0-SNAPSHOT</org.eclipse.kura.xml.marshaller.unmarshaller.provider.version>
        <!-- test-util -->
        <org.eclipse.kura.core.testutil.version>6.0.0-SNAPSHOT</org.eclipse.kura.core.testutil.version>
        <org.eclipse.kura.test.version>6.0.0-SNAPSHOT</org.eclipse.kura.test.version>
        <org.eclipse.kura.util.test.driver.version>6.0.0-SNAPSHOT</org.eclipse.kura.util.test.driver.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.ai.triton.server</artifactId>
                <version>${org.eclipse.kura.ai.triton.server.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.api</artifactId>
                <version>${org.eclipse.kura.api.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.broker.artemis.core</artifactId>
                <version>${org.eclipse.kura.broker.artemis.core.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.broker.artemis.simple.mqtt</artifactId>
                <version>${org.eclipse.kura.broker.artemis.simple.mqtt.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.broker.artemis.xml</artifactId>
                <version>${org.eclipse.kura.broker.artemis.xml.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.camel</artifactId>
                <version>${org.eclipse.kura.camel.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.camel.cloud.factory</artifactId>
                <version>${org.eclipse.kura.camel.cloud.factory.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.camel.xml</artifactId>
                <version>${org.eclipse.kura.camel.xml.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.cloud.base.provider</artifactId>
                <version>${org.eclipse.kura.cloud.base.provider.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.cloudconnection.eclipseiot.mqtt.provider</artifactId>
                <version>${org.eclipse.kura.cloudconnection.eclipseiot.mqtt.provider.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.cloudconnection.kapua.mqtt.provider</artifactId>
                <version>${org.eclipse.kura.cloudconnection.kapua.mqtt.provider.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.cloudconnection.raw.mqtt.provider</artifactId>
                <version>${org.eclipse.kura.cloudconnection.raw.mqtt.provider.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.cloudconnection.sparkplug.mqtt.provider</artifactId>
                <version>${org.eclipse.kura.cloudconnection.sparkplug.mqtt.provider.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.configuration.change.manager</artifactId>
                <version>${org.eclipse.kura.configuration.change.manager.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.container.orchestration.provider</artifactId>
                <version>${org.eclipse.kura.container.orchestration.provider.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.container.provider</artifactId>
                <version>${org.eclipse.kura.container.provider.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.core</artifactId>
                <version>${org.eclipse.kura.core.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.core.certificates</artifactId>
                <version>${org.eclipse.kura.core.certificates.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.core.cloud.factory</artifactId>
                <version>${org.eclipse.kura.core.cloud.factory.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.core.comm</artifactId>
                <version>${org.eclipse.kura.core.comm.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.core.configuration</artifactId>
                <version>${org.eclipse.kura.core.configuration.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.core.crypto</artifactId>
                <version>${org.eclipse.kura.core.crypto.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.core.deployment</artifactId>
                <version>${org.eclipse.kura.core.deployment.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.core.identity</artifactId>
                <version>${org.eclipse.kura.core.identity.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.core.inventory</artifactId>
                <version>${org.eclipse.kura.core.inventory.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.core.keystore</artifactId>
                <version>${org.eclipse.kura.core.keystore.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.core.net</artifactId>
                <version>${org.eclipse.kura.core.net.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.core.status</artifactId>
                <version>${org.eclipse.kura.core.status.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.core.system</artifactId>
                <version>${org.eclipse.kura.core.system.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.rest.tamper.detection.provider</artifactId>
                <version>${org.eclipse.kura.rest.tamper.detection.provider.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.db.h2db.provider</artifactId>
                <version>${org.eclipse.kura.db.h2db.provider.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.db.sqlite.provider</artifactId>
                <version>${org.eclipse.kura.db.sqlite.provider.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.deployment.agent</artifactId>
                <version>${org.eclipse.kura.deployment.agent.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.driver.ble.sensortag.provider</artifactId>
                <version>${org.eclipse.kura.driver.ble.sensortag.provider.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.driver.block</artifactId>
                <version>${org.eclipse.kura.driver.block.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.driver.gpio.provider</artifactId>
                <version>${org.eclipse.kura.driver.gpio.provider.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.driver.helper.provider</artifactId>
                <version>${org.eclipse.kura.driver.helper.provider.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.driver.opcua.provider</artifactId>
                <version>${org.eclipse.kura.driver.opcua.provider.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.driver.s7plc.provider</artifactId>
                <version>${org.eclipse.kura.driver.s7plc.provider.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.emulator</artifactId>
                <version>${org.eclipse.kura.emulator.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.emulator.clock</artifactId>
                <version>${org.eclipse.kura.emulator.clock.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.emulator.gpio</artifactId>
                <version>${org.eclipse.kura.emulator.gpio.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.emulator.net</artifactId>
                <version>${org.eclipse.kura.emulator.net.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.emulator.position</artifactId>
                <version>${org.eclipse.kura.emulator.position.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.emulator.usb</artifactId>
                <version>${org.eclipse.kura.emulator.usb.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.emulator.watchdog</artifactId>
                <version>${org.eclipse.kura.emulator.watchdog.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.event.publisher</artifactId>
                <version>${org.eclipse.kura.event.publisher.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.hook.file.move.provider</artifactId>
                <version>${org.eclipse.kura.hook.file.move.provider.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.http.server.manager</artifactId>
                <version>${org.eclipse.kura.http.server.manager.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.json.marshaller.unmarshaller.provider</artifactId>
                <version>${org.eclipse.kura.json.marshaller.unmarshaller.provider.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.linux.clock</artifactId>
                <version>${org.eclipse.kura.linux.clock.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.linux.gpio</artifactId>
                <version>${org.eclipse.kura.linux.gpio.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.linux.net</artifactId>
                <version>${org.eclipse.kura.linux.net.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.linux.systemd.provider</artifactId>
                <version>${org.eclipse.kura.linux.systemd.provider.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.linux.usb</artifactId>
                <version>${org.eclipse.kura.linux.usb.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.linux.usb.aarch64</artifactId>
                <version>${org.eclipse.kura.linux.usb.aarch64.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.linux.usb.x86_64</artifactId>
                <version>${org.eclipse.kura.linux.usb.x86_64.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.linux.watchdog</artifactId>
                <version>${org.eclipse.kura.linux.watchdog.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.log.filesystem.provider</artifactId>
                <version>${org.eclipse.kura.log.filesystem.provider.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.misc.cloudcat</artifactId>
                <version>${org.eclipse.kura.misc.cloudcat.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.net.admin.firewall</artifactId>
                <version>${org.eclipse.kura.net.admin.firewall.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.net.configuration</artifactId>
                <version>${org.eclipse.kura.net.configuration.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.network.threat.manager</artifactId>
                <version>${org.eclipse.kura.network.threat.manager.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.nm</artifactId>
                <version>${org.eclipse.kura.nm.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.protocol.modbus</artifactId>
                <version>${org.eclipse.kura.protocol.modbus.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.request.handler.jaxrs</artifactId>
                <version>${org.eclipse.kura.request.handler.jaxrs.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.rest.cloudconnection.provider</artifactId>
                <version>${org.eclipse.kura.rest.cloudconnection.provider.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.rest.configuration.provider</artifactId>
                <version>${org.eclipse.kura.rest.configuration.provider.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.rest.identity.provider</artifactId>
                <version>${org.eclipse.kura.rest.identity.provider.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.rest.inventory.provider</artifactId>
                <version>${org.eclipse.kura.rest.inventory.provider.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.rest.keystore.provider</artifactId>
                <version>${org.eclipse.kura.rest.keystore.provider.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.rest.network.configuration.provider</artifactId>
                <version>${org.eclipse.kura.rest.network.configuration.provider.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.rest.network.status.provider</artifactId>
                <version>${org.eclipse.kura.rest.network.status.provider.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.rest.packages.provider</artifactId>
                <version>${org.eclipse.kura.rest.packages.provider.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.rest.provider</artifactId>
                <version>${org.eclipse.kura.rest.provider.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.rest.security.provider</artifactId>
                <version>${org.eclipse.kura.rest.security.provider.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.rest.service.listing.provider</artifactId>
                <version>${org.eclipse.kura.rest.service.listing.provider.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.rest.system.provider</artifactId>
                <version>${org.eclipse.kura.rest.system.provider.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.stress</artifactId>
                <version>${org.eclipse.kura.stress.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.useradmin.store</artifactId>
                <version>${org.eclipse.kura.useradmin.store.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.util</artifactId>
                <version>${org.eclipse.kura.util.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.wire.camel</artifactId>
                <version>${org.eclipse.kura.wire.camel.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.xml.marshaller.unmarshaller.provider</artifactId>
                <version>${org.eclipse.kura.xml.marshaller.unmarshaller.provider.version}</version>
            </dependency>
            <!-- test-util -->
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.core.testutil</artifactId>
                <version>${org.eclipse.kura.core.testutil.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.test</artifactId>
                <version>${org.eclipse.kura.test.version}</version>
            </dependency>
            <dependency>
                <groupId>org.eclipse.kura</groupId>
                <artifactId>org.eclipse.kura.util.test.driver</artifactId>
                <version>${org.eclipse.kura.util.test.driver.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.ai.triton.server</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.broker.artemis.core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.broker.artemis.simple.mqtt</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.broker.artemis.xml</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.camel</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.camel.cloud.factory</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.camel.xml</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.cloud.base.provider</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.cloudconnection.eclipseiot.mqtt.provider</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.cloudconnection.kapua.mqtt.provider</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.cloudconnection.raw.mqtt.provider</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.cloudconnection.sparkplug.mqtt.provider</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.configuration.change.manager</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.container.orchestration.provider</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.container.provider</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.core.certificates</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.core.cloud.factory</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.core.comm</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.core.configuration</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.core.crypto</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.core.deployment</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.core.identity</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.core.inventory</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.core.keystore</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.core.net</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.core.status</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.core.system</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.rest.tamper.detection.provider</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.db.h2db.provider</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.db.sqlite.provider</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.deployment.agent</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.driver.ble.sensortag.provider</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.driver.block</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.driver.gpio.provider</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.driver.helper.provider</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.driver.opcua.provider</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.driver.s7plc.provider</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.emulator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.emulator.clock</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.emulator.gpio</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.emulator.net</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.emulator.position</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.emulator.usb</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.emulator.watchdog</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.event.publisher</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.hook.file.move.provider</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.http.server.manager</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.json.marshaller.unmarshaller.provider</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.linux.clock</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.linux.gpio</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.linux.net</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.linux.systemd.provider</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.linux.usb</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.linux.usb.aarch64</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.linux.usb.x86_64</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.linux.watchdog</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.log.filesystem.provider</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.misc.cloudcat</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.net.admin.firewall</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.net.configuration</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.network.threat.manager</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.nm</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.protocol.modbus</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.request.handler.jaxrs</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.rest.cloudconnection.provider</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.rest.configuration.provider</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.rest.identity.provider</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.rest.inventory.provider</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.rest.keystore.provider</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.rest.network.configuration.provider</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.rest.network.status.provider</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.rest.packages.provider</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.rest.provider</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.rest.security.provider</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.rest.service.listing.provider</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.rest.system.provider</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.stress</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.useradmin.store</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.util</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.wire.camel</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.xml.marshaller.unmarshaller.provider</artifactId>
        </dependency>
        <!-- test-util -->
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.core.testutil</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.test</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.util.test.driver</artifactId>
        </dependency>
    </dependencies>

</project>