---
exclusions:
  - "**/.git/**/*"
  - "**/.github/**/*"
  - "**/target/**/*"
  - "**/RELEASE_INFO/**/*"
  - "**/.settings/**/*"
  - "**/.classpath"
  - "**/.project"
  - "./kura/tools/archetype/example/src/main/resources/**/*"

tasks:
  - selector:
      and:
        - snapshot
        - not:
            artifact_id: "moquette-broker"
    actions:
      - print
      - transform_version:
        - add_major: 1
        - set_minor: 0
        - set_patch: 0
