/**
 * Apache Camel routers for the use inside of Kura
 * <p>
 * This package provides a set of Camel routers for the use inside of Kura. It
 * is preferred to use at least the {@link org.eclipse.kura.camel.router.AbstractCamelRouter} as a base class
 * instead of using Camel directly.
 * </p>
 * <p>
 * The following base classes are provided by this package:
 * </p>
 * <dl>
 * <dt>{@link AbstractCamelRouter}</dt>
 * <dd>This provides a thin wrapper around the original Camel context, enabling options are best the use
 * of Camel inside Kura</dd>
 * <dt>{@link AbstractXmlCamelRouter}</dt>
 * <dd>This base class can be used to create you own OSGi service which is based on camel but does not make use
 * of the Kura or OSGi configuration mechanism but allows for an easier implementation of XML base Camel routers.
 * The XML content is generated by that component itself.</dd>
 * <dt>{@link AbstractXmlCamelComponent}</dt>
 * <dd>This is an XML based Camel router which aids in creating an OSGi service component. The XML content is
 * applied externally.</dd>
 * </dl>
 * <p>
 * There is also a ready-to-run Kura component which can simply be configured with XML data using the Kura
 * configuration mechanism. This component is not part of this package since it automatically activates. It is
 * located in the bundle {@code org.eclipse.kura.camel.xml}.
 * </p>
 */
package org.eclipse.kura.camel.router;