/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 * Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.linux.position.options;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import java.util.HashMap;
import java.util.Map;

import org.junit.Test;

public class PositionServiceOptionsEqualityTest {

    private final Map<String, Object> firstProperties = staticPositionProperties();
    private final Map<String, Object> secondProperties = staticPositionProperties();
    private PositionServiceOptions firstOptions;
    private PositionServiceOptions secondOptions;

    /*
     * Scenarios
     */

    @Test
    public void sameConfigurationWithDistinctStringInstancesIsEqual() {
        givenGnssType(this.firstProperties, new String("Gps"));
        givenGnssType(this.secondProperties, new String("Gps"));

        whenOptionsAreCreated();

        thenOptionsAreEqual();
        thenHashCodesAreEqual();
    }

    @Test
    public void differentGnssTypeIsNotEqual() {
        givenGnssType(this.firstProperties, "Gps");
        givenGnssType(this.secondProperties, "Glonass");

        whenOptionsAreCreated();

        thenOptionsAreNotEqual();
    }

    @Test
    public void differentLatitudeIsNotEqual() {
        givenLatitude(this.firstProperties, 45.0);
        givenLatitude(this.secondProperties, 45.000001);

        whenOptionsAreCreated();

        thenOptionsAreNotEqual();
    }

    @Test
    public void notANumberLatitudeIsEqualToItself() {
        givenLatitude(this.firstProperties, Double.NaN);
        givenLatitude(this.secondProperties, Double.NaN);

        whenOptionsAreCreated();

        thenOptionsAreEqual();
        thenHashCodesAreEqual();
    }

    /*
     * Steps
     */

    private void givenGnssType(Map<String, Object> properties, String gnssType) {
        properties.put("gnss.type", gnssType);
    }

    private void givenLatitude(Map<String, Object> properties, double latitude) {
        properties.put("latitude", latitude);
    }

    private void whenOptionsAreCreated() {
        this.firstOptions = new PositionServiceOptions(this.firstProperties);
        this.secondOptions = new PositionServiceOptions(this.secondProperties);
    }

    private void thenOptionsAreEqual() {
        assertTrue(this.firstOptions.equals(this.secondOptions));
        assertTrue(this.secondOptions.equals(this.firstOptions));
    }

    private void thenOptionsAreNotEqual() {
        assertFalse(this.firstOptions.equals(this.secondOptions));
    }

    private void thenHashCodesAreEqual() {
        assertEquals(this.firstOptions.hashCode(), this.secondOptions.hashCode());
    }

    /*
     * Utilities
     */

    private static Map<String, Object> staticPositionProperties() {
        final Map<String, Object> properties = new HashMap<>();
        properties.put("enabled", true);
        properties.put("static", true);
        properties.put("latitude", 45.0);
        properties.put("longitude", 11.0);
        properties.put("altitude", 100.0);
        return properties;
    }
}
