/*******************************************************************************
 * Copyright (c) 2023, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.rest.system.dto;

import java.util.ArrayList;
import java.util.List;

import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Schema;

public class FilterDTO {

    @ArraySchema(arraySchema = @Schema(description = "Property names for framework and Kura filters. Omitted means an empty list."))
    private List<String> names;
    @ArraySchema(arraySchema = @Schema(description = "Group names for the extended-properties filter. Omitted means an empty list."))
    private List<String> groupNames;

    public FilterDTO() {
        this.names = new ArrayList<>();
        this.groupNames = new ArrayList<>();
    }

    public List<String> getNames() {
        return this.names;
    }

    public List<String> getGroupNames() {
        return this.groupNames;
    }

}
