/*******************************************************************************
 * Copyright (c) 2024, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.identity;

import java.time.Duration;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.stream.Collectors;

import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.KuraException;
import org.eclipse.kura.audit.AuditContext;
import org.eclipse.kura.configuration.ComponentConfiguration;
import org.eclipse.kura.configuration.ConfigurationService;
import org.eclipse.kura.core.identity.store.TemporaryIdentityStore;
import org.eclipse.kura.core.identity.store.TemporaryIdentityStoreAdapter;
import org.eclipse.kura.core.identity.store.UserAdminIdentityStore;
import org.eclipse.kura.crypto.CryptoService;
import org.eclipse.kura.identity.AdditionalConfigurations;
import org.eclipse.kura.identity.AssignedPermissions;
import org.eclipse.kura.identity.IdentityConfiguration;
import org.eclipse.kura.identity.IdentityConfigurationComponent;
import org.eclipse.kura.identity.IdentityService;
import org.eclipse.kura.identity.PasswordConfiguration;
import org.eclipse.kura.identity.PasswordHash;
import org.eclipse.kura.identity.PasswordStrengthVerificationService;
import org.eclipse.kura.identity.Permission;
import org.eclipse.kura.identity.configuration.extension.IdentityConfigurationExtension;
import org.eclipse.kura.util.useradmin.UserAdminHelper;
import org.eclipse.kura.util.useradmin.UserAdminHelper.AuthenticationException;
import org.osgi.service.useradmin.UserAdmin;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings("restriction")
public class IdentityServiceImpl implements IdentityService {

    private static final String IDENTITY_SERVICE_FAILURE_FORMAT_STRING = "{} IdentityService - Failure - {}";
    private static final String IDENTITY_SERVICE_SUCCESS_FORMAT_STRING = "{} IdentityService - Success - {}";

    private static final Logger auditLogger = LoggerFactory.getLogger("AuditLogger");
    private static final Logger logger = LoggerFactory.getLogger(IdentityServiceImpl.class);

    public static final String PASSWORD_PROPERTY = "kura.password";
    public static final String KURA_NEED_PASSWORD_CHANGE = "kura.need.password.change";

    private UserAdmin userAdmin;
    private CryptoService cryptoService;
    private UserAdminHelper userAdminHelper;
    private PasswordStrengthVerificationService passwordStrengthVerificationService;

    private final Map<String, IdentityConfigurationExtension> extensions = new ConcurrentHashMap<>();
    private final TemporaryIdentityStore temporaryStore = new TemporaryIdentityStore();
    private TemporaryIdentityStoreAdapter temporaryIdentityStore;
    private UserAdminIdentityStore userAdminIdentityStore;

    public void setCryptoService(final CryptoService cryptoService) {
        this.cryptoService = cryptoService;
    }

    public void setUserAdmin(final UserAdmin userAdmin) {
        this.userAdmin = userAdmin;
    }

    public void setPasswordStrengthVerificationService(
            final PasswordStrengthVerificationService passwordStrengthVerificationService) {
        this.passwordStrengthVerificationService = passwordStrengthVerificationService;
    }

    public synchronized void setIdentityConfigurationExtension(
            final IdentityConfigurationExtension identityConfigurationExtension, final Map<String, Object> properties) {
        final Object kuraServicePid = properties.get(ConfigurationService.KURA_SERVICE_PID);

        if (!(kuraServicePid instanceof String)) {
            logger.warn("found {} registered without setting the {} service property, service will not be tracked",
                    IdentityConfigurationExtension.class.getSimpleName(), ConfigurationService.KURA_SERVICE_PID);
            return;
        }

        this.extensions.put((String) kuraServicePid, identityConfigurationExtension);
    }

    public synchronized void unsetIdentityConfigurationExtension(
            final IdentityConfigurationExtension identityConfigurationExtension, final Map<String, Object> properties) {
        final Object kuraServicePid = properties.get(ConfigurationService.KURA_SERVICE_PID);

        if (kuraServicePid instanceof String) {
            this.extensions.remove(kuraServicePid);
        }
    }

    public void activate() {
        this.userAdminHelper = new UserAdminHelper(this.userAdmin, this.cryptoService);
        this.temporaryIdentityStore = new TemporaryIdentityStoreAdapter(this.temporaryStore,
                this.passwordStrengthVerificationService, this::computePasswordHash);
        this.userAdminIdentityStore = new UserAdminIdentityStore(this.userAdminHelper, this.extensions, logger,
                this::computePasswordHash);
    }

    public void deactivate() {
        this.temporaryStore.shutdown();
    }

    @Override
    public synchronized boolean createIdentity(final String name) throws KuraException {
        if (this.userAdminHelper.getUser(name).isPresent()) {
            return false;
        }

        audit(() -> {
            ValidationUtil.validateNewIdentityName(name);

            this.userAdminHelper.createUser(name);
        }, "Create identity " + name);

        return true;
    }

    @Override
    public synchronized boolean deleteIdentity(final String name) throws KuraException {
        if (this.temporaryIdentityStore.exists(name)) {
            return audit(() -> this.temporaryIdentityStore.deleteIdentity(name), "Delete temporary identity " + name);
        }

        if (this.userAdminIdentityStore.exists(name)) {
            return audit(() -> this.userAdminIdentityStore.deleteIdentity(name), "Delete identity " + name);
        }

        return false;
    }

    @Override
    public synchronized List<IdentityConfiguration> getIdentitiesConfiguration(
            Set<Class<? extends IdentityConfigurationComponent>> componentsToReturn) throws KuraException {
        final List<IdentityConfiguration> result = new ArrayList<>();

        result.addAll(this.userAdminIdentityStore.getIdentitiesConfiguration(componentsToReturn));
        result.addAll(this.temporaryIdentityStore.getIdentitiesConfiguration(componentsToReturn));

        return result;
    }

    @Override
    public synchronized Optional<IdentityConfiguration> getIdentityConfiguration(String name,
            Set<Class<? extends IdentityConfigurationComponent>> componentsToReturn) throws KuraException {

        final Optional<IdentityConfiguration> temporaryIdentity = this.temporaryIdentityStore
                .getIdentityConfiguration(name, componentsToReturn);
        if (temporaryIdentity.isPresent()) {
            return temporaryIdentity;
        }

        return this.userAdminIdentityStore.getIdentityConfiguration(name, componentsToReturn);
    }

    @Override
    public IdentityConfiguration getIdentityDefaultConfiguration(String identityName,
            Set<Class<? extends IdentityConfigurationComponent>> componentsToReturn) throws KuraException {
        final List<IdentityConfigurationComponent> components = new ArrayList<>();

        if (componentsToReturn.contains(PasswordConfiguration.class)) {
            components.add(new PasswordConfiguration(false, false, Optional.empty(), Optional.empty()));
        }

        if (componentsToReturn.contains(AssignedPermissions.class)) {
            components.add(new AssignedPermissions(Collections.emptySet()));
        }

        if (componentsToReturn.contains(AdditionalConfigurations.class)) {
            components.add(getAdditionalConfigurationsDefaults(identityName));
        }

        return new IdentityConfiguration(identityName, components);
    }

    @Override
    public void validateIdentityConfiguration(final IdentityConfiguration identityConfiguration) throws KuraException {
        audit(() -> {
            final Optional<PasswordConfiguration> passwordCofiguration = identityConfiguration
                    .getComponent(PasswordConfiguration.class);

            if (passwordCofiguration.isPresent()) {
                validatePasswordConfiguration(identityConfiguration, passwordCofiguration.get());
            }

            final Optional<AdditionalConfigurations> additionalConfigurations = identityConfiguration
                    .getComponent(AdditionalConfigurations.class);

            if (additionalConfigurations.isPresent()) {
                validateAdditionalConfigurations(identityConfiguration, additionalConfigurations.get());
            }

            final Optional<AssignedPermissions> assignedPermissions = identityConfiguration
                    .getComponent(AssignedPermissions.class);

            if (assignedPermissions.isPresent()) {
                validateAssignedPermissions(assignedPermissions.get());
            }

        }, "Validate configuration for identity" + identityConfiguration.getName());

    }

    @Override
    public synchronized void updateIdentityConfiguration(final IdentityConfiguration identityConfiguration)
            throws KuraException {

        audit(() -> {
            if (this.temporaryIdentityStore.exists(identityConfiguration.getName())) {
                validateIdentityConfiguration(identityConfiguration);
                this.temporaryIdentityStore.updateIdentityConfiguration(identityConfiguration);
                return;
            }

            if (!this.userAdminIdentityStore.exists(identityConfiguration.getName())) {
                throw new KuraException(KuraErrorCode.INVALID_PARAMETER, "Identity does not exist");
            }

            validateIdentityConfiguration(identityConfiguration);

            this.userAdminIdentityStore.updateIdentityConfiguration(identityConfiguration);
        }, "Update configuration for identity " + identityConfiguration.getName());

    }

    @Override
    public synchronized boolean createPermission(final Permission permission) throws KuraException {
        if (this.userAdminHelper.getPermission(permission.getName()).isPresent()) {
            return false;
        }

        ValidationUtil.validateNewPermissionName(permission.getName());

        this.userAdminHelper.getOrCreatePermission(permission.getName());
        return true;
    }

    @Override
    public synchronized boolean deletePermission(final Permission permission) throws KuraException {
        if (!this.userAdminHelper.getPermission(permission.getName()).isPresent()) {
            return false;
        }

        this.userAdminHelper.deletePremission(permission.getName());
        return true;
    }

    @Override
    public synchronized Set<Permission> getPermissions() {
        return new UserAdminHelper(this.userAdmin, this.cryptoService).getDefinedPermissions().stream()
                .map(Permission::new).collect(Collectors.toSet());
    }

    @Override
    public PasswordHash computePasswordHash(final char[] password) throws KuraException {
        try {
            final String result = this.cryptoService.sha256Hash(new String(password));

            for (int i = 0; i < password.length; i++) {
                password[i] = ' ';
            }

            return new PasswordHashImpl(result);
        } catch (Exception e) {
            throw new KuraException(KuraErrorCode.SERVICE_UNAVAILABLE, "failed to compute password hash");
        }
    }

    @Override
    public void checkPassword(String identityName, char[] password) throws KuraException {
        final PasswordConfiguration passwordConfiguration = getIdentityConfiguration(identityName,
                Collections.singleton(PasswordConfiguration.class))
                        .flatMap(i -> i.getComponent(PasswordConfiguration.class))
                        .orElseThrow(() -> new KuraException(KuraErrorCode.SECURITY_EXCEPTION));

        if (!passwordConfiguration.isPasswordAuthEnabled() || !Objects.equals(passwordConfiguration.getPasswordHash(),
                Optional.of(computePasswordHash(password)))) {
            throw new KuraException(KuraErrorCode.SECURITY_EXCEPTION,
                    "Password authentication is not enabled or password does not match");
        }
    }

    @Override
    public void checkPermission(String identityName, Permission permission) throws KuraException {
        final Optional<IdentityConfiguration> temporaryIdentity = this.temporaryStore.getIdentity(identityName);
        if (temporaryIdentity.isPresent()) {
            final Optional<AssignedPermissions> assignedPermissions = temporaryIdentity.get()
                    .getComponent(AssignedPermissions.class);

            if (!assignedPermissions.isPresent()) {
                throw new KuraException(KuraErrorCode.SECURITY_EXCEPTION,
                        "The specified permission is not assigned to the given identity");
            }

            final boolean hasPermission = assignedPermissions.get().getPermissions().stream()
                    .anyMatch(p -> Objects.equals(p.getName(), permission.getName()));
            if (!hasPermission) {
                throw new KuraException(KuraErrorCode.SECURITY_EXCEPTION,
                        "The specified permission is not assigned to the given identity");
            }

            return;
        }

        try {
            this.userAdminHelper.requirePermissions(identityName, permission.getName());
        } catch (AuthenticationException e) {
            throw new KuraException(KuraErrorCode.SECURITY_EXCEPTION,
                    "The specified permission is not assigned to the given identity");
        }
    }

    private AdditionalConfigurations getAdditionalConfigurationsDefaults(final String name) {
        final List<ComponentConfiguration> additionalConfigurations = new ArrayList<>();

        for (final IdentityConfigurationExtension extension : this.extensions.values()) {
            try {
                extension.getDefaultConfiguration(name).ifPresent(additionalConfigurations::add);
            } catch (final Exception e) {
                logger.warn("Failed to get identity additional configuration defaults from extension", e);
            }
        }

        return new AdditionalConfigurations(additionalConfigurations);
    }


    private void validatePasswordConfiguration(final IdentityConfiguration identityConfiguration,
            final PasswordConfiguration passwordCofiguration) throws KuraException {
        if (!passwordCofiguration.isPasswordAuthEnabled()) {
            return;
        }

        final Optional<char[]> newPassword = passwordCofiguration.getNewPassword();

        if (newPassword.isPresent()) {

            ValidationUtil.validateNewPassword(identityConfiguration.getName(), newPassword.get(),
                    passwordStrengthVerificationService);

        } else {
            final boolean hasPersistedPasswordHash = this.userAdminHelper.getUser(identityConfiguration.getName())
                    .filter(u -> u.getCredentials().get(PASSWORD_PROPERTY) != null).isPresent();
            final boolean hasTemporaryPasswordHash = this.temporaryStore.getIdentity(identityConfiguration.getName())
                    .flatMap(config -> config.getComponent(PasswordConfiguration.class))
                    .flatMap(PasswordConfiguration::getPasswordHash)
                    .isPresent();
            if (!hasPersistedPasswordHash && !hasTemporaryPasswordHash) {
                throw new KuraException(KuraErrorCode.INVALID_PARAMETER,
                        "Password authentication is enabled but no password has been provided or is currently assigned");
            }
        }
    }

    private void validateAssignedPermissions(final AssignedPermissions assignedPermissions) throws KuraException {
        for (final Permission permission : assignedPermissions.getPermissions()) {
            if (!this.userAdminHelper.getPermission(permission.getName()).isPresent()) {
                throw new KuraException(KuraErrorCode.INVALID_PARAMETER, "Permission does not exist");
            }
        }
    }

    private void validateAdditionalConfigurations(final IdentityConfiguration identityConfiguration,
            final AdditionalConfigurations additionalConfigurations) throws KuraException {
        for (final ComponentConfiguration config : additionalConfigurations.getConfigurations()) {

            final Optional<IdentityConfigurationExtension> extension = Optional
                    .ofNullable(this.extensions.get(config.getPid()));

            if (!extension.isPresent()) {
                throw new KuraException(KuraErrorCode.INVALID_PARAMETER,
                        "Configuration extension pid is not registered");
            }

            extension.get().validateConfiguration(identityConfiguration.getName(), config);

        }
    }

    // New unified temporary identity methods (IdentityService interface)

    @Override
    public synchronized void createTemporaryIdentity(IdentityConfiguration configuration,
            Duration lifetime) throws KuraException {

        final String identityName = configuration.getName();

        // Check if identity already exists (temporary or regular)
        if (this.temporaryStore.exists(identityName)) {
            throw new KuraException(KuraErrorCode.INVALID_PARAMETER,
                    "A temporary identity with name '" + identityName + "' already exists");
        }
        if (this.userAdminHelper.getUser(identityName).isPresent()) {
            throw new KuraException(KuraErrorCode.INVALID_PARAMETER,
                    "An identity with name '" + identityName + "' already exists");
        }

        audit(() -> {
            ValidationUtil.validateNewIdentityName(identityName);

            if (lifetime == null || lifetime.isZero() || lifetime.isNegative()) {
                throw new KuraException(KuraErrorCode.INVALID_PARAMETER,
                        "Temporary identity lifetime must be positive");
            }

            validateIdentityConfiguration(configuration);

            // Process the configuration to hash passwords before storage
            this.temporaryIdentityStore.createIdentity(configuration, lifetime);

        }, "Create temporary identity " + identityName);
    }

    public static <T, E extends Throwable> T audit(final FallibleSupplier<T, E> task, final String message) throws E {
        try {
            final T result = task.get();
            auditLogger.info(IDENTITY_SERVICE_SUCCESS_FORMAT_STRING, AuditContext.currentOrInternal(), message);
            return result;
        } catch (final Exception e) {
            auditLogger.warn(IDENTITY_SERVICE_FAILURE_FORMAT_STRING, AuditContext.currentOrInternal(), message);
            throw e;
        }
    }

    public static <E extends Throwable> void audit(final FallibleTask<E> task, final String message) throws E {
        try {
            task.run();
            auditLogger.info(IDENTITY_SERVICE_SUCCESS_FORMAT_STRING, AuditContext.currentOrInternal(), message);
        } catch (final Exception e) {
            auditLogger.warn(IDENTITY_SERVICE_FAILURE_FORMAT_STRING, AuditContext.currentOrInternal(), message);
            throw e;
        }
    }

    public interface FallibleSupplier<T, E extends Throwable> {

        public T get() throws E;
    }

    public interface FallibleTask<E extends Throwable> {

        public void run() throws E;
    }

}
