/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.core.identity;

import java.nio.charset.StandardCharsets;
import java.security.KeyStore.Entry;
import java.security.KeyStore.PrivateKeyEntry;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.security.Signature;
import java.time.Instant;
import java.util.Base64;
import java.util.Map;
import java.util.Optional;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicBoolean;

import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.KuraException;
import org.eclipse.kura.identity.IdentityService;
import org.eclipse.kura.identity.IdentityTokenService;
import org.eclipse.kura.identity.TokenPair;
import org.eclipse.kura.identity.VerifiedAccessToken;
import org.eclipse.kura.security.keystore.KeystoreService;
import org.osgi.service.component.annotations.Activate;
import org.osgi.service.component.annotations.Component;
import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.gson.Gson;
import com.google.gson.JsonObject;

@Component(immediate = true, service = IdentityTokenService.class)
public class IdentityTokenServiceImpl implements IdentityTokenService {

    private static final Logger logger = LoggerFactory.getLogger(IdentityTokenServiceImpl.class);

    private static final String TOKEN_USE_ACCESS = "access";
    private static final String TOKEN_USE_REFRESH = "refresh";
    private static final String JWT_ALG = "RS256";
    private static final String JWT_TYP = "JWT";
    private static final String ISSUER = "kura";
    private static final String AUDIENCE = "kura-rest";
    private static final String DEFAULT_KEY_ALIAS = "kura.jwt.active";
    private static final long ACCESS_TTL_SECONDS = 300;
    private static final long REFRESH_TTL_SECONDS = 24 * 60 * 60;
    private static final long CLOCK_SKEW_SECONDS = 5;

    private final Gson gson = new Gson();
    private final Base64.Encoder base64UrlEncoder = Base64.getUrlEncoder().withoutPadding();
    private final Base64.Decoder base64UrlDecoder = Base64.getUrlDecoder();
    private final Map<String, RefreshTokenRecord> refreshTokens = new ConcurrentHashMap<>();
    private final Map<String, Long> revokedFamilies = new ConcurrentHashMap<>();

    private IdentityService identityService;
    private KeystoreService keystoreService;

    @Reference
    public void setIdentityService(final IdentityService identityService) {
        this.identityService = identityService;
    }

    @Reference
    public void setKeystoreService(final KeystoreService keystoreService) {
        this.keystoreService = keystoreService;
    }

    @Activate
    public void activate() throws KuraException {
        ensureSigningKey(DEFAULT_KEY_ALIAS);
    }

    @Deactivate
    public void deactivate() {
        this.refreshTokens.clear();
        this.revokedFamilies.clear();
    }

    @Override
    public TokenPair issueTokenPair(final String identityName) throws KuraException {
        cleanupExpiredRefreshTokens();

        final long identityRevision = this.identityService.getIdentityRevision(identityName);
        final String familyId = UUID.randomUUID().toString();

        return issueTokenPair(identityName, identityRevision, familyId);
    }

    @Override
    public TokenPair refreshTokenPair(final String refreshToken) throws KuraException {
        cleanupExpiredRefreshTokens();

        final DecodedJwt decoded = decodeAndVerify(refreshToken);
        if (!TOKEN_USE_REFRESH.equals(payloadValue(decoded.payload, "token_use"))) {
            throw new KuraException(KuraErrorCode.SECURITY_EXCEPTION, "Invalid token use");
        }

        final String tokenId = payloadValue(decoded.payload, "jti");
        final String familyId = payloadValue(decoded.payload, "sid");
        final String identityName = payloadValue(decoded.payload, "sub");
        final long revision = payloadLongValue(decoded.payload, "rev");

        final RefreshTokenRecord existingRecord = this.refreshTokens.get(tokenId);
        if (existingRecord == null || isExpired(existingRecord.expiresAt)
                || !existingRecord.isUsed.compareAndSet(false, true)) {
            throw new KuraException(KuraErrorCode.SECURITY_EXCEPTION, "Refresh token has already been consumed");
        }

        if (this.revokedFamilies.containsKey(familyId)) {
            throw new KuraException(KuraErrorCode.SECURITY_EXCEPTION, "Token family revoked");
        }

        final long currentRevision = this.identityService.getIdentityRevision(identityName);
        if (revision != currentRevision) {
            revokeTokenFamilyWithExpiry(familyId);
            throw new KuraException(KuraErrorCode.SECURITY_EXCEPTION, "Token revision does not match current identity");
        }

        return issueTokenPair(identityName, revision, familyId);
    }

    @Override
    public Optional<VerifiedAccessToken> verifyAccessToken(final String accessToken) {
        cleanupExpiredRefreshTokens();

        try {
            final DecodedJwt decoded = decodeAndVerify(accessToken);
            if (!TOKEN_USE_ACCESS.equals(payloadValue(decoded.payload, "token_use"))) {
                return Optional.empty();
            }

            final String identityName = payloadValue(decoded.payload, "sub");
            final long revision = payloadLongValue(decoded.payload, "rev");
            final String tokenId = payloadValue(decoded.payload, "jti");
            final String tokenFamilyId = payloadValue(decoded.payload, "sid");
            final long expiresAt = payloadLongValue(decoded.payload, "exp");

            if (this.revokedFamilies.containsKey(tokenFamilyId)) {
                return Optional.empty();
            }

            final long currentRevision = this.identityService.getIdentityRevision(identityName);
            if (revision != currentRevision) {
                revokeTokenFamilyWithExpiry(tokenFamilyId);
                return Optional.empty();
            }

            return Optional.of(new VerifiedAccessToken(identityName, tokenId, tokenFamilyId, expiresAt));
        } catch (final Exception e) {
            return Optional.empty();
        }
    }

    @Override
    public void revokeTokenFamily(final String tokenFamilyId) {
        revokeTokenFamilyWithExpiry(tokenFamilyId);
    }

    private TokenPair issueTokenPair(final String identityName, final long identityRevision, final String familyId)
            throws KuraException {
        final long now = Instant.now().getEpochSecond();
        final long accessExpiration = now + ACCESS_TTL_SECONDS;
        final long refreshExpiration = now + REFRESH_TTL_SECONDS;
        final String accessTokenId = UUID.randomUUID().toString();
        final String refreshTokenId = UUID.randomUUID().toString();

        final TokenTiming accessTiming = new TokenTiming(now, now, accessExpiration);
        final TokenTiming refreshTiming = new TokenTiming(now, now, refreshExpiration);

        final String accessToken = buildSignedToken(new TokenDescriptor(identityName, accessTokenId, familyId,
                identityRevision, accessTiming, TOKEN_USE_ACCESS));
        final String refreshToken = buildSignedToken(new TokenDescriptor(identityName, refreshTokenId, familyId,
                identityRevision, refreshTiming, TOKEN_USE_REFRESH));

        this.refreshTokens.put(refreshTokenId, new RefreshTokenRecord(refreshExpiration));

        return new TokenPair(accessToken, refreshToken, accessExpiration, refreshExpiration, familyId);
    }

    private String buildSignedToken(final TokenDescriptor descriptor) throws KuraException {
        final JsonObject header = new JsonObject();
        header.addProperty("alg", JWT_ALG);
        header.addProperty("typ", JWT_TYP);
        header.addProperty("kid", DEFAULT_KEY_ALIAS);

        final JsonObject payload = new JsonObject();
        payload.addProperty("iss", ISSUER);
        payload.addProperty("aud", AUDIENCE);
        payload.addProperty("sub", descriptor.subject);
        payload.addProperty("iat", descriptor.issuedAt);
        payload.addProperty("nbf", descriptor.notBefore);
        payload.addProperty("exp", descriptor.expiresAt);
        payload.addProperty("jti", descriptor.tokenId);
        payload.addProperty("sid", descriptor.familyId);
        payload.addProperty("rev", descriptor.revision);
        payload.addProperty("token_use", descriptor.tokenUse);

        final String encodedHeader = encodeJsonObject(header);
        final String encodedPayload = encodeJsonObject(payload);
        final String signingInput = encodedHeader + "." + encodedPayload;

        final String encodedSignature = sign(signingInput, getSigningPrivateKey(DEFAULT_KEY_ALIAS));
        return signingInput + "." + encodedSignature;
    }

    private DecodedJwt decodeAndVerify(final String token) throws KuraException {
        final String[] parts = token.split("\\.");
        if (parts.length != 3) {
            throw new KuraException(KuraErrorCode.SECURITY_EXCEPTION, "Malformed JWT");
        }

        final JsonObject header = parseJsonObject(parts[0]);
        final JsonObject payload = parseJsonObject(parts[1]);

        final String algorithm = payloadValue(header, "alg");
        if (!JWT_ALG.equals(algorithm)) {
            throw new KuraException(KuraErrorCode.SECURITY_EXCEPTION, "Unsupported JWT algorithm");
        }

        final String kid = payloadValue(header, "kid");
        final String signingInput = parts[0] + "." + parts[1];
        verifySignature(signingInput, parts[2], getVerificationPublicKey(kid));

        validateClaims(payload);

        return new DecodedJwt(payload);
    }

    private void validateClaims(final JsonObject payload) throws KuraException {
        final long now = Instant.now().getEpochSecond();
        final long exp = payloadLongValue(payload, "exp");
        final long nbf = payloadLongValue(payload, "nbf");
        final long iat = payloadLongValue(payload, "iat");

        if (isExpired(exp)) {
            throw new KuraException(KuraErrorCode.SECURITY_EXCEPTION, "Token expired");
        }

        if (nbf > now + CLOCK_SKEW_SECONDS) {
            throw new KuraException(KuraErrorCode.SECURITY_EXCEPTION, "Token cannot be used yet");
        }

        if (iat > now + CLOCK_SKEW_SECONDS) {
            throw new KuraException(KuraErrorCode.SECURITY_EXCEPTION, "Token issue time is in the future");
        }

        if (!ISSUER.equals(payloadValue(payload, "iss"))) {
            throw new KuraException(KuraErrorCode.SECURITY_EXCEPTION, "Invalid token issuer");
        }

        if (!AUDIENCE.equals(payloadValue(payload, "aud"))) {
            throw new KuraException(KuraErrorCode.SECURITY_EXCEPTION, "Invalid token audience");
        }
    }

    private String payloadValue(final JsonObject payload, final String key) throws KuraException {
        if (!payload.has(key) || payload.get(key).isJsonNull()) {
            throw new KuraException(KuraErrorCode.SECURITY_EXCEPTION, "Missing JWT claim: " + key);
        }
        return payload.get(key).getAsString();
    }

    private long payloadLongValue(final JsonObject payload, final String key) throws KuraException {
        if (!payload.has(key) || payload.get(key).isJsonNull()) {
            throw new KuraException(KuraErrorCode.SECURITY_EXCEPTION, "Missing JWT claim: " + key);
        }
        return payload.get(key).getAsLong();
    }

    private String encodeJsonObject(final JsonObject object) {
        return base64UrlEncoder.encodeToString(this.gson.toJson(object).getBytes(StandardCharsets.UTF_8));
    }

    private JsonObject parseJsonObject(final String encodedJson) {
        return this.gson.fromJson(new String(base64UrlDecoder.decode(encodedJson), StandardCharsets.UTF_8),
                JsonObject.class);
    }

    private String sign(final String signingInput, final PrivateKey privateKey) throws KuraException {
        try {
            final Signature signature = Signature.getInstance("SHA256withRSA");
            signature.initSign(privateKey);
            signature.update(signingInput.getBytes(StandardCharsets.UTF_8));
            return base64UrlEncoder.encodeToString(signature.sign());
        } catch (Exception e) {
            throw new KuraException(KuraErrorCode.SERVICE_UNAVAILABLE, "Failed to sign JWT");
        }
    }

    private void verifySignature(final String signingInput, final String encodedSignature, final PublicKey publicKey)
            throws KuraException {
        try {
            final Signature signature = Signature.getInstance("SHA256withRSA");
            signature.initVerify(publicKey);
            signature.update(signingInput.getBytes(StandardCharsets.UTF_8));
            if (!signature.verify(base64UrlDecoder.decode(encodedSignature))) {
                throw new KuraException(KuraErrorCode.SECURITY_EXCEPTION, "Invalid token signature");
            }
        } catch (KuraException e) {
            throw e;
        } catch (Exception e) {
            throw new KuraException(KuraErrorCode.SECURITY_EXCEPTION, "Failed to verify token signature");
        }
    }

    private PrivateKey getSigningPrivateKey(final String keyAlias) throws KuraException {
        final Entry entry = this.keystoreService.getEntry(keyAlias);
        if (!(entry instanceof PrivateKeyEntry)) {
            throw new KuraException(KuraErrorCode.SERVICE_UNAVAILABLE, "JWT signing key is unavailable");
        }

        return ((PrivateKeyEntry) entry).getPrivateKey();
    }

    private PublicKey getVerificationPublicKey(final String keyAlias) throws KuraException {
        final Entry entry = this.keystoreService.getEntry(keyAlias);
        if (!(entry instanceof PrivateKeyEntry)) {
            throw new KuraException(KuraErrorCode.SECURITY_EXCEPTION, "JWT verification key is unavailable");
        }

        return ((PrivateKeyEntry) entry).getCertificate().getPublicKey();
    }

    private void ensureSigningKey(final String keyAlias) throws KuraException {
        try {
            final Entry existing = this.keystoreService.getEntry(keyAlias);
            if (existing instanceof PrivateKeyEntry) {
                return;
            }
        } catch (KuraException e) {
            logger.info("JWT signing key alias {} not present, creating a new keypair", keyAlias);
        }

        this.keystoreService.createKeyPair(keyAlias, "RSA", 2048, "SHA256withRSA", "CN=Kura JWT");
    }

    private void cleanupExpiredRefreshTokens() {
        final long now = Instant.now().getEpochSecond();
        this.refreshTokens.entrySet().removeIf(entry -> entry.getValue().expiresAt + CLOCK_SKEW_SECONDS < now);
        this.revokedFamilies.entrySet().removeIf(entry -> entry.getValue() + CLOCK_SKEW_SECONDS < now);
    }

    private void revokeTokenFamilyWithExpiry(final String familyId) {
        this.revokedFamilies.put(familyId, Instant.now().getEpochSecond() + REFRESH_TTL_SECONDS);
    }

    private boolean isExpired(final long epochSeconds) {
        return epochSeconds + CLOCK_SKEW_SECONDS < Instant.now().getEpochSecond();
    }

    private static final class DecodedJwt {
        private final JsonObject payload;

        private DecodedJwt(final JsonObject payload) {
            this.payload = payload;
        }
    }

    private static final class RefreshTokenRecord {
        private final long expiresAt;
        private final AtomicBoolean isUsed = new AtomicBoolean(false);

        private RefreshTokenRecord(final long expiresAt) {
            this.expiresAt = expiresAt;
        }
    }

    private static final class TokenDescriptor {
        private final String subject;
        private final String tokenId;
        private final String familyId;
        private final long revision;
        private final long issuedAt;
        private final long notBefore;
        private final long expiresAt;
        private final String tokenUse;

        private TokenDescriptor(final String subject, final String tokenId, final String familyId, final long revision,
                final TokenTiming timing, final String tokenUse) {
            this.subject = subject;
            this.tokenId = tokenId;
            this.familyId = familyId;
            this.revision = revision;
            this.issuedAt = timing.issuedAt;
            this.notBefore = timing.notBefore;
            this.expiresAt = timing.expiresAt;
            this.tokenUse = tokenUse;
        }
    }

    private static final class TokenTiming {
        private final long issuedAt;
        private final long notBefore;
        private final long expiresAt;

        private TokenTiming(final long issuedAt, final long notBefore, final long expiresAt) {
            this.issuedAt = issuedAt;
            this.notBefore = notBefore;
            this.expiresAt = expiresAt;
        }
    }
}
