/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 * Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.util.store.listener;

import static org.junit.Assert.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.lang.reflect.Field;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.TimeUnit;

import org.eclipse.kura.connection.listener.ConnectionListener;
import org.junit.Test;

public class ConnectionListenerManagerShutdownTest {

    private final ConnectionListenerManager manager = new ConnectionListenerManager();
    private final CountDownLatch slowListenerStarted = new CountDownLatch(1);
    private ExecutorService dispatchExecutor;
    private volatile boolean slowListenerCompleted;

    @Test
    public void shutdownCompletesPendingDispatches() throws Exception {
        givenSlowListener();
        givenConnectedEventDispatched();

        whenShutdown();

        thenSlowListenerCompleted();
    }

    @Test
    public void shutdownReturnsWhenDispatchExecutorDoesNotTerminate() throws Exception {
        givenDispatchExecutorThatDoesNotTerminate();

        whenShutdown();

        thenDispatchExecutorWasShutDownAndAwaited();
    }

    /*
     * Steps
     */

    private void givenSlowListener() {
        this.manager.add(new ConnectionListener() {

            @Override
            public void connected() {
                ConnectionListenerManagerShutdownTest.this.slowListenerStarted.countDown();
                try {
                    Thread.sleep(200);
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                    return;
                }
                ConnectionListenerManagerShutdownTest.this.slowListenerCompleted = true;
            }

            @Override
            public void disconnected() {
                // not used by these scenarios
            }
        });
    }

    private void givenConnectedEventDispatched() throws InterruptedException {
        this.manager.dispatchConnected();
        assertTrue(this.slowListenerStarted.await(5, TimeUnit.SECONDS));
    }

    private void givenDispatchExecutorThatDoesNotTerminate() throws Exception {
        this.dispatchExecutor = mock(ExecutorService.class);
        when(this.dispatchExecutor.awaitTermination(1, TimeUnit.MINUTES)).thenReturn(false);

        final Field field = ConnectionListenerManager.class.getDeclaredField("dispatchThread");
        field.setAccessible(true);
        final ExecutorService realExecutor = (ExecutorService) field.get(this.manager);
        realExecutor.shutdownNow();
        field.set(this.manager, this.dispatchExecutor);
    }

    private void whenShutdown() {
        this.manager.shutdown();
    }

    private void thenSlowListenerCompleted() {
        assertTrue(this.slowListenerCompleted);
    }

    private void thenDispatchExecutorWasShutDownAndAwaited() throws InterruptedException {
        verify(this.dispatchExecutor).shutdown();
        verify(this.dispatchExecutor).awaitTermination(1, TimeUnit.MINUTES);
    }
}
