/*******************************************************************************
 * Copyright (c) 2025, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
/* Some portions generated by generative AI */
package org.eclipse.kura.linux.gpio.libgpiod1;

import java.io.IOException;
import java.util.concurrent.atomic.AtomicBoolean;

import org.eclipse.kura.gpio.KuraClosedDeviceException;
import org.eclipse.kura.gpio.KuraGPIODeviceException;
import org.eclipse.kura.gpio.KuraGPIODirection;
import org.eclipse.kura.gpio.KuraGPIOMode;
import org.eclipse.kura.gpio.KuraGPIOPin;
import org.eclipse.kura.gpio.KuraGPIOTrigger;
import org.eclipse.kura.gpio.KuraUnavailableDeviceException;
import org.eclipse.kura.linux.gpio.libgpiod.LibGpiodPin;
import org.eclipse.kura.linux.gpio.libgpiod1.LibGpiodV1Native.LineEvent;
import org.eclipse.kura.linux.gpio.libgpiod1.LibGpiodV1Native.LineRequestConfig;
import org.eclipse.kura.linux.gpio.libgpiod1.LibGpiodV1Native.TimeSpec;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.sun.jna.Pointer;

/**
 * GPIO pin implementation for libgpiod v1.6.x
 */
public class LibGpiodV1Pin extends LibGpiodPin implements KuraGPIOPin {

    private static final Logger logger = LoggerFactory.getLogger(LibGpiodV1Pin.class);

    private Pointer line;
    private final AtomicBoolean isReserved = new AtomicBoolean(false);

    public LibGpiodV1Pin(String chipPath, int offset, KuraGPIODirection direction, KuraGPIOMode mode,
            KuraGPIOTrigger trigger, String pinName) {
        super(chipPath, offset, direction, mode, trigger, pinName);
    }

    @Override
    public void open() throws KuraGPIODeviceException, KuraUnavailableDeviceException {
        synchronized (this) {
            if (this.isOpen.get()) {
                return;
            }

            openGpioChip();
            getGpioLine();

            this.isOpen.set(true);
        }
    }

    @Override
    public void close() throws IOException {
        synchronized (this) {
            if (!this.isOpen.get()) {
                return;
            }

            stopEventMonitoring();
            this.listeners.clear();

            try {
                releaseGpioLine();
                closeGpioChip();
            } finally {
                this.isOpen.set(false);
                this.isReserved.set(false);
            }
        }
    }

    @Override
    public boolean getValue() throws KuraUnavailableDeviceException, KuraClosedDeviceException, IOException {
        try {
            ensureOpenAndReserved();
        } catch (KuraGPIODeviceException e) {
            throw new KuraUnavailableDeviceException(e, "Error ensuring pin is open and reserved");
        }

        int value = 0;
        try {
            value = LibGpiodV1NativeWrapper.getInstance().gpiod_line_get_value(this.line);
            if (value < 0) {
                throw new IOException("Failed to read GPIO value");
            }
        } catch (Error e) {
            throw new IOException("Failed to read GPIO value", e);
        }

        return value == 1;
    }

    @Override
    public void setValue(boolean value) throws KuraUnavailableDeviceException, KuraClosedDeviceException, IOException {
        try {
            ensureOpenAndReserved();
        } catch (KuraGPIODeviceException e) {
            throw new KuraUnavailableDeviceException(e, "Error ensuring pin is open and reserved");
        }

        if (this.direction != KuraGPIODirection.OUTPUT) {
            throw new IOException("Cannot set value on input pin");
        }

        int gpioValue = value ? 1 : 0;
        try {
            int exitCode = LibGpiodV1NativeWrapper.getInstance().gpiod_line_set_value(this.line, gpioValue);
            if (exitCode < 0) {
                throw new IOException("Failed to set GPIO value");
            }
        } catch (Error e) {
            throw new IOException("Failed to set GPIO value", e);
        }
    }

    protected void monitorEvents() {
        if (!this.isMonitoring.get()) {
            return;
        }
        try {
            ensureOpenAndReserved();
        } catch (KuraGPIODeviceException | KuraClosedDeviceException e) {
            logger.error("Error ensuring pin is open and reserved", e);
            return;
        }

        TimeSpec timeout = LibGpiodV1NativeWrapper.getInstance().createTimeSpec(DEFAULT_TIMEOUT_SEC);

        while (this.isMonitoring.get()) {
            manageEvents(timeout);
        }
    }

    private void manageEvents(TimeSpec timeout) {
        try {
            int waitResult = LibGpiodV1NativeWrapper.getInstance().gpiod_line_event_wait(this.line, timeout);
            if (waitResult > 0) {
                LineEvent[] events = new LineEvent[64];
                int numEvents = LibGpiodV1NativeWrapper.getInstance().gpiod_line_event_read_multiple(this.line, events,
                        64);
                if (numEvents > 0) {
                    for (int i = 0; i < numEvents; i++) {
                        if (events[i] != null) {
                        	notifyPinStatusChange(events[i]);
                        }
                    }
                }
            } else if (waitResult < 0) {
                logger.error("Error waiting for GPIO event: {}", waitResult);
            }
        } catch (Error e) {
            logger.error("Exception while managing GPIO events: {}", e.getMessage());
        }
    }

    private void notifyPinStatusChange(LineEvent event) {
        boolean newValue = event.event_type == LibGpiodV1Native.GPIOD_LINE_EVENT_RISING_EDGE;
        synchronized (this.listeners) {
            this.listeners.forEach(listener -> {
                if (this.trigger.equals(KuraGPIOTrigger.BOTH_EDGES)) {
                    listener.pinStatusChange(newValue);
                    return;
                }
                if (this.trigger.equals(KuraGPIOTrigger.RAISING_EDGE) && newValue) {
                    listener.pinStatusChange(newValue);
                    return;
                }
                if (this.trigger.equals(KuraGPIOTrigger.FALLING_EDGE) && !newValue) {
                    listener.pinStatusChange(newValue);
                }
            });
        }
    }
    
    private void openGpioChip() throws KuraUnavailableDeviceException {
        try {
            this.chip = LibGpiodV1NativeWrapper.getInstance().gpiod_chip_open(this.chipPath);
            if (this.chip == null) {
                throw new KuraUnavailableDeviceException("Cannot open GPIO chip: " + this.chipPath);
            }
        } catch (Error e) {
            throw new KuraUnavailableDeviceException(e, "Cannot open GPIO chip: " + this.chipPath);
        }
    }

    private void closeGpioChip() {
        if (this.chip != null) {
            try {
                LibGpiodV1NativeWrapper.getInstance().gpiod_chip_close(this.chip);
            } catch (Error e) {
                logger.error("Cannot open GPIO chip: " + this.chipPath, e);
            } finally {
                this.chip = null;
            }
        }
    }

    private void getGpioLine() throws KuraUnavailableDeviceException {
        try {
            this.line = LibGpiodV1NativeWrapper.getInstance().gpiod_chip_get_line(this.chip, this.offset);
            if (this.line == null) {
                closeGpioChip();
                throw new KuraUnavailableDeviceException("Cannot get GPIO line: " + this.offset);
            }
            boolean isUsed = LibGpiodV1NativeWrapper.getInstance().gpiod_line_is_used(this.line);
            if (isUsed) {
                closeGpioChip();
                throw new KuraUnavailableDeviceException("GPIO line already in use: " + this.offset);
            }
        } catch (Error e) {
            closeGpioChip();
            throw new KuraUnavailableDeviceException(e, "Cannot get GPIO line: " + this.offset);
        }
    }

    private void releaseGpioLine() {
        if (this.isReserved.get() && this.line != null) {
            try {
                LibGpiodV1NativeWrapper.getInstance().gpiod_line_release(this.line);
            } catch (Error e) {
                logger.error("Cannot release GPIO line: " + this.offset, e);
            } finally {
                this.line = null;
            }
        }
    }

    private void ensureOpenAndReserved() throws KuraClosedDeviceException, KuraGPIODeviceException {
        if (!this.isOpen.get()) {
            throw new KuraClosedDeviceException(this.pinName);
        }

        if (!this.isReserved.get()) {
            reservePin();
        }
    }

    private void reservePin() throws KuraGPIODeviceException {
        synchronized (this) {
            if (this.isReserved.get()) {
                return;
            }

            try {
                int result;

                LineRequestConfig config = LibGpiodV1NativeWrapper.getInstance().createLineRequestConfig("KuraGPIOPin", 
                		calculateRequestType(), calculateFlags());
                result = LibGpiodV1NativeWrapper.getInstance().gpiod_line_request(this.line, config, 0);

                if (result < 0) {
                    throw new KuraGPIODeviceException("Failed to reserve GPIO line");
                }

                this.isReserved.set(true);

            } catch (Error e) {
                throw new KuraGPIODeviceException(e, "Failed to reserve GPIO pin");
            }
        }
        
    }

    private int calculateFlags() {
        int flags = 0;
        switch (this.mode) {
        case INPUT_PULL_UP:
            flags |= LibGpiodV1Native.GPIOD_LINE_REQUEST_FLAG_BIAS_PULL_UP;
            break;
        case INPUT_PULL_DOWN:
            flags |= LibGpiodV1Native.GPIOD_LINE_REQUEST_FLAG_BIAS_PULL_DOWN;
            break;
        case OUTPUT_OPEN_DRAIN:
            flags |= LibGpiodV1Native.GPIOD_LINE_REQUEST_FLAG_OPEN_DRAIN;
            break;
        default:
            // No additional flags for OUTPUT_PUSH_PULL
            break;
        }

        return flags;
    }
    
    private int calculateRequestType() {
        switch (this.direction) {
            case INPUT:
                // If direction is INPUT, set the request type to both edges by default, 
                // as it will be further filtered in the event handler
                return LibGpiodV1Native.GPIOD_LINE_REQUEST_EVENT_BOTH_EDGES;
            case OUTPUT:
                return LibGpiodV1Native.GPIOD_LINE_REQUEST_DIRECTION_OUTPUT;
            default:
                throw new IllegalArgumentException("Unsupported direction: " + this.direction);
        }
    }

}