/*******************************************************************************
 * Copyright (c) 2025, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
/* Some portions generated by generative AI */
package org.eclipse.kura.linux.gpio.libgpiod1;

import java.util.Arrays;
import java.util.List;

import com.sun.jna.Callback;
import com.sun.jna.Library;
import com.sun.jna.Memory;
import com.sun.jna.Native;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.ptr.IntByReference;

/**
 * JNA interface for libgpiod v1.6.x native library
 * 
 * This interface provides access to the legacy libgpiod v1.6 API which
 * differs significantly from the v2.x API.
 */
public interface LibGpiodV1Native extends Library {

    LibGpiodV1Native INSTANCE = Native.load("gpiod", LibGpiodV1Native.class);

    // ============ Constants ============

    // Line bulk maximum size
    int GPIOD_LINE_BULK_MAX_LINES = 64;

    // Contextless flags
    int GPIOD_CTXLESS_FLAG_OPEN_DRAIN = 1;
    int GPIOD_CTXLESS_FLAG_OPEN_SOURCE = 2;
    int GPIOD_CTXLESS_FLAG_BIAS_DISABLE = 4;
    int GPIOD_CTXLESS_FLAG_BIAS_PULL_DOWN = 8;
    int GPIOD_CTXLESS_FLAG_BIAS_PULL_UP = 16;

    // Line directions
    int GPIOD_LINE_DIRECTION_INPUT = 1;
    int GPIOD_LINE_DIRECTION_OUTPUT = 2;

    // Active states
    int GPIOD_LINE_ACTIVE_STATE_HIGH = 1;
    int GPIOD_LINE_ACTIVE_STATE_LOW = 2;

    // Bias settings
    int GPIOD_LINE_BIAS_AS_IS = 1;
    int GPIOD_LINE_BIAS_DISABLE = 2;
    int GPIOD_LINE_BIAS_PULL_UP = 3;
    int GPIOD_LINE_BIAS_PULL_DOWN = 4;

    // Request types
    int GPIOD_LINE_REQUEST_DIRECTION_AS_IS = 1;
    int GPIOD_LINE_REQUEST_DIRECTION_INPUT = 2;
    int GPIOD_LINE_REQUEST_DIRECTION_OUTPUT = 3;
    int GPIOD_LINE_REQUEST_EVENT_FALLING_EDGE = 4;
    int GPIOD_LINE_REQUEST_EVENT_RISING_EDGE = 5;
    int GPIOD_LINE_REQUEST_EVENT_BOTH_EDGES = 6;

    // Request flags
    int GPIOD_LINE_REQUEST_FLAG_OPEN_DRAIN = 1;
    int GPIOD_LINE_REQUEST_FLAG_OPEN_SOURCE = 2;
    int GPIOD_LINE_REQUEST_FLAG_ACTIVE_LOW = 4;
    int GPIOD_LINE_REQUEST_FLAG_BIAS_DISABLE = 8;
    int GPIOD_LINE_REQUEST_FLAG_BIAS_PULL_DOWN = 16;
    int GPIOD_LINE_REQUEST_FLAG_BIAS_PULL_UP = 32;

    // Event types
    int GPIOD_LINE_EVENT_RISING_EDGE = 1;
    int GPIOD_LINE_EVENT_FALLING_EDGE = 2;

    // Contextless event types
    int GPIOD_CTXLESS_EVENT_RISING_EDGE = 1;
    int GPIOD_CTXLESS_EVENT_FALLING_EDGE = 2;
    int GPIOD_CTXLESS_EVENT_BOTH_EDGES = 3;

    // Contextless event callback types
    int GPIOD_CTXLESS_EVENT_CB_TIMEOUT = 1;
    int GPIOD_CTXLESS_EVENT_CB_RISING_EDGE = 2;
    int GPIOD_CTXLESS_EVENT_CB_FALLING_EDGE = 3;

    // Contextless event callback return values
    int GPIOD_CTXLESS_EVENT_CB_RET_ERR = -1;
    int GPIOD_CTXLESS_EVENT_CB_RET_OK = 0;
    int GPIOD_CTXLESS_EVENT_CB_RET_STOP = 1;

    // Contextless event poll return values
    int GPIOD_CTXLESS_EVENT_POLL_RET_STOP = -2;
    int GPIOD_CTXLESS_EVENT_POLL_RET_ERR = -1;
    int GPIOD_CTXLESS_EVENT_POLL_RET_TIMEOUT = 0;

    // ============ Structures ============

    /**
     * Structure holding configuration of a line request
     */
    class LineRequestConfig extends Structure {

        public Pointer consumer;
        public int request_type;
        public int flags;

        private Memory consumerMemory;
        
        @Override
        protected List<String> getFieldOrder() {
            return Arrays.asList("consumer", "request_type", "flags");
        }
        
        public void setConsumer(String value) {
            if (value == null) {
                consumerMemory = null;
                consumer = null;
                return;
            }

            // allocate native memory (+1 for null terminator)
            consumerMemory = new Memory(Native.toByteArray(value, "UTF-8").length + 1L);
            consumerMemory.setString(0, value);

            consumer = consumerMemory;
        }
    }

    public default LineRequestConfig createLineRequestConfig(String consumer, int request_type, int flags) {
		LineRequestConfig config = new LineRequestConfig();
		config.setConsumer(consumer);
		config.request_type = request_type;
		config.flags = flags;
		return config;
	}
    
    /**
     * Helper structure for storing a set of GPIO line objects
     */
    class LineBulk extends Structure {

        public Pointer[] lines = new Pointer[GPIOD_LINE_BULK_MAX_LINES];
        public int num_lines;

        @Override
        protected List<String> getFieldOrder() {
            return Arrays.asList("lines", "num_lines");
        }
    }

    /**
     * Structure holding event info
     */
    class LineEvent extends Structure {

        public TimeSpec ts;
        public int event_type;

        @Override
        protected List<String> getFieldOrder() {
            return Arrays.asList("ts", "event_type");
        }
    }

    /**
     * Timespec structure
     */
    class TimeSpec extends Structure {

        public long tv_sec;
        public long tv_nsec;

        @Override
        protected List<String> getFieldOrder() {
            return Arrays.asList("tv_sec", "tv_nsec");
        }
    }

    /**
     * Helper structure for the contextless event loop poll callback
     */
    class ContextlessEventPollFd extends Structure {

        public int fd;
        public boolean event;

        @Override
        protected List<String> getFieldOrder() {
            return Arrays.asList("fd", "event");
        }
    }

    // ============ Callback Interfaces ============

    /**
     * Simple set value callback
     */
    interface ContextlessSetValueCallback extends Callback {

        void callback(Pointer data);
    }

    /**
     * Simple event callback
     */
    interface ContextlessEventHandleCallback extends Callback {

        int callback(int event_type, int offset, TimeSpec timestamp, Pointer data);
    }

    /**
     * Simple event poll callback
     */
    interface ContextlessEventPollCallback extends Callback {

        int callback(int num_lines, ContextlessEventPollFd fds, TimeSpec timeout, Pointer data);
    }

    // ============ High-level API ============

    /**
     * Read current value from a single GPIO line
     */
    int gpiod_ctxless_get_value(String device, int offset, boolean active_low, String consumer);

    /**
     * Read current value from a single GPIO line (extended)
     */
    int gpiod_ctxless_get_value_ext(String device, int offset, boolean active_low, String consumer, int flags);

    /**
     * Read current values from a set of GPIO lines
     */
    int gpiod_ctxless_get_value_multiple(String device, int[] offsets, int[] values, int num_lines, boolean active_low,
            String consumer);

    /**
     * Read current values from a set of GPIO lines (extended)
     */
    int gpiod_ctxless_get_value_multiple_ext(String device, int[] offsets, int[] values, int num_lines,
            boolean active_low, String consumer, int flags);

    /**
     * Set value of a single GPIO line
     */
    int gpiod_ctxless_set_value(String device, int offset, int value, boolean active_low, String consumer,
            ContextlessSetValueCallback cb, Pointer data);

    /**
     * Set value of a single GPIO line (extended)
     */
    int gpiod_ctxless_set_value_ext(String device, int offset, int value, boolean active_low, String consumer,
            ContextlessSetValueCallback cb, Pointer data, int flags);

    /**
     * Set values of multiple GPIO lines
     */
    int gpiod_ctxless_set_value_multiple(String device, int[] offsets, int[] values, int num_lines, boolean active_low,
            String consumer, ContextlessSetValueCallback cb, Pointer data);

    /**
     * Set values of multiple GPIO lines (extended)
     */
    int gpiod_ctxless_set_value_multiple_ext(String device, int[] offsets, int[] values, int num_lines,
            boolean active_low, String consumer, ContextlessSetValueCallback cb, Pointer data, int flags);

    /**
     * Wait for events on a single GPIO line
     */
    int gpiod_ctxless_event_monitor(String device, int event_type, int offset, boolean active_low, String consumer,
            TimeSpec timeout, ContextlessEventPollCallback poll_cb, ContextlessEventHandleCallback event_cb,
            Pointer data);

    /**
     * Wait for events on a single GPIO line (extended)
     */
    int gpiod_ctxless_event_monitor_ext(String device, int event_type, int offset, boolean active_low, String consumer,
            TimeSpec timeout, ContextlessEventPollCallback poll_cb, ContextlessEventHandleCallback event_cb,
            Pointer data, int flags);

    /**
     * Wait for events on multiple GPIO lines
     */
    int gpiod_ctxless_event_monitor_multiple(String device, int event_type, int[] offsets, int num_lines,
            boolean active_low, String consumer, TimeSpec timeout, ContextlessEventPollCallback poll_cb,
            ContextlessEventHandleCallback event_cb, Pointer data);

    /**
     * Wait for events on multiple GPIO lines (extended)
     */
    int gpiod_ctxless_event_monitor_multiple_ext(String device, int event_type, int[] offsets, int num_lines,
            boolean active_low, String consumer, TimeSpec timeout, ContextlessEventPollCallback poll_cb,
            ContextlessEventHandleCallback event_cb, Pointer data, int flags);

    /**
     * Determine the chip name and line offset of a line with given name
     */
    int gpiod_ctxless_find_line(String name, byte[] chipname, int chipname_size, IntByReference offset);

    // ============ GPIO Chip Operations ============

    /**
     * Open a gpiochip by path
     */
    Pointer gpiod_chip_open(String path);

    /**
     * Open a gpiochip by name
     */
    Pointer gpiod_chip_open_by_name(String name);

    /**
     * Open a gpiochip by number
     */
    Pointer gpiod_chip_open_by_number(int num);

    /**
     * Open a gpiochip by label
     */
    Pointer gpiod_chip_open_by_label(String label);

    /**
     * Open a gpiochip based on the best guess what the path is
     */
    Pointer gpiod_chip_open_lookup(String descr);

    /**
     * Close a GPIO chip handle and release all allocated resources
     */
    void gpiod_chip_close(Pointer chip);

    /**
     * Get the GPIO chip name as represented in the kernel
     */
    String gpiod_chip_name(Pointer chip);

    /**
     * Get the GPIO chip label as represented in the kernel
     */
    String gpiod_chip_label(Pointer chip);

    /**
     * Get the number of GPIO lines exposed by this chip
     */
    int gpiod_chip_num_lines(Pointer chip);

    /**
     * Get the handle to the GPIO line at given offset
     */
    Pointer gpiod_chip_get_line(Pointer chip, int offset);

    /**
     * Retrieve a set of lines and store them in a line bulk object
     */
    int gpiod_chip_get_lines(Pointer chip, int[] offsets, int num_offsets, LineBulk bulk);

    /**
     * Retrieve all lines exposed by a chip and store them in a bulk object
     */
    int gpiod_chip_get_all_lines(Pointer chip, LineBulk bulk);

    /**
     * Find a GPIO line by name among lines associated with given GPIO chip
     */
    Pointer gpiod_chip_find_line(Pointer chip, String name);

    /**
     * Find a set of GPIO lines by names among lines exposed by this chip
     */
    int gpiod_chip_find_lines(Pointer chip, String[] names, LineBulk bulk);

    // ============ GPIO Line Operations ============

    /**
     * Read the GPIO line offset
     */
    int gpiod_line_offset(Pointer line);

    /**
     * Read the GPIO line name
     */
    String gpiod_line_name(Pointer line);

    /**
     * Read the GPIO line consumer name
     */
    String gpiod_line_consumer(Pointer line);

    /**
     * Read the GPIO line direction setting
     */
    int gpiod_line_direction(Pointer line);

    /**
     * Read the GPIO line active state setting
     */
    int gpiod_line_active_state(Pointer line);

    /**
     * Read the GPIO line bias setting
     */
    int gpiod_line_bias(Pointer line);

    /**
     * Check if the line is currently in use
     */
    boolean gpiod_line_is_used(Pointer line);

    /**
     * Check if the line is an open-drain GPIO
     */
    boolean gpiod_line_is_open_drain(Pointer line);

    /**
     * Check if the line is an open-source GPIO
     */
    boolean gpiod_line_is_open_source(Pointer line);

    /**
     * Re-read the line info
     */
    int gpiod_line_update(Pointer line);

    // ============ Line Requests ============

    /**
     * Reserve a single line
     */
    int gpiod_line_request(Pointer line, LineRequestConfig config, int default_val);

    /**
     * Reserve a single line, set the direction to input
     */
    int gpiod_line_request_input(Pointer line, String consumer);

    /**
     * Reserve a single line, set the direction to output
     */
    int gpiod_line_request_output(Pointer line, String consumer, int default_val);

    /**
     * Request rising edge event notifications on a single line
     */
    int gpiod_line_request_rising_edge_events(Pointer line, String consumer);

    /**
     * Request falling edge event notifications on a single line
     */
    int gpiod_line_request_falling_edge_events(Pointer line, String consumer);

    /**
     * Request all event type notifications on a single line
     */
    int gpiod_line_request_both_edges_events(Pointer line, String consumer);

    /**
     * Reserve a single line, set the direction to input (with flags)
     */
    int gpiod_line_request_input_flags(Pointer line, String consumer, int flags);

    /**
     * Reserve a single line, set the direction to output (with flags)
     */
    int gpiod_line_request_output_flags(Pointer line, String consumer, int flags, int default_val);

    /**
     * Request rising edge event notifications on a single line (with flags)
     */
    int gpiod_line_request_rising_edge_events_flags(Pointer line, String consumer, int flags);

    /**
     * Request falling edge event notifications on a single line (with flags)
     */
    int gpiod_line_request_falling_edge_events_flags(Pointer line, String consumer, int flags);

    /**
     * Request all event type notifications on a single line (with flags)
     */
    int gpiod_line_request_both_edges_events_flags(Pointer line, String consumer, int flags);

    /**
     * Reserve a set of GPIO lines
     */
    int gpiod_line_request_bulk(LineBulk bulk, LineRequestConfig config, int[] default_vals);

    /**
     * Reserve a set of GPIO lines, set the direction to input
     */
    int gpiod_line_request_bulk_input(LineBulk bulk, String consumer);

    /**
     * Reserve a set of GPIO lines, set the direction to output
     */
    int gpiod_line_request_bulk_output(LineBulk bulk, String consumer, int[] default_vals);

    /**
     * Request rising edge event notifications on a set of lines
     */
    int gpiod_line_request_bulk_rising_edge_events(LineBulk bulk, String consumer);

    /**
     * Request falling edge event notifications on a set of lines
     */
    int gpiod_line_request_bulk_falling_edge_events(LineBulk bulk, String consumer);

    /**
     * Request all event type notifications on a set of lines
     */
    int gpiod_line_request_bulk_both_edges_events(LineBulk bulk, String consumer);

    /**
     * Reserve a set of GPIO lines, set the direction to input (with flags)
     */
    int gpiod_line_request_bulk_input_flags(LineBulk bulk, String consumer, int flags);

    /**
     * Reserve a set of GPIO lines, set the direction to output (with flags)
     */
    int gpiod_line_request_bulk_output_flags(LineBulk bulk, String consumer, int flags, int[] default_vals);

    /**
     * Request rising edge event notifications on a set of lines (with flags)
     */
    int gpiod_line_request_bulk_rising_edge_events_flags(LineBulk bulk, String consumer, int flags);

    /**
     * Request falling edge event notifications on a set of lines (with flags)
     */
    int gpiod_line_request_bulk_falling_edge_events_flags(LineBulk bulk, String consumer, int flags);

    /**
     * Request all event type notifications on a set of lines (with flags)
     */
    int gpiod_line_request_bulk_both_edges_events_flags(LineBulk bulk, String consumer, int flags);

    /**
     * Release a previously reserved line
     */
    void gpiod_line_release(Pointer line);

    /**
     * Release a set of previously reserved lines
     */
    void gpiod_line_release_bulk(LineBulk bulk);

    /**
     * Check if the calling user has ownership of this line
     */
    boolean gpiod_line_is_requested(Pointer line);

    /**
     * Check if the calling user has neither requested ownership nor configured events
     */
    boolean gpiod_line_is_free(Pointer line);

    // ============ Reading & Setting Line Values ============

    /**
     * Read current value of a single GPIO line
     */
    int gpiod_line_get_value(Pointer line);

    /**
     * Read current values of a set of GPIO lines
     */
    int gpiod_line_get_value_bulk(LineBulk bulk, int[] values);

    /**
     * Set the value of a single GPIO line
     */
    int gpiod_line_set_value(Pointer line, int value);

    /**
     * Set the values of a set of GPIO lines
     */
    int gpiod_line_set_value_bulk(LineBulk bulk, int[] values);

    // ============ Setting Line Configuration ============

    /**
     * Update the configuration of a single GPIO line
     */
    int gpiod_line_set_config(Pointer line, int direction, int flags, int value);

    /**
     * Update the configuration of a set of GPIO lines
     */
    int gpiod_line_set_config_bulk(LineBulk bulk, int direction, int flags, int[] values);

    /**
     * Update the configuration flags of a single GPIO line
     */
    int gpiod_line_set_flags(Pointer line, int flags);

    /**
     * Update the configuration flags of a set of GPIO lines
     */
    int gpiod_line_set_flags_bulk(LineBulk bulk, int flags);

    /**
     * Set the direction of a single GPIO line to input
     */
    int gpiod_line_set_direction_input(Pointer line);

    /**
     * Set the direction of a set of GPIO lines to input
     */
    int gpiod_line_set_direction_input_bulk(LineBulk bulk);

    /**
     * Set the direction of a single GPIO line to output
     */
    int gpiod_line_set_direction_output(Pointer line, int value);

    /**
     * Set the direction of a set of GPIO lines to output
     */
    int gpiod_line_set_direction_output_bulk(LineBulk bulk, int[] values);

    // ============ Line Events Handling ============

    /**
     * Wait for an event on a single line
     */
    int gpiod_line_event_wait(Pointer line, TimeSpec timeout);

    /**
     * Wait for events on a set of lines
     */
    int gpiod_line_event_wait_bulk(LineBulk bulk, TimeSpec timeout, LineBulk event_bulk);

    /**
     * Read next pending event from the GPIO line
     */
    int gpiod_line_event_read(Pointer line, LineEvent event);

    /**
     * Read up to a certain number of events from the GPIO line
     */
    int gpiod_line_event_read_multiple(Pointer line, LineEvent[] events, int num_events);

    /**
     * Get the event file descriptor
     */
    int gpiod_line_event_get_fd(Pointer line);

    /**
     * Read the last GPIO event directly from a file descriptor
     */
    int gpiod_line_event_read_fd(int fd, LineEvent event);

    /**
     * Read up to a certain number of events directly from a file descriptor
     */
    int gpiod_line_event_read_fd_multiple(int fd, LineEvent[] events, int num_events);

    // ============ Misc Line Functions ============

    /**
     * Get a GPIO line handle by GPIO chip description and offset
     */
    Pointer gpiod_line_get(String device, int offset);

    /**
     * Find a GPIO line by its name
     */
    Pointer gpiod_line_find(String name);

    /**
     * Close a GPIO chip owning this line and release all resources
     */
    void gpiod_line_close_chip(Pointer line);

    /**
     * Get the handle to the GPIO chip controlling this line
     */
    Pointer gpiod_line_get_chip(Pointer line);

    // ============ Iterators ============

    /**
     * Create a new gpiochip iterator
     */
    Pointer gpiod_chip_iter_new();

    /**
     * Release all resources allocated for the gpiochip iterator
     */
    void gpiod_chip_iter_free(Pointer iter);

    /**
     * Release all resources but don't close the most recently opened chip
     */
    void gpiod_chip_iter_free_noclose(Pointer iter);

    /**
     * Get the next gpiochip handle
     */
    Pointer gpiod_chip_iter_next(Pointer iter);

    /**
     * Get the next gpiochip handle without closing the previous one
     */
    Pointer gpiod_chip_iter_next_noclose(Pointer iter);

    /**
     * Create a new line iterator
     */
    Pointer gpiod_line_iter_new(Pointer chip);

    /**
     * Free all resources associated with a GPIO line iterator
     */
    void gpiod_line_iter_free(Pointer iter);

    /**
     * Get the next GPIO line handle
     */
    Pointer gpiod_line_iter_next(Pointer iter);

    // ============ Misc Functions ============

    /**
     * Get the API version of the library as a human-readable string
     */
    String gpiod_version_string();

}