/*******************************************************************************
 * Copyright (c) 2025 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
/* Some portions generated by generative AI */
package org.eclipse.kura.linux.gpio.libgpiod1;

import java.io.IOException;
import java.util.Optional;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.atomic.AtomicBoolean;

import org.eclipse.kura.gpio.KuraClosedDeviceException;
import org.eclipse.kura.gpio.KuraGPIODeviceException;
import org.eclipse.kura.gpio.KuraGPIODirection;
import org.eclipse.kura.gpio.KuraGPIOMode;
import org.eclipse.kura.gpio.KuraGPIOPin;
import org.eclipse.kura.gpio.KuraGPIOTrigger;
import org.eclipse.kura.gpio.KuraUnavailableDeviceException;
import org.eclipse.kura.gpio.PinStatusListener;
import org.eclipse.kura.linux.gpio.libgpiod1.LibGpiodV1Native.LineEvent;
import org.eclipse.kura.linux.gpio.libgpiod1.LibGpiodV1Native.TimeSpec;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.sun.jna.Pointer;

/**
 * GPIO pin implementation for libgpiod v1.6.x
 */
public class LibGpiodV1Pin implements KuraGPIOPin {

    private static final Logger logger = LoggerFactory.getLogger(LibGpiodV1Pin.class);
    private static final int DEFAULT_TIMEOUT_SEC = 1;
    private static final ExecutorService EXECUTOR = Executors.newCachedThreadPool(runnable -> {
        Thread thread = new Thread(runnable, "GPIO-EventMonitor");
        thread.setDaemon(true);
        return thread;
    });

    private final String chipPath;
    private final int offset;
    private final String pinName;
    private final KuraGPIODirection direction;
    private final KuraGPIOMode mode;
    private final KuraGPIOTrigger trigger;

    private Pointer chip;
    private Pointer line;
    private final AtomicBoolean isOpen = new AtomicBoolean(false);
    private final AtomicBoolean isReserved = new AtomicBoolean(false);
    private final AtomicBoolean isMonitoring = new AtomicBoolean(false);

    private Optional<PinStatusListener> listener = Optional.empty();
    private Future<?> monitoringTask;

    public LibGpiodV1Pin(String chipPath, int offset, KuraGPIODirection direction, KuraGPIOMode mode,
            KuraGPIOTrigger trigger, String pinName) {
        this.chipPath = chipPath;
        this.offset = offset;
        this.direction = direction;
        this.mode = mode;
        this.trigger = trigger;
        this.pinName = pinName;
    }

    @Override
    public void open() throws KuraGPIODeviceException, KuraUnavailableDeviceException {
        synchronized (this) {
            if (this.isOpen.get()) {
                return;
            }

            openGpioChip();
            getGpioLine();

            this.isOpen.set(true);
        }
    }

    @Override
    public void close() throws IOException {
        synchronized (this) {
            if (!this.isOpen.get()) {
                return;
            }

            stopEventMonitoring();
            this.listener = Optional.empty();

            try {
                releaseGpioLine();
                closeGpioChip();
            } finally {
                this.isOpen.set(false);
                this.isReserved.set(false);
            }
        }
    }

    @Override
    public boolean getValue() throws KuraUnavailableDeviceException, KuraClosedDeviceException, IOException {
        try {
            ensureOpenAndReserved();
        } catch (KuraGPIODeviceException e) {
            throw new KuraUnavailableDeviceException(e, "Error ensuring pin is open and reserved");
        }

        int value = 0;
        try {
            value = LibGpiodV1NativeWrapper.getInstance().gpiod_line_get_value(this.line);
            if (value < 0) {
                throw new IOException("Failed to read GPIO value");
            }
        } catch (Error e) {
            throw new IOException("Failed to read GPIO value", e);
        }

        return value == 1;
    }

    @Override
    public void setValue(boolean value) throws KuraUnavailableDeviceException, KuraClosedDeviceException, IOException {
        try {
            ensureOpenAndReserved();
        } catch (KuraGPIODeviceException e) {
            throw new KuraUnavailableDeviceException(e, "Error ensuring pin is open and reserved");
        }

        if (this.direction != KuraGPIODirection.OUTPUT) {
            throw new IOException("Cannot set value on non-output pin");
        }

        int gpioValue = value ? 1 : 0;
        try {
            int exitCode = LibGpiodV1NativeWrapper.getInstance().gpiod_line_set_value(this.line, gpioValue);
            if (exitCode < 0) {
                throw new IOException("Failed to set GPIO value");
            }
        } catch (Error e) {
            throw new IOException("Failed to set GPIO value", e);
        }
    }

    @Override
    public boolean isOpen() {
        return this.isOpen.get();
    }

    @Override
    public String getName() {
        return this.pinName;
    }

    @Override
    public int getIndex() {
        return extractChipNumber(this.chipPath) * 1000 + this.offset;
    }

    @Override
    public KuraGPIODirection getDirection() {
        return this.direction;
    }

    @Override
    public KuraGPIOMode getMode() {
        return this.mode;
    }

    @Override
    public KuraGPIOTrigger getTrigger() {
        return this.trigger;
    }

    @Override
    public void addPinStatusListener(PinStatusListener listener) throws KuraClosedDeviceException, IOException {
        if (listener == null) {
            throw new IllegalArgumentException("Listener cannot be null");
        }

        if (!this.isOpen.get()) {
            throw new KuraClosedDeviceException("Pin is closed");
        }

        this.listener = Optional.of(listener);

        if (shouldMonitorEvents()) {
            startEventMonitoring();
        }
    }

    private boolean shouldMonitorEvents() {
        return this.direction == KuraGPIODirection.INPUT && this.trigger != KuraGPIOTrigger.NONE
                && this.trigger != KuraGPIOTrigger.HIGH_LEVEL && this.trigger != KuraGPIOTrigger.LOW_LEVEL
                && this.trigger != KuraGPIOTrigger.BOTH_LEVELS;
    }

    private void startEventMonitoring() {
        if (this.isMonitoring.compareAndSet(false, true)) {
            this.monitoringTask = EXECUTOR.submit(this::monitorEvents);
        }
    }

    private void monitorEvents() {
        if (!this.isMonitoring.get() || !this.isOpen.get()) {
            return;
        }
        TimeSpec timeout = new TimeSpec();
        timeout.tv_sec = DEFAULT_TIMEOUT_SEC;

        try {
            int triggerResult = 0;
            switch (this.trigger) {
            case RAISING_EDGE:
                triggerResult = LibGpiodV1NativeWrapper.getInstance().gpiod_line_request_rising_edge_events(this.line,
                        "LibGpiodV1PinEventMonitor");
                break;
            case FALLING_EDGE:
                triggerResult = LibGpiodV1NativeWrapper.getInstance().gpiod_line_request_falling_edge_events(this.line,
                        "LibGpiodV1PinEventMonitor");
                break;
            case BOTH_EDGES:
                triggerResult = LibGpiodV1NativeWrapper.getInstance().gpiod_line_request_both_edges_events(this.line,
                        "LibGpiodV1PinEventMonitor");
                break;
            default:
                logger.error("Unsupported trigger mode for event monitoring: " + this.trigger);
                this.isMonitoring.set(false);
                return;
            }
            if (triggerResult < 0) {
                logger.error("Failed to request line for events");
                return;
            }

            while (this.isMonitoring.get() && this.isOpen.get()) {
                int waitResult = LibGpiodV1NativeWrapper.getInstance().gpiod_line_event_wait(this.line, timeout);
                if (waitResult > 0) {
                    LineEvent event = new LineEvent();
                    int readResult = LibGpiodV1NativeWrapper.getInstance().gpiod_line_event_read(this.line, event);
                    if (readResult == 0) {
                        boolean newValue = event.event_type == LibGpiodV1Native.GPIOD_LINE_EVENT_RISING_EDGE;
                        this.listener.ifPresent(l -> l.pinStatusChange(newValue));
                    }
                } else if (waitResult < 0) {
                    logger.error("Error waiting for GPIO event: " + waitResult);
                }
            }
        } catch (Error e) {
            logger.error("Exception in GPIO event monitoring: " + e.getMessage());
        }
    }

    private void stopEventMonitoring() {
        if (this.isMonitoring.compareAndSet(true, false)) {
            if (this.monitoringTask != null) {
                this.monitoringTask.cancel(true);
                try {
                    Thread.sleep(DEFAULT_TIMEOUT_SEC * 2000L);
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                }
                this.monitoringTask = null;
            }
        }
    }

    @Override
    public void removePinStatusListener(PinStatusListener listener) {
        if (listener == null) {
            throw new IllegalArgumentException("Listener cannot be null");
        }

        stopEventMonitoring();
        this.listener = Optional.empty();
    }

    private void openGpioChip() throws KuraUnavailableDeviceException {
        try {
            this.chip = LibGpiodV1NativeWrapper.getInstance().gpiod_chip_open(this.chipPath);
            if (this.chip == null) {
                throw new KuraUnavailableDeviceException("Cannot open GPIO chip: " + this.chipPath);
            }
        } catch (Error e) {
            throw new KuraUnavailableDeviceException(e, "Cannot open GPIO chip: " + this.chipPath);
        }
    }

    private void closeGpioChip() {
        if (this.chip != null) {
            try {
                LibGpiodV1NativeWrapper.getInstance().gpiod_chip_close(this.chip);
            } catch (Error e) {
                logger.error("Cannot open GPIO chip: " + this.chipPath, e);
            } finally {
                this.chip = null;
            }
        }
    }

    private void getGpioLine() throws KuraUnavailableDeviceException {
        try {
            this.line = LibGpiodV1NativeWrapper.getInstance().gpiod_chip_get_line(this.chip, this.offset);
            if (this.line == null) {
                closeGpioChip();
                throw new KuraUnavailableDeviceException("Cannot get GPIO line: " + this.offset);
            }
            boolean is_used = LibGpiodV1NativeWrapper.getInstance().gpiod_line_is_used(this.line);
            if (is_used) {
                closeGpioChip();
                throw new KuraUnavailableDeviceException("GPIO line already in use: " + this.offset);
            }
        } catch (Error e) {
            closeGpioChip();
            throw new KuraUnavailableDeviceException(e, "Cannot get GPIO line: " + this.offset);
        }
    }

    private void releaseGpioLine() {
        if (this.isReserved.get() && this.line != null) {
            try {
                LibGpiodV1NativeWrapper.getInstance().gpiod_line_release(this.line);
            } catch (Error e) {
                logger.error("Cannot release GPIO line: " + this.offset, e);
            } finally {
                this.line = null;
            }
        }
    }

    private void ensureOpenAndReserved() throws KuraClosedDeviceException, KuraGPIODeviceException {
        if (!this.isOpen.get()) {
            throw new KuraClosedDeviceException("Pin is closed");
        }

        if (!this.isReserved.get()) {
            reservePin();
        }
    }

    private void reservePin() throws KuraGPIODeviceException {
        synchronized (this) {
            if (this.isReserved.get()) {
                return;
            }

            try {
                int flags = calculateFlags();
                int result;

                switch (this.direction) {
                case INPUT:
                    result = LibGpiodV1NativeWrapper.getInstance().gpiod_line_request_input_flags(this.line,
                            "LibGpiodV1PinDriver", flags);
                    break;
                case OUTPUT:
                    int defaultValue = LibGpiodV1Native.GPIOD_LINE_ACTIVE_STATE_LOW;
                    result = LibGpiodV1NativeWrapper.getInstance().gpiod_line_request_output_flags(this.line,
                            "LibGpiodV1PinDriver", flags, defaultValue);
                    break;
                default:
                    throw new KuraGPIODeviceException("Unsupported direction: " + this.direction);
                }

                if (result < 0) {
                    throw new KuraGPIODeviceException("Failed to reserve GPIO line");
                }

                this.isReserved.set(true);

            } catch (Error e) {
                throw new KuraGPIODeviceException(e, "Failed to reserve GPIO pin");
            }
        }
    }

    private int calculateFlags() {
        int flags = 0;
        switch (this.mode) {
        case INPUT_PULL_UP:
            flags |= LibGpiodV1Native.GPIOD_LINE_REQUEST_FLAG_BIAS_PULL_UP;
            break;
        case INPUT_PULL_DOWN:
            flags |= LibGpiodV1Native.GPIOD_LINE_REQUEST_FLAG_BIAS_PULL_DOWN;
            break;
        case OUTPUT_OPEN_DRAIN:
            flags |= LibGpiodV1Native.GPIOD_LINE_REQUEST_FLAG_OPEN_DRAIN;
            break;
        default:
            // No additional flags for OUTPUT_PUSH_PULL
            break;
        }

        return flags;
    }

    public static int extractChipNumber(String chipName) {
        try {
            return Integer.parseInt(chipName.replaceAll("\\D", ""));
        } catch (NumberFormatException e) {
            return 0;
        }
    }

    @Override
    public String toString() {
        return String.format("LibGpiodV1Pin{chip=%s, offset=%d, name=%s, direction=%s, mode=%s, trigger=%s}",
                this.chipPath, this.offset, this.pinName, this.direction, this.mode, this.trigger);
    }
}