/*******************************************************************************
 * Copyright (c) 2025 Eurotech and/or its affiliates and others
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *  Eurotech
 *******************************************************************************/
/* Some portions generated by generative AI */
package org.eclipse.kura.linux.gpio.libgpiod1;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.mockStatic;
import static org.mockito.Mockito.when;

import java.io.IOException;
import java.nio.file.FileAlreadyExistsException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Map;

import org.eclipse.kura.gpio.KuraGPIODirection;
import org.eclipse.kura.gpio.KuraGPIOMode;
import org.eclipse.kura.gpio.KuraGPIOPin;
import org.eclipse.kura.gpio.KuraGPIOTrigger;
import org.eclipse.kura.linux.gpio.libgpiod.CommonSteps;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.mockito.MockedStatic;

import com.sun.jna.Native;
import com.sun.jna.Pointer;

public class LibGpiodV1GPIOServiceTest extends CommonSteps {

    private static final String DEVICE_FOLDER = "/tmp/";

    private MockedStatic<Native> nativeMock;
    private LibGpiodV1Native nativeInterfaceMock;
    private MockedStatic<LibGpiodV1NativeWrapper> nativeInterfaceWrapperMock;

    private LibGpiodV1GPIOService v1Service;
    private KuraGPIOPin resultPin;
    private KuraGPIOPin resultPinAgain;
    private Map<Integer, String> resultPins;

    @Before
    public void setup() throws IOException {
        this.nativeMock = mockStatic(Native.class);
        this.nativeInterfaceMock = mock(LibGpiodV1Native.class);
        this.nativeMock.when(() -> Native.load("gpiod", LibGpiodV1Native.class)).thenReturn(this.nativeInterfaceMock);
        this.nativeInterfaceWrapperMock = mockStatic(LibGpiodV1NativeWrapper.class);
        this.nativeInterfaceWrapperMock.when(() -> LibGpiodV1NativeWrapper.getInstance())
                .thenReturn(this.nativeInterfaceMock);

        Pointer chip0 = Pointer.createConstant(0);
        when(this.nativeInterfaceMock.gpiod_chip_open(DEVICE_FOLDER + "gpiochip0")).thenReturn(chip0);
        when(this.nativeInterfaceMock.gpiod_chip_num_lines(chip0)).thenReturn(5);
        for (int offset = 0; offset < 5; offset++) {
            Pointer line0 = Pointer.createConstant(offset);
            when(this.nativeInterfaceMock.gpiod_chip_get_line(chip0, offset)).thenReturn(line0);
            when(this.nativeInterfaceMock.gpiod_line_name(line0)).thenReturn("GPIO0_" + offset);
        }
        Pointer chip1 = Pointer.createConstant(1);
        when(this.nativeInterfaceMock.gpiod_chip_open(DEVICE_FOLDER + "gpiochip1")).thenReturn(chip1);
        when(this.nativeInterfaceMock.gpiod_chip_num_lines(chip1)).thenReturn(5);
        for (int offset = 0; offset < 5; offset++) {
            Pointer line1 = Pointer.createConstant(offset + 5);
            when(this.nativeInterfaceMock.gpiod_chip_get_line(chip1, offset)).thenReturn(line1);
            when(this.nativeInterfaceMock.gpiod_line_name(line1)).thenReturn("GPIO1_" + offset);
        }
        Pointer chip2 = Pointer.createConstant(2);
        when(this.nativeInterfaceMock.gpiod_chip_open(DEVICE_FOLDER + "gpiochip2")).thenReturn(chip2);
        when(this.nativeInterfaceMock.gpiod_chip_num_lines(chip2)).thenReturn(5);
        for (int offset = 0; offset < 5; offset++) {
            Pointer line2 = Pointer.createConstant(offset + 10);
            when(this.nativeInterfaceMock.gpiod_chip_get_line(chip2, offset)).thenReturn(line2);
            when(this.nativeInterfaceMock.gpiod_line_name(line2)).thenReturn("GPIO2_" + offset);
        }
        Pointer chip3 = Pointer.createConstant(3);
        when(this.nativeInterfaceMock.gpiod_chip_open(DEVICE_FOLDER + "gpiochip3")).thenReturn(chip3);
        when(this.nativeInterfaceMock.gpiod_chip_num_lines(chip3)).thenReturn(5);
        for (int offset = 0; offset < 5; offset++) {
            Pointer line3 = Pointer.createConstant(offset + 15);
            when(this.nativeInterfaceMock.gpiod_chip_get_line(chip3, offset)).thenReturn(line3);
            when(this.nativeInterfaceMock.gpiod_line_name(line3)).thenReturn("-");
        }
        Pointer chip4 = Pointer.createConstant(4);
        when(this.nativeInterfaceMock.gpiod_chip_open(DEVICE_FOLDER + "gpiochip4")).thenReturn(chip4);
        when(this.nativeInterfaceMock.gpiod_chip_num_lines(chip4)).thenReturn(5);
        for (int offset = 0; offset < 5; offset++) {
            Pointer line4 = Pointer.createConstant(offset + 20);
            when(this.nativeInterfaceMock.gpiod_chip_get_line(chip4, offset)).thenReturn(line4);
            when(this.nativeInterfaceMock.gpiod_line_name(line4)).thenReturn("");
        }
        Pointer chip5 = Pointer.createConstant(2);
        when(this.nativeInterfaceMock.gpiod_chip_open(DEVICE_FOLDER + "gpiochip5")).thenReturn(chip5);
        when(this.nativeInterfaceMock.gpiod_chip_num_lines(chip5)).thenReturn(5);
        for (int offset = 0; offset < 5; offset++) {
            Pointer line5 = Pointer.createConstant(offset + 25);
            when(this.nativeInterfaceMock.gpiod_chip_get_line(chip5, offset)).thenReturn(line5);
            when(this.nativeInterfaceMock.gpiod_line_name(line5)).thenReturn(null);
        }

        for (int i = 0; i < 6; i++) {
            Files.deleteIfExists(Paths.get(DEVICE_FOLDER + "gpiochip" + i));
        }
    }

    @After
    public void cleanup() {
        this.nativeMock.close();
        this.nativeInterfaceWrapperMock.close();
    }

    @Test
    public void testGetPinByNameWithNullName() {
        givenV1GPIOService();

        whenV1ServiceGetPinByName(null);

        thenExceptionOccurred(IllegalArgumentException.class);
    }

    @Test
    public void testGetPinByNameWithEmptyName() {
        givenV1GPIOService();

        whenV1ServiceGetPinByName("");

        thenExceptionOccurred(IllegalArgumentException.class);
    }

    @Test
    public void testGetPinByNameWithWhitespaceOnlyName() {
        givenV1GPIOService();

        whenV1ServiceGetPinByName("   ");

        thenExceptionOccurred(IllegalArgumentException.class);
    }

    @Test
    public void testGetPinByNameWithValidNameAndDefaultParameters() {
        givenV1GPIOService();

        whenV1ServiceGetPinByName("GPIO0_1");

        thenNoExceptionOccurred();
        thenPinIsNotNull();
        thenPinIs("GPIO0_1", KuraGPIODirection.INPUT, KuraGPIOMode.INPUT_PULL_UP, KuraGPIOTrigger.NONE);
    }

    @Test
    public void testGetPinByNameWithValidNameAndParameters() {
        givenV1GPIOService();

        whenV1ServiceGetPinByName("GPIO0_1", KuraGPIODirection.OUTPUT, KuraGPIOMode.OUTPUT_OPEN_DRAIN,
                KuraGPIOTrigger.NONE);

        thenNoExceptionOccurred();
        thenPinIsNotNull();
        thenPinIs("GPIO0_1", KuraGPIODirection.OUTPUT, KuraGPIOMode.OUTPUT_OPEN_DRAIN, KuraGPIOTrigger.NONE);
    }

    @Test
    public void testGetPinByNameNotInAvailablePins() {
        givenV1GPIOService();

        whenV1ServiceGetPinByName("GPIO_100");

        thenExceptionOccurred(IllegalArgumentException.class);
    }

    @Test
    public void testGetPinByNameFromCache() {
        givenV1GPIOService();

        whenV1ServiceGetPinByName("GPIO2_3");
        whenV1ServiceGetPinByNameAgain("GPIO2_3");

        thenNoExceptionOccurred();
        thenPinsAreSame();
    }

    @Test
    public void testGetPinByTerminalWithNegativeTerminal() {
        givenV1GPIOService();

        whenV1ServiceGetPinByTerminal(-1);

        thenExceptionOccurred(IllegalArgumentException.class);
    }

    @Test
    public void testGetPinByTerminalWithValidTerminal() {
        givenV1GPIOService();

        whenV1ServiceGetPinByTerminal(2003);

        thenNoExceptionOccurred();
        thenPinIsNotNull();
        thenPinIs(2003, KuraGPIODirection.INPUT, KuraGPIOMode.INPUT_PULL_UP, KuraGPIOTrigger.NONE);
    }

    @Test
    public void testGetPinByTerminalWithParameters() {
        givenV1GPIOService();

        whenV1ServiceGetPinByTerminal(2003, KuraGPIODirection.OUTPUT, KuraGPIOMode.OUTPUT_PUSH_PULL,
                KuraGPIOTrigger.NONE);

        thenNoExceptionOccurred();
        thenPinIsNotNull();
        thenPinIs(2003, KuraGPIODirection.OUTPUT, KuraGPIOMode.OUTPUT_PUSH_PULL, KuraGPIOTrigger.NONE);
    }

    @Test
    public void testGetPinByTerminalNotInAvailablePins() {
        givenV1GPIOService();

        whenV1ServiceGetPinByTerminal(9999);

        thenExceptionOccurred(IllegalArgumentException.class);
    }

    @Test
    public void testGetPinByTerminalNotValid() {
        givenV1GPIOService();

        whenV1ServiceGetPinByTerminal(2033);

        thenExceptionOccurred(IllegalArgumentException.class);
    }

    @Test
    public void testGetPinByTerminalWithoutChip() {
        givenV1GPIOService();

        whenV1ServiceGetPinByTerminal(5023);

        thenExceptionOccurred(IllegalArgumentException.class);
    }

    @Test
    public void testGetPinByTerminalFromCache() {
        givenV1GPIOService();

        whenV1ServiceGetPinByTerminal(2003);
        whenV1ServiceGetPinByTerminalAgain(2003);

        thenNoExceptionOccurred();
        thenPinsAreSame();
    }

    @Test
    public void testGetAvailablePins() {
        givenV1GPIOService();

        whenV1ServiceGetAvailablePins();

        thenNoExceptionOccurred();
        thenAvailablePinsIsNotNullOrEmpty();
    }

    @Test
    public void testClearCache() {
        givenV1GPIOService();

        whenV1CacheIsCleared();

        thenNoExceptionOccurred();
        thenV1CacheIsEmpty();
    }

    @Test
    public void testRefresh() {
        givenV1GPIOService();

        whenV1CacheIsRefreshed();

        thenNoExceptionOccurred();
        thenV1CacheIsEmpty();
    }

    @Test
    public void testServiceInitialization() throws IOException {
        givenV1GPIOServiceNotInitialized(DEVICE_FOLDER);
        givenTmpGpioChips();

        whenV1ServiceIsInitialized();
        whenV1ServiceGetAvailablePins();

        thenNoExceptionOccurred();
        thenAvailablePinsIsNotNullOrEmpty();
    }

    @Test
    public void testServiceInitializationWithNotExistingDeviceFolder() throws IOException {
        givenV1GPIOServiceNotInitialized("not_existing_folder");
        givenTmpGpioChips();

        whenV1ServiceIsInitialized();
        whenV1ServiceGetAvailablePins();

        thenNoExceptionOccurred();
        thenAvailablePinsIsEmpty();
    }

    @Test
    public void testServiceInitializationWithNotExistingGpioChips() throws IOException {
        givenV1GPIOServiceNotInitialized("/opt/");
        givenTmpGpioChips();

        whenV1ServiceIsInitialized();
        whenV1ServiceGetAvailablePins();

        thenNoExceptionOccurred();
        thenAvailablePinsIsEmpty();
    }

    @Test
    public void testServiceInitializationWithWrongPinName() throws IOException {
        givenV1GPIOServiceNotInitialized(DEVICE_FOLDER);
        givenTmpGpioChips(3);

        whenV1ServiceIsInitialized();
        whenV1ServiceGetAvailablePins();

        thenNoExceptionOccurred();
        thenAvailablePinsIsEmpty();
    }

    @Test
    public void testServiceInitializationWithEmptyPinName() throws IOException {
        givenV1GPIOServiceNotInitialized(DEVICE_FOLDER);
        givenTmpGpioChips(4);

        whenV1ServiceIsInitialized();
        whenV1ServiceGetAvailablePins();

        thenNoExceptionOccurred();
        thenAvailablePinsIsEmpty();
    }

    @Test
    public void testServiceInitializationWithNullPinName() throws IOException {
        givenV1GPIOServiceNotInitialized(DEVICE_FOLDER);
        givenTmpGpioChips(5);

        whenV1ServiceIsInitialized();
        whenV1ServiceGetAvailablePins();

        thenNoExceptionOccurred();
        thenAvailablePinsIsEmpty();
    }

    /*
     * Given
     */

    private void givenV1GPIOService() {
        this.v1Service = new LibGpiodV1GPIOService() {

            @Override
            public void initialize() {
                this.availablePins.put("GPIO0_1", 1);
                this.availablePins.put("GPIO2_3", 2003);
                this.availablePins.put("GPIO5_23", 5023);
                this.initialized.set(true);
            }

            @Override
            protected String getDeviceFolderPath() {
                return DEVICE_FOLDER;
            }
        };
    }

    private void givenV1GPIOServiceNotInitialized(String deviceFolderPath) {
        this.v1Service = new LibGpiodV1GPIOService() {

            @Override
            protected String getDeviceFolderPath() {
                return deviceFolderPath;
            }
        };
    }

    private void givenTmpGpioChips() throws IOException {
        for (int i = 0; i < 3; i++) {
            try {
                Path newFilePath = Paths.get(DEVICE_FOLDER + "gpiochip" + i);
                Files.createFile(newFilePath);
            } catch (FileAlreadyExistsException e) {
                // Ignore if file already exists
            }
        }
    }

    private void givenTmpGpioChips(int gpioChipNumber) throws IOException {
        try {
            Path newFilePath = Paths.get(DEVICE_FOLDER + "gpiochip" + gpioChipNumber);
            Files.createFile(newFilePath);
        } catch (FileAlreadyExistsException e) {
            // Ignore if file already exists
        }
    }

    /*
     * When
     */

    private void whenV1ServiceGetPinByName(String pinName) {
        try {
            this.resultPin = this.v1Service.getPinByName(pinName);
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    private void whenV1ServiceGetPinByNameAgain(String pinName) {
        try {
            this.resultPinAgain = this.v1Service.getPinByName(pinName);
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    private void whenV1ServiceGetPinByName(String pinName, KuraGPIODirection direction, KuraGPIOMode mode,
            KuraGPIOTrigger trigger) {
        try {
            this.resultPin = this.v1Service.getPinByName(pinName, direction, mode, trigger);
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    private void whenV1ServiceGetPinByTerminal(int pinTerminal) {
        try {
            this.resultPin = this.v1Service.getPinByTerminal(pinTerminal);
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    private void whenV1ServiceGetPinByTerminalAgain(int pinTerminal) {
        try {
            this.resultPinAgain = this.v1Service.getPinByTerminal(pinTerminal);
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    private void whenV1ServiceGetPinByTerminal(int pinTerminal, KuraGPIODirection direction, KuraGPIOMode mode,
            KuraGPIOTrigger trigger) {
        try {
            this.resultPin = this.v1Service.getPinByTerminal(pinTerminal, direction, mode, trigger);
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    private void whenV1ServiceGetAvailablePins() {
        try {
            this.resultPins = this.v1Service.getAvailablePins();
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    private void whenV1CacheIsCleared() {
        try {
            this.v1Service.clearCache();
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    private void whenV1CacheIsRefreshed() {
        try {
            this.v1Service.refresh();
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    private void whenV1ServiceIsInitialized() {
        try {
            this.v1Service.initialize();
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    /*
     * Then
     */

    private void thenPinIsNotNull() {
        assertNotNull(this.resultPin);
    }

    private void thenPinIsNull() {
        assertNull(this.resultPin);
    }

    private void thenAvailablePinsIsNotNullOrEmpty() {
        assertNotNull(this.resultPins);
        assertFalse(this.resultPins.isEmpty());
    }

    private void thenAvailablePinsIsEmpty() {
        assertTrue(this.resultPins == null || this.resultPins.isEmpty());
    }

    private void thenV1CacheIsEmpty() {
        assertTrue(this.v1Service.pinCache.isEmpty());
    }

    private void thenPinIs(String pinName, KuraGPIODirection direction, KuraGPIOMode mode, KuraGPIOTrigger trigger) {
        assertEquals(pinName, this.resultPin.getName());
        assertEquals(direction, this.resultPin.getDirection());
        assertEquals(mode, this.resultPin.getMode());
        assertEquals(trigger, this.resultPin.getTrigger());
    }

    private void thenPinIs(int pinTerminal, KuraGPIODirection direction, KuraGPIOMode mode, KuraGPIOTrigger trigger) {
        assertEquals(pinTerminal, this.resultPin.getIndex());
        assertEquals(direction, this.resultPin.getDirection());
        assertEquals(mode, this.resultPin.getMode());
        assertEquals(trigger, this.resultPin.getTrigger());
    }

    private void thenPinsAreSame() {
        assertEquals(this.resultPin, this.resultPinAgain);
    }

}