/*******************************************************************************
 * Copyright (c) 2025 Eurotech and/or its affiliates and others
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *  Eurotech
 *******************************************************************************/
/* Some portions generated by generative AI */
package org.eclipse.kura.linux.gpio.libgpiod1;

import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.mockStatic;
import static org.mockito.Mockito.when;

import java.io.IOException;

import org.eclipse.kura.gpio.KuraClosedDeviceException;
import org.eclipse.kura.gpio.KuraGPIODirection;
import org.eclipse.kura.gpio.KuraGPIOMode;
import org.eclipse.kura.gpio.KuraGPIOTrigger;
import org.eclipse.kura.gpio.KuraUnavailableDeviceException;
import org.eclipse.kura.linux.gpio.libgpiod.StepsCollection;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.mockito.MockedStatic;

import com.sun.jna.Native;
import com.sun.jna.Pointer;

public class LibGpiodV1PinTest extends StepsCollection {

    private MockedStatic<Native> nativeMock;
    private LibGpiodV1Native nativeInterfaceMock;
    private MockedStatic<LibGpiodV1NativeWrapper> nativeInterfaceWrapperMock;

    @Before
    public void setup() {
        this.nativeMock = mockStatic(Native.class);
        this.nativeInterfaceMock = mock(LibGpiodV1Native.class);
        this.nativeMock.when(() -> Native.load("gpiod", LibGpiodV1Native.class)).thenReturn(this.nativeInterfaceMock);
        this.nativeInterfaceWrapperMock = mockStatic(LibGpiodV1NativeWrapper.class);
        this.nativeInterfaceWrapperMock.when(() -> LibGpiodV1NativeWrapper.getInstance())
                .thenReturn(this.nativeInterfaceMock);

        Pointer chip0 = Pointer.createConstant(1);
        when(this.nativeInterfaceMock.gpiod_chip_open("/dev/gpiochip0")).thenReturn(chip0);
        when(this.nativeInterfaceMock.gpiod_chip_num_lines(chip0)).thenReturn(16);
        Pointer chip2 = Pointer.createConstant(2);
        when(this.nativeInterfaceMock.gpiod_chip_open("/dev/gpiochip2")).thenReturn(chip2);
        when(this.nativeInterfaceMock.gpiod_chip_num_lines(chip2)).thenReturn(32);
        Pointer line4 = Pointer.createConstant(4);
        when(this.nativeInterfaceMock.gpiod_chip_get_line(chip2, 4)).thenReturn(line4);
        when(this.nativeInterfaceMock.gpiod_line_is_used(line4)).thenReturn(false);
        when(this.nativeInterfaceMock.gpiod_line_request_input_flags(line4, "LibGpiodV1PinDriver", 32)).thenReturn(1);
        when(this.nativeInterfaceMock.gpiod_line_request_output_flags(line4, "LibGpiodV1PinDriver", 1, 2))
                .thenReturn(1);
        when(this.nativeInterfaceMock.gpiod_line_get_value(line4)).thenReturn(1);
        Pointer chip5 = Pointer.createConstant(5);
        when(this.nativeInterfaceMock.gpiod_chip_open("/dev/gpiochip5")).thenReturn(chip5);
        when(this.nativeInterfaceMock.gpiod_chip_num_lines(chip5)).thenReturn(64);
        Pointer line6 = Pointer.createConstant(6);
        when(this.nativeInterfaceMock.gpiod_chip_get_line(chip5, 6)).thenReturn(line6);
        when(this.nativeInterfaceMock.gpiod_line_request_input_flags(line6, "LibGpiodV1PinDriver", 32)).thenReturn(-1);
        Pointer line7 = Pointer.createConstant(7);
        when(this.nativeInterfaceMock.gpiod_chip_get_line(chip5, 7)).thenReturn(line7);
        when(this.nativeInterfaceMock.gpiod_line_request_output_flags(line7, "LibGpiodV1PinDriver", 0, 2))
                .thenReturn(-1);
    }

    @After
    public void cleanup() {
        this.nativeMock.close();
        this.nativeInterfaceWrapperMock.close();
    }

    @Test
    public void testV1PinCreation() {
        givenV1Pin("GPIO_01", 1003);

        thenV1PinIsCreated();
        thenV1PinHasCorrectParameters("GPIO_01", 1003, KuraGPIODirection.INPUT, KuraGPIOMode.INPUT_PULL_UP,
                KuraGPIOTrigger.NONE);
    }

    @Test
    public void testV1PinCreationWithParameters() {
        givenV1Pin("GPIO_02", 2004, KuraGPIODirection.OUTPUT, KuraGPIOMode.OUTPUT_PUSH_PULL,
                KuraGPIOTrigger.BOTH_EDGES);

        thenV1PinIsCreated();
        thenV1PinHasCorrectParameters("GPIO_02", 2004, KuraGPIODirection.OUTPUT, KuraGPIOMode.OUTPUT_PUSH_PULL,
                KuraGPIOTrigger.BOTH_EDGES);
    }

    @Test
    public void testPinInitiallyNotOpen() {
        givenV1Pin("GPIO_01", 1001);

        thenV1PinIsCreated();
        thenV1PinIsNotOpen();
    }

    @Test
    public void testOpenPin() {
        givenV1Pin("GPIO_01", 2004);

        whenV1PinIsOpened();

        thenNoExceptionOccurred();
        thenV1PinIsOpen();
    }

    @Test
    public void testClosePin() {
        givenV1Pin("GPIO_01", 2004);

        whenV1PinIsOpened();
        whenV1PinIsClosed();

        thenNoExceptionOccurred();
        thenV1PinIsNotOpen();

    }

    @Test
    public void testGetValueFromInputPin() {
        givenV1Pin("GPIO_01", 2004, KuraGPIODirection.INPUT, KuraGPIOMode.INPUT_PULL_UP, KuraGPIOTrigger.NONE);

        whenV1PinIsOpened();
        whenV1PinValueIsRead();

        thenNoExceptionOccurred();
        thenV1PinValueIsBoolean();
        thenV1PinValueReadIs(true);
    }

    @Test
    public void testGetValueFromClosedPin() {
        givenV1Pin("GPIO_01", 2004, KuraGPIODirection.INPUT, KuraGPIOMode.INPUT_PULL_UP, KuraGPIOTrigger.NONE);

        whenV1PinValueIsRead();

        thenExceptionOccurred(KuraClosedDeviceException.class);
    }

    @Test
    public void testGetValueFromPinNotReserved() {
        givenV1Pin("GPIO_01", 5006, KuraGPIODirection.INPUT, KuraGPIOMode.INPUT_PULL_UP, KuraGPIOTrigger.NONE);

        whenV1PinIsOpened();
        whenV1PinValueIsRead();

        thenExceptionOccurred(KuraUnavailableDeviceException.class);
    }

    @Test
    public void testSetValueOnOutputPin() {
        givenV1Pin("GPIO_01", 2004, KuraGPIODirection.OUTPUT, KuraGPIOMode.OUTPUT_PUSH_PULL, KuraGPIOTrigger.NONE);

        whenV1PinIsOpened();
        whenV1PinValueIsSetTo(true);
        whenV1PinValueIsSetTo(false);

        thenNoExceptionOccurred();
    }

    @Test
    public void testSetValueOnInputPin() {
        givenV1Pin("GPIO_01", 2004, KuraGPIODirection.INPUT, KuraGPIOMode.INPUT_PULL_UP, KuraGPIOTrigger.NONE);

        whenV1PinIsOpened();
        whenV1PinValueIsSetTo(true);

        thenExceptionOccurred(IOException.class);
    }

    @Test
    public void testSetValueOnClosedPin() {
        givenV1Pin("GPIO_01", 2004, KuraGPIODirection.OUTPUT, KuraGPIOMode.OUTPUT_PUSH_PULL, KuraGPIOTrigger.NONE);

        whenV1PinValueIsSetTo(true);

        thenExceptionOccurred(KuraClosedDeviceException.class);
    }

    @Test
    public void testSetValueOnPinNotReserved() {
        givenV1Pin("GPIO_01", 5007, KuraGPIODirection.OUTPUT, KuraGPIOMode.OUTPUT_PUSH_PULL, KuraGPIOTrigger.NONE);

        whenV1PinIsOpened();
        whenV1PinValueIsSetTo(true);

        thenExceptionOccurred(KuraUnavailableDeviceException.class);
    }

    @Test
    public void testAddPinStatusListenerWithNullListener() {
        givenV1Pin("GPIO_01", 2004, KuraGPIODirection.INPUT, KuraGPIOMode.INPUT_PULL_UP, KuraGPIOTrigger.BOTH_EDGES);

        whenV1PinIsOpened();
        whenV1PinAddPinStatusListener(null);

        thenExceptionOccurred(IllegalArgumentException.class);
    }

    @Test
    public void testAddPinStatusListenerOnClosedPin() {
        givenV1Pin("GPIO_01", 2004, KuraGPIODirection.INPUT, KuraGPIOMode.INPUT_PULL_UP, KuraGPIOTrigger.BOTH_EDGES);
        givenPinStatusListener();

        whenV1PinAddPinStatusListener(this.pinStatusListener);

        thenExceptionOccurred(KuraClosedDeviceException.class);
    }

    @Test
    public void testAddPinStatusListener() {
        givenV1Pin("GPIO_01", 2004, KuraGPIODirection.INPUT, KuraGPIOMode.INPUT_PULL_UP, KuraGPIOTrigger.BOTH_EDGES);
        givenPinStatusListener();

        whenV1PinIsOpened();
        whenV1PinAddPinStatusListener(this.pinStatusListener);

        thenNoExceptionOccurred();
    }

    @Test
    public void testRemovePinStatusListenerWithNullListener() {
        givenV1Pin("GPIO_01", 1, KuraGPIODirection.INPUT, KuraGPIOMode.INPUT_PULL_UP, KuraGPIOTrigger.BOTH_EDGES);

        try {
            this.v1Pin.removePinStatusListener(null);
        } catch (Exception e) {
            this.occurredException = e;
        }

        thenExceptionOccurred(IllegalArgumentException.class);
    }

    @Test
    public void testRemovePinStatusListener() {
        givenV1Pin("GPIO_01", 2004, KuraGPIODirection.INPUT, KuraGPIOMode.INPUT_PULL_UP, KuraGPIOTrigger.BOTH_EDGES);
        givenPinStatusListener();

        whenV1PinRemovePinStatusListener(this.pinStatusListener);

        thenNoExceptionOccurred();
    }

    @Test
    public void testPinIndexCalculation() {
        givenV1Pin("GPIO_01", 2004);

        thenV1PinIndexIs(2004);
    }

    @Test
    public void testMultipleOpenCalls() {
        givenV1Pin("GPIO_01", 2004);

        whenV1PinIsOpened();
        whenV1PinIsOpened();
        whenV1PinIsOpened();

        thenNoExceptionOccurred();
        thenV1PinIsOpen();
    }

    @Test
    public void testMultipleCloseCalls() {
        givenV1Pin("GPIO_01", 2004);

        whenV1PinIsOpened();
        whenV1PinIsClosed();
        whenV1PinIsClosed();
        whenV1PinIsClosed();

        thenNoExceptionOccurred();
        thenV1PinIsNotOpen();
    }
}