/*******************************************************************************
 * Copyright (c) 2025 Eurotech and/or its affiliates and others
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *  Eurotech
 *******************************************************************************/
/* Some portions generated by generative AI */
package org.eclipse.kura.linux.gpio.libgpiod1;

import static org.junit.Assert.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.mockStatic;

import org.eclipse.kura.gpio.KuraGPIODirection;
import org.eclipse.kura.gpio.KuraGPIOMode;
import org.eclipse.kura.gpio.KuraGPIOTrigger;
import org.eclipse.kura.linux.gpio.libgpiod.StepsCollection;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.mockito.MockedStatic;

import com.sun.jna.Native;

public class LibGpiodV1GPIOServiceTest extends StepsCollection {

    private MockedStatic<Native> nativeMock;
    private LibGpiodV1Native nativeInterfaceMock;

    @Before
    public void setup() {
        this.nativeMock = mockStatic(Native.class);
        this.nativeInterfaceMock = mock(LibGpiodV1Native.class);
        this.nativeMock.when(() -> Native.load("gpiod", LibGpiodV1Native.class)).thenReturn(this.nativeInterfaceMock);
    }

    @After
    public void cleanup() {
        this.nativeMock.close();
    }

    @Test
    public void testGetPinByNameWithNullName() {
        givenV1GPIOService();

        whenV1ServiceGetPinByName(null);

        thenExceptionOccurred(IllegalArgumentException.class);
    }

    @Test
    public void testGetPinByNameWithEmptyName() {
        givenV1GPIOService();

        whenV1ServiceGetPinByName("");

        thenExceptionOccurred(IllegalArgumentException.class);
    }

    @Test
    public void testGetPinByNameWithWhitespaceOnlyName() {
        givenV1GPIOService();

        whenV1ServiceGetPinByName("   ");

        thenExceptionOccurred(IllegalArgumentException.class);
    }

    @Test
    public void testGetPinByNameWithValidNameAndDefaultParameters() {
        givenV1GPIOService();

        whenV1ServiceGetPinByName("GPIO0");

        thenNoExceptionOccurred();
        thenPinIsNotNull();
        thenPinIs("GPIO0", KuraGPIODirection.INPUT, KuraGPIOMode.INPUT_PULL_UP, KuraGPIOTrigger.NONE);
    }

    @Test
    public void testGetPinByNameWithValidNameAndParameters() {
        givenV1GPIOService();

        whenV1ServiceGetPinByName("GPIO0", KuraGPIODirection.OUTPUT, KuraGPIOMode.OUTPUT_OPEN_DRAIN,
                KuraGPIOTrigger.NONE);

        thenNoExceptionOccurred();
        thenPinIsNotNull();
        thenPinIs("GPIO0", KuraGPIODirection.OUTPUT, KuraGPIOMode.OUTPUT_OPEN_DRAIN, KuraGPIOTrigger.NONE);
    }

    @Test
    public void testGetPinByTerminalWithNegativeTerminal() {
        givenV1GPIOService();

        whenV1ServiceGetPinByTerminal(-1);

        thenExceptionOccurred(IllegalArgumentException.class);
    }

    @Test
    public void testGetPinByTerminalWithValidTerminal() {
        givenV1GPIOService();

        whenV1ServiceGetPinByTerminal(2003);

        thenNoExceptionOccurred();
        thenPinIsNotNull();
        thenPinIs(2003, KuraGPIODirection.OUTPUT, KuraGPIOMode.OUTPUT_OPEN_DRAIN, KuraGPIOTrigger.NONE);
    }

    @Test
    public void testGetPinByTerminalWithParameters() {
        givenV1GPIOService();

        whenV1ServiceGetPinByTerminal(2003, KuraGPIODirection.OUTPUT, KuraGPIOMode.OUTPUT_PUSH_PULL,
                KuraGPIOTrigger.NONE);

        thenNoExceptionOccurred();
        thenPinIsNotNull();
        thenPinIs(2003, KuraGPIODirection.OUTPUT, KuraGPIOMode.OUTPUT_OPEN_DRAIN, KuraGPIOTrigger.NONE);
    }

    @Test
    public void testGetAvailablePins() {
        givenV1GPIOService();

        whenV1ServiceGetAvailablePins();

        thenNoExceptionOccurred();
        thenAvailablePinsIsNotNullOrEmpty();
    }

    @Test
    public void testGetPinFromCache() {
        givenV1GPIOService();

        whenV1ServiceGetPinByName("GPIO_10");
        whenV1ServiceGetPinByNameAgain("GPIO_10");

        thenNoExceptionOccurred();
        thenPinsAreSame();
    }

    @Test
    public void testClearCache() {
        givenV1GPIOService();

        whenV1CacheIsCleared();

        thenNoExceptionOccurred();
        thenV1CacheIsEmpty();
    }

    @Test
    public void testRefresh() {
        givenV1GPIOService();

        whenV1CacheIsRefreshed();

        thenNoExceptionOccurred();
        thenV1CacheIsEmpty();
    }

    protected void thenV1CacheIsEmpty() {
        assertTrue(this.v1Service.pinCache.isEmpty());
    }

}