/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.internal.rest.provider;

import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoMoreInteractions;
import static org.mockito.Mockito.when;

import java.util.Collections;

import org.junit.Test;

import jakarta.ws.rs.container.ContainerResponseContext;
import jakarta.ws.rs.core.MediaType;

public class ErrorEntityFilterTest {

    private ContainerResponseContext response;

    @Test
    public void missingErrorEntityIsFilled() {
        givenResponse(404, false);

        whenResponseIsFiltered();

        thenErrorEntityIsAdded("Not Found");
    }

    @Test
    public void unknownStatusGetsSafeFallback() {
        givenResponse(499, false);

        whenResponseIsFiltered();

        thenErrorEntityIsAdded("Request failed");
    }

    @Test
    public void existingErrorEntityIsPreserved() {
        givenResponse(400, true);

        whenResponseIsFiltered();

        thenResponseIsUnchanged(true);
    }

    @Test
    public void successfulResponseIsPreserved() {
        givenResponse(204, false);

        whenResponseIsFiltered();

        thenResponseIsUnchanged(false);
    }

    @Test
    public void redirectIsPreserved() {
        givenResponse(302, false);

        whenResponseIsFiltered();

        thenResponseIsUnchanged(false);
    }

    private void givenResponse(int status, boolean hasEntity) {
        this.response = mock(ContainerResponseContext.class);
        when(this.response.getStatus()).thenReturn(status);
        when(this.response.hasEntity()).thenReturn(hasEntity);
    }

    private void whenResponseIsFiltered() {
        new ErrorEntityFilter().filter(null, this.response);
    }

    private void thenErrorEntityIsAdded(String message) {
        verify(this.response).getStatus();
        verify(this.response).hasEntity();
        verify(this.response).setEntity(Collections.singletonMap("message", message), null, MediaType.APPLICATION_JSON_TYPE);
        verifyNoMoreInteractions(this.response);
    }

    private void thenResponseIsUnchanged(boolean entityChecked) {
        verify(this.response).getStatus();
        if (entityChecked) {
            verify(this.response).hasEntity();
        }
        verifyNoMoreInteractions(this.response);
    }
}
