/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.container.orchestration.provider;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import com.github.dockerjava.api.DockerClient;
import java.util.Optional;
import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.KuraException;
import org.eclipse.kura.container.orchestration.provider.impl.ContainerOrchestrationServiceImpl;
import org.junit.Test;
import org.mockito.Mockito;

public class ContainerOrchestrationServiceImplFailureTest {

    private static final String CONTAINER_ID = "1f12d3s23";
    private static final String IMAGE_ID = "y456y5146hrth";

    private final ContainerOrchestrationServiceImpl dockerService = new ContainerOrchestrationServiceImpl();
    private DockerClient dockerClient;
    private Optional<KuraException> exception = Optional.empty();

    @Test
    public void startContainerFailureIsReportedAsOsCommandError() {
        givenDockerClient();
        givenStartContainerCommandFails();

        whenContainerIsStarted();

        thenKuraExceptionIsThrownWithCode(KuraErrorCode.OS_COMMAND_ERROR);
    }

    @Test
    public void stopContainerFailureIsReportedAsOsCommandError() {
        givenDockerClient();
        givenListContainersCommandFails();

        whenContainerIsStopped();

        thenKuraExceptionIsThrownWithCode(KuraErrorCode.OS_COMMAND_ERROR);
    }

    @Test
    public void deleteContainerFailureIsReportedAsOsCommandError() {
        givenDockerClient();
        givenListContainersCommandFails();

        whenContainerIsDeleted();

        thenKuraExceptionIsThrownWithCode(KuraErrorCode.OS_COMMAND_ERROR);
    }

    @Test
    public void deleteImageFailureIsReportedAsOsCommandError() {
        givenDockerClient();
        givenRemoveImageCommandFails();

        whenImageIsDeleted();

        thenKuraExceptionIsThrownWithCode(KuraErrorCode.OS_COMMAND_ERROR);
    }

    private void givenDockerClient() {
        this.dockerClient = mock(DockerClient.class, Mockito.RETURNS_DEEP_STUBS);
        this.dockerService.setDockerClient(this.dockerClient);
    }

    private void givenStartContainerCommandFails() {
        when(this.dockerClient.startContainerCmd(CONTAINER_ID).exec())
                .thenThrow(new IllegalStateException("container is already running"));
    }

    private void givenListContainersCommandFails() {
        when(this.dockerClient.listContainersCmd().withShowAll(true).exec())
                .thenThrow(new IllegalStateException("docker daemon unavailable"));
    }

    private void givenRemoveImageCommandFails() {
        when(this.dockerClient.removeImageCmd(IMAGE_ID).exec())
                .thenThrow(new IllegalStateException("image is in use by a container"));
    }

    private void whenContainerIsStarted() {
        try {
            this.dockerService.startContainer(CONTAINER_ID);
        } catch (KuraException e) {
            this.exception = Optional.of(e);
        }
    }

    private void whenContainerIsStopped() {
        try {
            this.dockerService.stopContainer(CONTAINER_ID);
        } catch (KuraException e) {
            this.exception = Optional.of(e);
        }
    }

    private void whenContainerIsDeleted() {
        try {
            this.dockerService.deleteContainer(CONTAINER_ID);
        } catch (KuraException e) {
            this.exception = Optional.of(e);
        }
    }

    private void whenImageIsDeleted() {
        try {
            this.dockerService.deleteImage(IMAGE_ID);
        } catch (KuraException e) {
            this.exception = Optional.of(e);
        }
    }

    private void thenKuraExceptionIsThrownWithCode(KuraErrorCode expectedCode) {
        assertTrue("a KuraException was expected", this.exception.isPresent());
        assertEquals(expectedCode, this.exception.get().getCode());
    }
}
