/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 ******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.openapi;

import java.util.Iterator;
import java.util.Locale;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonAutoDetect.Visibility;
import com.fasterxml.jackson.annotation.PropertyAccessor;
import com.fasterxml.jackson.databind.ObjectMapper;

import io.swagger.v3.core.converter.AnnotatedType;
import io.swagger.v3.core.converter.ModelConverter;
import io.swagger.v3.core.converter.ModelConverterContext;
import io.swagger.v3.core.converter.ModelConverters;
import io.swagger.v3.core.jackson.ModelResolver;
import io.swagger.v3.core.util.Json;
import io.swagger.v3.jaxrs2.Reader;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.media.Schema;

public class KuraOpenApiReader extends Reader {

    private static final String UNCONSTRAINED = "x-kura-unconstrained";

    @Override
    public OpenAPI read(Set<Class<?>> classes) {
        final ObjectMapper mapper = Json.mapper().copy();
        mapper.setVisibility(PropertyAccessor.ALL, Visibility.NONE);
        mapper.setVisibility(PropertyAccessor.FIELD, Visibility.ANY);
        final ModelResolver resolver = new ModelResolver(mapper) {
            @Override
            public Schema resolve(AnnotatedType type, ModelConverterContext context, Iterator<ModelConverter> chain) {
                if (type.getType() != null && mapper.constructType(type.getType()).isJavaLangObject()) {
                    final Schema<?> schema = new Schema<>();
                    schema.addExtension(UNCONSTRAINED, true);
                    return schema;
                }
                return super.resolve(type, context, chain);
            }
        };
        final ModelConverters converters = ModelConverters.getInstance();
        converters.addConverter(resolver);
        try {
            final OpenAPI result = super.read(classes);
            result.getComponents().getSchemas().values().forEach(this::normalizeSchema);
            result.getPaths().forEach((path, item) -> item.readOperationsMap().forEach((method, operation) -> {
                operation.setOperationId(method.name().toLowerCase(Locale.ROOT) + "_"
                        + path.replaceAll("[^a-zA-Z0-9]+", "_").replaceAll("^_|_$", ""));
            }));
            return result;
        } finally {
            converters.removeConverter(resolver);
        }
    }

    private void normalizeSchema(Schema<?> schema) {
        if (schema.getExtensions() != null && Boolean.TRUE.equals(schema.getExtensions().remove(UNCONSTRAINED))) {
            schema.setType(null);
            schema.setNullable(true);
        }
        if (schema.getProperties() != null) {
            schema.getProperties().values().forEach(this::normalizeSchema);
        }
        if (schema.getItems() != null) {
            normalizeSchema(schema.getItems());
        }
        if (schema.getAdditionalProperties() instanceof Schema<?> additionalProperties) {
            normalizeSchema(additionalProperties);
        }
    }
}
