/*******************************************************************************
 * Copyright (c) 2025, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
/* Some portions generated by generative AI */
package org.eclipse.kura.linux.gpio.libgpiod;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.atomic.AtomicBoolean;

import org.eclipse.kura.gpio.KuraClosedDeviceException;
import org.eclipse.kura.gpio.KuraGPIODirection;
import org.eclipse.kura.gpio.KuraGPIOMode;
import org.eclipse.kura.gpio.KuraGPIOTrigger;
import org.eclipse.kura.gpio.PinStatusListener;

import com.sun.jna.Pointer;

/**
 * Common methods for libgpiod-based GPIO pin implementations
 */
public abstract class LibGpiodPin {

    protected static final int DEFAULT_TIMEOUT_SEC = 1;
    private static final ExecutorService EXECUTOR = Executors.newCachedThreadPool(runnable -> {
        Thread thread = new Thread(runnable, "GPIO-EventMonitor");
        thread.setDaemon(true);
        return thread;
    });

    protected final String chipPath;
    protected final int offset;
    protected final String pinName;
    protected final KuraGPIODirection direction;
    protected final KuraGPIOMode mode;
    protected final KuraGPIOTrigger trigger;

    protected Pointer chip;

    protected final AtomicBoolean isOpen = new AtomicBoolean(false);
    protected final AtomicBoolean isMonitoring = new AtomicBoolean(false);

    protected List<PinStatusListener> listeners = Collections.synchronizedList(new ArrayList<>());
    private Future<?> monitoringTask;

    protected LibGpiodPin(String chipPath, int offset, KuraGPIODirection direction, KuraGPIOMode mode,
            KuraGPIOTrigger trigger, String pinName) {
        this.chipPath = chipPath;
        this.offset = offset;
        this.direction = direction;
        this.mode = mode;
        this.trigger = trigger;
        this.pinName = pinName;
    }

    public boolean isOpen() {
        return this.isOpen.get();
    }

    public String getName() {
        return this.pinName;
    }

    public int getIndex() {
        return extractChipNumber(this.chipPath) * 1000 + this.offset;
    }

    public KuraGPIODirection getDirection() {
        return this.direction;
    }

    public KuraGPIOMode getMode() {
        return this.mode;
    }

    public KuraGPIOTrigger getTrigger() {
        return this.trigger;
    }

    public void addPinStatusListener(PinStatusListener listener) throws KuraClosedDeviceException, IOException {
        if (listener == null) {
            throw new IllegalArgumentException("Listener cannot be null");
        }

        if (!this.isOpen.get()) {
            throw new KuraClosedDeviceException(this.pinName);
        }

        synchronized (this.listeners) {
            if (this.listeners.contains(listener)) {
                return;
            }
            this.listeners.add(listener);
        }

        if (shouldMonitorEvents()) {
            startEventMonitoring();
        }
    }

    private boolean shouldMonitorEvents() {
        return this.direction == KuraGPIODirection.INPUT && this.trigger != KuraGPIOTrigger.NONE
                && this.trigger != KuraGPIOTrigger.HIGH_LEVEL && this.trigger != KuraGPIOTrigger.LOW_LEVEL
                && this.trigger != KuraGPIOTrigger.BOTH_LEVELS;
    }

    private void startEventMonitoring() {
        if (this.isMonitoring.compareAndSet(false, true)) {
            this.monitoringTask = EXECUTOR.submit(this::monitorEvents);
        }
    }

    protected abstract void monitorEvents();

    protected void stopEventMonitoring() {
        if (this.isMonitoring.compareAndSet(true, false) && this.monitoringTask != null) {
            this.monitoringTask.cancel(true);
            try {
                Thread.sleep(DEFAULT_TIMEOUT_SEC * 2000L);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            }
            this.monitoringTask = null;
        }
    }

    public void removePinStatusListener(PinStatusListener listener) {
        if (listener == null) {
            throw new IllegalArgumentException("Listener cannot be null");
        }

        synchronized (this.listeners) {
            if (!this.listeners.contains(listener)) {
                return;
            }
            this.listeners.remove(listener);

            if (this.listeners.isEmpty()) {
                stopEventMonitoring();
            }
        }
    }

    public static int extractChipNumber(String chipName) {
        try {
            return Integer.parseInt(chipName.replaceAll("\\D", ""));
        } catch (NumberFormatException e) {
            return 0;
        }
    }

    @Override
    public String toString() {
        return String.format("LibGpiodPin{chip=%s, offset=%d, name=%s, direction=%s, mode=%s, trigger=%s}",
                this.chipPath, this.offset, this.pinName, this.direction, this.mode, this.trigger);
    }
}