/*******************************************************************************
 * Copyright (c) 2025 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
/* Some portions generated by generative AI */
package org.eclipse.kura.linux.gpio.libgpiod;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.sun.jna.Library;
import com.sun.jna.Native;

/**
 * Utility class for detecting libgpiod version and capabilities
 */
public class LibGpiodVersionDetector {

    /**
     * Minimal interface to detect libgpiod version
     */
    private interface VersionDetectionInterface extends Library {

        String gpiod_version_string();

        String gpiod_api_version();
    }

    private static final Logger logger = LoggerFactory.getLogger(LibGpiodVersionDetector.class);
    private static VersionDetectionInterface versionInterface;
    private static String detectedVersion = "unknown";
    private static LibGpiodVersion libGpiodVersion = LibGpiodVersion.UNKNOWN;

    public enum LibGpiodVersion {
        V1_6_X,
        V2_X_X,
        UNKNOWN
    }

    static {
        detectVersion();
    }

    private LibGpiodVersionDetector() {
        // Empty private constructor for static utility class
    }

    /**
     * Get the detected libgpiod version
     */
    public static LibGpiodVersion getVersion() {
        return libGpiodVersion;
    }

    /**
     * Get the detected version string
     */
    public static String getVersionString() {
        return detectedVersion;
    }

    // /**
    // * Check if the current libgpiod version is v1.6.x compatible
    // */
    // public static boolean isV1Compatible() {
    // return libGpiodVersion == LibGpiodVersion.V1_6_X;
    // }
    //
    // /**
    // * Check if the current libgpiod version is v2.x.x compatible
    // */
    // public static boolean isV2Compatible() {
    // return libGpiodVersion == LibGpiodVersion.V2_X_X;
    // }

    /**
     * Detect the libgpiod version by attempting to load and call version functions
     */
    private static void detectVersion() {
        // try {
        versionInterface = Native.load("gpiod", VersionDetectionInterface.class);

        // Try v2.x API first (gpiod_api_version was introduced in v2.x)
        try {
            detectedVersion = versionInterface.gpiod_api_version();
            if (detectedVersion != null && !detectedVersion.trim().isEmpty()) {
                libGpiodVersion = LibGpiodVersion.V2_X_X;
                return;
            }
        } catch (Error e) {
            logger.debug("gpiod_api_version() not found, trying v1.x API...");
        }

        // Try v1.x API (gpiod_version_string)
        try {
            detectedVersion = versionInterface.gpiod_version_string();
            if (detectedVersion != null && !detectedVersion.trim().isEmpty()) {
                // Parse version to determine if it's 1.6.x
                if (isVersion1_6_X(detectedVersion)) {
                    libGpiodVersion = LibGpiodVersion.V1_6_X;
                    // } else {
                    // libGpiodVersion = LibGpiodVersion.UNKNOWN;
                }
            }
        } catch (Error e) {
            logger.debug("gpiod_version_string() not found, unable to detect version...");
        }

        // Fallback: try to detect by testing API features really needed??????
        // detectByApiFeatures();

        // } catch (Exception e) {
        // detectedVersion = "unknown";
        // libGpiodVersion = LibGpiodVersion.UNKNOWN;
        // }
    }

    // /**
    // * Detect version by testing specific API features
    // */
    // private static void detectByApiFeatures() {
    // // Define interfaces to test specific API features
    // try {
    // // Test for v2.x specific functions
    // interface V2TestInterface extends Library {
    //
    // Pointer gpiod_chip_open(String path);
    //
    // void gpiod_chip_close(Pointer chip);
    //
    // Pointer gpiod_chip_get_info(Pointer chip);
    //
    // Pointer gpiod_line_settings_new();
    //
    // void gpiod_line_settings_free(Pointer settings);
    // }
    //
    // V2TestInterface v2Test = Native.load("gpiod", V2TestInterface.class);
    // Pointer settings = v2Test.gpiod_line_settings_new();
    // if (settings != null) {
    // v2Test.gpiod_line_settings_free(settings);
    // detectedVersion = "2.x.x (detected by API)";
    // libGpiodVersion = LibGpiodVersion.V2_X_X;
    // return;
    // }
    // } catch (Exception e) {
    // // v2.x functions not available
    // }
    //
    // try {
    // // Test for v1.x functions
    // interface V1TestInterface extends Library {
    //
    // Pointer gpiod_chip_open(String path);
    //
    // void gpiod_chip_close(Pointer chip);
    //
    // Pointer gpiod_chip_get_line(Pointer chip, int offset);
    // }
    //
    // V1TestInterface v1Test = Native.load("gpiod", V1TestInterface.class);
    // // Try to open a dummy path to see if the v1.x API works
    // // This will fail, but if the function exists, we know it's v1.x
    // v1Test.gpiod_chip_open("/dev/null"); // This will return null, but won't throw if function exists
    // detectedVersion = "1.6.x (detected by API)";
    // libGpiodVersion = LibGpiodVersion.V1_6_X;
    // return;
    // } catch (Exception e) {
    // // v1.x functions not available either
    // }
    //
    // // If we can't detect, assume unknown
    // detectedVersion = "unknown";
    // libGpiodVersion = LibGpiodVersion.UNKNOWN;
    // }

    /**
     * Check if the version string indicates libgpiod 1.6.x
     */
    private static boolean isVersion1_6_X(String version) {
        if (version == null) {
            return false;
        }

        // Look for version patterns like "1.6.0", "1.6.1", "1.6.2", "1.6.3" ... "1.6.99".
        return version.matches("^1.6.(\\d{1,2})$");
    }

    /**
     * Force a re-detection of the version (useful for testing)
     */
    public static void redetect() {
        versionInterface = null;
        detectedVersion = "unknown";
        libGpiodVersion = LibGpiodVersion.UNKNOWN;
        detectVersion();
    }
}