/*******************************************************************************
 * Copyright (c) 2025 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
/* Some portions generated by generative AI */
package org.eclipse.kura.linux.gpio.libgpiod;

import java.util.Optional;

import org.eclipse.kura.gpio.GPIOService;
import org.eclipse.kura.linux.gpio.libgpiod1.LibGpiodV1GPIOService;
import org.eclipse.kura.linux.gpio.libgpiod2.LibGpiodV2GPIOService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Factory for creating the appropriate GPIOService implementation based on the
 * detected libgpiod version installed on the system.
 *
 * This factory automatically detects whether libgpiod v1.6.x or v2.x.x is
 * installed and returns the corresponding implementation.
 */
public class LibGpiodGPIOServiceFactory {

    private static final Logger logger = LoggerFactory.getLogger(LibGpiodGPIOServiceFactory.class);
    private static final Object lock = new Object();
    private static Optional<GPIOService> instance = Optional.empty();

    private LibGpiodGPIOServiceFactory() {
        // Empty private constructor for static factory class
    }

    /**
     * Get a GPIOService instance appropriate for the installed libgpiod version
     *
     * @return GPIOService instance
     */
    public static Optional<GPIOService> getInstance() {
        if (!instance.isPresent()) {
            synchronized (lock) {
                instance = createService();
            }
        }
        return instance;
    }

    /**
     * Create a new GPIOService instance based on detected libgpiod version
     *
     * @return Optional<GPIOService> instance
     */
    public static Optional<GPIOService> createService() {
        LibGpiodVersionDetector.LibGpiodVersion version = LibGpiodVersionDetector.getVersion();

        switch (version) {
        case V1_6_X:
            return Optional.of(new LibGpiodV1GPIOService());
        case V2_X_X:
            return Optional.of(new LibGpiodV2GPIOService());
        case UNKNOWN:
        default:
            logger.warn(
                    "Unsupported or undetected libgpiod version: {}. Supported versions are 1.6.x and 2.x.x. "
                            + "Please install a compatible version of libgpiod.",
                    LibGpiodVersionDetector.getVersionString());
            return Optional.empty();
        }
    }

}