/*******************************************************************************
 * Copyright (c) 2025 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
/* Some portions generated by generative AI */
package org.eclipse.kura.linux.gpio.libgpiod;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.sun.jna.Library;
import com.sun.jna.Native;

/**
 * Utility class for detecting libgpiod version and capabilities
 */
public class LibGpiodVersionDetector {

    /**
     * Minimal interface to detect libgpiod version
     */
    protected interface VersionDetectionInterface extends Library {

        String gpiod_version_string();

        String gpiod_api_version();
    }

    private static final Logger logger = LoggerFactory.getLogger(LibGpiodVersionDetector.class);
    private VersionDetectionInterface versionInterface;
    private String detectedVersion = "unknown";
    private LibGpiodVersion libGpiodVersion = LibGpiodVersion.UNKNOWN;

    public enum LibGpiodVersion {
        V1_6_X,
        V2_X_X,
        UNKNOWN
    }

    public LibGpiodVersionDetector() {
        detectVersion();
    }

    /**
     * Get the detected libgpiod version
     */
    public LibGpiodVersion getVersion() {
        return this.libGpiodVersion;
    }

    /**
     * Get the detected version string
     */
    public String getVersionString() {
        return this.detectedVersion;
    }

    /**
     * Detect the libgpiod version by attempting to load and call version functions
     */
    private void detectVersion() {
        this.versionInterface = Native.load("gpiod", VersionDetectionInterface.class);

        // Try v2.x API first (gpiod_api_version was introduced in v2.x)
        try {
            this.detectedVersion = this.versionInterface.gpiod_api_version();
            if (this.detectedVersion != null && !this.detectedVersion.trim().isEmpty()) {
                this.libGpiodVersion = LibGpiodVersion.V2_X_X;
                return;
            }
        } catch (Error e) {
            logger.debug("gpiod_api_version() not found, trying v1.x API...");
        }

        // Try v1.x API (gpiod_version_string)
        try {
            this.detectedVersion = this.versionInterface.gpiod_version_string();
            if (this.detectedVersion != null && !this.detectedVersion.trim().isEmpty()
                    && isVersion16X(this.detectedVersion)) {
                this.libGpiodVersion = LibGpiodVersion.V1_6_X;
            }
        } catch (Error e) {
            logger.debug("gpiod_version_string() not found, unable to detect version...");
        }
    }

    /**
     * Check if the version string indicates libgpiod 1.6.x
     */
    protected static boolean isVersion16X(String version) {
        if (version == null) {
            return false;
        }

        // Look for version patterns like "1.6.0", "1.6.1", "1.6.2", "1.6.3" ... "1.6.99".
        return version.matches("^1.6.(\\d{1,2})$");
    }

    /**
     * Force a re-detection of the version (useful for testing)
     */
    public void redetect() {
        this.versionInterface = null;
        this.detectedVersion = "unknown";
        this.libGpiodVersion = LibGpiodVersion.UNKNOWN;
        detectVersion();
    }
}