<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2025 Eurotech and/or its affiliates and others

    This program and the accompanying materials are made
    available under the terms of the Eclipse Public License 2.0
    which is available at https://www.eclipse.org/legal/epl-2.0/

    SPDX-License-Identifier: EPL-2.0

    Contributors:
     Eurotech

-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>distrib</artifactId>
        <groupId>org.eclipse.kura</groupId>
        <version>6.0.0-SNAPSHOT</version>
        <relativePath>..</relativePath>
    </parent>

    <artifactId>docker-base</artifactId>

    <packaging>pom</packaging>

    <properties>
        <kura.basedir>../</kura.basedir>
        <device.name>docker-container-instance</device.name>
        <kura.primary.network.interface># kura.primary.network.interface=eth0</kura.primary.network.interface>
        <os.distribution>docker</os.distribution>
        <os.distribution.version>20.04</os.distribution.version>
        <kura.serialNumber.provider></kura.serialNumber.provider>
        <kura.serialNumber>${device.name}</kura.serialNumber>
        <exclude.linux.plugins>true</exclude.linux.plugins>
        <kura.arch>x86_64</kura.arch>
        <target.device>docker-x86_64-nn</target.device>
        <build.name>${target.device}</build.name>
        <deb.name>kura</deb.name>
        <deb.provides>kura-core (= ${release.version})</deb.provides>
        <deb.architecture>amd64</deb.architecture>
        <skip.resource.copy>false</skip.resource.copy>
    </properties>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-dependency-plugin</artifactId>
            </plugin>
            <plugin>
                <artifactId>maven-resources-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.vafer</groupId>
                <artifactId>jdeb</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>1.7</version>
                <executions>
                    <execution>
                        <id>docker-x86_64-nn-build-container</id>
                        <phase>package</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target>
                                <exec executable="docker" dir="${project.build.directory}"
                                    failonerror="true">
                                    <arg value="build" />
                                    <arg value="-t" />
                                    <arg value="base-kura-docker:${project.version}" />
                                    <arg value="-t" />
                                    <arg value="base-kura-docker-x86_64:${project.version}" />
                                    <arg value="." />
                                </exec>
                            </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>emulator-plugins-4s</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/pkg/plugins/4s</outputDirectory>
                            <includeArtifactIds>
                                <!-- emulator.watchdog-plugins --> 
                                org.eclipse.kura.emulator.watchdog,
                                <!-- emulator.usb-plugins -->
                                org.eclipse.kura.emulator.usb
                            </includeArtifactIds>
                        </configuration>
                    </execution>
                    <execution>
                        <id>emulator-plugins-5s</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/pkg/plugins/5s</outputDirectory>
                            <includeArtifactIds>
                                <!-- emulator-gpio-plugins --> 
                                org.eclipse.kura.emulator.gpio
                            </includeArtifactIds>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>