/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.container.provider.token;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.util.List;
import java.util.Optional;
import java.util.stream.Stream;

import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.KuraException;
import org.eclipse.kura.security.token.TokenIssueRequest;
import org.eclipse.kura.security.token.TokenIssuingService;
import org.junit.After;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;
import org.mockito.ArgumentCaptor;

import com.google.gson.Gson;
import com.google.gson.JsonObject;

public class ContainerTokenProvisionerTest {

    private static final String TMPFS_BASE_PROPERTY = "kura.tmpfs.base";
    private static final String IDENTITY_NAME = "container_test_0000abcd";
    private static final String ACCESS_TOKEN_CONSUMER = "/token/jwt/v1/access";
    private static final String REFRESH_TOKEN_CONSUMER = "/token/jwt/v1/refresh";
    private static final String ACCESS_TOKEN = "access-token";
    private static final String REFRESH_TOKEN = "refresh-token";
    private static final Duration ACCESS_TOKEN_DURATION = Duration.ofSeconds(60);
    private static final Duration REFRESH_TOKEN_DURATION = Duration.ofSeconds(900);

    @Rule
    public TemporaryFolder tmpfsBase = new TemporaryFolder();

    private String previousTmpfsBaseProperty;
    private final ContainerTokenProvisioner provisioner = new ContainerTokenProvisioner();
    private final TokenIssuingService tokenIssuingService = mock(TokenIssuingService.class);
    private final ArgumentCaptor<TokenIssueRequest> requestCaptor = ArgumentCaptor.forClass(TokenIssueRequest.class);
    private Path previousTokenPairFile;
    private Path tokenPairFile;
    private KuraException provisioningException;

    @Before
    public void setUp() {
        this.previousTmpfsBaseProperty = System.getProperty(TMPFS_BASE_PROPERTY);
        System.setProperty(TMPFS_BASE_PROPERTY, this.tmpfsBase.getRoot().getAbsolutePath());
    }

    @After
    public void tearDown() {
        this.provisioner.cleanup();

        if (this.previousTmpfsBaseProperty != null) {
            System.setProperty(TMPFS_BASE_PROPERTY, this.previousTmpfsBaseProperty);
        } else {
            System.clearProperty(TMPFS_BASE_PROPERTY);
        }
    }

    @Test
    public void issuesTokenPairForIdentity() throws Exception {
        givenTokenIssuingServiceIsBound();

        whenTokenPairIsProvisioned();

        thenTokenIsIssuedFor(ACCESS_TOKEN_CONSUMER, IDENTITY_NAME);
        thenTokenIsIssuedFor(REFRESH_TOKEN_CONSUMER, IDENTITY_NAME);
    }

    @Test
    public void issuesTokenPairWithRequestedDurations() throws Exception {
        givenTokenIssuingServiceIsBound();

        whenTokenPairIsProvisioned();

        thenTokenIsIssuedWithLifetime(ACCESS_TOKEN_CONSUMER, ACCESS_TOKEN_DURATION);
        thenTokenIsIssuedWithLifetime(REFRESH_TOKEN_CONSUMER, REFRESH_TOKEN_DURATION);
    }

    @Test
    public void writesTokenPairFile() throws Exception {
        givenTokenIssuingServiceIsBound();

        whenTokenPairIsProvisioned();

        thenTokenPairFileContainsIssuedTokens();
    }

    @Test
    public void replacesTokenPairFileOnEachProvisioning() throws Exception {
        givenTokenIssuingServiceIsBound();
        givenTokenPairIsProvisioned();

        whenTokenPairIsProvisioned();

        thenPreviousTokenPairFileIsDeleted();
        thenTokenPairFileContainsIssuedTokens();
    }

    @Test
    public void failsProvisioningWhenTokenIssuingServiceIsNotBound() {
        whenTokenPairProvisioningIsAttempted();

        thenProvisioningFailsWith(KuraErrorCode.SERVICE_UNAVAILABLE);
        thenNoTokenPairFileIsWritten();
    }

    @Test
    public void failsProvisioningWhenTokenIssuingServiceIsUnbound() throws Exception {
        givenTokenIssuingServiceIsBound();
        givenTokenIssuingServiceIsUnbound(this.tokenIssuingService);

        whenTokenPairProvisioningIsAttempted();

        thenProvisioningFailsWith(KuraErrorCode.SERVICE_UNAVAILABLE);
        thenNoTokenPairFileIsWritten();
    }

    @Test
    public void keepsTokenIssuingServiceWhenADifferentOneIsUnbound() throws Exception {
        givenTokenIssuingServiceIsBound();
        givenTokenIssuingServiceIsUnbound(mock(TokenIssuingService.class));

        whenTokenPairIsProvisioned();

        thenTokenPairFileContainsIssuedTokens();
    }

    @Test
    public void failsProvisioningWhenTokenIssuingFails() throws Exception {
        givenTokenIssuingServiceFails();

        whenTokenPairProvisioningIsAttempted();

        thenProvisioningFailsWith(KuraErrorCode.CONFIGURATION_ERROR);
        thenNoTokenPairFileIsWritten();
    }

    @Test
    public void deletesTokenPairFileOnCleanup() throws Exception {
        givenTokenIssuingServiceIsBound();
        givenTokenPairIsProvisioned();

        whenCleanupIsPerformed();

        thenTokenPairFileIsDeleted();
    }

    /*
     * GIVEN
     */

    private void givenTokenIssuingServiceIsBound() throws KuraException {
        when(this.tokenIssuingService.getMaximumLifetime()).thenReturn(Optional.empty());
        when(this.tokenIssuingService.issue(this.requestCaptor.capture())).thenAnswer(invocation -> {
            final TokenIssueRequest request = invocation.getArgument(0);
            return request.getIntendedConsumers().contains(ACCESS_TOKEN_CONSUMER) ? ACCESS_TOKEN : REFRESH_TOKEN;
        });

        this.provisioner.setTokenIssuingService(this.tokenIssuingService);
    }

    private void givenTokenIssuingServiceIsUnbound(final TokenIssuingService service) {
        this.provisioner.unsetTokenIssuingService(service);
    }

    private void givenTokenIssuingServiceFails() throws KuraException {
        when(this.tokenIssuingService.getMaximumLifetime()).thenReturn(Optional.empty());
        when(this.tokenIssuingService.issue(any()))
                .thenThrow(new KuraException(KuraErrorCode.CONFIGURATION_ERROR, "not yet ready"));

        this.provisioner.setTokenIssuingService(this.tokenIssuingService);
    }

    private void givenTokenPairIsProvisioned() throws KuraException {
        whenTokenPairIsProvisioned();
        this.previousTokenPairFile = this.tokenPairFile;
    }

    /*
     * WHEN
     */

    private void whenTokenPairIsProvisioned() throws KuraException {
        this.tokenPairFile = this.provisioner.provision(IDENTITY_NAME, ACCESS_TOKEN_DURATION, REFRESH_TOKEN_DURATION);
    }

    private void whenTokenPairProvisioningIsAttempted() {
        try {
            whenTokenPairIsProvisioned();
        } catch (final KuraException e) {
            this.provisioningException = e;
        }
    }

    private void whenCleanupIsPerformed() {
        this.provisioner.cleanup();
    }

    /*
     * THEN
     */

    private void thenTokenIsIssuedFor(final String intendedConsumer, final String identityName) {
        final TokenIssueRequest request = issuedRequestFor(intendedConsumer);

        assertEquals(identityName, request.getIdentityName());
        assertEquals(1, request.getIntendedConsumers().size());
    }

    private void thenTokenIsIssuedWithLifetime(final String intendedConsumer, final Duration lifetime) {
        final TokenIssueRequest request = issuedRequestFor(intendedConsumer);

        assertEquals(lifetime,
                Duration.between(request.getNotBefore().orElseThrow(), request.getExpiresAt().orElseThrow()));
    }

    private void thenTokenPairFileContainsIssuedTokens() throws Exception {
        assertNotNull(this.tokenPairFile);

        final JsonObject tokenPair = new Gson().fromJson(
                new String(Files.readAllBytes(this.tokenPairFile), StandardCharsets.UTF_8), JsonObject.class);

        assertEquals("Bearer", tokenPair.get("tokenType").getAsString());
        assertEquals(ACCESS_TOKEN, tokenPair.get("accessToken").getAsString());
        assertEquals(ACCESS_TOKEN_DURATION.toSeconds(), tokenPair.get("accessTokenExpiresInSeconds").getAsLong());
        assertEquals(REFRESH_TOKEN, tokenPair.get("refreshToken").getAsString());
        assertEquals(REFRESH_TOKEN_DURATION.toSeconds(), tokenPair.get("refreshTokenExpiresInSeconds").getAsLong());
    }

    private void thenPreviousTokenPairFileIsDeleted() {
        assertFalse(Files.exists(this.previousTokenPairFile));
    }

    private void thenProvisioningFailsWith(final KuraErrorCode errorCode) {
        assertNotNull(this.provisioningException);
        assertEquals(errorCode, this.provisioningException.getCode());
    }

    private void thenNoTokenPairFileIsWritten() {
        try (Stream<Path> files = Files.walk(this.tmpfsBase.getRoot().toPath())) {
            assertTrue(files.noneMatch(Files::isRegularFile));
        } catch (final Exception e) {
            throw new AssertionError(e);
        }
    }

    private void thenTokenPairFileIsDeleted() {
        assertFalse(Files.exists(this.tokenPairFile));
        assertFalse(Files.exists(this.tokenPairFile.getParent()));
    }

    private TokenIssueRequest issuedRequestFor(final String intendedConsumer) {
        final List<TokenIssueRequest> requests = this.requestCaptor.getAllValues();

        return requests.stream().filter(request -> request.getIntendedConsumers().contains(intendedConsumer))
                .reduce((first, second) -> second)
                .orElseThrow(() -> new AssertionError("no token issued for " + intendedConsumer));
    }
}
