/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotEquals;
import static org.junit.Assert.assertTrue;

import org.eclipse.kura.configuration.Password;
import org.junit.Test;

public class PasswordTest {

    private Password first;
    private Object second;

    @Test
    public void sameInstanceIsEqual() {
        givenPassword("secret");
        givenSameInstanceAsSecond();

        thenPasswordsAreEqual();
    }

    @Test
    public void passwordsWithSameValueAreEqual() {
        givenPassword("secret");
        givenSecondPassword("secret");

        thenPasswordsAreEqual();
        thenHashCodesAreEqual();
    }

    @Test
    public void passwordsFromStringAndCharArrayAreEqual() {
        givenPassword("secret");
        givenSecondPassword(new char[] { 's', 'e', 'c', 'r', 'e', 't' });

        thenPasswordsAreEqual();
        thenHashCodesAreEqual();
    }

    @Test
    public void passwordsWithDifferentValueAreNotEqual() {
        givenPassword("secret");
        givenSecondPassword("other");

        thenPasswordsAreNotEqual();
        thenHashCodesAreDifferent();
    }

    @Test
    public void passwordIsNotEqualToNull() {
        givenPassword("secret");
        givenNullSecond();

        thenPasswordsAreNotEqual();
    }

    @Test
    public void passwordIsNotEqualToObjectOfDifferentType() {
        givenPassword("secret");
        givenSecondObject("secret");

        thenPasswordsAreNotEqual();
    }

    @Test
    public void passwordsWithNullValueAreEqual() {
        givenPassword((String) null);
        givenSecondPassword((String) null);

        thenPasswordsAreEqual();
        thenHashCodesAreEqual();
    }

    private void givenPassword(String value) {
        this.first = new Password(value);
    }

    private void givenSameInstanceAsSecond() {
        this.second = this.first;
    }

    private void givenSecondPassword(String value) {
        this.second = new Password(value);
    }

    private void givenSecondPassword(char[] value) {
        this.second = new Password(value);
    }

    private void givenSecondObject(Object value) {
        this.second = value;
    }

    private void givenNullSecond() {
        this.second = null;
    }

    private void thenPasswordsAreEqual() {
        assertTrue(this.first.equals(this.second));
    }

    private void thenPasswordsAreNotEqual() {
        assertFalse(this.first.equals(this.second));
    }

    private void thenHashCodesAreEqual() {
        assertEquals(this.first.hashCode(), this.second.hashCode());
    }

    private void thenHashCodesAreDifferent() {
        assertNotEquals(this.first.hashCode(), this.second.hashCode());
    }
}
