/*******************************************************************************
 * Copyright (c) 2011, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 * Content with portions generated by generative AI platform
 *******************************************************************************/
package org.eclipse.kura.core.test;

import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import org.eclipse.kura.system.SystemAdminService;
import org.eclipse.kura.test.annotation.TestTarget;
import org.junit.Assume;
import org.junit.Test;

public class SystemAdminServiceTest {

    private static SystemAdminService sysAdminService = null;

    protected void setSystemAdminService(SystemAdminService sas) {
        sysAdminService = sas;
    }

    @TestTarget(targetPlatforms = { TestTarget.PLATFORM_ALL })
    @Test
    public void testServiceExists() {
        assertNotNull(sysAdminService);
    }

    @TestTarget(targetPlatforms = { TestTarget.PLATFORM_ALL })
    @Test
    public void testGetUptime() {
        // uptime is read from /proc, not available on Windows
        Assume.assumeFalse(System.getProperty("os.name").toLowerCase().startsWith("windows"));
        String actual = sysAdminService.getUptime();
        assertTrue(Long.parseLong(actual) > 0);
    }
}
