<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2025 Eurotech and/or its affiliates and others

    This program and the accompanying materials are made
    available under the terms of the Eclipse Public License 2.0
    which is available at https://www.eclipse.org/legal/epl-2.0/

    SPDX-License-Identifier: EPL-2.0

    Contributors:
     Eurotech

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.eclipse.kura</groupId>
        <artifactId>tools</artifactId>
        <version>6.0.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>kura-addon-archetype</artifactId>
    <packaging>maven-archetype</packaging>

    <properties>
        <kura_eth.basedir>${project.basedir}/../..</kura_eth.basedir>
    </properties>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
                <includes>
                    <include>archetype-resources/tests/test-env/framework/kura.properties</include>
                    <include>META-INF/maven/archetype-metadata.xml</include>
                </includes>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
                <excludes>
                    <exclude>archetype-resources/tests/test-env/framework/kura.properties</exclude>
                    <exclude>META-INF/maven/archetype-metadata.xml</exclude>
                </excludes>
            </resource>
            <!-- process projects versions properties in target definition -->
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
                <includes>
                    <include>archetype-resources/target-definition/__artifactId__.target</include>
                </includes>
            </resource>
        </resources>

        <extensions>
            <extension>
                <groupId>org.apache.maven.archetype</groupId>
                <artifactId>archetype-packaging</artifactId>
                <version>3.3.1</version>
            </extension>
        </extensions>

        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.3.1</version>
                <configuration>
                    <includeEmptyDirs>true</includeEmptyDirs>
                    <!-- needed to include .gitignore -->
                    <useDefaultExcludes>false</useDefaultExcludes>
                </configuration>
            </plugin>

            <plugin>
                <artifactId>maven-archetype-plugin</artifactId>
                <version>3.3.1</version>
                <configuration>
                    <!-- needed to include .gitignore -->
                    <useDefaultExcludes>false</useDefaultExcludes>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>properties-maven-plugin</artifactId>
                <version>1.2.1</version>
                <executions>
                    <execution>
                        <phase>initialize</phase>
                        <goals>
                            <goal>read-project-properties</goal>
                        </goals>
                        <configuration>
                            <files>
                                <file>${basedir}/../../../target-platform/config/kura.target-platform.build.properties</file>
                                <file>${basedir}/../../distrib/config/kura.build.properties</file>
                            </files>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>

</project>
