/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.internal.rest.auth.jwt;

import static org.junit.Assert.assertEquals;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.security.Principal;
import java.util.Optional;

import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.KuraException;
import org.eclipse.kura.internal.rest.auth.RestIdentityHelper;
import org.eclipse.kura.security.token.TokenVerificationService;
import org.eclipse.kura.security.token.VerificationProof;
import org.junit.Before;
import org.junit.Test;

import jakarta.servlet.http.HttpServletRequest;
import jakarta.ws.rs.container.ContainerRequestContext;

public class JwtAuthenticationProviderTest {

    private static final String IDENTITY = "alice";

    private final RestIdentityHelper identityHelper = mock(RestIdentityHelper.class);
    private final TokenVerificationService verifier = mock(TokenVerificationService.class);
    private final TokenVerificationService replacementVerifier = mock(TokenVerificationService.class);
    private final ContainerRequestContext requestContext = mock(ContainerRequestContext.class);

    private final JwtAuthenticationProvider provider = new JwtAuthenticationProvider(this.identityHelper);
    private Optional<Principal> principal = Optional.empty();

    @Before
    public void setUp() throws KuraException {
        final VerificationProof proof = mock(VerificationProof.class);
        when(proof.getIdentityName()).thenReturn(IDENTITY);
        when(this.verifier.verify(any())).thenReturn(proof);
        when(this.replacementVerifier.verify(any())).thenReturn(proof);
        when(this.requestContext.getHeaderString("Authorization")).thenReturn("Bearer access-token");
        when(this.identityHelper.identityExists(IDENTITY)).thenReturn(true);

        this.provider.setTokenVerificationService(this.verifier);
    }

    /*
     * Scenarios
     */

    @Test
    public void aTokenDoesNotAuthenticateWhenTheIdentityCannotBeChecked() throws KuraException {
        givenTheIdentityCheckFails();

        whenTheRequestIsAuthenticated();

        thenTheRequestIsNotAuthenticated();
    }

    @Test
    public void aReplacementVerificationServiceSurvivesTheOldOneBeingUnset() throws KuraException {
        givenAReplacementVerificationService();

        whenThePreviousVerificationServiceIsUnset();
        whenTheRequestIsAuthenticated();

        thenTheRequestIsAuthenticatedAs(IDENTITY);
        thenTheTokenIsVerifiedByTheReplacementService();
    }

    /*
     * Steps
     */

    private void givenTheIdentityCheckFails() throws KuraException {
        when(this.identityHelper.identityExists(IDENTITY))
                .thenThrow(new KuraException(KuraErrorCode.SECURITY_EXCEPTION));
    }

    private void givenAReplacementVerificationService() {
        this.provider.setTokenVerificationService(this.replacementVerifier);
    }

    private void whenThePreviousVerificationServiceIsUnset() {
        this.provider.unsetTokenVerificationService(this.verifier);
    }

    private void whenTheRequestIsAuthenticated() {
        this.principal = this.provider.authenticate(mock(HttpServletRequest.class), this.requestContext);
    }

    private void thenTheRequestIsNotAuthenticated() {
        assertEquals(Optional.empty(), this.principal);
    }

    private void thenTheRequestIsAuthenticatedAs(final String identityName) {
        assertEquals(Optional.of(identityName), this.principal.map(Principal::getName));
    }

    private void thenTheTokenIsVerifiedByTheReplacementService() throws KuraException {
        verify(this.replacementVerifier).verify(any());
        verify(this.verifier, never()).verify(any());
    }
}
