/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.internal.rest.auth.jwt;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.io.ByteArrayInputStream;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;

import org.eclipse.kura.KuraException;
import org.eclipse.kura.internal.rest.auth.RestIdentityHelper;
import org.eclipse.kura.internal.rest.provider.RestServiceOptions;
import org.eclipse.kura.security.token.TokenIssuingService;
import org.eclipse.kura.security.token.TokenVerificationService;
import org.eclipse.kura.security.token.VerificationProof;
import org.junit.Before;
import org.junit.Test;

import jakarta.ws.rs.WebApplicationException;
import jakarta.ws.rs.core.Response.Status;

public class JwtRestServiceTest {

    private static final String IDENTITY = "alice";
    private static final String REFRESH_TOKEN = "refresh-token";
    private static final int CONCURRENT_EXCHANGES = 4;

    private final RestIdentityHelper identityHelper = mock(RestIdentityHelper.class);
    private final TokenIssuingService issuer = mock(TokenIssuingService.class);
    private final TokenIssuingService replacementIssuer = mock(TokenIssuingService.class);
    private final TokenVerificationService verifier = mock(TokenVerificationService.class);
    private final VerificationProof proof = mock(VerificationProof.class);

    private final JwtRestService service = new JwtRestService(this.identityHelper);
    private final List<Integer> refusals = Collections.synchronizedList(new ArrayList<>());
    private int successfulExchanges;

    @Before
    public void setUp() throws KuraException {
        this.service.setOptions(new RestServiceOptions(Map.of("auth.jwt.enabled", true)));
        this.service.setTokenIssuingService(this.issuer);
        this.service.setTokenVerificationService(this.verifier);

        when(this.verifier.verify(any())).thenReturn(this.proof);
        when(this.proof.getIdentityName()).thenReturn(IDENTITY);
        when(this.proof.getExpiresAt()).thenReturn(Optional.of(Instant.now().plus(Duration.ofMinutes(1))));
        when(this.identityHelper.identityExists(IDENTITY)).thenReturn(true);
        when(this.issuer.issue(any())).thenReturn("token");
        when(this.replacementIssuer.issue(any())).thenReturn("token");
    }

    /*
     * Scenarios
     */

    @Test
    public void aRefreshTokenWithoutTokenIdentifierIsRefused() {
        givenARefreshTokenWith(Optional.empty(), Optional.of("kura"));

        whenTheRefreshTokenIsExchanged();

        thenTheExchangesAreRefusedWith(Status.UNAUTHORIZED, 1);
    }

    @Test
    public void aRefreshTokenWithoutIssuerIsRefused() {
        givenARefreshTokenWith(Optional.of("jti"), Optional.empty());

        whenTheRefreshTokenIsExchanged();

        thenTheExchangesAreRefusedWith(Status.UNAUTHORIZED, 1);
    }

    @Test
    public void concurrentExchangesOfTheSameRefreshTokenSucceedOnce() throws Exception {
        givenARefreshTokenWith(Optional.of("jti"), Optional.of("kura"));
        givenTheIssuerWaitsForAllConcurrentExchanges();

        whenTheRefreshTokenIsExchangedConcurrently();

        thenExactlyOneExchangeSucceeds();
        thenTheExchangesAreRefusedWith(Status.UNAUTHORIZED, CONCURRENT_EXCHANGES - 1);
    }

    @Test
    public void aReplacementIssuingServiceSurvivesTheOldOneBeingUnset() throws KuraException {
        givenARefreshTokenWith(Optional.of("jti"), Optional.of("kura"));
        givenAReplacementIssuingService();

        whenThePreviousIssuingServiceIsUnset();
        whenTheRefreshTokenIsExchanged();

        thenExactlyOneExchangeSucceeds();
        thenTheTokensAreIssuedByTheReplacementService();
    }

    @Test
    public void aUsedRefreshTokenIsTrackedForTheRetentionAfterItsExpiry() {
        givenTheUsedRefreshTokenRetention(Duration.ofMinutes(1));
        givenARefreshTokenExpiringAt("used", Instant.now().minusSeconds(10));
        givenTheRefreshTokenWasExchanged();
        givenARefreshTokenExpiringAt("other", Instant.now().plusSeconds(60));
        givenTheRefreshTokenWasExchanged();
        givenARefreshTokenExpiringAt("used", Instant.now().minusSeconds(10));

        whenTheRefreshTokenIsExchanged();

        thenTheExchangesAreRefusedWith(Status.UNAUTHORIZED, 1);
    }

    /*
     * Steps
     */

    private void givenTheUsedRefreshTokenRetention(final Duration retention) {
        this.service.setOptions(new RestServiceOptions(Map.of("auth.jwt.enabled", true,
                "auth.jwt.used.refresh.token.retention", (int) retention.toSeconds())));
    }

    // the verifier mock accepts the token even if it is expired, as a verifier does within its clock skew tolerance
    private void givenARefreshTokenExpiringAt(final String tokenId, final Instant expiresAt) {
        givenARefreshTokenWith(Optional.of(tokenId), Optional.of("kura"));
        when(this.proof.getExpiresAt()).thenReturn(Optional.of(expiresAt));
    }

    private void givenTheRefreshTokenWasExchanged() {
        exchangeTheRefreshToken();
    }

    private void givenARefreshTokenWith(final Optional<String> tokenId, final Optional<String> tokenIssuer) {
        when(this.proof.getTokenID()).thenReturn(tokenId);
        when(this.proof.getClaims()).thenReturn(tokenIssuer.<Map<String, Object>> map(iss -> Map.of("iss", iss))
                .orElse(Collections.emptyMap()));
    }

    private void givenTheIssuerWaitsForAllConcurrentExchanges() throws KuraException {
        // every exchange passes the replay check before any of them records the token as used
        final CountDownLatch allExchangesStarted = new CountDownLatch(CONCURRENT_EXCHANGES);

        when(this.issuer.issue(any())).thenAnswer(invocation -> {
            allExchangesStarted.countDown();
            allExchangesStarted.await(10, TimeUnit.SECONDS);
            return "token";
        });
    }

    private void givenAReplacementIssuingService() {
        this.service.setTokenIssuingService(this.replacementIssuer);
    }

    private void whenThePreviousIssuingServiceIsUnset() {
        this.service.unsetTokenIssuingService(this.issuer);
    }

    private void whenTheRefreshTokenIsExchanged() {
        exchangeTheRefreshToken();
    }

    private void whenTheRefreshTokenIsExchangedConcurrently() throws Exception {
        final ExecutorService executor = Executors.newFixedThreadPool(CONCURRENT_EXCHANGES);

        try {
            final List<Future<?>> exchanges = new ArrayList<>();

            for (int i = 0; i < CONCURRENT_EXCHANGES; i++) {
                exchanges.add(executor.submit(this::exchangeTheRefreshToken));
            }

            for (final Future<?> exchange : exchanges) {
                exchange.get(30, TimeUnit.SECONDS);
            }
        } finally {
            executor.shutdownNow();
        }
    }

    private void thenExactlyOneExchangeSucceeds() {
        assertEquals(1, this.successfulExchanges);
    }

    private void thenTheExchangesAreRefusedWith(final Status status, final int expectedRefusals) {
        assertEquals(Collections.nCopies(expectedRefusals, status.getStatusCode()), this.refusals);
    }

    private void thenTheTokensAreIssuedByTheReplacementService() throws KuraException {
        verify(this.replacementIssuer, times(2)).issue(any());
        verify(this.issuer, never()).issue(any());
    }

    private void exchangeTheRefreshToken() {
        try {
            this.service.refresh(new ByteArrayInputStream(REFRESH_TOKEN.getBytes(StandardCharsets.UTF_8)));
            synchronized (this) {
                this.successfulExchanges++;
            }
        } catch (final WebApplicationException e) {
            this.refusals.add(e.getResponse().getStatus());
        } catch (final Exception e) {
            fail("unexpected exception " + e);
        }
    }
}
