/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 * Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.cloud;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Optional;

import org.eclipse.kura.message.KuraDeviceProfile;
import org.eclipse.kura.net.IP4Address;
import org.eclipse.kura.net.IPAddress;
import org.eclipse.kura.net.NetInterface;
import org.eclipse.kura.net.NetInterfaceAddress;
import org.eclipse.kura.net.NetworkService;
import org.eclipse.kura.net.status.NetworkInterfaceIpAddress;
import org.eclipse.kura.net.status.NetworkInterfaceIpAddressStatus;
import org.eclipse.kura.net.status.NetworkStatusService;
import org.eclipse.kura.net.status.modem.ModemConnectionStatus;
import org.eclipse.kura.net.status.modem.ModemInterfaceStatus;
import org.eclipse.kura.net.status.modem.ModemInterfaceStatus.ModemInterfaceStatusBuilder;
import org.eclipse.kura.system.SystemAdminService;
import org.eclipse.kura.system.SystemService;
import org.junit.Test;

/**
 * Feature: include the ModemManager-managed modem interface in the device profile
 * connection info reported in the birth message.
 */
public class BuildDeviceProfileModemConnectionInfoTest {

    private static final String ETH0 = "eth0";
    private static final String ETH0_IP = "192.168.3.105";
    private static final String WWAN0 = "wwan0";
    private static final String WWAN0_IP = "10.20.30.40";

    private CloudServiceImpl cloudServiceImpl;
    private KuraDeviceProfile deviceProfile;

    @Test
    public void includesModemIpWhenNetworkStatusServiceReportsConnectedModem() throws Exception {
        givenCloudServiceImplWithLegacyActiveInterface(ETH0, ETH0_IP);
        givenNetworkStatusServiceWithConnectedModem(WWAN0, WWAN0_IP);

        whenDeviceProfileIsBuilt();

        thenConnectionInterfaceContains(ETH0);
        thenConnectionInterfaceContains(WWAN0);
        thenConnectionIpContains(ETH0_IP);
        thenConnectionIpContains(WWAN0_IP);
    }

    @Test
    public void fallsBackToLegacyInterfacesOnlyWhenNetworkStatusServiceIsAbsent() throws Exception {
        givenCloudServiceImplWithLegacyActiveInterface(ETH0, ETH0_IP);
        givenNoNetworkStatusService();

        whenDeviceProfileIsBuilt();

        thenConnectionInterfaceEquals(buildConnectionInterfaceEntry(ETH0));
        thenConnectionIpEquals(ETH0_IP);
    }

    @Test
    public void skipsModemInterfaceWithoutAnIpAddress() throws Exception {
        givenCloudServiceImplWithLegacyActiveInterface(ETH0, ETH0_IP);
        givenNetworkStatusServiceWithModemWithoutIp(WWAN0);

        whenDeviceProfileIsBuilt();

        thenConnectionInterfaceEquals(buildConnectionInterfaceEntry(ETH0));
        thenConnectionIpEquals(ETH0_IP);
    }

    private void givenCloudServiceImplWithLegacyActiveInterface(String interfaceName, String ip) throws Exception {
        this.cloudServiceImpl = new CloudServiceImpl();
        this.cloudServiceImpl.setSystemService(mock(SystemService.class));
        this.cloudServiceImpl.setSystemAdminService(mock(SystemAdminService.class));

        final List<NetInterface<? extends NetInterfaceAddress>> interfaces = buildLegacyInterface(interfaceName, ip);
        final NetworkService networkService = mock(NetworkService.class);
        when(networkService.getActiveNetworkInterfaces()).thenReturn(interfaces);
        this.cloudServiceImpl.setNetworkService(networkService);
    }

    private void givenNetworkStatusServiceWithConnectedModem(String interfaceName, String ip) throws Exception {
        final NetworkStatusService networkStatusService = mock(NetworkStatusService.class);
        final ModemInterfaceStatus modemStatus = buildModemStatus(interfaceName, ModemConnectionStatus.CONNECTED,
                Optional.of(ip));
        when(networkStatusService.getInterfaceIds()).thenReturn(Arrays.asList("1-8"));
        when(networkStatusService.getNetworkStatus("1-8")).thenReturn(Optional.of(modemStatus));
        this.cloudServiceImpl.setNetworkStatusService(networkStatusService);
    }

    private void givenNetworkStatusServiceWithModemWithoutIp(String interfaceName) throws Exception {
        final NetworkStatusService networkStatusService = mock(NetworkStatusService.class);
        final ModemInterfaceStatus modemStatus = buildModemStatus(interfaceName, ModemConnectionStatus.CONNECTED,
                Optional.empty());
        when(networkStatusService.getInterfaceIds()).thenReturn(Arrays.asList("1-8"));
        when(networkStatusService.getNetworkStatus("1-8")).thenReturn(Optional.of(modemStatus));
        this.cloudServiceImpl.setNetworkStatusService(networkStatusService);
    }

    private void givenNoNetworkStatusService() {
        // no-op: CloudServiceImpl already defaults to an empty NetworkStatusService reference
    }

    private void whenDeviceProfileIsBuilt() {
        this.deviceProfile = new LifeCyclePayloadBuilder(this.cloudServiceImpl).buildDeviceProfile();
    }

    private void thenConnectionInterfaceContains(String interfaceName) {
        assertTrue("expected connectionInterface to contain " + interfaceName + " but was "
                + this.deviceProfile.getConnectionInterface(),
                this.deviceProfile.getConnectionInterface().contains(interfaceName));
    }

    private void thenConnectionIpContains(String ip) {
        assertTrue("expected connectionIp to contain " + ip + " but was " + this.deviceProfile.getConnectionIp(),
                this.deviceProfile.getConnectionIp().contains(ip));
    }

    private void thenConnectionInterfaceEquals(String expected) {
        assertEquals(expected, this.deviceProfile.getConnectionInterface());
    }

    private void thenConnectionIpEquals(String expected) {
        assertEquals(expected, this.deviceProfile.getConnectionIp());
    }

    private static String buildConnectionInterfaceEntry(String interfaceName) {
        return interfaceName + " (00:00:00:00:00:00)";
    }

    private static List<NetInterface<? extends NetInterfaceAddress>> buildLegacyInterface(String interfaceName,
            String ip) throws Exception {
        final NetInterfaceAddress address = mock(NetInterfaceAddress.class);
        when(address.getAddress()).thenReturn(IPAddress.parseHostAddress(ip));

        @SuppressWarnings("unchecked")
        final NetInterface<NetInterfaceAddress> netInterface = mock(NetInterface.class);
        when(netInterface.getName()).thenReturn(interfaceName);
        when(netInterface.getHardwareAddress()).thenReturn(new byte[] { 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 });
        when(netInterface.getNetInterfaceAddresses()).thenReturn(Collections.singletonList(address));

        return Collections.singletonList(netInterface);
    }

    private static ModemInterfaceStatus buildModemStatus(String interfaceName, ModemConnectionStatus connectionStatus,
            Optional<String> ip) throws Exception {
        final ModemInterfaceStatusBuilder builder = ModemInterfaceStatus.builder();
        builder.withInterfaceName(interfaceName).withConnectionStatus(connectionStatus);

        if (ip.isPresent()) {
            final IP4Address address = (IP4Address) IPAddress.parseHostAddress(ip.get());
            final NetworkInterfaceIpAddress<IP4Address> netAddress = new NetworkInterfaceIpAddress<>(address,
                    (short) 24);
            final NetworkInterfaceIpAddressStatus<IP4Address> ipStatus = NetworkInterfaceIpAddressStatus
                    .<IP4Address>builder().withAddresses(Collections.singletonList(netAddress)).build();
            builder.withInterfaceIp4Addresses(Optional.of(ipStatus));
        }

        return builder.build();
    }
}
