/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 * Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.net.admin.util;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;
import static org.junit.Assume.assumeFalse;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Comparator;
import java.util.stream.Stream;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

public class ReplaceSymbolicLinkTest {

    private Path directory;
    private Path newTarget;
    private Path link;
    private Exception occurredException;

    /*
     * Scenarios
     */

    @Test
    public void replacesLinkToAnotherFile() throws IOException {
        givenLinkTo(existingFile("old-target"));

        whenLinkIsReplaced();

        thenNoExceptionOccurred();
        thenLinkPointsToNewTarget();
    }

    @Test
    public void replacesDanglingLink() throws IOException {
        givenLinkTo(this.directory.resolve("missing-target"));

        whenLinkIsReplaced();

        thenNoExceptionOccurred();
        thenLinkPointsToNewTarget();
    }

    @Test
    public void createsLinkWhenNoneExists() throws IOException {
        whenLinkIsReplaced();

        thenNoExceptionOccurred();
        thenLinkPointsToNewTarget();
    }

    @Before
    public void setUp() throws IOException {
        assumeFalse(System.getProperty("os.name").contains("indows"));
        this.directory = Files.createTempDirectory("symlink-test");
        this.newTarget = existingFile("new-target");
        this.link = this.directory.resolve("link");
    }

    @After
    public void tearDown() throws IOException {
        if (this.directory != null) {
            try (Stream<Path> paths = Files.walk(this.directory)) {
                paths.sorted(Comparator.reverseOrder()).forEach(path -> path.toFile().delete());
            }
        }
    }

    /*
     * Steps
     */

    private void givenLinkTo(Path target) throws IOException {
        Files.createSymbolicLink(this.link, target);
    }

    private void whenLinkIsReplaced() {
        try {
            LinuxFileUtil.createSymbolicLink(this.newTarget.toString(), this.link.toString(), true);
        } catch (Exception e) {
            this.occurredException = e;
        }
    }

    private void thenNoExceptionOccurred() {
        assertNull(this.occurredException);
    }

    private void thenLinkPointsToNewTarget() throws IOException {
        assertTrue(Files.isSymbolicLink(this.link));
        assertEquals(this.newTarget, Files.readSymbolicLink(this.link));
    }

    /*
     * Utilities
     */

    private Path existingFile(String name) throws IOException {
        return Files.write(this.directory.resolve(name), name.getBytes());
    }
}
