/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.configuration.internal;

import static org.eclipse.kura.cloudconnection.request.RequestHandlerMessageConstants.ARGS_KEY;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;
import static org.mockito.ArgumentMatchers.anyList;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.Callable;

import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.KuraException;
import org.eclipse.kura.cloudconnection.message.KuraMessage;
import org.eclipse.kura.configuration.ComponentConfiguration;
import org.eclipse.kura.configuration.ConfigurationService;
import org.eclipse.kura.core.configuration.XmlComponentConfigurations;
import org.eclipse.kura.message.KuraRequestPayload;
import org.junit.Test;

public class CloudConfigurationHandlerFailureTest {

    private static final String PID = "org.eclipse.kura.test.pid";

    private final ConfigurationService configurationService = mock(ConfigurationService.class);

    private CloudConfigurationHandler handler;
    private Callable<Void> callable;
    private Optional<KuraException> exception = Optional.empty();

    @Test
    public void snapshotListingFailureIsReportedAsSnapshotListingError() throws KuraException {
        givenHandler();
        givenSnapshotListingFails();

        whenGetIsInvoked("snapshots");

        thenKuraExceptionIsThrownWithCode(KuraErrorCode.CONFIGURATION_SNAPSHOT_LISTING);
    }

    @Test
    public void configurationRetrievalFailureIsReportedAsBadRequest() throws KuraException {
        givenHandler();
        givenConfigurationRetrievalFails();

        whenGetIsInvoked("configurations", PID);

        thenKuraExceptionIsThrownWithCode(KuraErrorCode.BAD_REQUEST);
    }

    @Test
    public void emptyRequestBodyIsRejectedAsBadRequest() {
        givenHandler();

        whenPutIsInvokedWithoutBody("configurations");

        thenKuraExceptionIsThrownWithCode(KuraErrorCode.BAD_REQUEST);
    }

    @Test
    public void snapshotTakingFailureIsReportedAsSnapshotTakingError() throws KuraException {
        givenHandler();
        givenSnapshotTakingFails();

        whenExecIsInvoked("snapshot");

        thenKuraExceptionIsThrownWithCode(KuraErrorCode.CONFIGURATION_SNAPSHOT_TAKING);
    }

    @Test
    public void marshallingFailureIsReportedAsSnapshotLoadingError() throws KuraException {
        givenHandlerWithFailingMarshaller();
        givenSnapshotListingSucceeds();

        whenGetIsInvoked("snapshots");

        thenKuraExceptionIsThrownWithCode(KuraErrorCode.CONFIGURATION_SNAPSHOT_LOADING);
    }

    @Test
    public void configurationUpdateFailureIsReportedAsConfigurationUpdateError() throws KuraException {
        givenConfigurationUpdateFails();
        givenUpdateConfigurationsCallable();

        whenCallableIsRun();

        thenKuraExceptionIsThrownWithCode(KuraErrorCode.CONFIGURATION_UPDATE);
    }

    @Test
    public void rollbackFailureIsReportedAsConfigurationRollbackError() throws KuraException {
        givenRollbackFails();
        givenRollbackCallable();

        whenCallableIsRun();

        thenKuraExceptionIsThrownWithCode(KuraErrorCode.CONFIGURATION_ROLLBACK);
    }

    private void givenHandler() {
        this.handler = new CloudConfigurationHandler();
        this.handler.setConfigurationService(this.configurationService);
    }

    private void givenHandlerWithFailingMarshaller() {
        this.handler = new CloudConfigurationHandler() {

            @Override
            protected String marshal(Object object) {
                throw new IllegalStateException("marshaller unavailable");
            }
        };
        this.handler.setConfigurationService(this.configurationService);
    }

    private void givenSnapshotListingFails() throws KuraException {
        when(this.configurationService.getSnapshots()).thenThrow(new KuraException(KuraErrorCode.STORE_ERROR));
    }

    private void givenSnapshotListingSucceeds() throws KuraException {
        when(this.configurationService.getSnapshots()).thenReturn(Collections.singleton(1L));
    }

    private void givenConfigurationRetrievalFails() throws KuraException {
        when(this.configurationService.getComponentConfiguration(PID))
                .thenThrow(new KuraException(KuraErrorCode.CONFIGURATION_ERROR));
    }

    private void givenSnapshotTakingFails() throws KuraException {
        when(this.configurationService.snapshot()).thenThrow(new KuraException(KuraErrorCode.STORE_ERROR));
    }

    private void givenConfigurationUpdateFails() throws KuraException {
        doThrow(new KuraException(KuraErrorCode.CONFIGURATION_ERROR)).when(this.configurationService)
                .updateConfigurations(anyList());
    }

    private void givenRollbackFails() throws KuraException {
        doThrow(new KuraException(KuraErrorCode.STORE_ERROR)).when(this.configurationService).rollback();
    }

    private void givenUpdateConfigurationsCallable() {
        ComponentConfiguration configuration = mock(ComponentConfiguration.class);
        when(configuration.getPid()).thenReturn(PID);
        XmlComponentConfigurations xmlConfigurations = new XmlComponentConfigurations();
        xmlConfigurations.setConfigurations(Collections.singletonList(configuration));
        this.callable = new UpdateConfigurationsCallable(null, xmlConfigurations, this.configurationService);
    }

    private void givenRollbackCallable() {
        this.callable = new RollbackCallable(null, this.configurationService);
    }

    private void whenGetIsInvoked(String... resources) {
        try {
            this.handler.doGet(null, requestMessage(resources));
        } catch (KuraException e) {
            this.exception = Optional.of(e);
        }
    }

    private void whenPutIsInvokedWithoutBody(String... resources) {
        try {
            this.handler.doPut(null, requestMessage(resources));
        } catch (KuraException e) {
            this.exception = Optional.of(e);
        }
    }

    private void whenExecIsInvoked(String... resources) {
        try {
            this.handler.doExec(null, requestMessage(resources));
        } catch (KuraException e) {
            this.exception = Optional.of(e);
        }
    }

    private void whenCallableIsRun() {
        try {
            this.callable.call();
        } catch (KuraException e) {
            this.exception = Optional.of(e);
        } catch (Exception e) {
            throw new IllegalStateException("unexpected exception", e);
        }
    }

    private void thenKuraExceptionIsThrownWithCode(KuraErrorCode expectedCode) {
        assertTrue("a KuraException was expected", this.exception.isPresent());
        assertEquals(expectedCode, this.exception.get().getCode());
        if (expectedCode != KuraErrorCode.BAD_REQUEST) {
            assertNotNull("the original failure must be preserved as cause", this.exception.get().getCause());
        }
    }

    private static KuraMessage requestMessage(String... resources) {
        List<String> resourceList = Arrays.asList(resources);
        Map<String, Object> properties = new HashMap<>();
        properties.put(ARGS_KEY.value(), resourceList);
        return new KuraMessage(new KuraRequestPayload(), properties);
    }
}
