/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.core.inventory;

import static org.eclipse.kura.cloudconnection.request.RequestHandlerMessageConstants.ARGS_KEY;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

import org.eclipse.kura.KuraException;
import org.eclipse.kura.cloudconnection.message.KuraMessage;
import org.eclipse.kura.message.KuraRequestPayload;
import org.eclipse.kura.message.KuraResponsePayload;
import org.junit.Test;
import org.osgi.service.deploymentadmin.DeploymentAdmin;
import org.osgi.service.deploymentadmin.DeploymentPackage;

public class DeploymentPackagesMarshallingFailureTest {

    private static final String RESOURCE_DEPLOYMENT_PACKAGES = "deploymentPackages";

    private InventoryHandlerV1 inventory;
    private KuraResponsePayload response;

    @Test
    public void marshallingFailureStillReturnsAResponseWithoutBody() throws KuraException {
        givenInventoryHandlerWithFailingMarshaller();
        givenNoDeploymentPackagesInstalled();

        whenDeploymentPackagesAreRequested();

        thenResponseCodeIs(KuraResponsePayload.RESPONSE_CODE_OK);
        thenResponseHasNoBody();
    }

    private void givenInventoryHandlerWithFailingMarshaller() {
        this.inventory = new InventoryHandlerV1() {

            @Override
            protected String marshal(Object object) {
                throw new IllegalStateException("marshaller unavailable");
            }
        };
    }

    private void givenNoDeploymentPackagesInstalled() {
        DeploymentAdmin deploymentAdmin = mock(DeploymentAdmin.class);
        when(deploymentAdmin.listDeploymentPackages()).thenReturn(new DeploymentPackage[0]);
        this.inventory.setDeploymentAdmin(deploymentAdmin);
    }

    private void whenDeploymentPackagesAreRequested() throws KuraException {
        Map<String, Object> properties = new HashMap<>();
        properties.put(ARGS_KEY.value(), Collections.singletonList(RESOURCE_DEPLOYMENT_PACKAGES));
        KuraMessage request = new KuraMessage(new KuraRequestPayload(), properties);

        this.response = (KuraResponsePayload) this.inventory.doGet(null, request).getPayload();
    }

    private void thenResponseCodeIs(int expectedCode) {
        assertEquals(expectedCode, this.response.getResponseCode());
    }

    private void thenResponseHasNoBody() {
        assertNull(this.response.getBody());
    }
}
