/*******************************************************************************
 * Copyright (c) 2022, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.container.provider;

import static java.util.Objects.isNull;

import java.net.InetAddress;
import java.net.NetworkInterface;
import java.net.SocketException;
import java.time.Duration;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.atomic.AtomicReference;
import java.util.function.UnaryOperator;
import java.util.stream.Collectors;

import org.eclipse.kura.KuraException;
import org.eclipse.kura.configuration.ComponentConfiguration;
import org.eclipse.kura.configuration.ConfigurableComponent;
import org.eclipse.kura.configuration.ConfigurationService;
import org.eclipse.kura.container.orchestration.ContainerConfiguration;
import org.eclipse.kura.container.orchestration.ContainerInstanceDescriptor;
import org.eclipse.kura.container.orchestration.ContainerOrchestrationService;
import org.eclipse.kura.container.orchestration.RegistryCredentials;
import org.eclipse.kura.container.orchestration.listener.ContainerOrchestrationServiceListener;
import org.eclipse.kura.container.signature.ContainerSignatureValidationService;
import org.eclipse.kura.container.signature.ValidationResult;
import org.eclipse.kura.identity.AssignedPermissions;
import org.eclipse.kura.identity.IdentityConfiguration;
import org.eclipse.kura.identity.IdentityService;
import org.eclipse.kura.identity.PasswordConfiguration;
import org.eclipse.kura.identity.PasswordStrengthVerificationService;
import org.eclipse.kura.identity.Permission;
import org.eclipse.kura.net.IPAddress;
import org.eclipse.kura.net.NetInterface;
import org.eclipse.kura.net.NetInterfaceAddress;
import org.eclipse.kura.net.NetworkService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ContainerInstance implements ConfigurableComponent, ContainerOrchestrationServiceListener {

    private static final Logger logger = LoggerFactory.getLogger(ContainerInstance.class);

    private static final ValidationResult FAILED_VALIDATION = new ValidationResult();

    private final ExecutorService executor = Executors.newSingleThreadExecutor();

    private ContainerOrchestrationService containerOrchestrationService;
    private Set<ContainerSignatureValidationService> availableContainerSignatureValidationService = new HashSet<>();
    private ConfigurationService configurationService;
    private IdentityService identityService;
    private NetworkService networkService;
    private PasswordStrengthVerificationService passwordStrengthVerificationService;
    private State state = new Disabled(new ContainerInstanceOptions(Collections.emptyMap()));
    private ContainerInstanceOptions currentOptions = null;
    private final AtomicReference<String> currentTemporaryIdentityName = new AtomicReference<>();
    private final AtomicReference<char[]> currentTemporaryPassword = new AtomicReference<>();

    public void setContainerOrchestrationService(final ContainerOrchestrationService containerOrchestrationService) {
        this.containerOrchestrationService = containerOrchestrationService;
    }

    public void setPasswordStrengthVerificationService(
            final PasswordStrengthVerificationService passwordStrengthVerificationService) {
        this.passwordStrengthVerificationService = passwordStrengthVerificationService;
    }

    public synchronized void setContainerSignatureValidationService(
            final ContainerSignatureValidationService containerSignatureValidationService) {

        logger.info("Container signature validation service {} added.", containerSignatureValidationService.getClass());
        this.availableContainerSignatureValidationService.add(containerSignatureValidationService);
    }

    public synchronized void unsetContainerSignatureValidationService(
            final ContainerSignatureValidationService containerSignatureValidationService) {
        logger.info("Container signature validation service {} removed.",
                containerSignatureValidationService.getClass());
        this.availableContainerSignatureValidationService.remove(containerSignatureValidationService);
    }

    public synchronized void setConfigurationService(final ConfigurationService confService) {
        this.configurationService = confService;
    }

    public synchronized void setIdentityService(final IdentityService identityService) {
        this.identityService = identityService;
    }

    public synchronized void setNetworkService(final NetworkService networkService) {
        this.networkService = networkService;
    }

    // ----------------------------------------------------------------
    //
    // Activation APIs
    //
    // ----------------------------------------------------------------

    public void activate(final Map<String, Object> properties) {
        logger.info("activating...");
        updated(properties);

        logger.info("activating...done");
    }

    public void updated(Map<String, Object> properties) {

        if (isNull(properties)) {
            throw new IllegalArgumentException("Properties cannot be null!");
        }

        try {
            ContainerInstanceOptions newOptions = new ContainerInstanceOptions(properties);

            if (this.currentOptions != null && this.currentOptions.equals(newOptions)) {
                return;
            }

            this.currentOptions = newOptions;

            if (!this.currentOptions.getEnforcementDigest().isPresent()) {

                logger.info(
                        "Container configuration doesn't include enforcement digest. Validating with Container Signature Validation service");

                if (this.currentOptions.getSignatureTrustAnchor().isPresent()) {

                    ValidationResult containerSignatureValidated = validateContainerImageSignature(this.currentOptions);

                    logger.info("Container signature validation result for {}@{}({}) - {}",
                            this.currentOptions.getContainerImage(),
                            containerSignatureValidated.imageDigest().orElse("?"),
                            this.currentOptions.getContainerImageTag(),
                            containerSignatureValidated.isSignatureValid() ? "OK" : "FAIL");

                    containerSignatureValidated.imageDigest().ifPresent(digest -> {

                        Map<String, Object> updatedProperties = updatePropertiesWithSignatureDigest(properties, digest);
                        this.currentOptions = new ContainerInstanceOptions(updatedProperties);
                        updateSnapshotWithSignatureDigest(updatedProperties);

                    });

                } else {
                    logger.info("No trust anchor available. Signature validation skipped.");
                }

            }

            if (this.currentOptions.isEnabled()) {
                this.containerOrchestrationService.registerListener(this);
            } else {
                this.containerOrchestrationService.unregisterListener(this);
            }

            updateState(s -> s.onConfigurationUpdated(this.currentOptions));

        } catch (Exception e) {
            logger.error("Failed to create container instance. Please check configuration of container: {}. Caused by:",
                    properties.get(ConfigurationService.KURA_SERVICE_PID), e);
            updateState(State::onDisabled);
        }

    }

    public void deactivate() {
        logger.info("deactivate...");

        updateState(State::onDisabled);
        cleanupTemporaryIdentity();

        this.executor.shutdown();
        this.containerOrchestrationService.unregisterListener(this);

        logger.info("deactivate...done");
    }

    public synchronized String getState() {
        return this.state.getClass().getSimpleName();
    }

    // ----------------------------------------------------------------
    //
    // Private methods
    //
    // ----------------------------------------------------------------

    @Override
    public void onConnect() {
        updateState(State::onConnect);
    }

    @Override
    public void onDisconnect() {
        //
    }

    @Override
    public void onDisabled() {
        updateState(State::onDisabled);
    }

    private ValidationResult validateContainerImageSignature(ContainerInstanceOptions configuration) {

        if (Objects.isNull(this.availableContainerSignatureValidationService)
                || this.availableContainerSignatureValidationService.isEmpty()) {
            logger.warn("No container signature validation service available. Signature validation failed.");
            return FAILED_VALIDATION;
        }

        Optional<String> optTrustAnchor = configuration.getSignatureTrustAnchor();
        if (!optTrustAnchor.isPresent() || optTrustAnchor.get().isEmpty()) {
            logger.warn("No trust anchor available. Signature validation failed.");
            return FAILED_VALIDATION;
        }

        String trustAnchor = optTrustAnchor.get();
        boolean verifyInTransparencyLog = configuration.getSignatureVerifyTransparencyLog();
        Optional<RegistryCredentials> registryCredentials = configuration.getRegistryCredentials();

        for (ContainerSignatureValidationService validationService : this.availableContainerSignatureValidationService) {
            ValidationResult results = FAILED_VALIDATION;

            try {
                if (registryCredentials.isPresent()) {
                    results = validationService.verify(configuration.getContainerImage(),
                            configuration.getContainerImageTag(), trustAnchor, verifyInTransparencyLog,
                            registryCredentials.get());
                } else {
                    results = validationService.verify(configuration.getContainerImage(),
                            configuration.getContainerImageTag(), trustAnchor, verifyInTransparencyLog);
                }
            } catch (KuraException e) {
                logger.warn(
                        "Error validating container signature with {}. Setting validation results as FAILED. Caused by: ",
                        validationService.getClass(), e);
            }

            if (results.isSignatureValid()) {
                return results;
            }
        }

        return FAILED_VALIDATION;
    }

    private synchronized void updateState(final UnaryOperator<State> update) {
        final State previous = this.state;
        final State newState = update.apply(previous);
        logger.info("State update: {} -> {}", previous.getClass().getSimpleName(), newState.getClass().getSimpleName());

        this.state = newState;
    }

    private Optional<ContainerInstanceDescriptor> getExistingContainerByName(final String containerName) {
        return containerOrchestrationService.listContainerDescriptors().stream()
                .filter(c -> c.getContainerName().equals(containerName)).findAny();
    }

    private interface State {

        public default State onConnect() {
            return this;
        }

        public default State onConfigurationUpdated(final ContainerInstanceOptions options) {
            return this;
        }

        public default State onContainerReady(final String containerId) {
            return this;
        }

        public default State onStartupFailure() {
            return this;
        }

        public default State onDisabled() {
            return this;
        }

    }

    private class Disabled implements State {

        private final ContainerInstanceOptions options;

        public Disabled(ContainerInstanceOptions options) {
            this.options = options;
        }

        @Override
        public State onConfigurationUpdated(ContainerInstanceOptions options) {
            return updateStateInternal(options);
        }

        @Override
        public State onConnect() {
            return updateStateInternal(this.options);
        }

        private State updateStateInternal(ContainerInstanceOptions newOptions) {

            final Optional<ContainerInstanceDescriptor> existingContainer;
            final boolean isInstanceEnabled = newOptions.isEnabled();

            try {
                existingContainer = getExistingContainerByName(
                        newOptions.getContainerConfiguration().getContainerName());
            } catch (final Exception e) {
                logger.warn("failed to get existing container state", e);
                return new Disabled(newOptions);
            }

            if (existingContainer.isPresent()) {

                logger.info("found existing container with name {}",
                        newOptions.getContainerConfiguration().getContainerName());
                if (isInstanceEnabled) {
                    return new Starting(newOptions);
                } else {
                    return new Created(newOptions, existingContainer.get().getContainerId()).onDisabled();
                }

            } else {

                if (isInstanceEnabled) {
                    return new Starting(newOptions);
                } else {
                    return new Disabled(newOptions);
                }

            }
        }
    }

    private class Starting implements State {

        private final ContainerInstanceOptions options;
        private final Future<?> startupFuture;

        public Starting(final ContainerInstanceOptions options) {
            this.options = options;
            this.startupFuture = ContainerInstance.this.executor.submit(() -> startMicroservice(options));
        }

        private ContainerConfiguration getContainerConfigurationWithCredentials(
                final ContainerInstanceOptions options) {
            ContainerConfiguration baseConfig = options.getContainerConfiguration();

            final String identityName = ContainerInstance.this.currentTemporaryIdentityName.get();
            final char[] password = ContainerInstance.this.currentTemporaryPassword.get();

            if (options.isIdentityIntegrationEnabled() && password != null && identityName != null) {
                final List<String> envVars = new ArrayList<>(baseConfig.getContainerEnvVars());
                envVars.add("KURA_IDENTITY_NAME=" + identityName);
                envVars.add("KURA_IDENTITY_PASSWORD=" + new String(password));

                String restBaseUrl = buildRestBaseUrl(options);
                envVars.add("KURA_REST_BASE_URL=" + restBaseUrl);
                logger.info("Setting container REST base URL to: {}", restBaseUrl);

                return ContainerConfiguration.builder().setContainerName(baseConfig.getContainerName())
                        .setImageConfiguration(baseConfig.getImageConfiguration())
                        .setContainerPorts(baseConfig.getContainerPorts()).setEnvVars(envVars)
                        .setVolumes(baseConfig.getContainerVolumes())
                        .setPrivilegedMode(baseConfig.isContainerPrivileged())
                        .setDeviceList(baseConfig.getContainerDevices())
                        .setFrameworkManaged(baseConfig.isFrameworkManaged())
                        .setLoggingType(baseConfig.getContainerLoggingType())
                        .setContainerNetowrkConfiguration(baseConfig.getContainerNetworkConfiguration())
                        .setLoggerParameters(baseConfig.getLoggerParameters()).setEntryPoint(baseConfig.getEntryPoint())
                        .setRestartOnFailure(baseConfig.getRestartOnFailure()).setMemory(baseConfig.getMemory())
                        .setCpus(baseConfig.getCpus()).setGpus(baseConfig.getGpus()).setRuntime(baseConfig.getRuntime())
                        .setEnforcementDigest(baseConfig.getEnforcementDigest()).build();
            }

            return baseConfig;
        }

        private void createTemporaryIdentityIfEnabled(final ContainerInstanceOptions options) {
            if (options.isIdentityIntegrationEnabled() && ContainerInstance.this.identityService != null) {
                try {
                    cleanupTemporaryIdentity();

                    final Set<Permission> permissions = options.getContainerPermissions().stream().map(Permission::new)
                            .collect(Collectors.toSet());

                    final String identityName = "container_" + options.getContainerName().replace("-", "_");

                    // Generate password
                    final String password = new String(PasswordGenerator
                            .generatePassword(passwordStrengthVerificationService.getPasswordStrengthRequirements()));

                    // Create identity configuration (computePasswordHash will clear this char[])
                    final PasswordConfiguration passwordConfiguration = new PasswordConfiguration(false, true,
                            Optional.of(password.toCharArray()), Optional.empty());
                    final AssignedPermissions assignedPermissions = new AssignedPermissions(permissions);
                    final IdentityConfiguration configuration = new IdentityConfiguration(identityName,
                            Arrays.asList(passwordConfiguration, assignedPermissions));

                    // Create temporary identity with very long lifetime (365 days)
                    // The identity lifetime matches the container lifecycle - cleanup happens when container stops
                    // The duration is a safety net for cases where cleanup fails
                    ContainerInstance.this.identityService.createTemporaryIdentity(configuration, Duration.ofDays(365));

                    // Store identity name and password for env injection (fresh char[] from same string)
                    ContainerInstance.this.currentTemporaryIdentityName.set(identityName);
                    ContainerInstance.this.currentTemporaryPassword.set(password.toCharArray());

                    logger.info("Created temporary identity {} for container {} with {} permissions", identityName,
                            options.getContainerName(), permissions.size());

                } catch (KuraException e) {
                    logger.error("Failed to create temporary identity for container {}", options.getContainerName(), e);
                    ContainerInstance.this.currentTemporaryIdentityName.set(null);
                    clearTemporaryPassword();
                }
            }
        }

        @Override
        public State onConfigurationUpdated(ContainerInstanceOptions newOptions) {
            if (newOptions.equals(this.options)) {
                return this;
            }

            cleanupTemporaryIdentity();
            this.startupFuture.cancel(true);

            if (newOptions.isEnabled()) {
                return new Starting(newOptions);
            } else {
                return new Disabled(newOptions);
            }
        }

        @Override
        public State onContainerReady(final String containerId) {
            clearTemporaryPassword();
            return new Created(this.options, containerId);
        }

        @Override
        public State onStartupFailure() {
            clearTemporaryPassword();
            cleanupTemporaryIdentity();
            return new Disabled(this.options);
        }

        @Override
        public State onDisabled() {
            this.startupFuture.cancel(true);

            try {
                final Optional<ContainerInstanceDescriptor> existingInstance = getExistingContainerByName(
                        this.options.getContainerName());

                if (existingInstance.isPresent()) {
                    return new Created(this.options, existingInstance.get().getContainerId()).onDisabled();
                }
            } catch (final Exception e) {
                logger.warn("failed to check container state", e);
            }

            return new Disabled(this.options);
        }

        private void startMicroservice(final ContainerInstanceOptions options) {
            boolean unlimitedRetries = options.isUnlimitedRetries();
            int maxRetries = options.getMaxDownloadRetries();
            int retryInterval = options.getRetryInterval();

            createTemporaryIdentityIfEnabled(options);
            final ContainerConfiguration containerConfiguration = getContainerConfigurationWithCredentials(options);

            int retries = 0;
            while ((unlimitedRetries || retries < maxRetries) && !Thread.currentThread().isInterrupted()) {
                try {
                    logger.info("Tentative number: {}", retries);

                    if (retries > 0) {
                        Thread.sleep(retryInterval);
                    }

                    final String containerId = ContainerInstance.this.containerOrchestrationService
                            .startContainer(containerConfiguration);
                    updateState(s -> s.onContainerReady(containerId));

                    return;

                } catch (InterruptedException e) {
                    logger.info("interrupted exiting");
                    Thread.currentThread().interrupt();
                    return;
                } catch (KuraException e) {
                    logger.error("Error managing microservice state", e);
                    if (!unlimitedRetries) {
                        retries++;
                    }
                }
            }

            updateState(State::onStartupFailure);

            logger.warn("Unable to start microservice...giving up");
        }

        private String buildRestBaseUrl(ContainerInstanceOptions options) {
            boolean useHttps = isHttpsEnabled();
            String protocol = useHttps ? "https" : "http";
            String host = getHostAddressForNetworkMode(options.getContainerNetworkingMode().orElse("bridge"));
            int port = getRestServicePort(useHttps);

            return String.format("%s://%s:%d/services", protocol, host, port);
        }

        private int getRestServicePort(boolean useHttps) {
            int defaultPort = useHttps ? 443 : 8080;

            if (ContainerInstance.this.configurationService == null) {
                logger.debug("ConfigurationService not available, using default port");
                return defaultPort;
            }

            try {
                ComponentConfiguration config = ContainerInstance.this.configurationService
                        .getComponentConfiguration("org.eclipse.kura.http.server.manager.HttpService");

                return extractPortFromConfig(config, useHttps).orElse(defaultPort);
            } catch (KuraException e) {
                logger.warn("Failed to get REST service port configuration", e);
            }

            return defaultPort;
        }

        private Optional<Integer> extractPortFromConfig(ComponentConfiguration config, boolean useHttps) {
            if (config == null || config.getConfigurationProperties() == null) {
                return Optional.empty();
            }

            Map<String, Object> properties = config.getConfigurationProperties();
            String portKey = useHttps ? "https.ports" : "http.ports";
            Integer[] ports = (Integer[]) properties.get(portKey);

            if (ports != null && ports.length > 0) {
                return Optional.of(ports[0]);
            }

            return Optional.empty();
        }

        private boolean isHttpsEnabled() {
            if (ContainerInstance.this.configurationService == null) {
                logger.debug("ConfigurationService not available, defaulting to HTTP");
                return false;
            }

            try {
                ComponentConfiguration config = ContainerInstance.this.configurationService
                        .getComponentConfiguration("org.eclipse.kura.http.server.manager.HttpService");

                if (config != null && config.getConfigurationProperties() != null) {
                    Map<String, Object> properties = config.getConfigurationProperties();
                    Integer[] httpsPorts = (Integer[]) properties.get("https.ports");
                    return httpsPorts != null && httpsPorts.length > 0;
                }
            } catch (KuraException e) {
                logger.warn("Failed to check HTTPS configuration", e);
            }
            return false;
        }

        private String getHostAddressForNetworkMode(String networkMode) {
            if ("host".equalsIgnoreCase(networkMode)) {
                logger.debug("Container using host network mode, using localhost");
                return "localhost";
            }

            return getAddressForBridgeMode();
        }

        private String getAddressForBridgeMode() {
            String dockerGateway = getDockerBridgeGateway();
            if (dockerGateway != null) {
                return dockerGateway;
            }

            String hostPrimaryIp = getHostPrimaryIpAddress();
            if (hostPrimaryIp != null) {
                return hostPrimaryIp;
            }

            logger.warn("Could not determine host address, using host.docker.internal as fallback");
            return "host.docker.internal";
        }

        private String getDockerBridgeGateway() {
            String address = getDockerBridgeViaNetworkService();
            if (address != null) {
                return address;
            }

            return getDockerBridgeViaJavaApi();
        }

        private String getDockerBridgeViaNetworkService() {
            if (ContainerInstance.this.networkService == null) {
                return null;
            }

            try {
                for (NetInterface<?> netInterface : ContainerInstance.this.networkService.getNetworkInterfaces()) {
                    String address = extractDockerInterfaceAddress(netInterface);
                    if (address != null) {
                        return address;
                    }
                }
            } catch (Exception e) {
                logger.debug("Failed to detect docker0 interface using NetworkService", e);
            }
            return null;
        }

        private String extractDockerInterfaceAddress(NetInterface<?> netInterface) {
            if (!"docker0".equals(netInterface.getName())) {
                return null;
            }

            List<? extends NetInterfaceAddress> addresses = netInterface.getNetInterfaceAddresses();
            if (addresses.isEmpty()) {
                return null;
            }

            IPAddress ipAddress = addresses.get(0).getAddress();
            if (ipAddress != null) {
                logger.debug("Found docker0 interface with address: {}", ipAddress.getHostAddress());
                return ipAddress.getHostAddress();
            }
            return null;
        }

        private String getDockerBridgeViaJavaApi() {
            try {
                NetworkInterface dockerInterface = NetworkInterface.getByName("docker0");
                if (dockerInterface != null) {
                    Enumeration<InetAddress> addresses = dockerInterface.getInetAddresses();
                    if (addresses.hasMoreElements()) {
                        String address = addresses.nextElement().getHostAddress();
                        logger.debug("Found docker0 interface with address (via Java API): {}", address);
                        return address;
                    }
                }
            } catch (Exception e) {
                logger.debug("Failed to detect docker0 interface using Java NetworkInterface API", e);
            }
            return null;
        }

        private String getHostPrimaryIpAddress() {
            try {
                Enumeration<NetworkInterface> nifs = NetworkInterface.getNetworkInterfaces();
                if (nifs != null) {
                    return findSuitableNetworkAddress(nifs);
                }
            } catch (Exception e) {
                logger.warn("Failed to determine host IP address", e);
            }
            return null;
        }

        private String findSuitableNetworkAddress(Enumeration<NetworkInterface> nifs) throws Exception {
            while (nifs.hasMoreElements()) {
                NetworkInterface nif = nifs.nextElement();
                String address = getAddressFromInterface(nif);
                if (address != null) {
                    return address;
                }
            }
            return null;
        }

        private String getAddressFromInterface(NetworkInterface nif) throws Exception {
            if (!isValidNetworkInterface(nif)) {
                return null;
            }

            Enumeration<InetAddress> nadrs = nif.getInetAddresses();
            while (nadrs.hasMoreElements()) {
                InetAddress adr = nadrs.nextElement();
                if (isValidAddress(adr, nif)) {
                    logger.debug("Using host primary IP address: {}", adr.getHostAddress());
                    return adr.getHostAddress();
                }
            }
            return null;
        }

        private boolean isValidNetworkInterface(NetworkInterface nif) throws Exception {
            return !nif.isLoopback() && nif.isUp() && !nif.isVirtual() && nif.getHardwareAddress() != null;
        }

        private boolean isValidAddress(InetAddress adr, NetworkInterface nif) throws SocketException {
            return adr != null && !adr.isLoopbackAddress() && (nif.isPointToPoint() || !adr.isLinkLocalAddress());
        }

    }

    private class Created implements State {

        private final ContainerInstanceOptions options;
        private final String containerId;

        public Created(ContainerInstanceOptions options, String containerId) {
            this.options = options;
            this.containerId = containerId;
        }

        private void deleteContainer() {
            try {
                ContainerInstance.this.containerOrchestrationService.stopContainer(this.containerId);
            } catch (Exception e) {
                logger.error("Error stopping microservice {}", this.options.getContainerName(), e);
            }

            try {
                ContainerInstance.this.containerOrchestrationService.deleteContainer(this.containerId);
            } catch (Exception e) {
                logger.error("Error deleting microservice {}", this.options.getContainerName(), e);
            }

            cleanupTemporaryIdentity();
        }

        @Override
        public State onConfigurationUpdated(ContainerInstanceOptions options) {
            if (options.equals(this.options)) {
                return this;
            }

            deleteContainer();

            if (options.isEnabled()) {
                return new Starting(options);
            } else {
                return new Disabled(options);
            }
        }

        @Override
        public State onDisabled() {
            deleteContainer();
            return new Disabled(this.options);
        }

    }

    private Map<String, Object> updatePropertiesWithSignatureDigest(Map<String, Object> oldProperties,
            String enforcementDigest) {

        Map<String, Object> updatedProperties = new HashMap<>(oldProperties);
        updatedProperties.put("container.signature.enforcement.digest", enforcementDigest);
        return updatedProperties;

    }

    private void updateSnapshotWithSignatureDigest(Map<String, Object> properties) {

        try {
            this.configurationService.updateConfiguration(
                    (String) properties.get(ConfigurationService.KURA_SERVICE_PID), properties, true);
        } catch (KuraException ex) {
            logger.error("Impossible to update snapshot for pid {} due to {}",
                    properties.get(ConfigurationService.KURA_SERVICE_PID), ex.getMessage());
        }
    }

    private void cleanupTemporaryIdentity() {
        final String identityName = this.currentTemporaryIdentityName.getAndSet(null);
        clearTemporaryPassword();

        if (identityName != null && this.identityService != null) {
            try {
                this.identityService.deleteIdentity(identityName);
                logger.info("Cleaned up temporary identity: {}", identityName);
            } catch (KuraException e) {
                logger.warn("Failed to cleanup temporary identity: {}", identityName, e);
            }
        }
    }

    private void clearTemporaryPassword() {
        final char[] password = this.currentTemporaryPassword.getAndSet(null);
        if (password != null) {
            Arrays.fill(password, '\0');
        }
    }

}
