/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.container.provider;

import java.security.SecureRandom;
import java.util.Random;

import org.eclipse.kura.identity.PasswordStrengthRequirements;

public class PasswordGenerator {

    private static final char[] SPECIAL_CHARS = { '!', '#', '$', '%', '&', '\'', '(', ')', '*', '+', ',', '-', '.', '/',
            ':', ';', '?', '@', '[', ']', '^', '_', '{', '|', '~' };
    private static final int SPECIAL_CHARS_BOUND = SPECIAL_CHARS.length;
    private static final int DIGITS_BOUND = SPECIAL_CHARS_BOUND + ('9' - '0' + 1);
    private static final int LOWERCASE_BOUND = DIGITS_BOUND + ('z' - 'a' + 1);
    private static final int UPPERCASE_BOUND = LOWERCASE_BOUND + ('Z' - 'A' + 1);
    private static final Random RANDOM = new SecureRandom();

    private PasswordGenerator() {
    }

    private static char charInRange(final Random random, final char lower, final char upper) {
        return (char) random.nextInt(lower, (upper) + 1);
    }

    private static int freeIndex(final Random random, final char[] values) {
        int result;

        do {
            result = random.nextInt(values.length);
        } while (values[result] != '\u0000');

        return result;
    }

    public static char[] generatePassword(final PasswordStrengthRequirements requirements) {
        final char[] pwd = new char[Math.max(32, requirements.getPasswordMinimumLength())];

        if (requirements.digitsRequired()) {
            pwd[freeIndex(RANDOM, pwd)] = charInRange(RANDOM, '0', '9');
        }

        if (requirements.specialCharactersRequired()) {
            pwd[freeIndex(RANDOM, pwd)] = SPECIAL_CHARS[RANDOM.nextInt(SPECIAL_CHARS.length)];
        }

        if (requirements.bothCasesRequired()) {
            pwd[freeIndex(RANDOM, pwd)] = charInRange(RANDOM, 'A', 'Z');
            pwd[freeIndex(RANDOM, pwd)] = charInRange(RANDOM, 'a', 'z');
        }

        for (int i = 0; i < pwd.length; i++) {
            if (pwd[i] != '\u0000') {
                continue;
            }

            final int index = RANDOM.nextInt(UPPERCASE_BOUND);

            char result;

            if (index < SPECIAL_CHARS_BOUND) {
                result = SPECIAL_CHARS[index];
            } else if (index < DIGITS_BOUND) {
                result = (char) ('0' + (index - SPECIAL_CHARS_BOUND));
            } else if (index < LOWERCASE_BOUND) {
                result = (char) ('a' + (index - DIGITS_BOUND));
            } else {
                result = (char) ('A' + (index - LOWERCASE_BOUND));
            }

            pwd[i] = result;
        }

        return pwd;
    }
}
