/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.container.provider;

import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.CharBuffer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.Optional;
import java.util.UUID;

import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.KuraException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Stores a container authentication token in a tmpfs-backed file so that it can be
 * bind-mounted into the container instead of being passed as an environment variable.
 */
class TokenFileManager {

    static final String TMPFS_BASE_PROPERTY = "kura.tmpfs.base";
    static final String DEFAULT_TMPFS_BASE = "/dev/shm";
    static final String TOKENS_DIRECTORY_NAME = "kura-tokens";
    static final String TOKEN_FILE_NAME = "kura-token";

    private static final Logger logger = LoggerFactory.getLogger(TokenFileManager.class);

    private Path tokenDirectory;

    synchronized Path writeToken(final char[] password) throws KuraException {
        cleanup();

        final String base = System.getProperty(TMPFS_BASE_PROPERTY, DEFAULT_TMPFS_BASE);
        final Path basePath = Paths.get(base);

        if (!Files.isDirectory(basePath)) {
            throw new KuraException(KuraErrorCode.CONFIGURATION_ERROR,
                    "tmpfs base directory " + basePath.toAbsolutePath()
                            + " does not exist. The platform does not provide a tmpfs mount at this location:"
                            + " set the \"" + TMPFS_BASE_PROPERTY
                            + "\" system property to an existing tmpfs directory");
        }

        final Path tokensRoot = basePath.resolve(TOKENS_DIRECTORY_NAME);
        final Path directory = tokensRoot.resolve(UUID.randomUUID().toString());
        final Path tokenFile = directory.resolve(TOKEN_FILE_NAME);

        try {
            Files.createDirectories(directory);
            // Restrict both the shared "kura-tokens" root and the per-token UUID directory to the owner so that
            // the token file cannot be traversed to by other local users.
            setPosixPermissions(tokensRoot, "rwx------");
            setPosixPermissions(directory, "rwx------");

            final ByteBuffer encoded = StandardCharsets.UTF_8.encode(CharBuffer.wrap(password));
            final byte[] bytes = new byte[encoded.remaining()];
            encoded.get(bytes);
            if (encoded.hasArray()) {
                Arrays.fill(encoded.array(), (byte) 0);
            }
            try {
                Files.write(tokenFile, bytes);
            } finally {
                Arrays.fill(bytes, (byte) 0);
            }

            setPosixPermissions(tokenFile, "r--------");
        } catch (final IOException e) {
            deleteBestEffort(tokenFile, directory);
            throw new KuraException(KuraErrorCode.INTERNAL_ERROR, e,
                    "failed to create token file " + tokenFile.toAbsolutePath() + ". Verify that "
                            + basePath.toAbsolutePath() + " is a writable tmpfs mount");
        }

        this.tokenDirectory = directory;
        return tokenFile;
    }

    synchronized void cleanup() {
        final Path directory = this.tokenDirectory;
        this.tokenDirectory = null;

        if (directory == null) {
            return;
        }

        deleteBestEffort(directory.resolve(TOKEN_FILE_NAME), directory);
    }

    synchronized Optional<Path> getTokenFilePath() {
        return Optional.ofNullable(this.tokenDirectory).map(dir -> dir.resolve(TOKEN_FILE_NAME));
    }

    private static void setPosixPermissions(final Path path, final String permissions) throws IOException {
        try {
            Files.setPosixFilePermissions(path,
                    java.nio.file.attribute.PosixFilePermissions.fromString(permissions));
        } catch (final UnsupportedOperationException e) {
            // Non-POSIX platform (e.g. Windows during development): nothing we can do, warn and continue.
            logger.warn("POSIX file permissions are not supported, unable to restrict access to {}", path, e);
        }
        // An IOException here means we could not restrict access on a POSIX platform: let it propagate so that the
        // caller aborts and deletes the partially created token rather than exposing a world-readable secret.
    }

    private static void deleteBestEffort(final Path tokenFile, final Path directory) {
        try {
            Files.deleteIfExists(tokenFile);
            Files.deleteIfExists(directory);
        } catch (final IOException e) {
            logger.warn("failed to delete token directory {}", directory, e);
        }
    }
}
