<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) ${year} Eurotech and/or its affiliates and others

    This program and the accompanying materials are made
    available under the terms of the Eclipse Public License 2.0
    which is available at https://www.eclipse.org/legal/epl-2.0/

    SPDX-License-Identifier: EPL-2.0

    Contributors:
     Eurotech

-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>${groupId}</groupId>
        <artifactId>${artifactId}</artifactId>
        <version>${version}</version>
    </parent>

    <artifactId>${artifactId}-tests</artifactId>
    <packaging>pom</packaging>
    <description>Tests aggregator project of ${artifactId}</description>

    <properties>
        <kura.workdir>${project.build.directory}/test-env</kura.workdir>
        <mockito.version>5.21.0</mockito.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>${mockito.version}</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13.2</version>
        </dependency>

        <!-- This OSGi bundle wraps junit 4.13.2 jar file. -->
        <dependency>
            <groupId>org.apache.servicemix.bundles</groupId>
            <artifactId>org.apache.servicemix.bundles.junit</artifactId>
            <version>4.13.2_1</version>
        </dependency>

        <dependency>
            <groupId>com.github.moquette-io.moquette</groupId>
            <artifactId>moquette-broker</artifactId>
        </dependency>

        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>kura-pde-deps</artifactId>
            <version>6.0.0-SNAPSHOT</version>
            <type>pom</type>
        </dependency>

        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>target-platform-pde-deps</artifactId>
            <version>6.0.0-SNAPSHOT</version>
            <type>pom</type>
        </dependency>
    </dependencies>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-resources-plugin</artifactId>
                    <version>3.3.1</version>
                    <executions>
                        <execution>
                            <id>generate-test-env</id>
                            <phase>generate-test-resources</phase>
                            <goals>
                                <goal>copy-resources</goal>
                            </goals>
                            <configuration>
                                <includeEmptyDirs>true</includeEmptyDirs>
                                <outputDirectory>${kura.workdir}</outputDirectory>
                                <resources>
                                    <resource>
                                        <directory>../test-env</directory>
                                        <includes>
                                            <include>data</include>
                                            <include>framework/*</include>
                                            <include>log4j/*</include>
                                            <include>user/**/*</include>
                                        </includes>
                                        <filtering>false</filtering>
                                    </resource>
                                </resources>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-antrun-plugin</artifactId>
                    <executions>
                        <execution>
                            <id>prepare-test-env</id>
                            <phase>process-test-resources</phase>
                            <goals>
                                <goal>run</goal>
                            </goals>
                            <configuration>
                                <target>
                                    <replace
                                        file="${kura.workdir}/framework/kura.properties"
                                        token="/tmp/kura"
                                        value="${kura.workdir}" />
                                    <replace
                                        file="${kura.workdir}/user/snapshots/snapshot_0.xml"
                                        token="/tmp/kura"
                                        value="${kura.workdir}" />
                                </target>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>

                <plugin>
                    <groupId>org.jacoco</groupId>
                    <artifactId>jacoco-maven-plugin</artifactId>
                    <version>0.8.12</version>
                    <executions>
                        <execution>
                            <goals>
                                <goal>prepare-agent</goal>
                            </goals>
                        </execution>
                        <execution>
                            <id>report</id>
                            <phase>verify</phase>
                            <goals>
                                <goal>report-aggregate</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>

                <plugin>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>2.22.2</version>
                    <executions>
                        <execution>
                            <id>default-test</id>
                            <phase>test</phase>
                            <goals>
                                <goal>test</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration/>
                </plugin>

                <plugin>
                    <groupId>biz.aQute.bnd</groupId>
                    <artifactId>bnd-resolver-maven-plugin</artifactId>
                    <executions>
                        <execution>
                            <id>osgi-integration-resolving</id>
                            <phase>none</phase>
                        </execution>
                    </executions>
                </plugin>

            </plugins>
        </pluginManagement>
    </build>

    <!-- This profile is used to resolve the OSGi integration test dependencies before running the tests. -->
    <profiles>
        <profile>
            <id>resolve-integration-tests</id>
            <build>
                <pluginManagement>
                    <plugins>
                        <plugin>
                            <groupId>biz.aQute.bnd</groupId>
                            <artifactId>bnd-resolver-maven-plugin</artifactId>
                            <executions>
                                <execution>
                                    <id>osgi-integration-resolving</id>
                                    <phase>pre-integration-test</phase>
                                </execution>
                            </executions>
                        </plugin>
                    </plugins>
                </pluginManagement>
            </build>
        </profile>
    </profiles>

    <modules>
        <module>${package}.test</module>
    </modules>

</project>
