/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.rest.keystore.provider;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;

import java.security.KeyStore.Entry;
import java.util.Optional;

import javax.security.auth.x500.X500Principal;

import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.KuraException;
import org.eclipse.kura.internal.rest.keystore.provider.KeystoreRestService;
import org.eclipse.kura.internal.rest.keystore.request.CsrReadRequest;
import org.eclipse.kura.internal.rest.keystore.request.EntryRequest;
import org.eclipse.kura.internal.rest.keystore.request.TrustedCertificateWriteRequest;
import org.eclipse.kura.security.keystore.KeystoreService;
import org.junit.Test;
import org.osgi.service.component.ComponentContext;

import jakarta.ws.rs.WebApplicationException;

public class KeystoreErrorResponseTest {

    private static final String KEYSTORE_PID = "MyKeystore";
    private static final String ALIAS = "MyAlias";
    private static final String SIGNATURE_ALGORITHM = "SHA256withRSA";
    private static final String VALID_DISTINGUISHED_NAME = "CN=Kura, OU=IoT, O=Eclipse, C=US";

    @Test
    public void shouldReturnBadRequestWhenCsrDistinguishedNameIsInvalid() throws KuraException {
        givenKeystoreService();

        whenCsrIsRequested("not a distinguished name");

        thenResponseStatusIs(400);
        thenCsrIsNotGenerated();
    }

    @Test
    public void shouldReturnNotFoundWhenCsrEntryIsMissing() throws KuraException {
        givenKeystoreService();
        givenCsrFailsWith(KuraErrorCode.NOT_FOUND);

        whenCsrIsRequested(VALID_DISTINGUISHED_NAME);

        thenResponseStatusIs(404);
    }

    @Test
    public void shouldReturnBadRequestWhenCertificateIsMalformed() throws KuraException {
        givenKeystoreService();

        whenTrustedCertificateIsStored("not a certificate");

        thenResponseStatusIs(400);
        thenNoEntryIsStored();
    }

    @Test
    public void shouldReturnNotFoundWhenEntryToDeleteIsMissing() throws KuraException {
        givenKeystoreService();
        givenDeleteFailsWith(KuraErrorCode.NOT_FOUND);

        whenEntryIsDeleted();

        thenResponseStatusIs(404);
    }

    @Test
    public void shouldReturnBadRequestWhenKeystoreRejectsDeletion() throws KuraException {
        givenKeystoreService();
        givenDeleteFailsWith(KuraErrorCode.BAD_REQUEST);

        whenEntryIsDeleted();

        thenResponseStatusIs(400);
    }

    @Test
    public void shouldReturnInternalServerErrorWhenEntriesCannotBeRead() throws KuraException {
        givenKeystoreService();
        givenReadingEntriesFailsWith(KuraErrorCode.INTERNAL_ERROR);

        whenEntriesAreRead();

        thenResponseStatusIs(500);
    }

    private final KeystoreService keystoreService = mock(KeystoreService.class);
    private KeystoreRestService restService;
    private Optional<Exception> exception = Optional.empty();

    private void givenKeystoreService() {
        this.restService = new KeystoreRestService() {

            @Override
            public void activate(ComponentContext componentContext) {
                this.keystoreServices.put(KEYSTORE_PID, KeystoreErrorResponseTest.this.keystoreService);
            }
        };
        this.restService.activate(null);
    }

    private void givenCsrFailsWith(final KuraErrorCode code) throws KuraException {
        doThrow(new KuraException(code)).when(this.keystoreService).getCSR(anyString(), any(X500Principal.class),
                anyString());
    }

    private void givenDeleteFailsWith(final KuraErrorCode code) throws KuraException {
        doThrow(new KuraException(code)).when(this.keystoreService).deleteEntry(ALIAS);
    }

    private void givenReadingEntriesFailsWith(final KuraErrorCode code) throws KuraException {
        doThrow(new KuraException(code)).when(this.keystoreService).getEntries();
    }

    private void whenCsrIsRequested(final String distinguishedName) {
        final CsrReadRequest request = new CsrReadRequest(KEYSTORE_PID, ALIAS);
        request.setSignatureAlgorithm(SIGNATURE_ALGORITHM);
        request.setAttributes(distinguishedName);

        try {
            this.restService.getCSR(request);
        } catch (final Exception e) {
            this.exception = Optional.of(e);
        }
    }

    private void whenTrustedCertificateIsStored(final String certificate) {
        final TrustedCertificateWriteRequest request = new TrustedCertificateWriteRequest(KEYSTORE_PID, ALIAS);
        request.setCertificate(certificate);

        try {
            this.restService.storeTrustedCertificateEntry(request);
        } catch (final Exception e) {
            this.exception = Optional.of(e);
        }
    }

    private void whenEntryIsDeleted() {
        try {
            this.restService.deleteKeyEntry(new EntryRequest(KEYSTORE_PID, ALIAS));
        } catch (final Exception e) {
            this.exception = Optional.of(e);
        }
    }

    private void whenEntriesAreRead() {
        try {
            this.restService.getEntries(KEYSTORE_PID, null);
        } catch (final Exception e) {
            this.exception = Optional.of(e);
        }
    }

    private void thenResponseStatusIs(final int expectedStatus) {
        assertTrue(this.exception.isPresent());
        assertTrue("unexpected exception: " + this.exception.get(),
                this.exception.get() instanceof WebApplicationException);
        assertEquals(expectedStatus, ((WebApplicationException) this.exception.get()).getResponse().getStatus());
    }

    private void thenCsrIsNotGenerated() throws KuraException {
        verify(this.keystoreService, never()).getCSR(anyString(), any(X500Principal.class), anyString());
    }

    private void thenNoEntryIsStored() throws KuraException {
        verify(this.keystoreService, never()).setEntry(anyString(), any(Entry.class));
    }
}
