/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.core.identity.store;

import java.time.Duration;
import java.time.Instant;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

import org.eclipse.kura.identity.IdentityConfiguration;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * In-memory store for temporary identities that are not persisted.
 * Temporary identities use the same IdentityConfiguration structure as regular identities
 * but are stored in-memory only and have automatic expiration.
 */
public class TemporaryIdentityStore {

    private static final Logger logger = LoggerFactory.getLogger(TemporaryIdentityStore.class);

    private final Map<String, TemporaryIdentityRecord> identities = new ConcurrentHashMap<>();
    private final ScheduledExecutorService expirationScheduler;

    /**
     * Record storing a temporary identity configuration and its expiration time.
     */
    static class TemporaryIdentityRecord {
        final IdentityConfiguration configuration;
        final Instant expiration;

        TemporaryIdentityRecord(IdentityConfiguration configuration, Duration lifetime) {
            this.configuration = configuration;
            this.expiration = Instant.now().plus(lifetime);
        }

        TemporaryIdentityRecord(IdentityConfiguration configuration, Instant expiration) {
            this.configuration = configuration;
            this.expiration = expiration;
        }

        boolean isExpired() {
            return Instant.now().isAfter(expiration);
        }
    }

    /**
     * Creates a new temporary identity store with automatic expiration cleanup.
     */
    public TemporaryIdentityStore() {
        this.expirationScheduler = Executors.newSingleThreadScheduledExecutor(r -> {
            Thread thread = new Thread(r, "TemporaryIdentityStore-Cleanup");
            thread.setDaemon(true);
            return thread;
        });

        // Schedule periodic cleanup every minute
        this.expirationScheduler.scheduleWithFixedDelay(this::cleanupExpired, 1, 1, TimeUnit.MINUTES);
    }

    /**
     * Creates a temporary identity with the given configuration and lifetime.
     *
     * @param name          the identity name
     * @param configuration the identity configuration
     * @param lifetime      the duration before automatic expiration
     */
    public void createIdentity(String name, IdentityConfiguration configuration, Duration lifetime) {
        TemporaryIdentityRecord identityRecord = new TemporaryIdentityRecord(configuration, lifetime);
        identities.put(name, identityRecord);

        // Schedule individual expiration
        scheduleExpiration(name, lifetime);

        logger.info("Created temporary identity '{}' with expiration at {}", name, identityRecord.expiration);
    }

    /**
     * Retrieves a temporary identity configuration if it exists and is not expired.
     *
     * @param name the identity name
     * @return the identity configuration if found and not expired, empty otherwise
     */
    public Optional<IdentityConfiguration> getIdentity(String name) {
        TemporaryIdentityRecord identityRecord = identities.get(name);

        if (identityRecord == null) {
            return Optional.empty();
        }

        if (identityRecord.isExpired()) {
            // Auto-cleanup expired identity
            identities.remove(name);
            logger.debug("Temporary identity '{}' has expired and was removed", name);
            return Optional.empty();
        }

        return Optional.of(identityRecord.configuration);
    }

    /**
     * Checks if a temporary identity exists (and is not expired).
     *
     * @param name the identity name
     * @return true if the identity exists and is not expired
     */
    public boolean exists(String name) {
        return getIdentity(name).isPresent();
    }

    /**
     * Deletes a temporary identity.
     *
     * @param name the identity name
     * @return true if the identity was deleted, false if it didn't exist
     */
    public boolean deleteIdentity(String name) {
        boolean removed = identities.remove(name) != null;
        if (removed) {
            logger.info("Deleted temporary identity '{}'", name);
        }
        return removed;
    }

    /**
     * Updates a temporary identity configuration while preserving its expiration.
     *
     * @param name the identity name
     * @param configuration the new configuration
     * @return true if the identity existed and was updated
     */
    public boolean updateIdentity(String name, IdentityConfiguration configuration) {
        final TemporaryIdentityRecord identityRecord = identities.get(name);
        if (identityRecord == null) {
            return false;
        }

        if (identityRecord.isExpired()) {
            identities.remove(name);
            logger.debug("Temporary identity '{}' has expired and was removed", name);
            return false;
        }

        identities.put(name, new TemporaryIdentityRecord(configuration, identityRecord.expiration));
        return true;
    }

    /**
     * Returns all temporary identity names (not expired).
     *
     * @return array of identity names
     */
    public String[] getAllIdentityNames() {
        // Remove expired entries first
        cleanupExpired();
        return identities.keySet().toArray(new String[0]);
    }

    /**
     * Shuts down the expiration scheduler.
     */
    public void shutdown() {
        logger.info("Shutting down temporary identity store");
        expirationScheduler.shutdown();
        try {
            if (!expirationScheduler.awaitTermination(5, TimeUnit.SECONDS)) {
                expirationScheduler.shutdownNow();
            }
        } catch (InterruptedException e) {
            expirationScheduler.shutdownNow();
            Thread.currentThread().interrupt();
        }
        identities.clear();
    }

    /**
     * Schedules the expiration of a temporary identity.
     *
     * @param name     the identity name
     * @param lifetime the duration before expiration
     */
    private void scheduleExpiration(String name, Duration lifetime) {
        expirationScheduler.schedule(() -> {
            boolean removed = identities.remove(name) != null;
            if (removed) {
                logger.info("Temporary identity '{}' expired and was removed", name);
            }
        }, lifetime.toMillis(), TimeUnit.MILLISECONDS);
    }

    /**
     * Removes all expired identities.
     */
    private void cleanupExpired() {
        identities.entrySet().removeIf(entry -> {
            boolean expired = entry.getValue().isExpired();
            if (expired) {
                logger.debug("Cleaning up expired temporary identity '{}'", entry.getKey());
            }
            return expired;
        });
    }
}
