/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.container.provider;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.lang.reflect.Field;
import java.time.Duration;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicReference;

import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.KuraException;
import org.eclipse.kura.configuration.ConfigurationService;
import org.eclipse.kura.container.orchestration.ContainerConfiguration;
import org.eclipse.kura.container.orchestration.ContainerOrchestrationService;
import org.eclipse.kura.identity.AssignedPermissions;
import org.eclipse.kura.identity.IdentityConfiguration;
import org.eclipse.kura.identity.IdentityService;
import org.eclipse.kura.identity.PasswordConfiguration;
import org.eclipse.kura.identity.Permission;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.mockito.ArgumentCaptor;
import org.mockito.Mockito;

/**
 * Feature: Container instance identity integration with temporary identities enabled.
 */
public class ContainerIdentityIntegrationTest {

    private static final String CONTAINER_NAME = "kura-test-container";
    private static final String CONTAINER_IMAGE = "nginx";
    private static final String CONTAINER_TAG = "latest";
    private static final String PERMISSIONS = "rest.read,rest.write";
    private static final String CONTAINER_ID = "container-id";
    private static final String SECOND_CONTAINER_ID = "container-id-2";
    private static final String UPDATED_CONTAINER_NAME = CONTAINER_NAME + "-v2";

    private ContainerInstance containerInstance;
    private ContainerOrchestrationService containerOrchestrationService;
    private IdentityService identityService;
    private ConfigurationService configurationService;
    private Map<String, Object> properties;
    private CountDownLatch startLatch;
    private AtomicInteger createCount;
    private AtomicInteger deleteCount;
    private AtomicInteger startCount;
    private ArgumentCaptor<ContainerConfiguration> configurationCaptor;
    private ArgumentCaptor<String> identityNameCaptor;
    private ArgumentCaptor<IdentityConfiguration> identityConfigCaptor;
    private ArgumentCaptor<Duration> durationCaptor;
    private List<String> capturedPasswords = new ArrayList<>();
    private List<String> capturedIdentityNames = new ArrayList<>();

    @Before
    public void setUp() {
        this.containerInstance = new ContainerInstance();
        this.containerOrchestrationService = Mockito.mock(ContainerOrchestrationService.class);
        this.identityService = Mockito.mock(IdentityService.class);
        this.configurationService = Mockito.mock(ConfigurationService.class);
        this.properties = new HashMap<>();
        this.startLatch = new CountDownLatch(1);
        this.createCount = new AtomicInteger(0);
        this.deleteCount = new AtomicInteger(0);
        this.startCount = new AtomicInteger(0);
        this.configurationCaptor = ArgumentCaptor.forClass(ContainerConfiguration.class);
        this.identityNameCaptor = ArgumentCaptor.forClass(String.class);
        this.identityConfigCaptor = ArgumentCaptor.forClass(IdentityConfiguration.class);
        this.durationCaptor = ArgumentCaptor.forClass(Duration.class);

        this.containerInstance.setContainerOrchestrationService(this.containerOrchestrationService);
        this.containerInstance.setIdentityService(this.identityService);
        this.containerInstance.setConfigurationService(this.configurationService);

        when(this.containerOrchestrationService.listContainerDescriptors()).thenReturn(Collections.emptyList());
    }

    @After
    public void tearDown() {
        this.containerInstance.deactivate();
    }

    @Test
    public void createsTemporaryIdentityAndInjectsToken() throws Exception {
        givenIdentityIntegrationIsEnabled();
        givenTemporaryIdentityServiceProvidesPassword();
        givenContainerOrchestratorStartsSuccessfully();

        whenContainerInstanceIsActivated();

        thenTemporaryIdentityIsCreatedWithPermissions();
        thenStartContainerReceivesTokenEnvironment();
    }

    @Test
    public void deletesTemporaryIdentityWhenContainerIsDisabled() throws Exception {
        givenIdentityIntegrationIsEnabled();
        givenTemporaryIdentityServiceProvidesPassword();
        givenContainerOrchestratorStartsSuccessfully();

        whenContainerInstanceIsActivatedUntilCreated();
        whenContainerInstanceIsDisabled();

        thenTemporaryIdentityIsDeleted();
    }

    @Test
    public void recreatesTemporaryIdentityOnConfigurationChange() throws Exception {
        givenIdentityIntegrationIsEnabled();
        givenTemporaryIdentityServiceProvidesPassword();
        givenContainerOrchestratorStartsSuccessfullyWithIds(CONTAINER_ID, SECOND_CONTAINER_ID);

        whenContainerInstanceIsActivatedUntilCreated();
        whenContainerConfigurationIsUpdatedWithNewName();

        thenTemporaryIdentityIsRecreated();
        thenLatestContainerStartReceivesRefreshedPassword();
    }

    @Test
    public void cleansUpTemporaryIdentityOnceAcrossMultipleShutdowns() throws Exception {
        givenIdentityIntegrationIsEnabled();
        givenTemporaryIdentityServiceProvidesPassword();
        givenContainerOrchestratorStartsSuccessfully();

        whenContainerInstanceIsActivatedUntilCreated();
        whenContainerInstanceIsDisabled();
        whenContainerInstanceIsDeactivated();

        thenTemporaryIdentityIsDeletedOnlyOnce();
    }

    @Test
    public void clearsTemporaryPasswordAfterContainerStarts() throws Exception {
        givenIdentityIntegrationIsEnabled();
        givenTemporaryIdentityServiceProvidesPassword();
        givenContainerOrchestratorStartsSuccessfully();

        whenContainerInstanceIsActivatedUntilCreated();

        thenTemporaryPasswordIsCleared();
    }

    @Test
    public void clearsTemporaryPasswordAfterStartupFailure() throws Exception {
        givenIdentityIntegrationIsEnabled();
        givenTemporaryIdentityServiceProvidesPassword();
        givenContainerOrchestratorFailsToStart();
        givenFastRetryConfiguration();

        whenContainerInstanceIsActivatedUntilDisabled();

        thenTemporaryPasswordIsCleared();
    }

    /*
     * GIVEN
     */

    private void givenIdentityIntegrationIsEnabled() {
        this.properties.put("container.enabled", true);
        this.properties.put("container.name", CONTAINER_NAME);
        this.properties.put("kura.service.pid", CONTAINER_NAME);
        this.properties.put("container.image", CONTAINER_IMAGE);
        this.properties.put("container.image.tag", CONTAINER_TAG);
        this.properties.put("container.identity.enabled", true);
        this.properties.put("container.permissions", PERMISSIONS);
    }

    private void givenTemporaryIdentityServiceProvidesPassword() throws Exception {
        doAnswer(invocation -> {
            this.createCount.incrementAndGet();

            // Extract identity name and password from configuration (first argument)
            IdentityConfiguration config = invocation.getArgument(0);
            this.capturedIdentityNames.add(config.getName());
            final char[] newPassword = config.getComponent(PasswordConfiguration.class).orElseThrow()
                    .getNewPassword().orElseThrow();
            this.capturedPasswords.add(new String(newPassword));

            return null; // API returns void
        }).when(this.identityService).createTemporaryIdentity(
                this.identityConfigCaptor.capture(), this.durationCaptor.capture());

        doAnswer(invocation -> {
            this.deleteCount.incrementAndGet();
            return true; // New API returns boolean
        }).when(this.identityService).deleteIdentity(anyString());
    }

    private void givenContainerOrchestratorStartsSuccessfully() throws Exception {
        doAnswer(invocation -> {
            this.startLatch.countDown();
            this.startCount.incrementAndGet();
            return CONTAINER_ID;
        }).when(this.containerOrchestrationService).startContainer(this.configurationCaptor.capture());
    }

    private void givenContainerOrchestratorStartsSuccessfullyWithIds(final String... containerIds) throws Exception {
        this.startLatch = new CountDownLatch(containerIds.length);
        this.startCount.set(0);
        final AtomicInteger index = new AtomicInteger(0);

        doAnswer(invocation -> {
            this.startLatch.countDown();
            this.startCount.incrementAndGet();
            final int current = Math.min(index.getAndIncrement(), containerIds.length - 1);
            return containerIds[current];
        }).when(this.containerOrchestrationService).startContainer(this.configurationCaptor.capture());
    }

    private void givenContainerOrchestratorFailsToStart() throws Exception {
        doAnswer(invocation -> {
            this.startCount.incrementAndGet();
            throw new KuraException(KuraErrorCode.SERVICE_UNAVAILABLE);
        }).when(this.containerOrchestrationService).startContainer(this.configurationCaptor.capture());
    }

    private void givenFastRetryConfiguration() {
        this.properties.put("container.image.download.retries", 1);
        this.properties.put("container.image.download.interval", 0);
    }

    /*
     * WHEN
     */

    private void whenContainerInstanceIsActivated() {
        this.containerInstance.activate(this.properties);
    }

    private void whenContainerInstanceIsActivatedUntilCreated() throws InterruptedException {
        this.containerInstance.activate(this.properties);
        thenWaitForContainerState("Created");
    }

    private void whenContainerInstanceIsActivatedUntilDisabled() throws InterruptedException {
        this.containerInstance.activate(this.properties);
        thenWaitForContainerState("Disabled");
    }

    private void whenContainerConfigurationIsUpdatedWithNewName() throws InterruptedException {
        final Map<String, Object> updated = new HashMap<>(this.properties);
        updated.put("container.name", UPDATED_CONTAINER_NAME);
        updated.put("kura.service.pid", UPDATED_CONTAINER_NAME);

        this.containerInstance.updated(updated);
        thenWaitForContainerState("Created");
    }

    private void whenContainerInstanceIsDisabled() {
        final Map<String, Object> disabled = new HashMap<>(this.properties);
        disabled.put("container.enabled", false);

        this.containerInstance.updated(disabled);
    }

    private void whenContainerInstanceIsDeactivated() {
        this.containerInstance.deactivate();
    }

    /*
     * THEN
     */

    private void thenTemporaryIdentityIsCreatedWithPermissions() throws Exception {
        awaitCounterAtLeast(this.createCount, 1);

        final String expectedIdentityName = "container_" + CONTAINER_NAME.replace("-", "_");
        verify(this.identityService).createTemporaryIdentity(
                this.identityConfigCaptor.capture(), this.durationCaptor.capture());

        // Verify identity name from configuration
        IdentityConfiguration config = this.identityConfigCaptor.getValue();
        assertTrue("Identity name should match expected",
                config.getName().equals(expectedIdentityName));

        // Verify permissions from IdentityConfiguration
        AssignedPermissions assignedPermissions = config.getComponent(AssignedPermissions.class).orElseThrow();
        Set<Permission> permissions = assignedPermissions.getPermissions();

        assertTrue("Expected rest.read permission",
                permissions.stream().anyMatch(permission -> "rest.read".equals(permission.getName())));
        assertTrue("Expected rest.write permission",
                permissions.stream().anyMatch(permission -> "rest.write".equals(permission.getName())));
    }

    private void thenStartContainerReceivesTokenEnvironment() throws Exception {
        assertTrue("Container start was not invoked", this.startLatch.await(2, TimeUnit.SECONDS));

        final ContainerConfiguration configuration = this.configurationCaptor.getValue();
        final List<String> envVars = configuration.getContainerEnvVars();

        assertTrue("Identity name var missing",
                envVars.contains("KURA_IDENTITY_NAME=" + this.capturedIdentityNames.get(0)));
        assertTrue("Password var missing",
                envVars.contains("KURA_IDENTITY_PASSWORD=" + this.capturedPasswords.get(0)));
        // Check that KURA_REST_BASE_URL is set (now dynamic, not hardcoded to localhost:8080)
        assertTrue("Base URL env var missing",
                envVars.stream().anyMatch(envVar -> envVar.startsWith("KURA_REST_BASE_URL=")));
    }

    private void thenTemporaryIdentityIsDeleted() throws Exception {
        awaitCounterAtLeast(this.deleteCount, 1);
        assertEquals("Temporary identity was not deleted", 1, this.deleteCount.get());
        verify(this.identityService).deleteIdentity(this.capturedIdentityNames.get(0));
    }

    private void thenTemporaryIdentityIsDeletedOnlyOnce() throws Exception {
        awaitCounterAtLeast(this.deleteCount, 1);
        assertEquals("Temporary identity was not deleted", 1, this.deleteCount.get());
        verify(this.identityService, times(1)).deleteIdentity(this.capturedIdentityNames.get(0));
    }

    private void thenTemporaryIdentityIsRecreated() throws Exception {
        awaitCounterAtLeast(this.createCount, 2);
        awaitCounterAtLeast(this.deleteCount, 1);
        awaitCounterAtLeast(this.startCount, 2);

        assertEquals("Temporary identities were not created twice", 2, this.createCount.get());
        assertEquals("Original temporary identity was not cleaned up", 1, this.deleteCount.get());
        assertTrue("Container was not started twice", this.startLatch.await(5, TimeUnit.SECONDS));
    }

    private void thenLatestContainerStartReceivesRefreshedPassword() {
        // Extract the latest token from captured IdentityConfiguration
        final String latestPassword = this.capturedPasswords.get(this.capturedPasswords.size() - 1);

        // Verify the latest container start received this password
        final List<ContainerConfiguration> configurations = this.configurationCaptor.getAllValues();
        final ContainerConfiguration latestConfiguration = configurations.get(configurations.size() - 1);
        final List<String> envVars = latestConfiguration.getContainerEnvVars();

        assertTrue("Latest start should include refreshed token",
                envVars.contains("KURA_IDENTITY_PASSWORD=" + latestPassword));
    }

    private void thenTemporaryPasswordIsCleared() throws Exception {
        final Field field = ContainerInstance.class.getDeclaredField("currentTemporaryPassword");
        field.setAccessible(true);
        @SuppressWarnings("unchecked")
        final AtomicReference<char[]> passwordRef = (AtomicReference<char[]>) field.get(this.containerInstance);

        assertTrue("Temporary password should be cleared", passwordRef.get() == null);
    }

    private void thenWaitForContainerState(String expectedState) throws InterruptedException {
        int attempts = 50;
        while (!expectedState.equals(this.containerInstance.getState()) && attempts-- > 0) {
            Thread.sleep(100);
        }
    }

    private void awaitCounterAtLeast(final AtomicInteger counter, final int expected) throws InterruptedException {
        int attempts = 50;
        while (counter.get() < expected && attempts-- > 0) {
            Thread.sleep(100);
        }
        assertTrue("Counter did not reach expected value", counter.get() >= expected);
    }
}
