/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.container.provider;

import static org.junit.Assert.assertTrue;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoMoreInteractions;
import static org.mockito.Mockito.when;

import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;

import java.time.Duration;

import org.eclipse.kura.configuration.ConfigurationService;
import org.eclipse.kura.container.orchestration.ContainerConfiguration;
import org.eclipse.kura.container.orchestration.ContainerOrchestrationService;
import org.eclipse.kura.identity.AssignedPermissions;
import org.eclipse.kura.identity.IdentityConfiguration;
import org.eclipse.kura.identity.IdentityService;
import org.eclipse.kura.identity.Permission;
import org.eclipse.kura.identity.TokenConfiguration;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.mockito.ArgumentCaptor;
import org.mockito.Mockito;

/**
 * Feature: Container instance identity integration with temporary identities enabled.
 */
public class ContainerIdentityIntegrationTest {

    private static final String CONTAINER_NAME = "kura-test-container";
    private static final String CONTAINER_IMAGE = "nginx";
    private static final String CONTAINER_TAG = "latest";
    private static final String PERMISSIONS = "rest.read,rest.write";
    private static final String CONTAINER_ID = "container-id";
    private static final String SECOND_CONTAINER_ID = "container-id-2";
    private static final String UPDATED_CONTAINER_NAME = CONTAINER_NAME + "-v2";

    private ContainerInstance containerInstance;
    private ContainerOrchestrationService containerOrchestrationService;
    private IdentityService identityService;
    private ConfigurationService configurationService;
    private Map<String, Object> properties;
    private CountDownLatch startLatch;
    private CountDownLatch createLatch;
    private CountDownLatch deleteLatch;
    private AtomicInteger createCount;
    private AtomicInteger deleteCount;
    private AtomicInteger startCount;
    private ArgumentCaptor<ContainerConfiguration> configurationCaptor;
    private ArgumentCaptor<String> identityNameCaptor;
    private ArgumentCaptor<IdentityConfiguration> identityConfigCaptor;
    private ArgumentCaptor<Duration> durationCaptor;
    private String capturedToken;
    private String capturedIdentityName;

    @Before
    public void setUp() {
        this.containerInstance = new ContainerInstance();
        this.containerOrchestrationService = Mockito.mock(ContainerOrchestrationService.class);
        this.identityService = Mockito.mock(IdentityService.class);
        this.configurationService = Mockito.mock(ConfigurationService.class);
        this.properties = new HashMap<>();
        this.startLatch = new CountDownLatch(1);
        this.createLatch = new CountDownLatch(1);
        this.deleteLatch = new CountDownLatch(1);
        this.createCount = new AtomicInteger(0);
        this.deleteCount = new AtomicInteger(0);
        this.startCount = new AtomicInteger(0);
        this.configurationCaptor = ArgumentCaptor.forClass(ContainerConfiguration.class);
        this.identityNameCaptor = ArgumentCaptor.forClass(String.class);
        this.identityConfigCaptor = ArgumentCaptor.forClass(IdentityConfiguration.class);
        this.durationCaptor = ArgumentCaptor.forClass(Duration.class);

        this.containerInstance.setContainerOrchestrationService(this.containerOrchestrationService);
        this.containerInstance.setIdentityService(this.identityService);
        this.containerInstance.setConfigurationService(this.configurationService);

        when(this.containerOrchestrationService.listContainerDescriptors()).thenReturn(Collections.emptyList());
    }

    @After
    public void tearDown() {
        this.containerInstance.deactivate();
    }

    @Test
    public void createsTemporaryIdentityAndInjectsToken() throws Exception {
        givenIdentityIntegrationIsEnabled();
        givenTemporaryIdentityServiceProvidesToken();
        givenContainerOrchestratorStartsSuccessfully();

        whenContainerInstanceIsActivated();

        thenTemporaryIdentityIsCreatedWithPermissions();
        thenStartContainerReceivesTokenEnvironment();
    }

    @Test
    public void deletesTemporaryIdentityWhenContainerIsDisabled() throws Exception {
        givenIdentityIntegrationIsEnabled();
        givenTemporaryIdentityServiceProvidesToken();
        givenContainerOrchestratorStartsSuccessfully();

        whenContainerInstanceIsActivatedUntilCreated();
        whenContainerInstanceIsDisabled();

        thenTemporaryIdentityIsDeleted();
    }

    @Test
    public void recreatesTemporaryIdentityOnConfigurationChange() throws Exception {
        givenIdentityIntegrationIsEnabled();
        givenTemporaryIdentityServiceProvidesMultipleTokens();
        givenContainerOrchestratorStartsSuccessfullyWithIds(CONTAINER_ID, SECOND_CONTAINER_ID);

        whenContainerInstanceIsActivatedUntilCreated();
        whenContainerConfigurationIsUpdatedWithNewName();

        thenTemporaryIdentityIsRecreated();
        thenLatestContainerStartReceivesRefreshedToken();
    }

    @Test
    public void cleansUpTemporaryIdentityOnceAcrossMultipleShutdowns() throws Exception {
        givenIdentityIntegrationIsEnabled();
        givenTemporaryIdentityServiceProvidesToken();
        givenContainerOrchestratorStartsSuccessfully();

        whenContainerInstanceIsActivatedUntilCreated();
        whenContainerInstanceIsDisabled();
        whenContainerInstanceIsDeactivated();

        thenTemporaryIdentityIsDeletedOnlyOnce();
    }

    /*
     * GIVEN
     */

    private void givenIdentityIntegrationIsEnabled() {
        this.properties.put("container.enabled", true);
        this.properties.put("container.name", CONTAINER_NAME);
        this.properties.put("kura.service.pid", CONTAINER_NAME);
        this.properties.put("container.image", CONTAINER_IMAGE);
        this.properties.put("container.image.tag", CONTAINER_TAG);
        this.properties.put("container.identity.enabled", true);
        this.properties.put("container.permissions", PERMISSIONS);
    }

    private void givenTemporaryIdentityServiceProvidesToken() throws Exception {
        doAnswer(invocation -> {
            this.createLatch.countDown();
            this.createCount.incrementAndGet();

            // Capture the identity name and extract token from configuration
            this.capturedIdentityName = invocation.getArgument(0);
            IdentityConfiguration config = invocation.getArgument(1);
            TokenConfiguration tokenConfig = config.getComponent(TokenConfiguration.class).orElseThrow();
            this.capturedToken = tokenConfig.getToken();

            return null; // New API returns void
        }).when(this.identityService).createTemporaryIdentity(
                this.identityNameCaptor.capture(),
                this.identityConfigCaptor.capture(),
                this.durationCaptor.capture());

        doAnswer(invocation -> {
            this.deleteLatch.countDown();
            this.deleteCount.incrementAndGet();
            return true; // New API returns boolean
        }).when(this.identityService).deleteTemporaryIdentity(anyString());
    }

    private void givenTemporaryIdentityServiceProvidesMultipleTokens() throws Exception {
        this.createLatch = new CountDownLatch(2);
        this.deleteLatch = new CountDownLatch(1);
        this.createCount.set(0);
        this.deleteCount.set(0);

        doAnswer(invocation -> {
            this.createLatch.countDown();
            this.createCount.incrementAndGet();

            // Capture the identity name and extract token from configuration
            this.capturedIdentityName = invocation.getArgument(0);
            IdentityConfiguration config = invocation.getArgument(1);
            TokenConfiguration tokenConfig = config.getComponent(TokenConfiguration.class).orElseThrow();
            this.capturedToken = tokenConfig.getToken();

            return null; // New API returns void
        }).when(this.identityService).createTemporaryIdentity(
                this.identityNameCaptor.capture(),
                this.identityConfigCaptor.capture(),
                this.durationCaptor.capture());

        doAnswer(invocation -> {
            this.deleteLatch.countDown();
            this.deleteCount.incrementAndGet();
            return true;
        }).when(this.identityService).deleteTemporaryIdentity(anyString());
    }

    private void givenContainerOrchestratorStartsSuccessfully() throws Exception {
        doAnswer(invocation -> {
            this.startLatch.countDown();
            this.startCount.incrementAndGet();
            return CONTAINER_ID;
        }).when(this.containerOrchestrationService).startContainer(this.configurationCaptor.capture());
    }

    private void givenContainerOrchestratorStartsSuccessfullyWithIds(final String... containerIds) throws Exception {
        this.startLatch = new CountDownLatch(containerIds.length);
        this.startCount.set(0);
        final AtomicInteger index = new AtomicInteger(0);

        doAnswer(invocation -> {
            this.startLatch.countDown();
            this.startCount.incrementAndGet();
            final int current = Math.min(index.getAndIncrement(), containerIds.length - 1);
            return containerIds[current];
        }).when(this.containerOrchestrationService).startContainer(this.configurationCaptor.capture());
    }

    /*
     * WHEN
     */

    private void whenContainerInstanceIsActivated() {
        this.containerInstance.activate(this.properties);
    }

    private void whenContainerInstanceIsActivatedUntilCreated() throws InterruptedException {
        this.containerInstance.activate(this.properties);
        thenWaitForContainerState("Created");
    }

    private void whenContainerConfigurationIsUpdatedWithNewName() throws InterruptedException {
        final Map<String, Object> updated = new HashMap<>(this.properties);
        updated.put("container.name", UPDATED_CONTAINER_NAME);
        updated.put("kura.service.pid", UPDATED_CONTAINER_NAME);

        this.containerInstance.updated(updated);
        thenWaitForContainerState("Created");
    }

    private void whenContainerInstanceIsDisabled() {
        final Map<String, Object> disabled = new HashMap<>(this.properties);
        disabled.put("container.enabled", false);

        this.containerInstance.updated(disabled);
    }

    private void whenContainerInstanceIsDeactivated() {
        this.containerInstance.deactivate();
    }

    /*
     * THEN
     */

    private void thenTemporaryIdentityIsCreatedWithPermissions() throws Exception {
        assertTrue("Temporary identity was not created", this.createLatch.await(2, TimeUnit.SECONDS));

        final String expectedIdentityName = "container_" + CONTAINER_NAME.replace("-", "_");
        verify(this.identityService).createTemporaryIdentity(
                this.identityNameCaptor.capture(),
                this.identityConfigCaptor.capture(),
                this.durationCaptor.capture());

        // Verify identity name
        assertTrue("Identity name should match expected",
                this.identityNameCaptor.getValue().equals(expectedIdentityName));

        // Verify permissions from IdentityConfiguration
        IdentityConfiguration config = this.identityConfigCaptor.getValue();
        AssignedPermissions assignedPermissions = config.getComponent(AssignedPermissions.class).orElseThrow();
        Set<Permission> permissions = assignedPermissions.getPermissions();

        assertTrue("Expected rest.read permission", permissions.stream()
                .anyMatch(permission -> "rest.read".equals(permission.getName())));
        assertTrue("Expected rest.write permission", permissions.stream()
                .anyMatch(permission -> "rest.write".equals(permission.getName())));
    }

    private void thenStartContainerReceivesTokenEnvironment() throws Exception {
        assertTrue("Container start was not invoked", this.startLatch.await(2, TimeUnit.SECONDS));

        final ContainerConfiguration configuration = this.configurationCaptor.getValue();
        final List<String> envVars = configuration.getContainerEnvVars();

        assertTrue("Token env var missing", envVars.contains("KURA_IDENTITY_TOKEN=" + this.capturedToken));
        // Check that KURA_REST_BASE_URL is set (now dynamic, not hardcoded to localhost:8080)
        assertTrue("Base URL env var missing", envVars.stream()
                .anyMatch(envVar -> envVar.startsWith("KURA_REST_BASE_URL=")));
    }

    private void thenTemporaryIdentityIsDeleted() throws Exception {
        assertTrue("Temporary identity was not deleted", this.deleteLatch.await(2, TimeUnit.SECONDS));
        verify(this.identityService).deleteTemporaryIdentity(this.capturedIdentityName);
    }

    private void thenTemporaryIdentityIsDeletedOnlyOnce() throws Exception {
        assertTrue("Temporary identity deletion did not occur", this.deleteLatch.await(5, TimeUnit.SECONDS));
        verify(this.identityService, times(1)).deleteTemporaryIdentity(this.capturedIdentityName);
    }

    private void thenTemporaryIdentityIsRecreated() throws Exception {
        awaitCounterAtLeast(this.createCount, 2);
        awaitCounterAtLeast(this.deleteCount, 1);
        awaitCounterAtLeast(this.startCount, 2);

        assertTrue("Temporary identities were not created twice", this.createLatch.await(5, TimeUnit.SECONDS));
        assertTrue("Original temporary identity was not cleaned up", this.deleteLatch.await(5, TimeUnit.SECONDS));
        assertTrue("Container was not started twice", this.startLatch.await(5, TimeUnit.SECONDS));
    }

    private void thenLatestContainerStartReceivesRefreshedToken() {
        // Extract the latest token from captured IdentityConfiguration
        final List<IdentityConfiguration> identityConfigs = this.identityConfigCaptor.getAllValues();
        final IdentityConfiguration latestIdentityConfig = identityConfigs.get(identityConfigs.size() - 1);
        final TokenConfiguration latestTokenConfig = latestIdentityConfig.getComponent(TokenConfiguration.class)
                .orElseThrow();
        final String latestToken = latestTokenConfig.getToken();

        // Verify the latest container start received this token
        final List<ContainerConfiguration> configurations = this.configurationCaptor.getAllValues();
        final ContainerConfiguration latestConfiguration = configurations.get(configurations.size() - 1);
        final List<String> envVars = latestConfiguration.getContainerEnvVars();

        assertTrue("Latest start should include refreshed token",
                envVars.contains("KURA_IDENTITY_TOKEN=" + latestToken));
    }

    private void thenWaitForContainerState(String expectedState) throws InterruptedException {
        int attempts = 50;
        while (!expectedState.equals(this.containerInstance.getState()) && attempts-- > 0) {
            Thread.sleep(100);
        }
    }

    private void awaitCounterAtLeast(final AtomicInteger counter, final int expected) throws InterruptedException {
        int attempts = 50;
        while (counter.get() < expected && attempts-- > 0) {
            Thread.sleep(100);
        }
        assertTrue("Counter did not reach expected value", counter.get() >= expected);
    }
}
