/*******************************************************************************
 * Copyright (c) 2025 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.container.provider;

import static org.junit.Assert.assertTrue;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoMoreInteractions;
import static org.mockito.Mockito.when;

import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;

import org.eclipse.kura.configuration.ConfigurationService;
import org.eclipse.kura.container.orchestration.ContainerConfiguration;
import org.eclipse.kura.container.orchestration.ContainerOrchestrationService;
import org.eclipse.kura.identity.Permission;
import org.eclipse.kura.identity.TemporaryIdentityService;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.mockito.ArgumentCaptor;
import org.mockito.Mockito;

/**
 * Feature: Container instance identity integration with temporary identities enabled.
 */
public class ContainerIdentityIntegrationTest {

    private static final String CONTAINER_NAME = "kura-test-container";
    private static final String CONTAINER_IMAGE = "nginx";
    private static final String CONTAINER_TAG = "latest";
    private static final String PERMISSIONS = "rest.read,rest.write";
    private static final String TOKEN = "temp-token";
    private static final String CONTAINER_ID = "container-id";

    private ContainerInstance containerInstance;
    private ContainerOrchestrationService containerOrchestrationService;
    private TemporaryIdentityService temporaryIdentityService;
    private ConfigurationService configurationService;
    private Map<String, Object> properties;
    private CountDownLatch startLatch;
    private CountDownLatch createLatch;
    private CountDownLatch deleteLatch;
    private ArgumentCaptor<ContainerConfiguration> configurationCaptor;
    private ArgumentCaptor<Set<Permission>> permissionsCaptor;

    @Before
    public void setUp() {
        this.containerInstance = new ContainerInstance();
        this.containerOrchestrationService = Mockito.mock(ContainerOrchestrationService.class);
        this.temporaryIdentityService = Mockito.mock(TemporaryIdentityService.class);
        this.configurationService = Mockito.mock(ConfigurationService.class);
        this.properties = new HashMap<>();
        this.startLatch = new CountDownLatch(1);
        this.createLatch = new CountDownLatch(1);
        this.deleteLatch = new CountDownLatch(1);
        this.configurationCaptor = ArgumentCaptor.forClass(ContainerConfiguration.class);
        this.permissionsCaptor = ArgumentCaptor.forClass(Set.class);

        this.containerInstance.setContainerOrchestrationService(this.containerOrchestrationService);
        this.containerInstance.setTemporaryIdentityService(this.temporaryIdentityService);
        this.containerInstance.setConfigurationService(this.configurationService);

        when(this.containerOrchestrationService.listContainerDescriptors()).thenReturn(Collections.emptyList());
    }

    @After
    public void tearDown() {
        this.containerInstance.deactivate();
    }

    @Test
    public void createsTemporaryIdentityAndInjectsToken() throws Exception {
        givenIdentityIntegrationIsEnabled();
        givenTemporaryIdentityServiceProvidesToken();
        givenContainerOrchestratorStartsSuccessfully();

        whenContainerInstanceIsActivated();

        thenTemporaryIdentityIsCreatedWithPermissions();
        thenStartContainerReceivesTokenEnvironment();
    }

    @Test
    public void deletesTemporaryIdentityWhenContainerIsDisabled() throws Exception {
        givenIdentityIntegrationIsEnabled();
        givenTemporaryIdentityServiceProvidesToken();
        givenContainerOrchestratorStartsSuccessfully();

        whenContainerInstanceIsActivatedUntilCreated();
        whenContainerInstanceIsDisabled();

        thenTemporaryIdentityIsDeleted();
    }

    /*
     * GIVEN
     */

    private void givenIdentityIntegrationIsEnabled() {
        this.properties.put("container.enabled", true);
        this.properties.put("container.name", CONTAINER_NAME);
        this.properties.put("container.image", CONTAINER_IMAGE);
        this.properties.put("container.image.tag", CONTAINER_TAG);
        this.properties.put("container.identity.enabled", true);
        this.properties.put("container.permissions", PERMISSIONS);
    }

    private void givenTemporaryIdentityServiceProvidesToken() throws Exception {
        doAnswer(invocation -> {
            this.createLatch.countDown();
            return TOKEN;
        }).when(this.temporaryIdentityService).createTemporaryIdentity(anyString(), this.permissionsCaptor.capture());

        doAnswer(invocation -> {
            this.deleteLatch.countDown();
            return null;
        }).when(this.temporaryIdentityService).deleteTemporaryIdentity(TOKEN);
    }

    private void givenContainerOrchestratorStartsSuccessfully() throws Exception {
        doAnswer(invocation -> {
            this.startLatch.countDown();
            return CONTAINER_ID;
        }).when(this.containerOrchestrationService).startContainer(this.configurationCaptor.capture());
    }

    /*
     * WHEN
     */

    private void whenContainerInstanceIsActivated() {
        this.containerInstance.activate(this.properties);
    }

    private void whenContainerInstanceIsActivatedUntilCreated() throws InterruptedException {
        this.containerInstance.activate(this.properties);
        thenWaitForContainerState("Created");
    }

    private void whenContainerInstanceIsDisabled() {
        final Map<String, Object> disabled = new HashMap<>(this.properties);
        disabled.put("container.enabled", false);

        this.containerInstance.updated(disabled);
    }

    /*
     * THEN
     */

    private void thenTemporaryIdentityIsCreatedWithPermissions() throws Exception {
        assertTrue("Temporary identity was not created", this.createLatch.await(2, TimeUnit.SECONDS));

        final String expectedIdentityName = "container_" + CONTAINER_NAME.replace("-", "_");
        verify(this.temporaryIdentityService).createTemporaryIdentity(expectedIdentityName,
                this.permissionsCaptor.getValue());

        final Set<Permission> permissions = this.permissionsCaptor.getValue();
        assertTrue("Expected rest.read permission", permissions.stream()
                .anyMatch(permission -> "rest.read".equals(permission.getName())));
        assertTrue("Expected rest.write permission", permissions.stream()
                .anyMatch(permission -> "rest.write".equals(permission.getName())));
    }

    private void thenStartContainerReceivesTokenEnvironment() throws Exception {
        assertTrue("Container start was not invoked", this.startLatch.await(2, TimeUnit.SECONDS));

        final ContainerConfiguration configuration = this.configurationCaptor.getValue();
        final List<String> envVars = configuration.getContainerEnvVars();

        assertTrue("Token env var missing", envVars.contains("KURA_IDENTITY_TOKEN=" + TOKEN));
        assertTrue("Base URL env var missing",
                envVars.contains("KURA_REST_BASE_URL=http://localhost:8080/services/rest"));
    }

    private void thenTemporaryIdentityIsDeleted() throws Exception {
        assertTrue("Temporary identity was not deleted", this.deleteLatch.await(2, TimeUnit.SECONDS));
        verify(this.temporaryIdentityService).deleteTemporaryIdentity(TOKEN);
    }

    private void thenWaitForContainerState(String expectedState) throws InterruptedException {
        int attempts = 10;
        while (!expectedState.equals(this.containerInstance.getState()) && attempts-- > 0) {
            Thread.sleep(100);
        }
    }
}
