/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.container.provider;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotEquals;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import java.nio.charset.StandardCharsets;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.attribute.PosixFilePermission;
import java.util.EnumSet;
import java.util.Set;
import java.util.regex.Pattern;

import org.eclipse.kura.KuraException;
import org.junit.After;
import org.junit.Assume;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;

/**
 * Feature: storage of container authentication tokens in tmpfs-backed files.
 */
public class TokenFileManagerTest {

    private static final String TMPFS_BASE_PROPERTY = "kura.tmpfs.base";
    private static final char[] PASSWORD = "s3cret-Passw0rd!".toCharArray();

    @Rule
    public TemporaryFolder tmpfsBase = new TemporaryFolder();

    private String previousTmpfsBaseProperty;
    private TokenFileManager tokenFileManager;
    private Path tokenFile;
    private KuraException writeException;

    @Before
    public void setUp() {
        this.previousTmpfsBaseProperty = System.getProperty(TMPFS_BASE_PROPERTY);
        System.setProperty(TMPFS_BASE_PROPERTY, this.tmpfsBase.getRoot().getAbsolutePath());
        this.tokenFileManager = new TokenFileManager();
    }

    @After
    public void tearDown() {
        this.tokenFileManager.cleanup();

        if (this.previousTmpfsBaseProperty != null) {
            System.setProperty(TMPFS_BASE_PROPERTY, this.previousTmpfsBaseProperty);
        } else {
            System.clearProperty(TMPFS_BASE_PROPERTY);
        }
    }

    @Test
    public void writesTokenFileContainingOnlyThePassword() throws Exception {
        whenTokenIsWritten();

        thenTokenFileContent(new String(PASSWORD));
    }

    @Test
    public void createsUniqueUuidDirectoryPerToken() throws Exception {
        whenTokenIsWritten();
        final Path firstTokenFile = this.tokenFile;
        whenTokenIsWritten();

        thenPathMatchesTokenLayout(firstTokenFile);
        thenPathMatchesTokenLayout(this.tokenFile);
        assertNotEquals("Each token should get a unique directory", firstTokenFile.getParent(),
                this.tokenFile.getParent());
    }

    @Test
    public void setsOwnerReadOnlyPermissions() throws Exception {
        givenPosixFileSystem();

        whenTokenIsWritten();

        final Set<PosixFilePermission> permissions = Files.getPosixFilePermissions(this.tokenFile);
        assertEquals("Token file should be owner read-only", EnumSet.of(PosixFilePermission.OWNER_READ), permissions);
    }

    @Test
    public void failsFastWhenBaseDirectoryDoesNotExist() {
        final String missingBase = Paths.get(this.tmpfsBase.getRoot().getAbsolutePath(), "missing").toString();
        System.setProperty(TMPFS_BASE_PROPERTY, missingBase);

        whenTokenWriteIsAttempted();

        assertTrue("A KuraException should be thrown", this.writeException != null);
        assertTrue("The error message should contain the missing path",
                this.writeException.getMessage().contains(missingBase));
    }

    @Test
    public void cleanupDeletesTokenFileAndDirectory() throws Exception {
        whenTokenIsWritten();

        this.tokenFileManager.cleanup();

        assertFalse("Token file should be deleted", Files.exists(this.tokenFile));
        assertFalse("Token directory should be deleted", Files.exists(this.tokenFile.getParent()));
    }

    @Test
    public void cleanupIsIdempotentAndSafeBeforeAnyWrite() throws Exception {
        this.tokenFileManager.cleanup();

        whenTokenIsWritten();
        this.tokenFileManager.cleanup();
        this.tokenFileManager.cleanup();

        assertFalse("Token file should be deleted", Files.exists(this.tokenFile));
    }

    @Test
    public void writeTokenReplacesPreviousToken() throws Exception {
        whenTokenIsWritten();
        final Path firstTokenFile = this.tokenFile;

        whenTokenIsWritten();

        assertFalse("Previous token file should be deleted", Files.exists(firstTokenFile));
        assertFalse("Previous token directory should be deleted", Files.exists(firstTokenFile.getParent()));
        assertTrue("New token file should exist", Files.exists(this.tokenFile));
    }

    /*
     * Steps
     */

    private void givenPosixFileSystem() {
        Assume.assumeTrue("POSIX permissions are not supported on this platform",
                FileSystems.getDefault().supportedFileAttributeViews().contains("posix"));
    }

    private void whenTokenIsWritten() throws KuraException {
        this.tokenFile = this.tokenFileManager.writeToken(PASSWORD.clone());
    }

    private void whenTokenWriteIsAttempted() {
        try {
            whenTokenIsWritten();
            fail("writeToken should have thrown a KuraException");
        } catch (final KuraException e) {
            this.writeException = e;
        }
    }

    private void thenTokenFileContent(final String expectedContent) throws Exception {
        assertTrue("Token file should exist", Files.exists(this.tokenFile));
        assertEquals("Unexpected token file content", expectedContent,
                new String(Files.readAllBytes(this.tokenFile), StandardCharsets.UTF_8));
    }

    private void thenPathMatchesTokenLayout(final Path path) {
        final Path relative = Paths.get(this.tmpfsBase.getRoot().getAbsolutePath()).relativize(path);

        assertEquals("Unexpected path depth", 3, relative.getNameCount());
        assertEquals("Unexpected tokens directory", "kura-tokens", relative.getName(0).toString());
        assertTrue("Directory name should be a UUID", Pattern
                .matches("[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}", relative.getName(1).toString()));
        assertEquals("Unexpected token file name", "kura-token", relative.getName(2).toString());
    }
}
