/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.linux.clock;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;

import org.eclipse.kura.clock.ClockSyncState;
import org.eclipse.kura.core.linux.executor.LinuxExitStatus;
import org.eclipse.kura.core.testutil.TestUtil;
import org.eclipse.kura.crypto.CryptoService;
import org.eclipse.kura.executor.Command;
import org.eclipse.kura.executor.CommandExecutorService;
import org.eclipse.kura.executor.CommandStatus;
import org.junit.Test;

public class ChronyProviderSyncStateTest {

    private static final String[] CHRONYD_STATUS_COMMAND = { "systemctl", "is-active", "chrony" };
    private static final String[] TRACKING_COMMAND = { "chronyc", "-c", "tracking" };
    private static final String[] RESULT_COMMAND = { "systemctl", "show", "chrony", "-p", "Result" };

    private CommandExecutorService executorMock;
    private CryptoService cryptoServiceMock;
    private ChronyClockSyncProvider provider;
    private ClockSyncState reportedState;
    private RuntimeException thrownException;

    @Test
    public void trackingNormalReportsSynced() throws NoSuchFieldException {
        givenChronyProvider();
        givenChronydIsActive();
        givenTrackingOutputIs(trackingCsvWithLeapStatus("Normal"));

        whenSyncStateIsQueried();

        thenReportedStateIs(ClockSyncState.SYNCED);
    }

    @Test
    public void chronydInactiveReportsNotSynced() throws NoSuchFieldException {
        givenChronyProvider();
        givenChronydIsInactive();

        whenSyncStateIsQueried();

        thenReportedStateIs(ClockSyncState.NOT_SYNCED);
    }

    @Test
    public void trackingNotSynchronisedReportsNotSynced() throws NoSuchFieldException {
        givenChronyProvider();
        givenChronydIsActive();
        givenTrackingOutputIs(trackingCsvWithLeapStatus("Not synchronised"));

        whenSyncStateIsQueried();

        thenReportedStateIs(ClockSyncState.NOT_SYNCED);
    }

    @Test
    public void probeCommandFailureReportsUnknown() throws NoSuchFieldException {
        givenChronyProvider();
        givenChronydIsActive();
        givenTrackingCommandFails();

        whenSyncStateIsQueried();

        thenReportedStateIs(ClockSyncState.UNKNOWN);
    }

    @Test
    public void emptyProbeOutputReportsUnknown() throws NoSuchFieldException {
        givenChronyProvider();
        givenChronydIsActive();
        givenTrackingOutputIsEmpty();

        whenSyncStateIsQueried();

        thenReportedStateIs(ClockSyncState.UNKNOWN);
    }

    @Test
    public void unparseableProbeOutputReportsUnknown() throws NoSuchFieldException {
        givenChronyProvider();
        givenChronydIsActive();
        givenTrackingOutputIs("this is not a valid tracking line");

        whenSyncStateIsQueried();

        thenReportedStateIs(ClockSyncState.UNKNOWN);
    }

    @Test
    public void executorExceptionReportsUnknown() throws NoSuchFieldException {
        givenChronyProvider();
        givenChronydCheckThrowsRuntimeException();

        whenSyncStateIsQueried();

        thenReportedStateIs(ClockSyncState.UNKNOWN);
    }

    @Test
    public void emptyUnitStateOutputReportsUnknown() throws NoSuchFieldException {
        givenChronyProvider();
        givenChronydStateOutputIsEmpty();

        whenSyncStateIsQueried();

        thenReportedStateIs(ClockSyncState.UNKNOWN);
        thenFailureReasonIsNull();
    }

    @Test
    public void blankUnitStateOutputReportsUnknown() throws NoSuchFieldException {
        givenChronyProvider();
        givenChronydStateOutputIs("  \n");

        whenSyncStateIsQueried();

        thenReportedStateIs(ClockSyncState.UNKNOWN);
        thenFailureReasonIsNull();
    }

    @Test
    public void failedUnitReportsFailedWithResultReason() throws NoSuchFieldException {
        givenChronyProvider();
        givenChronydIsFailed();
        givenResultProbeOutputIs("Result=exit-code\n");

        whenSyncStateIsQueried();

        thenReportedStateIs(ClockSyncState.FAILED);
        thenFailureReasonIs("chrony service failed (Result: exit-code)");
    }

    @Test
    public void failingResultProbeReportsGenericFailureReason() throws NoSuchFieldException {
        givenChronyProvider();
        givenChronydIsFailed();
        givenResultProbeFails();

        whenSyncStateIsQueried();

        thenReportedStateIs(ClockSyncState.FAILED);
        thenFailureReasonIs("chrony service is in a failed state");
    }

    @Test
    public void emptyResultProbeOutputReportsGenericFailureReason() throws NoSuchFieldException {
        givenChronyProvider();
        givenChronydIsFailed();
        givenResultProbeOutputIs("");

        whenSyncStateIsQueried();

        thenReportedStateIs(ClockSyncState.FAILED);
        thenFailureReasonIs("chrony service is in a failed state");
    }

    @Test
    public void resultProbeWithoutResultPropertyReportsGenericFailureReason() throws NoSuchFieldException {
        givenChronyProvider();
        givenChronydIsFailed();
        givenResultProbeOutputIs("MainPID=1234\n");

        whenSyncStateIsQueried();

        thenReportedStateIs(ClockSyncState.FAILED);
        thenFailureReasonIs("chrony service is in a failed state");
    }

    @Test
    public void commaOnlyTrackingLineReportsUnknown() throws NoSuchFieldException {
        givenChronyProvider();
        givenChronydIsActive();
        givenTrackingOutputIs(",");

        whenSyncStateIsQueried();

        thenNoExceptionIsThrown();
        thenReportedStateIs(ClockSyncState.UNKNOWN);
    }

    @Test
    public void trackingLineWithoutCommaIsParsedAsWhole() throws NoSuchFieldException {
        givenChronyProvider();
        givenChronydIsActive();
        givenTrackingOutputIs("Normal");

        whenSyncStateIsQueried();

        thenNoExceptionIsThrown();
        thenReportedStateIs(ClockSyncState.SYNCED);
    }

    @Test
    public void inactiveUnitReportsNoFailureReason() throws NoSuchFieldException {
        givenChronyProvider();
        givenChronydIsInactive();

        whenSyncStateIsQueried();

        thenReportedStateIs(ClockSyncState.NOT_SYNCED);
        thenFailureReasonIsNull();
    }

    @Test
    public void syncedClockReportsNoFailureDetails() throws NoSuchFieldException {
        givenChronyProvider();
        givenChronydIsActive();
        givenTrackingOutputIs(trackingCsvWithLeapStatus("Normal"));

        whenSyncStateIsQueried();

        thenReportedStateIs(ClockSyncState.SYNCED);
        thenFailureReasonIsNull();
        thenRetryCountIsNull();
    }

    private void givenChronyProvider() throws NoSuchFieldException {
        this.executorMock = mock(CommandExecutorService.class);
        this.cryptoServiceMock = mock(CryptoService.class);
        this.provider = new ChronyClockSyncProvider(this.executorMock, this.cryptoServiceMock);
        TestUtil.setFieldValue(this.provider, "chronyServiceName", "chrony");
    }

    private void givenChronydIsActive() {
        CommandStatus status = new CommandStatus(new Command(CHRONYD_STATUS_COMMAND), new LinuxExitStatus(0));
        status.setOutputStream(outputStreamOf("active\n"));
        when(this.executorMock.execute(new Command(CHRONYD_STATUS_COMMAND))).thenReturn(status);
    }

    private void givenChronydIsInactive() {
        CommandStatus status = new CommandStatus(new Command(CHRONYD_STATUS_COMMAND), new LinuxExitStatus(3));
        status.setOutputStream(outputStreamOf("inactive\n"));
        when(this.executorMock.execute(new Command(CHRONYD_STATUS_COMMAND))).thenReturn(status);
    }

    private void givenChronydStateOutputIsEmpty() {
        CommandStatus status = new CommandStatus(new Command(CHRONYD_STATUS_COMMAND), new LinuxExitStatus(0));
        status.setOutputStream(new ByteArrayOutputStream());
        when(this.executorMock.execute(new Command(CHRONYD_STATUS_COMMAND))).thenReturn(status);
    }

    private void givenChronydStateOutputIs(String output) {
        CommandStatus status = new CommandStatus(new Command(CHRONYD_STATUS_COMMAND), new LinuxExitStatus(0));
        status.setOutputStream(outputStreamOf(output));
        when(this.executorMock.execute(new Command(CHRONYD_STATUS_COMMAND))).thenReturn(status);
    }

    private void givenChronydIsFailed() {
        CommandStatus status = new CommandStatus(new Command(CHRONYD_STATUS_COMMAND), new LinuxExitStatus(3));
        status.setOutputStream(outputStreamOf("failed\n"));
        when(this.executorMock.execute(new Command(CHRONYD_STATUS_COMMAND))).thenReturn(status);
    }

    private void givenResultProbeOutputIs(String output) {
        CommandStatus status = new CommandStatus(new Command(RESULT_COMMAND), new LinuxExitStatus(0));
        status.setOutputStream(outputStreamOf(output));
        when(this.executorMock.execute(new Command(RESULT_COMMAND))).thenReturn(status);
    }

    private void givenResultProbeFails() {
        CommandStatus status = new CommandStatus(new Command(RESULT_COMMAND), new LinuxExitStatus(1));
        when(this.executorMock.execute(new Command(RESULT_COMMAND))).thenReturn(status);
    }

    private void givenChronydCheckThrowsRuntimeException() {
        when(this.executorMock.execute(new Command(CHRONYD_STATUS_COMMAND)))
                .thenThrow(new RuntimeException("simulated executor failure"));
    }

    private void givenTrackingOutputIs(String output) {
        CommandStatus status = new CommandStatus(new Command(TRACKING_COMMAND), new LinuxExitStatus(0));
        status.setOutputStream(outputStreamOf(output));
        when(this.executorMock.execute(new Command(TRACKING_COMMAND))).thenReturn(status);
    }

    private void givenTrackingOutputIsEmpty() {
        CommandStatus status = new CommandStatus(new Command(TRACKING_COMMAND), new LinuxExitStatus(0));
        status.setOutputStream(new ByteArrayOutputStream());
        when(this.executorMock.execute(new Command(TRACKING_COMMAND))).thenReturn(status);
    }

    private void givenTrackingCommandFails() {
        CommandStatus status = new CommandStatus(new Command(TRACKING_COMMAND), new LinuxExitStatus(1));
        when(this.executorMock.execute(new Command(TRACKING_COMMAND))).thenReturn(status);
    }

    private void whenSyncStateIsQueried() {
        try {
            this.reportedState = this.provider.getSyncState();
        } catch (RuntimeException e) {
            this.thrownException = e;
        }
    }

    private void thenReportedStateIs(ClockSyncState expected) {
        assertEquals(expected, this.reportedState);
    }

    private void thenFailureReasonIs(String expected) {
        assertEquals(expected, this.provider.getFailureReason());
    }

    private void thenFailureReasonIsNull() {
        assertNull(this.provider.getFailureReason());
    }

    private void thenRetryCountIsNull() {
        assertNull(this.provider.getRetryCount());
    }

    private void thenNoExceptionIsThrown() {
        assertNull(this.thrownException);
    }

    private static ByteArrayOutputStream outputStreamOf(String content) {
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        try {
            outputStream.write(content.getBytes(StandardCharsets.UTF_8));
        } catch (IOException e) {
            throw new IllegalStateException(e);
        }
        return outputStream;
    }

    private static String trackingCsvWithLeapStatus(String leapStatus) {
        return "A29FC87B,192.168.1.1,3,1755436564.123456,0.000012,0.000034,0.000056,0.001,0.002,0.003,0.004,0.005,"
                + "64.2," + leapStatus;
    }
}
