/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.linux.clock;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;

import org.eclipse.kura.clock.ClockSyncState;
import org.eclipse.kura.core.linux.executor.LinuxExitStatus;
import org.eclipse.kura.core.testutil.TestUtil;
import org.eclipse.kura.crypto.CryptoService;
import org.eclipse.kura.executor.Command;
import org.eclipse.kura.executor.CommandExecutorService;
import org.eclipse.kura.executor.CommandStatus;
import org.junit.Test;

public class ChronyProviderSyncStateTest {

    private static final String[] CHRONYD_STATUS_COMMAND = { "systemctl", "is-active", "chrony" };
    private static final String[] TRACKING_COMMAND = { "chronyc", "-c", "tracking" };

    private CommandExecutorService executorMock;
    private CryptoService cryptoServiceMock;
    private ChronyClockSyncProvider provider;
    private ClockSyncState reportedState;

    @Test
    public void trackingNormalReportsSynced() throws NoSuchFieldException {
        givenChronyProvider();
        givenChronydIsActive();
        givenTrackingOutputIs(trackingCsvWithLeapStatus("Normal"));

        whenSyncStateIsQueried();

        thenReportedStateIs(ClockSyncState.SYNCED);
    }

    @Test
    public void chronydInactiveReportsNotSynced() throws NoSuchFieldException {
        givenChronyProvider();
        givenChronydIsInactive();

        whenSyncStateIsQueried();

        thenReportedStateIs(ClockSyncState.NOT_SYNCED);
    }

    @Test
    public void trackingNotSynchronisedReportsNotSynced() throws NoSuchFieldException {
        givenChronyProvider();
        givenChronydIsActive();
        givenTrackingOutputIs(trackingCsvWithLeapStatus("Not synchronised"));

        whenSyncStateIsQueried();

        thenReportedStateIs(ClockSyncState.NOT_SYNCED);
    }

    @Test
    public void probeCommandFailureReportsUnknown() throws NoSuchFieldException {
        givenChronyProvider();
        givenChronydIsActive();
        givenTrackingCommandFails();

        whenSyncStateIsQueried();

        thenReportedStateIs(ClockSyncState.UNKNOWN);
    }

    @Test
    public void emptyProbeOutputReportsUnknown() throws NoSuchFieldException {
        givenChronyProvider();
        givenChronydIsActive();
        givenTrackingOutputIsEmpty();

        whenSyncStateIsQueried();

        thenReportedStateIs(ClockSyncState.UNKNOWN);
    }

    @Test
    public void unparseableProbeOutputReportsUnknown() throws NoSuchFieldException {
        givenChronyProvider();
        givenChronydIsActive();
        givenTrackingOutputIs("this is not a valid tracking line");

        whenSyncStateIsQueried();

        thenReportedStateIs(ClockSyncState.UNKNOWN);
    }

    @Test
    public void executorExceptionReportsUnknown() throws NoSuchFieldException {
        givenChronyProvider();
        givenChronydCheckThrowsRuntimeException();

        whenSyncStateIsQueried();

        thenReportedStateIs(ClockSyncState.UNKNOWN);
    }

    private void givenChronyProvider() throws NoSuchFieldException {
        this.executorMock = mock(CommandExecutorService.class);
        this.cryptoServiceMock = mock(CryptoService.class);
        this.provider = new ChronyClockSyncProvider(this.executorMock, this.cryptoServiceMock);
        TestUtil.setFieldValue(this.provider, "chronyServiceName", "chrony");
    }

    private void givenChronydIsActive() {
        CommandStatus status = new CommandStatus(new Command(CHRONYD_STATUS_COMMAND), new LinuxExitStatus(0));
        when(this.executorMock.execute(new Command(CHRONYD_STATUS_COMMAND))).thenReturn(status);
    }

    private void givenChronydIsInactive() {
        CommandStatus status = new CommandStatus(new Command(CHRONYD_STATUS_COMMAND), new LinuxExitStatus(3));
        when(this.executorMock.execute(new Command(CHRONYD_STATUS_COMMAND))).thenReturn(status);
    }

    private void givenChronydCheckThrowsRuntimeException() {
        when(this.executorMock.execute(new Command(CHRONYD_STATUS_COMMAND)))
                .thenThrow(new RuntimeException("simulated executor failure"));
    }

    private void givenTrackingOutputIs(String output) {
        CommandStatus status = new CommandStatus(new Command(TRACKING_COMMAND), new LinuxExitStatus(0));
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        try {
            outputStream.write(output.getBytes(StandardCharsets.UTF_8));
        } catch (IOException e) {
            throw new IllegalStateException(e);
        }
        status.setOutputStream(outputStream);
        when(this.executorMock.execute(new Command(TRACKING_COMMAND))).thenReturn(status);
    }

    private void givenTrackingOutputIsEmpty() {
        CommandStatus status = new CommandStatus(new Command(TRACKING_COMMAND), new LinuxExitStatus(0));
        status.setOutputStream(new ByteArrayOutputStream());
        when(this.executorMock.execute(new Command(TRACKING_COMMAND))).thenReturn(status);
    }

    private void givenTrackingCommandFails() {
        CommandStatus status = new CommandStatus(new Command(TRACKING_COMMAND), new LinuxExitStatus(1));
        when(this.executorMock.execute(new Command(TRACKING_COMMAND))).thenReturn(status);
    }

    private void whenSyncStateIsQueried() {
        this.reportedState = this.provider.getSyncState();
    }

    private void thenReportedStateIs(ClockSyncState expected) {
        assertEquals(expected, this.reportedState);
    }

    private static String trackingCsvWithLeapStatus(String leapStatus) {
        return "A29FC87B,192.168.1.1,3,1755436564.123456,0.000012,0.000034,0.000056,0.001,0.002,0.003,0.004,0.005,"
                + "64.2," + leapStatus;
    }
}
