/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.linux.clock;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.KuraException;
import org.eclipse.kura.clock.ClockService;
import org.eclipse.kura.clock.ClockSyncState;
import org.eclipse.kura.clock.ClockSyncStatus;
import org.eclipse.kura.core.testutil.TestUtil;
import org.junit.Test;

public class ClockServiceSyncStatusTest {

    private ClockService serviceUnderTest;
    private ClockSyncStatus status;
    private KuraException thrownException;

    @Test
    public void disabledServiceThrowsServiceUnavailable() throws NoSuchFieldException {
        givenFreshClockServiceImpl();

        whenGetSyncStatusIsInvoked();

        thenExceptionHasErrorCode(KuraErrorCode.SERVICE_UNAVAILABLE);
    }

    @Test
    public void statusComposesProviderStateLastSyncAndConfiguredProvider() throws NoSuchFieldException {
        Date lastSync = new Date(1000L);
        givenClockServiceImplWithProvider(ClockSyncState.UNKNOWN, lastSync, "java-ntp");

        whenGetSyncStatusIsInvoked();

        thenStatusStateIs(ClockSyncState.UNKNOWN);
        thenStatusLastSyncIs(lastSync);
        thenStatusSyncProviderIs("java-ntp");
    }

    @Test
    public void statusComposesProviderReportedFailureReasonAndRetryCount() throws NoSuchFieldException {
        givenClockServiceImplWithProvider(ClockSyncState.FAILED, new Date(3000L), "chrony-advanced",
                "chrony service is in failed state", 5);

        whenGetSyncStatusIsInvoked();

        thenStatusStateIs(ClockSyncState.FAILED);
        thenStatusFailureReasonIs("chrony service is in failed state");
        thenStatusRetryCountIs(5);
    }

    @Test
    public void statusReportsNoFailureReasonAndNoRetryCountWhenProviderReportsNeither() throws NoSuchFieldException {
        givenClockServiceImplWithProvider(ClockSyncState.SYNCED, new Date(4000L), "java-ntp", null, null);

        whenGetSyncStatusIsInvoked();

        thenStatusStateIs(ClockSyncState.SYNCED);
        thenStatusFailureReasonIs(null);
        thenStatusRetryCountIs(null);
    }

    @Test
    public void defaultMethodDerivesNotSyncedFromNullLastSync() throws NoSuchFieldException {
        givenClockServiceWithLastSync(null);

        whenGetSyncStatusIsInvoked();

        thenStatusStateIs(ClockSyncState.NOT_SYNCED);
        thenStatusLastSyncIs(null);
        thenStatusSyncProviderIs(null);
        thenStatusFailureReasonIs(null);
        thenStatusRetryCountIs(null);
    }

    @Test
    public void defaultMethodDerivesSyncedFromLastSync() throws NoSuchFieldException {
        Date lastSync = new Date(2000L);
        givenClockServiceWithLastSync(lastSync);

        whenGetSyncStatusIsInvoked();

        thenStatusStateIs(ClockSyncState.SYNCED);
        thenStatusLastSyncIs(lastSync);
        thenStatusSyncProviderIs(null);
        thenStatusFailureReasonIs(null);
        thenStatusRetryCountIs(null);
    }

    private void givenFreshClockServiceImpl() {
        this.serviceUnderTest = new ClockServiceImpl();
    }

    private void givenClockServiceImplWithProvider(ClockSyncState providerState, Date lastSync,
            String configuredProvider) throws NoSuchFieldException {
        givenClockServiceImplWithProvider(providerState, lastSync, configuredProvider, null, null);
    }

    private void givenClockServiceImplWithProvider(ClockSyncState providerState, Date lastSync,
            String configuredProvider, String failureReason, Integer retryCount) throws NoSuchFieldException {
        ClockServiceImpl clockServiceImpl = new ClockServiceImpl();

        ClockSyncProvider providerMock = mock(ClockSyncProvider.class);
        when(providerMock.getSyncState()).thenReturn(providerState);
        when(providerMock.getLastSync()).thenReturn(lastSync);
        when(providerMock.getFailureReason()).thenReturn(failureReason);
        when(providerMock.getRetryCount()).thenReturn(retryCount);

        Map<String, Object> properties = new HashMap<>();
        properties.put("clock.provider", configuredProvider);
        ClockServiceConfig config = new ClockServiceConfig(properties);

        TestUtil.setFieldValue(clockServiceImpl, "provider", providerMock);
        TestUtil.setFieldValue(clockServiceImpl, "clockServiceConfig", config);

        this.serviceUnderTest = clockServiceImpl;
    }

    private void givenClockServiceWithLastSync(Date lastSync) {
        this.serviceUnderTest = new ClockService() {

            @Override
            public Date getLastSync() throws KuraException {
                return lastSync;
            }
        };
    }

    private void whenGetSyncStatusIsInvoked() {
        try {
            this.status = this.serviceUnderTest.getSyncStatus();
        } catch (KuraException e) {
            this.thrownException = e;
        }
    }

    private void thenExceptionHasErrorCode(KuraErrorCode expected) {
        assertNotNull("expected a KuraException to be thrown", this.thrownException);
        assertEquals(expected, this.thrownException.getCode());
    }

    private void thenStatusStateIs(ClockSyncState expected) {
        assertNotNull("expected a status to be returned", this.status);
        assertEquals(expected, this.status.getState());
    }

    private void thenStatusLastSyncIs(Date expected) {
        if (expected == null) {
            assertNull(this.status.getLastSync());
        } else {
            assertEquals(expected, this.status.getLastSync());
        }
    }

    private void thenStatusSyncProviderIs(String expected) {
        if (expected == null) {
            assertNull(this.status.getSyncProvider());
        } else {
            assertEquals(expected, this.status.getSyncProvider());
        }
    }

    private void thenStatusFailureReasonIs(String expected) {
        if (expected == null) {
            assertNull(this.status.getFailureReason());
        } else {
            assertEquals(expected, this.status.getFailureReason());
        }
    }

    private void thenStatusRetryCountIs(Integer expected) {
        if (expected == null) {
            assertNull(this.status.getRetryCount());
        } else {
            assertEquals(expected, this.status.getRetryCount());
        }
    }
}
