/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.linux.clock;

import static org.junit.Assert.assertEquals;

import java.util.HashMap;
import java.util.Map;

import org.junit.Test;

public class ClockServiceConfigRetryIntervalTest {

    private final Map<String, Object> properties = new HashMap<>();
    private ClockServiceConfig config;

    @Test
    public void retryIntervalIsReadFromItsOwnKey() {
        givenProperty("clock.ntp.retry.interval", 30);

        whenConfigIsCreated();

        thenRetryIntervalIs(30);
    }

    @Test
    public void retryIntervalIsNotDrivenByMaxRetry() {
        givenProperty("clock.ntp.max-retry", 99);

        whenConfigIsCreated();

        thenRetryIntervalIs(5);
        thenMaxRetriesIs(99);
    }

    @Test
    public void retryIntervalAndMaxRetryAreReadIndependently() {
        givenProperty("clock.ntp.retry.interval", 30);
        givenProperty("clock.ntp.max-retry", 99);

        whenConfigIsCreated();

        thenRetryIntervalIs(30);
        thenMaxRetriesIs(99);
    }

    @Test
    public void unconfiguredRetryIntervalFallsBackToItsDefault() {
        whenConfigIsCreated();

        thenRetryIntervalIs(5);
        thenMaxRetriesIs(0);
    }

    private void givenProperty(String key, Object value) {
        this.properties.put(key, value);
    }

    private void whenConfigIsCreated() {
        this.config = new ClockServiceConfig(this.properties);
    }

    private void thenRetryIntervalIs(int expected) {
        assertEquals(expected, this.config.getNtpRetryInterval());
    }

    private void thenMaxRetriesIs(int expected) {
        assertEquals(expected, this.config.getNtpMaxRetries());
    }

}
