/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.linux.clock;

import static org.junit.Assert.assertEquals;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;

import java.util.ArrayDeque;
import java.util.Deque;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.KuraException;
import org.eclipse.kura.clock.ClockSyncState;
import org.eclipse.kura.core.testutil.TestUtil;
import org.junit.Test;
import org.mockito.ArgumentCaptor;

public class NtpProviderSyncStateTest {

    private ScheduledExecutorService scheduler;
    private ScriptedNtpProvider provider;
    private Runnable scheduledTick;

    @Test
    public void freshProviderReportsUnknown() throws Exception {
        givenNtpProviderConfiguredWithRefreshInterval(3600, 0);

        thenSyncStateIs(ClockSyncState.UNKNOWN);
    }

    @Test
    public void successfulSyncAttemptReportsSynced() throws Exception {
        givenNtpProviderConfiguredWithRefreshInterval(3600, 0);
        givenNextSyncAttemptSucceeds();

        whenScheduledSyncAttemptRuns();

        thenSyncStateIs(ClockSyncState.SYNCED);
    }

    @Test
    public void failedSyncAttemptReportsNotSynced() throws Exception {
        givenNtpProviderConfiguredWithRefreshInterval(3600, 0);
        givenNextSyncAttemptFails();

        whenScheduledSyncAttemptRuns();

        thenSyncStateIs(ClockSyncState.NOT_SYNCED);
    }

    @Test
    public void syncExceptionReportsNotSynced() throws Exception {
        givenNtpProviderConfiguredWithRefreshInterval(3600, 0);
        givenNextSyncAttemptThrows();

        whenScheduledSyncAttemptRuns();

        thenSyncStateIs(ClockSyncState.NOT_SYNCED);
    }

    @Test
    public void retryExhaustionReportsNotSynced() throws Exception {
        givenNtpProviderConfiguredWithRefreshInterval(3600, 2);
        givenNextSyncAttemptFails();
        givenNextSyncAttemptFails();

        whenScheduledSyncAttemptRuns();
        whenScheduledSyncAttemptRuns();

        thenSyncStateIs(ClockSyncState.NOT_SYNCED);
        thenSchedulingFlagIs(true);
    }

    @Test
    public void refreshWindowFlipDoesNotFlapReport() throws Exception {
        givenNtpProviderConfiguredWithRefreshInterval(1, 0);
        givenNextSyncAttemptSucceeds();

        whenScheduledSyncAttemptRuns();

        thenSyncStateIs(ClockSyncState.SYNCED);
        thenSchedulingFlagIs(true);

        whenScheduledSyncAttemptRuns();

        thenSchedulingFlagIs(false);
        thenSyncStateIs(ClockSyncState.SYNCED);
    }

    private void givenNtpProviderConfiguredWithRefreshInterval(int refreshIntervalSeconds, int maxRetry)
            throws KuraException {
        Map<String, Object> properties = new HashMap<>();
        properties.put("clock.ntp.refresh-interval", refreshIntervalSeconds);
        properties.put("clock.ntp.max-retry", maxRetry);
        ClockServiceConfig config = new ClockServiceConfig(properties);

        this.scheduler = mock(ScheduledExecutorService.class);
        this.provider = new ScriptedNtpProvider();
        this.provider.init(config, this.scheduler, null);
        this.provider.start();

        ArgumentCaptor<Runnable> tickCaptor = ArgumentCaptor.forClass(Runnable.class);
        verify(this.scheduler).scheduleAtFixedRate(tickCaptor.capture(), eq(0L), anyLong(), eq(TimeUnit.SECONDS));
        this.scheduledTick = tickCaptor.getValue();
    }

    private void givenNextSyncAttemptSucceeds() {
        this.provider.enqueueResult(true);
    }

    private void givenNextSyncAttemptFails() {
        this.provider.enqueueResult(false);
    }

    private void givenNextSyncAttemptThrows() {
        this.provider.enqueueException(new KuraException(KuraErrorCode.CONNECTION_FAILED, "simulated sync failure"));
    }

    private void whenScheduledSyncAttemptRuns() {
        this.scheduledTick.run();
    }

    private void thenSyncStateIs(ClockSyncState expected) {
        assertEquals(expected, this.provider.getSyncState());
    }

    private void thenSchedulingFlagIs(boolean expected) throws NoSuchFieldException {
        assertEquals(expected, TestUtil.getFieldValue(this.provider, "isSynced"));
    }

    private static final class ScriptedNtpProvider extends AbstractNtpClockSyncProvider {

        private final Deque<Object> scriptedOutcomes = new ArrayDeque<>();

        void enqueueResult(boolean result) {
            this.scriptedOutcomes.addLast(result);
        }

        void enqueueException(KuraException exception) {
            this.scriptedOutcomes.addLast(exception);
        }

        @Override
        protected boolean syncClock() throws KuraException {
            Object outcome = this.scriptedOutcomes.pollFirst();
            if (outcome instanceof KuraException) {
                throw (KuraException) outcome;
            }
            return Boolean.TRUE.equals(outcome);
        }
    }
}
