/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.openapi;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.ArgumentMatchers.isNull;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.net.CookieManager;
import java.net.CookiePolicy;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.util.Base64;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Properties;
import java.util.Set;

import org.eclipse.jetty.ee10.servlet.ServletContextHandler;
import org.eclipse.jetty.ee10.servlet.ServletHolder;
import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.server.ServerConnector;
import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.KuraException;
import org.eclipse.kura.configuration.ConfigurationService;
import org.eclipse.kura.configuration.metatype.OCDService;
import org.eclipse.kura.crypto.CryptoService;
import org.eclipse.kura.identity.IdentityService;
import org.eclipse.kura.identity.LoginBannerService;
import org.eclipse.kura.identity.PasswordStrengthRequirements;
import org.eclipse.kura.identity.PasswordStrengthVerificationService;
import org.eclipse.kura.identity.Permission;
import org.eclipse.kura.internal.rest.auth.BasicAuthenticationProvider;
import org.eclipse.kura.internal.rest.auth.RestIdentityHelper;
import org.eclipse.kura.internal.rest.auth.RestSessionHelper;
import org.eclipse.kura.internal.rest.auth.SessionAuthProvider;
import org.eclipse.kura.internal.rest.auth.SessionRestService;
import org.eclipse.kura.internal.rest.configuration.ConfigurationRestService;
import org.eclipse.kura.internal.rest.provider.AuditFilter;
import org.eclipse.kura.internal.rest.provider.AuthenticationFilter;
import org.eclipse.kura.internal.rest.provider.AuthorizationFilter;
import org.eclipse.kura.internal.rest.provider.GsonSerializer;
import org.eclipse.kura.internal.rest.provider.RestExceptionMapper;
import org.eclipse.kura.internal.rest.provider.RestServiceOptions;
import org.eclipse.kura.rest.system.SystemRestService;
import org.eclipse.kura.system.InternetConnectionStatus;
import org.eclipse.kura.system.SystemService;
import org.glassfish.jersey.server.ResourceConfig;
import org.glassfish.jersey.servlet.ServletContainer;
import org.junit.After;
import org.osgi.framework.BundleContext;
import org.osgi.framework.ServiceRegistration;
import org.osgi.service.cm.ConfigurationAdmin;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.networknt.schema.JsonSchemaFactory;
import com.networknt.schema.SpecVersion;
import com.networknt.schema.ValidationMessage;
import com.networknt.schema.oas.OpenApi30;

import io.swagger.v3.core.util.Json;
import jakarta.ws.rs.container.ContainerResponseFilter;

public abstract class AbstractHttpContractTest {

    protected final SystemService system = mock(SystemService.class);
    protected final ConfigurationService configurations = mock(ConfigurationService.class);
    protected final OCDService definitions = mock(OCDService.class);
    protected final RestIdentityHelper identities = mock(RestIdentityHelper.class);
    protected final Map<String, Object> options = new HashMap<>();
    protected Set<String> permissions = Set.of("rest.system", "rest.configuration");
    protected HttpResponse<String> response;
    protected String token;

    private final IdentityService identityService = mock(IdentityService.class);
    private final AuthenticationFilter authentication = new AuthenticationFilter();
    private Server server;
    private HttpClient client;
    private URI base;
    private JsonNode document;
    private String requestPath;
    private String requestMethod;
    private String authorization;
    private final List<Exchange> exchanges = new ArrayList<>();

    @After
    public void tearDown() throws Exception {
        if (this.client != null) {
            this.client.close();
        }
        if (this.server != null) {
            this.server.stop();
        }
        this.authentication.close();
    }

    protected void givenServer() throws Exception {
        this.document = Json.mapper().readTree(Files.readString(
                Path.of(System.getProperty("openapi.directory"), "openapi.json")));
        when(this.system.getDeviceName()).thenReturn("contract-gateway");
        when(this.system.getInternetConnectionStatus()).thenReturn(InternetConnectionStatus.FULL);
        final Properties properties = new Properties();
        properties.setProperty("test.property", "test-value");
        when(this.system.getProperties()).thenReturn(properties);
        when(this.configurations.getSnapshots()).thenReturn(Set.of(7L));
        when(this.configurations.snapshot()).thenReturn(7L);
        when(this.configurations.rollback()).thenReturn(7L);

        doAnswer(invocation -> {
            final String username = invocation.getArgument(0);
            final char[] password = invocation.getArgument(1);
            if (!"user".equals(username) || !"password".equals(new String(password))) {
                throw new KuraException(KuraErrorCode.SECURITY_EXCEPTION);
            }
            return null;
        }).when(this.identities).checkPassword(anyString(), any(char[].class));
        when(this.identities.getPasswordHash(anyString())).thenReturn(Optional.empty());
        when(this.identities.getAssignedPermissions(anyString())).thenReturn(Set.of(new Permission("rest.system")));
        doAnswer(invocation -> {
            final Permission permission = invocation.getArgument(1);
            if (!this.permissions.contains(permission.getName())) {
                throw new KuraException(KuraErrorCode.SECURITY_EXCEPTION);
            }
            return null;
        }).when(this.identityService).checkPermission(anyString(), any(Permission.class));

        final SystemRestService systemResource = new SystemRestService();
        systemResource.bindSystemService(this.system);
        final ConfigurationRestService configurationResource = new ConfigurationRestService();
        configurationResource.setConfigurationService(this.configurations);
        configurationResource.setOCDService(this.definitions);
        configurationResource.setCryptoService(mock(CryptoService.class));
        final RestSessionHelper sessions = new RestSessionHelper(this.identities);
        final LoginBannerService banners = mock(LoginBannerService.class);
        final PasswordStrengthVerificationService passwords = mock(PasswordStrengthVerificationService.class);
        when(passwords.getPasswordStrengthRequirements()).thenReturn(mock(PasswordStrengthRequirements.class));
        final SessionRestService sessionResource = new SessionRestService(this.identities, sessions,
                mock(ConfigurationAdmin.class), passwords, banners);
        final RestServiceOptions restOptions = new RestServiceOptions(this.options);
        sessionResource.setOptions(restOptions);
        final SessionAuthProvider sessionAuth = new SessionAuthProvider(sessions,
                Set.of("/session/v1/changePassword", "/session/v1/xsrfToken"), Set.of("/session/v1/xsrfToken"));
        sessionAuth.setOptions(restOptions);

        final ResourceConfig application = new ResourceConfig();
        application.property("jersey.config.server.response.setStatusOverSendError", true);
        final BundleContext bundle = mock(BundleContext.class);
        when(bundle.registerService(eq(ContainerResponseFilter.class), any(ContainerResponseFilter.class), isNull()))
                .thenAnswer(invocation -> {
                    application.register(invocation.getArgument(1, ContainerResponseFilter.class));
                    return mock(ServiceRegistration.class);
                });
        this.authentication.setIdentityService(this.identityService);
        this.authentication.registerAuthenticationProvider(new BasicAuthenticationProvider(bundle, this.identities));
        if (restOptions.isSessionManagementEnabled()) {
            this.authentication.registerAuthenticationProvider(sessionAuth);
        }
        application.register(systemResource);
        application.register(configurationResource);
        application.register(sessionResource);
        registerAdditionalResources(application);
        application.register(this.authentication);
        application.register(AuthorizationFilter.class);
        application.register(AuditFilter.class);
        application.register(GsonSerializer.class);
        application.register(RestExceptionMapper.class);

        this.server = new Server();
        final ServerConnector connector = new ServerConnector(this.server);
        connector.setHost("127.0.0.1");
        connector.setPort(0);
        this.server.addConnector(connector);
        final ServletContextHandler context = new ServletContextHandler(ServletContextHandler.SESSIONS);
        context.setContextPath("/services");
        context.addServlet(new ServletHolder(new ServletContainer(application)), "/*");
        this.server.setHandler(context);
        this.server.start();
        this.base = URI.create("http://127.0.0.1:" + connector.getLocalPort() + "/services");
        this.client = HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(5))
                .cookieHandler(new CookieManager(null, CookiePolicy.ACCEPT_ALL)).build();
        this.authorization = "Basic " + Base64.getEncoder()
                .encodeToString("user:password".getBytes(StandardCharsets.UTF_8));
    }

    protected void registerAdditionalResources(ResourceConfig application) throws Exception {
    }

    protected void givenNoBasicAuthentication() {
        this.authorization = null;
    }

    protected void givenInvalidBasicCredentials() {
        this.authorization = "Basic aW52YWxpZDpjcmVkZW50aWFscw==";
    }

    protected void givenSession() throws Exception {
        givenNoBasicAuthentication();
        whenRequest("POST", "/session/v1/login/password", "{\"username\":\"user\",\"password\":\"password\"}");

        thenResponseMatchesContract(200);
        assertTrue(this.response.headers().firstValue("Set-Cookie").isPresent());
    }

    protected void givenXsrfToken() throws Exception {
        whenRequest("GET", "/session/v1/xsrfToken", null);

        thenResponseMatchesContract(200);
        this.token = Json.mapper().readTree(this.response.body()).path("xsrfToken").asText();
        assertFalse(this.token.isBlank());
    }

    protected void whenTokenIsRefreshed() throws Exception {
        whenRequest("GET", "/session/v1/xsrfToken", null);
        this.token = Json.mapper().readTree(this.response.body()).path("xsrfToken").asText();
    }

    protected void whenRequest(String method, String path, String body) throws Exception {
        whenRequest(method, path, body, "application/json");
    }

    protected void whenRequest(String method, String path, String body, String contentType) throws Exception {
        this.requestPath = path.split("\\?", 2)[0];
        this.requestMethod = method.toLowerCase(java.util.Locale.ROOT);
        final HttpRequest.Builder request = HttpRequest.newBuilder(URI.create(this.base + path))
                .timeout(Duration.ofSeconds(5)).header("Accept", "application/json");
        if (this.authorization != null) {
            request.header("Authorization", this.authorization);
        }
        if (this.token != null) {
            request.header("X-XSRF-Token", this.token);
        }
        if (body != null) {
            request.header("Content-Type", contentType);
        }
        request.method(method, body == null ? HttpRequest.BodyPublishers.noBody() : HttpRequest.BodyPublishers.ofString(body));
        this.response = this.client.send(request.build(), HttpResponse.BodyHandlers.ofString());
        this.exchanges.add(new Exchange(this.requestPath, this.requestMethod, this.response));
    }

    protected void thenLastResponsesMatchContract(int... statuses) throws Exception {
        final int start = this.exchanges.size() - statuses.length;
        for (int i = 0; i < statuses.length; i++) {
            final Exchange exchange = this.exchanges.get(start + i);
            this.requestPath = exchange.path();
            this.requestMethod = exchange.method();
            this.response = exchange.response();
            thenResponseMatchesContract(statuses[i]);
        }
    }

    private record Exchange(String path, String method, HttpResponse<String> response) {
    }

    protected void thenResponseMatchesContract(int status) throws Exception {
        assertEquals(this.response.body(), status, this.response.statusCode());
        JsonNode contract = this.document.path("paths").path(this.requestPath).path(this.requestMethod)
                .path("responses").path(Integer.toString(status));
        assertFalse("Undocumented status for " + this.requestPath + ": " + status, contract.isMissingNode());
        if (contract.has("$ref")) {
            contract = this.document.at(contract.path("$ref").asText().substring(1));
        }
        final JsonNode content = contract.path("content");
        if (content.isMissingNode() || content.isEmpty()) {
            assertTrue(this.response.body(), this.response.body().isEmpty());
            return;
        }
        assertTrue(this.response.headers().firstValue("Content-Type").orElse(""), this.response.headers()
                .firstValue("Content-Type").orElse("").startsWith("application/json"));
        final JsonNode schema = content.path("application/json").path("schema");
        final ObjectNode resolved = schema.deepCopy();
        resolved.set("components", this.document.path("components"));
        final JsonNode payload = Json.mapper().readTree(this.response.body());
        final Set<ValidationMessage> errors = JsonSchemaFactory.builder(JsonSchemaFactory.getInstance(SpecVersion.VersionFlag.V4))
                .metaSchema(OpenApi30.getInstance()).defaultMetaSchemaIri("https://spec.openapis.org/oas/3.0/dialect").build()
                .getSchema(resolved).validate(payload);
        assertTrue(errors.toString(), errors.isEmpty());
        thenDocumentedPropertiesCoverThePayload(schema, payload);
    }

    private void thenDocumentedPropertiesCoverThePayload(final JsonNode schema, final JsonNode payload) {
        final JsonNode resolved = resolveReference(schema);
        if (resolved.isMissingNode() || resolved.has("oneOf") || resolved.has("anyOf")) {
            return;
        }
        if (payload.isArray()) {
            if (resolved.has("items")) {
                for (final JsonNode element : payload) {
                    thenDocumentedPropertiesCoverThePayload(resolved.path("items"), element);
                }
            }
            return;
        }
        if (!payload.isObject() || resolved.has("additionalProperties")) {
            return;
        }
        final Set<String> documented = new HashSet<>();
        collectProperties(resolved, documented);
        if (documented.isEmpty()) {
            return;
        }
        payload.fieldNames().forEachRemaining(
                field -> assertTrue("Undocumented response property " + this.requestPath + "." + field,
                        documented.contains(field)));
    }

    private JsonNode resolveReference(final JsonNode schema) {
        JsonNode resolved = schema;
        while (resolved.has("$ref")) {
            resolved = this.document.at(resolved.path("$ref").asText().substring(1));
        }
        return resolved;
    }

    private void collectProperties(final JsonNode schema, final Set<String> documented) {
        final JsonNode allOf = schema.path("allOf");
        if (allOf.isArray()) {
            for (final JsonNode member : allOf) {
                collectProperties(resolveReference(member), documented);
            }
        }
        schema.path("properties").fieldNames().forEachRemaining(documented::add);
    }
}
