/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.openapi;

import static org.mockito.Mockito.when;

import java.util.Set;

import org.junit.Test;

public class AuthenticationHttpContractTest extends AbstractHttpContractTest {

    @Test
    public void publicAuthenticationOptionsMatchTheContract() throws Exception {
        givenServer();
        givenNoBasicAuthentication();

        whenRequest("GET", "/session/v1/authenticationInfo", null);

        thenResponseMatchesContract(200);
    }

    @Test
    public void missingAuthenticationReturnsDocumentedUnauthorized() throws Exception {
        givenServer();
        givenNoBasicAuthentication();

        whenRequest("GET", "/system/v1/properties/kura", null);

        thenResponseMatchesContract(401);
    }

    @Test
    public void missingPermissionReturnsDocumentedForbidden() throws Exception {
        givenServer();
        givenNoPermissions();

        whenRequest("GET", "/configuration/v2/snapshots", null);

        thenResponseMatchesContract(403);
    }

    @Test
    public void administratorPermissionAllowsConfigurationReads() throws Exception {
        givenServer();
        givenAdministratorPermission();

        whenRequest("GET", "/configuration/v2/snapshots", null);

        thenResponseMatchesContract(200);
    }

    @Test
    public void invalidBasicCredentialsReturnDocumentedUnauthorized() throws Exception {
        givenServer();
        givenInvalidBasicCredentials();

        whenRequest("GET", "/system/v1/properties/kura", null);

        thenResponseMatchesContract(401);
    }

    @Test
    public void invalidLoginMatchesTheErrorContract() throws Exception {
        givenServer();
        givenNoBasicAuthentication();

        whenRequest("POST", "/session/v1/login/password", "{\"username\":\"user\",\"password\":\"wrong\"}");

        thenResponseMatchesContract(401);
    }

    @Test
    public void missingLoginFieldsMatchTheErrorContract() throws Exception {
        givenServer();
        givenNoBasicAuthentication();

        whenRequest("POST", "/session/v1/login/password", "{}");

        thenResponseMatchesContract(400);
    }

    @Test
    public void sessionAndXsrfTokenAllowReadAccess() throws Exception {
        givenServer();
        givenSession();
        givenXsrfToken();

        whenRequest("GET", "/system/v1/properties/kura", null);

        whenRequest("GET", "/session/v1/currentIdentity", null);

        thenLastResponsesMatchContract(200, 200);
    }

    @Test
    public void missingXsrfTokenRejectsEvenGetRequests() throws Exception {
        givenServer();
        givenSession();

        whenRequest("GET", "/system/v1/properties/kura", null);

        thenResponseMatchesContract(401);
    }

    @Test
    public void invalidXsrfTokenRejectsReadAccess() throws Exception {
        givenServer();
        givenSession();
        givenInvalidXsrfToken();

        whenRequest("GET", "/configuration/v2/snapshots", null);

        thenResponseMatchesContract(401);
    }

    @Test
    public void lockedSessionCannotReadProperties() throws Exception {
        givenServer();
        givenPasswordChangeRequired();
        givenSession();
        givenXsrfToken();

        whenRequest("GET", "/system/v1/properties/kura", null);

        thenResponseMatchesContract(401);
    }

    @Test
    public void passwordChangeReplacesAndUnlocksTheSession() throws Exception {
        givenServer();
        givenPasswordChangeRequired();
        givenSession();
        givenXsrfToken();

        whenRequest("POST", "/session/v1/changePassword",
                "{\"currentPassword\":\"password\",\"newPassword\":\"new-password\"}");
        whenTokenIsRefreshed();
        whenRequest("GET", "/system/v1/properties/kura", null);

        thenLastResponsesMatchContract(204, 200, 200);
    }

    @Test
    public void logoutInvalidatesTheSession() throws Exception {
        givenServer();
        givenSession();
        givenXsrfToken();

        whenRequest("POST", "/session/v1/logout", null);

        whenRequest("GET", "/system/v1/properties/kura", null);

        thenLastResponsesMatchContract(204, 401);
    }

    @Test
    public void disabledSessionLoginReturnsDocumentedNotFound() throws Exception {
        givenSessionsDisabled();
        givenServer();
        givenNoBasicAuthentication();

        whenRequest("POST", "/session/v1/login/password", "{\"username\":\"user\",\"password\":\"password\"}");

        thenResponseMatchesContract(404);
    }

    @Test
    public void certificateLoginWithoutCertificateIsRejected() throws Exception {
        givenServer();
        givenNoBasicAuthentication();

        whenRequest("POST", "/session/v1/login/certificate", null);

        thenResponseMatchesContract(401);
    }

    private void givenNoPermissions() {
        this.permissions = Set.of();
    }

    private void givenAdministratorPermission() {
        this.permissions = Set.of("kura.admin");
    }

    private void givenInvalidXsrfToken() {
        this.token = "invalid-token";
    }

    private void givenPasswordChangeRequired() throws Exception {
        when(this.identities.isPasswordChangeRequired("user")).thenReturn(true);
    }

    private void givenSessionsDisabled() {
        this.options.put("session.management.enabled", false);
    }
}
