/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 ******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.openapi;

import static org.junit.Assert.assertEquals;
import static org.mockito.ArgumentMatchers.anyMap;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.util.List;
import java.util.Map;

import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.KuraException;
import org.eclipse.kura.configuration.ComponentConfiguration;
import org.junit.Test;

import io.swagger.v3.core.util.Json;

public class ConfigurationHttpContractTest extends AbstractHttpContractTest {

    @Test
    public void configurationReadsMatchTheContract() throws Exception {
        givenServer();
        givenComponentConfiguration();

        whenRequest("GET", "/configuration/v2/configurableComponents/configurations", null);

        whenRequest("POST", "/configuration/v2/configurableComponents/configurations/byPid", "{\"pids\":[\"test.component\"]}");

        whenRequest("POST", "/configuration/v2/configurableComponents/configurations/byPid/_default",
                "{\"pids\":[\"test.component\"]}");

        whenRequest("GET", "/configuration/v2/configurableComponents", null);

        whenRequest("GET", "/configuration/v2/configurableComponents/pidsWithFactory", null);

        thenLastResponsesMatchContract(200, 200, 200, 200, 200);
    }

    @Test
    public void factoryReadsMatchTheContract() throws Exception {
        givenServer();

        whenRequest("GET", "/configuration/v2/factoryComponents", null);

        whenRequest("GET", "/configuration/v2/factoryComponents/ocd", null);

        whenRequest("POST", "/configuration/v2/factoryComponents/ocd/byFactoryPid", "{\"pids\":[]}");

        thenLastResponsesMatchContract(200, 200, 200);
    }

    @Test
    public void mutationsReturnDocumentedEmptyBodies() throws Exception {
        givenServer();

        whenRequest("POST", "/configuration/v2/factoryComponents",
                "{\"configs\":[{\"factoryPid\":\"test.factory\",\"pid\":\"test.component\"}],\"takeSnapshot\":false}");

        whenRequest("PUT", "/configuration/v2/configurableComponents/configurations/_update",
                "{\"configs\":[{\"pid\":\"test.component\",\"properties\":{\"enabled\":"
                        + "{\"type\":\"BOOLEAN\",\"value\":true}}}],\"takeSnapshot\":false}");

        whenRequest("DELETE", "/configuration/v2/factoryComponents/byPid",
                "{\"pids\":[\"test.component\"],\"takeSnapshot\":false}");

        thenLastResponsesMatchContract(200, 200, 200);
        thenTypedPropertyReachesTheService();
    }

    @Test
    public void snapshotsMatchTheContract() throws Exception {
        givenServer();

        whenRequest("GET", "/configuration/v2/snapshots", null);

        whenRequest("POST", "/configuration/v2/snapshots/byId", "{\"id\":7}");

        whenRequest("POST", "/configuration/v2/snapshots/_write", null);

        whenRequest("POST", "/configuration/v2/snapshots/_rollback", null);

        whenRequest("POST", "/configuration/v2/snapshots/byId/_rollback", "{\"id\":7}");

        thenLastResponsesMatchContract(200, 200, 200, 200, 200);
    }

    @Test
    public void missingRequestFieldsMatchTheErrorContract() throws Exception {
        givenServer();

        whenRequest("PUT", "/configuration/v2/configurableComponents/configurations/_update", "{}");

        thenResponseMatchesContract(400);
    }

    @Test
    public void missingSnapshotMatchesTheErrorContract() throws Exception {
        givenServer();

        whenRequest("POST", "/configuration/v2/snapshots/byId", "{\"id\":99}");

        thenResponseMatchesContract(404);
    }

    @Test
    public void batchFailureReportsTheFailedSubtask() throws Exception {
        givenServer();
        givenFailingUpdate();

        whenRequest("PUT", "/configuration/v2/configurableComponents/configurations/_update",
                "{\"configs\":[{\"pid\":\"test.component\",\"properties\":{}}],\"takeSnapshot\":false}");

        thenResponseMatchesContract(500);
        thenFailureIdentifiesTheSubtask();
    }

    private void givenComponentConfiguration() throws Exception {
        final ComponentConfiguration configuration = mock(ComponentConfiguration.class);
        when(configuration.getPid()).thenReturn("test.component");
        when(configuration.getConfigurationProperties()).thenReturn(Map.of("enabled", true, "count", 3));
        when(this.configurations.getComponentConfigurations()).thenReturn(List.of(configuration));
        when(this.configurations.getComponentConfiguration("test.component")).thenReturn(configuration);
    }

    private void givenFailingUpdate() throws Exception {
        doThrow(new KuraException(KuraErrorCode.CONFIGURATION_ERROR)).when(this.configurations)
                .updateConfiguration(anyString(), anyMap(), eq(false));
    }

    private void thenFailureIdentifiesTheSubtask() throws Exception {
        assertEquals("update:test.component", Json.mapper().readTree(this.response.body()).at("/failures/0/id").asText());
    }

    private void thenTypedPropertyReachesTheService() throws Exception {
        verify(this.configurations).updateConfiguration("test.component", Map.of("enabled", true), false);
    }
}
