/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.openapi;

import static org.junit.Assert.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.util.Set;

import org.eclipse.kura.identity.IdentityConfiguration;
import org.eclipse.kura.identity.IdentityService;
import org.eclipse.kura.internal.rest.identity.provider.IdentityRestServiceV1;
import org.eclipse.kura.internal.rest.identity.provider.IdentityRestServiceV2;
import org.eclipse.kura.internal.rest.identity.provider.LegacyIdentityService;
import org.glassfish.jersey.server.ResourceConfig;
import org.junit.Test;

public class IdentityHttpContractTest extends AbstractHttpContractTest {

    private final LegacyIdentityService legacy = mock(LegacyIdentityService.class);
    private final IdentityService identity = mock(IdentityService.class);

    @Test
    public void permissionDiscoveryIsPublicInBothVersions() throws Exception {
        givenServer();
        givenNoBasicAuthentication();

        whenRequest("GET", "/identity/v1/definedPermissions", null);
        whenRequest("GET", "/identity/v2/definedPermissions", null);

        thenLastResponsesMatchContract(200, 200);
    }

    @Test
    public void identityCreationRequiresTheIdentityRole() throws Exception {
        givenServer();

        whenRequest("POST", "/identity/v1/identities", "{\"userName\":\"alice\"}");
        whenRequest("POST", "/identity/v2/identities", "{\"name\":\"alice\"}");

        thenLastResponsesMatchContract(403, 403);
    }

    @Test
    public void identityCreationReturnsDocumentedEmptyResponses() throws Exception {
        givenIdentityPermission();
        givenServer();

        whenRequest("POST", "/identity/v1/identities", "{\"userName\":\"alice\"}");
        whenRequest("POST", "/identity/v2/identities", "{\"name\":\"alice\"}");

        thenLastResponsesMatchContract(200, 200);
        thenIdentityWasCreated();
    }

    @Test
    public void conflictingIdentityCreationReturnsTheDocumentedErrorBody() throws Exception {
        givenIdentityPermission();
        givenServer();
        givenIdentityAlreadyExists();

        whenRequest("POST", "/identity/v2/identities", "{\"name\":\"alice\"}");

        thenResponseMatchesContract(409);
    }

    @Test
    public void unknownConfigurationComponentsAreRejectedAsBadRequests() throws Exception {
        givenIdentityPermission();
        givenServer();

        whenRequest("POST", "/identity/v2/identities/byName",
                "{\"identity\":{\"name\":\"alice\"},\"configurationComponents\":[\"Bogus\"]}");
        whenRequest("POST", "/identity/v2/identities/default/byName",
                "{\"identity\":{\"name\":\"alice\"},\"configurationComponents\":[\"Bogus\"]}");

        thenLastResponsesMatchContract(400, 400);
    }

    private void givenIdentityPermission() {
        this.permissions = Set.of("rest.identity");
    }

    private void givenIdentityAlreadyExists() throws org.eclipse.kura.KuraException {
        when(this.identity.createIdentity(any(IdentityConfiguration.class))).thenReturn(false);
    }

    @Override
    protected void registerAdditionalResources(ResourceConfig application) throws Exception {
        when(this.legacy.getDefinedPermissions()).thenReturn(Set.of("rest.identity"));
        when(this.identity.getPermissions()).thenReturn(Set.of());
        when(this.identity.createIdentity(any(IdentityConfiguration.class))).thenReturn(true);
        final IdentityRestServiceV1 v1 = new IdentityRestServiceV1();
        v1.bindLegacyIdentityService(this.legacy);
        final IdentityRestServiceV2 v2 = new IdentityRestServiceV2();
        v2.bindIdentityService(this.identity);
        application.register(v1);
        application.register(v2);
    }

    private void thenIdentityWasCreated() throws Exception {
        assertTrue(this.response.body().isEmpty());
        verify(this.identity).createIdentity(any(IdentityConfiguration.class));
        verify(this.legacy).createUser(any());
    }
}
