/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.openapi;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.io.ByteArrayInputStream;
import java.nio.charset.StandardCharsets;
import java.security.KeyStore.Entry;
import java.security.KeyStore.PrivateKeyEntry;
import java.security.KeyStore.TrustedCertificateEntry;
import java.security.KeyStore;
import java.security.PrivateKey;
import java.security.cert.Certificate;
import java.security.cert.CertificateFactory;
import java.security.spec.PKCS8EncodedKeySpec;
import java.util.Base64;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;

import org.eclipse.kura.internal.rest.keystore.provider.KeystoreRestServiceV1;
import org.eclipse.kura.internal.rest.keystore.provider.KeystoreRestServiceV2;
import org.eclipse.kura.security.keystore.KeystoreService;
import org.glassfish.jersey.server.ResourceConfig;
import org.junit.Test;

public class KeystoreHttpContractTest extends AbstractHttpContractTest {

    private static final String CERTIFICATE_PEM = """
            -----BEGIN CERTIFICATE-----
            MIIDazCCAlOgAwIBAgIUKbHH1qpfMhdVF1iJquhoAMI+Im8wDQYJKoZIhvcNAQEL
            BQAwNzEeMBwGA1UEAwwVb3BlbmFwaS1jb250cmFjdC10ZXN0MRUwEwYDVQQKDAxF
            Y2xpcHNlIEt1cmEwHhcNMjYwOTIyMjA1ODE5WhcNMzYwOTE5MjA1ODE5WjA3MR4w
            HAYDVQQDDBVvcGVuYXBpLWNvbnRyYWN0LXRlc3QxFTATBgNVBAoMDEVjbGlwc2Ug
            S3VyYTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJwRtRkP/KdckQja
            Zv8h0lRlvl64dRk6dfYzApoDNR8TncslmOk2MbgRj1Pq8fMoFzO1TjLlGwGIZ6TK
            6ifwFE1wh5q1EJjPUMaeKJQkH/CwmROr+E7n5xyL6Qito1ZRYRC9nGsQpxsqhLyt
            fdyxEiPhcIkZVS7mtVFO1WmKcaNDNUuM++1qxFkJRrjJB87q1BrETaL2DiLXWtKJ
            UntKPKPKCr+p3EC1WkGZAdhY0P3zhWkbO62lPTNIm0nzoL4JDTsy2aJ2XTtPUnPM
            xSTi4vwa8npTi8hokj6gERV3xqbGeHwoVb8thWGiJ35UEwYIMStzIu0kPaGuZwa7
            4dtGFCUCAwEAAaNvMG0wHQYDVR0OBBYEFLMR5mdVHNUr/LCMyYJJ1BZv6ZhIMB8G
            A1UdIwQYMBaAFLMR5mdVHNUr/LCMyYJJ1BZv6ZhIMA8GA1UdEwEB/wQFMAMBAf8w
            GgYDVR0RBBMwEYIJbG9jYWxob3N0hwR/AAABMA0GCSqGSIb3DQEBCwUAA4IBAQAc
            PcdgszQ7VsVCYzE7iz7cfu8ob7l8kpuTlLhNG8X157EDn479SN2piDpE8m3I6+20
            izOzugQvB9ROmtO2fo0VzwbVVm5fq4mjuJ55V5+3kubgu+2wvaLIWJs+ODquTjUQ
            fmIGq4VWIETwthZPqJUsDsI9sqbqj1lg3t99VyHDQpZAsbEkYZ3u9BaOD+W7fxx6
            j+dmIMqPnkSJbn0p6mT9j+Eajhw2FeL4Js5wdc2gTYhyiTnfttyXbK9gvLI1lRiY
            eW4281nDllHq+FrHYmiSnL7z0bxPN4mh2XhBk1yIUmbxNv1x1MwgJi9i45Q6+OqM
            Gr7+YVttzqYIcD4OPboh
            -----END CERTIFICATE-----""";

    private static final String PRIVATE_KEY_PKCS8_PEM = """
            -----BEGIN PRIVATE KEY-----
            MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCcEbUZD/ynXJEI
            2mb/IdJUZb5euHUZOnX2MwKaAzUfE53LJZjpNjG4EY9T6vHzKBcztU4y5RsBiGek
            yuon8BRNcIeatRCYz1DGniiUJB/wsJkTq/hO5+cci+kIraNWUWEQvZxrEKcbKoS8
            rX3csRIj4XCJGVUu5rVRTtVpinGjQzVLjPvtasRZCUa4yQfO6tQaxE2i9g4i11rS
            iVJ7Sjyjygq/qdxAtVpBmQHYWND984VpGzutpT0zSJtJ86C+CQ07Mtmidl07T1Jz
            zMUk4uL8GvJ6U4vIaJI+oBEVd8amxnh8KFW/LYVhoid+VBMGCDErcyLtJD2hrmcG
            u+HbRhQlAgMBAAECggEAB1AxG0aLgVAuH6sUTnpIP9owrIGaQx9hLbNAOPVThOxH
            ZaCSZMM8WzK/c6A7zDghtjOVwX7I4C6DJM65YDu4x9QxFofLik2UrGn23tI+iOnN
            koVpclEdnFHWDqkMUVwo3z7zWHUET5qTc7/xeOj3P6Utv87nFfaLoo6+I17wakUG
            MMBLpAMCG3ybaxnko94ea5+kYP9qQ1/reM0l0SLeysee6gEA0TVvdZW9Y2s3sweD
            1WA0v5EWNpfY3ROQn4RpJ6OM7ZxWxzGlX/vM0x1Npt/67MA9QlxfeuqVhAzbaz8v
            y9csRyqwQ0+1cta5t2fLszTFQ6BK2Co+UJ687JNI4QKBgQDV0kvoScTeAW1LYTgf
            H5QzywZbcvz1GTqeOEsyRJzq9BBq0EijstbM7caWJXN1hBXphQQEGZAiy/yMOBX6
            E9laS5aWiTluAJ8UDt22vr/k6HfW8xoLoVR9m8gkJ8t/JDE2SUj+m2mhoLX3ra5Z
            W8U0S4UK25nKD92nFz3cWJr7WQKBgQC62v7bGGHIypZSOl0p5IrehRZkK9J665ZU
            rN0gRfVD4LTmEpCVpnCLPeGtilUM7g1izFRksgXIfKHhz7mqE2Jo0wrVjKuFe9dK
            2IpKF5m3n0vt3n1FlWUeyC8ATGw4KcDvlhLuPnF+YyT5qx7ilYurWRjRmInUJXCD
            AqkoKYnhrQKBgDGIbAk9vZtoXTdPKD8dg6mT6L8anjrxQ0EP7WuRtYBAVeVIpus1
            LMmAc7aoqlyY4rKcG9gPS/KjqreY7o5mNr3SMOpik6lF/5QX9Yi2G6IdsFVdL7Vu
            BDKs+epWRbAIZFYdGAnTWt8UadMcqv0MY1y/+ewP/0pt7n0cxznaVNzRAoGBAKao
            bwlRbN3fO0XqAnA8BFRGFduQbnHuMC4j5DJF02UQRaizRDwFsHmw3tme+Q7IQC4v
            mtIZKilQaD50vN9h3LMsEIy5o74x36tFCcrd09+/98QYXlkyz3cuCyXUA+3v58KJ
            cycFkMqueSsqIijsQx+4HvfKepw6LGjddax5qB4dAoGBAIjnd1pNoNX5QJ5DCGsG
            eBwcwUowbvEwOHeY6FKhOedtUE8DVkR2AP4Kv/QZVhwsz/m3Py2KTnXqrx2UxsDn
            1OVtdpEpNplJVEsMHkxZLjjM7Ynk9kHwy3KjAA1i3dMkGXgHrQMR6C+2O5ALsDRN
            VZbfnmyduERiTEbBQKFGvzJZ
            -----END PRIVATE KEY-----""";

    private static final String KEYSTORE_PID = "keystore-contract-test";

    @Test
    public void polymorphicEntriesMatchTheContractInBothVersions() throws Exception {
        givenKeystorePermission();
        givenServer();

        whenRequest("GET", "/keystores/v1/entries", null);
        whenRequest("GET", "/keystores/v2/entries", null);

        thenLastResponsesMatchContract(200, 200);
        thenBothEntryKindsAreReturned();
    }

    @Test
    public void singleCertificateEntryCarriesCertificateDetails() throws Exception {
        givenKeystorePermission();
        givenServer();

        whenRequest("GET", "/keystores/v1/entries/entry?keystoreServicePid=" + KEYSTORE_PID + "&alias=trusted", null);
        whenRequest("GET", "/keystores/v2/entries/entry?keystoreServicePid=" + KEYSTORE_PID + "&alias=trusted", null);

        thenLastResponsesMatchContract(200, 200);
    }

    @Test
    public void unknownEntryYieldsEntitylessNotFound() throws Exception {
        givenKeystorePermission();
        givenServer();

        whenRequest("GET", "/keystores/v1/entries/entry?keystoreServicePid=" + KEYSTORE_PID + "&alias=missing", null);

        thenResponseMatchesContract(404);
    }

    @Test
    public void invalidWriteRequestsReturnDocumentedPlainTextErrors() throws Exception {
        givenKeystorePermission();
        givenServer();

        whenRequest("POST", "/keystores/v1/entries/certificate", "{}");
        whenRequest("POST", "/keystores/v2/entries/certificate", "{}");
        whenRequest("POST", "/keystores/v1/entries/keypair", "{}");
        whenRequest("POST", "/keystores/v2/entries/privatekey", "{}");
        whenRequest("POST", "/keystores/v2/entries/csr", "{}");
        whenRequest("DELETE", "/keystores/v2/entries", "{}");

        thenLastResponsesMatchContract(400, 400, 400, 400, 400, 400);
    }

    @Test
    public void malformedWriteRequestsReturnDocumentedJsonErrors() throws Exception {
        givenKeystorePermission();
        givenServer();

        whenRequest("POST", "/keystores/v2/entries/certificate", "{");

        thenResponseMatchesContract(400);
    }

    @Test
    public void privateKeyWritesToUnknownKeystoresReturnJsonErrors() throws Exception {
        givenKeystorePermission();
        givenServer();

        whenRequest("POST", "/keystores/v2/entries/privatekey",
                "{\"keystoreServicePid\":\"missing\",\"alias\":\"key\",\"certificateChain\":[\"certificate\"]}");

        thenResponseMatchesContract(404);
    }

    private void givenKeystorePermission() {
        this.permissions = Set.of("rest.keystores");
    }

    @Override
    protected void registerAdditionalResources(ResourceConfig application) throws Exception {
        final Certificate certificate = CertificateFactory.getInstance("X.509")
                .generateCertificate(new ByteArrayInputStream(CERTIFICATE_PEM.getBytes(StandardCharsets.US_ASCII)));
        final PrivateKey privateKey = readPrivateKey();

        final Map<String, Entry> entries = new LinkedHashMap<>();
        entries.put("trusted", new TrustedCertificateEntry(certificate));
        entries.put("keypair", new PrivateKeyEntry(privateKey, new Certificate[] { certificate }));

        final KeystoreService keystoreService = mock(KeystoreService.class);
        when(keystoreService.getEntries()).thenReturn(entries);
        when(keystoreService.getAliases()).thenReturn(new java.util.ArrayList<>(entries.keySet()));
        when(keystoreService.getEntry("trusted")).thenReturn(entries.get("trusted"));
        when(keystoreService.getEntry("keypair")).thenReturn(entries.get("keypair"));

        final KeyStore keyStore = mock(KeyStore.class);
        when(keyStore.getType()).thenReturn("JKS");
        when(keyStore.size()).thenReturn(entries.size());
        when(keystoreService.getKeyStore()).thenReturn(keyStore);

        application.register(new KeystoreRestServiceV1() {
            {
                this.keystoreServices.put(KEYSTORE_PID, keystoreService);
            }
        });
        application.register(new KeystoreRestServiceV2() {
            {
                this.keystoreServices.put(KEYSTORE_PID, keystoreService);
            }
        });
    }

    private static PrivateKey readPrivateKey() throws Exception {
        final String base64 = PRIVATE_KEY_PKCS8_PEM.replaceAll("-----[A-Z ]+-----", "").replaceAll("\\s", "");
        final byte[] encoded = Base64.getDecoder().decode(base64);
        return java.security.KeyFactory.getInstance("RSA").generatePrivate(new PKCS8EncodedKeySpec(encoded));
    }

    private void thenBothEntryKindsAreReturned() throws Exception {
        final com.fasterxml.jackson.databind.JsonNode payload = io.swagger.v3.core.util.Json.mapper()
                .readTree(this.response.body());
        assertEquals(2, payload.size());
        final Set<String> types = new java.util.HashSet<>();
        payload.forEach(entry -> types.add(entry.path("type").asText()));
        assertTrue(types.contains("TRUSTED_CERTIFICATE"));
        assertTrue(types.contains("PRIVATE_KEY"));
    }
}
