/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *     Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.openapi;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import java.util.HashSet;
import java.util.Set;

import org.junit.Test;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.models.OpenAPI;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;

public class KuraOpenApiReaderTest {

    private OpenAPI document;

    @Test
    public void inheritedOperationsGetUniquePathDerivedIdentifiers() {
        givenSharedBaseClassResources();

        whenDocumentIsRead();

        thenAllOperationIdsAreUnique();
        thenInheritedOperationsUseMethodAndPath();
    }

    @Test
    public void explicitOperationIdsArePreservedEverywhere() {
        givenSharedBaseClassResources();

        whenDocumentIsRead();

        thenExplicitIdentifiersAreKept();
    }

    private void givenSharedBaseClassResources() {
    }

    private void whenDocumentIsRead() {
        this.document = new KuraOpenApiReader()
                .read(Set.of(FirstVersionResource.class, SecondVersionResource.class, StandaloneResource.class));
    }

    private void thenAllOperationIdsAreUnique() {
        final Set<String> identifiers = new HashSet<>();
        this.document.getPaths().forEach(
                (path, item) -> item.readOperationsMap().forEach((method, operation) -> assertTrue(
                        "Duplicate operationId: " + operation.getOperationId(),
                        identifiers.add(operation.getOperationId()))));
    }

    private void thenInheritedOperationsUseMethodAndPath() {
        assertEquals("get_v1_shared", this.document.getPaths().get("/v1/shared").getGet().getOperationId());
        assertEquals("get_v2_shared", this.document.getPaths().get("/v2/shared").getGet().getOperationId());
        assertEquals("post_v2_extra", this.document.getPaths().get("/v2/extra").getPost().getOperationId());
    }

    private void thenExplicitIdentifiersAreKept() {
        assertEquals("explicit_kept_operation",
                this.document.getPaths().get("/standalone/thing").getGet().getOperationId());
    }

    public static class Result {

        private String value;

        public String getValue() {
            return this.value;
        }
    }

    public abstract static class SharedBaseResource {

        @GET
        @Path("shared")
        @Produces(MediaType.APPLICATION_JSON)
        @Operation(summary = "Shared operation without an explicit identifier.")
        @ApiResponse(responseCode = "200", description = "Shared result.", content = @Content(
                mediaType = MediaType.APPLICATION_JSON, schema = @Schema(implementation = Result.class)))
        public Result getShared() {
            return new Result();
        }
    }

    @Path("v1")
    public static class FirstVersionResource extends SharedBaseResource {
    }

    @Path("v2")
    public static class SecondVersionResource extends SharedBaseResource {

        @POST
        @Path("extra")
        @Produces(MediaType.APPLICATION_JSON)
        @Operation(summary = "Version specific operation without an explicit identifier.")
        @ApiResponse(responseCode = "200", description = "Extra result.", content = @Content(
                mediaType = MediaType.APPLICATION_JSON, schema = @Schema(implementation = Result.class)))
        public Result postExtra() {
            return new Result();
        }
    }

    @Path("standalone")
    public static class StandaloneResource {

        @GET
        @Path("thing")
        @Produces(MediaType.APPLICATION_JSON)
        @Operation(operationId = "explicit_kept_operation", summary = "Standalone operation.")
        @ApiResponse(responseCode = "200", description = "Standalone result.", content = @Content(
                mediaType = MediaType.APPLICATION_JSON, schema = @Schema(implementation = Result.class)))
        public Result getThing() {
            return new Result();
        }
    }
}
