/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.openapi;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

import org.junit.Test;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.networknt.schema.ValidationMessage;

import io.swagger.v3.core.util.Json31;

public class NullableConfigurationSchemaTest {

    private JsonNode document;
    private final List<String> schemas = new ArrayList<>();
    private final List<JsonNode> requests = new ArrayList<>();
    private final List<Set<ValidationMessage>> errors = new ArrayList<>();

    @Test
    public void snapshotFlagsAllowOmissionNullAndBooleans() throws Exception {
        givenGeneratedSchemas();
        givenSnapshotRequests(null, "null", "true", "false");

        whenRequestsAreValidated();

        thenAllRequestsAreAccepted();
    }

    @Test
    public void snapshotFlagsRejectOtherTypes() throws Exception {
        givenGeneratedSchemas();
        givenSnapshotRequests("42", "\"true\"", "[]", "{}");

        whenRequestsAreValidated();

        thenAllRequestsAreRejected();
    }

    @Test
    public void factoryPropertiesAllowOmissionNullAndMaps() throws Exception {
        givenGeneratedSchemas();
        givenFactoryRequests(null, "null", "{}", "{\"enabled\":{\"type\":\"BOOLEAN\",\"value\":true}}");

        whenRequestsAreValidated();

        thenAllRequestsAreAccepted();
    }

    @Test
    public void factoryPropertiesRejectOtherTypesAndInvalidEntries() throws Exception {
        givenGeneratedSchemas();
        givenFactoryRequests("true", "42", "[]", "\"properties\"", "{\"enabled\":{\"type\":\"INVALID\"}}",
                "{\"enabled\":null}", "{\"enabled\":{}}");

        whenRequestsAreValidated();

        thenAllRequestsAreRejected();
    }

    @Test
    public void dynamicConfigurationValuesAllowEveryJsonType() throws Exception {
        givenGeneratedSchemas();
        givenPropertyRequests(null, "null", "true", "42", "1.5", "\"text\"", "[1,null,\"two\"]", "{\"nested\":null}");

        whenRequestsAreValidated();

        thenAllRequestsAreAccepted();
        thenDynamicValuesHaveNoTypeRestriction();
    }

    private void givenGeneratedSchemas() throws Exception {
        this.document = Json31.mapper().readTree(Files.readString(
                Path.of(System.getProperty("openapi.directory"), "openapi.json")));
    }

    private void givenSnapshotRequests(String... values) throws Exception {
        for (final String schema : List.of("CreateFactoryComponentConfigurationsRequest", "UpdateComponentConfigurationRequest",
                "DeleteFactoryComponentRequest")) {
            for (final String value : values) {
                givenRequest(schema, schema.startsWith("Delete") ? "{\"pids\":[]}" : "{\"configs\":[]}", "takeSnapshot", value);
            }
        }
    }

    private void givenFactoryRequests(String... values) throws Exception {
        for (final String value : values) {
            givenRequest("FactoryComponentConfigurationDTO", "{\"pid\":\"test\",\"factoryPid\":\"factory\"}", "properties", value);
        }
    }

    private void givenPropertyRequests(String... values) throws Exception {
        for (final String value : values) {
            givenRequest("PropertyDTO", "{\"type\":\"STRING\"}", "value", value);
        }
    }

    private void givenRequest(String schema, String base, String field, String value) throws Exception {
        final ObjectNode request = (ObjectNode) Json31.mapper().readTree(base);
        if (value != null) {
            request.set(field, Json31.mapper().readTree(value));
        }
        this.schemas.add(schema);
        this.requests.add(request);
    }

    private void whenRequestsAreValidated() {
        for (int i = 0; i < this.requests.size(); i++) {
            this.errors.add(OpenApiSchemaValidator.payloadSchema(this.document, this.schemas.get(i)).validate(this.requests.get(i)));
        }
    }

    private void thenAllRequestsAreAccepted() {
        assertFalse(this.errors.isEmpty());
        for (int i = 0; i < this.errors.size(); i++) {
            assertTrue(this.schemas.get(i) + ": " + this.requests.get(i) + ": " + this.errors.get(i), this.errors.get(i).isEmpty());
        }
    }

    private void thenAllRequestsAreRejected() {
        assertFalse(this.errors.isEmpty());
        for (int i = 0; i < this.errors.size(); i++) {
            assertFalse("Accepted " + this.schemas.get(i) + ": " + this.requests.get(i), this.errors.get(i).isEmpty());
        }
    }

    private void thenDynamicValuesHaveNoTypeRestriction() {
        final JsonNode value = this.document.at("/components/schemas/PropertyDTO/properties/value");
        assertFalse(value.has("type"));
        assertFalse(value.has("nullable"));
    }
}
