/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.openapi;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;

import org.junit.Test;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.networknt.schema.ValidationMessage;

import io.swagger.v3.core.util.Json31;

public class RequiredRequestFieldsTest {

    private JsonNode document;
    private final Map<String, String> requests = new LinkedHashMap<>();
    private final Map<String, Set<ValidationMessage>> results = new LinkedHashMap<>();

    @Test
    public void completeRequestsAreAccepted() throws Exception {
        givenMinimalRequests();

        whenRequestsAreValidated();

        thenAllRequestsAreAccepted();
    }

    @Test
    public void missingRequiredFieldsAreRejected() throws Exception {
        givenMinimalRequests();

        whenRequiredFieldsAreRemoved(false);

        thenAllRequestsAreRejected();
    }

    @Test
    public void nullRequiredFieldsAreRejected() throws Exception {
        givenMinimalRequests();

        whenRequiredFieldsAreRemoved(true);

        thenAllRequestsAreRejected();
    }

    private void givenMinimalRequests() throws Exception {
        this.document = Json31.mapper().readTree(Files.readString(
                Path.of(System.getProperty("openapi.directory"), "openapi.json")));
        this.requests.put("IdentityDTO", "{\"name\":\"alice\"}");
        this.requests.put("PermissionDTO", "{\"name\":\"rest.system\"}");
        this.requests.put("IdentityConfigurationDTO", "{\"identity\":{\"name\":\"alice\"}}");
        this.requests.put("IdentityConfigurationRequestDTO", "{\"identity\":{\"name\":\"alice\"}}");
        this.requests.put("EntryRequest", "{\"keystoreServicePid\":\"keystore\",\"alias\":\"entry\"}");
        this.requests.put("TrustedCertificateWriteRequest",
                "{\"keystoreServicePid\":\"keystore\",\"alias\":\"entry\",\"certificate\":\"certificate\"}");
        this.requests.put("CsrReadRequest", "{\"keystoreServicePid\":\"keystore\",\"alias\":\"entry\","
                + "\"signatureAlgorithm\":\"SHA256withRSA\",\"attributes\":\"CN=test\"}");
        this.requests.put("KeyPairWriteRequest", "{\"keystoreServicePid\":\"keystore\",\"alias\":\"entry\","
                + "\"algorithm\":\"RSA\",\"size\":2048,\"signatureAlgorithm\":\"SHA256withRSA\",\"attributes\":\"CN=test\"}");
        this.requests.put("PrivateKeyWriteRequest",
                "{\"keystoreServicePid\":\"keystore\",\"alias\":\"entry\",\"certificateChain\":[\"certificate\"]}");
    }

    private void whenRequestsAreValidated() throws Exception {
        for (final Map.Entry<String, String> request : this.requests.entrySet()) {
            whenRequestIsValidated(request.getKey(), request.getKey(), Json31.mapper().readTree(request.getValue()));
        }
    }

    private void whenRequiredFieldsAreRemoved(boolean explicitNull) throws Exception {
        for (final Map.Entry<String, String> request : this.requests.entrySet()) {
            final ObjectNode original = (ObjectNode) Json31.mapper().readTree(request.getValue());
            final Iterator<String> fields = original.fieldNames();
            while (fields.hasNext()) {
                final String field = fields.next();
                final ObjectNode payload = original.deepCopy();
                if (explicitNull) {
                    payload.putNull(field);
                } else {
                    payload.remove(field);
                }
                whenRequestIsValidated(request.getKey() + "." + field, request.getKey(), payload);
            }
        }
    }

    private void whenRequestIsValidated(String key, String schemaName, JsonNode payload) {
        this.results.put(key, OpenApiSchemaValidator.payloadSchema(this.document, schemaName).validate(payload));
    }

    private void thenAllRequestsAreAccepted() {
        assertFalse(this.results.isEmpty());
        this.results.forEach((key, errors) -> assertTrue(key + ": " + errors, errors.isEmpty()));
    }

    private void thenAllRequestsAreRejected() {
        assertFalse(this.results.isEmpty());
        this.results.forEach((key, errors) -> assertFalse("Accepted missing required field: " + key, errors.isEmpty()));
    }
}
