/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 ******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.openapi;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Set;

import org.junit.Test;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.networknt.schema.JsonSchema;
import com.networknt.schema.ValidationMessage;

import io.swagger.v3.core.util.Json31;
import io.swagger.v3.core.util.Yaml31;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.parser.OpenAPIV3Parser;
import io.swagger.v3.parser.core.models.ParseOptions;
import io.swagger.v3.parser.core.models.SwaggerParseResult;

public class ValidateOpenApiTest {

    private static final Set<String> HTTP_OPERATIONS = Set.of("get", "post", "put", "delete", "patch", "head",
            "options", "trace");

    private JsonNode document;
    private JsonSchema specificationSchema;
    private Set<ValidationMessage> errors;
    private SwaggerParseResult parsed;
    private JsonNode roundTrip;

    @Test
    public void jsonConformsToTheOpenApiSpecification() throws Exception {
        givenGeneratedDocument("json");

        whenDocumentIsValidated();

        thenDocumentIsValid();
        thenOperationsHaveExplicitContracts();
        thenSecurityMatchesTheAuthenticationFlow();
    }

    @Test
    public void yamlConformsToTheOpenApiSpecification() throws Exception {
        givenGeneratedDocument("yaml");

        whenDocumentIsValidated();

        thenDocumentIsValid();
    }

    @Test
    public void invalidSpecificationIsRejected() throws Exception {
        givenGeneratedDocument("json");
        givenMissingApiTitle();

        whenDocumentIsValidated();

        thenDocumentIsRejected();
    }

    @Test
    public void schemaKeywordsAreValidated() throws Exception {
        givenGeneratedDocument("json");
        givenInvalidSchemaType();

        whenDocumentIsValidated();

        thenDocumentIsRejected();
    }

    @Test
    public void serializationPreservesTheOpenApi31Contract() throws Exception {
        givenGeneratedDocument("json");

        whenDocumentIsRoundTripped();

        thenSchemasAndSecurityArePreserved();
        thenSchemasUseJsonSchemaNullability(this.roundTrip);
    }

    private void givenGeneratedDocument(String format) throws Exception {
        final String source = Files.readString(Path.of(System.getProperty("openapi.directory"), "openapi." + format));
        this.document = ("json".equals(format) ? Json31.mapper() : Yaml31.mapper()).readTree(source);
        this.specificationSchema = OpenApiSchemaValidator.documentSchema();
    }

    private void givenMissingApiTitle() {
        ((ObjectNode) this.document.path("info")).remove("title");
    }

    private void givenInvalidSchemaType() {
        ((ObjectNode) this.document.at("/components/schemas/PropertyDTO/properties/value")).put("type", "invalid-type");
    }

    private void whenDocumentIsRoundTripped() throws Exception {
        final OpenAPI model = Json31.mapper().treeToValue(this.document, OpenAPI.class);
        final OpenAPI yamlModel = Yaml31.mapper().readValue(Yaml31.mapper().writeValueAsString(model), OpenAPI.class);
        this.roundTrip = Json31.mapper().readTree(Json31.mapper().writeValueAsString(yamlModel));
    }

    private void whenDocumentIsValidated() {
        this.errors = this.specificationSchema.validate(this.document);
        final ParseOptions options = new ParseOptions();
        options.setResolve(true);
        this.parsed = new OpenAPIV3Parser().readContents(this.document.toString(), null, options);
    }

    private void thenDocumentIsValid() {
        assertTrue(this.errors.toString(), this.errors.isEmpty());
        assertEquals("3.1.2", this.document.path("openapi").asText());
        thenSchemasUseJsonSchemaNullability(this.document);
        assertNotNull(this.parsed.getOpenAPI());
        assertTrue(this.parsed.getMessages().toString(), this.parsed.getMessages().isEmpty());
    }

    private void thenDocumentIsRejected() {
        assertFalse(this.errors.isEmpty());
    }

    private void thenOperationsHaveExplicitContracts() {
        this.document.path("paths").forEach(
                path -> path.fields().forEachRemaining(operation -> {
                    if (!HTTP_OPERATIONS.contains(operation.getKey())) {
                        return;
                    }
                    final JsonNode contract = operation.getValue();
                    assertFalse(contract.path("summary").asText().isBlank());
                    assertFalse(contract.path("description").asText().isBlank());
                    assertFalse(contract.path("responses").has("default"));
                    assertTrue(contract.path("responses").has("200") || contract.path("responses").has("204"));
                    if (contract.has("requestBody")) {
                        assertTrue(contract.path("requestBody").path("required").asBoolean());
                    }
                }));
    }

    private void thenSchemasAndSecurityArePreserved() {
        assertEquals("3.1.2", this.roundTrip.path("openapi").asText());
        assertEquals(this.document.path("jsonSchemaDialect"), this.roundTrip.path("jsonSchemaDialect"));
        assertEquals(this.document.path("components"), this.roundTrip.path("components"));
        assertEquals(this.document.path("security"), this.roundTrip.path("security"));
        assertEquals(this.document.path("paths"), this.roundTrip.path("paths"));
    }

    private void thenSchemasUseJsonSchemaNullability(JsonNode node) {
        assertFalse("Obsolete nullable keyword: " + node, node.has("nullable"));
        assertFalse("Internal converter marker: " + node, node.has("x-kura-unconstrained"));
        node.forEach(this::thenSchemasUseJsonSchemaNullability);
    }

    private void thenSecurityMatchesTheAuthenticationFlow() throws Exception {
        final JsonNode paths = this.document.path("paths");
        assertEquals(Json31.mapper().readTree("[{\"basicAuth\":[]},{\"sessionCookie\":[],\"xsrfToken\":[]},"
                + "{\"clientCertificate\":[]}]"), this.document.path("security"));
        assertEquals("mutualTLS", this.document.at("/components/securitySchemes/clientCertificate/type").asText());
        assertEquals(Json31.mapper().readTree("[{\"clientCertificate\":[]}]"),
                paths.path("/session/v1/login/certificate").path("post").path("security"));
        assertEquals(Json31.mapper().readTree("[{\"sessionCookie\":[]}]"),
                paths.path("/session/v1/xsrfToken").path("get").path("security"));
        for (final String path : List.of("/session/v1/authenticationInfo", "/identity/v1/definedPermissions",
                "/identity/v1/passwordRequirements", "/identity/v2/definedPermissions", "/identity/v2/passwordStrenghtRequirements")) {
            assertEquals(path, Json31.mapper().createArrayNode(), paths.path(path).path("get").path("security"));
        }
        assertEquals(Json31.mapper().createArrayNode(), paths.path("/session/v1/login/password").path("post").path("security"));
        final JsonNode protectedOperation = paths.path("/system/v1/properties/framework").path("get");
        assertFalse(protectedOperation.isMissingNode());
        assertFalse(protectedOperation.has("security"));
    }
}
