name: Version uptick automation

on:
  workflow_dispatch:
    inputs:
        target_branch:
          type: string
          default: 'develop'
          required: true
        uptick_config:
          type: choice
          description: Configuration to use for the uptick
          options:
            - uptick_major_on_develop_branch.yml
            - uptick_minor_on_develop_branch.yml
            - uptick_patch_on_maintenance_branch.yml
            - uptick_snapshot_to_patch_release.yml
            - uptick_snapshot_to_release.yml
          required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  uptick:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      with:
        ref: ${{ github.event.inputs.target_branch }}

    - name: Setup Java
      uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Download version upticker tool
      uses: carlosperate/download-file-action@8b89cb8b4807765e7d63fe765cc600eb1919af11 # v1.1.2
      with:
        file-url: https://kura-repo.s3.us-west-2.amazonaws.com/esf_upticker_tool/version-uptick-0.2.0-linux-x86_64

    - name: Make the uptick tool executable
      run: |
        chmod +x ./version-uptick-0.2.0-linux-x86_64
      shell: bash

    - name: Run the uptick tool
      run: |
        ./version-uptick-0.2.0-linux-x86_64 \
        --commit --trace process-versions \
        --config-path .github/version_uptick_configs/${{ github.event.inputs.uptick_config }} \
        --root-dir .
      shell: bash

    - name: Cleanup uptick tool
      run: |
        rm ./version-uptick-0.2.0-linux-x86_64
      shell: bash

    - name: Get version
      id: get-version
      run: "echo \"resolved-version=\
        $(mvn
          --file ./bom/pom.xml
          -Dexec.executable=echo
          -Dexec.args='${project.version}'
          --quiet exec:exec --non-recursive
        )\" >> \"${GITHUB_OUTPUT}\""
      shell: bash

    - name: Align the kura-bom import to the upticked version
      env:
        RESOLVED_VERSION: ${{ steps.get-version.outputs.resolved-version }}
      run: |
        perl -0pi -e 's{(<artifactId>kura-bom</artifactId>\s*<version>)[^<]+(</version>)}{${1}'"${RESOLVED_VERSION}"'${2}}' pom.xml
        grep -n 'kura-bom' -A1 pom.xml
      shell: bash

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@38e0b6e68b4c852a5500a94740f0e535e0d7ba54 # v4.2.4
      with:
        title: "chore: automated uptick to ${{ steps.get-version.outputs.resolved-version }}"
        commit-message: "chore: automated uptick to ${{ steps.get-version.outputs.resolved-version }}"
        body: "Automated changes by _Version uptick automation_ action: automated uptick to ${{ steps.get-version.outputs.resolved-version }} version"
        branch-suffix: timestamp
        token: ${{ secrets.BOT_GITHUB_TOKEN }}
