bin.includes = META-INF/,\
               .,\
               OSGI-INF/,\
               about.html,\
               about_files/
source.. = src/main/java/
additional.bundles = org.osgi.service.component.annotations,\
                     org.osgi.service.metatype.annotations