package org.eclipse.kura.nm;

import org.freedesktop.dbus.types.UInt32;

public enum NMDeviceStateReason {

    NM_DEVICE_STATE_REASON_NONE,
    NM_DEVICE_STATE_REASON_UNKNOWN,
    NM_DEVICE_STATE_REASON_NOW_MANAGED,
    NM_DEVICE_STATE_REASON_NOW_UNMANAGED,
    NM_DEVICE_STATE_REASON_CONFIG_FAILED,
    NM_DEVICE_STATE_REASON_IP_CONFIG_UNAVAILABLE,
    NM_DEVICE_STATE_REASON_IP_CONFIG_EXPIRED,
    NM_DEVICE_STATE_REASON_NO_SECRETS,
    NM_DEVICE_STATE_REASON_SUPPLICANT_DISCONNECT,
    NM_DEVICE_STATE_REASON_SUPPLICANT_CONFIG_FAILED,
    NM_DEVICE_STATE_REASON_SUPPLICANT_FAILED,
    NM_DEVICE_STATE_REASON_SUPPLICANT_TIMEOUT,
    NM_DEVICE_STATE_REASON_PPP_START_FAILED,
    NM_DEVICE_STATE_REASON_PPP_DISCONNECT,
    NM_DEVICE_STATE_REASON_PPP_FAILED,
    NM_DEVICE_STATE_REASON_DHCP_START_FAILED,
    NM_DEVICE_STATE_REASON_DHCP_ERROR,
    NM_DEVICE_STATE_REASON_DHCP_FAILED,
    NM_DEVICE_STATE_REASON_SHARED_START_FAILED,
    NM_DEVICE_STATE_REASON_SHARED_FAILED,
    NM_DEVICE_STATE_REASON_AUTOIP_START_FAILED,
    NM_DEVICE_STATE_REASON_AUTOIP_ERROR,
    NM_DEVICE_STATE_REASON_AUTOIP_FAILED,
    NM_DEVICE_STATE_REASON_MODEM_BUSY,
    NM_DEVICE_STATE_REASON_MODEM_NO_DIAL_TONE,
    NM_DEVICE_STATE_REASON_MODEM_NO_CARRIER,
    NM_DEVICE_STATE_REASON_MODEM_DIAL_TIMEOUT,
    NM_DEVICE_STATE_REASON_MODEM_DIAL_FAILED,
    NM_DEVICE_STATE_REASON_MODEM_INIT_FAILED,
    NM_DEVICE_STATE_REASON_GSM_APN_FAILED,
    NM_DEVICE_STATE_REASON_GSM_REGISTRATION_NOT_SEARCHING,
    NM_DEVICE_STATE_REASON_GSM_REGISTRATION_DENIED,
    NM_DEVICE_STATE_REASON_GSM_REGISTRATION_TIMEOUT,
    NM_DEVICE_STATE_REASON_GSM_REGISTRATION_FAILED,
    NM_DEVICE_STATE_REASON_GSM_PIN_CHECK_FAILED,
    NM_DEVICE_STATE_REASON_FIRMWARE_MISSING,
    NM_DEVICE_STATE_REASON_REMOVED,
    NM_DEVICE_STATE_REASON_SLEEPING,
    NM_DEVICE_STATE_REASON_CONNECTION_REMOVED,
    NM_DEVICE_STATE_REASON_USER_REQUESTED,
    NM_DEVICE_STATE_REASON_CARRIER,
    NM_DEVICE_STATE_REASON_CONNECTION_ASSUMED,
    NM_DEVICE_STATE_REASON_SUPPLICANT_AVAILABLE,
    NM_DEVICE_STATE_REASON_MODEM_NOT_FOUND,
    NM_DEVICE_STATE_REASON_BT_FAILED,
    NM_DEVICE_STATE_REASON_GSM_SIM_NOT_INSERTED,
    NM_DEVICE_STATE_REASON_GSM_SIM_PIN_REQUIRED,
    NM_DEVICE_STATE_REASON_GSM_SIM_PUK_REQUIRED,
    NM_DEVICE_STATE_REASON_GSM_SIM_WRONG,
    NM_DEVICE_STATE_REASON_INFINIBAND_MODE,
    NM_DEVICE_STATE_REASON_DEPENDENCY_FAILED,
    NM_DEVICE_STATE_REASON_BR2684_FAILED,
    NM_DEVICE_STATE_REASON_MODEM_MANAGER_UNAVAILABLE,
    NM_DEVICE_STATE_REASON_SSID_NOT_FOUND,
    NM_DEVICE_STATE_REASON_SECONDARY_CONNECTION_FAILED,
    NM_DEVICE_STATE_REASON_DCB_FCOE_FAILED,
    NM_DEVICE_STATE_REASON_TEAMD_CONTROL_FAILED,
    NM_DEVICE_STATE_REASON_MODEM_FAILED,
    NM_DEVICE_STATE_REASON_MODEM_AVAILABLE,
    NM_DEVICE_STATE_REASON_SIM_PIN_INCORRECT,
    NM_DEVICE_STATE_REASON_NEW_ACTIVATION,
    NM_DEVICE_STATE_REASON_PARENT_CHANGED,
    NM_DEVICE_STATE_REASON_PARENT_MANAGED_CHANGED,
    NM_DEVICE_STATE_REASON_OVSDB_FAILED,
    NM_DEVICE_STATE_REASON_IP_ADDRESS_DUPLICATE,
    NM_DEVICE_STATE_REASON_IP_METHOD_UNSUPPORTED,
    NM_DEVICE_STATE_REASON_SRIOV_CONFIGURATION_FAILED,
    NM_DEVICE_STATE_REASON_PEER_NOT_FOUND;

    public static NMDeviceStateReason fromUInt32(UInt32 reason) {
        switch (reason.intValue()) {
        case 0:
            return NM_DEVICE_STATE_REASON_NONE;
        case 2:
            return NM_DEVICE_STATE_REASON_NOW_MANAGED;
        case 3:
            return NM_DEVICE_STATE_REASON_NOW_UNMANAGED;
        case 4:
            return NM_DEVICE_STATE_REASON_CONFIG_FAILED;
        case 5:
            return NM_DEVICE_STATE_REASON_IP_CONFIG_UNAVAILABLE;
        case 6:
            return NM_DEVICE_STATE_REASON_IP_CONFIG_EXPIRED;
        case 7:
            return NM_DEVICE_STATE_REASON_NO_SECRETS;
        case 8:
            return NM_DEVICE_STATE_REASON_SUPPLICANT_DISCONNECT;
        case 9:
            return NM_DEVICE_STATE_REASON_SUPPLICANT_CONFIG_FAILED;
        case 10:
            return NM_DEVICE_STATE_REASON_SUPPLICANT_FAILED;
        case 11:
            return NM_DEVICE_STATE_REASON_SUPPLICANT_TIMEOUT;
        case 12:
            return NM_DEVICE_STATE_REASON_PPP_START_FAILED;
        case 13:
            return NM_DEVICE_STATE_REASON_PPP_DISCONNECT;
        case 14:
            return NM_DEVICE_STATE_REASON_PPP_FAILED;
        case 15:
            return NM_DEVICE_STATE_REASON_DHCP_START_FAILED;
        case 16:
            return NM_DEVICE_STATE_REASON_DHCP_ERROR;
        case 17:
            return NM_DEVICE_STATE_REASON_DHCP_FAILED;
        case 18:
            return NM_DEVICE_STATE_REASON_SHARED_START_FAILED;
        case 19:
            return NM_DEVICE_STATE_REASON_SHARED_FAILED;
        case 20:
            return NM_DEVICE_STATE_REASON_AUTOIP_START_FAILED;
        case 21:
            return NM_DEVICE_STATE_REASON_AUTOIP_ERROR;
        case 22:
            return NM_DEVICE_STATE_REASON_AUTOIP_FAILED;
        case 23:
            return NM_DEVICE_STATE_REASON_MODEM_BUSY;
        case 24:
            return NM_DEVICE_STATE_REASON_MODEM_NO_DIAL_TONE;
        case 25:
            return NM_DEVICE_STATE_REASON_MODEM_NO_CARRIER;
        case 26:
            return NM_DEVICE_STATE_REASON_MODEM_DIAL_TIMEOUT;
        case 27:
            return NM_DEVICE_STATE_REASON_MODEM_DIAL_FAILED;
        case 28:
            return NM_DEVICE_STATE_REASON_MODEM_INIT_FAILED;
        case 29:
            return NM_DEVICE_STATE_REASON_GSM_APN_FAILED;
        case 30:
            return NM_DEVICE_STATE_REASON_GSM_REGISTRATION_NOT_SEARCHING;
        case 31:
            return NM_DEVICE_STATE_REASON_GSM_REGISTRATION_DENIED;
        case 32:
            return NM_DEVICE_STATE_REASON_GSM_REGISTRATION_TIMEOUT;
        case 33:
            return NM_DEVICE_STATE_REASON_GSM_REGISTRATION_FAILED;
        case 34:
            return NM_DEVICE_STATE_REASON_GSM_PIN_CHECK_FAILED;
        case 35:
            return NM_DEVICE_STATE_REASON_FIRMWARE_MISSING;
        case 36:
            return NM_DEVICE_STATE_REASON_REMOVED;
        case 37:
            return NM_DEVICE_STATE_REASON_SLEEPING;
        case 38:
            return NM_DEVICE_STATE_REASON_CONNECTION_REMOVED;
        case 39:
            return NM_DEVICE_STATE_REASON_USER_REQUESTED;
        case 40:
            return NM_DEVICE_STATE_REASON_CARRIER;
        case 41:
            return NM_DEVICE_STATE_REASON_CONNECTION_ASSUMED;
        case 42:
            return NM_DEVICE_STATE_REASON_SUPPLICANT_AVAILABLE;
        case 43:
            return NM_DEVICE_STATE_REASON_MODEM_NOT_FOUND;
        case 44:
            return NM_DEVICE_STATE_REASON_BT_FAILED;
        case 45:
            return NM_DEVICE_STATE_REASON_GSM_SIM_NOT_INSERTED;
        case 46:
            return NM_DEVICE_STATE_REASON_GSM_SIM_PIN_REQUIRED;
        case 47:
            return NM_DEVICE_STATE_REASON_GSM_SIM_PUK_REQUIRED;
        case 48:
            return NM_DEVICE_STATE_REASON_GSM_SIM_WRONG;
        case 49:
            return NM_DEVICE_STATE_REASON_INFINIBAND_MODE;
        case 50:
            return NM_DEVICE_STATE_REASON_DEPENDENCY_FAILED;
        case 51:
            return NM_DEVICE_STATE_REASON_BR2684_FAILED;
        case 52:
            return NM_DEVICE_STATE_REASON_MODEM_MANAGER_UNAVAILABLE;
        case 53:
            return NM_DEVICE_STATE_REASON_SSID_NOT_FOUND;
        case 54:
            return NM_DEVICE_STATE_REASON_SECONDARY_CONNECTION_FAILED;
        case 55:
            return NM_DEVICE_STATE_REASON_DCB_FCOE_FAILED;
        case 56:
            return NM_DEVICE_STATE_REASON_TEAMD_CONTROL_FAILED;
        case 57:
            return NM_DEVICE_STATE_REASON_MODEM_FAILED;
        case 58:
            return NM_DEVICE_STATE_REASON_MODEM_AVAILABLE;
        case 59:
            return NM_DEVICE_STATE_REASON_SIM_PIN_INCORRECT;
        case 60:
            return NM_DEVICE_STATE_REASON_NEW_ACTIVATION;
        case 61:
            return NM_DEVICE_STATE_REASON_PARENT_CHANGED;
        case 62:
            return NM_DEVICE_STATE_REASON_PARENT_MANAGED_CHANGED;
        case 63:
            return NM_DEVICE_STATE_REASON_OVSDB_FAILED;
        case 64:
            return NM_DEVICE_STATE_REASON_IP_ADDRESS_DUPLICATE;
        case 65:
            return NM_DEVICE_STATE_REASON_IP_METHOD_UNSUPPORTED;
        case 66:
            return NM_DEVICE_STATE_REASON_SRIOV_CONFIGURATION_FAILED;
        case 67:
            return NM_DEVICE_STATE_REASON_PEER_NOT_FOUND;
        case 1:
        default:
            return NM_DEVICE_STATE_REASON_UNKNOWN;

        }
    }

}
