<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2025 Eurotech and/or its affiliates and others

    This program and the accompanying materials are made
    available under the terms of the Eclipse Public License 2.0
    which is available at https://www.eclipse.org/legal/epl-2.0/

    SPDX-License-Identifier: EPL-2.0

    Contributors:
     Eurotech

-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>distrib-extra</artifactId>
        <groupId>org.eclipse.kura</groupId>
        <version>6.0.0-SNAPSHOT</version>
        <relativePath>..</relativePath>
    </parent>

    <artifactId>distrib-nm</artifactId>

    <packaging>pom</packaging>

    <properties>
        <kura.have.net.admin>true</kura.have.net.admin>
        <deb.dependencies> openjdk-17-jre-headless | temurin-17-jdk,
            setserial, zip, gzip, unzip, procps, usbutils, socat, gawk, sed, inetutils-telnet,
            polkit | policykit-1, ssh | openssh, openssl, busybox, openvpn,
            chrony, chronyc | chrony, cron | cronie,
            network-manager | networkmanager, bind9 | bind, dnsmasq | isc-dhcp-server, isc-dhcp-client | dhcpcd, iw, iptables, modemmanager,
            logrotate, gpsd, python3
        </deb.dependencies>
        <kura-networking.version>3.0.0-SNAPSHOT</kura-networking.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.core.net</artifactId>
            <version>${kura-networking.version}</version>
        </dependency>

        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.linux.net</artifactId>
            <version>${kura-networking.version}</version>
        </dependency>

        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.linux.systemd.provider</artifactId>
            <version>${kura-networking.version}</version>
        </dependency>

        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.net.admin.firewall</artifactId>
            <version>${kura-networking.version}</version>
        </dependency>

        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.net.configuration</artifactId>
            <version>${kura-networking.version}</version>
        </dependency>

        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.network.threat.manager</artifactId>
            <version>${kura-networking.version}</version>
        </dependency>

        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.nm</artifactId>
            <version>${kura-networking.version}</version>
        </dependency>

        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.rest.network.configuration.provider</artifactId>
            <version>${kura-networking.version}</version>
        </dependency>

        <dependency>
            <groupId>org.eclipse.kura</groupId>
            <artifactId>org.eclipse.kura.rest.network.status.provider</artifactId>
            <version>${kura-networking.version}</version>
        </dependency>
    </dependencies>

    <modules>
        <module>aarch64</module>
        <module>x86_64</module>
    </modules>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <artifactId>maven-dependency-plugin</artifactId>
                    <executions>
                        <execution>
                            <id>network-management-plugins-4</id>
                            <phase>generate-sources</phase>
                            <goals>
                                <goal>copy-dependencies</goal>
                            </goals>
                            <configuration>
                                <outputDirectory>${project.build.directory}/pkg/plugins/4</outputDirectory>
                                <skip>${exclude.network.management}</skip>
                                <includeArtifactIds>
                                    <!-- core.net-plugins -->
                                    org.eclipse.kura.net.configuration,
                                    <!-- linux-network-plugins -->
                                    org.eclipse.kura.linux.net,
                                    org.eclipse.kura.linux.systemd.provider
                                </includeArtifactIds>
                            </configuration>
                        </execution>
                        <execution>
                            <id>network-management-plugins-4s</id>
                            <phase>generate-sources</phase>
                            <goals>
                                <goal>copy-dependencies</goal>
                            </goals>
                            <configuration>
                                <outputDirectory>${project.build.directory}/pkg/plugins/4s</outputDirectory>
                                <includeArtifactIds>
                                    <!-- linux-network-plugins -->
                                    org.eclipse.kura.rest.network.configuration.provider,
                                    org.eclipse.kura.network.threat.manager,
                                    <!-- core.net-plugins -->
                                    org.eclipse.kura.core.net
                                </includeArtifactIds>
                            </configuration>
                        </execution>
                        <execution>
                            <id>network-management-plugins-5s</id>
                            <phase>generate-sources</phase>
                            <goals>
                                <goal>copy-dependencies</goal>
                            </goals>
                            <configuration>
                                <outputDirectory>${project.build.directory}/pkg/plugins/5s</outputDirectory>
                                <includeArtifactIds>
                                    <!-- linux-network-plugins --> org.eclipse.kura.net.admin.firewall,
                                    org.eclipse.kura.rest.network.status.provider,
                                    org.eclipse.kura.nm </includeArtifactIds>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.vafer</groupId>
                    <artifactId>jdeb</artifactId>
                    <configuration>
                        <dataSet combine.children="append">
                            <data>
                                <src>
                                    ${project.build.directory}/99-kura-nm.conf</src>
                                <dst>/etc/NetworkManager/conf.d/99-kura-nm.conf</dst>
                                <type>file</type>
                            </data>
                        </dataSet>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>