/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.util.zip;

import java.io.FilterInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InterruptedIOException;
import java.util.Locale;
import java.util.concurrent.TimeUnit;

/**
 * Fails every read made after the given time has elapsed.
 */
class TimeLimitedInputStream extends FilterInputStream {

    private final long start = System.nanoTime();
    private final long timeoutNanos;
    private final String timeoutMessage;

    TimeLimitedInputStream(InputStream in, long timeout, TimeUnit unit) {
        super(in);
        this.timeoutNanos = unit.toNanos(timeout);
        this.timeoutMessage = "The extraction did not complete within " + timeout + " "
                + unit.name().toLowerCase(Locale.ROOT);
    }

    @Override
    public int read() throws IOException {
        checkTimeout();
        return super.read();
    }

    @Override
    public int read(byte[] b, int off, int len) throws IOException {
        checkTimeout();
        return super.read(b, off, len);
    }

    private void checkTimeout() throws InterruptedIOException {
        if (System.nanoTime() - this.start > this.timeoutNanos) {
            throw new InterruptedIOException(this.timeoutMessage);
        }
    }
}
