/*******************************************************************************
 * Copyright (c) 2011, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.util.zip;

import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.util.ArrayDeque;
import java.util.Deque;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;

import org.eclipse.kura.KuraErrorCode;
import org.eclipse.kura.KuraException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class UnZip {

    private static final Logger logger = LoggerFactory.getLogger(UnZip.class);

    private static final int BUFFER = 1024;
    private static int tooBig = 0x6400000; // Max size of unzipped data, 100MB
    private static int tooMany = 1024;     // Max number of files

    private UnZip() {
        // Do nothing...
    }

    public static void unZipBytes(byte[] bytes, String outputFolder) throws IOException {
        ZipInputStream zis = new ZipInputStream(new ByteArrayInputStream(bytes));
        unZipZipInputStream(zis, outputFolder);
    }

    public static void unZipFile(String filename, String outputFolder) throws IOException {
        File file = new File(filename);
        ZipInputStream zis = new ZipInputStream(new FileInputStream(file));
        unZipZipInputStream(zis, outputFolder);
    }

    private static void unZipZipInputStream(ZipInputStream zis, String outFolder) throws IOException {
        File folder = new File(outFolder == null ? System.getProperty("user.dir") : outFolder);
        Deque<File> createdEntries = new ArrayDeque<>();

        try {
            createDirectories(folder, createdEntries);

            unZipEntries(zis, folder, createdEntries);
        } catch (IOException | RuntimeException e) {
            deleteCreatedEntries(createdEntries);
            throw e;
        } finally {
            zis.close();
        }
    }

    private static void unZipEntries(ZipInputStream zis, File folder, Deque<File> createdEntries) throws IOException {
        int entries = 0;
        long total = 0;

        ZipEntry ze = zis.getNextEntry();

        while (ze != null) {
            File newFile = getFile(entryPath(folder, ze), folder);

            if (ze.isDirectory()) {
                createDirectories(newFile, createdEntries);
            } else {
                total = writeEntry(zis, newFile, createdEntries, total);
                entries++;

                verifyLimits(entries, total);
            }

            ze = zis.getNextEntry();
        }

        zis.closeEntry();
    }

    private static long writeEntry(ZipInputStream zis, File newFile, Deque<File> createdEntries, long writtenSoFar)
            throws IOException {
        if (newFile.getParent() != null) {
            createDirectories(new File(newFile.getParent()), createdEntries);
        }

        if (!newFile.exists()) {
            createdEntries.push(newFile);
        }

        long total = writtenSoFar;
        try (FileOutputStream fos = new FileOutputStream(newFile)) {
            byte[] buffer = new byte[BUFFER];

            int len = zis.read(buffer);
            while (total + BUFFER <= tooBig && len > 0) {
                fos.write(buffer, 0, len);
                total += len;
                len = zis.read(buffer);
            }
            fos.flush();
        }

        return total;
    }

    private static void verifyLimits(int entries, long total) {
        if (entries > tooMany) {
            throw new IllegalStateException("Too many files to unzip.");
        }

        if (total + BUFFER > tooBig) {
            throw new IllegalStateException("File being unzipped is too big.");
        }
    }

    private static String entryPath(File folder, ZipEntry ze) {
        return new StringBuilder(folder.getPath()).append(File.separator).append(ze.getName()).toString();
    }

    private static void createDirectories(File directory, Deque<File> createdEntries) {
        if (directory == null || directory.exists()) {
            return;
        }

        createDirectories(directory.getParentFile(), createdEntries);

        if (directory.mkdir()) {
            createdEntries.push(directory);
        }
    }

    private static void deleteCreatedEntries(Deque<File> createdEntries) {
        while (!createdEntries.isEmpty()) {
            File entry = createdEntries.pop();
            try {
                Files.deleteIfExists(entry.toPath());
            } catch (IOException e) {
                logger.warn("Unable to delete {} while cleaning up a failed extraction", entry, e);
            }
        }
    }

    private static File getFile(String expectedFilePath, File folder) throws IOException {
        String fileName;
        try {
            fileName = validateFileName(expectedFilePath, folder.getPath());
        } catch (KuraException e) {
            throw new IOException("File is outside extraction target directory.");
        }
        return new File(fileName);
    }

    private static String validateFileName(String zipFileName, String intendedDir) throws IOException, KuraException {
        File zipFile = new File(zipFileName);
        String filePath = zipFile.getCanonicalPath();

        File iD = new File(intendedDir);
        String canonicalID = iD.getCanonicalPath();

        if (filePath.startsWith(canonicalID)) {
            return filePath;
        } else {
            throw new KuraException(KuraErrorCode.SECURITY_EXCEPTION);
        }
    }

    public static boolean isZipCompressed(String filePath) throws IOException {
        byte b1 = 0;
        byte b2 = 0;

        try (InputStream is = new FileInputStream(filePath)) {
            b1 = (byte) is.read();
            b2 = (byte) is.read();
        } catch (IOException e) {
            throw new IOException(e);
        }

        return b1 == 0x50 && b2 == 0x4B;
    }

    public static boolean isZipCompressed(byte[] bytes) {
        if (bytes.length > 2) {
            return bytes[0] == 0x50 && bytes[1] == 0x4B;
        } else {
            return false;
        }
    }

}
