/*******************************************************************************
 * Copyright (c) 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.util.zip;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.attribute.FileAttribute;
import java.nio.file.attribute.PosixFilePermissions;

import org.eclipse.kura.executor.Command;
import org.eclipse.kura.executor.CommandExecutorService;
import org.eclipse.kura.executor.CommandStatus;
import org.eclipse.kura.executor.ExitStatus;

/**
 * Implements {@link UnZip#unZip(InputStream, String, CommandExecutorService)}: runs {@link ZipExtractor#main(String[])}
 * in a dedicated process spawned through a {@link CommandExecutorService}, so that the files are written with the
 * permissions of the user the executor runs commands as.
 */
final class UnZipProcess {

    // ZipExtractor.main enforces EXTRACTION_TIMEOUT itself, so that it can remove what it extracted so far. The
    // executor
    // kills the process only if it hangs, for instance on a stalled read, and then a partial extraction is left behind.
    private static final int PROCESS_TIMEOUT = ZipExtractor.EXTRACTION_TIMEOUT + 30;
    private static final String EXTRACTION_CLASSES_PREFIX = "kura-unzip-classes-";

    private static final Class<?>[] EXTRACTION_CLASSES = { ZipExtractor.class, TimeLimitedInputStream.class };

    private static volatile String extractionClassPath;

    private UnZipProcess() {
        // Do nothing...
    }

    static void unZip(InputStream archive, String outputFolder, CommandExecutorService executorService)
            throws IOException {
        // The arguments are quoted for a shell, which is requested from every executor since the unprivileged one
        // always
        // joins them with spaces and runs them through "su -c". The JVM options keep the footprint of the extraction
        // process low.
        String[] commandLine = { quote(javaExecutable()), "-Xmx32m", "-XX:+UseSerialGC", "-XX:TieredStopAtLevel=1",
                "-cp", quote(extractionClassPath()), ZipExtractor.class.getName(), quote(outputFolder) };

        ByteArrayOutputStream err = new ByteArrayOutputStream();

        Command command = new Command(commandLine);
        command.setExecuteInAShell(true);
        command.setTimeout(PROCESS_TIMEOUT);
        command.setInputStream(archive);
        command.setErrorStream(err);

        CommandStatus status = executorService.execute(command);

        if (status.isTimedout()) {
            throw new IOException("The extraction of the archive in " + outputFolder + " did not complete within "
                    + PROCESS_TIMEOUT + " seconds");
        }

        ExitStatus exitStatus = status.getExitStatus();
        if (!exitStatus.isSuccessful()) {
            throw new IOException("Unable to extract the archive in " + outputFolder + " (exit code "
                    + exitStatus.getExitCode() + "): " + new String(err.toByteArray(), StandardCharsets.UTF_8).trim());
        }
    }

    private static String javaExecutable() {
        return System.getProperty("java.home") + File.separator + "bin" + File.separator + "java";
    }

    private static String extractionClassPath() throws IOException {
        String classPath = extractionClassPath;

        if (classPath == null) {
            synchronized (UnZipProcess.class) {
                if (extractionClassPath == null) {
                    extractionClassPath = copyExtractionClasses();
                }
                classPath = extractionClassPath;
            }
        }

        return classPath;
    }

    // On a packaged installation the bundles are in a folder that only the framework user can read (/opt/eclipse is
    // go-rwx), so the classes run by the extraction process are copied where the command user can read them
    private static String copyExtractionClasses() throws IOException {
        Path classesFolder = Files.createTempDirectory(EXTRACTION_CLASSES_PREFIX, ownerOnly());
        classesFolder.toFile().deleteOnExit();

        Path packageFolder = classesFolder;
        for (String packageName : ZipExtractor.class.getPackage().getName().split("\\.")) {
            packageFolder = packageFolder.resolve(packageName);
            Files.createDirectory(packageFolder);
            packageFolder.toFile().deleteOnExit();
        }

        for (Class<?> extractionClass : EXTRACTION_CLASSES) {
            Path target = packageFolder.resolve(extractionClass.getSimpleName() + ".class");
            copyClass(extractionClass, target);
            target.toFile().deleteOnExit();

            shareWithExtractionUser(target, false);
        }

        for (Path folder = packageFolder; folder.startsWith(classesFolder); folder = folder.getParent()) {
            shareWithExtractionUser(folder, true);
        }

        return classesFolder.toString();
    }

    private static void copyClass(Class<?> extractionClass, Path target) throws IOException {
        try (InputStream classFile = extractionClass.getResourceAsStream(extractionClass.getSimpleName() + ".class")) {
            if (classFile == null) {
                throw new IOException("Unable to read the class file of " + extractionClass.getName());
            }

            Files.copy(classFile, target);
        }
    }

    private static FileAttribute<?>[] ownerOnly() {
        if (!FileSystems.getDefault().supportedFileAttributeViews().contains("posix")) {
            return new FileAttribute<?>[0]; // As on Windows, where the temporary folder is private to the user already
        }

        return new FileAttribute<?>[] {
                PosixFilePermissions.asFileAttribute(PosixFilePermissions.fromString("rwx------")) };
    }

    private static void shareWithExtractionUser(Path path, boolean traversable) throws IOException {
        File file = path.toFile();

        if (!file.setReadable(true, false) || (traversable && !file.setExecutable(true, false))) {
            throw new IOException("Unable to make " + path + " readable by the user performing the extraction");
        }
    }

    private static String quote(String argument) {
        return "'" + argument.replace("'", "'\\''") + "'";
    }
}
