/*******************************************************************************
 * Copyright (c) 2011, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform

package org.eclipse.kura.util.zip;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.LinkOption;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.util.ArrayDeque;
import java.util.Deque;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;

/**
 * Extracts zip archives for {@link UnZip}, refusing entries that would be written outside the target folder and
 * archives that are too large.
 * <p>
 * This class must depend on the JDK only: {@link UnZipProcess} runs {@link #main(String[])} in a separate JVM whose
 * class path contains nothing but this bundle.
 */
final class ZipExtractor {

    private static final Logger logger = Logger.getLogger(ZipExtractor.class.getName());

    static final int EXTRACTION_TIMEOUT = 300; // Max duration of an extraction run by main, in seconds
    private static final int BUFFER = 1024;
    private static int tooBig = 0x6400000; // Max size of unzipped data, 100MB
    private static int tooMany = 1024; // Max number of files

    private ZipExtractor() {
        // Do nothing...
    }

    /**
     * Extracts in the given folder the archive read from the standard input. This is the entry point of the process
     * started by {@link UnZipProcess}.
     * <p>
     * The extraction fails when it takes longer than {@value #EXTRACTION_TIMEOUT} seconds and, as after any other
     * failure, the entries extracted so far are removed.
     *
     * @param args
     *            the folder the archive is extracted in
     */
    public static void main(String[] args) {
        if (args.length != 1) {
            System.err.println("Usage: " + ZipExtractor.class.getName()
                    + " <output folder> - the archive is read from the standard input");
            System.exit(1);
            return;
        }

        try {
            extract(new TimeLimitedInputStream(System.in, EXTRACTION_TIMEOUT, TimeUnit.SECONDS), args[0]);
        } catch (IOException | RuntimeException e) {
            System.err.println("Unable to extract the archive in " + args[0] + ": " + e.toString());
            System.exit(1);
        }
    }

    static void extract(InputStream archive, String outputFolder) throws IOException {
        unZipZipInputStream(new ZipInputStream(archive), outputFolder);
    }

    private static void unZipZipInputStream(ZipInputStream zis, String outFolder) throws IOException {
        File folder = new File(outFolder == null ? System.getProperty("user.dir") : outFolder);
        Deque<File> createdEntries = new ArrayDeque<>();

        try {
            createDirectories(folder, createdEntries);

            unZipEntries(zis, folder, createdEntries);
        } catch (IOException | RuntimeException e) {
            deleteCreatedEntries(createdEntries);
            throw e;
        } finally {
            zis.close();
        }
    }

    private static void unZipEntries(ZipInputStream zis, File folder, Deque<File> createdEntries) throws IOException {
        int entries = 0;
        long total = 0;

        ZipEntry ze = zis.getNextEntry();

        while (ze != null) {
            File newFile = getFile(entryPath(folder, ze), folder);

            if (ze.isDirectory()) {
                createDirectories(newFile, createdEntries);
            } else {
                total = writeEntry(zis, newFile, createdEntries, total);
                entries++;

                verifyLimits(entries, total);
            }

            ze = zis.getNextEntry();
        }

        zis.closeEntry();
    }

    private static long writeEntry(ZipInputStream zis, File newFile, Deque<File> createdEntries, long writtenSoFar)
            throws IOException {
        if (newFile.getParent() != null) {
            createDirectories(new File(newFile.getParent()), createdEntries);
        }

        if (!newFile.exists()) {
            createdEntries.push(newFile);
        }

        long total = writtenSoFar;
        try (OutputStream fos = Files.newOutputStream(newFile.toPath(),
                StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING,
                StandardOpenOption.WRITE, LinkOption.NOFOLLOW_LINKS)) {
            byte[] buffer = new byte[BUFFER];

            int len = zis.read(buffer);
            while (total + BUFFER <= tooBig && len > 0) {
                fos.write(buffer, 0, len);
                total += len;
                len = zis.read(buffer);
            }
            fos.flush();
        }

        return total;
    }

    private static void verifyLimits(int entries, long total) {
        if (entries > tooMany) {
            throw new IllegalStateException("Too many files to unzip.");
        }

        if (total + BUFFER > tooBig) {
            throw new IllegalStateException("File being unzipped is too big.");
        }
    }

    private static String entryPath(File folder, ZipEntry ze) {
        return new StringBuilder(folder.getPath()).append(File.separator).append(ze.getName()).toString();
    }

    private static void createDirectories(File directory, Deque<File> createdEntries) {
        if (directory == null || directory.exists()) {
            return;
        }

        createDirectories(directory.getParentFile(), createdEntries);

        if (directory.mkdir()) {
            createdEntries.push(directory);
        }
    }

    private static void deleteCreatedEntries(Deque<File> createdEntries) {
        while (!createdEntries.isEmpty()) {
            File entry = createdEntries.pop();
            try {
                Files.deleteIfExists(entry.toPath());
            } catch (IOException e) {
                logger.log(Level.WARNING, e,
                        () -> "Unable to delete " + entry + " while cleaning up a failed extraction");
            }
        }
    }

    private static File getFile(String expectedFilePath, File folder) throws IOException {
        String fileName = validateFileName(expectedFilePath, folder.getPath());
        return new File(fileName);
    }

    private static String validateFileName(String zipFileName, String intendedDir) throws IOException {
        final Path filePath = new File(zipFileName).getCanonicalFile().toPath();
        final Path intendedCanonicalPath = new File(intendedDir).getCanonicalFile().toPath();

        if (filePath.startsWith(intendedCanonicalPath)) {
            return filePath.toString();
        } else {
            throw new IOException("File is outside extraction target directory.");
        }
    }
}
