/*******************************************************************************
 * Copyright (c) 2025, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
/* Some portions generated by generative AI */
package org.eclipse.kura.linux.gpio.libgpiod2;

import java.io.IOException;

import org.eclipse.kura.gpio.KuraClosedDeviceException;
import org.eclipse.kura.gpio.KuraGPIODeviceException;
import org.eclipse.kura.gpio.KuraGPIODirection;
import org.eclipse.kura.gpio.KuraGPIOMode;
import org.eclipse.kura.gpio.KuraGPIOPin;
import org.eclipse.kura.gpio.KuraGPIOTrigger;
import org.eclipse.kura.gpio.KuraUnavailableDeviceException;
import org.eclipse.kura.linux.gpio.libgpiod.LibGpiodPin;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.sun.jna.Pointer;

/**
 * Implementation of KuraGPIOPin using libgpiod v2.2.x via JNA
 */
public class LibGpiodV2Pin extends LibGpiodPin implements KuraGPIOPin {

    private static final Logger logger = LoggerFactory.getLogger(LibGpiodV2Pin.class);

    private Pointer lineRequest;
    private Pointer lineConfig;
    private Pointer lineSettings;
    private Pointer requestConfig;
    private Pointer edgeEventBuffer;

    public LibGpiodV2Pin(String chipPath, int offset, KuraGPIODirection direction, KuraGPIOMode mode,
            KuraGPIOTrigger trigger, String pinName) {
        super(chipPath, offset, direction, mode, trigger, pinName);
    }

    @Override
    public void open() throws KuraGPIODeviceException, KuraUnavailableDeviceException, IOException {
        synchronized (this) {
            if (this.isOpen.get()) {
                return;
            }

            try {
                openGpioChip();
                createLineSettings();
                createlineConfig();
                createRequestConfig();
                requestLine();
                createEventBuffer();

                this.isOpen.set(true);

            } catch (Error e) {
                cleanup();
                throw new KuraUnavailableDeviceException(e, "Cannot open GPIO chip: " + this.chipPath);
            }
        }

    }

    private void createEventBuffer() throws KuraGPIODeviceException {
        try {
            // Create edge event buffer if we need event monitoring
            if (this.direction == KuraGPIODirection.INPUT && this.trigger != KuraGPIOTrigger.NONE) {
                this.edgeEventBuffer = LibGpiodV2NativeWrapper.getInstance().gpiod_edge_event_buffer_new(64);
                if (this.edgeEventBuffer == null) {
                    throw new KuraGPIODeviceException("Failed to create edge event buffer");
                }
            }
        } catch (Error e) {
            cleanup();
            throw new KuraGPIODeviceException(e, "Error creating edge event buffer");
        }
    }

    private void requestLine() throws KuraGPIODeviceException {
        try {
            this.lineRequest = LibGpiodV2NativeWrapper.getInstance().gpiod_chip_request_lines(this.chip,
                    this.requestConfig, this.lineConfig);
            if (this.lineRequest == null) {
                throw new KuraGPIODeviceException("Failed to request GPIO line " + this.offset);
            }
        } catch (Error e) {
            cleanup();
            throw new KuraGPIODeviceException(e, "Error requesting GPIO line");
        }
    }

    private void createRequestConfig() throws KuraGPIODeviceException {
        try {
            // Create request config
            this.requestConfig = LibGpiodV2NativeWrapper.getInstance().gpiod_request_config_new();
            if (this.requestConfig == null) {
                throw new KuraGPIODeviceException("Failed to create request config");
            }

            LibGpiodV2NativeWrapper.getInstance().gpiod_request_config_set_consumer(this.requestConfig, "KuraGPIOPin");
        } catch (Error e) {
            cleanup();
            throw new KuraGPIODeviceException(e, "Error creating request config");
        }
    }

    private void createlineConfig() throws KuraGPIODeviceException {
        try {
            // Create line config
            this.lineConfig = LibGpiodV2NativeWrapper.getInstance().gpiod_line_config_new();
            if (this.lineConfig == null) {
                throw new KuraGPIODeviceException("Failed to create line config");
            }

            // Add line settings to config
            int[] offsets = { this.offset };
            if (LibGpiodV2NativeWrapper.getInstance().gpiod_line_config_add_line_settings(this.lineConfig, offsets, 1,
                    this.lineSettings) < 0) {
                throw new KuraGPIODeviceException("Failed to add line settings to config");
            }
        } catch (Error e) {
            cleanup();
            throw new KuraGPIODeviceException(e, "Error creating line config");
        }
    }

    private void openGpioChip() throws KuraUnavailableDeviceException {
        try {
            this.chip = LibGpiodV2NativeWrapper.getInstance().gpiod_chip_open(this.chipPath);
            if (this.chip == null) {
                throw new KuraUnavailableDeviceException("Failed to open GPIO chip: " + this.chipPath);
            }
        } catch (Error e) {
            throw new KuraUnavailableDeviceException(e, "Cannot open GPIO chip: " + this.chipPath);
        }
    }

    private void createLineSettings() throws KuraGPIODeviceException {
        try {

            // Create line settings
            this.lineSettings = LibGpiodV2NativeWrapper.getInstance().gpiod_line_settings_new();
            if (this.lineSettings == null) {
                throw new KuraGPIODeviceException("Failed to create line settings");
            }

            // Configure direction
            int gpiodDirection = convertDirection(this.direction);
            if (LibGpiodV2NativeWrapper.getInstance().gpiod_line_settings_set_direction(this.lineSettings,
                    gpiodDirection) < 0) {
                throw new KuraGPIODeviceException("Failed to set line direction");
            }

            // Configure bias/mode
            int gpiodBias = convertModeToBias(this.mode);
            if (gpiodBias != -1 && LibGpiodV2NativeWrapper.getInstance().gpiod_line_settings_set_bias(this.lineSettings,
                    gpiodBias) < 0) {
                throw new KuraGPIODeviceException("Failed to set line bias");
            }

            // Configure drive for output modes
            if (this.direction == KuraGPIODirection.OUTPUT) {
                int gpiodDrive = convertModeToDrive(this.mode);
                if (gpiodDrive != -1 && LibGpiodV2NativeWrapper.getInstance()
                        .gpiod_line_settings_set_drive(this.lineSettings, gpiodDrive) < 0) {
                    throw new KuraGPIODeviceException("Failed to set line drive");
                }
            }

            // Configure edge detection for input with trigger
            if (this.direction == KuraGPIODirection.INPUT && this.trigger != KuraGPIOTrigger.NONE) {
                int gpiodEdge = convertTriggerToEdge(this.trigger);
                if (gpiodEdge != -1 && LibGpiodV2NativeWrapper.getInstance()
                        .gpiod_line_settings_set_edge_detection(this.lineSettings, gpiodEdge) < 0) {
                    throw new KuraGPIODeviceException("Failed to set edge detection");
                }
            }
        } catch (Error e) {
            cleanup();
            throw new KuraGPIODeviceException(e, "Error creating line settings");
        }
    }

    @Override
    public void close() throws IOException {
        synchronized (this) {
            if (!this.isOpen.get()) {
                return;
            }

            stopEventMonitoring();
            this.listeners.clear();

            try {
                cleanup();
                this.isOpen.set(false);
            } finally {
                this.isOpen.set(false);
            }
        }
    }

    private void cleanup() {

        try {
            if (this.edgeEventBuffer != null) {
                LibGpiodV2NativeWrapper.getInstance().gpiod_edge_event_buffer_free(this.edgeEventBuffer);
                this.edgeEventBuffer = null;
            }
        } catch (Error e) {
            logger.warn("Error freeing edge event buffer: {}", e.getMessage());
        }

        try {
            if (this.lineRequest != null) {
                LibGpiodV2NativeWrapper.getInstance().gpiod_line_request_release(this.lineRequest);
                this.lineRequest = null;
            }
        } catch (Error e) {
            logger.warn("Error releasing line request: {}", e.getMessage());
        }

        try {
            if (this.requestConfig != null) {
                LibGpiodV2NativeWrapper.getInstance().gpiod_request_config_free(this.requestConfig);
                this.requestConfig = null;
            }
        } catch (Error e) {
            logger.warn("Error freeing request config: {}", e.getMessage());
        }

        try {
            if (this.lineConfig != null) {
                LibGpiodV2NativeWrapper.getInstance().gpiod_line_config_free(this.lineConfig);
                this.lineConfig = null;
            }
        } catch (Error e) {
            logger.warn("Error freeing line config: {}", e.getMessage());
        }

        try {
            if (this.lineSettings != null) {
                LibGpiodV2NativeWrapper.getInstance().gpiod_line_settings_free(this.lineSettings);
                this.lineSettings = null;
            }
        } catch (Error e) {
            logger.warn("Error freeing line settings: {}", e.getMessage());
        }

        try {
            if (this.chip != null) {
                LibGpiodV2NativeWrapper.getInstance().gpiod_chip_close(this.chip);
                this.chip = null;
            }
        } catch (Error e) {
            logger.warn("Error closing GPIO chip: {}", e.getMessage());
        }
    }

    @Override
    public boolean getValue() throws KuraUnavailableDeviceException, KuraClosedDeviceException, IOException {
        if (!this.isOpen.get()) {
            throw new KuraClosedDeviceException(this.pinName);
        }

        int value = LibGpiodV2Native.GPIOD_LINE_VALUE_INACTIVE;
        try {
            value = LibGpiodV2NativeWrapper.getInstance().gpiod_line_request_get_value(this.lineRequest, this.offset);
            if (value < 0) {
                throw new IOException("Failed to read GPIO value");
            }
        } catch (Error e) {
            throw new IOException("Failed to read GPIO value", e);
        }
        return value == LibGpiodV2Native.GPIOD_LINE_VALUE_ACTIVE;
    }

    @Override
    public void setValue(boolean value) throws KuraUnavailableDeviceException, KuraClosedDeviceException, IOException {
        if (!this.isOpen.get()) {
            throw new KuraClosedDeviceException(this.pinName);
        }

        if (this.direction != KuraGPIODirection.OUTPUT) {
            throw new IOException("Cannot set value on input pin");
        }

        int gpioValue = value ? LibGpiodV2Native.GPIOD_LINE_VALUE_ACTIVE : LibGpiodV2Native.GPIOD_LINE_VALUE_INACTIVE;
        try {
            int exitCode = LibGpiodV2NativeWrapper.getInstance().gpiod_line_request_set_value(this.lineRequest,
                    this.offset, gpioValue);
            if (exitCode < 0) {
                throw new IOException("Failed to set GPIO value");
            }
        } catch (Error e) {
            throw new IOException("Failed to set GPIO value", e);
        }
    }

    protected void monitorEvents() {
        if (!this.isMonitoring.get() || !this.isOpen.get()) {
            return;
        }
        while (this.isMonitoring.get() && this.isOpen.get() && !Thread.currentThread().isInterrupted()) {
            manageEvents();
        }
    }

    private void manageEvents() {
        try {
            int waitResult = LibGpiodV2NativeWrapper.getInstance()
                    .gpiod_line_request_wait_edge_events(this.lineRequest, DEFAULT_TIMEOUT_SEC * 1_000_000_000L);

            if (waitResult > 0) {
                int numEvents = LibGpiodV2NativeWrapper.getInstance()
                        .gpiod_line_request_read_edge_events(this.lineRequest, this.edgeEventBuffer, 64);

                if (numEvents > 0) {
                    for (int i = 0; i < numEvents; i++) {
                        Pointer event = LibGpiodV2NativeWrapper.getInstance()
                                .gpiod_edge_event_buffer_get_event(this.edgeEventBuffer, i);
                        if (event != null) {
                            int eventType = LibGpiodV2NativeWrapper.getInstance()
                                    .gpiod_edge_event_get_event_type(event);
                            boolean newValue = eventType == LibGpiodV2Native.GPIOD_EDGE_EVENT_TYPE_RISING_EDGE;
                            synchronized (this.listeners) {
                                this.listeners.forEach(l -> l.pinStatusChange(newValue));
                            }
                        }
                    }
                }
            } else if (waitResult < 0) {
                logger.error("Error waiting for GPIO event: {}", waitResult);
            }
        } catch (Error e) {
            logger.error("Exception in GPIO event monitoring: {}", e.getMessage());
        }
    }

    // Helper methods to convert Kura enums to libgpiod constants
    private int convertDirection(KuraGPIODirection direction) {
        switch (direction) {
        case INPUT:
            return LibGpiodV2Native.GPIOD_LINE_DIRECTION_INPUT;
        case OUTPUT:
            return LibGpiodV2Native.GPIOD_LINE_DIRECTION_OUTPUT;
        default:
            return LibGpiodV2Native.GPIOD_LINE_DIRECTION_AS_IS;
        }
    }

    private int convertModeToBias(KuraGPIOMode mode) {
        switch (mode) {
        case INPUT_PULL_UP:
            return LibGpiodV2Native.GPIOD_LINE_BIAS_PULL_UP;
        case INPUT_PULL_DOWN:
            return LibGpiodV2Native.GPIOD_LINE_BIAS_PULL_DOWN;
        default:
            return -1;
        }
    }

    private int convertModeToDrive(KuraGPIOMode mode) {
        switch (mode) {
        case OUTPUT_OPEN_DRAIN:
            return LibGpiodV2Native.GPIOD_LINE_DRIVE_OPEN_DRAIN;
        case OUTPUT_PUSH_PULL:
            return LibGpiodV2Native.GPIOD_LINE_DRIVE_PUSH_PULL;
        default:
            return LibGpiodV2Native.GPIOD_LINE_DRIVE_PUSH_PULL;
        }
    }

    private int convertTriggerToEdge(KuraGPIOTrigger trigger) {
        switch (trigger) {
        case RAISING_EDGE:
            return LibGpiodV2Native.GPIOD_LINE_EDGE_RISING;
        case FALLING_EDGE:
            return LibGpiodV2Native.GPIOD_LINE_EDGE_FALLING;
        case BOTH_EDGES:
            return LibGpiodV2Native.GPIOD_LINE_EDGE_BOTH;
        default:
            return -1;
        }
    }

    public static int extractChipNumber(String chipName) {
        try {
            return Integer.parseInt(chipName.replaceAll("\\D", ""));
        } catch (NumberFormatException e) {
            return 0;
        }
    }

}