/*******************************************************************************
 * Copyright (c) 2025 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
/* Some portions generated by generative AI */
package org.eclipse.kura.linux.gpio.libgpiod2;

import java.io.File;

import org.eclipse.kura.gpio.GPIOService;
import org.eclipse.kura.gpio.KuraGPIODirection;
import org.eclipse.kura.gpio.KuraGPIOMode;
import org.eclipse.kura.gpio.KuraGPIOPin;
import org.eclipse.kura.gpio.KuraGPIOTrigger;
import org.eclipse.kura.linux.gpio.libgpiod.LibGpiodGPIOService;

import com.sun.jna.Pointer;

/**
 * Implementation of GPIOService using libgpiod v2.2.x
 *
 * This service manages GPIO pins across multiple GPIO chips and provides
 * pin discovery, name resolution, and pin lifecycle management.
 */
public class LibGpiodV2GPIOService extends LibGpiodGPIOService implements GPIOService {

    protected void discoverChipPins(String chipPath) {
        Pointer chip = null;
        Pointer chipInfo = null;

        try {
            chip = LibGpiodV2NativeWrapper.getInstance().gpiod_chip_open(chipPath);
            if (chip == null) {
                return;
            }

            chipInfo = LibGpiodV2NativeWrapper.getInstance().gpiod_chip_get_info(chip);
            if (chipInfo == null) {
                return;
            }

            long numLines = LibGpiodV2NativeWrapper.getInstance().gpiod_chip_info_get_num_lines(chipInfo);

            for (int offset = 0; offset < numLines; offset++) {
                readLineInfo(chipPath, chip, offset);
            }

        } finally {
            if (chipInfo != null) {
                LibGpiodV2NativeWrapper.getInstance().gpiod_chip_info_free(chipInfo);
            }
            if (chip != null) {
                LibGpiodV2NativeWrapper.getInstance().gpiod_chip_close(chip);
            }
        }
    }

    private void readLineInfo(String chipPath, Pointer chip, int offset) {
        Pointer lineInfo = null;
        try {
            lineInfo = LibGpiodV2NativeWrapper.getInstance().gpiod_chip_get_line_info(chip, offset);
            if (lineInfo != null) {
                String pinName = LibGpiodV2NativeWrapper.getInstance().gpiod_line_info_get_name(lineInfo);
                if (pinName == null || pinName.trim().isEmpty() || pinName.equals("-")) {
                    return;
                }
                // Calculate global pin number (chip_number * 1000 + offset)
                int chipNumber = LibGpiodV2Pin.extractChipNumber(new File(chipPath).getName());
                int globalPinNumber = chipNumber * 1000 + offset;

                this.availablePins.put(pinName, globalPinNumber);
            }

        } finally {
            if (lineInfo != null) {
                LibGpiodV2NativeWrapper.getInstance().gpiod_line_info_free(lineInfo);
            }
        }
    }

    protected boolean isValidPin(String chipPath, int offset) {
        Pointer chip = null;
        Pointer chipInfo = null;

        try {
            chip = LibGpiodV2NativeWrapper.getInstance().gpiod_chip_open(chipPath);
            if (chip == null) {
                return false;
            }

            chipInfo = LibGpiodV2NativeWrapper.getInstance().gpiod_chip_get_info(chip);
            if (chipInfo == null) {
                return false;
            }

            long numLines = LibGpiodV2NativeWrapper.getInstance().gpiod_chip_info_get_num_lines(chipInfo);
            return offset >= 0 && offset < numLines;

        } finally {
            if (chipInfo != null) {
                LibGpiodV2NativeWrapper.getInstance().gpiod_chip_info_free(chipInfo);
            }
            if (chip != null) {
                LibGpiodV2NativeWrapper.getInstance().gpiod_chip_close(chip);
            }
        }
    }

    protected KuraGPIOPin createPin(String chipPath, int offset, KuraGPIODirection direction, KuraGPIOMode mode,
            KuraGPIOTrigger trigger, String pinName) {
        return new LibGpiodV2Pin(chipPath, offset, direction, mode, trigger, pinName);
    }

}