/*******************************************************************************
 * Copyright (c) 2025 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
/* Some portions generated by generative AI */
package org.eclipse.kura.linux.gpio.libgpiod2;

import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.Pointer;

/**
 * JNA interface for libgpiod v2.2.x native library
 */
public interface LibGpiodV2Native extends Library {

    LibGpiodV2Native INSTANCE = Native.load("gpiod", LibGpiodV2Native.class);

    // GPIO line values
    int GPIOD_LINE_VALUE_ERROR = -1;
    int GPIOD_LINE_VALUE_INACTIVE = 0;
    int GPIOD_LINE_VALUE_ACTIVE = 1;

    // GPIO line directions
    int GPIOD_LINE_DIRECTION_AS_IS = 1;
    int GPIOD_LINE_DIRECTION_INPUT = 2;
    int GPIOD_LINE_DIRECTION_OUTPUT = 3;

    // GPIO line edge detection
    int GPIOD_LINE_EDGE_NONE = 1;
    int GPIOD_LINE_EDGE_RISING = 2;
    int GPIOD_LINE_EDGE_FALLING = 3;
    int GPIOD_LINE_EDGE_BOTH = 4;

    // GPIO line bias
    int GPIOD_LINE_BIAS_AS_IS = 1;
    int GPIOD_LINE_BIAS_UNKNOWN = 2;
    int GPIOD_LINE_BIAS_DISABLED = 3;
    int GPIOD_LINE_BIAS_PULL_UP = 4;
    int GPIOD_LINE_BIAS_PULL_DOWN = 5;

    // GPIO line drive
    int GPIOD_LINE_DRIVE_PUSH_PULL = 1;
    int GPIOD_LINE_DRIVE_OPEN_DRAIN = 2;
    int GPIOD_LINE_DRIVE_OPEN_SOURCE = 3;

    // GPIO line clock
    int GPIOD_LINE_CLOCK_MONOTONIC = 1;
    int GPIOD_LINE_CLOCK_REALTIME = 2;
    int GPIOD_LINE_CLOCK_HTE = 3;

    // Chip operations
    Pointer gpiod_chip_open(String path);

    void gpiod_chip_close(Pointer chip);

    Pointer gpiod_chip_get_info(Pointer chip);

    String gpiod_chip_get_path(Pointer chip);

    Pointer gpiod_chip_get_line_info(Pointer chip, int offset);

    Pointer gpiod_chip_watch_line_info(Pointer chip, int offset);

    int gpiod_chip_unwatch_line_info(Pointer chip, int offset);

    int gpiod_chip_get_fd(Pointer chip);

    int gpiod_chip_wait_info_event(Pointer chip, long timeout_ns);

    Pointer gpiod_chip_read_info_event(Pointer chip);

    int gpiod_chip_get_line_offset_from_name(Pointer chip, String name);

    Pointer gpiod_chip_request_lines(Pointer chip, Pointer req_cfg, Pointer line_cfg);

    // Chip info operations
    void gpiod_chip_info_free(Pointer info);

    String gpiod_chip_info_get_name(Pointer info);

    String gpiod_chip_info_get_label(Pointer info);

    long gpiod_chip_info_get_num_lines(Pointer info);

    // Line info operations
    void gpiod_line_info_free(Pointer info);

    Pointer gpiod_line_info_copy(Pointer info);

    int gpiod_line_info_get_offset(Pointer info);

    String gpiod_line_info_get_name(Pointer info);

    boolean gpiod_line_info_is_used(Pointer info);

    String gpiod_line_info_get_consumer(Pointer info);

    int gpiod_line_info_get_direction(Pointer info);

    int gpiod_line_info_get_edge_detection(Pointer info);

    int gpiod_line_info_get_bias(Pointer info);

    int gpiod_line_info_get_drive(Pointer info);

    boolean gpiod_line_info_is_active_low(Pointer info);

    boolean gpiod_line_info_is_debounced(Pointer info);

    long gpiod_line_info_get_debounce_period_us(Pointer info);

    int gpiod_line_info_get_event_clock(Pointer info);

    // Line settings operations
    Pointer gpiod_line_settings_new();

    void gpiod_line_settings_free(Pointer settings);

    void gpiod_line_settings_reset(Pointer settings);

    Pointer gpiod_line_settings_copy(Pointer settings);

    int gpiod_line_settings_set_direction(Pointer settings, int direction);

    int gpiod_line_settings_get_direction(Pointer settings);

    int gpiod_line_settings_set_edge_detection(Pointer settings, int edge);

    int gpiod_line_settings_get_edge_detection(Pointer settings);

    int gpiod_line_settings_set_bias(Pointer settings, int bias);

    int gpiod_line_settings_get_bias(Pointer settings);

    int gpiod_line_settings_set_drive(Pointer settings, int drive);

    int gpiod_line_settings_get_drive(Pointer settings);

    void gpiod_line_settings_set_active_low(Pointer settings, boolean active_low);

    boolean gpiod_line_settings_get_active_low(Pointer settings);

    void gpiod_line_settings_set_debounce_period_us(Pointer settings, long period);

    long gpiod_line_settings_get_debounce_period_us(Pointer settings);

    int gpiod_line_settings_set_event_clock(Pointer settings, int event_clock);

    int gpiod_line_settings_get_event_clock(Pointer settings);

    int gpiod_line_settings_set_output_value(Pointer settings, int value);

    int gpiod_line_settings_get_output_value(Pointer settings);

    // Line config operations
    Pointer gpiod_line_config_new();

    void gpiod_line_config_free(Pointer config);

    void gpiod_line_config_reset(Pointer config);

    int gpiod_line_config_add_line_settings(Pointer config, int[] offsets, long num_offsets, Pointer settings);

    Pointer gpiod_line_config_get_line_settings(Pointer config, int offset);

    int gpiod_line_config_set_output_values(Pointer config, int[] values, long num_values);

    long gpiod_line_config_get_num_configured_offsets(Pointer config);

    long gpiod_line_config_get_configured_offsets(Pointer config, int[] offsets, long max_offsets);

    // Request config operations
    Pointer gpiod_request_config_new();

    void gpiod_request_config_free(Pointer config);

    void gpiod_request_config_set_consumer(Pointer config, String consumer);

    String gpiod_request_config_get_consumer(Pointer config);

    void gpiod_request_config_set_event_buffer_size(Pointer config, long event_buffer_size);

    long gpiod_request_config_get_event_buffer_size(Pointer config);

    // Line request operations
    void gpiod_line_request_release(Pointer request);

    String gpiod_line_request_get_chip_name(Pointer request);

    long gpiod_line_request_get_num_requested_lines(Pointer request);

    long gpiod_line_request_get_requested_offsets(Pointer request, int[] offsets, long max_offsets);

    int gpiod_line_request_get_value(Pointer request, int offset);

    int gpiod_line_request_get_values_subset(Pointer request, long num_values, int[] offsets, int[] values);

    int gpiod_line_request_get_values(Pointer request, int[] values);

    int gpiod_line_request_set_value(Pointer request, int offset, int value);

    int gpiod_line_request_set_values_subset(Pointer request, long num_values, int[] offsets, int[] values);

    int gpiod_line_request_set_values(Pointer request, int[] values);

    int gpiod_line_request_reconfigure_lines(Pointer request, Pointer config);

    int gpiod_line_request_get_fd(Pointer request);

    int gpiod_line_request_wait_edge_events(Pointer request, long timeout_ns);

    int gpiod_line_request_read_edge_events(Pointer request, Pointer buffer, long max_events);

    // Edge event operations
    void gpiod_edge_event_free(Pointer event);

    Pointer gpiod_edge_event_copy(Pointer event);

    int gpiod_edge_event_get_event_type(Pointer event);

    long gpiod_edge_event_get_timestamp_ns(Pointer event);

    int gpiod_edge_event_get_line_offset(Pointer event);

    long gpiod_edge_event_get_global_seqno(Pointer event);

    long gpiod_edge_event_get_line_seqno(Pointer event);

    // Edge event buffer operations
    Pointer gpiod_edge_event_buffer_new(long capacity);

    long gpiod_edge_event_buffer_get_capacity(Pointer buffer);

    void gpiod_edge_event_buffer_free(Pointer buffer);

    Pointer gpiod_edge_event_buffer_get_event(Pointer buffer, long index);

    long gpiod_edge_event_buffer_get_num_events(Pointer buffer);

    // Misc operations
    boolean gpiod_is_gpiochip_device(String path);

    String gpiod_api_version();
}