/*******************************************************************************
 * Copyright (c) 2025 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
/* Some portions generated by generative AI */
package org.eclipse.kura.linux.gpio.libgpiod2;

import java.io.IOException;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.atomic.AtomicBoolean;

import org.eclipse.kura.gpio.KuraClosedDeviceException;
import org.eclipse.kura.gpio.KuraGPIODeviceException;
import org.eclipse.kura.gpio.KuraGPIODirection;
import org.eclipse.kura.gpio.KuraGPIOMode;
import org.eclipse.kura.gpio.KuraGPIOPin;
import org.eclipse.kura.gpio.KuraGPIOTrigger;
import org.eclipse.kura.gpio.KuraUnavailableDeviceException;
import org.eclipse.kura.gpio.PinStatusListener;

import com.sun.jna.Pointer;

/**
 * Implementation of KuraGPIOPin using libgpiod v2.2.x via JNA
 */
public class LibGpiodV2Pin implements KuraGPIOPin {

    private final String chipPath;
    private final int offset;
    private final KuraGPIODirection direction;
    private final KuraGPIOMode mode;
    private final KuraGPIOTrigger trigger;
    private final String name;

    private Pointer chip;
    private Pointer lineRequest;
    private Pointer lineConfig;
    private Pointer lineSettings;
    private Pointer requestConfig;
    private Pointer edgeEventBuffer;

    private final AtomicBoolean isOpen = new AtomicBoolean(false);
    private final CopyOnWriteArrayList<PinStatusListener> listeners = new CopyOnWriteArrayList<>();
    private ExecutorService eventExecutor;
    private volatile boolean monitoring = false;

    public LibGpiodV2Pin(String chipPath, int offset, KuraGPIODirection direction, KuraGPIOMode mode,
            KuraGPIOTrigger trigger, String name) {
        this.chipPath = chipPath;
        this.offset = offset;
        this.direction = direction;
        this.mode = mode;
        this.trigger = trigger;
        this.name = name != null ? name : "GPIO_" + offset;
    }

    @Override
    public void open() throws KuraGPIODeviceException, KuraUnavailableDeviceException, IOException {
        if (isOpen.get()) {
            return;
        }

        try {
            // Open the GPIO chip
            chip = LibGpiodV2Native.INSTANCE.gpiod_chip_open(chipPath);
            if (chip == null) {
                throw new KuraUnavailableDeviceException("Failed to open GPIO chip: " + chipPath);
            }

            // Create line settings
            lineSettings = LibGpiodV2Native.INSTANCE.gpiod_line_settings_new();
            if (lineSettings == null) {
                throw new KuraGPIODeviceException("Failed to create line settings");
            }

            // Configure direction
            int gpiodDirection = convertDirection(direction);
            if (LibGpiodV2Native.INSTANCE.gpiod_line_settings_set_direction(lineSettings, gpiodDirection) < 0) {
                throw new KuraGPIODeviceException("Failed to set line direction");
            }

            // Configure bias/mode
            int gpiodBias = convertModeToBias(mode);
            if (gpiodBias != -1) {
                if (LibGpiodV2Native.INSTANCE.gpiod_line_settings_set_bias(lineSettings, gpiodBias) < 0) {
                    throw new KuraGPIODeviceException("Failed to set line bias");
                }
            }

            // Configure drive for output modes
            if (direction == KuraGPIODirection.OUTPUT) {
                int gpiodDrive = convertModeToDrive(mode);
                if (gpiodDrive != -1) {
                    if (LibGpiodV2Native.INSTANCE.gpiod_line_settings_set_drive(lineSettings, gpiodDrive) < 0) {
                        throw new KuraGPIODeviceException("Failed to set line drive");
                    }
                }
            }

            // Configure edge detection for input with trigger
            if (direction == KuraGPIODirection.INPUT && trigger != KuraGPIOTrigger.NONE) {
                int gpiodEdge = convertTriggerToEdge(trigger);
                if (gpiodEdge != -1) {
                    if (LibGpiodV2Native.INSTANCE.gpiod_line_settings_set_edge_detection(lineSettings, gpiodEdge) < 0) {
                        throw new KuraGPIODeviceException("Failed to set edge detection");
                    }
                }
            }

            // Create line config
            lineConfig = LibGpiodV2Native.INSTANCE.gpiod_line_config_new();
            if (lineConfig == null) {
                throw new KuraGPIODeviceException("Failed to create line config");
            }

            // Add line settings to config
            int[] offsets = { offset };
            if (LibGpiodV2Native.INSTANCE.gpiod_line_config_add_line_settings(lineConfig, offsets, 1,
                    lineSettings) < 0) {
                throw new KuraGPIODeviceException("Failed to add line settings to config");
            }

            // Create request config
            requestConfig = LibGpiodV2Native.INSTANCE.gpiod_request_config_new();
            if (requestConfig == null) {
                throw new KuraGPIODeviceException("Failed to create request config");
            }

            LibGpiodV2Native.INSTANCE.gpiod_request_config_set_consumer(requestConfig, "KuraGPIOPin");

            // Request the line
            lineRequest = LibGpiodV2Native.INSTANCE.gpiod_chip_request_lines(chip, requestConfig, lineConfig);
            if (lineRequest == null) {
                throw new KuraGPIODeviceException("Failed to request GPIO line " + offset);
            }

            // Create edge event buffer if we need event monitoring
            if (direction == KuraGPIODirection.INPUT && trigger != KuraGPIOTrigger.NONE) {
                edgeEventBuffer = LibGpiodV2Native.INSTANCE.gpiod_edge_event_buffer_new(64);
                if (edgeEventBuffer == null) {
                    throw new KuraGPIODeviceException("Failed to create edge event buffer");
                }
            }

            isOpen.set(true);

        } catch (Exception e) {
            cleanup();
            if (e instanceof KuraGPIODeviceException || e instanceof KuraUnavailableDeviceException) {
                throw e;
            }
            throw new KuraGPIODeviceException(e, "Failed to open GPIO pin: " + e.getMessage());
        }
    }

    @Override
    public void close() throws IOException {
        if (!isOpen.get()) {
            return;
        }

        stopEventMonitoring();
        cleanup();
        isOpen.set(false);
    }

    private void cleanup() {
        if (edgeEventBuffer != null) {
            LibGpiodV2Native.INSTANCE.gpiod_edge_event_buffer_free(edgeEventBuffer);
            edgeEventBuffer = null;
        }

        if (lineRequest != null) {
            LibGpiodV2Native.INSTANCE.gpiod_line_request_release(lineRequest);
            lineRequest = null;
        }

        if (requestConfig != null) {
            LibGpiodV2Native.INSTANCE.gpiod_request_config_free(requestConfig);
            requestConfig = null;
        }

        if (lineConfig != null) {
            LibGpiodV2Native.INSTANCE.gpiod_line_config_free(lineConfig);
            lineConfig = null;
        }

        if (lineSettings != null) {
            LibGpiodV2Native.INSTANCE.gpiod_line_settings_free(lineSettings);
            lineSettings = null;
        }

        if (chip != null) {
            LibGpiodV2Native.INSTANCE.gpiod_chip_close(chip);
            chip = null;
        }
    }

    @Override
    public void setValue(boolean active) throws KuraUnavailableDeviceException, KuraClosedDeviceException, IOException {
        if (!isOpen.get()) {
            throw new KuraClosedDeviceException("GPIO pin is not open");
        }

        if (direction != KuraGPIODirection.OUTPUT) {
            throw new IOException("Cannot set value on input pin");
        }

        int value = active ? LibGpiodV2Native.GPIOD_LINE_VALUE_ACTIVE : LibGpiodV2Native.GPIOD_LINE_VALUE_INACTIVE;

        if (LibGpiodV2Native.INSTANCE.gpiod_line_request_set_value(lineRequest, offset, value) < 0) {
            throw new IOException("Failed to set GPIO pin value");
        }
    }

    @Override
    public boolean getValue() throws KuraUnavailableDeviceException, KuraClosedDeviceException, IOException {
        if (!isOpen.get()) {
            throw new KuraClosedDeviceException("GPIO pin is not open");
        }

        int value = LibGpiodV2Native.INSTANCE.gpiod_line_request_get_value(lineRequest, offset);

        if (value == LibGpiodV2Native.GPIOD_LINE_VALUE_ERROR) {
            throw new IOException("Failed to read GPIO pin value");
        }

        return value == LibGpiodV2Native.GPIOD_LINE_VALUE_ACTIVE;
    }

    @Override
    public void addPinStatusListener(PinStatusListener listener) throws KuraClosedDeviceException, IOException {
        if (!isOpen.get()) {
            throw new KuraClosedDeviceException("GPIO pin is not open");
        }

        if (direction != KuraGPIODirection.INPUT) {
            // Silently ignore as per API specification
            return;
        }

        listeners.add(listener);

        // Start event monitoring if not already started
        if (!monitoring && trigger != KuraGPIOTrigger.NONE) {
            startEventMonitoring();
        }
    }

    @Override
    public void removePinStatusListener(PinStatusListener listener) throws KuraClosedDeviceException, IOException {
        if (!isOpen.get()) {
            throw new KuraClosedDeviceException("GPIO pin is not open");
        }

        listeners.remove(listener);

        // Stop event monitoring if no more listeners
        if (listeners.isEmpty() && monitoring) {
            stopEventMonitoring();
        }
    }

    private void startEventMonitoring() {
        if (edgeEventBuffer == null || monitoring) {
            return;
        }

        monitoring = true;
        eventExecutor = Executors.newSingleThreadExecutor(r -> {
            Thread t = new Thread(r, "GPIO-Event-Monitor-" + offset);
            t.setDaemon(true);
            return t;
        });

        eventExecutor.submit(() -> {
            while (monitoring && !Thread.currentThread().isInterrupted()) {
                try {
                    // Wait for edge events with 1 second timeout
                    int result = LibGpiodV2Native.INSTANCE.gpiod_line_request_wait_edge_events(lineRequest,
                            1_000_000_000L);

                    if (result > 0) {
                        // Read events
                        int numEvents = LibGpiodV2Native.INSTANCE.gpiod_line_request_read_edge_events(lineRequest,
                                edgeEventBuffer, 64);

                        if (numEvents > 0) {
                            // Process events
                            for (int i = 0; i < numEvents; i++) {
                                Pointer event = LibGpiodV2Native.INSTANCE
                                        .gpiod_edge_event_buffer_get_event(edgeEventBuffer, i);
                                if (event != null) {
                                    int eventType = LibGpiodV2Native.INSTANCE.gpiod_edge_event_get_event_type(event);
                                    boolean newValue = (eventType == 1); // GPIOD_EDGE_EVENT_RISING_EDGE

                                    // Notify all listeners
                                    for (PinStatusListener listener : listeners) {
                                        try {
                                            listener.pinStatusChange(newValue);
                                        } catch (Exception e) {
                                            // Ignore listener exceptions
                                        }
                                    }
                                }
                            }
                        }
                    }
                } catch (Exception e) {
                    // Ignore and continue monitoring
                }
            }
        });
    }

    private void stopEventMonitoring() {
        monitoring = false;
        if (eventExecutor != null) {
            eventExecutor.shutdown();
            eventExecutor = null;
        }
    }

    @Override
    public KuraGPIODirection getDirection() {
        return direction;
    }

    @Override
    public KuraGPIOMode getMode() {
        return mode;
    }

    @Override
    public KuraGPIOTrigger getTrigger() {
        return trigger;
    }

    @Override
    public String getName() {
        return name;
    }

    @Override
    public int getIndex() {
        return offset;
    }

    @Override
    public boolean isOpen() {
        return isOpen.get();
    }

    // Helper methods to convert Kura enums to libgpiod constants

    private int convertDirection(KuraGPIODirection direction) {
        switch (direction) {
        case INPUT:
            return LibGpiodV2Native.GPIOD_LINE_DIRECTION_INPUT;
        case OUTPUT:
            return LibGpiodV2Native.GPIOD_LINE_DIRECTION_OUTPUT;
        default:
            return LibGpiodV2Native.GPIOD_LINE_DIRECTION_AS_IS;
        }
    }

    private int convertModeToBias(KuraGPIOMode mode) {
        switch (mode) {
        case INPUT_PULL_UP:
            return LibGpiodV2Native.GPIOD_LINE_BIAS_PULL_UP;
        case INPUT_PULL_DOWN:
            return LibGpiodV2Native.GPIOD_LINE_BIAS_PULL_DOWN;
        default:
            return -1; // No bias setting
        }
    }

    private int convertModeToDrive(KuraGPIOMode mode) {
        switch (mode) {
        case OUTPUT_OPEN_DRAIN:
            return LibGpiodV2Native.GPIOD_LINE_DRIVE_OPEN_DRAIN;
        case OUTPUT_PUSH_PULL:
            return LibGpiodV2Native.GPIOD_LINE_DRIVE_PUSH_PULL;
        default:
            return LibGpiodV2Native.GPIOD_LINE_DRIVE_PUSH_PULL; // Default
        }
    }

    private int convertTriggerToEdge(KuraGPIOTrigger trigger) {
        switch (trigger) {
        case RAISING_EDGE:
            return LibGpiodV2Native.GPIOD_LINE_EDGE_RISING;
        case FALLING_EDGE:
            return LibGpiodV2Native.GPIOD_LINE_EDGE_FALLING;
        case BOTH_EDGES:
            return LibGpiodV2Native.GPIOD_LINE_EDGE_BOTH;
        default:
            return -1; // No edge detection
        }
    }
}